### PR TITLE
fix: SliceIterator to drop a max of Int.MaxValue

### LINKED ISSUE #12822: Iterator.drop susceptible to arithmetic overflow
## Reproduction steps

Scala version: 2.13.11

```scala
println(List(1).iterator.drop(1).drop(Int.MaxValue).toList)
```

## Problem
prints
```scala
List(1)
```

### PR DESCRIPTION
**Pull request by yzia2000**
resolves [#12822](https://github.com/scala/bug/issues/12822)

### CODE REVIEW

**Comment by yzia2000** [comment]
Either this solution or we don't put a limit on the drop count eg by making the variable something of type BigInt

**Comment by yzia2000** [comment]
@scala/collections pointers with this one?

**Comment by jxnu-liguobin** [comment]
lgtm

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by yzia2000** [comment]
woah this is quite dumb. Just noticed the fatal flaw with math.max here

**Comment by yzia2000** [comment]
Updated to use min and not max. max would basically set the dropping count to Int.MaxValue everytime

**Comment by som-snytt** [comment]
Supposedly, some combination of `collections-laws` and scalacheck tests would have caught the bad conditional.

Maybe the PR needs more tests. (More than one.)

**Comment by yzia2000** [comment]
> Supposedly, some combination of `collections-laws` and scalacheck tests would have caught the bad conditional.
> 
> Maybe the PR needs more tests. (More than one.)

Yeah fair point. Kinda surprised the suite passed at such a radical bug. 

EDIT: No one of the tests did fail which makes sense

File: test/junit/scala/collection/IteratorTest.scala [hunk 1]
```diff
@@ -213,6 +213,10 @@ class IteratorTest {
     assertEquals(it.drop(1).next(), it.drop(1).drop(1).next())
   }
 
+  @Test def dropDoesNotOverflow(): Unit = {
+    assertEquals(List(1, 2, 3).iterator.drop(1).drop(Int.MaxValue).drop(1).toList.isEmpty, true)
```
Comment (He-Pin) [inline test/junit/scala/collection/IteratorTest.scala:217]: List(1, 2, 3).iterator.drop(1).drop(Int.MaxValue) 
List(1, 2, 3).iterator.drop(Int.MaxValue).drop(1) 
List(1, 2, 3).reverseIterator.drop(Int.MaxValue).drop(1)
List(1, 2, 3).reverseIterator.drop(1).drop(Int.MaxValue).drop(1)
All those should be empty iterator, how about add more tests?

and `List(3) ::: List(1, 2, 3).reverseIterator.drop(1)` should be `List(3,2,1)`

File: src/library/scala/collection/Iterator.scala [hunk 2]
```diff
@@ -1259,7 +1259,7 @@ object Iterator extends IterableFactory[Iterator] {
         else adjustedBound min (until - lo)   // keep lesser bound
       if (rest == 0) empty
       else {
-        dropping += lo
+        dropping = math.min(Int.MaxValue.toLong, lo.toLong + dropping.toLong).toInt
```
Comment (He-Pin) [inline src/library/scala/collection/Iterator.scala]:
```scala
val sum = lo + dropping 
dropping = if (sum < 0) Int.MaxValue else sum
``` 
how about this?

or 
```scala
dropping = if (lo + dropping < 0) Int.MaxValue else lo + dropping
```

File: test/junit/scala/collection/IteratorTest.scala (hunk 1 above)
Comment (yzia2000) [reply test/junit/scala/collection/IteratorTest.scala:217]: Yeah the reverseIterator test is a good addition just in case although both should be treated the same way since the reverseIterator is a property of the List collection

File: src/library/scala/collection/Iterator.scala (hunk 2 above)
Comment (yzia2000) [reply src/library/scala/collection/Iterator.scala]: I don't see the difference

File: test/junit/scala/collection/IteratorTest.scala (hunk 1 above)
Comment (yzia2000) [reply test/junit/scala/collection/IteratorTest.scala:217]: The last one doesn't seem relevant to Iterator though considering the appending is happening in the List side and when its passed to iterator its all the same

Comment (yzia2000) [reply test/junit/scala/collection/IteratorTest.scala:217]: Added requested tests

File: src/library/scala/collection/Iterator.scala (hunk 2 above)
Comment (He-Pin) [reply src/library/scala/collection/Iterator.scala]: the math.min is a method call

**Review by He-Pin — CHANGES_REQUESTED** [review]
I would like to avoid the method call of `math.min` and `toLong`

File: src/library/scala/collection/Iterator.scala (hunk 2 above)
Comment (yzia2000) [reply src/library/scala/collection/Iterator.scala]: The Long conversion is required I think. Simply checking whether the int has overflowed might not work given something like this

```
.drop(IntMax).drop(IntMax) and so on
```
 Because that would turn the variable back to positive though unlikely

Comment (He-Pin) [reply src/library/scala/collection/Iterator.scala]: Have you tested it? I think it will not reach the positive again.
```scala
        dropping = {
          val sum = dropping + lo
          if (sum < 0) Int.MaxValue else sum
        }
```

Comment (yzia2000) [reply src/library/scala/collection/Iterator.scala]: Ah yes missed the part where we set it to maxvalue. Yeah that works

**Comment by yzia2000** [comment]
> I would like to avoid the method call of `math.min` and `toLong`

There are max/min functions and even toLong used in the same file. Is the concern here memory/performance?

File: src/library/scala/collection/Iterator.scala (hunk 2 above)
Comment (yzia2000) [reply src/library/scala/collection/Iterator.scala]: Anyways, updated as mentioned

**Review by He-Pin — APPROVED** [review]
lgtm

File: src/library/scala/collection/Iterator.scala [hunk 3]
```diff
@@ -1259,7 +1259,10 @@ object Iterator extends IterableFactory[Iterator] {
         else adjustedBound min (until - lo)   // keep lesser bound
       if (rest == 0) empty
       else {
-        dropping += lo
+        dropping = {
+          val sum = dropping + lo
+          if (sum < 0) Int.MaxValue else sum
+        }
```
Comment (He-Pin) [inline src/library/scala/collection/Iterator.scala:1265]: the `sum` is not a good name,maybe you can find another one.

**Comment by He-Pin** [comment]
@som-snytt This should be labled as `collection`

File: src/library/scala/collection/Iterator.scala (hunk 3 above)
Comment (yzia2000) [reply src/library/scala/collection/Iterator.scala:1265]: Its scoped down to dropping only which makes the choice of name quite unnecessary

**Comment by ansvonwa** [comment]
I don't mean to bikeshed here, but why not use the smallest, most simple and imho most readable fix?
Just insert one line
```scala
if (dropping < 0) dropping = Int.MaxValue
```
after the original `+=` line.
I think there is no need here for any casts, method calls, inner scopes or local variables, which all add visual clutter when reading the code.

**Comment by He-Pin** [comment]
@ansvonwa Do you mean:
```scala
dropping = dropping + lo
if (dropping < 0) dropping = Int.MaxValue
```
I think we can then do 
```scala
 if (dropping += lo < 0) {
    dropping = Int.MaxValue
 }
```

@yzia2000 what your option here.

**Comment by yzia2000** [comment]
> @ansvonwa Do you mean:
> 
> ```scala
> dropping = dropping + lo
> if (dropping < 0) dropping = Int.MaxValue
> ```
> 
> I think we can then do
> 
> ```scala
>  if (dropping += lo < 0) {
>     dropping = Int.MaxValue
>  }
> ```
> 
> @yzia2000 what your option here.

Tbh current solution and this one look barely different in my eyes and I would be hesitant to introduce changes unless there is a best practices from the maintainers out there compelling to do so.
I did change the initial solution with min and toLong to suggested mainly because the toLong in hindsight is an unnecessary increase in the size of the variable, though benign.

**Comment by SethTisue** [comment]
@ansvonwa wdyt?

File: src/library/scala/collection/Iterator.scala [hunk 4]
```diff
@@ -1259,7 +1259,10 @@ object Iterator extends IterableFactory[Iterator] {
         else adjustedBound min (until - lo)   // keep lesser bound
       if (rest == 0) empty
       else {
-        dropping += lo
+        dropping = {
+          val sum = dropping + lo
+          if (sum < 0) Int.MaxValue else sum
```
Comment (lrytz) [inline src/library/scala/collection/Iterator.scala:1264]: Setting `dropping = Int.MaxValue` on overflow is not correct

```
scala> Iterator.from(0).drop(1).drop(Int.MaxValue).take(5).toList
val res3: List[Int] = List(2147483647, -2147483648, -2147483647, -2147483646, -2147483645)

scala> Iterator.from(0).drop(100).drop(Int.MaxValue).take(5).toList
val res4: List[Int] = List(2147483647, -2147483648, -2147483647, -2147483646, -2147483645)
```

Comment (lrytz) [reply src/library/scala/collection/Iterator.scala:1264]: Though maybe that's OK? Generally iterators can have more than `Int.MaxValue` elements, but once we start using operations like `drop` that have an `Int` parameter, maybe it's too difficult / not necessary dealing with all overflow conditions?

Comment (ansvonwa) [reply src/library/scala/collection/Iterator.scala:1264]: That's also what I thought. As our "size type" for all the collections in the std lib is always `Int`, I think this is fine. Imho everything below the size of `Int.MaxValue` has to work, but everything above is a bonus.

**Review by lrytz — APPROVED** [review]
