### PR TITLE
Tighter condition for nowarn a single patvar

### LINKED ISSUE #902: 2.13.17 regression (?): Scalafix failing in community build
reproducible locally using dbuild (also probably reproducible outside dbuild if you locally publish scalameta?)

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/2616/artifact/logs/scalafix-build.log

```
[info] - scala/test/removeUnused/RemoveUnusedPatternVars.scala *** FAILED *** (98 milliseconds)
```

```diff
--- obtained
+++ expected
@@ -385,3 +385,3 @@
   def f(v: (Int, (Boolean, String))): Int = v match {
-    case (i, v @ (_, _)) => i
+    case (i, (_, _)) => i
   }
```

I haven't bisected it but it's in this range:

```diff
-nightly=2.13.17-bin-483b4ee
+nightly=2.13.17-bin-c392ee5
```

eyeballing that range, https://github.com/scala/scala/pull/11032 looks like a possible culprit (@som-snytt)

### PR DESCRIPTION
**Pull request by som-snytt**
Address the question how liberal the exclusion for unused patvars should be.

This commit proposes: a single patvar named after the selector is always OK.

That is analogous to "narrow a var via a type pattern", `(x: Option[_]) match { case x: Some[_] => }`.

This "ergonomics" respects "cut and paste" where patterns that don't have a "canonical" patvar name may represent "extract a canonically narrower value". It still requires the patvar name to "align" with the selector name.

```Scala
person match {
  case PreferredName(person) =>
  case _ => // no preference
}
```
The patvar is unused, but the match expression is allowed as something cut and pasted, so it's annoying to require "fixing up" just to pass a lint. The previous allowance is for case class element names, `case Person(firstName, lastName) =>`.

At a `case`, it's not necessary to walk the pattern twice: it will process `Apply` before recursing into children, so child `Bind` will see the attachment.

Fixes scala/scala-dev#902

### CODE REVIEW

**Comment by som-snytt** [comment]
The other lesson is to pay better attention when lrytz raises his eyebrows during code review.

**Comment by som-snytt** [comment]
I'm glad they're making a biopic about working on 2.13 knowing there will be no 2.14.

image

@lrytz @SethTisue

File: src/reflect/scala/reflect/internal/Trees.scala [hunk 1]
```diff
@@ -632,7 +632,8 @@ trait Trees extends api.Trees {
   case class UnApply(fun: Tree, args: List[Tree])
        extends TermTree with UnApplyApi {
     override def transform(transformer: Transformer): Tree =
-      transformer.treeCopy.UnApply(this, transformer.transform(fun), transformer.transformTrees(args)) // bq: see test/.../unapplyContexts2.scala
+      transformer.treeCopy.UnApply(this, transformer.transform(fun), transformer.transformTrees(args))
+        // bq: see test/.../unapplyContexts2.scala
```
Comment (lrytz) [inline src/reflect/scala/reflect/internal/Trees.scala:636]: btw, i think `bq` is `@burakemir` :)

**Review by lrytz — APPROVED** [review]
nice! makes sense.
