### PR TITLE
Fix compiler crash involving pattern match with literal type

### LINKED ISSUE #12127: "Error while emitting" with bind to literal in match and literal type result
## reproduction steps

```scala
scala 2.13.3> def f(x: Any): "hi" = x match { case s @ "hi" => s }
error: Error while emitting <console>
value s
```

## problem

Compiles normally when result type is `String` (as is inferred).

Trace under `-Vdebug`:
```
java.util.NoSuchElementException: value s
        at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:505)
        at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:504)
        at scala.collection.mutable.AnyRefMap.apply(AnyRefMap.scala:205)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$locals$.load(BCodeSkelBuilder.scala:428)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:361)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.$anonfun$genLoadLabelArguments$4(BCodeBodyBuilder.scala:912)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadLabelArguments(BCodeBodyBuilder.scala:912)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:640)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:303)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadIf(BCodeBodyBuilder.scala:205)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:286)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLabelDef(BCodeBodyBuilder.scala:483)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:266)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:87)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:803)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:373)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:641)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:673)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:546)
```

Noticed at https://github.com/scala/bug/issues/12119

### PR DESCRIPTION
**Pull request by som-snytt**
In `case s @ "" => s`, it may be dubious to elide
the binding. With an expected literal type,
the case body was incorrectly `s.type`, so that it was not adapted to constant type. This commit
fixes the latter issue only, especially since
-Wunused does not warn about terms of constant type anyway (because they were probably inlined): `case "" => ""`.

Fixes scala/bug#12127

### CODE REVIEW

**Comment by som-snytt** [comment]
The change also enables inlining of the field value in the RHS of an accessor:
```
private[this] val x: Int(42) = 42
def x: Int(42) = 42  // inlined this.x
```
The RHS also gets an OriginalTreeAttachment. There is no change to the generated code. (The field is elided during fields.)

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 1]
```diff
@@ -641,7 +641,7 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
         // A module reference in a pattern has type Foo.type, not "object Foo"
         narrowIf(checkStable(tree), sym.isModuleNotMethod)
       else if (isModuleTypedExpr)                     // (3)
-        narrowIf(tree, condition = true)
+        narrowIf(tree, condition = !sym.isConstant)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: Maybe `!isConstantType(tree.tpe)` is somewhat more direct, as `narrowIf` is calling `tree.setType`?

**Review by lrytz — APPROVED** [review]

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: You're probably right. I forget that `tree.symbol.tpe` is different from `tree.tpe`, so I'm not sure why I reached for the symbol test, except that first I added the condition to `isModuleTypedExpr`. `#3` is about the tree type.

**Comment by som-snytt** [comment]
Rebased and added a commit that moves the constant test into `isStableContext`, which is what flipped when the `pt` changed from `String` to `"hello, world"`. The difference is seen in `isNarrowable` (the technical term for it). The method is used in a few places, so the improvement may ameliorate or deteriorate in other subtle ways.

Unwound the old refactor in `stabilize` so that the perspicacious reader need not perspire to see the code paths.

In particular, on `UnstableTreeError`, the code must not set the tree type. Using good old `if/else if` shows the necessary exclusion.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 2]
```diff
@@ -1055,7 +1045,7 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
         if (sym != null && !context.unit.isJava && sym.isDeprecated)
           context.deprecationWarning(tree.pos, sym)
         tree match {
-          case Literal(`value`) => tree
+          case Literal(`value`) /*| Bind(_, _)*/ => tree
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala:1048]: Not obvious whether `case s @ ""` getting squashed is surprising to tooling.

**Comment by SethTisue** [comment]
> stabiliszing

is this... Hungarian notation?

**Comment by som-snytt** [comment]
@SethTisue https://fosstodon.org/@som_snytt/113306593431459494

**Review by lrytz — APPROVED** [review]
That looks right 👍
