### PR TITLE
Retain constant value types when inferring result types

### LINKED ISSUE #12830: Inferred override type of final val
## Reproduction steps

Scala version: 2.13.12

```scala
➜  snips cat narrows.scala

class C {
  def i: Int = 42
}
object D extends C {
  override final val i = 27
}
object Test {
  def f: 27 = D.i
}
```

## Problem

Compiles under 2.13 but not under `-Xsource:3` because of the inferred type for `D.i`.

Dotty correctly infers `27`. Probably Scala 2 inadvertently widens when picking the "narrow" intersection.

Noticed at https://github.com/scala/scala/pull/10439#issuecomment-1637074874

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12830

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/Namers.scala [hunk 1]
```diff
@@ -1140,6 +1140,7 @@ trait Namers extends MethodSynthesis {
       tree.tpt.defineType {
         val inferOverridden = currentRun.isScala3 &&
           !pt.isWildcard && pt != NoType && !pt.isErroneous &&
+          !(tree.isInstanceOf[ValDef] && tree.symbol.isFinal && isConstantType(rhsTpe)) &&
```
Comment (joroKr21) [inline src/compiler/scala/tools/nsc/typechecker/Namers.scala:1143]: Does it matter that it's a val?

Comment (lrytz) [reply src/compiler/scala/tools/nsc/typechecker/Namers.scala:1143]: `final val` without explicit type is a secret handshake to not widen, that doesn't apply to `def` (https://scala-lang.org/files/archive/spec/2.13/04-basic-declarations-and-definitions.html#value-declarations-and-definitions)

**Review by lrytz — APPROVED** [review]
