### PR TITLE
Try harder to find Enum, warn for Java statics

### LINKED ISSUE #1211: when mixing Scala and Java, scalac doesn't recognize unqualified name of inherited enum
compilation fails if all source files are passed to scalac:
```scala
  ~/newbug> cat I.java 
interface I { public enum E { E1 } }
  ~/newbug> cat J.java 
class J implements I {
	public void foo(E e) { }
}
  ~/newbug> cat S.scala 
object S { (new J).foo(null) }
  ~/newbug> ~/scala/dists/latest/bin/scalac I.java J.java S.scala 
J.java:2: error: not found: type E
	public void foo(E e) { }
                        ^
one error found
```

but succeeds if javac is run first:
```scala
  ~/newbug> javac *.java
  ~/newbug> ~/scala/dists/latest/bin/scalac S.scala
```

the bug is very easy to work around by writing out the name more fully:
```scala
  ~/newbug> cat J.java 
class J implements I {
	public void foo(I.E e) { }
}
  ~/newbug> ~/scala/dists/latest/bin/scalac I.java J.java S.scala
```

I'm running r15746.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#1211

We have a nice warning if you try to select a Java static, assuming they are inherited.

For inherited enums, retry lookup of term name as enum type, and on error, look up in any base class from Java for static to warn about.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 1]
```diff
@@ -1333,7 +1333,15 @@ trait Contexts { self: Analyzer =>
               val pre2 = companionModule.typeOfThis
               val found = pre2.decl(name).filter(qualifies)
               found match {
-                case NoSymbol => NoJavaMemberFound
+                case NoSymbol =>
+                  if (name.isTermName) {
+                    val found = pre2.decl(name.toTypeName).filter(qualifies)
+                    if (found.isJavaEnum)
+                      (pre2, found)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala]: I worry that returning a type member for a term name lookup could leak. Is that why you narrowed it to enums, to limit the scope?

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala]: I just wanted my use case to work in the middle of the night. At the other end, in typer, it does the converse. Maybe the retry should be up the stack. I did think maybe it's ok here for enum, however, the extra code is incurred for many failures, so it may be relatively expensive. 

Also I will add tests to probe the behavior.

**Comment by som-snytt** [comment]
Worth remembering that if error construction is expensive, it's expensive to throw away if forced during weird speculative typing.

This just retries when erroring.

**Review by lrytz — APPROVED** [review]
Nice, thank you!
