### PR TITLE
Nuance import selector errors in Namers

### LINKED ISSUE #12813: Double import error message thinks it's a rename import
## Reproduction steps

Scala version: 2.13.11

```
Welcome to Scala 2.13.11 (OpenJDK 64-Bit Server VM, Java 17.0.7).
Type in expressions for evaluation. Or try :help.

scala> object O { val a = 1 }
object O

scala> import O.{a, a}
              ^
       error: a is renamed twice
                 ^
```

## Problem

It's not renamed at all

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12813

The real error is trying to introduce the same identifier twice. Give a different message if a rename is involved.

Do the syntax checking in parser.

Fix missing error:
```
➜  ~ scala -Xsource:3
Welcome to Scala 2.13.11 (OpenJDK 64-Bit Server VM, Java 20.0.1).
Type in expressions for evaluation. Or try :help.

scala> object X { val x = 42 }
object X

scala> import X.{given, x, *}
import X.{x, _}

scala>
```

### CODE REVIEW

**Comment by lrytz** [comment]
test.files.pos.import-future.scala

```
                sbt.ForkMain$ForkError: java.lang.NullPointerException: null
	at scala.reflect.internal.Scopes$Scope.lookupEntry(Scopes.scala:353)
```

File: test/files/pos/import-future.scala [hunk 1]
```diff
@@ -26,7 +26,7 @@ class C {
 
 object starring {
 
-  import scala.concurrent.{*, given}, duration.{given, Duration as D, *}, ExecutionContext.Implicits.*
+  import scala.concurrent.{*, given}, duration.{Duration as D, given, *}, ExecutionContext.Implicits.*
```
Comment (som-snytt) [inline test/files/pos/import-future.scala:29]: check this syntax

**Comment by lrytz** [comment]
Ping @scala/collections for review.

**Comment by lrytz** [comment]
Ups, not this one, sorry...

**Review by lrytz — APPROVED** [review]
👍 nice cleanup!
