### PR TITLE
Avoid completableFuture.asScala crash for MinimalStage

### LINKED ISSUE #12918: FutureConverters fails for MinimalStage
Reported by @nmarton-da (https://github.com/scala/scala/pull/10181/files#r1385648137)

```scala
scala> import scala.jdk.FutureConverters._
import scala.jdk.FutureConverters._

scala> import java.util.concurrent.CompletableFuture
import java.util.concurrent.CompletableFuture

scala> CompletableFuture.completedStage(42).asScala
java.lang.UnsupportedOperationException
  at java.base/java.util.concurrent.CompletableFuture$MinimalStage.isDone(CompletableFuture.java:2976)
  at scala.jdk.javaapi.FutureConverters$.asScala(FutureConverters.scala:73)
  at scala.jdk.FutureConverters$CompletionStageOps$.asScala$extension(FutureConverters.scala:41)
  ... 30 elided
```

 JDK 11 has MinimalStage which is a CompletableFuture (also CompletionStage), with UnsupportedOperationException in lot of method bodies (like isDone). Regressed in https://github.com/scala/scala/pull/10181.
 
See also https://github.com/Kotlin/kotlinx.coroutines/issues/2456, https://github.com/playframework/playframework/issues/11991

### PR DESCRIPTION
**Pull request by lrytz**
`CompletableFuture.completedStage` creates a `MinimalStage` instance which extends `CompletableFuture` and overrides most methods with `UnsupportedOperationException`.

Calling `toCompletableFuture` on it creates a fresh `CompletableFuture`.

Fixes https://github.com/scala/bug/issues/12918.

### CODE REVIEW

**Comment by He-Pin** [comment]
I will fix it in other repo this weekend

**Comment by He-Pin** [comment]
I was missed this @DougLea

File: src/library/scala/jdk/javaapi/FutureConverters.scala [hunk 1]
```diff
@@ -66,11 +66,15 @@ object FutureConverters {
     * @return a Scala Future that represents the CompletionStage's completion
     */
   def asScala[T](cs: CompletionStage[T]): Future[T] = {
+    object Comfy {
+      // scala/bug#12918
+      def unapply(cf: CompletableFuture[T]) = Some(cf.toCompletableFuture)
```
Comment (He-Pin) [inline src/library/scala/jdk/javaapi/FutureConverters.scala]: Will this create a `Some` object?

Comment (lrytz) [reply src/library/scala/jdk/javaapi/FutureConverters.scala]: Yes

Comment (He-Pin) [reply src/library/scala/jdk/javaapi/FutureConverters.scala]: If we add some think like Akka's OptionVal we can then do it with allocation free.
Or we can just rewrite the this part of the code.

Comment (He-Pin) [reply src/library/scala/jdk/javaapi/FutureConverters.scala]: What about 
```scala
        val cf = cs.toCompletableFuture
        if (cf.isDone && !cf.isCompletedExceptionally) {
          val p = new P[T](cs)
          p.tryComplete(Success(cf.join()))
          p.future
        } else {
          val p = new P[T](cs)
          cs.handle(p)
          p.future
        }
```

Comment (lrytz) [reply src/library/scala/jdk/javaapi/FutureConverters.scala]: Pushed a version without extractor.

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by som-snytt** [comment]
Thanks for the opportunity to read up on these interfaces I'd managed to avoid all these years.

The issue is exactly this concluding line of JavaDoc:

> This interface does not define methods for initially creating, forcibly completing normally or exceptionally, probing completion status or results, or awaiting completion of a stage. Implementations of CompletionStage may provide means of achieving such effects, as appropriate. Method toCompletableFuture enables interoperability among different implementations of this interface by providing a common conversion type.

That is obscure, but says don't call `isDone`. If you want to do these things, use `toCompletableFuture`. The phrase "common conversion type" is not meaningful to me, even though the context is conversions. But presumably it means what you already discovered, that there may be various `CompletionStage` implementations of variable abilities, and convert to a CF for interoperability.

The other "object lesson" (pun alert) is why did we ever think it's OK to downcast to runtime types? On the one hand, we can despise Java's penchant for implementing an interface by throwing unsupported operations, such as `iterator.remove` when it's not supported by a collection. On the other hand, we can only trust the (compile time) type we're given as a value parameter. The exception is probing for the private wrapper type.

**Review by som-snytt — APPROVED** [review]
Despite the hiccup, it was pleasant to see the previous optimization and the benchmarking.

My last question is why do we downcast at all if I can always call `CompletionStage#toCompetableFuture#isDone`? Any completion stage can tell me (via the "common conversion type") whether a value is available. 

Since it's only an optimization of sorts, approving forthwith.

**Comment by lrytz** [comment]
> My last question is why do we downcast at all if I can always call `CompletionStage#toCompetableFuture#isDone`? Any completion stage can tell me (via the "common conversion type") whether a value is available.

Maybe `toCompetableFuture` is more likely to be a no-op if we only call it on `CompletableFuture`s, so there could be a performance benefit? I don't know.
