### PR TITLE
Fix some cases of `instanceOf[X.type]`: rewrite TypeApply's type arguments to use explicit outer references

### LINKED ISSUE #12312: Trying to access the this of another class with instanceOf singleton
## reproduction steps

using Scala 2.13.4,

```scala
scala> object X
object X

scala> X.isInstanceOf[X.type]
error: Error while emitting <console>
assertion failed:
  Trying to access the this of another class: tree.symbol = class $read, class symbol = class iw compilation unit: <console>
     while compiling: <console>
        during phase: jvm
     library version: version 2.13.4
    compiler version: version 2.13.4
  reconstructed args: -deprecation -feature -Wconf:cat=feature:w -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws

  last tree to typer: Literal(Constant(type))
       tree position: <unknown>
            tree tpe: Class(classOf[])
              symbol: null
           call site: constructor $iw in package $line4

== Source file context for tree position ==
```

or
```scala
package $line4 {
  sealed class $read extends _root_.scala.Serializable {
    sealed class $iw extends _root_.java.io.Serializable {
      object X
    };
    val $iw = new $iw
  };
  object $read extends scala.AnyRef {
    val INSTANCE = new $read
  }
}
package $line5 {
  sealed class $read extends _root_.scala.Serializable {
    val $line4$read: $line4.$read.INSTANCE.type = $line4.$read.INSTANCE;
    import $line4$read.$iw.X;
    sealed class $iw extends _root_.java.io.Serializable {
      val res1 = X.isInstanceOf[X.type]
    };
    val $iw = new $iw
  };
  object $read extends scala.AnyRef {
    val INSTANCE = new $read
  }
}
```

## problem

Expected the compiler to be less assertive.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes https://github.com/scala/bug/issues/12312

### CODE REVIEW

File: test/files/pos/t12312.scala [hunk 1]
```diff
@@ -0,0 +1,8 @@
+class A { object X }
+
+class C {
+  val a = new A; import a.X
+  class D {
+    def res1() = X.isInstanceOf[X.type]
+  }
```
Comment (retronym) [inline test/files/pos/t12312.scala]: Worth converting this to a run test to check that the semantics of the `instanceOf` check are correct. Maybe its covered by another test, but not necessarily.

Also worth testing something with multiple outer-pointer hops.

```scala
class A { object X }

object Test {
  val a, b = new A; import a.X
  class D {
    def isInstanceOf_aX(z: AnyRef) = z.isInstanceOf[X.type]
    class E {
      def isInstanceOf_aX(z: AnyRef) = z.isInstanceOf[X.type]
    }
  }
  def main(args: Array[String]): Unit = {
    val d = new D()
    assert(d.isInstanceOf_aX(a.X))
    assert(!d.isInstanceOf_aX(b.X))
    assert(!d.isInstanceOf_aX(new Object))

    val e = new d.E()
    assert(e.isInstanceOf_aX(a.X))
    assert(!e.isInstanceOf_aX(b.X))
    assert(!e.isInstanceOf_aX(new Object))
  }
}
```

The doubly nested case seems gives a `ClassCastException` as this PR stands:

```
Welcome to Scala 2.13.6-20210419-144201-bb7bea5 (OpenJDK 64-Bit Server VM, Java 1.8.0_272).
Type in expressions for evaluation. Or try :help.

...

scala> Test.main(null)
java.lang.ClassCastException: Test$D cannot be cast to Test$
  at Test$D$E.isInstanceOf_aX(<console>:8)
  at Test$.main(<console>:18)
  ... 32 elided
```

**Review by retronym — CHANGES_REQUESTED** [review]
Nice to see such a long standing bug ready to be eradicated.

But first needs the expanded test case and a fix for the doubly nested case.

File: src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala [hunk 2]
```diff
@@ -488,6 +488,31 @@ abstract class ExplicitOuter extends InfoTransform
...
+                tpe.mapOver(typeMap)
+              case tp => tp.mapOver(typeMap)
+            }
+          }
+          val fun2   = transform(fun)
+          val targs2 = targs.mapConserve { targ0 =>
+            val targ    = transform(targ0)
+            val targTp  = targ.tpe
+            val targTp2 = rewriteTypeToExplicitOuter(targTp.dealias)
+            if (targTp eq targTp2) targ else transform(TypeTree(targTp2).setOriginal(targ))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala]: Why do you recurse here?

Comment (dwijnand) [reply src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala]: Good question.  I tried to look around and I couldn't tell if I should recurse before or after my change.  Looks like here I opted for both.  And the reason for recursing is for completeness?  I.e. to avoid the top level transform not seeing this TypeTree (in some future case TypeTree).  Is there a rule of thumb on this?

Comment (lrytz) [reply src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala]: Here you create a `TypeTree`, does the transform do anything to that tree? I'd guess not. Also, the `targ` tree from with the type is derived is already transformed.

**Review by retronym — APPROVED** [review]

**Comment by SethTisue** [comment]
this caused a regression in the community build: https://github.com/scala/community-build/pull/1400#issuecomment-833748877
