### PR TITLE
Override checks between Java-defined members only for mixins

### LINKED ISSUE #12394: Too much vs too little override checking for Java-defined inherited members
(Related to https://github.com/scala/bug/issues/12380)

The following Java class is valid, Java doesn't have the same linearization rules as Scala. In class D, the final method `D.m` overrides the default method `J.m`.

```java
package p;

public class A {
  public static interface I {
    default int m() { return 1; }
  }

  public static interface J extends I {
    @Override default int m() { return 2; }
  }

  public static class C implements I {
    @Override public final int m() { return 3; }
  }

  public static class D extends C implements J { }
}
```

-----

The Scala class `S1` is also valid, it should compile:

```scala
class S1 extends p.A.D
```

Compiling `S1`
  - with 2.13.1 gives a compile-time error: `cannot override final member` because the compiler checks if `J.m` is a valid override of `C.m`, according to Scala's lineariaztion
  - with 2.13.2 - 2.13.5 compiles successfully, thanks to https://github.com/scala/scala/pull/8643, which started skipping override checks for Java-defined members
    - however, https://github.com/scala/scala/pull/8643 went too far, as explained in https://github.com/scala/scala/pull/9615/commits/be57ce90a6630e0c49e43fda9a649cd132123e2e
  - current 2.13.x is back to 2.13.1 behavior, which is wrong and caused a community build failure: https://github.com/scala/scala/pull/9615#issuecomment-838907483

-----

The Scala class `S2` is invalid, it should not compile:

```scala
class S2 extends p.A.C with p.A.J
```

Compiling `S2`
  - is correctly rejected with 2.13.1
  - incorrectly succeeds with 2.13.2 - 2.13.5, leading to a `java.lang.VerifyError: class S2 overrides final method p.A$C.m()I`. This is because a bridge method is generated invoke `J.m`, which is necessary for Scala's linearization semantics.
  - is again rejected with current 2.13.x

### PR DESCRIPTION
**Pull request by lrytz**
Override checking between Java-defined members can and should be
skipped: javac will do the checks anyway, and applying Scala's rules
can lead to false errors.

However, when mixing in a Java interface into a Scala class, default
methods in the interface have to be checked according to Scala's
rules, because Scala linearization applies in this case.

Fixes https://github.com/scala/bug/issues/12394

### CODE REVIEW

**Comment by lrytz** [comment]
@smarter this is already fixed in dotty - do you know how?

File: src/compiler/scala/tools/nsc/transform/OverridingPairs.scala [hunk 1]
```diff
@@ -53,6 +53,19 @@ abstract class OverridingPairs extends SymbolPairs {
...
     ) // TODO we don't call exclude(high), should we?
+
+    override protected def skipOwnerPair(lowClass: Symbol, highClass: Symbol): Boolean = {
+      // Two Java-defined methods can be skipped in most cases, as javac will check the overrides; skipping is
+      // actually necessary to avoid false errors, as Java doesn't have the Scala's linearization rules. However, when
+      // a Java interface is mixed into a Scala class, mixed-in default methods need to go through override checking.
+      // See scala/bug#12394.
+      lowClass.isJavaDefined && highClass.isJavaDefined && {
+        !lowClass.isJavaInterface && !highClass.isJavaInterface || {
+          val interfaceMixins = base.info.parents.collect { case i if i.typeSymbol.isJavaInterface => i.typeSymbol }
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/transform/OverridingPairs.scala]: Meh, this is not enough, a Scala trait mixin that extends a Java interface needs to get the same check

**Comment by SethTisue** [comment]
I verified just now that this does fix sttp.

We should merge this fairly promptly and then re-run the entire community build, but let's allow another 8 hours or so for feedback before merging.

I read through the whole twisty sequence of tickets and PRs leading up to this, and I looked through the fix, and I didn't come up with anything new to say. The fix seems sensible and is narrowly targeted. There may well be more bugs out along this long tail, but if the (now larger) set of tests we have are passing and the repos we know about are green, then clearly this is progress.

**Review by SethTisue — APPROVED** [review]

**Review by dwijnand — APPROVED** [review]
^

**Comment by smarter** [comment]
> this is already fixed in dotty - do you know how?

Not sure, this might just be because our override checking is incomplete compared to scala 2: https://github.com/lampepfl/dotty/issues/7551
