### PR TITLE
Split the SliceIterator on drop overflow [ci: last-only]

### LINKED ISSUE #13052: Iterator.drop cannot handle (very) large iterators
I sometimes use very large iterators (more than `Int.MaxValue` elements) to check that students don't expend in memory when they shouldn't. However, some iterator methods, like `drop`, don't work correctly on those:

```scala
class TenBillionIterator extends AbstractIterator[Long]:
   private var n        = 0L
   def hasNext: Boolean = n < 10_000_000_000L
   def next: Long       = { val r = n; n += 1L; r }

val i: Iterator[Long] =
   TenBillionIterator()
      .drop(1_000_000_000)
      .drop(1_000_000_000)
      .drop(1_000_000_000)

i.next() // 2147483647, should be 3000000000
```

Interestingly, `++` (`concat`) does work:

```scala
val j = TenBillionIterator() ++ TenBillionIterator()
var n = 13_000_000_000L
while n > 0 do
   n -= 1L
   j.next()

j.next() // 3000000000, correctly
```

I understand it's a somewhat corner case, but the documentation is silent about such a limitation and the behavior caught me off-guard (especially because `++` worked and things only fell apart when I started using `drop`). I don't know if this is a documentation issue or if some code needs fixing (maybe just a matter of making `dropping` a `Long` in class `SliceIterator`).

(Note that `Iterator.range(0L, 10_000_000_000L)` also doesn't work, but it's a different issue.)

I'm using Scala 3.5.2, but this is a Scala 2 collection problem.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#13052

When the drop count overflows, concatenate a slice with max drop count with a slice dropping the difference.

On hasNext, the first slice drains its drop count, then the second drops before delivering elements of the underlying iterator.

~Evaluate the underlying iterator on overflow of drop count.~

~"Real" iterators will override some behavior for efficiency, as desired.~

Previously, drop count was capped at `Int.MaxValue`.

### CODE REVIEW

**Comment by SethTisue** [comment]
@scala/collections

File: test/junit/scala/collection/IteratorTest.scala [hunk 1]
```diff
@@ -221,6 +221,14 @@ class IteratorTest {
     assertSameElements(List(3) ++ List(1, 2, 3).reverseIterator.drop(1), List(3, 2, 1))
   }
 
+  @Test def `drop does overflow t13052`: Unit = {
+    var counter = 0L
+    val it = Iterator.continually(counter.tap(_ => counter += 1))
+    val n = 1_000_000_000
+    val dropped = it.drop(n).drop(n).drop(n)
+    assertEquals(3L * n, dropped.next())
+  }
```
Comment (som-snytt) [inline test/junit/scala/collection/IteratorTest.scala:231]: This is 4-5 secs on my old machine. It would normally go in a "slow test" group. (`AtomicLong` is 4x longer, albeit atomic.)

**Comment by som-snytt** [comment]
Rebased. I tried adding test argument
```
s"--exclude-categories=${List("scala.SlowTests").mkString(",")}",
```
but with the annotation on a test method
```
@Test @Category(Array(classOf[scala.SlowTests])) def `drop does overflow t13052`: Unit
```
it excludes all tests for that test class, which is not helpful.

The useful behavior would be that
```
junit/testOnly scala.collection.IteratorTest
```
would skip only the one slow test method.

I will leave the test as-is, since the suite takes a couple of minutes to run; a few seconds doesn't matter to DX.

In a thousand years, they will analyze our era and note that we drove SUVs and wrote tests that heated the atmosphere.

**Comment by Ichoran** [comment]
Is it a bad idea to switch to a `Long` of elements-to-drop instead?

**Comment by som-snytt** [comment]
Long count was suggested on the ticket, but it doesn't seem principled for a niche case which should never happen in non-student code.

The old commit comment was that the iterator avoids daisy-chaining, so this restores daisy-chaining for the edge case of huge drop counts.

In other news, not sure what broke on rebase.

Edit: OOM on a routine junit test. It uses a Thread, does it keep GC from making progress on a constrained CI VM?

**Comment by som-snytt** [comment]
The answer is that the test has contending threads, one to reset a map value, the other to double it in length, but the doubler results in exponential increase. That is visible in normal local test; not sure what is wrong with the other thread in test, whether it dies outright or is starved in that environment. I'll open a separate PR, probably to retire the test, which does not prove anything.

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
squash?
