### PR TITLE
Completions: exclude top-level class symbols with a `$`

### LINKED ISSUE #905: metals tests failing in community build
log: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk21-integrate-community-build/2307/artifact/logs/metals-build.log

Metals commit: https://github.com/scalameta/metals/commits/565323c2f5dc8f2d4f43aeded7799958fddfab96

Example log
```
[metals] [info] tests.pc.CompletionSuite.fuzzy1_2.13.17-bin-f4ca74b started
[metals] [error] ==> X tests.pc.CompletionSuite.fuzzy1_2.13.17-bin-f4ca74b  0.219s munit.ComparisonFailException: tests/cross/src/test/scala/tests/pc/CompletionSuite.scala:357
[metals] [error] 356:
[metals] [error] 357:  check(
[metals] [error] 358:    "fuzzy1",
[metals] [error] diff assertion failed
[metals] [error] => Obtained
[metals] [error] ProcessBuilder java.lang
[metals] [error] ProcessBuilder$Redirect java.lang
[metals] [error] ProcessBuilder$Redirect$Type java.lang
[metals] [error] ProcessBuilder - scala.sys.process
[metals] [error] CertPathBuilder - java.security.cert
[metals] [error] CertPathBuilderSpi - java.security.cert
[metals] [error] ProcessBuilderImpl - scala.sys.process
[metals] [error] CertPathBuilderResult - java.security.cert
[metals] [error] PKIXBuilderParameters - java.security.cert
[metals] [error] PooledConnectionBuilder - javax.sql
[metals] [error] CertPathBuilderException - java.security.cert
[metals] [error] PKIXCertPathBuilderResult - java.security.cert
[metals] [error] => Diff (- expected, + obtained)
[metals] [error]  ProcessBuilder java.lang
[metals] [error] +ProcessBuilder$Redirect java.lang
[metals] [error] +ProcessBuilder$Redirect$Type java.lang
[metals] [error]  ProcessBuilder - scala.sys.process
```

Looks like https://github.com/scala/scala/pull/11024.

The other failures in the log (search for `ComparisonFailException`) all seem to be about patterns somehow. Not immediately obvious what could have caused these

```
[metals] [error] ==> X tests.pc.CompletionCaseSuite.trailing-block_2.13.17-bin-f4ca74b  0.105s munit.ComparisonFailException: tests/cross/src/test/scala/tests/pc/CompletionCaseSuite.scala:103
[metals] [error] 102:
[metals] [error] 103:  check(
[metals] [error] 104:    "trailing-block",
[metals] [error] Obtained empty output!
[metals] [error] => Expected:
[metals] [error] case None => scala
[metals] [error] case Some(value) => scala
```

### PR DESCRIPTION
**Pull request by lrytz**
Completions were changed recently to include symbols with a `$` in their name (PR 11024).

In SymbolLoaders, the compiler creates a class symbol for every `.class` file on the classpath. This results in many class symbols that we don't want to see in completions: inner classes, specialized classes, module classes.

This commit excludes non-completed top-level symbols that have a `$` in their name.

Fixes https://github.com/scala/scala-dev/issues/905

### CODE REVIEW

**Comment by lrytz** [comment]
Review by harpocrates

**Comment by lrytz** [comment]
Review by @harpocrates

File: src/interactive/scala/tools/nsc/interactive/Global.scala [hunk 1]
```diff
@@ -1007,9 +1007,16 @@ class Global(settings: Settings, _reporter: Reporter, projectName: String = "")
       (!implicitlyAdded || m.implicitlyAdded)
 
     def add(sym: Symbol, pre: Type, implicitlyAdded: Boolean)(toMember: (Symbol, Type) => M): Unit = {
+      // cannot exclude `isSynthetic` because, eg, synthetic case class members
+      def exclude =
+        sym.isError || !sym.hasRawInfo ||
+          sym.isArtifact || sym.isDefaultGetter || sym.isMixinConstructor ||
+          // Exclude top-level class symbols with a `$`. The compiler creates a symbol for every `.class` file, but there
+          // are many that we don't want in completions (inner / module / specialized classes). See scala/scala-dev#905.
+          sym.isTopLevel && !sym.rawInfo.isComplete && sym.name.decodedName.containsChar('$')
```
Comment (tgodzik) [inline src/interactive/scala/tools/nsc/interactive/Global.scala:1016]: Is there no other way? Mostly curious if this might be less efficient than checking for a specific flag about the symbol. Can we instead check if it's the unwanted type of symbol?

**Review by tgodzik — APPROVED** [review]
One question from me, but should be good ok to merge anyway

File: src/interactive/scala/tools/nsc/interactive/Global.scala (hunk 1 above)
Comment (lrytz) [reply src/interactive/scala/tools/nsc/interactive/Global.scala:1016]: We were doing the `name contains` check before (https://github.com/scala/scala/pull/11024/files removed it, which caused the issue I'm fixing now), so it should be fine™️

Because the symbol is not yet completed we don't know much about it. Running the type completer would certainly be a lot slower.
