### PR TITLE
Fix VectorMap Bug [scala/bug#11933]

### LINKED ISSUE #11933: VectorMap#{remove, init, tail} still broken.
## reproduction steps
related BugReport #11100, #11218, #11220

When remove last element (most recentry updated element) and update element, Iterator does not work.
```scala
scala> VectorMap(1 -> "a", 2 -> "b").removed(2).updated(3, "c")
res0: scala.collection.immutable.VectorMap[Int,String] = VectorMap(1 -> a)
```
When remove last element and update element, remove may not work. 
```scala
scala> VectorMap(1 -> "a", 2 -> "b").removed(2).updated(3, "c").removed(3)
java.lang.IllegalStateException: kinless tombstone found in prefix: 3
  at scala.collection.immutable.VectorMap.removed(VectorMap.scala:151)
  ... 28 elided
```

When remove last element. init does not work.
```scala
scala> VectorMap(1 -> "a", 2 -> "b", 3 -> "c").removed(3).init
java.util.NoSuchElementException: key not found: 2
  at scala.collection.immutable.Map$Map1.apply(Map.scala:240)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:112)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:84)
  at scala.collection.Iterator$SliceIterator.next(Iterator.scala:1219)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
  at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1170)
  at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1162)
  at scala.collection.AbstractIterator.addString(Iterator.scala:1274)
  at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1112)
  at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1110)
  at scala.collection.AbstractIterator.mkString(Iterator.scala:1274)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:234)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:243)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:251)
  at .$print$lzycompute(<synthetic>:8)
  ... 26 elided
```

When get tail. Attempt to remove wrong position.
```scala
scala> VectorMap(1 -> "a", 2 -> "b", 3 -> "c").tail.removed(3)
java.lang.IndexOutOfBoundsException: 2 is out of bounds (min 0, max 2)
  at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:193)
  at scala.collection.immutable.Vector.apply(Vector.scala:183)
  at scala.collection.immutable.VectorMap.scala$collection$immutable$VectorMap$$field(VectorMap.scala:74)
  at scala.collection.immutable.VectorMap.removed(VectorMap.scala:136)
  ... 28 elided
```
When remove any element, init may not work.
```scala
scala> VectorMap(1 -> "a", 2 -> "b", 3 -> "c").removed(1).init
java.util.NoSuchElementException: key not found: 2
  at scala.collection.immutable.Map$Map1.apply(Map.scala:240)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:112)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:84)
  at scala.collection.Iterator$SliceIterator.next(Iterator.scala:1219)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
  at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1167)
  at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1162)
  at scala.collection.AbstractIterator.addString(Iterator.scala:1274)
  at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1112)
  at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1110)
  at scala.collection.AbstractIterator.mkString(Iterator.scala:1274)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:234)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:243)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:251)
  at .$print$lzycompute(<synthetic>:8)
  ... 26 elided

scala> VectorMap(1 -> "a", 2 -> "b", 3 -> "c", 4 -> "d", 5 -> "e").removed(1).removed(4).init
java.util.NoSuchElementException
  at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:608)
  at scala.collection.immutable.HashMap.apply(HashMap.scala:131)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:112)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:84)
  at scala.collection.Iterator$SliceIterator.next(Iterator.scala:1219)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
  at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1170)
  at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1162)
  at scala.collection.AbstractIterator.addString(Iterator.scala:1274)
  at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1112)
  at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1110)
  at scala.collection.AbstractIterator.mkString(Iterator.scala:1274)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:234)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:243)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:251)
  at .$print$lzycompute(<synthetic>:8)
  ... 26 elided
```
## problem
Excuse my poor English.

when remove last element. 'fields' is filled with Tombstone.Kinless.
But after insert new element, Kinless fields are not renewed.

tail method shrink 'fields' to back. But 'underlying' (except last key) is not renewed.
So occur a gap between 'fields' and 'underlying' element.

init method use 'underlying' size via size property. And use it to access 'fields'. wrong way.
And, init method need to find prev valid field, but field method searches next valid field.

### PR DESCRIPTION
**Pull request by gitdako3706**
see also scala/bug#11933

Change usage of Tombstone

- First element of Tombstone sequence, indicates next valid element of the Tombstone sequence.
- Last element of Tombstone sequence if it not first element (in other words, the Tombstone sequence's length > 1), then indicates prev valid element of the Tombstone sequence.
- The others, Not Concerned.

So remove Kinless class.

Add parameter 'dropped'

- 'dropped' indicates sum count of drop fields. It also indicates gap between actual slot and slot that underlying indicates.

Change method 'removed'

- It only merge preceding tombstone sequence and succeeding tombstone sequence.

Change method 'init'

Fixes scala/bug#11933

### CODE REVIEW

**Comment by lrytz** [comment]
Also asking @odd for a review, since he authored `Tombstone` (https://github.com/scala/scala/pull/7193)

**Comment by SethTisue** [comment]
tests are passing on the last commit, but CI is red just because "combined" check is failing. the "combined" check ensures that every commit passes CI, not only the last commit. (we're strict about that in this repo, because it helps us bisect regressions.) @gitdako3706 can you squash all of this into a single commit?

**Comment by SethTisue** [comment]
On my laptop I just ran 2.13.2-bin-b4accdc-SNAPSHOT through https://github.com/scala/scala-collection-laws and it passed.

@Ichoran should the test cases in this PR be added to scala-collection-laws as laws?

**Comment by mdedetrich** [comment]
For me it looks fine but I would also wait for @odd feedback since he added in tombstone feature (as @lrytz said).

**Comment by Ichoran** [comment]
@SethTisue - I suppose we could, but these are awfully weird and specific sequences of calls that highlight problems particular to `VectorMap`.  Of course they _might_ catch something else, but I think they work better as specific regression tests for `VectorMap`.

File: src/library/scala/collection/immutable/VectorMap.scala [hunk 1]
```diff
@@ -29,7 +29,7 @@ import scala.annotation.tailrec
   */
 final class VectorMap[K, +V] private (
     private[immutable] val fields: Vector[Any],
-    private[immutable] val underlying: Map[K, (Int, V)], dummy: Boolean)
+    private[immutable] val underlying: Map[K, (Int, V)], dummy: Boolean, dropped: Int)
```
Comment (odd) [inline src/library/scala/collection/immutable/VectorMap.scala]: The `dummy` parameter should be dropped now since the `dropped` parameter only exists on the `private` constructor (thus making the signature different from the `private[immutable]` constructor signature so they wont conflict anymore).

**Review by odd — APPROVED** [review]
Hello all and sorry for not responding sooner, I only became aware of this PR and the associated issue earlier today (thanks @SethTisue for pinging me). 

I have now looked through the code and not only does it fix scala/bug#11933 but it also improves the performance of removals by not updating the intermediate tombstones. 

Since it passes the tests and follows the laws it looks good to go. Great work @gitdako3706!

**Comment by SethTisue** [comment]
@gitdako3706: Odd suggested one small change, are you available to take care of that? otherwise this seems ready for merge.

File: src/library/scala/collection/immutable/VectorMap.scala (hunk 1 above)
Comment (gitdako3706) [reply src/library/scala/collection/immutable/VectorMap.scala]: Thank you for your comment.
Certainly that parameter doesn't seem to be used, I'll trim it.

**Comment by SethTisue** [comment]
thank you @gitdako3706 and reviewers!
