### PR TITLE
Avoid rare StackOverflow in diverging implicits check

### LINKED ISSUE #12005: Regression using Scala 2.13.2 with quill macro.
## reproduction steps

Regression using Scala compiler 2.13.2

```
git clone --branch 2.13.2 https://github.com/ajozwik/quill-generic.git 
cd quill-generic
sbt -Dmacro.scala.version=2.13 ";project quill-jdbc-macro;test:compile;"
```

## problem
Up to scala 2.13.1 (and scala 2.12.11)  the code using [getquill](https://github.com/getquill/quill) with scala macro compiled without any problem.

For scala 2.13.2 - the java.lang.StackOverflowError without clear error occurs:

```
[error] java.lang.StackOverflowError
[error] scala.reflect.internal.Symbols$Symbol.isPrimaryConstructor(Symbols.scala:951)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:1122)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitssImpl(Contexts.scala:1145)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:1124)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitssImpl(Contexts.scala:1145)
.....
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1717)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:113)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
[error] scala.tools.nsc.Global$$anon$5.inferImplicit(Global.scala:482)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
[error] scala.tools.nsc.Global$$anon$5.inferImplicitFor(Global.scala:482)
[error] scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:272)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:888)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:492)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1305)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1302)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:875)
.....

```

### PR DESCRIPTION
**Pull request by joroKr21**
Two refined types may be equal wrt `=:=` but have different symbols.
We cannot use `=:=` because it is too pessimistic (wrt wildcards),
but this property of refined types makes `allSymbols` too optimistic.

For the implicit divergence check to work, we want the invariant:
`T =:= U` implies `allSymbols(T) == allSymbols(U)` to hold.
The solution is to exclude the symbols of refined types,
which makes `allSymbols` a bit more pessimistic.

Convert `allSymbols` from a recursive function to a `TypeCollector`
to avoid all the intermediate list allocations.

Fixes scala/bug#12005

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/Implicits.scala [hunk 1]
```diff
@@ -529,25 +529,24 @@ trait Implicits {
...
-            case ThisType(sym)           => loop(tl, hdSym(acc + sym))
-            case TypeRef(pre, sym, args) => loop(pre :: args ++ tl, hdSym(acc + sym))
-            case RefinedType(parents, _) => loop(parents ++ tl, hdSym(acc))
-            case _ => loop(tl, hdSym(acc))
-          }
-        }
-
-      loop(List(tp), Set.empty)
+    private object AllSymbols extends TypeCollector(Set[Symbol](NoSymbol)) {
+      def apply(tp: Type): Unit = tp match {
```
Comment (diesalbla) [inline src/compiler/scala/tools/nsc/typechecker/Implicits.scala:533]: The default implementation of a set are usually memory heavy. In the code below, the only thing we do with the set of symbols generated from this collector is to compare if they are equal. However, all the information we need for that are the identifiers of  those symbols. 

Perhaps we could use two collectors here:

- First collector builds an array of _longs_, which are the identifiers of symbols in the first type. At the end that array is sorted and repetitions removed.
- Second collector receives the array of ids (sorted and without repetitions), and uses an internal bitset to mark positions of the array whose elements it has found in the second type. It also uses a boolean variable to flag if it ever finds a symbol not in the array.

This would reduce allocations to the first array (and regrowing attempts), and the bitset. 


However, this may be not needed for a bugfix PR.

Comment (joroKr21) [reply src/compiler/scala/tools/nsc/typechecker/Implicits.scala:533]: That sounds rather complicated - how about just using a `BitSet`?

Comment (diesalbla) [reply src/compiler/scala/tools/nsc/typechecker/Implicits.scala:533]: _If I understand correctly_, the trouble with a BitSet is that its size would be proportional to the _maximum_ number you store in it. So, if you are storing Ids fro, 1043 to 1258, it would take `ceiling(1258/64)` = 20 longs. A bitset is all the elements from zero to that number. Hence the idea of a bitset of _array_ positions (from zero to # of elements)

Comment (diesalbla) [reply src/compiler/scala/tools/nsc/typechecker/Implicits.scala:533]: Regardless, since Seth just scheduled this for release 2.13.3, let's go ahead with it. We can look at it later.

**Review by diesalbla — APPROVED** [review]

File: src/compiler/scala/tools/nsc/typechecker/Implicits.scala (hunk 1 above)
Comment (joroKr21) [reply src/compiler/scala/tools/nsc/typechecker/Implicits.scala:533]: Yeah sounds good for a follow up PR

**Review by dwijnand — APPROVED** [review]
Seems good to merge, to me.

Just throwing it out there (not a request): it would've been interesting to see this as a commit that reworks it as a `TypeCollector` first and then the `RefinedType` proposed change.

Particularly I'm not sure I'm understanding properly what's going on around `NoSymbol`: it seems to be painstakingly excluded before but eagerly included now?

**Comment by joroKr21** [comment]
> Just throwing it out there (not a request): it would've been interesting to see this as a commit that reworks it as a TypeCollector first and then the RefinedType proposed change.

That's a good point. I am guilty sometimes of doing too much in one commit. 👍 
I will add it to my todo list, but depending on the 2.13.3 timeline I might not be able to get to that.

> Particularly I'm not sure I'm understanding properly what's going on around NoSymbol: it seems to be painstakingly excluded before but eagerly included now?

We use the set of all symbols just for equals comparison. So it doesn't matter if we add `NoSymbol` to this set or not.
The important part is that it's consistently present or absent in both sides of the comparison.

**Comment by dwijnand** [comment]
> I will add it to my todo list, but depending on the 2.13.3 timeline I might not be able to get to that.

No sweat 🙂  Thanks for the fix!
