### PR TITLE
Map#keys is alias of keySet and may be a view

### LINKED ISSUE #11727: Scala 2.12 map.keySet leaks reference to map
Hello, we discovered with prod pain and crashes that `Map.keySet` leaks a reference to the Map object so that it is not GC'ed and leaks memory - huge memory if objects in the map are big and you wanted to only return light identifiers to them. 

It can be seen for ex here: https://gist.github.com/fanf/ff39065f7f9738467e40929ad7490da1

Is this known/wanted and I'm just 13 years late in that knowledge, or is it a bug (at least a bad documentation)? 

The problem is likely the references to self in `DefaultKeySet` (`contains`, `size`...) https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/MapLike.scala#L176

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#11727

### CODE REVIEW

**Comment by som-snytt** [comment]
~Still need to review the doc locally.~ The mima filter should be benign. I briefly probed `VectorMap#keys` and left a comment for a future spelunker. Apologies for syntax tweaks in that file, intended to improve readability (for me) modulo style preference. I did not pursue any material changes to avoid allocations and such.

**Comment by som-snytt** [comment]
deprecation reveals that `keys` is used heavily because it is pithy. And that's just in the scala project. So probably deprecation is -- what's the midpoint between unwise and untenable?

deprecatedOverriding reveals
```
 // Ideally this returns a `View`, but bincompat
  /** Creates a view over all keys of this map.
   *
   *  @return the keys of this map as a view.
   */
  @nowarn
  override def keys: Iterable[K] = new MapView.Keys(this)
```

**Comment by yzia2000** [comment]
Don't see any issues with the PR (though there are more touches than just docs)

**Comment by yzia2000** [comment]
Don't see any issues with the PR (though there are more touches than just docs I think changes are benign)

File: src/library/scala/collection/MapView.scala [hunk 1]
```diff
@@ -27,6 +27,7 @@ trait MapView[K, +V]
    *
    *  @return the keys of this map as a view.
    */
+  @nowarn
```
Comment (iusildra) [inline src/library/scala/collection/MapView.scala]: Why add a `@nowarn` after putting it as deprecated ?

File: project/MimaFilters.scala [hunk 2]
```diff
@@ -39,6 +39,8 @@ object MimaFilters extends AutoPlugin {
     ProblemFilters.exclude[DirectMissingMethodProblem]("scala.concurrent.impl.FutureConvertersImpl#P.accept"),
     ProblemFilters.exclude[IncompatibleMethTypeProblem]("scala.concurrent.impl.FutureConvertersImpl#P.andThen"),
 
+    // private[immutable] utility used by VectorMap#values, analogous to collection.AbstractIterable
+    ProblemFilters.exclude[MissingClassProblem]("scala.collection.immutable.AbstractIterable"),
```
Comment (iusildra) [inline project/MimaFilters.scala]: Does this means that if this class is missing, it won't be detected as binary incompatible ? It's ok because this class is only used internally ?

**Review by iusildra — COMMENTED** [review]
Looks good to me, I just have 2 small questions to be sure

File: project/MimaFilters.scala (hunk 2 above)
Comment (som-snytt) [reply project/MimaFilters.scala]: It means the class doesn't exist before, so if it's in API, it would be incompatible. But since you asked, I'll take a second look at whether this accommodation of `VectorMap` is worth it (for the one case). I also did not track down why it required `immutable` there. In fact, `VectorMap` fought all the tweaks, so I will roll back the syntax/whitespace edits and keep just the useful comment on `nextValidField`. Thanks for your question.

File: src/library/scala/collection/MapView.scala (hunk 1 above)
Comment (som-snytt) [reply src/library/scala/collection/MapView.scala]: It's deprecated for overriding, but we can't remove it from subclasses, in particular where it can leak to client code, e.g., `mymapview.keys`.

**Comment by som-snytt** [comment]
I removed the unnecessary distractions. Thanks for first round of reviews.

The first commit is documentation; the second commit adds a deprecation. I don't know that deprecation (for overriding) is desirable, or what the `keys` API is intended to do.

I wonder if the collections label automatically summons @scala/collections or if it is actually a clothing line in the Scala store, "The Collections collection, new for fall."

**Review by iusildra — APPROVED** [review]

File: src/library/scala/collection/Map.scala [hunk 3]
```diff
@@ -179,9 +179,10 @@ trait MapOps[K, +V, +CC[_, _] <: IterableOps[_, AnyConstr, _], +C]
 
   override /*PartialFunction*/ def applyOrElse[K1 <: K, V1 >: V](x: K1, default: K1 => V1): V1 = getOrElse(x, default(x))
 
-  /** Collects all keys of this map in a set.
-    * @return  a set containing all keys of this map.
-    */
+  /** A set view of the keys contained by this map.
```
Comment (He-Pin) [inline src/library/scala/collection/Map.scala]: Return a set view of the keys contained in this map?

File: src/library/scala/collection/Map.scala [hunk 4]
```diff
@@ -179,9 +179,10 @@ trait MapOps[K, +V, +CC[_, _] <: IterableOps[_, AnyConstr, _], +C]
...
+   *
+   *  @return  a set view of the keys contained by this map
+   */
   def keySet: Set[K] = new KeySet
```
Comment (He-Pin) [inline src/library/scala/collection/Map.scala:192]: Questions:
1. will remove the key from a keyset affect the underling map?
2. can user add new key to the returning keySet?
3. does the implementation cache a keyset instance ?

File: src/library/scala/collection/Map.scala [hunk 5]
```diff
@@ -199,10 +200,11 @@ trait MapOps[K, +V, +CC[_, _] <: IterableOps[_, AnyConstr, _], +C]
...
-  /** Collects all keys of this map in an iterable collection.
-    *
-    *  @return the keys of this map as an iterable.
-    */
+  /** An [[Iterable]] collection of the keys contained by this map.
+   *
+   *  @return  an [[Iterable]] collection of the keys contained by this map.
+   */
+  @deprecatedOverriding("A set view of keys, i.e., keySet; for an ordered traversal, use keysIterator or keys.iterator", since="2.13.13")
   def keys: Iterable[K] = keySet
```
Comment (lrytz) [inline src/library/scala/collection/Map.scala:220]: Should `keys` be deprecated? Why does it exist alongside `keySet` and `keysIterator`?

File: src/library/scala/collection/Map.scala (hunk 4 above)
Comment (lrytz) [reply src/library/scala/collection/Map.scala:192]: I think the semantic question is important: do we guarantee that `keySet` returns a view? Because that's not reflected in the return type.

It might be better to say that it *may* return a view which *may* hold a reference to the original collection, and *may* reflect changes to the underlying Map.

File: src/library/scala/collection/Map.scala (hunk 5 above)
Comment (som-snytt) [reply src/library/scala/collection/Map.scala:220]: I tried just deprecation first and it was bad FSR. I think a couple of collections wanted to offer an alternative where keySet did not feel natural or showed mismatched impedance.

**Comment by som-snytt** [comment]
Yes, the strong position here is that key sets are views. `keys` is not. This is like Map#mapValues, an API choice that creates a smell that lingers for a decade of upgrades.

File: src/library/scala/collection/Map.scala (hunk 3 above)
Comment (som-snytt) [reply src/library/scala/collection/Map.scala]: That's a good question. I prefer minimal words. Instead of, "This class is a map of values," it's enough to say, "A map of values." For an accessor, "Returns a set view" is misleading, because an accessor trivially produces its accessed. The signature of `keys` by contrast ought to be `keys()` with doc, "Returns a collection..." Maybe the rule is that for attributives of the form `X is A`, it's sufficient to document the attribute A. For active verbs, retain the verbiage: "Produce a widget that does A and B."

File: src/library/scala/collection/Map.scala (hunk 4 above)
Comment (som-snytt) [reply src/library/scala/collection/Map.scala:192]: it is a `collection.Set` so answers are provided by the type, unlike Java. The other active question is the ticket about treemap.range.clear() clearing the map in scala but only the subrange in java.

By uniform access, it's an implementation detail whether the same instance is returned always.

IIUC, the collections (by Mr Reginald Straw, the straw-man) intend for subclasses to return a subclass of `KeySet`; it is appropriate that the class is not exposed in the API. Arguably, it's appropriate for the doc to announce the most severe restriction (it's a view because that is efficient) which may be relaxed by any given subclass (not a view, maybe it's easier to return a new set of one element than a view object that must walk an extra pointer).

File: src/library/scala/collection/Map.scala (hunk 5 above)
Comment (som-snytt) [reply src/library/scala/collection/Map.scala:220]: I noticed that I commented on the PR that keys is popular (because it is a short name, presumably). I propose we introduce an alias `keyS` to emphasize that it is just a short form of the name `keySet`.

File: src/library/scala/collection/Map.scala [hunk 6]
```diff
@@ -214,10 +216,10 @@ trait MapOps[K, +V, +CC[_, _] <: IterableOps[_, AnyConstr, _], +C]
     override def iterator: Iterator[V] = valuesIterator
   }
 
-  /** Creates an iterator for all keys.
-    *
-    *  @return an iterator over all keys.
-    */
+  /** An [[Iterator]] of the keys contained by this map.
+   *
+   *  @return  an [[Iterator]] of the keys contained by this map
```
Comment (som-snytt) [inline src/library/scala/collection/Map.scala]: weird extra space

File: test/junit/scala/collection/MapTest.scala [hunk 7]
```diff
@@ -128,4 +130,10 @@ class MapTest {
     assertFalse(Set("") == immutable.BitSet(1))
     assertFalse(Map("" -> 2) == scala.collection.immutable.LongMap(1L -> 2))
   }
+
+  @Test def `map is reachable from its keyset`: Unit =
+    assertFails(_.contains("held reference")) {
+      val m = Map("one" -> "eins")
+      assertNotReachable(m, m.keySet)(())
```
Comment (som-snytt) [inline test/junit/scala/collection/MapTest.scala:137]: maybe it should have a default body arg `(body: => Unit = ())`. I've seen this usage a couple of times this week.

File: src/library/scala/collection/Map.scala (hunk 4 above)
Comment (iusildra) [reply src/library/scala/collection/Map.scala:192]: > It might be better to say that it may return a view which may hold a reference to the original collection, and may reflect changes to the underlying Map.

Isn't it weird to say that `A` _may_ return `b` ? I think sometimes we would like to be sure not to have a reference to the original collection

Comment (lrytz) [reply src/library/scala/collection/Map.scala:192]: Some implementations return a view, some overrides return a new independent collection. I don't think this is good design, but it's what we have and we probably cannot change it in a minor release. We can add a snippet to the documentation showing how to turn the result into a strict copy.

**Review by lrytz — COMMENTED** [review]
pushed my suggestion, @som-snytt wdyt?

**Comment by som-snytt** [comment]
I squashed with all suggestions. It is a lot of words now. I adjusted only the left gutter. I did not re-view the Scaladoc locally.
