### PR TITLE
Make StringOps a pure value class

### LINKED ISSUE #10844: `String.patch` does not anymore return a `String` when it could
Before:

~~~
Welcome to Scala 2.12.5 (OpenJDK 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> "foo".patch(1, List('e', 'e'), 2): String
res0: String = fee

scala> "foo".patch(1, List('e', 'e'), 2) // Even without the type annotation we get back a `String`
res1: String = fee
~~~

Now:

~~~
Welcome to Scala 2.13.0-pre-1c0be29 (OpenJDK 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> "foo".patch(1, List('e', 'e'), 2): String
                          ^
       error: type mismatch;
        found   : List[Char]
        required: String

scala> "foo".patch(1, List('e', 'e'), 2)
res2: scala.collection.immutable.IndexedSeq[Char] = Vector(f, e, e)

scala> "foo".patch(1, List('e', 'e').mkString, 2)  // possible workaround
res3: String = fee
~~~

The problem might be solved by playing with overloads.

### LINKED ISSUE #10845: Move StringOps out of the collections hierarchy
As suggested by @szeiger in https://github.com/scala/scala/pull/6535#pullrequestreview-114854395. This would (hopefully) address issues like https://github.com/scala/bug/issues/10844.

### PR DESCRIPTION
**Pull request by szeiger**
This is the same treatment we gave ArrayOps previously. Some of the
more complex and nonsensical (for Strings) operations are provided for
compatibility. They delegate to WrappedString. Most operations have
efficient implementations in StringOps.

Fixes https://github.com/scala/bug/issues/10845.
Fixes https://github.com/scala/bug/issues/10844.

I've changed the signature of `contains` to disallow widening (and thus the need for expensive equality tests):
```scala
  def contains(elem: Char): Boolean = s.indexOf(elem) >= 0
```

Other collection-values methods with widening (from Char to Any) are probably not very useful for Strings. We should consider deprecating them.

The following methods are new overloads. They were missing for completeness:
```scala
  @`inline` def concat(suffix: String): String = s + suffix
  def prependedAll(prefix: String): String = prefix + s
  @`inline` def ++: (prefix: String): String = prependedAll(prefix)
  @`inline` def appendedAll(suffix: String): String = s + suffix
```

### CODE REVIEW

**Comment by julienrf** [comment]
How can we be sure that we don’t forget operations? (like it was the case with `scanLeft` on `ArrayOps`, or like we have in scala/bug#10852)

**Comment by lrytz** [comment]
Hmm... the change is not binary compatible and causes the partest binary to fail

```
[test] Caused by: sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: scala.collection.StringOps.drop(I)Ljava/lang/Object;
[test] 	at scala.tools.partest.nest.Runner.retainOn$1(Runner.scala:332)
```

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6566 would fix that issue

**Comment by szeiger** [comment]
I went through the scaladoc generated from the previous implementation to make sure that I don't overlook any operations. AFAIR @lrytz linked to a tool to automate this in some ticket but I can't find it anymore.

We still need to fix `ArrayOps`, I noticed several more methods that are missing for which there is no ticket yet.

**Comment by lrytz** [comment]
In https://github.com/scala/collection-strawman/issues/419 I proposed some crude code that uses reflection to show members

File: src/library/scala/collection/StringOps.scala [hunk 1]
```diff
@@ -452,45 +805,545 @@ final class StringOps(private val s: String)
...
+    *  @param op      a binary operator that must be associative.
+    *  @return        the result of applying the fold operator `op` between all the chars and `z`, or `z` if this string is empty.
+    */
+  @`inline` def fold[A1 >: Char](z: A1)(op: (A1, A1) => A1): A1 = foldLeft(z)(op)
+
+  /** Selects the first char of this string.
+    *  @return  the first char of this string.
+    *  @throws NoSuchElementException if the string is empty.
+    */
+  def head: Char = if(s.isEmpty) throw new NoSuchElementException else s.charAt(0)
```
Comment (lrytz) [inline src/library/scala/collection/StringOps.scala]: could also include a message `"head of empty string"`

**Review by lrytz — COMMENTED** [review]
Which are the "other collection-values methods with widening" that are "not very useful"? It would probably be good to deprecate them.

**Comment by szeiger** [comment]
All widening operations (excluding `@inline` aliases):

Standard collection operations that are overloaded in `StringOps` and therefore need a copy of the original method. If we want to keep an implicit conversion from `String` to `Seq[Char]` we have to keep them. And I reversed my stance on this conversion: I don't think we should remove it. A `String` is already conceptually a sequence of chars, treating it as a `Seq[Char]` is not a problem. The problem is that "sequence of chars" is not very meaningful in Unicode.
```
def concat[B >: Char](suffix: Iterable[B]): immutable.IndexedSeq[B]
def padTo[B >: Char](len: Int, elem: B): immutable.IndexedSeq[B]
def prepended[B >: Char](elem: B): immutable.IndexedSeq[B]
def prependedAll[B >: Char](prefix: Iterable[B]): immutable.IndexedSeq[B]
def appended[B >: Char](elem: B): immutable.IndexedSeq[B]
def patch[B >: Char](from: Int, other: IterableOnce[B], replaced: Int): immutable.IndexedSeq[B]
```

Useful because it allows widening to `Object[]` (with a cast):
```
def toArray[B >: Char : ClassTag]: Array[B]
```

Widening doesn't make much sense here. We could remove the widening.
```
def fold[A1 >: Char](z: A1)(op: (A1, A1) => A1): A1
```

These methods could be removed completely. You'll still be able to call the version in `WrappedString` (so the return type will be `WrappedString` instead of `String`) but IMHO they are useless for Strings.
```
def diff(that: Seq[_ >: Char]): String
def intersect(that: Seq[_ >: Char]): String
def sorted[B >: Char](implicit ord: Ordering[B]): String
```

**Comment by szeiger** [comment]
Rebased and updated.

**Comment by lrytz** [comment]
The failure here is explained in https://github.com/scala/scala/pull/6611/commits/c5733d2b9bd3d424f30f8d0b511cf82d2a30507d. We need to rebase after merging #6611

**Comment by lrytz** [comment]
Rebased on top of #6611 (and fixed some exception messages)
