### PR TITLE
[#8469] IterableOnce#copyToArray returns number of elements copied

### LINKED ISSUE #8469: copyToArray should return the number of elements copied
I believe copyToArray should return the number of elements copied. In particular this would be important for Iterator, but might be handy in general. Given that copyToArray returns Unit at the moment, this would be a backward compatible change.

Consider the following use case. I receive an Iterator that I expect to be of a certain size. I want to put it into an Array. One option is to use Iterator.toArray and then assert that the size is as expected. But toArray is slow, because it does not know the expected size and has to use a dynamic array (or linked list?). copyToArray would be perfect, except we cannot tell how much was copied in the end. If Iterator.hasNext is true, we know the Iterator was too long. But if it is false, it was either the expected size or too short, and we cannot tell these cases apart.

Link to actual code with the above use-case:
https://github.com/apache/spark/blob/f4d9019aa8c93e6f7539192ba5780a2f6c8ce19e/graphx/src/main/scala/org/apache/spark/graphx/impl/EdgePartition.scala#L92

### LINKED ISSUE #11048: No-op copyToArray throws exception in Array, ArrayDeque, Queue, ArrayStack
The standard behavior is not to throw an exception, even if you index outside the target, as long as you're not doing anything.  (In fact, even if you are doing anything, you don't throw an exception--you just don't do it.)

Array and the ArrayDeque inheritance hierarchy all throw an exception instead, even on a no-op (zero length copied).

```
Welcome to Scala 2.13.0-20180731-142616-329c477 (OpenJDK 64-Bit Server VM, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

scala> val target = Array[Int]()
target: Array[Int] = Array()

scala> List(1, 2).copyToArray(target, 1, 0)
res0: target.type = Array()

scala> Array(1, 2).copyToArray(target, 1, 0)
java.lang.ArrayIndexOutOfBoundsException
  at java.lang.System.arraycopy(Native Method)
  at scala.Array$.copy(Array.scala:110)
  at scala.collection.ArrayOps$.copyToArray$extension(ArrayOps.scala:1267)
  ... 43 elided

scala> collection.mutable.ArrayDeque(1, 2).copyToArray(target, 1, 0)
java.lang.IndexOutOfBoundsException: 1
  at scala.collection.mutable.ArrayDeque.requireBounds(ArrayDeque.scala:494)
  at scala.collection.mutable.ArrayDeque.copySliceToArray(ArrayDeque.scala:454)
  at scala.collection.mutable.ArrayDeque.copyToArray(ArrayDeque.scala:438)
  ... 43 elided
```

### PR DESCRIPTION
**Pull request by joshlemer**
This fixes scala/bug#8469, and also adds `StringOps#copyToArray(Array[Char])`

This also fixes scala/bug#11048

### CODE REVIEW

**Comment by NthPortal** [comment]
@joshlemer I'm marking this as WIP because you said it's not ready for merging. Just drop a message here when that changes, and someone can remove the label :)

File: src/library/scala/collection/IterableOnce.scala [hunk 1]
```diff
@@ -729,24 +730,27 @@ trait IterableOnceOps[+A, +CC[_], +C] extends Any { this: IterableOnce[A] =>
...
     val it = iterator
     var i = start
+    var written = 0
     while (i < xsLen && it.hasNext) {
       xs(i) = it.next()
       i += 1
+      written += 1
     }
-    xs
+    written
```
Comment (julienrf) [inline src/library/scala/collection/IterableOnce.scala]: We could also write `i - start`, and remove the `written` variable. I’m not sure which solution is better, though.

**Review by julienrf — COMMENTED** [review]
Thanks @joshlemer, I think this is the right way to go!

The fact that you can not call `copyToArray` on a `String` is a regression. I’ve just noticed that one overload of `copyToArray` is missing. You can copy the way it is defined in `IterableOnceOps`.

File: src/library/scala/collection/IterableOnce.scala (hunk 1 above)
Comment (joshlemer) [reply src/library/scala/collection/IterableOnce.scala]: 👍

**Comment by joshlemer** [comment]
@NthPortal @julienrf I would consider this pr to be ready for review now.
Thanks :-)

File: src/library/scala/collection/ArrayOps.scala [hunk 2]
```diff
@@ -1263,13 +1263,18 @@ final class ArrayOps[A](val xs: Array[A]) extends AnyVal {
     *  @param  len    the maximal number of elements to copy.
     *  @tparam B      the type of the elements of the array.
     */
-  def copyToArray[B >: A](dest: Array[B], start: Int, len: Int = Int.MaxValue): dest.type = {
-    Array.copy(xs, 0, dest, start, min(xs.length, min(dest.length-start, len)))
-    dest
+  def copyToArray[B >: A](dest: Array[B], start: Int, len: Int = Int.MaxValue): Int = {
+    val copied = min(xs.length, min(dest.length-start, len))
```
Comment (julienrf) [inline src/library/scala/collection/ArrayOps.scala]: The maths are not correct in case the `start` parameter is higher than `dest.length`. Consider the case where `start = dest.length + 1` (and `len` is a positive number):

~~~
copied = min(xs.length, min(dest.length - start, len))
copied = min(xs.length, min(-1, len)
copied = min(xs.length, -1)
copied = -1
~~~

File: src/library/scala/collection/IterableOnce.scala [hunk 3]
```diff
@@ -1198,7 +1201,11 @@ trait IterableOnceOps[+A, +CC[_], +C] extends Any { this: IterableOnce[A] =>
 
   /** Convert collection to array. */
   def toArray[B >: A: ClassTag]: Array[B] =
-    if (knownSize >= 0) copyToArray(new Array[B](knownSize), 0)
+    if (knownSize >= 0) {
+      val a = new Array[B](knownSize)
```
Comment (julienrf) [inline src/library/scala/collection/IterableOnce.scala]: Do you mind giving `a` a more meaningful name? e.g. `copied` or `written`.

File: src/library/scala/collection/StringOps.scala [hunk 4]
```diff
@@ -1142,11 +1140,25 @@ final class StringOps(private val s: String) extends AnyVal {
...
+    * Copying will stop once either the entire string has been copied,
+    * or the end of the array is reached or `len` chars have been copied.
+    *
+    *  @param  xs     the array to fill.
+    *  @param  start  the starting index.
+    *  @param  len    the maximal number of elements to copy.
+    */
+  def copyToArray(xs: Array[Char], start: Int, len: Int): Int = {
+    val written = max(min(min(s.length, len), xs.length - start), 0)
+    s.getChars(0, written, xs, start)
```
Comment (julienrf) [inline src/library/scala/collection/StringOps.scala]: We could event put this line within an `if (written > 0)`

File: src/library/scala/collection/immutable/ArraySeq.scala [hunk 5]
```diff
@@ -133,12 +133,14 @@ sealed abstract class ArraySeq[+A]
...
 
-  override def copyToArray[B >: A](xs: Array[B], start: Int = 0): xs.type = copyToArray[B](xs, start, length)
+  override def copyToArray[B >: A](xs: Array[B], start: Int = 0): Int = copyToArray[B](xs, start, length)
 
-  override def copyToArray[B >: A](xs: Array[B], start: Int, len: Int): xs.type = {
-    val l = scala.math.min(scala.math.min(len, length), xs.length-start)
-    if(l > 0) Array.copy(unsafeArray, 0, xs, start, l)
-    xs
+  override def copyToArray[B >: A](xs: Array[B], start: Int, len: Int): Int = {
+    val _len = math.max(math.min(scala.math.min(len, length), xs.length-start), 0)
```
Comment (julienrf) [inline src/library/scala/collection/immutable/ArraySeq.scala]: I suggest that we use the same identifier everywhere. E.g. `copied`?

File: src/library/scala/collection/mutable/ArrayBuffer.scala [hunk 6]
```diff
@@ -159,12 +159,14 @@ class ArrayBuffer[A] private (initialElements: Array[AnyRef], initialSize: Int)
...
 
-  override def copyToArray[B >: A](xs: Array[B], start: Int): xs.type = copyToArray[B](xs, start, length)
+  override def copyToArray[B >: A](xs: Array[B], start: Int): Int = copyToArray[B](xs, start, length)
 
-  override def copyToArray[B >: A](xs: Array[B], start: Int, len: Int): xs.type = {
-    val l = scala.math.min(scala.math.min(len, length), xs.length-start)
-    if(l > 0) Array.copy(array, 0, xs, start, l)
-    xs
+  override def copyToArray[B >: A](xs: Array[B], start: Int, len: Int): Int = {
+    val _len = scala.math.min(scala.math.min(len, length), xs.length-start)
```
Comment (julienrf) [inline src/library/scala/collection/mutable/ArrayBuffer.scala]: Also, I’m thinking that it could be beneficial to define only once the computation that returns the number of copied elements, and then reuse it everywhere so that we don’t miss the final `max(…, 0)`. You could, for instance, create a private method in the `IterableOnce` companion object.

Comment (julienrf) [reply src/library/scala/collection/mutable/ArrayBuffer.scala]: We could even put the `if (copied > 0)` in that reusable method to save some logic duplication…

~~~ scala
@inline private[collection] def copyToArrayTemplate[A](
    thisLength: Int, xs: Array[A], start: Int, len: Int)(doCopy: Int => Unit): Int = {
  val copied = math.max(math.min(scala.math.min(len, thisLength), xs.length-start), 0)
  if (copied > 0) {
    doCopy(copied)
  }
  copied
}
~~~

And then, at use site:

~~~ scala
override def copyToArray[B >: A](xs: Array[B], start: Int, len: Int): Int =
  copyToArrayTemplate(length, xs, start, len) { copied =>
    Array.copy(array, 0, xs, start, copied)
  }
~~~

WDYT?

(You can use a better name than `copyToArrayTemplate`, obviously…)

(And I’m not sure how efficiently are literal functions inlined/optimized in such cases)

**Review by julienrf — COMMENTED** [review]
Thanks @joshlemer! The implementations or overrides are not always consistent together. I’ve left a comment with a suggestion to factor them out, let me know what you think!

File: src/library/scala/collection/mutable/ArrayBuffer.scala (hunk 6 above)
Comment (joshlemer) [reply src/library/scala/collection/mutable/ArrayBuffer.scala]: Hey @julienrf I really like the idea of implementing this a single time. I think though that the utility method could just return the number of elements to write, and that would save us having to allocate a closure

File: src/library/scala/collection/immutable/ArraySeq.scala (hunk 5 above)
Comment (joshlemer) [reply src/library/scala/collection/immutable/ArraySeq.scala]: 👍

File: src/library/scala/collection/StringOps.scala (hunk 4 above)
Comment (joshlemer) [reply src/library/scala/collection/StringOps.scala]: 👍

File: src/library/scala/collection/IterableOnce.scala (hunk 3 above)
Comment (joshlemer) [reply src/library/scala/collection/IterableOnce.scala]: 👍

**Comment by NthPortal** [comment]
@joshlemer do you wanna edit the PR description to no longer say that it's not ready for review, btw?

**Comment by joshlemer** [comment]
@NthPortal done, not sure why the build fails, it compiles fine for me

**Review by julienrf — APPROVED** [review]
Thanks! Can you squash your commits?

**Comment by joshlemer** [comment]
@julienrf yep! I'll do this tonight probably

**Comment by joshlemer** [comment]
@julienrf commits are squashed

File: test/junit/scala/collection/IterableTest.scala [hunk 7]
```diff
@@ -55,124 +56,116 @@ class IterableTest {
...
     assert(Iterable.empty == mutable.Traversable.empty.toTraversable)
-    assert(Map.empty      == mutable.LinkedHashMap.empty.toTraversable)
-    assert(Set.empty      == mutable.LinkedHashSet.empty.toTraversable)
+    assert(Map.empty == mutable.LinkedHashMap.empty.toTraversable)
+    assert(Set.empty == mutable.LinkedHashSet.empty.toTraversable)
     assert(Iterable.empty == mutable.ListBuffer.empty.toTraversable)
-    assert(Map.empty      == mutable.OpenHashMap.empty.toTraversable)
-    assert(Set.empty      == mutable.Set.empty.toTraversable)
+    assert(Map.empty == mutable.OpenHashMap.empty.toTraversable)
+    assert(Set.empty == mutable.Set.empty.toTraversable)
```
Comment (dwijnand) [inline test/junit/scala/collection/IterableTest.scala]: This is a little sad.. 😕

Comment (NthPortal) [reply test/junit/scala/collection/IterableTest.scala]: +1, I would like to keep the alignment

Comment (joshlemer) [reply test/junit/scala/collection/IterableTest.scala]: :+1: will fix

Comment (joshlemer) [reply test/junit/scala/collection/IterableTest.scala]: @dwijnand @NthPortal btw this is fixed now

File: src/library/scala/collection/immutable/ArraySeq.scala [hunk 8]
```diff
@@ -5,6 +5,7 @@ import java.io.{ObjectInputStream, ObjectOutputStream}
 
 import scala.collection.mutable.{ArrayBuffer, ArrayBuilder, Builder, ArraySeq => MutableArraySeq}
 import scala.collection.{ArrayOps, ClassTagSeqFactory, SeqFactory, StrictOptimizedClassTagSeqFactory, View}
+import scala.collection._
```
Comment (szeiger) [inline src/library/scala/collection/immutable/ArraySeq.scala]: This appears to be what causes the build errors. Never import `collection._` in a more specific collection package. You want to use the names from `immutable`, in particular the build errors are due to `immutable.ArraySeq` now extending `collection.IndexedSeq` instead of `immutable.IndexedSeq`.

**Comment by joshlemer** [comment]
I believe this is ready for merging now :-)
