### PR TITLE
Fix checkKindBoundsHK for higher kinds

### LINKED ISSUE #2067: Mistake in subkinding
```scala
trait A[B[D[X, Y <: X]]] {
 def f() : B[P]
}

trait C[E[T, S]]

trait P[U, V <: U]
```

Now, the kinds are:

```scala
D : X@* -> *(Nothing,X) -> *
B : (X@* -> *(Nothing,X) -> *) -> *

E : * -> * -> *
C : (* -> * -> *) -> *
```

In type application `A[C]`, `C` is substituted instead of the type parameter `B`, which leads to the ill-kinded type application C[P] in the return type of f().

So `(* -> * -> *) -> *` must be a subkind of `(X@* -> *(Nothing,X) -> *) -> *`.
Contravariantly, `X@* -> *(Nothing,X) -> *` must be a subkind of `* -> * -> *`.
Contravariantly, `*` must be a subkind of `*(Nothing,X)`, but this is not the case.

### LINKED ISSUE #12242: Can't take advantange of covariance of trait T[+A[_<:B[X], _], X] when extending it: self type error.
## reproduction steps

using Scala 2.13.4,

```scala
	trait Box[T]

	trait Adapter[B <: Box[T], T]

	trait SpecialAdapter[B <: Box[T], T] extends Adapter[B, T]

	trait Mixin[+A[B <: Box[S], X], S]

	trait Super[T] extends Mixin[Adapter, T]

	trait Sub[T] extends Super[T] with Mixin[SpecialAdapter, T]
```

## problem
```
illegal inheritance;
 self-type Playground.Sub[T] does not conform to Playground.Mixin[Playground.SpecialAdapter,T]'s selftype Playground.Mixin[Playground.SpecialAdapter,T]
	trait Sub[T] extends Super[T] with Mixin[SpecialAdapter, T]
```

Apparently all type parameters matter: I can't remove any without the error going away.  Crucial here is also the bound `<: Box[S]` in the type parameter of `Mixin`; removing it, or substituting it with `<: Box[_]` compiles.

### PR DESCRIPTION
**Pull request by joroKr21**
We need to flip the direction of the checks on every other level.
This is similar to contravariance of higher-order function types.

Another option would be to heed the comment:
```
          // Their arguments use different symbols, but are
          // conceptually the same. Could also replace the types by
          // polytypes, but can't just strip the symbols, as ordering
          // is lost then.
```
although I don't understand the last sentence - what ordering?
If we switch to PolyTypes we would lose the detailed error messages,
but I think this is what Scala 3 does.

fixes scala/bug#2067, fixes scala/bug#12242
This would probably need a community build

### CODE REVIEW

**Comment by lrytz** [comment]
> probably need a community build

cc @SethTisue

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2343/

**Comment by SethTisue** [comment]
> If we switch to PolyTypes we would lose the detailed error messages,
but I think this is what Scala 3 does

It seems maybe-implied by this remark, but just to confirm: does this PR bring Scala 2 and Scala 3 in closer alignment? (Should scala/bug#2067 be labeled `fixed-in-dotty`?)

**Comment by joroKr21** [comment]
> It seems maybe-implied by this remark, but just to confirm: does this PR bring Scala 2 and Scala 3 in closer alignment? (Should scala/bug#2067 be labeled fixed-in-dotty?)

@SethTisue yes, it's fixed in dotty:
```scala
Starting scala3 REPL...
scala> trait A[B[D[X, Y <: X]]]
     | trait C[E[T, S]]
     | type Bad = A[C]
3 |type Bad = A[C]
  |             ^
  |         Type argument C does not conform to upper bound [D[X, Y]] =>> Any

scala> trait A[T[_[_]]]
     | trait C[X[+_]]
     | type Bad = A[C]
3 |type Bad = A[C]
  |             ^
  |        Type argument C does not conform to upper bound [_$1[_$2]] =>> Any

```

Note that the error messages are not very informative.
It's also evident that dotty is reusing type lambdas for kind conformance.

On this branch of scalac:
```scala
Welcome to Scala 2.13.5-20201224-113823-22fc021 (OpenJDK 64-Bit Server VM, Java 11.0.9).
Type in expressions for evaluation. Or try :help.

scala> trait A[B[D[X, Y <: X]]]
     | trait C[E[T, S]]
     | type Bad = A[C]
       type Bad = A[C]
                  ^
On line 3: error: kinds of the type arguments (C) do not conform to the expected kinds of the type parameters (type B) in trait A.
       C's type parameters do not match type B's expected parameters:
       type Y's bounds <: X are stricter than type S's declared bounds >: Nothing <: Any

scala> trait A[T[_[_]]]
     | trait C[X[+_]]
     | type Bad = A[C]
       type Bad = A[C]
                  ^
On line 3: error: kinds of the type arguments (C) do not conform to the expected kinds of the type parameters (type T) in trait A.
       C's type parameters do not match type T's expected parameters:
       type _ is invariant, but type _ is declared covariant

```

Also I just realised this fixes scala/bug#12242 as well (it has a bad kind):
 * dotty:
```scala
scala> trait Box[T]
     | trait Adapter[B <: Box[T], T]
     | trait Mixin[+A[B <: Box[S], X], S]
     | trait Super[T] extends Mixin[Adapter, T]
4 |trait Super[T] extends Mixin[Adapter, T]
  |                             ^
  |Type argument Adapter does not conform to upper bound [B <: Box[T], X] =>> Any

```

* this branch:
```scala
scala> trait Box[T]
     | trait Adapter[B <: Box[T], T]
     | trait Mixin[+A[B <: Box[S], X], S]
     | trait Super[T] extends Mixin[Adapter, T]
       trait Super[T] extends Mixin[Adapter, T]
                              ^
On line 4: error: kinds of the type arguments (Adapter,T) do not conform to the expected kinds of the type parameters (type A,type S) in trait Mixin.
       Adapter's type parameters do not match type A's expected parameters:
       type B (in trait Adapter)'s bounds <: Box[T] are stricter than type B's declared bounds <: Box[S]
```

Do you think I should add one more test?

**Comment by joroKr21** [comment]
> queued: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2343/

"No space left on device" 🤖

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2345

**Comment by joroKr21** [comment]
> Do you think I should add one more test?

I just did

**Comment by SethTisue** [comment]
The failure in the community build is in a known-flaky repo, so I'd call 2345 a green run.

This needs rebase before merge.

**Review by SethTisue — APPROVED** [review]

File: test/files/neg/subkinding.scala [hunk 1]
```diff
@@ -0,0 +1,23 @@
+// scala/bug#2067
+object Test1 {
+  trait A[B[D[X, Y <: X]]]
+  trait C[E[T, S]]
+  trait P[U, V <: U]
```
Comment (lrytz) [inline test/files/neg/subkinding.scala]: unused - remove this line?

File: test/files/neg/subkinding.scala [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+  type T = A[C]
+}
+
+// scala/bug#2067
+object Test2 {
+  class P[Y](val y : Y)
```
Comment (lrytz) [inline test/files/neg/subkinding.scala]: also unused

**Review by lrytz — APPROVED** [review]
