### PR TITLE
[bug#11515] Fix View#toString impl

### LINKED ISSUE #11515: MapView has silly `toString`
```scala
scala> Seq(1).view
res0: scala.collection.SeqView[Int] = View(?)

scala> Array(1).view
res3: scala.collection.IndexedSeqView[Int] = View(?)

scala> Set(1).view
res1: scala.collection.View[Int] = View(?)

scala> Map(1 -> 1).view
res2: scala.collection.MapView[Int,Int] = <function1>


```

### PR DESCRIPTION
**Pull request by NthPortal**
Fix `View#toString` implementation so that subclasses
can override `className` and still change the string
representation. Since by default `className`
forwards to `stringPrefix`, it will still behave correctly
for old/migratory implementations, but will now also support
"correct" implementations as well.

Followup to #8029.

Fixes scala/bug#11515 *for real this time*.

### CODE REVIEW

File: test/junit/scala/collection/MapViewTest.scala [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.junit.runners.JUnit4
+
+@RunWith(classOf[JUnit4])
+class MapViewTest {
+  @Test
+  def _toString(): Unit = {
+    assertEquals("MapView(<not computed>)", Map(1 -> 2).view.toString)
+  }
```
Comment (joshlemer) [inline test/junit/scala/collection/MapViewTest.scala:13]: Could we add a test for SeqView and IndexedSeqView?

Comment (NthPortal) [reply test/junit/scala/collection/MapViewTest.scala:13]: I don't think it's super important, given that they override `stringPrefix` anyway, but sure

**Review by lrytz — APPROVED** [review]
This could go in 2.13.1, but it's such a simple change that I'd say RC3 is fine too.

**Comment by adriaanm** [comment]
Last time we changed a toString it broke some tests. They were wrong, but just saying... anyway, let’s do it!
