### PR TITLE
Scaladoc: realign `-doc-source-url` behavior with 2.12

### LINKED ISSUE #12867: scaladoc 2.13.12 `-doc-source-url` behavior change
Changed in https://github.com/scala/scala/pull/10502

## Reproduction steps

```scala
// /workspace/sandbox/foo.scala
class Foo
```

```
scaladoc -doc-source-url 'http://somewhere€{FILE_PATH}.scala' /workspace/sandbox/foo.scala
```

## Problem

In 2.13.11 we get source links like:

```html
<a href="http://somewhere/workspace/sandbox/foo.scala" target="_blank">foo.scala</a>
```

In 2.13.12 we get:

```html
<a href="http://somewherefoo.scala" target="_blank">foo.scala</a>
```

h/t @Jasper-M, cc @j-mie6

### PR DESCRIPTION
**Pull request by lrytz**
Summary

  - In the common case, build tools pass absolute paths to the compiler for source files to compile
  - `-sourcepath` is used to relativize them
  - In 2.12.11, [the relativized path starts with a `/`](https://github.com/scala/scala/blob/v2.13.11/src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala#L316-L320), so `base€{FILE_PATH_EXT}` becomes `base/src/...`
  - [#10502](https://github.com/scala/scala/pull/10502) changed relativization to use `srcpathUri.relativize(fileUri)`, which doesn't have a leading `/`
  - Fix: for a relative path, `foo/€{FILE_PATH}` and `foo€{FILE_PATH}` both emit `foo/relative/path/File` (insert `/` if a word character precedes `€{FILE_PATH}`). No such magic for absolute paths (if `-sourcepath` is not specified or is not a prefix of the file).

What happens without `-sourcepath`:

  - 2.13.11 [used the path that the compiler got on the command line](https://github.com/scala/scala/blob/v2.13.11/src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala#L320). So `scaladoc a/B.scala` would insert a relative path.
  - 2.13.12 relativizes source paths to the current directory because `Paths.get("").toUri` is the current directory
  - I changed it to use an absolute path. As build tools pass absolute paths to the compiler, the behavior is the same as in 2.13.11 in the common case.

Fixes https://github.com/scala/bug/issues/12867

### CODE REVIEW

**Comment by som-snytt** [comment]
I have a couple of branches. I'll comment if either contains a break-through.
```
  issue/12867-doc-url
  issue/12867-scaladoc-source-link
```
One was from Sept 13, the longer one from Sept 20, when apparently it occurred to me to fix Scaladoc tickets?
```
commit d25e06dc81cd60d0efb9ffaf9239b65f341dd2cb (HEAD -> issue/12867-scaladoc-source-link)
Author: Som Snytt <som.snytt@gmail.com>
Date:   Thu Sep 21 17:40:22 2023 -0700

    more

commit 714275ffd3ac81506dd5e15081107b1c9b38038e
Author: Som Snytt <som.snytt@gmail.com>
Date:   Wed Sep 20 20:48:09 2023 -0700

    Minor refactor for reading

commit 6b994a4f30ee0cb78a5f2a28b0c6279467c890f6
Author: Som Snytt <som.snytt@gmail.com>
Date:   Wed Sep 20 19:10:03 2023 -0700

    No inheritdoc on Iterator.sameElements

commit 51885feabfae5030b6c473db1bf463418b81d2d2
Author: Som Snytt <som.snytt@gmail.com>
Date:   Wed Sep 20 18:36:49 2023 -0700

    Library leverages canonical url

commit 2df1a5fff4b745102203e1d68c6e62c6552fd3f9
Author: Som Snytt <som.snytt@gmail.com>
Date:   Wed Sep 20 17:28:36 2023 -0700

    Clean up doclet newinstance, avoid null currentRun
```

File: src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala [hunk 1]
```diff
@@ -318,27 +318,22 @@ class ModelFactory(val global: Global, val settings: doc.Settings) {
...
-          val path = file.file.toPath.toUri
-          val filePathExt = src.relativize(path)
-          val rawPath: String = filePathExt.getRawPath
+          val filePathExt = {
+            // file path is relative to source root (-sourcepath)
+            val sp = settings.sourcepath.value
+            val fileUri = file.file.toPath.toUri
+            // if the sourcepath is empty use an absolute path
+            if (sp.isEmpty) fileUri.getRawPath
+            else Paths.get(sp).toUri.relativize(fileUri).getRawPath
```
Comment (lrytz) [inline src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala:327]: In 2.13.11, without `-sourcepath`, the path string is what the compiler got on the command line. So `scaladoc a/B.scala` would insert a relative path.

https://github.com/scala/scala/blob/v2.13.11/src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala#L320

Assuming build tools use absolute paths, I went for an absolute path if `-sourcepath` is empty.

2.13.12 defaults to path relative to the current directory because `Paths.get("").toUri` is the current directory

https://github.com/scala/scala/blob/v2.13.12/src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala#L322

But I think we can use the absolute path in this case.

**Comment by lrytz** [comment]
@SethTisue could you review this? I summarized everything in the description.

**Review by SethTisue — APPROVED** [review]
I've looked through this and I can't think of a flaw or fresh angle, so I'll hit "Approve", but @som-snytt, you analyzed the situation pretty thoroughly at https://github.com/scala/bug/issues/12867#issuecomment-1718481858 ; would be good to have your signoff before merge, if you can spare the time

also perhaps @armanbilge would like to have a look?

File: test/junit/scala/tools/nsc/doc/html/ModelFactoryTest.scala [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+    t("/base/p/file.scala", "/base€{FILE_PATH_EXT}", filePath = "p/file", fileExt = ".scala")
+    t("/base/p/file.scala", "/base/€{FILE_PATH_EXT}", filePath = "p/file", fileExt = ".scala")
+    t("/base.p/file.scala", "/base.€{FILE_PATH_EXT}", filePath = "p/file", fileExt = ".scala")
+
+    t("/base/p/file.scala", "/base€{FILE_PATH_EXT}", filePath = "/p/file", fileExt = ".scala")
+    t("/base//p/file.scala", "/base/€{FILE_PATH_EXT}", filePath = "/p/file", fileExt = ".scala")
+
+    // file extension: don't duplicate `.`
+    t("/base/p/file.scala", "/base€{FILE_PATH}€{FILE_EXT}", filePath = "p/file", fileExt = ".scala")
+    t("/base/p/file.scala", "/base/€{FILE_PATH}.€{FILE_EXT}", filePath = "p/file", fileExt =".scala")
```
Comment (armanbilge) [inline test/junit/scala/tools/nsc/doc/html/ModelFactoryTest.scala]:
```suggestion
    t("/base/p/file.scala", "/base/€{FILE_PATH}.€{FILE_EXT}", filePath = "p/file", fileExt = ".scala")
```

**Comment by som-snytt** [comment]
my test dirs from that day...
```
...    4096 Sep 20 13:38  t12876
...    4096 Sep 20 14:37  t12867
```

File: src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala [hunk 3]
```diff
@@ -1061,11 +1055,38 @@ object ModelFactory {
   val defaultGroupDesc = None
   val defaultGroupPriority = 1000
 
-  val tokens = raw"€\{($FILE_PATH|$FILE_EXT|$FILE_PATH_EXT|$FILE_LINE|$TPL_OWNER|$TPL_NAME)\}".r
+  // 4 subgroups: (.?), (FILE_PATH|FILE_PATH_EXT), (FILE_EXT) and (FILE_LINE|TPL_OWNER|TPL_NAME). non-matching are `null`
+  val tokens = raw"(?:(.?)€\{($FILE_PATH|$FILE_PATH_EXT)\}|\.?€\{($FILE_EXT)\}|€\{($FILE_LINE|$TPL_OWNER|$TPL_NAME)\})".r
```
Comment (som-snytt) [inline src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala]: The outermost parens are extraneous.

The pattern and usage is clever but complex. You can look left given `m.start` to inspect the char, boring but clear.

Alternatively, or alternately, `\w(FILE_PATH)|\W(FILE_PATH)`. `(?<!Z)(?<bees>B+)` a group name to easily distinguish which match happened. `beez` would have the `Z`, pun alert. (Actually that doesn't help with the weird ugly `€\{` bits.)

File: src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala [hunk 4]
```diff
@@ -1061,11 +1055,38 @@ object ModelFactory {
...
+        case c => c
+      }
+
+      groups.tail.find(_ != null).get match {
+        case FILE_PATH => s"$sep$filePath"
+        case FILE_EXT => fileExt
+        case FILE_PATH_EXT => s"$sep$filePathExt"
+        case FILE_LINE => line.toString
+        case TPL_OWNER => tplOwner
+        case TPL_NAME => tplName
```
Comment (som-snytt) [inline src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala]: remember when arrows used to line up?

File: test/scaladoc/run/doc-source-url.scala [hunk 5]
```diff
@@ -26,7 +26,7 @@ object Test extends ScaladocModelTest {
 
   override def model: Option[Universe] = newDocFactory.makeUniverse(Left(List(resourceFile)))
 
-  def scaladocSettings = "-doc-source-url file:€{FILE_PATH}@@€{FILE_EXT}@@€{FILE_PATH_EXT}@@€{FILE_LINE}"
+  def scaladocSettings = "-doc-source-url file:€{FILE_PATH}@@€{FILE_EXT}@@€{FILE_PATH_EXT}@@€{FILE_LINE} -sourcepath ."
```
Comment (som-snytt) [inline test/scaladoc/run/doc-source-url.scala:29]: On the ticket, I asked why I had to use `-sourcepath` to show the problem but the reporters did not (in their examples).

Was there different behavior for `Paths.get("")` on different platforms? I saw in this fix that sourcepath is used if nonempty. I haven't looked at this test yet, but somehow I haven't nailed down why it's needed here.

**Review by som-snytt — APPROVED** [review]
I happen to be tired and lacking focus at the moment, so reading even this much regex is like, I'm not going to read any more regex until after New Year's.

**Comment by som-snytt** [comment]
NBD I tried the crusty way. https://github.com/scala/scala/compare/2.13.x...som-snytt:scala:test/t12867?expand=1

**Comment by lrytz** [comment]
I'm all for a simpler regex, thanks a lot for your cleanup.

File: test/scaladoc/run/doc-source-url.scala (hunk 5 above)
Comment (lrytz) [reply test/scaladoc/run/doc-source-url.scala:29]: I think:
  - 2.12.11: `FILE_PATH` was `test/scaladoc/...` because partest a relative path to scaladoc
  - 2.12.12: `FILE_PATH` was changed to be relative to `Paths.get("")`, cwd is the root directory, so in the end it's unchanged
  - with this PR: if `-sourcepath` is not specified `FILE_PATH` is changed to be absolute

File: src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala (hunk 4 above)
Comment (lrytz) [reply src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala]: There are other things that itch me, but somehow not this...
