### PR TITLE
Don't recurse without bound in outerPath

### LINKED ISSUE #10035: Compiler crash when accessing member inside auxiliary constructor
```scala
trait Inner {
  def f(): Outer
}

class Outer(o: Set[Inner]) {
  def this() = this(Set(1).map{
    case k => new Inner {
      def f(): Outer = Outer.this
    }
  })
}
```

```scala

Exception in thread "main" scala.reflect.internal.Types$TypeError: value <none> is not a member of <notype>
	at scala.tools.nsc.typechecker.Contexts$ThrowingReporter.handleError(Contexts.scala:1402)
	at scala.tools.nsc.typechecker.Contexts$ContextReporter.issue(Contexts.scala:1254)
	at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:573)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$normalTypedApply$1$1.apply(Typers.scala:4549)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$normalTypedApply$1$1.apply(Typers.scala:4548)
	at scala.tools.nsc.typechecker.Typers$Typer.onError$3(Typers.scala:4522)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4548)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4580)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5343)

```

### PR DESCRIPTION
**Pull request by milessabin**
`outerSelect` returns `EmptyTree` if it hits a `Symbol` with no outer accessor. `outerPath` doesn't check for this and will happily hand the returned `EmptyTree` back to outerSelect, and so on until stack overflow.
The fix is to check for an `EmptyTree` result and terminate.

Fixes scala/bug#10035.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala [hunk 1]
```diff
@@ -264,7 +264,11 @@ abstract class ExplicitOuter extends InfoTransform
     protected def outerPath(base: Tree, from: Symbol, to: Symbol): Tree = {
       //Console.println("outerPath from "+from+" to "+to+" at "+base+":"+base.tpe)
       if (from == to) base
-      else outerPath(outerSelect(base), from.outerClass, to)
+      else {
+        val outerSel = outerSelect(base)
+        if(outerSel == EmptyTree) EmptyTree
+        else outerPath(outerSelect(base), from.outerClass, to)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala]: Probably intended to use `outerSel` again. Also, space after if! Ahh! if is not a function call!

**Comment by som-snytt** [comment]
The PR title is very Zen.

File: src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala (hunk 1 above)
Comment (milessabin) [reply src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala]: Oh good grief ... inexcusable.

File: src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala [hunk 2]
```diff
@@ -264,7 +264,11 @@ abstract class ExplicitOuter extends InfoTransform
     protected def outerPath(base: Tree, from: Symbol, to: Symbol): Tree = {
       //Console.println("outerPath from "+from+" to "+to+" at "+base+":"+base.tpe)
       if (from == to) base
-      else outerPath(outerSelect(base), from.outerClass, to)
+      else {
+        val outerSel = outerSelect(base)
+        if (outerSel == EmptyTree) EmptyTree
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala]: `if (outerSel.isEmpty)` is idiomatic, it turns out.

**Review by som-snytt — APPROVED** [review]
Hey, it works! One style nit. I hesitate to call it that, because Miles is a style icon. I guess in the sense of lifestyle icon.

**Comment by milessabin** [comment]
Used `isEmpty` and squashed.
