### PR TITLE
`-Yrelease` supplements `-release`, allows access to additional JVM packages

### LINKED ISSUE #12643: [2.13.9] Can't reference `sun.` package classes with `-release` option
## Reproduction steps

```scala
class A {
  classOf[sun.misc.Unsafe]
}
```

### Java 8 without `-release` option

Success

```sh
$ java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Zulu 8.62.0.19-CA-macos-aarch64) (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Zulu 8.62.0.19-CA-macos-aarch64) (build 25.332-b09, mixed mode)
$ scala -version
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac A.scala 
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
1 warning
```

### Java 8 with `-release:8` option

Success

```sh
$ scalac -release:8 A.scala
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
1 warning
```

### Java 11 without `-release` option

Success

```sh
$ java -version
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
$ scala -version
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac A.scala           
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
1 warning
```

### Java 11 with `-release:11` option

Success

```sh
$ java -version 
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
$ scala -version
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac -release:11 A.scala
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
1 warning
```

### Java 11 with `-release:8` option

Failure !?

```sh
$ java -version            
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
$ scala -version            
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac -release:8 A.scala 
A.scala:2: error: not found: value sun
  classOf[sun.misc.Unsafe]
          ^
1 error
```

### Java 11 with `-target:jvm-1.8` option

Success

```sh
$ java -version                
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
$ scala -version                
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac -target:jvm-1.8 A.scala
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
warning: 1 deprecation; re-run with -deprecation for details
2 warnings
```

### PR DESCRIPTION
**Pull request by som-snytt**
Legacy usage of `sun.misc.Unsafe` makes it difficult to leverage `-release` in a build, since the internal class is not available as API. To enable this common use case, `-Yrelease` is introduced to allow access to specified platform packages. 

For example, `-release:8 -Yrelease:sun.misc`.

This "private" option is a convenience intended to support a project while migrating away from using `Unsafe`.

Fixes scala/bug#12643

### CODE REVIEW

**Comment by SethTisue** [comment]
@som-snytt it seems likely we'll merge this. but by merge time we'll need a public-facing PR description explaining what this does and when it's needed. but I think it would actually be helpful if you provided that now, to help reviewers?

**Comment by SethTisue** [comment]
Another thought: do you intend to port this to Scala 3? We're always a bit reluctant to add things to Scala 2 unless the path to supporting them in 3 as well is clear. That's partly because the 3 folks aren't happy if they feel we are putting pressure on them to support things they don't want to support, and also partly because users can be annoyed or disappointed if the two versions seem gratuitously misaligned to them.

Do we know if the workaround suggested on the scala/bug ticket also works in Scala 3? Because if it does, that would ease the 2 vs 3 tension here a bit, since 3 users wouldn't be blocked.

**Comment by som-snytt** [comment]
`-Yunsafe` is a convenience to get a Scala 2 project to use `--release`, for a net gain in API safety without too much hassle.

A project that is cross-built probably has the machinery to build against the jar of its choice, if `Unsafe` is part of its long-term strategy, so that would not be a use case supported by this private option.

**Comment by SethTisue** [comment]
Nice description — thank you.

Let's ponder the naming, prior to merge. `-Yunsafe`'s broadness is a bit cryptic and threatening. Maybe something that makes it clear it's 1) a very specific/niche thing, and/or 2) a modifier to `--release`? like `-Yrelease-include-unsafe` or `-Yopen-internal-packages` something? thinking out loud

File: src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala [hunk 1]
```diff
@@ -145,28 +145,52 @@ object JrtClassPath {
...
-              val classPath = ctSymClassPathCache.getOrCreate(v, ctSym :: Nil, () => new CtSymClassPath(ctSym, v.toInt), closeableRegistry, true)
-              Some(classPath)
-            }
-          } catch {
-            case _: Throwable => None
+        case Some(version) if version.toInt < currentMajorVersion =>
+          val ct = createCt(version, closeableRegistry)
+          unsafe match {
+            case Some(pkgs) =>
+              val open = if (pkgs.isEmpty) List("sun.misc") else pkgs
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala]: Maybe skip the default? It gives more work for documentation.

File: src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala [hunk 2]
```diff
@@ -145,28 +145,52 @@ object JrtClassPath {
...
+}
+
+final class FilteringJrtClassPath(delegate: JrtClassPath, allowed: String*) extends ClassPath with NoSourcePaths {
+  private val allowedPackages = allowed
+  private def packagePrefix(p: String, q: String) = p.startsWith(q) && (p.length == q.length || p.charAt(q.length) == '.')
+  private def ok(pkg: PackageName) = pkg.dottedString.isEmpty || allowedPackages.exists(packagePrefix(_, pkg.dottedString))
+  def asClassPathStrings: Seq[String] = delegate.asClassPathStrings
+  def asURLs: Seq[java.net.URL] = delegate.asURLs
+  private[nsc] def classes(inPackage: PackageName) = if (ok(inPackage)) delegate.classes(inPackage) else Nil
+  def findClassFile(className: String) = delegate.findClassFile(className)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala]: Also filter here?

**Review by lrytz — COMMENTED** [review]
This LGTM, it's a very nice idea!

File: src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala]: When I updated the PR comment, I realized no one will use `-Yunsafe:some.weird.pkg`; they will only use `-Yunsafe`.

File: src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala]: I only guessed here. The API ought to be: first query a package, then use that result to do class operations.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala]: Intuitively I'd add the filter here. Would you do a forward port to DOT·E?

File: src/compiler/scala/tools/nsc/settings/ScalaSettings.scala [hunk 3]
```diff
@@ -264,6 +264,7 @@ trait ScalaSettings extends StandardScalaSettings with Warnings { _: MutableSett
 
   val Youtline        = BooleanSetting    ("-Youtline", "Don't compile method bodies. Use together with `-Ystop-after:pickler` to generate the pickled signatures for all source files.").internalOnly()
 
+  val unsafe = MultiStringSetting("-Yunsafe", "packages", "Expose platform packages under --release")
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/settings/ScalaSettings.scala]: Maybe the name is a bit too generic? I see the relation to `misc.unsafe`, but still.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/ScalaSettings.scala]: `-Ymisc-unsafe`? `-Yunsafe-misc`? Don't make me break open `-Zmisc.unsafe`. Maybe Seth will have an idea.

File: src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala [hunk 4]
```diff
@@ -145,28 +145,52 @@ object JrtClassPath {
...
+  private def createCt(v: String, closeableRegistry: CloseableRegistry): List[ClassPath] =
+    try {
+      val ctSym = Paths.get(javaHome).resolve("lib").resolve("ct.sym")
+      if (Files.notExists(ctSym)) Nil
+      else {
+        val classPath = ctSymClassPathCache.getOrCreate(v, ctSym :: Nil, () => new CtSymClassPath(ctSym, v.toInt), closeableRegistry, checkStamps=true)
+        List(classPath)
+      }
+    } catch {
+      case _: Throwable => Nil
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala]: this is a bit lazy

File: src/compiler/scala/tools/nsc/settings/ScalaSettings.scala (hunk 3 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/ScalaSettings.scala]: `-Yopen-packages`

File: src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala]: I forgot to look at this before pushing.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala]: Lukas, you clever man, I see you force pushed it last week.

I'm willing to submit a PR to dotty, but I'm not willing to sweat whether they look at it.

**Comment by som-snytt** [comment]
Instead of `release-notes` the label should be `--release notes`.

I assUME that `NonFatal` is adequate. I don't remember if I had noticed something thrown such as a LinkageError (to guess).

**Review by lrytz — COMMENTED** [review]
LGTM. @SethTisue wdyt about the flag name `-Yopen-packages`?

**Comment by som-snytt** [comment]
Maybe it should be `allow-packages`. I was thinking of modules. Edit: `use-packages`? oh, `require-packages`.

File: src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala (hunk 2 above)
Comment (SethTisue) [reply src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala]: > I'm willing to submit a PR to dotty, but I'm not willing to sweat whether they look at it

heh, fair enough

**Comment by SethTisue** [comment]
I'm almost ready to hit "approve" here, only remaining concerns are naming and doc

> wdyt about the flag name -Yopen-packages?

@som-snytt what is the relationship between this new flag and `--add-opens`? I'm asking for my own understanding, and also because it could affect the naming, and also because it could affect what we put in the PR description

P.S. needs rebase!

**Comment by som-snytt** [comment]
Apparently, `-Yunsafe` was the right name all along. Who's been messing with DirectoryClassPath?

An interesting post-mortem would be rates of change to modules (classes and packages), as a measure of what was so complicated.

**Comment by He-Pin** [comment]
Thank you for this.
Will there a '-Yexport-packages' too？

**Comment by som-snytt** [comment]
This is just for considering packages on the real class path during compilation. Clearly it needs a better name

`-Yrerelease`? Because you use it when `--release` which hides the package and you want to `release` it for use. `-Yunrelease`.

oh just `--release:8,sun.misc` because you're saying use release 8 of the API but include this extra package.

**Comment by som-snytt** [comment]
`--release:8,sun.misc` would be nice, but it also creates a cross-building burden, besides complicating help and parsing.

Instead, we get a companion option `-Yrelease:sun.misc` which allows look-ups in the named packages when `--release` is set by the user.

**Comment by He-Pin** [comment]
@mdedetrich ping, pekko/akka can make use of it in future

**Comment by mdedetrich** [comment]
Yup, it has to be released in Scala 2.12/2.13/3.3.x for us to use it though

**Comment by som-snytt** [comment]
That could happen! I might need a reminder...

**Comment by mdedetrich** [comment]
> That could happen! I might need a reminder...

Ive been told I'm good at that, to the detriment of societies sanity

**Comment by SethTisue** [comment]
@som-snytt what is the relationship between this new flag and `--add-opens`? I'm asking for my own understanding, and also because it could affect the naming, and also because it could affect what we put in the PR description

What does the current workaround look like? Could someone point me to the relevant section of the Akka build or the Pekko build?

I think `-Yrelease` might be an okay name, but I'd like to understand this whole thing better.

**Comment by som-snytt** [comment]
@SethTisue this hasn't to do with modules, but with the `--release` mechanism, where the available platform API is defined by the ct.sym (and not by rt.jar). This just asks for a "backup" jrt class path that allows only the given package for look-up.

Practically, it's to support access to `sun.misc.Unsafe`, which is not a platform module but unsupported stuff. There is a JDK ticket to come up with replacements, but that is not yet the case even for projects willing to migrate.

Note to self: does `a.b.c` also allow classes of `a` and `a.b`?

**Review by SethTisue — APPROVED** [review]
to @lrytz for final review/merge

**Comment by SethTisue** [comment]
> What does the current workaround look like? Could someone point me to the relevant section of the Akka build or the Pekko build?

Still curious about this, if @mdedetrich or @He-Pin or somebody could answer.

**Comment by He-Pin** [comment]
@SethTisue This code origin from Akka too, some kind of this.
https://github.com/apache/incubator-pekko/blob/main/project/JdkOptions.scala#L69

**Comment by SethTisue** [comment]
Thanks @He-Pin — though I see now we already had this same exchange over at https://github.com/scala/bug/issues/12643 😆

**Review by lrytz — APPROVED** [review]
Thank you! This is a nice improvement.
