### PR TITLE
Standard extrapolator processes escapes

### LINKED ISSUE #12893: Dual string interpolator not processing strings with escaped characters
## Reproduction steps

Scala version: 2.13 onwards (including scala 3) for Java 8.

```scala
scala> val s"Hello\t$name" = "Hello\tJames"
scala.MatchError: Hello James (of class java.lang.String)
  ... 32 elided

scala> val s"Hello\n$name" = "Hello\nJames"
scala.MatchError: Hello
James (of class java.lang.String)
  ... 32 elided
```

## Problem

In both cases, the expected behavior is that `name` would be bound to "James", but instead a `MatchError` is thrown.

See also [original SO post](https://stackoverflow.com/questions/77226021/scalas-dual-string-interpolation-not-working-with-escaped-characters) where this was raised. This happens when other escaped characters are involved like "\\", "\"", "\r".

## Background

This dual interpolation feature was introduced into scala 2.13 by [PR 7387](https://github.com/scala/scala/pull/7387).

It added an `s.unapply` method for destructuring strings based on interpolation patterns. The underlying implementation for that is the `glob` method which I analyze below.

```
object s {
  ...
  def unapplySeq(s: String) = StringContext.glob(parts, s)
}

object StringContext {
  ...
  def glob(patternChunks: Seq[String], input: String): Option[Seq[String]] = ...
}
```

## Investigation

I have done some preliminary investigation and I believe the root cause is that the `parts` produced in the examples above are representing an escaped character as _two_ separate characters, e.g. a tab character becomes a backslash and a "t". But the `glob` function introduced in the PR 

For example code like this:

```scala
val s"$a\t$b" = "0\t1"
```

leads to a `StringContext` being constructed with parts:

```
Seq(
  "", // empty string for the text prior to "$a"
  "\\t", // string of length 2, a backslash, then a 't'
  "", // empty strong for the text after "$b"
)
```

The `glob` method is effectively called with this data:

```scala
glob(Seq("", "\\t", ""), "0\t1")
// returns None
```

Because it returns `None`, the `s.unapplySeq` returns `None` and the pattern match fails leading to a `MatchError`.

I verified this using a debugger and setting a breakpoint inside the glob method.

When `glob` is passed the expected data, a `Some` is returned as expected:

```scala
glob(Seq("", "\t", ""), "0\t1")
// Option[Seq[String]] = Some(value = ArraySeq("0", "1"))
```

So I think the "bug" is either:

- `StringContext` parts aren't being produced correctly with regards to escaped characters
- `StringContext` parts _are_ being produced correctly with regards to escaped characters, but `glob` incorrectly assumes they'll be a single character

## Other notes

The behavior appears to be consistent for any scala version from 2.13+ and the java version isn't relevant.

On my SO post, I asked if this feature has an official name. That would be helpful going forward for documenting this and doing searches. For now I'm calling it the "dual string interpolator".

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12893

### CODE REVIEW

File: src/library/scala/StringContext.scala [hunk 1]
```diff
@@ -127,7 +127,7 @@ case class StringContext(parts: String*) {
      *  Here, we use the `TimeSplitter` regex within the `s` matcher, further splitting the
      *  matched string "10.50" into its constituent parts
      */
-    def unapplySeq(s: String): Option[Seq[String]] = glob(parts, s)
+    def unapplySeq(s: String): Option[Seq[String]] = glob(parts.map(processEscapes), s)
```
Comment (lrytz) [inline src/library/scala/StringContext.scala:130]: `processEscapes` can throw a `InvalidEscapeException`, should the exception be handled?

```
scala.StringContext$InvalidUnicodeEscapeException: invalid unicode escape at index 7 of Hello,\u
  at scala.StringContext$.loop$1(StringContext.scala:341)
```

Comment (som-snytt) [reply src/library/scala/StringContext.scala:130]: They asked on the PR if it should be a macro. Since they did not make it a macro, does `case s"\z"` throw when constructing the extractor? Sure.

Comment (lrytz) [reply src/library/scala/StringContext.scala:130]: 👍  I was just confirming.
