### PR TITLE
Find more doc vars and distinguish C from CC [ci: last-only]

### LINKED ISSUE #12681: Misleading documentation of Range.map - it returns an IndexedSeq not a Range
## Problem

image

The doc says map on Range returns a new Range but it returns an IndexedSeq (which defaults to Vector).

### LINKED ISSUE #12908: Buffer.padTo calls it shrinkable instead of growable
## Reproduction steps

https://www.scala-lang.org/api/current/scala/collection/mutable/Buffer.html#padTo[B%3E:A](len:Int,elem:B):CC[B]

## Problem

It's growable & shrinkable, but growing methods should call it growable.

There is a ticket for nuanced CC vs C or something, so it is probably the same effort to chisel how collections refer to themselves in doc macros.

### PR DESCRIPTION
**Pull request by som-snytt**
Look up doc vars in self-types to facilitate collection trait culture.

Introduce ccoll for natural language phrase for `CC`, alongside coll for `C` and Coll for the `CC` type.

Fixes scala/bug#12681
Fixes scala/bug#12908

### CODE REVIEW

**Comment by som-snytt** [comment]
It seems redundant for both a class and its companion to define `coll`.

**Comment by som-snytt** [comment]
This seems to trigger at site `IeeeOrdering` but then is found at `Double` and rendered somehow.

```
[warn] /home/jenkins/workspace/scala-2.13.x-validate-main/src/library/scala/math/Ordering.scala:548:10: Variable doubleOrdering undefined in comment for trait IeeeOrdering in trait IeeeOrdering
[warn]       * $doubleOrdering
[warn]          ^
```

**Comment by som-snytt** [comment]
todo, no interpolation in backticks, to avoid warning; assuming that is intended here.
```
[warn] /home/jenkins/workspace/scala-2.13.x-validate-main/src/reflect/scala/reflect/api/Internals.scala:379:49: Variable name undefined in comment for method markForAsyncTransform in trait InternalApi
[warn]      * @param method A method of the form `def $name($paramName: $ParamType): $T = $CODE`, where calls to `$CODE`
[warn]                                                 ^
```

**Comment by som-snytt** [comment]
Marked ready for review, but I'll undertake to look for other cases where the doc should use `ccoll`.

I think it would be nicer if I could write doc of the form, "Produce a $CC", and scaladoc knows how to pretty print that: natural language in doc or type name in code sample. (Similar to `implicitNotFound` message.)

**Comment by lrytz** [comment]
This looks like the right way to fix the documentation of `Range.map`.

There would be some follow up work to push this through all of the collections: replace uses of `$coll` with `$ccoll` in more methods, redefine `@define ccoll` in all subclasses, maybe also introdcue `$CColl` if needed. So wonder if we should just book the progress, or try to find someone to push this further first.

**Comment by som-snytt** [comment]
I didn't see more to tweak that day, but I also did not diff the doc for regressions.

I guess we can't go two weeks without tweaking `IterableOnce`. I'll rebase it.

IIRC ccoll is normally just coll. A tweak is necessary only for special cases.

File: src/compiler/scala/tools/nsc/ast/DocComments.scala [hunk 1]
```diff
@@ -60,16 +60,18 @@ trait DocComments { self: Global =>
   private def allInheritedOverriddenSymbols(sym: Symbol): List[Symbol] = {
     val getter: Symbol = sym.getter
     val symOrGetter = getter.orElse(sym)
-    if (!symOrGetter.owner.isClass) Nil
-    else symOrGetter.owner.ancestors map (symOrGetter overriddenSymbol _) filter (_ != NoSymbol)
+    if (symOrGetter.owner.isClass)
+      symOrGetter.owner.ancestors.map { ancestor =>
+        symOrGetter.matchingSymbol(ancestor, symOrGetter.owner.thisType)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/ast/DocComments.scala]: could have kept one-liner with placeholder syntax

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/ast/DocComments.scala]: No, the one-liner is quite long. I may have tried it that day. Its lengthiness looks familiar.

**Comment by lrytz** [comment]
> IIRC ccoll is normally just coll. A tweak is necessary only for special cases.

From the top of my head, BitSet, Range, but also

```
trait SortedSetOps[A, +CC[X] <: SortedSet[X], +C <: SortedSetOps[A, CC, C]]
  extends SetOps[A, Set, C]
                    ^^^
```

not sure if some `SortedSet` operations fall back to returning `Set`?

About methods, shouldn't we use `$ccoll` on all methods that return `CC` (e.g., `collect`, `flatten`)?

**Comment by joshlemer** [comment]
> not sure if some `SortedSet` operations fall back to returning `Set`?

Correct, lots of operations lose the sortedness (map, flatmap, etc)

**Comment by lrytz** [comment]
> > not sure if some `SortedSet` operations fall back to returning `Set`?
> 
> Correct, lots of operations lose the sortedness (map, flatmap, etc)

In reality, calling those methods requires `.unsorted`:

```
scala> SortedSet(1,2,3).map(_ => new Object)
                           ^
       error: No implicit Ordering[Object] found to build a SortedSet[Object]. You may want to upcast to a Set[Int] first by calling `unsorted`.
```

But the overload still shows up in Scaladoc and it's not correct:

image

**Comment by som-snytt** [comment]
It may be necessary to validate under dottydoc as well. Hopefully it just works the same. 🤞 

image

image

Actually I was looking for the typo in `mutable.Sortedset` [sic]:

image

I noticed the typo in the definition, but grepping html for where it pops out is not efficient or effective. "There must be a tool that people use."

**Comment by som-snytt** [comment]
It's about 50/50 whether I can switch to an old branch, rebase, and work without restarting sbt.
```
[error] scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object Predef
```

**Comment by som-snytt** [comment]
> Introduce ccoll for natural language phrase for `CC`, alongside coll for `C` and Coll for the `CC` type.

The punning mnemonic is `colloquial collection`.

**Comment by som-snytt** [comment]
On `SortedSet#map`, by coincidence I just revived ancient https://github.com/scala/scala/pull/11033 on the theme of overloads that differ by just an implicit param list. That was to avoid confusion with nullary method, but I think it should be applied in general.

**Comment by lrytz** [comment]
> It's about 50/50 whether I can switch to an old branch, rebase, and work without restarting sbt.

Yeah, I often get that and need to `library/clean`. Fortunately builds are fast these days on modern (3.5 years old in my case) hardware.

**Comment by som-snytt** [comment]
Builds are fast, but waiting for sbt to start is still excruciating. (Only partly joking.) Next time I will try just library clean; I assumed something about compiler bridge broke so I always git clean, which is probably not needed. I owe you a beer or beverage of choice.

Also to note, I dreaded looking at this PR again, but actually after making a couple of Scaladoc tweaks just before going to sleep, now I'm excited to tweak more and maybe learn more about collections.

I'm also curious to jardiff what happens when all those inline annotations are removed. At one time, I started looking at the optimizer warnings: either it matters and we should care, or it really doesn't matter and we should not. I suppose Scala 3 will wind up with their "fork" before Scala 2 is finally put to rest.

**Comment by som-snytt** [comment]
To follow up, this commit adds some `$ccoll` to top-level, which is normally enough because that is just `$coll`.

Only `Range` has a different `ccoll` that I can see.

`Buffer` was lacking `define coll`. Worth adding that it's still a challenge to guess how anything will work, but it's nice when it does.

This commit does not solve the problem with overloaded, shadowed `SortedSet#map`.

Dotty has the same problem, but doesn't show the expected text.

image

I lodged that bug, see linked ticket.

**Comment by som-snytt** [comment]
The test failure is scaladoc use case blah blah, a challenge to summon the motivation to look into it. I have a debug commit that I put down and walked away from.

Edit: I had two (2!) small refactors that were wrong. Was someone coding after midnight?

Only one (1!) test failed; probably 92 scaladoc tests isn't enough.

**Review by lrytz — APPROVED** [review]
👍 progress, thank you.

**Comment by lrytz** [comment]
> Only `Range` has a different `ccoll` that I can see.

Mhm.. follow-up possible, but this is tedious without tooling.

**Comment by som-snytt** [comment]
@lrytz thanks. Since I just noticed the flaws in dottydoc's Option page, I'll have to follow up with the rendering in "current API". One can assume nothing.

**Comment by som-snytt** [comment]
An adjacent question is the comment on `allInheritedOverriddenSymbols`, that it is a version that does not examine self-types (for some particular reason). That method is basically `sym.allOverriddenSymbols`, so did this PR expand where to find related doc, does it address the comment, and is that method still needed? Noticed again while looking at the fix for "bad position when doc var is not found". (These are not crucial questions, but relevant for Scaladoc 3. Can I stick a doc macro define in a self type, such that it is found there?)
