### PR TITLE
Fix false-positive unused warnings in for comprehensions [ci: last-only]

### LINKED ISSUE #10287: surprising unused warnings due to for comprehension desugaring
in 2.12.1 (and 2.11):
```
$ scala -Ywarn-unused
cat: /release: No such file or directory
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> object Foo {
     |   for {
     |     x <- Some(1 -> 2)
     |     y = 3
     |     (a, b) = x
     |   } yield (a + b)
     | }
<console>:14: warning: local val in value $anonfun is never used
           (a, b) = x
            ^
<console>:14: warning: local val in value $anonfun is never used
           (a, b) = x
               ^
defined object Foo
```
I get a warning that neither `a` nor `b` are used, although they are clearly used.  No warning is issued for `y`, which is indeed unused.

In 2.12.2, no warnings are issued for `a` or `b` (yay) or `y` (boo).  I acknowledge I may be doin' it wrong!
```
21:34 lawn-128-61-43-99:~/opensource/rho (master)$ scala -Ywarn-unused:_
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> object Foo {
     |   for {
     |     x <- Some(1 -> 2)
     |     y = 3
     |     (a, b) = x
     |   } yield (a + b)
     | }
defined object Foo
```

Side note, I would love to be able omit `x` altogether and use
```
object Foo {
  for {
    (a, b) <- MyObjectHavingFlatmap(1 -> 2)
  } yield (a + b)
}
```
without calling `.filter`, which is a bit scary to me.

### PR DESCRIPTION
**Pull request by som-snytt**
`-Wunused:patvars` correctly warns for unused pattern variables in `for` comprehensions.

In the following snippet, both vars are pattern vars:
```
for (x <- e; y = x) yield y
```
and both are "used".

There is no warning when introducing a canonical parameter name:
```
case class C(x, y, z)
c match { case C(x, y, z) => true }
```

Fixes scala/bug#10287

Also improves by sorting altogether.

### CODE REVIEW

**Comment by som-snytt** [comment]
The first swing used an attachment `UserVar` that indicated the "original patvar". Duplicating the pat tree would just copy the attachment.

The hangup is that the Bind is converted to a ValDef (for either param to map or assignment), but only after the original has been duplicated. Creating the ValDef "in advance" was a bit messy.

The second swing uses `VarAlias` to point to a chain of trees, the last of which is taken as original. Then the valdef conversion just sticks the new tree at the head. The old head (the original pat tree) is never used or typechecked.

Previously, there was a `forFor` flag for the pat var traverser to suppress warnings. Now the flag is for `mkPatDef` to know if `val x` is a patvar.

This PR treats `for x <- g; y = x` taking `y` as a patvar. There is a Dotty ticket asking whether the RHS of assignment is subject to `-Wnonunit-statement`, even for `_ = expr`. As a first step, we clarify here that x and y are patterns and remain patvars for warning purposes, even if `g.map(x => expr)` or `val y = expr` appears in the desugared elaboration.

**Comment by SethTisue** [comment]
needs rebase

File: test/files/neg/warn-unused-params.scala [hunk 1]
```diff
@@ -94,7 +94,7 @@ trait Anonymous {
 
   def f2: Int => Int = _ + 1  // no warn placeholder syntax (a fresh name and synthetic parameter)
 
-  def g = for (i <- List(1)) yield answer    // warn map.(i => 42)
+  def g = for (i <- List(1)) yield answer    // no warn patvar elaborated as map.(i => 42)
```
Comment (lrytz) [inline test/files/neg/warn-unused-params.scala:97]: can you elaborate on this change..?

**Review by lrytz — APPROVED** [review]
awesome to have this fixed after so long! thank you.

File: test/files/neg/warn-unused-params.scala (hunk 1 above)
Comment (som-snytt) [reply test/files/neg/warn-unused-params.scala:97]: per the end of my comment above, this used to warn under "params" but now warns under "patvars" (because `i` is a pattern var).

**Comment by som-snytt** [comment]
Worth asking if patvars should be promoted to `-Xlint:unused`. It is less buggy; the question is whether people want it or would heed it. But params is in the same boat.

If I haven't done it yet, `case C(p)` should not warn if `p` is the param name; that is the same exclusion as for the shadowing check.

This is to say that matching on `C` "naturally" brings its elements into scope, even if unused or shadowing.

Since everyone wants new syntax that reduces naming, it would be nice to automate
```
case c: C => import c.* // just params

case C(export) => // just a thought
```

**Comment by SethTisue** [comment]
> Worth asking if patvars should be promoted to -Xlint:unused. It is less buggy; the question is whether people want it or would heed it. But params is in the same boat

I don't think I see the downside, assuming it is no longer buggy? Do you have an example where the warning would be correctly issued, but you think users would find it just annoying...?
