### PR TITLE
Fix `-Wconf` and `-nowarn` to be more consistent

### LINKED ISSUE #12664: Reporter counts warnings when `-nowarn` is enabled
Because `-nowarn` is "just" setting `-Xmaxwarns 0`, warnings are not displayed but still counted in the reporter.

Maybe not a bug? Thoughts welcome. It's an easy fix in `FilteringReporter`.

```scala
Welcome to Scala 2.13.10 (OpenJDK 64-Bit Server VM, Java 17.0.1).
Type in expressions for evaluation. Or try :help.

scala> import scala.tools.nsc._
     | import scala.tools.nsc.interpreter._
     | import scala.tools.nsc.interpreter.shell._
     | val s = new Settings()
     | s.nowarn.value = true
     | val r = new ReplReporterImpl(s) { override def reset(): Unit = () } // interpreter calls `reset` after each line
     | val i = new IMain(s, r)
     | i.interpret("val x: Unit = 1")
     | r.warningCount
val x: Unit = ()
import scala.tools.nsc._
import scala.tools.nsc.interpreter._
import scala.tools.nsc.interpreter.shell._
val s: scala.tools.nsc.Settings =
Settings {
  -encoding = UTF-8
  -nowarn = true
  -Xmaxwarns = 0
}

// mutated s.nowarn.value
val r: scala.tools.nsc.interpreter.shell.ReplReporterImpl = $anon$1@594c66c3
val i: scala.tools.nsc.interpreter.IMain = scala.tools.nsc.interpreter.IMain@64e657b0
val res0: Int = 1
```

### LINKED ISSUE #12984: -Wconf can depend on order of other args, such as -deprecation
## Questions are not bug reports

What if it's a documentation bug?

I realize that's another question.

## Reproduction steps

Scala version: 2.13.13

https://github.com/scalameta/munit/pull/461

to exercise `-Wconf:cat=deprecation:s -Xlint` and upgrading a project.

## Problem

It still warns, even with `-Wconf:any:s`.

If I junkify the config, it tells me
```
[error] Failed to parse `-Wconf` configuration: List(cat=deprecation:w, junk:s, cat=unchecked:w, cat=feature:w, cat=deprecation:ws, cat=feature:ws, cat=optimizer:ws)
[error] unknown filter: junk
```
Ah, I thought a plugin was prepending to the config, but I just realized that `Xlint` sets `deprecation` which sets `-Wconf`.

But what if I only want to see some deprecations?

That is my third and final question.

Besides documenting the behavior, under `-verbose` it could echo settings or explain what's going on when a filter matches.

### PR DESCRIPTION
**Pull request by som-snytt**
Always respect user `-Wconf` settings, including `-nowarn`. Previously, some defaults were incorrectly enforced.

For example,
`-Wconf:cat=deprecation:e -deprecation -nowarn`
would fail to issue an error on deprecation, but now correctly works the same as
`-deprecation -nowarn -Wconf:cat=deprecation:e`

`-nowarn` sets `-Xmaxwarns:0` (which limits how many warnings are displayed) and also suppresses the "summary" messages that report a summary count, as well as suppressing the error under `-Werror` ("No warnings can be incurred"). It adds `any:s` to suppress any other warnings, and turns off `cat=scala3-migration:e` that boosts migration errors under `-Xsource:3`.

Fixes scala/bug#12984
Fixes https://github.com/scala/bug/issues/12664

Instead of adding wconf for deprecation when setting is selected, adjust the default filter when processing the configuration. This ensures that user config is respected in this respect.

Otherwise, subtle order dependency is not friendly.

Besides setting `maxwarns`, `nowarn` is a trailing `-Wconf:any:s`. That is, any unconfigured warnings are silenced. Configured warnings are counted and reported in the usual way, but summaries are silenced under `-nowarn`.

### CODE REVIEW

**Comment by som-snytt** [comment]
Somewhere in the `-Wconf` PR, there was a "reset setByUser", a facility I needed for the test (WConfTest.default).

Reporting adjusts the deprecation conf depending on deprecation.isSetByUser.

Note: revisit `reset` impls

**Comment by SethTisue** [comment]
@som-snytt if I'm a Scala user hurriedly/impatiently reading the 2.13.15 release notes, what is the upshot of this change for me...?

**Comment by SethTisue** [comment]
needs rebase

**Comment by lrytz** [comment]
> Instead of setting `maxwarn`, `nowarn` is a trailing `-Wconf:any:s`.

In the current form it's both (which is the right thing), not "instead".

**Review by lrytz — APPROVED** [review]

**Comment by som-snytt** [comment]
@lrytz thanks again for the care you take. I reviewed the changes again and updated the text.

File: src/compiler/scala/tools/nsc/Reporting.scala [hunk 1]
```diff
@@ -53,11 +53,29 @@ trait Reporting extends internal.Reporting { self: ast.Positions with Compilatio
...
-        else conf
+        // default is "cat=deprecation:ws,cat=feature:ws,cat=optimizer:ws"
+        // under -deprecation, "cat=deprecation:w", but under -deprecation:false or -nowarn, "cat=deprecation:s"
+        // similarly for -feature, -Wopt (?)
+        val needsDefaultAdjustment = settings.deprecation.isSetByUser
+        val adjusted =
+          if (needsDefaultAdjustment || settings.nowarn.value) {
+            val (user, defaults) = conf.filters.splitAt(conf.filters.length - settings.WconfDefault.length)
+            val Deprecation = MessageFilter.Category(WarningCategory.Deprecation)
+            val action = if (settings.deprecation.value) Action.Warning else Action.Silent
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/Reporting.scala:64]: Worth following up whether `-deprecation -nowarn` does the obvious thing (whatever that is). With a custom reporter, there could be a difference between "what is displayed" and "warnings that reach the reporter"?
