### PR TITLE
Un-deprecate default floating point Orderings; issue migration warning instead under -Xmigration

### LINKED ISSUE #11844: List(1.0, -1.0).sorted gives a deprecation warning
_Originally posted by @odersky in https://github.com/scala/bug/issues/10511#issuecomment-569510889_

Ref scala/scala#6323
Ref scala/scala#6410

## steps

```scala
scala> List(1.0, -1.0).sorted
warning: there was one deprecation warning (since 2.13.0); for details, enable `:setting -deprecation' or `:replay -deprecation'
res0: List[Double] = List(-1.0, 1.0)
```

## problem

It gives a deprecation warning. I think this is _very bad_, not to say catastrophic.

## expectation

These things should just work. I don't care what ordering is used and whether it is inconsistent or not (we all know IEEE is broken and unfixable). But we should do the right thing for everyday users. As an everyday user I do not care what the ordering does for NaN and -0.0, maybe I do not even know that these weird numbers exist! (and they should not exist, if I go by common mathematical logic). But I _do_ care that I can sort a list of doubles without going into the deeper mysteries of Scala's implicit system. This requirement is now violated. 

## notes

I think we should revert ASAP. We should keep the old total ordering and offer IEEE as an optional alternative that needs to be imported explicitly.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/scala/bug/issues/11844
Ref https://github.com/scala/bug/issues/10511
Ref https://github.com/scala/scala/pull/6410
Ref https://github.com/scala/scala/pull/76

This changes the deprecation of `DeprecatedDoubleOrdering` to a migration warning to avoid `List(1.0, -1.0).sorted` giving a deprecation warning.

This also provides some documentation on the ordering instances in Scaladoc:

The behavior of the comparison operations provided by the default (implicit) ordering on `Double` changed in 2.10.0 and 2.13.0. Prior to Scala 2.10.0, the `Ordering` instance used semantics consistent with `java.lang.Double.compare`.
 
Scala 2.10.0 changed the implementation of `lt`, `equiv`, `min`, etc., to be IEEE 754 compliant, while keeping the `compare` method NOT compliant, creating an internally inconsistent instance. IEEE 754 specifies that `0.0 == -0.0`. In addition, it requires all comparisons with `Double.NaN` return `false` thus `0.0 < Double.NaN`, `0.0 > Double.NaN`, and `Double.NaN == Double.NaN` all yield `false`, analogous `None` in `flatMap`.
 
Recognizing the limitation of the IEEE 754 semantics in terms of ordering, Scala 2.13.0 created two instances: `Ordering.Double.IeeeOrdering`, which retains the IEEE 754 semantics from Scala 2.12.x, and `Ordering.Double.TotalOrdering`, which brings back the `java.lang.Double.compare` semantics for all operations. The default extends `TotalOrdering`.
 
```scala
List(0.0, 1.0, 0.0 / 0.0, -1.0 / 0.0).sorted      // List(-Infinity, 0.0, 1.0, NaN)
List(0.0, 1.0, 0.0 / 0.0, -1.0 / 0.0).min         // -Infinity
implicitly[Ordering[Double]].lt(0.0, 0.0 / 0.0)   // true
{
  import Ordering.Double.IeeeOrdering
  List(0.0, 1.0, 0.0 / 0.0, -1.0 / 0.0).sorted    // List(-Infinity, 0.0, 1.0, NaN)
  List(0.0, 1.0, 0.0 / 0.0, -1.0 / 0.0).min       // NaN
  implicitly[Ordering[Double]].lt(0.0, 0.0 / 0.0) // false
}
```

### CODE REVIEW

File: src/library/scala/math/Ordering.scala [hunk 1]
```diff
@@ -369,7 +370,36 @@ object Ordering extends LowPriorityOrderingImplicits {
...
+    * Scala 2.10.0 changed the implementation of `lt`, `equiv`, `min` etc to be
+    * IEEE 754 compliant, while keeping `compare` method NOT compliant,
+    * creating an internally inconsistent instance. IEEE 754 specified that
+    * `0.0F == -0.0F`. In addition, all comparisons with `Float.NaN` must return
+    * `false` thus `0.0F < Float.NaN`, `0.0F > Float.NaN`, and
+    * `Float.NaN == Float.NaN` all yield `false`, analogous to `None`.
+    *
+    * Recognizing the limitation of the IEEE 754 semantics in terms of ordering,
+    * Scala 2.13.0 created two instances `Ordering.Float.IeeeOrdering` and
+    * `Ordering.Float.TotalOrdering`, which brings back the `java.lang.Float.compare`
```
Comment (NthPortal) [inline src/library/scala/math/Ordering.scala]: this wording is a bit ambiguous and kind of makes it seem like both `IeeeOrdering` and `TotalOrdering` both have `Float.compare` semantics, but only the latter does. While it should be obvious that `IeeeOrdering` has IEEE 754 semantics, it might be worth changing the wording to something like

> Scala 2.13.0 created two instances: `Ordering.Float.IeeeOrdering`, which retains the IEEE 754 semantics from Scala 2.12.x, and `Ordering.Float.TotalOrdering`, which brings back the `java.lang.Float.compare` semantics for all operations.

File: src/library/scala/math/Ordering.scala [hunk 2]
```diff
@@ -369,7 +370,36 @@ object Ordering extends LowPriorityOrderingImplicits {
...
+    *
+    *  {{{
+    *  List(0.0F, 1.0F, 0.0F / 0.0F, -1.0F / 0.0F).sorted      // List(-Infinity, 0.0, 1.0, NaN)
+    *  List(0.0F, 1.0F, 0.0F / 0.0F, -1.0F / 0.0F).min         // -Infinity
+    *  implicitly[Ordering[Float]].lt(0.0F, 0.0F / 0.0F)       // true
+    *  {
+    *    import Ordering.Float.IeeeOrdering
+    *    List(0.0F, 1.0F, 0.0F / 0.0F, -1.0F / 0.0F).sorted    // List(-Infinity, 0.0, 1.0, NaN)
+    *    List(0.0F, 1.0F, 0.0F / 0.0F, -1.0F / 0.0F).min       // NaN
+    *    implicitly[Ordering[Float]].lt(0.0F, 0.0F / 0.0F)     // false
```
Comment (NthPortal) [inline src/library/scala/math/Ordering.scala:399]: I like it! 👍

File: src/library/scala/math/Ordering.scala [hunk 3]
```diff
@@ -422,14 +452,46 @@ object Ordering extends LowPriorityOrderingImplicits {
     }
     implicit object IeeeOrdering extends IeeeOrdering
   }
-  @deprecated("There are multiple ways to order Floats (Ordering.Float.TotalOrdering, " +
-    "Ordering.Float.IeeeOrdering). Specify one by using a local import, assigning an implicit val, or passing it " +
-    "explicitly. See their documentation for details.", since = "2.13.0")
+  @migration(
+    "  The new ordering does not affect the sorting, placing NaN at the end.\n" +
+    "  However, methods such as `lt`, `min`, and `equiv` now match `compare`\n" +
+    "  instead of giving IEEE 754 behavior for -0.0F and NaN.\n" +
```
Comment (NthPortal) [inline src/library/scala/math/Ordering.scala]: I'd say "instead of having" rather than "instead of giving"

File: test/files/neg/ordering-migration.scala [hunk 4]
```diff
@@ -1,4 +1,4 @@
-// scalac: -deprecation -Xfatal-warnings
+// scalac: -Xmigration -Werror
```
Comment (NthPortal) [inline test/files/neg/ordering-migration.scala:1]: should this file be called `t11844.scala` instead?

**Review by NthPortal — APPROVED** [review]

File: src/library/scala/math/Ordering.scala (hunk 1 above)
Comment (eed3si9n) [reply src/library/scala/math/Ordering.scala]: 👍

File: test/files/neg/ordering-migration.scala (hunk 4 above)
Comment (eed3si9n) [reply test/files/neg/ordering-migration.scala:1]: I generally prefer English name for partests since it makes it easier to figure out what it's testing afterwards, and you can also grep easier from sbt shell.

File: src/library/scala/math/Ordering.scala (hunk 1 above)
Comment (eed3si9n) [reply src/library/scala/math/Ordering.scala]: Addressed in acf7044

File: src/library/scala/math/Ordering.scala (hunk 3 above)
Comment (eed3si9n) [reply src/library/scala/math/Ordering.scala]: acf7044

File: test/files/neg/ordering-migration.scala (hunk 4 above)
Comment (dwijnand) [reply test/files/neg/ordering-migration.scala]: If you're going to move it, move it to `pos`, seeing as it's no longer a negative test.

**Comment by dwijnand** [comment]
Suggested some tweaks: https://github.com/eed3si9n/scala/pull/1

**Review by SethTisue — APPROVED** [review]
squash before merge, otherwise LGTM, thanks Eugene, and thanks @NthPortal @Ichoran @odersky and everyone else who helped this along

**Review by szeiger — APPROVED** [review]

**Review by dwijnand — CHANGES_REQUESTED** [review]
Suggested some tweaks https://github.com/eed3si9n/scala/pull/1

**Comment by eed3si9n** [comment]
I just pulled @dwijnand's fix ups in. I'll squash them all now.

**Review by dwijnand — APPROVED** [review]
