### PR TITLE
Elim erased value types from sammy bridges

### LINKED ISSUE #10600: Scala compiler crash caused by AnyVal + Single Abstract Method
Scala versions tried: `2.12.3`, `2.12.4`

Code snippet: 
```scala
case class A(value: Int) extends AnyVal

case class B(value: Int) extends AnyVal

trait TypeClass[T] {
  def v(r: T): A
}

object TypeClass {
  val doesNotWork: TypeClass[B] = b => A(b.value)
  val works: TypeClass[B] =
    new TypeClass[B] {
      override def v(r: B) = A(r.value)
    }
}
```

Error:
```
[warn] an unexpected type representation reached the compiler backend while compiling Test.scala: ErasedValueType(class A, Int). If possible, please file a bug on https://github.com/scala/bug/issues.
scala.MatchError: ErasedValueType(class A, Int) (of class scala.reflect.internal.Types$UniqueErasedValueType)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.typeToBType(BTypesFromSymbols.scala:195)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.methodBTypeFromMethodType(BTypesFromSymbols.scala:129)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.methodBTypeFromSymbol(BTypesFromSymbols.scala:120)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.$anonfun$buildInlineInfoFromClassSymbol$6(BTypesFromSymbols.scala:577)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:473)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:479)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
```

### PR DESCRIPTION
**Pull request by hrhino**
Delambdafy looks at the info of SAMs exiting erasure, so that it can tell whether an unboxing conversion needs to be applied. If you look at infos exiting erasure, though, you will see `ErasedValueTypes`, which generally aren't valid types and under no circumstances should make it to the backend.

It turns out that the posterasure transformer was already being applied to the bridge def, but the symbols weren't getting the posterased type.

Fixes scala/bug#10600.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/Delambdafy.scala [hunk 1]
```diff
@@ -34,6 +34,7 @@ import scala.collection._
 abstract class Delambdafy extends Transform with TypingTransformers with ast.TreeDSL with TypeAdaptingTransformer {
   import global._
   import definitions._
+  import postErasure.{elimErasedValueType => postErase}
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/transform/Delambdafy.scala]: maybe more confusing than helping? i'd just use `postErasure.elimErasedValueType` at the callsites, some verbosity doesn't hurt for cross-phase-calls.

**Review by lrytz — COMMENTED** [review]
~Just guessing from your PR description, would it work to use `exitingPostErasure` instead of `exitingErasure` in Delambdafy?~

Edit: no that's not right

**Comment by lrytz** [comment]
~@hrhino pushed a commit - wdyt?~ meh

**Review by diesalbla — APPROVED** [review]

**Review by lrytz — APPROVED** [review]
