### PR TITLE
Literal/constant-typed local lazy vals need refined values.

### LINKED ISSUE #10792: Literal/constant typed local lazy vals result in type errors
Compiling the following with 2.13.x,
```scala
object Test {
  type Id[T] = T
  def foo(x: Int): Id[x.type] = x

  { lazy val result: 1 = foo(1) }
}
```
crashes with an unexpected type error during the Fields phase,
```
miles@tarski:scala (topic/local-lazy-new)% ./build/quick/bin/scalac -d out test/files/pos/local-lazy.scala
error: scala.reflect.internal.Types$TypeError: type mismatch;
 found   : Int
 required: 1
Exception in thread "main" scala.reflect.internal.Types$TypeError: type mismatch;
 found   : Int
 required: 1
```
This is because the translation of the local lazy val in Fields maps to a `LazyInt` which holds an `Int` value. This is too wide to assign to the `1`-typed val and results in a type error when the tree synthesized during Fields phase is typechecked.

Although this problem is a little to easier to surface with literal types, it actually predates 2.13.x. In 2.12.x the following,
```scala
object Test {
  type Id[T] = T
  def foo(x: String): Id[x.type] = x

  { lazy val result = foo("foo") }
}
```
crashes the compiler in the same way,
```
scala.reflect.internal.Types$TypeError: type mismatch;
 found   : String
 required: String("foo")
```
Here the type of `result` has been inferred as the constant type `String("foo")` which is too narrow for the synthesized `String` reference.

PR on its way ...

### PR DESCRIPTION
**Pull request by milessabin**
Compiling the following,
```scala
object Test {
  type Id[T] = T
  def foo(x: Int): Id[x.type] = x

  { lazy val result: 1 = foo(1) }
}
```
crashes with an unexpected type error during the Fields phase,
```
error: scala.reflect.internal.Types$TypeError: type mismatch;
 found   : Int
 required: 1
```
This is because the translation of the local lazy val in Fields maps to a `LazyInt` which holds an `Int` value. This is too wide to assign to the `1`-typed val and results in a type error when the tree synthesized
during Fields is typechecked.

I've fixed this by inserting a cast to the narrower type, which is eliminated during erasure. In principle we could switch to a scheme similar to `LazyUnit` for literal typed local lazy vals, ie. eliminating the storage for the value whilst retaining the effects, but this seems like an unlikely enough scenario to not warrant the additional complexity that this optimization would entail.

This fixes scala/bug#10792.

### CODE REVIEW

**Comment by adriaanm** [comment]
As discussed, we'll review in Berlin and give ourselves until M5 to refine.

File: src/compiler/scala/tools/nsc/transform/Fields.scala [hunk 1]
```diff
@@ -594,23 +594,31 @@ abstract class Fields extends InfoTransform with ast.TreeDSL with TypingTransfor
...
       val computerSym =
         owner.newMethod(lazyName append nme.LAZY_SLOW_SUFFIX, pos, ARTIFACT | PRIVATE) setInfo MethodType(Nil, lazyValType)
 
       val rhsAtComputer = rhs.changeOwner(lazySym -> computerSym)
 
       val computer = mkAccessor(computerSym)(gen.mkSynchronized(Ident(holderSym))(
-        If(initialized, getValue,
-          if (isUnit) Block(rhsAtComputer :: Nil, Apply(initialize, Nil))
-          else Apply(initialize, rhsAtComputer :: Nil))))
+        refineLiteral(
```
Comment (adriaanm) [inline src/compiler/scala/tools/nsc/transform/Fields.scala]: it feels weird the unit case is under the cast. Is there a way to cast a smaller expression?

**Comment by milessabin** [comment]
Narrowed the scope of the refinement, also rebased.

**Comment by milessabin** [comment]
@adriaanm this is ready to go now if you're happy.

**Review by adriaanm — APPROVED** [review]
