### PR TITLE
Runtime mirror must follow class loader

### LINKED ISSUE #11915: IMain.valueOfTerm returns obsolete values in Scala 2.13
## reproduction steps

I created [a repository to reproduce](https://github.com/Sciss/ScalaIssue11915). Compare the output of `sbt ++2.12.11 run`:

```
[info] res0: Int = 1234
[info] res0: Int = 5678
[info] run1: 1234, run2: 5678
```

with the output of `sbt ++2.13.1 run`:

```
[info] res0: Int = 1234
[info] res0: Int = 5678
[info] run1: 1234, run2: 1234
```

## problem

So while the reporter prints the correct values, getting them from user code via `valueOfTerm` is broken under Scala 2.13.

The invocation at hand is

```scala
trait Base {
  _: IMain =>

  def test(): Unit = {
    val run1 = eval("1234")
    val run2 = eval("5678")
    println(s"run1: $run1, run2: $run2")
  }

  def eval(source: String): Any = {
    reset()
    val res: Results.Result = interpret(source)

    res match {
      case Results.Success =>
        val n = mostRecentVar
        valueOfTerm(n).getOrElse(sys.error(s"No value for term $n"))

      case Results.Error      => sys.error("failed")
      case Results.Incomplete => sys.error("incomplete")
    }
  }
}
```

Going into the implementation of `valueOfTerm`, one finds that under 2.12, a fresh `SynchronizedSymbol` is seen for the two subsequent `res0`, whereas under 2.13, the same symbol is returned twice, and consequently the same (old) value is returned in the second run.

### PR DESCRIPTION
**Pull request by som-snytt**
Cache but clear the mirror when class loader is reset.

Fixes scala/bug#11915

### CODE REVIEW

File: src/repl/scala/tools/nsc/interpreter/IMain.scala [hunk 1]
```diff
@@ -90,6 +90,7 @@ class IMain(val settings: Settings, parentClassLoaderOverride: Option[ClassLoade
     *  on the future.
     */
   private var _classLoader: AbstractFileClassLoader = null  // active classloader
+  private var _runtimeMirror: reflect.runtime.universe.Mirror = null
```
Comment (dwijnand) [inline src/repl/scala/tools/nsc/interpreter/IMain.scala]: There's `ru`m for improvement.

**Review by dwijnand — APPROVED** [review]
Turns out to be part of the non-forward-ported #5657 (in case you're interested).

LGTM.

File: src/repl/scala/tools/nsc/interpreter/IMain.scala (hunk 1 above)
Comment (som-snytt) [reply src/repl/scala/tools/nsc/interpreter/IMain.scala]: rum would be an improvement right about now.

**Comment by som-snytt** [comment]
@dwijnand thanks, I had forgotten that but it comes back to me (to bite me). There are tickets to improve `:reset` from that time.
