### PR TITLE
Fix `ArrayBuilder` regression in Scala 2.13.13 (`OutOfMemoryError` when adding empty arrays)

### LINKED ISSUE #12971: `ArrayBuilder` regression in scala `2.13.13`, `OutOfMemoryError` when adding empty arrays
## Reproduction steps

Scala version: 2.13.13

The issue is reproducible only on scala `2.13.13`, because a recent patch to the `ArrayBuilder` triggered it, but the incriminated code is probably the same in every scala release: https://github.com/scala/scala/blob/5aa3dc5ea77800ddd2a3bdf9e7feeea57484421c/src/library/scala/collection/mutable/ArrayBuffer.scala#L326-L331

As you can see from the code above, if the `targetLen` is `0` the array length is doubled.

Here you can find a minimal test-case: https://github.com/alexdupre/scala-2.13.13-bug

Just `sbt run` to reproduce it.

## Problem

`OutOfMemoryError` because the underlying array is doubled at every iteration even if no elements have been added.

### PR DESCRIPTION
**Pull request by som-snytt**
Defer array resize on empty; `resizeUp` no longer resizes at target length zero.

`addAll` no longer assumes `elems` is allocated (non-null).

`ArrayBuffer` allocates eagerly anyway, so it is unaffected by not resizing at "default".

Fixes scala/bug#12971

### CODE REVIEW

File: src/library/scala/collection/mutable/ArrayBuffer.scala [hunk 1]
```diff
@@ -323,7 +323,7 @@ object ArrayBuffer extends StrictOptimizedSeqFactory[ArrayBuffer] {
       else if (targetLen < 0)
         throw new Exception(s"Overflow while resizing array of array-backed collection. Requested length: $targetLen; current length: $arrayLen; increase: ${targetLen - arrayLen}")
 
-    if (targetLen > 0 && targetLen <= arrayLen) -1
+    if (targetLen >= 0 && targetLen <= arrayLen) -1
     else {
       checkArrayLengthLimit()
```
Comment (OndrejSpanel) [inline src/library/scala/collection/mutable/ArrayBuffer.scala]: Is there any reason why is `checkArrayLengthLimit` a local function? To me it would be more readable if its content would be inlined, it would be easier to see what are various possibilities of `targetLen` and `arrayLen` values. If there are performance reasons, perhaps some comment should be in place?

Comment (som-snytt) [reply src/library/scala/collection/mutable/ArrayBuffer.scala]: maybe rename it `checkTargetLenInBounds`. There are two parameters and `arrayLen` is the one it does **not** check. But I see you mean the if-else if-else is easier to read.

Comment (som-snytt) [reply src/library/scala/collection/mutable/ArrayBuffer.scala]: I see that I moved the method to local but did not inline it "all the way". Probably I'm just out of practice with throwing exceptions.

File: test/junit/scala/collection/mutable/ArrayBuilderTest.scala [hunk 2]
```diff
@@ -32,4 +32,11 @@ class ArrayBuilderTest {
     // expect an exception when trying to grow larger than maximum size by addAll(array)
     assertThrows[Exception](ab.addAll(arr))
   }
+
+  // avoid allocating "default size" for empty, and especially avoid doubling capacity for empty
+  @Test def `addAll allocates elems more lazily`: Unit = {
+    val builder = ArrayBuilder.make[String]
+    (1 to 100).foreach(_ => builder.addAll(Array.empty[String]))
```
Comment (He-Pin) [inline test/junit/scala/collection/mutable/ArrayBuilderTest.scala:39]: What about a random test? 100 is too small, I think we should test the result of the builder too.

Comment (som-snytt) [reply test/junit/scala/collection/mutable/ArrayBuilderTest.scala:39]: You must read line 40.

File: src/library/scala/collection/mutable/ArrayBuilder.scala [hunk 3]
```diff
@@ -45,14 +45,16 @@ sealed abstract class ArrayBuilder[T]
...
+  /** Add all elements of an array. */
   def addAll(xs: Array[_ <: T]): this.type = addAll(xs, 0, xs.length)
 
-  /** Add a slice of an array */
+  /** Add a slice of an array. */
   def addAll(xs: Array[_ <: T], offset: Int, length: Int): this.type = {
-    ensureSize(this.size + length)
-    Array.copy(xs, offset, elems, this.size, length)
-    size += length
+    if (length > 0) {
```
Comment (He-Pin) [inline src/library/scala/collection/mutable/ArrayBuilder.scala:60]: if (length - offset > 1 && xs.isNotEmpty)

File: test/junit/scala/collection/mutable/ArrayBufferTest.scala [hunk 4]
```diff
@@ -392,6 +392,9 @@ class ArrayBufferTest {
 
     // check termination and correctness
     assertTrue(7 < ArrayBuffer.DefaultInitialSize) // condition of test
+    assertEquals(-1, resizeUp(7, 0))
+    assertEquals(-1, resizeUp(Int.MaxValue, 0))
+    assertEquals(ArrayBuffer.DefaultInitialSize, resizeUp(-1, 0)) // no check of arrayLen
```
Comment (He-Pin) [inline test/junit/scala/collection/mutable/ArrayBufferTest.scala:397]: add test case for `targetLen< 0`

File: src/library/scala/collection/mutable/ArrayBuffer.scala [hunk 5]
```diff
@@ -316,20 +316,12 @@ object ArrayBuffer extends StrictOptimizedSeqFactory[ArrayBuffer] {
...
-    if (targetLen > 0 && targetLen <= arrayLen) -1
-    else {
-      checkArrayLengthLimit()
-      if (arrayLen > VM_MaxArraySize / 2) VM_MaxArraySize
-      else math.max(targetLen, math.max(arrayLen * 2, DefaultInitialSize))
-    }
-  }
+  private[mutable] def resizeUp(arrayLen: Int, targetLen: Int): Int =
+    if (targetLen >= 0 && targetLen <= arrayLen) -1
+    else if (targetLen < 0) throw new Exception(s"Overflow while resizing array of array-backed collection. Requested length: $targetLen; current length: $arrayLen; increase: ${targetLen - arrayLen}")
```
Comment (OndrejSpanel) [inline src/library/scala/collection/mutable/ArrayBuffer.scala]:
```suggestion
    if (targetLen < 0) throw new Exception(s"Overflow while resizing array of array-backed collection. Requested length: $targetLen; current length: $arrayLen; increase: ${targetLen - arrayLen}")
    else if (targetLen <= arrayLen) -1
```

I think it would be more readable to reorder the cases, so that `targetLen` overflow is tested only once. It might even have some (probably unmeasurable) performance gain - the test was already done and there is no need to do it twice.

**Review by OndrejSpanel — COMMENTED** [review]
I think the more logical order would be to test for

**Review by lrytz — APPROVED** [review]
Thanks!

File: src/library/scala/collection/mutable/ArrayBuilder.scala (hunk 3 above)
Comment (som-snytt) [reply src/library/scala/collection/mutable/ArrayBuilder.scala:60]: I see, instead of `ensureSize` for some `length`, first make sure the capacity is needed.

xs.length != 0 && xs.length - offset > 0 and the effective length is min(length, xs.length - offset)

I think all this was deferred to `Array.copy` for convenience. But the downside of erroneously large length makes it worth guarding here.

File: test/junit/scala/collection/mutable/ArrayBufferTest.scala (hunk 4 above)
Comment (som-snytt) [reply test/junit/scala/collection/mutable/ArrayBufferTest.scala:397]: `checkExceedsMaxInt(-1)` added

**Review by OndrejSpanel — APPROVED** [review]
