### PR TITLE
Simplify reporters

### LINKED ISSUE #8908: Extend @uncheckedStable to allow stable defs
```scala
object pig {
  @scala.annotation.unchecked.uncheckedStable def dog = ()
  () match {
    case `dog` =>
  }
}

scala> error: stable identifier required, but pig.this.dog found.
           case `dog` =>
```

### PR DESCRIPTION
**Pull request by lrytz**
Messages are counted in the reporter, not in the Severity objects.
The Severity class is moved out of the reporter to the package, with
an `@uncheckedStable` trick to make pattern matching on severities
source-compatbile (Fixes https://github.com/scala/bug/issues/8908).

ContextReporter no longer extends Reporter. The ContextReporter is
only used in the context, and it reports through Global.reporter. But
it's never assigned to Global.reporter. So better keep the two
separate. This also saves the inherited fields (ContextReporters are
allocated manies, type checking every Apply uses silent).

Remove most reporter mixins to get to a linear inheritance structure,
no more delegating reporters.

Ignore the `force` parameter of `info0`.

Restores support for `-Xprompt` in the repl.

Some quirks to remain source compatible with the sbt compiler interface.
`nsc.reporters.Reporter` only exists for sbt compatibility, Global
has a `FilteringReporter`. `-Xreporter` must be a FilteringReporter.

### CODE REVIEW

**Comment by lrytz** [comment]
cc @ghik. ~Probably we need to open up the API a little to allow for more overrides. Perhaps `ForwardingReporter` (a reporter that delegates) should come back, but as a subclass of `FilteringReporter` so that it can be assigned to Global.reporter.~ Added a `ForwardingReporter`.

cc @som-snytt let me know what you think. I think preferring `internal.Reporter` in the compiler is an illusion. This PR makes it explicit that `Global.reporter` supports limits and does position filtering.

**Comment by som-snytt** [comment]
I think I would have clung to the illusion.

There was a reason the old regime was a problem. This returns to: `-Xreporter` must extend the thing. I think the illusory goal was to drop the old classes and all the glue code.

File: src/compiler/scala/tools/nsc/PipelineMain.scala [hunk 1]
```diff
@@ -566,7 +566,7 @@ class PipelineMainClass(argFiles: Seq[Path], pipelineSettings: PipelineMain.Pipe
               diagnostic.getKind match {
                 case Kind.ERROR => reporter.error(position, msg)
                 case Kind.WARNING | Kind.MANDATORY_WARNING => reporter.warning(position, msg)
```
Comment (adriaanm) [inline src/compiler/scala/tools/nsc/PipelineMain.scala:568]: For future reference, should this distinction be captured in the FilteringReporter interface?

File: src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+ * additional information regarding copyright ownership.
+ */
+
+package scala.tools.nsc.reporters
+import scala.reflect.internal.settings.MutableSettings
+import scala.reflect.internal.util.Position
+import scala.tools.nsc.Settings
+
+
+/** A ForwardingReporter that delegates to another ForwardingReporter. This class can be used to
```
Comment (adriaanm) [inline src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala]:
```suggestion
/** A FilteringReporter that delegates to another FilteringReporter. This class can be used to
```

File: src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+  * customize error reporting.
+  * {{{
+  *   val myReporter = new ForwardingReporter(global.reporter) {
+  *     override def doReport(pos: Position, msg: String, severity: Severity): Unit = { ... }
+  *   }
+  *   global.reporter = myReporter
+  * }}}
+  */
+class ForwardingReporter(delegate: FilteringReporter) extends FilteringReporter {
```
Comment (adriaanm) [inline src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala:28]: Can/should we seal this class?

**Review by adriaanm — APPROVED** [review]
Nice cleanup! A few small comments.

**Comment by som-snytt** [comment]
If you could leave this open another day, I may have comments. I unsquashed the last commit so I could follow along.

File: src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+  override def finish(): Unit = delegate.finish()
+  override def reset(): Unit = delegate.reset() // super.reset not necessary, own state is never modified
+
+  override def rerunWithDetails(setting: MutableSettings#Setting, name: String): String = delegate.rerunWithDetails(setting, name)
+}
+
+/** Used in `Global.reporter_=`. sbt assigns a plain `Reporter`, which is then adapted to respect
+  * maxerrs and do position filtering.
+  */
+class MakeFilteringForwardingReporter(delegate: Reporter, val settings: Settings) extends FilteringReporter {
```
Comment (mkeskells) [inline src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala:58]: It seems to me that this should be a factory method generating a filtered reported based on the setting, thus avoiding the reference to settings during the runtime, and improving performance

File: src/compiler/scala/tools/nsc/Global.scala [hunk 5]
```diff
@@ -85,20 +86,24 @@ class Global(var currentSettings: Settings, reporter0: LegacyReporter)
 
   override def settings = currentSettings
 
-  private[this] var currentReporter: LegacyReporter = { reporter = reporter0 ; currentReporter }
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/Global.scala:88]: I guess you didn't like this trick. BTW, this usage of `locally` is what inspired the recent PR. I just took this up again, and sbt tells me that this is where I left off...

File: src/compiler/scala/tools/nsc/reporters/Reporter.scala [hunk 6]
```diff
@@ -47,61 +50,104 @@ abstract class Reporter extends InternalReporter {
...
+
+/** The reporter used in a Global instance.
+  *
+  * It filters messages based on
+  *   - settings.nowarn
+  *   - settings.maxerrs / settings.maxwarns
+  *   - positions (only one error at a position, no duplicate messages on a position)
+  */
+abstract class FilteringReporter extends Reporter {
+  def settings: Settings
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/reporters/Reporter.scala:87]: It seemed obvious that FilteringReporter should take settings as a ctor param, as all reporters are required to have that ctor sig, but InteractiveReporter has an abstract compiler from which it derives settings.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/reporters/Reporter.scala:87]: I was literally just thinking, Nobody has to muck with settings at construction time, but:
```
  /**
   * Called before instantiating the presentation compiler's instance.
   * You should provide an implementation of this method if you need
   * to customize the `settings` used to instantiate the presentation compiler.
   * */
  protected def prepareSettings(settings: Settings): Unit = ()
```
Well, how about you take the compiler as an arg and they can do all their mucking about before they call you?

File: src/compiler/scala/tools/nsc/PipelineMain.scala (hunk 1 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/PipelineMain.scala:568]: Is the question whether we should have multiple kinds of warnings? I personally think simpler is better.

File: src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala (hunk 3 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala:28]: It's not actually used or subclassed in the compiler, the idea is to provide it as a utility to compiler plugins like silencer, maybe other tools.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala:28]: The thing I was going to try today was how easy to customize. I remember the whole point of blowing the functionality into traits was that the old AbstractReporter was too rigid.

File: src/compiler/scala/tools/nsc/reporters/Reporter.scala (hunk 6 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/reporters/Reporter.scala:87]: > FilteringReporter should take settings as a ctor param

Either way is fine with me, but I don't see a reason to prefer one or the other.

File: src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala (hunk 3 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala:28]: OK, let me know!

File: src/compiler/scala/tools/nsc/Global.scala (hunk 5 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/Global.scala:88]: > you didn't like this trick

Not that I didn't like it, it made me smile

File: src/compiler/scala/tools/nsc/reporters/Reporter.scala (hunk 6 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/reporters/Reporter.scala:87]: It's a clear signal or reminder to customizers that you must provide this constructor. Otherwise it's just documented somewhere, or not documented. I did spend a minute wondering if there is a reason to have a preference.

File: src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala (hunk 4 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala:58]: Settings can change in the lifetime of the reporter, in principle.

File: src/compiler/scala/tools/reflect/package.scala [hunk 7]
```diff
@@ -59,13 +58,13 @@ package object reflect {
...
     def display(info: Info): Unit = info.severity match {
-      case API_INFO => reporter.info(info.pos, info.msg, force = false)
+      case API_INFO => reporter.echo(info.pos, info.msg)
       case API_WARNING => reporter.warning(info.pos, info.msg)
       case API_ERROR => reporter.error(info.pos, info.msg)
     }
 
     def interactive(): Unit = reporter match {
-      case reporter: AbstractReporter => reporter.displayPrompt()
+      case reporter: PrintReporter => reporter.displayPrompt()
```
Comment (som-snytt) [inline src/compiler/scala/tools/reflect/package.scala]: It's lunch time, just confirming that `interactive` was intentionally removed.

Comment (lrytz) [reply src/compiler/scala/tools/reflect/package.scala]: Yes, i missed this one. The method is unused.

**Comment by som-snytt** [comment]
I didn't wind up going that way, but I will have a few suggestions.

I'm fixing up a few tests; also a few fail under jdk 11, I'm not sure there's another PR for that?

**Comment by som-snytt** [comment]
It turns out that I'm the guy who added

https://github.com/scala/scala/commit/bf4c304a71672d375e5f7d238e679b1826cc7489#diff-7be4d723ccf7e669e134ed85ea87b56b

and then deleted

https://github.com/scala/scala/commit/b0192f748626691d8252b756d92ded05eca78089#diff-7be4d723ccf7e669e134ed85ea87b56b

the `#partest java8` condition in checksensible.check. That test drives me crazy.

`--update-check` should at least confirm the update if it detects a conditional check!

File: src/compiler/scala/tools/nsc/reporters/Reporter.scala (hunk 6 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/reporters/Reporter.scala:87]: I didn't mean to persuade you!

Comment (lrytz) [reply src/compiler/scala/tools/nsc/reporters/Reporter.scala:87]: I'm not sure you did :-) But as I said, either way is fine with me.

[edit. reverted because]

Also it caused
```
+Caused by: java.lang.NullPointerException
+	at scala.tools.nsc.interactive.tests.InteractiveTestSettings.prepareSettings(InteractiveTestSettings.scala:50)
+	at scala.tools.nsc.interactive.tests.InteractiveTestSettings.prepareSettings$(InteractiveTestSettings.scala:39)
+	at scala.tools.nsc.interactive.tests.InteractiveTest.prepareSettings(InteractiveTest.scala:50)
+	at scala.tools.nsc.interactive.tests.core.PresentationCompilerInstance.compiler(PresentationCompilerInstance.scala:28)
+	at scala.tools.nsc.interactive.tests.core.PresentationCompilerInstance.compiler$(PresentationCompilerInstance.scala:27)
+	at scala.tools.nsc.interactive.tests.InteractiveTest.compiler$lzycompute(InteractiveTest.scala:50)
+	at scala.tools.nsc.interactive.tests.InteractiveTest.compiler(InteractiveTest.scala:50)
+	at scala.tools.nsc.interactive.tests.core.PresentationCompilerInstance.$init$(PresentationCompilerInstance.scala:23)
+	at scala.tools.nsc.interactive.tests.InteractiveTest.<init>(InteractiveTest.scala:51)
+	at Test$.<init>(Test.scala:3)
+	at Test$.<clinit>(Test.scala:3)
```

File: src/compiler/scala/tools/reflect/package.scala (hunk 7 above)
Comment (lrytz) [reply src/compiler/scala/tools/reflect/package.scala]: Also it caused
```
+Caused by: java.lang.NullPointerException
+	at scala.tools.nsc.interactive.tests.InteractiveTestSettings.prepareSettings(InteractiveTestSettings.scala:50)
+	at scala.tools.nsc.interactive.tests.InteractiveTestSettings.prepareSettings$(InteractiveTestSettings.scala:39)
+	at scala.tools.nsc.interactive.tests.InteractiveTest.prepareSettings(InteractiveTest.scala:50)
+	at scala.tools.nsc.interactive.tests.core.PresentationCompilerInstance.compiler(PresentationCompilerInstance.scala:28)
+	at scala.tools.nsc.interactive.tests.core.PresentationCompilerInstance.compiler$(PresentationCompilerInstance.scala:27)
+	at scala.tools.nsc.interactive.tests.InteractiveTest.compiler$lzycompute(InteractiveTest.scala:50)
+	at scala.tools.nsc.interactive.tests.InteractiveTest.compiler(InteractiveTest.scala:50)
+	at scala.tools.nsc.interactive.tests.core.PresentationCompilerInstance.$init$(PresentationCompilerInstance.scala:23)
+	at scala.tools.nsc.interactive.tests.InteractiveTest.<init>(InteractiveTest.scala:51)
+	at Test$.<init>(Test.scala:3)
+	at Test$.<clinit>(Test.scala:3)
```

**Comment by som-snytt** [comment]
I learned a few things over at https://github.com/scala/scala/pull/8366

I learned, for example, that I really hate the word "reporter". If you want to start a fight, just drop that word in my presence. Anything to do with error messages and filtering them or testing them just bugs the creepers out of me. I don't want to discuss them or hear them discussed or mentioned on the forums, ever again. That goes double for partests about reporting.

And if you want to see my head explode, just ask me if it's "reflect.internal" or "reflect.api".

Maybe Scala 3 can do without error messages entirely. Just ping my phone, and bring up a google page to browse the state of the code. People are always apologizing about editing a change and committing it to github without testing. But that's the way it should be! You make the edit on your phone, hit send, and then go back to whatever you were doing.

**Comment by som-snytt** [comment]
Oh, I see Lukas changed 53 files, but I changed 56. I'm not saying that means I win. But do I?

**Comment by lrytz** [comment]
I'll go through the [diff between your and my PR](https://github.com/lrytz/scala/commit/ef88b4e92434e053e0ba24c5f787059f306a22c0) and push (probably most of) the changes here, then we can merge?

**Comment by som-snytt** [comment]
As Ingrid Bergman tells Humphrey Bogart in Casablanca, you'll have to do the thinking for the both of us.

**Comment by lrytz** [comment]
@adriaanm / @szeiger good to go for 2.13.1?

**Comment by adriaanm** [comment]
I'll let Stefan decide, but good to go for me.

**Comment by som-snytt** [comment]
I was too busy to notice this went in. Thanks!
