### PR TITLE
Fix scala/bug#10094 - add regression test

### LINKED ISSUE #10094: Incorrect field initialization in specialized traits
Reported on scala-internals by Georgi Jojgov.

```scala
trait T[@specialized(Int) S] {
  def initialValue: S
  var value: S = initialValue
}

final class C[@specialized(Int) S](val initialValue: S) extends T[S]

object Test extends App {
  new C("hi")
}
```

Results in a `ClassCastException: String cannot be cast to Integer` at run-time.

The bad code is generated in constructors:

```
[[syntax trees at end of              constructors]] // Test.scala
...
  abstract trait T extends Object {
    ...
    def /*T*/$init$(): Unit = {
      T.this.value_=((T.this.initialValue(): Object));
      T.this.value$mcI$sp_=(scala.Int.unbox(T.this.value()));
    }
  }
```

when creating a `C[String]`, the unboxing of `value` will fail.

As a test case, here's a full example (as reported on the mailing list), it works in 2.11.8

```scala
trait BaseSp[@specialized(Long, Double) S] {
  def initialValue: S
  var value: S = initialValue
  override def toString = "" + value
}

trait BaseNotSp[S] {
  def initialValue: S
  var value: S = initialValue
  override def toString = "" + value
}

final class Bar_Sp_Sp    [@specialized(Long, Double) S](val initialValue: S) extends BaseSp[S]
final class Bar_NotSp_Sp [                           S](val initialValue: S) extends BaseSp[S]
final class Bar_Sp_NotSp [@specialized(Long, Double) S](val initialValue: S) extends BaseNotSp[S]
final class Bar_NotSp_NotSp                         [S](val initialValue: S) extends BaseNotSp[S]

object Test extends App {
  val a = new Bar_Sp_Sp[Double](Double.MaxValue)    // CCE
  val b = new Bar_Sp_Sp[Long](Long.MaxValue)        // CCE
  val c = new Bar_NotSp_Sp[Double](Double.MaxValue) // AbstractMethodError
  val d = new Bar_NotSp_Sp[Long](Long.MaxValue)     // CCE
  println((a, b, c, d))

  val e = new Bar_Sp_NotSp[Double](Double.MaxValue)
  val f = new Bar_Sp_NotSp[Long](Long.MaxValue)
  val g = new Bar_NotSp_NotSp[Double](Double.MaxValue)
  val h = new Bar_NotSp_NotSp[Long](Long.MaxValue)
  println((e, f, g, h))
}
```

### PR DESCRIPTION
**Pull request by joroKr21**
Didn't investigate in which version it progressed.

Closes https://github.com/scala/bug/issues/10094

### CODE REVIEW

File: test/files/run/t10094.scala [hunk 1]
```diff
@@ -0,0 +1,11 @@
+trait T[@specialized(Int) S] {
+  def initialValue: S
+  var value: S = initialValue
+}
+
+final class C[@specialized(Int) S](val initialValue: S) extends T[S]
+
+object Test {
+  def main(args: Array[String]): Unit =
+    println(new C("hi").initialValue)
```
Comment (som-snytt) [inline test/files/run/t10094.scala:10]: Worth noting that just assert saves a check file.

Comment (joroKr21) [reply test/files/run/t10094.scala:10]: TIL
