### PR TITLE
Fix AnnotationInfo when using named/default arguments, support custom annotation subclasses

### LINKED ISSUE #884: Fix AnnotationInfo when using defaults
```scala
scala> class ann(x: Int = 1, y: Int = 2) extends annotation.StaticAnnotation
class ann

scala> @ann(y = Nil.size) class K
        ^
       warning: Usage of named or default arguments transformed this annotation
       constructor call into a block. The corresponding AnnotationInfo
       will contain references to local values and default getters instead
       of the actual argument trees
class K

scala> typeOf[K].typeSymbol.annotations.head
val res0: $r.intp.global.AnnotationInfo = ann(x$2, x$1)

scala> typeOf[K].typeSymbol.annotations.head.original
val res1: $r.intp.global.Tree = <empty>
```

Before typing, the annotation is represented as `new ann(y = Nil.size)`. To construct the `AnnotationInfo`, that expression is type checked like ordinary code, resulting in

```scala
{
  val x$1 = Nil.size
  val x$2 = ann.<init>$default$1
  new ann(x$2, x$1)
}
```

The `AnnotationInfo` only has `ann(x$2, x$1)`, the block is thrown away it seems, there's now way get to the actual arguments.

Ideas
  - Minimum: attach the typed Block AST to the `AnnotationInfo`. But IMO this is not a good solution, it leaves processing annotations too difficult.
  - Never create blocks in NamesDefaults when typing an annotation. Evaluation order is not a concern, so `new ann(y = Nil.size)` can be typed as `new ann(<init>$default$1, Nil.size)`
  - Improve handling of defaults. It would be great if default values defined in the annotation declaration ended up in the `AnnotationInfo`, i.e., `new ann(1, Nil.size)`.

For the last one, the question is how to get to the default value AST. One option is to make the compiler attach it to to a symbol, so the `class ann` above would become

```
class ann(@defaultArg(1) x: Int, @defaultArg(2) y: Int) extends StaticAnnotation
object ann {
  <synthetic> def <init>$default$1 : Int = 1
  <synthetic> def <init>$default$2 : Int = 2
}
```

When constructing the `AnnotationInfo` from `new ann(<init>$default$1, Nil.size)` we can get the AST for the default from the annotation parameter symbol.

Earlier tickets: https://github.com/scala/bug/issues/7656, https://github.com/scala/bug/issues/9612

I did some prototyping when discussing `@apiStatus` (https://github.com/scala/scala/pull/8820 / https://github.com/scala/scala/compare/2.13.x...lrytz:constAnnDefaults). The goal here was to allow subclasses of annotations to define certain defaults, which would be great for `@nowarn`: https://github.com/scala/bug/issues/12367.

Fixing that at the same time would be good.

### PR DESCRIPTION
**Pull request by lrytz**
In an ordinary application `f(y = b, x = a)`, the compiler needs to create a block with local variables

```scala
{
  val x$1 = b
  val x$2 = a
  f(x$2, x$1)
}
```

in order to preserve evaluation order (`b` before `a`).

## Avoid named / default args transformation

For annotations `@ann(y = b, x = a)` this is not needed, and it makes annotation processing more difficult / impossible.

This PR disables the named / default arguments transformation for annotations.

## Inline default argument values (syntax trees)

Furthermore, when an annotation uses a default argument, the compiler inserts a copy of the default expression AST to the `AnnotationInfo` (instaead of a call to the `annot$init$default$1` method):

```scala
scala> :power
scala> class ann(x: Int = 1, y: Int = 2) extends annotation.Annotation
scala> @ann(y = 22) class C
scala> val i = typeOf[C].typeSymbol.annotations.head
val i: $r.intp.global.AnnotationInfo = ann(1, 22)
```

The `argIsDefault` method identifies which annotation arguments are defaults inserted by the compiler

```scala
scala> i.args.map(a => i.argIsDefault(a))
  List(true, false)
```

<details>
<summary><b>Details</b></summary>

The default expression ASTs are stored in meta-annotations so that they can be recovered later when using an annotation:

```scala
scala> typeOf[ann].typeSymbol.primaryConstructor.paramss.flatten.map(p => (p, p.annotations))
  List((value x,List(scala.annotation.meta.defaultArg(1))), (value y,List(scala.annotation.meta.defaultArg(2))))
```

The behavior with defaults differes betwen Java/ConstantAnnotation and other annotations.

In 2.13.15:
  - missing arguments for a Java/ConstantAnnotation are simply not present in `annotationInfo.assocs`
  - missing args for other annotations are present in `args` as `annot.init$default$1` method call ASTs

In order to remain mostly compatible, in this PR:
  - `assocs` still returns only explicit arguments, the new `annotationInfo.assocsWithDefaults` method extends `assocs` with the default values
  - default arguments in `args` are now an AST corresponding to the default expression.

Internally, default annotation arguments inserted by the compiler have the `arg.tpe` tagged with an `@defaultArg`:

```scala
scala> class ann(x: Int = 1) extends annotation.Annotation
scala> @ann() class K

scala> :power

scala> val info = typeOf[K].typeSymbol.annotations.head
val info: $r.intp.global.AnnotationInfo = ann(1)

scala> info.args.head.tpe
val res1: $r.intp.global.Type = Int(1) @scala.annotation.meta.defaultArg

scala> info.argIsDefault(info.args.head)
val res2: Boolean = true
```
</details>

## Support user-defined annotation subclasses

This PR also adds support for user-defined annotation subclasses. The `annotationInfo.argsForSuper` method returns the corresponding annotation arguments:

```scala
scala> class sub(z: Int) extends ann(11, z)
scala> @sub(z = 33) class D

scala> val info = typeOf[D].typeSymbol.annotations.head
val info: $r.intp.global.AnnotationInfo = sub(33)

scala> info.argsForSuper(typeOf[ann].typeSymbol)
val res5: List[$r.intp.global.Tree] = List(11, 33)
```

<details>
<summary><b>Details</b></summary>
Arguments passed to the super annotation are encoded in yet more meta annotations:

```scala
scala> typeOf[sub].typeSymbol.annotations
val res6: List[$r.intp.global.AnnotationInfo] = List(scala.annotation.meta.superArg("x", 11), scala.annotation.meta.superFwdArg(p = "y", n = "z"))
```
</details>

## Custom `@nowarn` subclasses

Finally, this PR adds support for custom `@nowarn` subclasses

```scala
scala> class nodep extends annotation.nowarn("cat=deprecation")
scala> @nodep def f = Map().mapValues(identity)
def f: scala.collection.MapView[Nothing,Nothing]
```

-----

Fixes https://github.com/scala/scala-dev/issues/884, https://github.com/scala/bug/issues/7656, https://github.com/scala/bug/issues/9612, https://github.com/scala/bug/issues/12367

Ticket for Scala 3 forward port: https://github.com/scala/scala3/discussions/22414

### CODE REVIEW

**Comment by lrytz** [comment]
Added support for default arguments.

The behavior differes betwen Java/ConstantAnnotation and other annotations.

In 2.13.15:
  - missing arguments for a Java/ConstantAnnotation are simply not present in `annotationInfo.assocs`
  - missing args for other annotations are present in `args` as `annot.init$default$1` method call ASTs

In order to remain mostly compatible, in this PR:
  - `assocs` still returns only explicit arguments, the new `annotationInfo.assocsWithDefaults` method extends `assocs` with the default values
  - default arguments in `args` are now an AST corresponding to the default expression. The new `annotationInfo.argIsDefault(arg)` method tells whether an whether an argument was explicitly given or a default inserted by the compiler. Internally this is represented by tagging the `arg.tpe` with an annotation:

```scala
scala> class ann(x: Int = 1) extends annotation.Annotation
scala> @ann() class K

scala> :power

scala> val info = typeOf[K].typeSymbol.annotations.head
val info: $r.intp.global.AnnotationInfo = ann(1)

scala> info.args.head.tpe
val res1: $r.intp.global.Type = Int(1) @scala.annotation.meta.defaultArg

scala> info.argIsDefault(info.args.head)
val res2: Boolean = true
```

**Comment by lrytz** [comment]
Added support for subclassing annotations, so `class nodep extends nowarn("cat=deprecation")` works now.

**Comment by lrytz** [comment]
Updated the PR description with all the changes.

I had to introduce a typer mode (`ANNOTmode`) because we still need to perform the named/default args transformation when using annotation classes in executable code, which is allowed (`def foo = new annot(y = blah)`).

@som-snytt want to take a look? will also pass it by the Scala 3 folks.

**Comment by He-Pin** [comment]
Thanks, Does the same problem exits in Scala 3?

**Comment by som-snytt** [comment]
I'll take a look. I've been following a bit. It's always an event when lrytz adds a mode.

**Comment by lrytz** [comment]
@som-snytt I simplified things a bit so it's easier to port / integrate in Scala 3. We discussed it at the meeting last week, it seems they are fine with the approach (https://github.com/scala/scala3/discussions/22414).

Known tradeoffs:

 - `ConstantAnnotation` supports `Array[T]` params, `Array(1, 2, 3)` is a valid argument. But this doesn't make it through the mechanisms here, only values that fit in `Constant`. So:

```scala
scala> class ann(x: Array[Int] = Array(1), y: Int = 1) extends ConstantAnnotation

scala> @ann class K

scala> typeOf[K].typeSymbol.annotations.head.assocsWithDefaults
val res14: List[($r.intp.global.Name, $r.intp.global.ClassfileAnnotArg)] = List((y,1))
```

 - Default ASTs are transplanted from the annotation declaration to the use site, so they can refer to private symbols for example. I think that's OK, these ASTs are not compiled / transformed.

 -  `assocsWithDefaults` / `assocsForSuper` don't work for Java-defined annotations

**Comment by som-snytt** [comment]
I see from comment 2 that compatibility is a concern; also the old TODO comments from ten years ago suggest that compatibility in 2.11 was a concern.

Although I'm just re-learning all the moving parts of annotation handling, after looking at the code, my general question is how does this differ from Scala 3 inlining. The annotations represent opportunities to inline, and the difference in annotation mode is that the args are known not to side-effect. I'm wondering if the meta annotation model is as compelling for Scala 3.

I briefly wondered if it's very convenient to have both `superArg` and `superFwdArg`, but it is convenient for the usage (which is to look for an explicit arg then for a forwarded arg). It's just internal mechanism.

Otherwise it LGTM.

**Comment by lrytz** [comment]
> I see from comment 2 that compatibility is a concern; also the old TODO comments from ten years ago suggest that compatibility in 2.11 was a concern.

I don't follow what you're referring to.

> my general question is how does this differ from Scala 3 inlining

I mentioned inlining to the Scala 3 team. @sjrd's gut reaction was that it's not worth having different encodings between Scala 2 and 3. That said, Scala 3 is free to use a different mechanism, either when this is ported forward or after some later refactoring, it's all internal. But as long as Scala 3 reads the Scala 2 standard library jar, the Scala 3 compiler needs to be able to read the encoding we use here.

Support for user-defined annotation subclasses probably can't be implemented with inlining.

**Comment by som-snytt** [comment]
On old TODOs in AnnotationInfos, and deprecations in api.AnnotationInfos from 2.11, I only meant to say that I don't have perspective on whether there are simpler models that could never be pursued just for compatibility or to support existing plugins.

Here is an example in Dotty of "I don't quite know how this works":

image

https://github.com/scala/scala3/pull/20894/files#diff-367e32065f51ed46353fdaaf526ab7e7899404b219d24d5b1054fce7f376dfe5R218

Whether or not that code tweak is correct, it illustrates how it's hard to escape complexity.

I like that this solution uses existing mechanisms. My question about inlining was more philosophical.

File: src/reflect/scala/reflect/internal/AnnotationInfos.scala [hunk 1]
```diff
@@ -181,27 +181,140 @@ trait AnnotationInfos extends api.Annotations { self: SymbolTable =>
...
+   * The `argIsDefault` method tells if an annotation argument is explicit or a default inserted by the compiler.
    *
-   *  `args` stores arguments to Scala annotations, represented as typed
-   *  trees. Note that these trees are not transformed by any phases
-   *  following the type-checker.
+   *  Annotations are written to the classfile as Java annotations if `atp` conforms to `ClassfileAnnotation`
+   *  (the classfile parser adds this interface to any Java annotation class).
    *
-   *  `assocs` stores arguments to classfile annotations as name-value pairs.
+   *  Annotations are pickled (written to scala symtab attribute in the classfile) if `atp` inherits form
```
Comment (som-snytt) [inline src/reflect/scala/reflect/internal/AnnotationInfos.scala]: s/form/from and could also align the indent of the old comment

**Review by som-snytt — APPROVED** [review]

**Comment by lrytz** [comment]
> On old TODOs in AnnotationInfos

Ah, I see. Yeah in `reflect.api.Annotations` there are a lot of deprecations, I guess the idea was to simplify the API to be around a single `Tree`, maybe inspired by dotty (or the other way around). Not sure if many macros are using that API. For compiler plugins (and the compiler itself) I think it's more common to work with `AnnotationInfo`.

**Comment by lrytz** [comment]
Got the OK from the Scala 3 people.

**Comment by SethTisue** [comment]
community build regression at https://github.com/scala/scala-dev/issues/893
