### PR TITLE
fix searching with weird parameters

### LINKED ISSUE #11032: infinite loop in IndexedSeq#search
```scala
resolvers += "scala-pr" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"

scalaVersion := "2.13.0-pre-d71f4da" // latest 2018-07-20
```

```
Welcome to Scala 2.13.0-pre-d71f4da (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> Vector("a").search(elem = "b", from = 1, to = 0)
```

https://github.com/scala/scala/blob/d71f4da401c72faa6d91d904d3f2859b49895a06/src/library/scala/collection/IndexedSeq.scala#L62-L76

### PR DESCRIPTION
**Pull request by martijnhoekstra**
closes scala/bug#11032

makes searching obey the following invariants:

* Terminates for finite collections (this was violated in the binary search version with to < from)
* If `search(e, from, t)(ord)` returns `InsertionPoint(i)`, then for each index` j`
  * if `from <= j < i` then  `e > col(j)`
  * if `i <= j < to` then `e < col(j)`
  * no promises otherwise
* If `search(e, from, t)(ord)` returns `Found(i)`, then `ord.equiv(e, col(i))` (this was violated in the linear search version with from < 0)

### CODE REVIEW

File: test/junit/scala/collection/immutable/VectorTest.scala [hunk 1]
```diff
@@ -39,4 +39,34 @@ class VectorTest {
       assertEquals(els, prefix.toList ++: suffix)
     }
   }
+
+  @Test def checkSearch: Unit = {
```
Comment (martijnhoekstra) [inline test/junit/scala/collection/immutable/VectorTest.scala]: This is copy/paste between the List and Vector test. Is there a better way?

**Comment by szeiger** [comment]
Probably a spurious error:
```
[info] Test scala.concurrent.FutureTest.bug$divissues$hash10513$u0020firstCompletedOf$u0020must$u0020not$u0020leak$u0020references started
[error] Test scala.concurrent.FutureTest.bug$divissues$hash10513$u0020firstCompletedOf$u0020must$u0020not$u0020leak$u0020references failed: java.lang.AssertionError: Root Future(<not completed>) held reference, took 0.018 sec
[error]     at scala.tools.testing.AssertUtil$.$anonfun$assertNotReachable$6(AssertUtil.scala:90)
[error]     at scala.tools.testing.AssertUtil$.$anonfun$assertNotReachable$6$adapted(AssertUtil.scala:89)
[error]     at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:442)
[error]     at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:440)
[error]     at scala.collection.AbstractIterable.foreach(Iterable.scala:731)
[error]     at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:715)
[error]     at scala.concurrent.FutureTest.bug$divissues$hash10513$u0020firstCompletedOf$u0020must$u0020not$u0020leak$u0020references(FutureTest.scala:24)
[error]     ...
[info] Test run finished: 1 failed, 0 ignored, 1 total, 0.023s
```
I've restarted the build.

**Review by szeiger — APPROVED** [review]

**Comment by SethTisue** [comment]
thanks Martijn!
