### PR TITLE
t10729 annotation usage should extend annotation and Seq won't slay compiler

### LINKED ISSUE #11428: Error if not an annotation
Consider this example:
```
import annotation.switch

class switch {
  def test(x: Int) = (x: @switch) match {
    case 1 | 2 | 3 => ()
  }
}
```
Dotty reports:
```
-- [E007] Type Mismatch Error: tests/allan/Test.scala:4:25 ---------------------
4 |  def test(x: Int) = (x: @switch) match {
  |                         ^^^^^^^
  |                         found:    switch
  |                         required: scala.annotation.Annotation
  |                         
one error found
```
And scalac
```
tests/allan/Test.scala:1: warning: imported `switch` is permanently hidden by definition of class switch
import annotation.switch
                  ^
one warning found
```
I would say an error is warranted. One guess is that it was lost under https://github.com/scala/scala/pull/1901.

Description copied from https://github.com/lampepfl/dotty/issues/3617.

### PR DESCRIPTION
**Pull request by psilospore**
Issue: https://github.com/scala/bug/issues/10729

The linked issue says `1: Array(10)` should slay the compiler but it seems like that doesn't anymore after talking to @hrhino. Instead, I got some an error about an unexpected tree. However `1: Seq(10)` did slay.

This fix gives a more descriptive error for the Array case and prevents a slay for the Seq case.

Fixes scala/bug#11428

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 1]
```diff
@@ -390,8 +390,13 @@ trait ContextErrors {
       }
 
       //typedNew
-      def IsAbstractError(tree: Tree, sym: Symbol) = {
-        issueNormalTypeError(tree, sym + " is abstract; cannot be instantiated")
+      def IsAbstractError(tree: Tree, sym: Symbol, context: Context) = {
+        issueNormalTypeError(tree, sym + s" is ${if (sym.isTrait) "trait" else "abstract"}; cannot be ${if(context.inAnnotation) "annotated" else "instantiated"}")
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: "cannot be annotated" has the wrong subject, in `@Foo X`, "X" is annotated, not "Foo". I'd keep the original message ("Foo cannot be instantiated") or be more explicit ("cannot be used as an annotation"). I'm also not sure if "Foo is trait" is an improvement, I find "Foo is abstract" a better explanation.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 2]
```diff
@@ -3729,6 +3729,10 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
           typedFun0
       )
       val treeInfo.Applied(typedFun @ Select(New(annTpt), _), _, _) = typedFunPart
+      if (typedFunPart.isErroneous) {
+        return finish(ErroneousAnnotation)
+      }
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: this could more one more line up. and unnecessary `{ }`.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 3]
```diff
@@ -390,8 +390,13 @@ trait ContextErrors {
...
+        setError(tree)
+      }
+
+      def DoesNotExtendAnnotation(tree: Tree, sym: Symbol, context: Context) = {
```
Comment (hrhino) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: you don't need `context` here

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala (hunk 1 above)
Comment (hrhino) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: I'd vote for the "more explicit" one.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 4]
```diff
@@ -390,8 +390,13 @@ trait ContextErrors {
...
+        issueNormalTypeError(tree, s"$sym does not extend $AnnotationClass")
```
Comment (hrhino) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: I would consider using `${AnnotationClass.fullName}` instead (`Foo does not extend scala.annotation.Annotation`) but yomv.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 5]
```diff
@@ -4490,10 +4494,13 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
 
         val tp = tpt1.tpe
         val sym = tp.typeSymbol.initialize
-        if ((sym.isAbstractType || sym.hasAbstractFlag)
-            && !(sym.isJavaAnnotation && context.inAnnotation))
-          IsAbstractError(tree, sym)
-        else if (isPrimitiveValueClass(sym)) {
+
+        if (!sym.isJavaAnnotation && context.inAnnotation && !sym.baseClasses.contains(AnnotationClass)) {
```
Comment (hrhino) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: this can be `!(sym isNonBottomSubclassOf AnnotationClass)` I think.

**Review by hrhino — CHANGES_REQUESTED** [review]
You have a couple of failures; some look like checkfile updates are needed, others are more concerning:

```
+t7259.scala:8: error: <none> does not extend class Annotation
+@annotation.xxxxx // error: not found: type scala
+ ^
```

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala (hunk 1 above)
Comment (psilospore) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: I prefer the explicit one as well but ok with changing it back as well lmk

**Comment by psilospore** [comment]
@hrhino how did you get?
```
+t7259.scala:8: error: <none> does not extend class Annotation
+@annotation.xxxxx // error: not found: type scala
+ ^
```

Edit: I just noticed the t7259 in the log. Looks like I just need to update that checkfile. There's probably others. I'll have a look.

**Comment by psilospore** [comment]
/rebuild

test/files/neg/t935.scala works fine locally hmmmm
Edit: Turns out I had a .check with changes

**Comment by psilospore** [comment]
@lrytz and @hrhino does this look good to go?

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 6]
```diff
@@ -455,6 +455,7 @@ trait Contexts { self: Analyzer =>
     def inReturnExpr                          = this(ReturnExpr)
     def inTypeConstructorAllowed              = this(TypeConstructorAllowed)
     def inAnnotation                          = this(TypingAnnotation)
+    def typingAnnotationCore              = this(TypingAnnotationCore)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala]: Alignment nerd alert. Also naive question, what does "core" mean? Is there a more usual term?

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: It would be terribly stylish to write in one liner:
```
if (typedFunPart.isErroneous) return finish(ErrAnn)
```
Some code bases would frown on one-liners, and maybe also return.

Obviously, "terribly" here means "good".

File: test/files/neg/java-annotation-bad.check [hunk 7]
```diff
@@ -1,13 +1,13 @@
-Test_1.scala:12: error: Java annotation Ann_0 is abstract; cannot be instantiated
+Test_1.scala:12: error: Java annotation Ann_0 is trait; cannot be instantiated
```
Comment (som-snytt) [inline test/files/neg/java-annotation-bad.check]: Java doesn't have traits. I think Lukas commented that he preferred "abstract"?

File: test/files/neg/t7259.check [hunk 8]
```diff
@@ -4,4 +4,7 @@ t7259.scala:1: error: not found: type xxxxx
 t7259.scala:8: error: type xxxxx is not a member of package annotation
 @annotation.xxxxx // error: not found: type scala
             ^
-two errors found
+t7259.scala:8: error: <none> does not extend scala.annotation.Annotation
```
Comment (som-snytt) [inline test/files/neg/t7259.check]: This additional messaging does not look right.

File: test/files/neg/t771.check [hunk 9]
```diff
@@ -1,4 +1,4 @@
-t771.scala:4: error: trait Iterator is abstract; cannot be instantiated
+t771.scala:4: error: trait Iterator is trait; cannot be instantiated
```
Comment (som-snytt) [inline test/files/neg/t771.check]: Here, the word "abstract" is explanatory. It already says it is a trait, so "trait" is redundant.

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala (hunk 6 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala]: It's the "fun" part, but here it just means the type. `typingAnnotationType`? `TypeOfAnnotation`?

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 10]
```diff
@@ -430,8 +430,13 @@ trait ContextErrors {
       }
 
       //typedNew
-      def IsAbstractError(tree: Tree, sym: Symbol) = {
-        issueNormalTypeError(tree, sym + " is abstract; cannot be instantiated")
+      def IsAbstractError(tree: Tree, sym: Symbol, context: Context) = {
+        issueNormalTypeError(tree, sym + s" is ${if (sym.isTrait) "trait" else "abstract"}; cannot be ${if(context.typingAnnotationCore) "used as an annotation" else "instantiated"}")
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: Might as well write `s"$sym is ${ stuff }"`. Avoids `any2stringadd`, right? which actually warns now.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: OK, looking at the source, I'd be inclined to avoid return, make the error checks more readable (for instance, only one null check for annType), and instead of the big clever block arg for finish:
```
val info =
  if (check1) Erroneous
  else { other stuff }
finish(info)
```
Maybe it's possible to structure that clearly without early returns?

Not sure you want to undertake that here and now, however.

**Comment by som-snytt** [comment]
A made a few comments, some of which are supplemental to the excellent prior reviews.

File: test/files/neg/java-annotation-bad.check (hunk 7 above)
Comment (psilospore) [reply test/files/neg/java-annotation-bad.check]: > I think Lukas commented that he preferred "abstract"?

@hrhino mentioned he prefered it mention trait and I do as well, but I could change it back.

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala (hunk 6 above)
Comment (psilospore) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala]: I forgot since it's been a bit but maybe it's because I saw `Apply(core ...)` somewhere. Also this
```
  /** Applications in Scala can have one of the following shapes:
   *
   *    1) naked core: Ident(_) or Select(_, _) or basically anything else
   *    2) naked core with targs: TypeApply(core, targs) or AppliedTypeTree(core, targs)
   *    3) apply or several applies wrapping a core: Apply(core, _), or Apply(Apply(core, _), _), etc
   *
```

I can rename though.

File: test/files/neg/t7259.check (hunk 8 above)
Comment (psilospore) [reply test/files/neg/t7259.check]: So I found one way to solve this but I'm not sure if it's right

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 11]
```diff
@@ -4595,10 +4595,15 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
 
         val tp = tpt1.tpe
         val sym = tp.typeSymbol.initialize
-        if ((sym.isAbstractType || sym.hasAbstractFlag)
-            && !(sym.isJavaAnnotation && context.inAnnotation))
-          IsAbstractError(tree, sym)
-        else if (isPrimitiveValueClass(sym)) {
+
+        if (tpt.isErroneous) {
+          setError(tpt)
```
Comment (psilospore) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: So this is what prevents the <none> does not extend scala.annotation.Annotation from partest t7259. I wasn't sure if this was the right thing to do. Should it not even get to this point? I could also just remove the top condition and make this:
```
if (context.typingAnnotationCore && !sym.isJavaAnnotation && !(sym isNonBottomSubClass AnnotationClass) && !tpt.isErroneous) {
          DoesNotExtendAnnotation(tree, sym)
} else if ...
```
but that also doesn't seem proper.

Edit: I mentioned log implicits being changed but that only happened locally for some reason.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 12]
```diff
@@ -4595,10 +4595,15 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
...
+        } else if (context.typingAnnotationCore && !sym.isJavaAnnotation && !(sym isNonBottomSubClass AnnotationClass)) {
```
Comment (hrhino) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: I don't really like having both `TypingAnnotation` and `TypingAnnotationCore` around. 

What if we checked this in `typedAnnotation`, after typing the core? Something like
```scala
val pt = (if (typedFun0.symbol.isJavaAnnotation) JavaAnnotationClass else AnnotationClass).tpe
if (!typedFun0.tpe <:< pt) NotAnAnnotationError(tree, typedFun0.symbol)
```
?

Comment (psilospore) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: So it seems like that would work for most cases except test/files/jvm/annotations/Test_2.scala:97

typedFun0 would be false for isJavaAnnotation but .baseClasses shows it extends java.lang.annotation. Not sure if that's a bug. I did something else. lmk what you think

**Comment by som-snytt** [comment]
Fix the test rather than delete it. https://github.com/scala/bug/issues/10497

**Comment by psilospore** [comment]
Hi could someone review this PR

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 13]
```diff
@@ -3935,11 +3934,25 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
         else
           typedFun0
       )
+      if (typedFunPart.isErroneous) return finish(ErroneousAnnotation)
+
       val treeInfo.Applied(typedFun @ Select(New(annTpt), _), _, _) = typedFunPart
-      val annType = annTpt.tpe // for a polymorphic annotation class, this type will have unbound type params (see context.undetparams)
+      val annType = annTpt.tpe // for a polymorphic annotation class, th/t10497is type will have unbound type params (see context.undetparams)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: typo?

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 14]
```diff
@@ -3935,11 +3934,25 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
...
+      typedFun0 match {
+        case Select(New(a), _) =>
+
+          // test/files/jvm/annotations/Test_2.scala:97 fails if I just use a.symbol.isJavaAnnotation. Seems like it might be a bug?
+          val typedFun0ExtendsAnn = a.tpe <:< AnnotationClass.tpe || a.symbol.baseClasses.exists(x => x.isJavaAnnotation)
+
+          if (!typedFun0ExtendsAnn){
+            reportAnnotationError(DoesNotExtendAnnotation(typedFun0, a.tpe.typeSymbol.initialize))
+            return finish(ErroneousAnnotation)
+          }
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala:3952]: might be good to play it safe and add a `case _ =>`, so avoid the compiler crashing in unexpected situations (maybe under some error conditions that are not currently tested).

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 15]
```diff
@@ -3935,11 +3934,25 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
...
       val treeInfo.Applied(typedFun @ Select(New(annTpt), _), _, _) = typedFunPart
-      val annType = annTpt.tpe // for a polymorphic annotation class, this type will have unbound type params (see context.undetparams)
+      val annType = annTpt.tpe // for a polymorphic annotation class, th/t10497is type will have unbound type params (see context.undetparams)
       val annTypeSym = annType.typeSymbol
       val isJava = annType != null && annTypeSym.isJavaDefined
 
+      typedFun0 match {
+        case Select(New(a), _) =>
+
+          // test/files/jvm/annotations/Test_2.scala:97 fails if I just use a.symbol.isJavaAnnotation. Seems like it might be a bug?
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: this failed because `type myAnn = SourceAnnotation_1` is a type alias. use `a.tpe.dealiasWiden.typeSymbol.isJavaAnnotation`.

**Review by lrytz — CHANGES_REQUESTED** [review]
Looks good!

**Review by lrytz — APPROVED** [review]
Nice, thank you @psilospore!

**Comment by som-snytt** [comment]
Thanks @lrytz !
