### PR TITLE
Use BTypes in StringConcatFactory code gen

### LINKED ISSUE #12761: String interpolation fails to compile running on JDK 20 when using release:11 compiler option
## Reproduction steps

Scala version: 2.13.10

```scala
object A {
  def a(s: String): String = s"S: $s"
}
```

## Problem

When  trying to compile on JDK 20:
```
% java -version             
openjdk version "20" 2023-03-21
OpenJDK Runtime Environment Temurin-20+36 (build 20+36)
OpenJDK 64-Bit Server VM Temurin-20+36 (build 20+36, mixed mode)

% scala -version
Scala code runner version 2.13.10 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.

% scalac -release:11 A.scala
error: Error while emitting A$
Unsupported class file major version 64
1 error
```

Compiles just fine with Temuring 17 JDK. 

Platforms tested on:
* macOS arm64

### PR DESCRIPTION
**Pull request by lrytz**
This makes sure the BType for the inner class `MethodHandles$Lookup` is initialized (by getting the information from the Symbol) when emitting the InnerClass attribute. If not, the backend attempts to read the BType from the classfile, which can fail (newer than supported classfile version). 

Fixes https://github.com/scala/bug/issues/12761

Thanks for the analysis on the ticket, @som-snytt!

### CODE REVIEW

**Comment by som-snytt** [comment]
Aha! I spent a few minutes on where BTypes come from, but was not quick enough to see how to get it from the Symbol before I was distracted, probably by domestic chores. I'm glad there is an expert in the house.

**Comment by lrytz** [comment]
Yeah, it's not very obvious.. every BType can be constructed either from the symbol table (`classBTypeFromSymbol`) or from a parsed classfile. The latter should only ever be necessary when using the inliner.

BTypes for every type that appears in an emitted classfile are expected to exist in the cache. They are needed for the `InnerClass` attribute and for stack map frames (`getCommonSuperClass`). The compiler still tries to look up BTypes from classfiles if that is not the case, but that can fail. The compiler should give better hints to its maintainers when this happens...

File: src/compiler/scala/tools/nsc/backend/jvm/BCodeIdiomatic.scala [hunk 1]
```diff
@@ -236,9 +236,9 @@ abstract class BCodeIdiomatic {
         asm.Type.getMethodDescriptor(StringRef.toASMType, argTypes:_*),
         new asm.Handle(
           asm.Opcodes.H_INVOKESTATIC,
-          "java/lang/invoke/StringConcatFactory",
+          jliStringConcatFactoryRef.internalName,
           "makeConcatWithConstants",
-          "(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;",
+          s"(${List(jliMethodHandlesLookupRef, StringRef, jliMethodTypeRef, StringRef, ArrayBType(ObjectRef)).map(_.descriptor).mkString})${jliCallSiteRef.descriptor}",
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/backend/jvm/BCodeIdiomatic.scala]:
```suggestion
          List(jliMethodHandlesLookupRef, StringRef, jliMethodTypeRef, StringRef, ArrayBType(ObjectRef))
            .map(_.descriptor)
            .mkString("(", "", s")${jliCallSiteRef.descriptor}"),
```

**Review by som-snytt — APPROVED** [review]
Noted my preferred use of mkString to highlight list that is formatted.

Thanks, TIL CoreBTypes.

**Comment by som-snytt** [comment]
Maybe Travis fails under auto-merge.

I feel that auto-Marge should be a SImpsons episode.
