### PR TITLE
Exclude universal members (getClass, toString, etc) from root module import

### LINKED ISSUE #5389: Misleading compiler error on wrong import
Assuming there is no `ne` package, the following top-level import:

```scala
import ne.foobar
```

makes the compiler complain that:

```
error: missing arguments for method ne in class Object;
follow this method with `_' if you want to treat it as a partially applied function
       import ne.foo
              ^
```

I believe this is misleading for the Plain Old User.

### PR DESCRIPTION
**Pull request by som-snytt**
`definitions.isImportable` makes the faulty assertion that universal members are not importable.

In fact, they are imported by default from `Predef`. This is observable in scala 2 imports and in scala 3 top level definitions.

Fixes scala/bug#5389

### CODE REVIEW

File: test/files/neg/t5389.scala [hunk 1]
```diff
@@ -0,0 +1,4 @@
+
+import ne.scala
```
Comment (hrhino) [inline test/files/neg/t5389.scala:2]: So @jducoeur's paying you under the table after all, hmm.

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 2]
```diff
@@ -150,10 +160,7 @@ trait Contexts { self: Analyzer =>
       if (!unit.hasXml || ScalaXmlTopScope == NoSymbol) rootImportsContext
       else rootImportsContext.make(gen.mkImport(ScalaXmlPackage, nme.TopScope, nme.dollarScope))
 
-    val c = contextWithXML.make(tree, unit = unit)
-
-    c.initRootContext(throwing, checking)
-    c
+    contextWithXML.make(tree, unit = unit).tap(_.initRootContext(throwing, checking))
```
Comment (hrhino) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala:163]: Fancy!

**Review by hrhino — APPROVED** [review]
Thanks. I hate to give the impression that I'm an easier reviewer than all the rest, but lgtm.

This can't have been strange enough to be a puzzler, right? I'm always concerned that we give thought to breaking our users but very little to the puzzlers guy. Should we add it to the community build?

**Comment by som-snytt** [comment]
The improvement would be to construct the masking selectors for universal members only once.

File: test/files/neg/t5389.scala (hunk 1 above)
Comment (jducoeur) [reply test/files/neg/t5389.scala:2]: I've owned the domain for less than 24 hours, and I'm already a world power!

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 3]
```diff
@@ -137,7 +138,16 @@ trait Contexts { self: Analyzer =>
...
   def rootContext(unit: CompilationUnit, tree: Tree = EmptyTree, throwing: Boolean = false, checking: Boolean = false): Context = {
-    val rootImportsContext = rootImports(unit).foldLeft(startContext)((c, sym) => c.make(gen.mkWildcardImport(sym), unit = unit))
+    val rootImportsContext = rootImports(unit).foldLeft(startContext) { (c, sym) =>
+      if (sym.isPackage) c.make(gen.mkWildcardImport(sym), unit = unit)
+      else {
+        val universals = sym.typeSignature.members.filter(isUniversalMember).map(_.name).toSet
+        val sels = universals.iterator
+          .map(ImportSelector.mask).toList
+          .appended(ImportSelector.wild)
+        c.make(gen.mkImportFromSelector(sym, sels), unit = unit)
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala:148]: This [hurts](https://scala-ci.typesafe.com/grafana/dashboard/db/scala-benchmark?orgId=1&from=1573526022724&to=1574227932992&var-branch=All&var-source=All&var-bench=HotScalacBenchmark.compile&var-host=scalabench%40scalabench%40) compiler performance markedly. I haven't investigated profiles, so I'm not sure whether the cost is creating this `Import` or the overhead of subsequent symbol lookups using it rather than the simple wildcard.

Could we instead make `ImportInfo.importedSymbol` exclude these, perhaps conditionally on `isRootImport`?

It already filters its results through `isUnimportable` which excludes constructors and `private[this]`. There is also logic in there that purports to stop all imports of members of `AnyRef`, but was disabled fully, maybe unintentionally, in 2b4cd6c11016d046affb1d4ae787f85c6be1deec.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala:148]: Definitely for minor values of major.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala:148]: I was more worried about compiler performance when merging this one: https://github.com/scala/scala/pull/8538/files#diff-62ccdfe29e58b8e9f06ed66d4cfc88a5R590-R593

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala:148]: Basically `Any` is not your friend. And how could it be?

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala:148]: JZ's improvement in the linked PR. I'll follow up by running benchmarks and then by putting LR's mind at ease, if I am able.

**Comment by SethTisue** [comment]
I've added the "release notes" since two projects in the community build were affected: https://github.com/akka/akka/pull/28355, https://github.com/lagom/lagom/issues/2579

**Comment by som-snytt** [comment]
See hrhino's prescient approval comment above:

> Should we add it to the community build?

> This can't have been strange enough to be a puzzler, right?

Also the part where he cops to being an easy review.

It's been said many times on this project that there is no bug so outré that no code in the wild relies on it.

This behavior was actually as specified and not a bug; it could have been a lint. In fact, I am inclined to demote it to lint. WDYT @SethTisue @hrhino ?  Or leave it as it is, because it's always a bug? In that case, we can make it a non-lint warning without irking anyone; a behavior change can be irksome; if only we could specify what java.lang and scala.Predef export!

**Comment by SethTisue** [comment]
I think I would have also signed off on a PR that made it a lint. mainly, I am happy we now have one or the other, rather than neither.

**Comment by hrhino** [comment]
Thanks for the reminder to get my NEScala tickets.

**Comment by som-snytt** [comment]
So long as you both are happy.

I don't like that it's a bit of a special case, but there's nothing which says the spec can't specify that root contexts work like the first implementation, masking `Any`-defined members.
