### PR TITLE
Align package detection in Java with Java

### LINKED ISSUE #10350: compiler: invalid package resolution in java source
```sh
% java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

% scalac -version
Scala compiler version 2.12.2 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.
```

### `foo/Foo.java`
```java
package foo;

public interface Foo {
  static Foo create(java.lang.String val) { return null; }
}
```

### `foo/java/Baz.java`
```java
package foo.java;
interface Baz {}
```

### `bar/Bar.scala`
```scala
package bar

object Bar {
  def xxx(s: String): foo.Foo = { foo.Foo.create(s) }
}
```

### output
```sh
% scalac bar/Bar.scala foo/Foo.java foo/java/Baz.java
foo/Foo.java:4: error: object lang is not a member of package foo.java
  static Foo create(java.lang.String val) { return null; }
                         ^
one error found
```

### PR DESCRIPTION
**Pull request by som-snytt**
Java packages are absolute, not relative.

So for a package symbol to be a typed identifier,
it must be effectively `_root_`ed.

I don't know why people like to call their
packages `java`, `scala`, and `util`, but
the conflict happens for any package name
appearing twice in a dotted name and
accessed from the bowels.

Also bestowed upon partest the ability to
descend a directory, which is technology
available only since Java 7. This was the
reason they forked Vulpix/Xipluv.

Noticed that a couple of other tests seem
to be mistakenly nested.

Fixes scala/bug#10350

### CODE REVIEW

**Comment by som-snytt** [comment]
Review by @hrhino who is likely back from vacation, if he ever was on vacation. Unless he's taking off for the long weekend.

Happy Valentine's Day! :heart_decoration: 

Happy President's Day! :medal_military:

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 1]
```diff
@@ -5400,16 +5400,21 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
...
           startContext.lookupSymbol(name.toTypeName, qualifies).symbol
         } else NoSymbol
 
-        val nameLookup   = tree.symbol match {
-          case NoSymbol   => startContext.lookupSymbol(name, qualifies)
-          case sym        => LookupSucceeded(EmptyTree, sym)
+        // in Java, only pick a package if it is rooted
+        def termQualifies(sym: Symbol) = qualifies(sym) && (
+            !startContext.unit.isJava  || !sym.hasPackageFlag
+          || sym.owner.isEffectiveRoot || sym.owner.isRootPackage || sym.isRootPackage
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala:5479]: tempting is the paulpism, `List(sym, sym.owner).exists(s => s.isEffectiveRoot || s.isRootPackage)`

**Comment by som-snytt** [comment]
Not sure how presentation tests blew up? I may have to learn something.

File: src/partest/scala/tools/partest/nest/Runner.scala [hunk 2]
```diff
@@ -447,7 +449,7 @@ class Runner(val testInfo: TestInfo, val suiteRunner: AbstractRunner) {
   /** Source files for the given test file. */
   def sources(file: File): List[File] = (
     if (file.isDirectory)
-      file.listFiles.toList filter (_.isJavaOrScala)
+      Files.walk(file.toPath).collect(Collectors.toList()).asScala.map(_.toFile).filter(_.isJavaOrScala).toList
```
Comment (hrhino) [inline src/partest/scala/tools/partest/nest/Runner.scala]: Preso tests put their (incomplete) mock user input into a subdirectory, so you can't do this for that. I support a special case for them, though, especially since I don't know if anyone still uses the presentation compiler. Does Metals?

Comment (hrhino) [reply src/partest/scala/tools/partest/nest/Runner.scala]: Also, many of the test mains in that directory look similar. If we were a cool test framework would it go only off of magic code comments?

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 1 above)
Comment (hrhino) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala:5479]: Or the introduction of `sym.isRooted`.

**Review by hrhino — COMMENTED** [review]
It's a good thing those by-name-implicits tests work. Thanks for modernizing partest, or something.

File: src/partest/scala/tools/partest/nest/Runner.scala (hunk 2 above)
Comment (som-snytt) [reply src/partest/scala/tools/partest/nest/Runner.scala]: Thanks for the hint. I am awake now.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala:5479]: It actually took me a while (while working on something work-related) to come up with this formulation. I didn't get to the point where I felt comfortable adding `sym.isEffectiveRoot` and I've already forgotten the grid. For `p`, is `p.isEffectiveRoot` or its owner?

**Review by hrhino — APPROVED** [review]

**Comment by som-snytt** [comment]
@SethTisue I'll hit merge with improved partest plus delinting if you advance the milestone at this critical junction. How much you want to bet it breaks the community build?

**Comment by SethTisue** [comment]
> How much you want to bet it breaks the community build?

Should we find out before merging?

**Comment by som-snytt** [comment]
@SethTisue before I say I was just joking, it's conceivable that someone somewhere relies on scalac using scala rules to resolve package names in java. Perhaps, as in the example, they installed a fake java package for cross-compilation purposes. That would be clever.

I thought we only check the community build after a commit joins the community of committed commits.

File: src/partest/scala/tools/partest/nest/Runner.scala [hunk 3]
```diff
@@ -447,7 +449,8 @@ class Runner(val testInfo: TestInfo, val suiteRunner: AbstractRunner) {
   /** Source files for the given test file. */
   def sources(file: File): List[File] = (
     if (file.isDirectory)
-      file.listFiles.toList filter (_.isJavaOrScala)
+      if (testInfo.kind == "presentation") file.listFiles.toList.filter(_.isJavaOrScala)
```
Comment (lrytz) [inline src/partest/scala/tools/partest/nest/Runner.scala]: We could also not descend into `src/` subdirectories https://github.com/scala/scala/blob/2c462e1c88b5444e5191c3fb2ade28c07e6fa0c3/src/interactive/scala/tools/nsc/interactive/tests/core/TestSettings.scala#L28

**Review by lrytz — APPROVED** [review]

File: src/partest/scala/tools/partest/nest/Runner.scala (hunk 3 above)
Comment (lrytz) [reply src/partest/scala/tools/partest/nest/Runner.scala]: Or put all java source files into the top directory - javac doesn't seem to mind.
