### PR TITLE
More imports clean up

### LINKED ISSUE #11690: Imports competing at same nesting level fail to warn unused
One of these imports is unused.
```
object X {
  val v = 27
}
object Y {
  val v = 42
}
object Main {
  import X._
  import Y.v
  def main(args: Array[String]) = println {
    //import Y.v // induces warning
    v
  }
}
```

### PR DESCRIPTION
**Pull request by som-snytt**
Besides the fix for unused imports, inlines a bit of code around implicit imports. Exploiting the idiom to ask for alternatives only when overloaded. No more parameter to "record usage", which is done only when done.

Fixes scala/bug#11690

### CODE REVIEW

**Comment by lrytz** [comment]
Still WIP? Will try to review this some other day :-)

**Comment by som-snytt** [comment]
@lrytz no one cares about this corner case. Even I don't care. I still have to check whether it must be ported to dotty.

**Comment by som-snytt** [comment]
**som-snytt** commented some other day:

OK, so this is the one that fixes the remaining "edge case" in name binding, see the test.

(Level 4 definition cannot shadow level 1 definition. It sounds obvious when you put it like that.)

Edit: actually the second commit is a follow-up to https://github.com/scala/scala/pull/7609

This is rebased, and maybe I'll find time to make it prettier.

Edit: also I just noticed this fixes a bug in unused import warning.

**Comment by dwijnand** [comment]
Can/should we try to land this?  (Looks like it needs a rebase too, btw.)

**Comment by som-snytt** [comment]
I'll take a third look, but if it sits around again, I'll forget again. I see that in November, I realized it's a real fix, not just a clean-up.

**Comment by som-snytt** [comment]
Rebased. I left the tweak in a separate commit for review, but it could be squashed.

My previous reference to prettifying means that the current code could be more symmetric. It originally assumed that lookup could be short-circuited when a definition is found, and that only imports required looking for ambiguities. Instead, it should search the context chain and stop only with a precedence level 1 binding (or root import contexts, which are lowest precedence and can't introduce an ambiguity).

**Comment by som-snytt** [comment]
`lookup refactor` sounds like a line of cosmetics.

**Comment by dwijnand** [comment]
> Exploiting the idiom to ask for alternatives only when overloaded.

Why is this the idiom?  And if it's idiomatic, is there a reason there's no terse way to express it?  `.alternativesOrMe`?

I read the diff and nothing concerning jumped out of me, but I have no context (ironically) so perhaps it's best if @hrhino or @retronym sign off on it.

**Review by lrytz — APPROVED** [review]

**Comment by hrhino** [comment]
@som-snytt sorry I didn't review it in type. @lrytz reviews the neglected and unreviewed, as always.

@dwijnand using `.alternatives` on a non-overloaded symbol allocates a whole extra `::` object, which is either negligible or unforgivable depending on the hotness of the method and your personal mood.

**Comment by dwijnand** [comment]
......................... -.-

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 1]
```diff
@@ -1798,7 +1793,27 @@ trait Contexts { self: Analyzer =>
...
+
+    private def selectorString(s: ImportSelector): String = {
+      if (s.isWildcard) "_"
+      else if (s.isRename) s.name + " => " + s.rename
+      else "" + s.name
+    }
+
+    /** Optionally record that a selector was used to import the given symbol. */
+    def recordUsage(sel: ImportSelector, result: Symbol): Unit = {
+      debuglog(s"In $this at ${ pos.source.file.name }:${ posOf(sel).line }, selector '${ selectorString(sel)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1810]: Fine, to at least leave a comment 😄

This call was guarded by `settings.warnUnusedImport` before this PR, I assume it's a deliberate improvement.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1810]: I was focused on nontrivial rebase; I'll take a second look.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1810]: @lrytz Actually this will need a follow-up. The point of the "record" flag was to distinguish look-ups of implicits, which are not yet usages. Or wait, I guess it's OK, implicits collection uses `importedSymbol` which ignores the guilty selector and records nothing; `SymbolLookup.apply` has `lookupImport` that tracks the selector which is then recorded. All the words are permutations of the same words, and all the types are combinations of `Name` and `Symbol`. I'm also suspicious of the `requireExplicit` flag.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1810]: It was a rebase error to move `def selectorString` back outside `recordUsage`.
