### PR TITLE
Compiler plugins: rework and improve phase assembly (possibly requiring plugin authors to adjust)

### LINKED ISSUE #8755: Phase Assembly is broken
The phase assembly, which is responsible for ensuring correct execution order of internal as well as user-defined compiler components, is severely broken.

### How to reproduce

I have written a small compiler plugin which can be configured to instantiate an arbitrary number of noop components with user-defined phase constraints. For installing it locally, perform

```scala
$ git clone git@github.com:misberner/dummyphase.git
$ cd dummyphase
$ sbt publishLocal
```

The syntax for defining phases is: `phase1(after;rightAfter;before)|phase2(after;rightAfter;before)|...`. 
Here, `after` and `before` are comma-separated lists of phase names. The phase definition is specified as the property `dummyphase.phases`. Example invocations can be found below (note that the "parser" is extremely fragile).

### If components specify no constraints, they are ignored

Every phase should run after "parser" and before "terminal". However, if a component specifies empty lists for both `runsAfter` and `runsBefore`, it is ignored entirely.

To make matters worse, a component is considered if it declares that it runs after parser, but not if it declares to run before terminal.

```scala
# A phase without any constraints, ignored
$ scalac -Xplugin ~/.ivy2/local/dummyphase/dummyphase_2.11/0.1-SNAPSHOT/jars/dummyphase_2.11.jar \
  -Ddummyphase.phases='phase(;;)' -Xshow-phases
# A phase that specifies it runs after the parser phase, shows up
$ scalac -Xplugin ~/.ivy2/local/dummyphase/dummyphase_2.11/0.1-SNAPSHOT/jars/dummyphase_2.11.jar \
  -Ddummyphase.phases='phase(parser;;)' -Xshow-phases
# A phase that specifies it runs before the terminal phase, ignored
$ scalac -Xplugin ~/.ivy2/local/dummyphase/dummyphase_2.11/0.1-SNAPSHOT/jars/dummyphase_2.11.jar \
  -Ddummyphase.phases='phase(;;terminal)' -Xshow-phases
```

### If components specify runsRightAfter, all other constraints are ignored

This leads to wrong phase orders without any kind of warning.

```scala
# phase1 needs to run after delambdafy, phase2 needs to run *right after* phase1 and before icode.
# Since icode does not need to run *right* after delambdafy, a valid order would be:
# delambdafy, phase1, phase2, icode
$ scalac -Xplugin ~/.ivy2/local/dummyphase/dummyphase_2.11/0.1-SNAPSHOT/jars/dummyphase_2.11.jar \
  -Ddummyphase.phases='phase1(delambdafy;;)|phase2(;phase1;icode)' \
  -Xshow-phases
...
    delambdafy  22  remove lambdas
         icode  23  generate portable intermediate code
        phase1  24
        phase2  25
...
```

### Solvable constraint systems are rejected

The current phase assembly  fails if a phase that defines a `rightAfter` dependency has another outgoing edge. Due to the above, this cannot be shown by specifying an `after` and a `rightAfter` dependency, but a `rightAfter` in combination with a `before` exposes this.

```scala
$ scalac -Xplugin ~/.ivy2/local/dummyphase/dummyphase_2.11/0.1-SNAPSHOT/jars/dummyphase_2.11.jar \
  -Ddummyphase.phases='phase1(;patmat;)|phase2(parser;;phase1)' \
  -Xshow-phases
error: scala.reflect.internal.FatalError: Phase phase1 can't follow patmat, created phase-order.dot
```
As can be seen in the attached `phase-order.png`, the constraint system is satisfiable.

### The implementation has bugs

The implementation modifies variable members of case classes (that are used for `hashCode` calculation), without removing them from containing `HashSet` s. This leads to erroneous phase graphs. See attached file `phase-4.png`, where the `posterasure` node is still present even though it was collapsed into another node.

Note that no user-defined phases are necessary to expose this behavior.

```scala
$ scalac -Xshow-phases -Xgenerate-phase-graph phase
$ dot -Tpng phase-4.dot >phase-4.png
```

### PR DESCRIPTION
**Pull request by som-snytt**
Improve `PhaseAssembly`, which orders compiler phases according to their `runsBefore` / `runsAfter` constraints, for correctness and performance.

## Compatibility

When using compiler plugins with lax constraints (multiple correct solutions for placing a plugin phase) or bad constraints (e.g., `runsAfter` a non-existing phase), the resulting list of compiler phases may be different.

If your project breaks or you just want to be sure, use the `-Vphases` flag before and after the update to 2.13.15 and compare the list of compiler phases.

## Details

In particular, the phase named in a constraint (such as `runsBefore`) must be an actual phase; previously, a typo in the name would cause a constraint to be silently ignored.

Scaladoc provides "placeholder" phases named "patmat" and "erasure", so that plugins that name those phases can load benignly.

The list of phases in execution order can be viewed with the compiler option `-Vphases`.

From the sbt prompt:
```
set ThisBuild/scalacOptions += "-Vphases"
compile
```
In general, the order of phases is not expected to change, in the absence of errors. As previously, phases which are N phases after parser are sorted by name.

Further details:

One test correctly assembles the phases now but failed before.

One nuance is that phases at the same "level" (distance from parser) used to be sorted only by name, ~but now are sorted first by whether they are "internal" or supplied by a plugin~. The async test relied on the old sorting but arguably using `runsRightAfter` is more correct.

Scaladoc was lax about its `phasesSet`, which is typically the sum of internal, platform, and plugin components. Now Scaladoc only adds the phases it wants.

Some anomalies such as empty phase names (for `runsAfter` constraints) have been corrected, but will be ignored.

The initial (parser) and terminal (terminal) phases are required. The standard terminal component is added if there is none. All other phases run after parser and before terminal.

The `phasesSet` is closed; a phase can't depend on a spurious phase name.

Fixes scala/bug#8755

### CODE REVIEW

**Comment by SethTisue** [comment]
what prompted you to pry open the lid of this haunted ancient crypt?

**Comment by som-snytt** [comment]
Will replace the algo, but thought I'd tease it apart first, also to run the benchmark for before/after. Also, forgot to review dotty phase fusion.

**Comment by som-snytt** [comment]
"parser" and "terminal" are still special names, but should rely only on `initial` and `terminal`.

File: src/compiler/scala/tools/nsc/PhaseAssembly.scala [hunk 1]
```diff
@@ -12,271 +12,228 @@
...
-      return // no need to revisit
+    val v = getNode(from)
+    val w = getNode(to)
+    adjacency(v).find(e => e.from == v && e.to == w) match {
+      case None =>
+        //inDegree(w) += 1
+        //size += 1
+        adjacency(v) ::= Edge(from = v, to = w, weight)
+      case Some(e) if weight == FollowsNow => // use runsRightAfter edge FollowsNow
+        adjacency(v) = Edge(from = v, to = w, weight) :: adjacency(v).filterNot(e => e.from == v && e.to == w)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/PhaseAssembly.scala]: when do we get here?

**Review by lrytz — COMMENTED** [review]
This looks a lot clearer - I need more time to look into `compilerPhaseList` though. Do you write graph algorithm textbooks in your spare time?

Some high-level questions.

I assume it can give different results than 2.13.13? It's not unlikely to have loose dependency graphs, I remember https://github.com/lightbend/genjavadoc/pull/191 from last time. Would it be possible to
  - also run the old algorithm, warn if there are changes?
  - warn about loose graphs? I guess that's not actionalbe though, when using multiple plugins.

Is the algorithm deterministic? I see the starting point is `global.phasesSet`, which is a hash set. Would it make sense to sort them in `DependencyGraph.apply`?

**Comment by lrytz** [comment]
> and performance

Can you elaborate how the new implementation is better? Did you compare the benchmark before / after? It seems performance is relevant https://github.com/scala/scala/commit/e83ea4415bc42b02b3f3042563fd970967032458

**Comment by som-snytt** [comment]
I assume CB will show broken constraints (since the compiler had to be tweaked); see the OP comment on async and scaladoc.

For example, I had to accommodate having a `runsAfter` that duplicates `runsRightAfter` (which is redundant).

Users could compare old and new by trying the old and new compilers.

This is a topo sort for longest path, where `runsRightAfter` is special. See OP for sorting behavior at same distance; FSR I tweaked it to prefer "internal" phases first, then plugins sorted by name.

Recently I used github search for `language:scala PluginComponent` and was not rewarded. I see lihaoyi ecosystem has some plugins, so I'll try those and also your example (genjavadoc as used by akka).

I ran the retronym benchmark FWIW, which was in the context of adding many phases in order. The unit test agrees that the old code is slow with more phases. This either doesn't matter IRL, or matters to anyone running many compilations in the cloud.

```
retronym benchmark on 2.13.12

[info] Benchmark                        (size)  Mode  Cnt      Score     Error  Units
[info] PhaseAssemblyBenchmark.assemble       1  avgt   10    816.109 ± 111.995  ns/op
[info] PhaseAssemblyBenchmark.assemble       4  avgt   10   2791.529 ± 178.296  ns/op
[info] PhaseAssemblyBenchmark.assemble       8  avgt   10   6148.445 ± 610.413  ns/op
[info] PhaseAssemblyBenchmark.assemble      16  avgt   10  12495.480 ± 247.890  ns/op
[success] Total time: 856 s (14:16), completed Jan 27, 2024, 5:02:34 PM

[info] PhaseAssemblyBenchmark.assemble       1  avgt   10    824.016 ±   26.198  ns/op
[info] PhaseAssemblyBenchmark.assemble       4  avgt   10   2689.058 ±  455.633  ns/op
[info] PhaseAssemblyBenchmark.assemble       8  avgt   10   5787.073 ±   31.035  ns/op
[info] PhaseAssemblyBenchmark.assemble      16  avgt   10  11815.265 ± 1384.701  ns/op
[info] PhaseAssemblyBenchmark.assemble      64  avgt   10  90687.464 ± 3440.683  ns/op
[success] Total time: 1037 s (17:17), completed Feb 10, 2024, 10:57:51 PM
```
after, also showing a cost for a tweak for correctness
```
[info] Benchmark                        (size)  Mode  Cnt      Score     Error  Units
[info] PhaseAssemblyBenchmark.assemble       1  avgt   10   1273.694 ± 165.329  ns/op
[info] PhaseAssemblyBenchmark.assemble       4  avgt   10   3360.838 ±  72.838  ns/op
[info] PhaseAssemblyBenchmark.assemble       8  avgt   10   5512.273 ±  95.010  ns/op
[info] PhaseAssemblyBenchmark.assemble      16  avgt   10   9923.611 ± 475.227  ns/op
[info] PhaseAssemblyBenchmark.assemble      64  avgt   10  37914.080 ± 933.747  ns/op
[success] Total time: 1022 s (17:02), completed Feb 11, 2024, 9:01:28 AM

[info] Benchmark                        (size)  Mode  Cnt      Score     Error  Units
[info] PhaseAssemblyBenchmark.assemble       1  avgt   10   1431.521 ±  75.982  ns/op
[info] PhaseAssemblyBenchmark.assemble       4  avgt   10   3947.124 ±  70.060  ns/op
[info] PhaseAssemblyBenchmark.assemble       8  avgt   10   6603.209 ±  89.266  ns/op
[info] PhaseAssemblyBenchmark.assemble      16  avgt   10  11868.508 ± 160.368  ns/op
[info] PhaseAssemblyBenchmark.assemble      64  avgt   10  46191.684 ± 871.991  ns/op
[success] Total time: 1014 s (16:54), completed Feb 13, 2024, 9:43:43 PM
```

**Comment by som-snytt** [comment]
re: unordered inputs https://github.com/scala/scala/pull/10687/files#diff-e616cc3a2f3f30e519fdef9dcd1a42322cea0e8c13a5f6fefef2ed59aaed5e38R126

File: src/compiler/scala/tools/nsc/PhaseAssembly.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/PhaseAssembly.scala]: There is already `v -> w` (runsBefore) and we add `v => w` (runsRightAfter), retaining the `=>` (for `FollowsNow`).

Otherwise, the new edge is normal `Follows` so keep existing edge, which can't have lower weight.

**Comment by som-snytt** [comment]
sample new order with acyclic.
```
[info]      phase name  id  description
[info]      ----------  --  -----------
[info]          parser   1  parse source into ASTs, perform simple desugaring
[info]           namer   2  resolve names, attach symbols to named trees
[info]  packageobjects   3  load package objects
[info]           typer   4  the meat and potatoes: type the trees
[info]  superaccessors   5  add super accessors in traits and nested classes
[info]         acyclic   6
[info]      extmethods   7  add extension methods for inline classes
```

**Comment by lrytz** [comment]
Assuming the new implementation is correct, the compiler behaves as specified; but there will be valid changes within the constraints that might uncover bugs in compiler plugins, or it can break projects that were the constraints are too lax and everything was working by accident.

Is release notes enough? @SethTisue

> re: unordered inputs https://github.com/scala/scala/pull/10687/files#diff-e616cc3a2f3f30e519fdef9dcd1a42322cea0e8c13a5f6fefef2ed59aaed5e38R126

I don't follow; in the test everything is deterministic, but in the compiler the phases go through a hash set.

**Comment by som-snytt** [comment]
In general, the phases are assigned their greatest distance from parser (longest path); in each equivalence class, the phases are sorted deterministically (by the tuple `(isInternal, name)`).

In that test, I was setting up the "actual" constraints to fix a bug (in handling `followsRightAfter` IIRC), and the comment is that shuffling the inputs shouldn't matter. One of the tests shuffles inputs.

BTW, that bug convinced me that simple things are easier to fix. Also, "basically correct except for this bug" is easier to fix than "code with unknown behavior which, like a broken clock, is occasionally correct, but has this erroneous test we don't know how to fix".

Since there is a good chance that any given plugin "works by chance", if we can get an actual snapshot of CB, I would follow up with tweaks. Besides plugins, someone may also use the "internal API" to manage phases, like Scaladoc.

**Comment by lrytz** [comment]
> In general, the phases are assigned their greatest distance from parser (longest path); in each equivalence class, the phases are sorted deterministically (by the tuple `(isInternal, name)`).

Good, thanks!

**Comment by som-snytt** [comment]
That is assuming the implementation is correct.

**Comment by SethTisue** [comment]
I don't doubt the new code is cleaner and faster, but I'm not convinced we should merge this, on cost/benefit grounds. Any behavior change here that affects actual plugins — even if the change could technically be classified as a progression rather than regression — is an ecosystem cost. See Lukas's remarks above.

As for potential benefits
* speed: this code isn't actually a noticeable factor in real build times, is it?
* cleanliness: clean code only has tangible benefit if the code is still undergoing or expected to undergo well-motivated change

**Comment by som-snytt** [comment]
retronym's previous swing was due to a real customer. The unit test is newly commented that the old code took 20 seconds; I forgot to revert the test from 64K because it is fast now.

If you run CB, I'll follow up with mitigations.

**Comment by SethTisue** [comment]
> retronym's previous swing was due to a real customer 

Ah! I've contacted him and invited him to comment.

> If you run CB, I'll follow up with mitigations

I can definitely do that (but after 2.13.14 ships).

**Comment by som-snytt** [comment]
Note to self: needs some clean-up and code comments.

For mitigating change, it should revert to the previous sorting (alpha-only, not internal-first).

The API should not require `terminal` but do some reasonable thing if

1.  parser or terminal are missing
2.  use the initial and terminal properties instead of phase names
3. handle phases that don't follow anything the same. (currently not tested)

This PR makes everything follow the initial phase; a lack of constraint does not mean "don't run me". I don't remember what the old code intended with "orphan" nodes.

**Comment by som-snytt** [comment]
I verified that `genjavadoc` runs correctly, and runs correctly without the tweaks at https://github.com/scala/scala/pull/8426

**Comment by som-snytt** [comment]
Ten years ago https://github.com/scala/scala/pull/3901

**Comment by som-snytt** [comment]
This PR is from the first quarter of the year when I was going for a run at the park every day and dropped 15 pounds (weight not money). I'll try to get back to that place, but I think this should move forward. The reason it is painful is that no one bothered to correct the rot a decade ago.

**Comment by lrytz** [comment]
I'm trying it out next week in a big project with a lot (> 10?) of plugin phases.

**Comment by som-snytt** [comment]
🤞

**Comment by SethTisue** [comment]
@som-snytt I'd like to do a community build run on this. mind rebasing it against current HEAD? I could test 2.13.14-bin-6665398-SNAPSHOT, but it would be better if we had all the more recent changes in

**Comment by som-snytt** [comment]
I hope one of you finds something. It occurs to me that besides breaking someone's build, it may also fix someone's build. "Oh, I could never get my plugin to run after erasure."

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/1967/

as an aside, it's pleasant that scala-cli can retrieve PR validation snapshots, e.g. with `-S 2.13.15-bin-441cf5b-SNAPSHOT --repository https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/`

**Comment by som-snytt** [comment]
@SethTisue thanks, I know Lukas has a script and you've explained somewhere how to do it, but you know what, I never have. To test, I fetch the branch and muck around with it. But I've been using `scala-cli` more and will follow up your aside, with gratitude (if it works).

**Comment by som-snytt** [comment]
The community build has so many ignored warnings, it's painful to see. They are careening around the mountain pass, the photo Odersky used to illustrate how Scala devs like their guardrails, which they also prefer to overlook.

**Comment by SethTisue** [comment]
In the community build, it seems that every project using kind-projector broke.

**Comment by som-snytt** [comment]
I'm able to reproduce.
```
[error] scala.reflect.internal.FatalError: Extra name xplicitlocaljs; names [parser,bm4-parser,namer,terminal,explicitouter,erasure,typer,bm4-typer,patmat,async,lambdalift,xsbt-api,xsbt-dependency,refchecks,constructors,flatten,mixin,jscode,delambdafy,cleanup,extmethods,pickler,uncurry,jspretyper,specialize,posterasure,jvm,packageobjects,xsbt-analyzer,jsinterop,pickle,bm4-parser2,superaccessors,fields,tailcalls,xplicitinnerjs,kind-projector]
```
The bad name is `pickle`. (The error message could say that.)
```
jsinterop right after None after List(typer) before List(pickle)
```
For "compatibility", it could just warn loudly instead of erroring on a bad constraint.

```
[warn] No phase `pickle` for jsinterop.runsBefore
```

**Comment by som-snytt** [comment]
Dotty has a fixed "base plan"; only plugins get before and after constraints. That's how it tolerates duplicate phase names.
```
             preRecheck  preRecheck
                recheck  recheck
             preRecheck  preRecheck
                     cc  cc
```

**Comment by SethTisue** [comment]
new CB run queued: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/1971/

I'm leaving tomorrow on vacation, returning July 8, so I might not think to check the results before then

**Comment by som-snytt** [comment]
@SethTisue thanks, that will give me more time to break stuff while you're away.

Edit: under `-Vphases`, the `typelevel-sbt` template shows the same for JVM and JS with or without this change.

I see the dbuild output
```
[cats-effect] [error] /home/jenkins/workspace/scala-2.13.x-jdk17-integrate-community-build/target-0.9.20/project-builds/cats-effect-3a1be8aa145f1120d46b5e8f7d8808274e54b940/kernel/shared/src/main/scala/cats/effect/kernel/Async.scala:393:43: not found: type *
[cats-effect] [error]       L0: Monoid[L]): Async[WriterT[F, L, *]] =
[cats-effect] [error]                                           ^
```
but haven't got a non-trivial build working locally via `scalaHome` yet. Except for plugin compatibility, that is the easiest way to test if you're not dbuild.

Well, I got cats-effect/kernel to build by pegging it to 2.13.14. Tests ran.
```
sbt:cats-effect> compile
[info] compiling 37 Scala sources to /home/amarki/projects/cats-effect/kernel/jvm/target/scala-2.13/classes ...
[info] compiling 1 Scala source to /home/amarki/projects/cats-effect/ioapp-tests/.js/target/scala-2.13/classes ...
[info] compiling 37 Scala sources to /home/amarki/projects/cats-effect/kernel/native/target/scala-2.13/classes ...
[info] compiling 1 Scala source to /home/amarki/projects/cats-effect/ioapp-tests/.native/target/scala-2.13/classes ...
[info] compiling 37 Scala sources to /home/amarki/projects/cats-effect/kernel/js/target/scala-2.13/classes ...
[warn] No phase `pickle` for jsinterop.runsBefore
[info] compiling 39 Scala sources to /home/amarki/projects/cats-effect/std/jvm/target/scala-2.13/classes ...
```

**Comment by lrytz** [comment]
> I'm trying it out next week in a big project with a lot (> 10?) of plugin phases.

Turns out it's 24 additional custom phases, plus async, plus the 3 from zinc. The phase assembly with this patch is the same as before 👍.

The project uses strict contraints, it sets `runsAfter` and `runsBefore` for every custom phase without any slack; every phase has its exact position and each block of custom phases is between two adjacent built in phases.

**Comment by som-snytt** [comment]
@lrytz that's too easy!

File: src/compiler/scala/tools/nsc/PhaseAssembly.scala [hunk 2]
```diff
@@ -29,9 +29,10 @@ trait PhaseAssembly {
    */
   def computePhaseAssembly(): List[SubComponent] = {
     require(phasesSet.exists(phase => phase.initial || phase.phaseName == DependencyGraph.Parser), "Missing initial phase")
-    if (!phasesSet.exists(phase => phase.terminal || phase.phaseName == DependencyGraph.Terminal))
-      if (phasesSet.add(terminal))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/PhaseAssembly.scala]: `add` is always true?

File: src/compiler/scala/tools/nsc/PhaseAssembly.scala [hunk 3]
```diff
@@ -74,11 +75,11 @@ class DependencyGraph(order: Int, start: String, val components: Map[String, Sub
     }
     val v = getNode(from)
     val w = getNode(to)
-    adjacency(v).find(e => e.from == v && e.to == w) match {
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/PhaseAssembly.scala]: `e.from == v` is invariant, right?

File: src/compiler/scala/tools/nsc/PhaseAssembly.scala [hunk 4]
```diff
@@ -157,9 +158,11 @@ class DependencyGraph(order: Int, start: String, val components: Map[String, Sub
         //if (debugging) println(s"deq ${names(v)}")
         for (e <- adjacency(v)) {
           val w = e.to
+          /* cannot happen as `runsRightAfter: Option[String]` is the only way to introduce a `FollowsNow`
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/PhaseAssembly.scala:161]: ... correct?

File: src/compiler/scala/tools/nsc/PhaseAssembly.scala [hunk 5]
```diff
@@ -172,36 +175,38 @@ class DependencyGraph(order: Int, start: String, val components: Map[String, Sub
...
       def sortComponents(c: SubComponent, d: SubComponent): Boolean =
+        // sort by name only, like the old implementation (pre scala/scala#10687)
         /*c.internal && !d.internal ||*/ c.phaseName.compareTo(d.phaseName) < 0
       def sortVertex(i: Int, j: Int): Boolean = sortComponents(componentOf(i), componentOf(j))
 
       distance.zipWithIndex.groupBy(_._1).toList.sortBy(_._1)
       .flatMap { case (d, dis) =>
         val vs = dis.map { case (_, i) => i }
-        val (anchors, followers) = vs.partition(v => edgeTo(v) == null || distance(edgeTo(v).from) != d)
+        val (anchors, followers) = vs.partition(v => edgeTo(v) == null || edgeTo(v).weight != FollowsNow)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/PhaseAssembly.scala:195]: I find that slightly easier to follow - assuming I got it right.

File: src/compiler/scala/tools/nsc/PhaseAssembly.scala [hunk 6]
```diff
@@ -237,18 +242,18 @@ object DependencyGraph {
       for (p <- phases) {
         require(p.phaseName.nonEmpty, "Phase name must be non-empty.")
         def checkConstraint(name: String, constraint: String): Boolean =
-          phases.exists(_.phaseName == name).tap(ok => if (!ok) graph.warning(s"No phase `$name` for ${p.phaseName}.$constraint"))
+          graph.components.contains(name).tap(ok => if (!ok) graph.warning(s"No phase `$name` for ${p.phaseName}.$constraint"))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/PhaseAssembly.scala:245]: This quadratic lookup is where `PhaseAssemblyTest.multipleRunsRightAfter` was spending all of its time

**Review by lrytz — COMMENTED** [review]
Pushed a commit with a few small changes, let me know if I got it right.

The new implementation LGTM, really nice!

**Comment by som-snytt** [comment]
@lrytz thanks, I really appreciate your attention, since no one asked for this change. Now I must refresh my memory and answer your questions, which I will attempt during the next daylight cycle.

File: src/compiler/scala/tools/nsc/PhaseAssembly.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/PhaseAssembly.scala]: well, it's conservative and survives `-Wnonunit-statement`.

**Comment by som-snytt** [comment]
not a vampire, but also didn't find a full daylight cycle for re-re-re-review.

**Comment by SethTisue** [comment]
@som-snytt whatever broke the community build was not fixed before this was merged — see e.g. https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk17-integrate-community-build/1991/console — can you take a look? at a glance, looks like any project that uses kind-projector no longer works

**Comment by som-snytt** [comment]
@SethTisue sorry, that fell off my radar. I'll follow up toot sweet.

**Comment by som-snytt** [comment]
@SethTisue "Oh wait..."

> Well, I got cats-effect/kernel to build by pegging it to 2.13.14. Tests ran.

I think I assumed something else was wrong with dbuild, since I got something to build locally.

Edit: actually it's scaladoc that is erroring, not ordinary compilation.

**Comment by som-snytt** [comment]
I loosened the screws on Scaladoc (obviously https://github.com/scala/scala/blob/2.13.x/src/scaladoc/scala/tools/nsc/ScalaDoc.scala#L42 is not true).

`computePhaseDescriptors` should be final, with template methods (extension points) compute internal, backend, plugins.

bm4's MapRemover and TupleRemover want to run before patmat, which Scaladoc lacks. Maybe I'll add a dummy phase just to reduce noise.
```
[warn] No phase `patmat` for bm4-parser2.runsBefore
[warn] No phase `patmat` for bm4-typer.runsBefore
```

**Comment by SethTisue** [comment]
note that #10807 has some followup work (and https://github.com/scala/bug/issues/13028 means some further followup appears to be needed)
