### PR TITLE
Fix regressions in immutable.TreeMap merge errors from 2.12.x

### LINKED ISSUE #12227: TreeMap addAll should retain existing keys
After https://github.com/scala/scala/pull/9291

```
scala> scala.collection.immutable.TreeMap[String, String]()(_ compareToIgnoreCase _) + ("a" -> "1") + ("A" -> "2")
val res0: scala.collection.immutable.TreeMap[String,String] = TreeMap(a -> 2)

scala> scala.collection.immutable.TreeMap[String, String]()(_ compareToIgnoreCase _) ++ Seq("a" -> "1", "A" -> "2")
val res1: scala.collection.immutable.TreeMap[String,String] = TreeMap(A -> 2)
```

`res1` is wrong

### PR DESCRIPTION
**Pull request by retronym**
Heed the comments in the source about what needed to be adapted
to the new key-retention semantic in 2.13.x.

Make the test work despite scala/bug#12228

Fixes scala/bug#12227

### CODE REVIEW

**Comment by SethTisue** [comment]
does this have anything to do with https://github.com/scala/bug/issues/12227 ?

File: src/library/scala/collection/immutable/RedBlackTree.scala [hunk 1]
```diff
@@ -21,7 +21,9 @@ import scala.runtime.Statics.releaseFence
 /** An object containing the RedBlack tree implementation used by for `TreeMaps` and `TreeSets`.
   *
   *  Implementation note: since efficiency is important for data structures this implementation
-  *  uses `null` to represent empty trees. This also means pattern matching cannot
+  *  uses `null` to represent empty trees. This also means pat
+ *
+ *  itern matching cannot
```
Comment (lrytz) [inline src/library/scala/collection/immutable/RedBlackTree.scala]: some typo here

**Review by lrytz — APPROVED** [review]

**Comment by mkeskells** [comment]
> does this have anything to do with [scala/bug#12227](https://github.com/scala/bug/issues/12227) ?

Yes - I would think so
