### PR TITLE
Erase constant value type [ci: last-only]

### LINKED ISSUE #12301: final val overriding def: Duplicate method name
## reproduction steps

using Scala 2.13.4, example:

```scala
case object Foo extends Product {
  override final val productPrefix = "Foo"
}

println(Foo)
```

## problem

Causes a runtime error in the class loader:

```
java.lang.ClassFormatError: Duplicate method name "productPrefix" with signature "()Ljava.lang.String;" in class file Playground$Foo$
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:98)
	at sbt.internal.BottomClassLoader.lambda$findClass$0(BottomClassLoader.java:56)
	at sbt.internal.ClassLoadingLock.withLock(ClassLoadingLock.java:28)
	at sbt.internal.BottomClassLoader.findClass(BottomClassLoader.java:51)
	at sbt.internal.BottomClassLoader.loadClass(BottomClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Playground$.delayedEndpoint$Playground$1(main.scala:7)
...
```

Possibly related: #8663

### PR DESCRIPTION
**Pull request by som-snytt**
Mixin was confused when `String("hello, world")` overrides `String`.

Fixes scala/bug#12301

### CODE REVIEW

**Comment by som-snytt** [comment]
Quick lunchtime fix. This probably breaks overriding a method of literal type. (Edit: that works after all. I was wondering about the asymmetry of the fix.)

File: src/reflect/scala/reflect/internal/Types.scala [hunk 1]
```diff
@@ -4855,6 +4855,8 @@ trait Types
           false
         case PolyType(_, _) =>
           false
+        case ConstantType(_) =>
+          matchesType(tp1, tp2.underlying.widen, alwaysMatchSimple)
```
Comment (lrytz) [inline src/reflect/scala/reflect/internal/Types.scala]: I'm not convinced this is the right fix. IIUC, `matches` is used for override checking.

----

I really don't understand why `alwaysMatchSimple` is `!phase.erasedTypes`, an explanation of this would be very welcome. The result is (without your patch):

```
scala> typeOf[Int] matches typeOf[String]
val res3: Boolean = true

scala> exitingErasure(typeOf[Int] matches typeOf[String])
val res4: Boolean = false
```

----

The bug is that Mixin creates a mixin forwarder in `X` for `P.p`, it shouldn't do that. Your patch fixes that, so it *does* have an effect in Mixin, but I fear that it has more (potentially undesired) effects. With your patch:

```
scala> exitingErasure(typeOf[""] matches typeOf[String])
val res2: Boolean = false

scala> typeOf[Int] matches typeOf[String]
val res3: Boolean = true
```

----

In Mixin, there is a call to `matchesType` which explicitly sets `alwaysMatchSimple = true`. So maybe the bug is that through some different patch we get from Mixin to `matchesType` with `alwaysMatchSimple = false`?


Or maybe the bug is that the `ConstantType` is not erased?

**Review by lrytz — CHANGES_REQUESTED** [review]

File: src/reflect/scala/reflect/internal/Types.scala (hunk 1 above)
Comment (lrytz) [reply src/reflect/scala/reflect/internal/Types.scala]: > I really don't understand why `alwaysMatchSimple` is `!phase.erasedTypes`, an explanation of this would be very welcome

Maybe the idea is "let's assume things override" before erasure. RefChecks will issue errors when overridding is not correct.


> Or maybe the bug is that the `ConstantType` is not erased?

```
scala> trait P { def p: String = "p" }
     | class X extends P { override final val p      = "x" }
     | class Y extends P { override final val p: "x" = "x" }

scala> exitingErasure(typeOf[X].member(TermName("p")).tpe)
val res1: $r.intp.global.Type = String("x") <and> String

scala> exitingErasure(typeOf[Y].member(TermName("p")).tpe)
val res2: $r.intp.global.Type = (): String

scala> (new X).p
java.lang.ClassFormatError: Duplicate method name "p" with signature "()Ljava.lang.String;" in class file X
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:77)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  ... 36 elided

scala> (new Y).p
val res4: String = x
```

Comment (som-snytt) [reply src/reflect/scala/reflect/internal/Types.scala]: I'll convert to draft and give it some thought.

I moved the scouting commits to a separate PR.

**Comment by som-snytt** [comment]
@lrytz I'll rework this. Also Jean Rondeau will be in [Zürich](https://discord.com/channels/632150470000902164/632628644035952680/959272526486323200) per [the website](https://www.jean-rondeau.com/?page_id=10015)

**Comment by SethTisue** [comment]
@som-snytt is this one you're thinking of reviving...?

**Comment by som-snytt** [comment]
@SethTisue yes, although like all old relationships, I've forgotten what was so attractive about it.

**Comment by som-snytt** [comment]
For my stage name, I may take "Johnny Rondo". TIL "Ryan Starr" is just a stage name.

This is the "quick lunchtime fix" I must have intended two years ago. It is also the last of Lukas's semi-rhetorical questions.

In the test, explicitly annotated `override def x: "x" = "x"` was erased correctly. Unannotated `x(): String("x")` was untouched.

I did not answer Lukas's other question about `matches` during this visit; I left that red herring for another meal.

**Comment by som-snytt** [comment]
The answer is
```
[error]  * method BLACK()java.lang.String in interface scala.io.AnsiColor does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.io.AnsiColor.BLACK")
```
and various osgi
```
[error] Test tools.test.osgi.reflection.toolbox.ReflectionToolBoxTest.basicMirrorThroughOsgi failed: java.lang.ClassFormatError: Method LogPendingSubTypesThreshold in class scala/reflect/internal/tpe/TypeComparers has illegal modifiers: 0x402, took 0.212 sec
```

**Comment by som-snytt** [comment]
The bug fix is to handle `FoldableConstantType` correctly in `reflect.internal.transform.Erasure`.

The rest of the commit is style adjustments while reading code.

It is difficult to see the history above, but the first swing was about matching members; lrytz hinted it's just an erasure problem; and at some point I made that tweak.

A duplicate ticket from a decade ago shows that the symptom has been noticed for some time; that ticket said specialized, so may have been neglected on that basis; it is unknown whether mysterious runtime errors were due to this behavior; OTOH, how often does one override with a constant result.

Edit: maybe this was what gave me pause:

```
[error] ## Exception when compiling 26 sources to /home/runner/work/scala/scala/build/quick/classes/sbt-bridge
[error] java.lang.ClassFormatError: Method HASH_SIZE in class scala/reflect/internal/Names has illegal modifiers: 0x402
```
Edit: that was constructors detecting whether to drop RHS, resulting in abstract member.

**Comment by som-snytt** [comment]
Ran the sbt test locally, thanks to instructions in build.sbt.

```
[info] [info] compiling 1 Scala source to /tmp/sbt_6b9da7a3/target/classes ...
[info] [error] /tmp/sbt_6b9da7a3/A.scala:3:20: type mismatch;
[info] [error]  found   : Int
[info] [error]  required: String
[info] [error]  val z: String = B.y
[info] [error]                    ^
[info] [error] one error found
[info] [error] (Compile / compileIncremental) Compilation failed
[info] [error] Total time: 0 s, completed Apr 28, 2025, 1:53:32 PM
[error] x source-dependencies/false-error [PENDING]
[error]  Cause of test exception: {line 7}  Command failed: compile failed
```
It's supposed to recompile and notice B.y is now a String. From the test name, it looks like erroring was the old behavior.

Or is it supposed to be skipped as "pending" not "test"? What's going on? (That is, I have to learn something new again?)

All the PENDING are failures.

**Comment by lrytz** [comment]
The repording for those pending tests is very confusing :-/
```
[error] x source-dependencies/false-error [PENDING]
[error]  Cause of test exception: {line 7}  Command failed: compile failed
```
is its way of saying "I ran `source-dependencies/false-error` and it failed, as expected, since it's marked pending".

So the scripted tests look clean.

The real error seems to be

```
[error] Test scala.reflect.ClassOfTest.classOfUnitConstant failed: java.lang.ClassFormatError: Duplicate method name "f" with signature "()Ljava.lang.Class;" in class file __wrapper$4$8c32535ff2d0445a8346dfeff9e261a4/__wrapper$4$8c32535ff2d0445a8346dfeff9e261a4$C$1, took 0.094 sec
```

**Comment by som-snytt** [comment]
D'oh, I didn't scroll back far enough. It's so hard to keep up with these important computering skills.

**Comment by som-snytt** [comment]
The other important skill is when the comment says "special case", to preserve the special case.

My other style preference that has evolved is to avoid long lines where the important bit is pushed too far to the right. Less important side effects can be pushed right, speaking typographically not politically. Then vertical alignment becomes a matter of aligning important bits, as we learned when writing out addition with a pencil.

File: src/reflect/scala/reflect/internal/Symbols.scala [hunk 2]
```diff
@@ -2469,12 +2469,8 @@ trait Symbols extends api.Symbols { self: SymbolTable =>
...
      *  @param ofclazz is a subclass of this symbol's owner
      */
-    final def overridingSymbol(ofclazz: Symbol): Symbol = (
-      if (canMatchInheritedSymbols)
-        matchingSymbol(ofclazz, ofclazz.thisType)
-      else
-        NoSymbol
-    )
+    final def overridingSymbol(ofclazz: Symbol): Symbol =
+      if (canMatchInheritedSymbols) matchingSymbol(ofclazz, ofclazz.thisType) else NoSymbol
```
Comment (som-snytt) [inline src/reflect/scala/reflect/internal/Symbols.scala:2473]: One-liner has the same form as previous method; this works well because the else alternative is trivial.

File: src/compiler/scala/tools/nsc/transform/Constructors.scala [hunk 3]
```diff
@@ -609,7 +607,7 @@ abstract class Constructors extends Statics with Transform with TypingTransforme
 
       private def triage() = {
         // Constant typed vals are not memoized.
-        def memoizeValue(sym: Symbol) = !sym.info.resultType.isInstanceOf[FoldableConstantType]
+        def memoizeValue(sym: Symbol) = enteringErasure(!sym.info.resultType.isInstanceOf[FoldableConstantType])
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/transform/Constructors.scala:610]: Why it's important to study history.

File: src/compiler/scala/tools/nsc/transform/Constructors.scala [hunk 4]
```diff
@@ -691,14 +690,22 @@ abstract class Constructors extends Statics with Transform with TypingTransforme
...
+                && (statSym.isSetter || memoizeValue(statSym))
+              )
+              val toMove =
+                if (shouldMoveRHS) {
+                  if (statSym.isGetter)
+                    moveEffectToCtor(dd.mods, dd.rhs, statSym.asTerm.referenced.orElse(statSym.setterIn(clazz)))
+                  deriveDefDef(stat)(_ => EmptyTree)
+                }
+                else dd
+              defBuf += toMove
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/transform/Constructors.scala:708]: I used to think vertical boolean exprs (wrapped in parens) were too much style just to have leading infix operators, but after using actual leading infix (without parens), I find it much easier to read. I only preferred the one-liner because mentally I would skip it and that's why it felt easier to read.

note that under `-Xsource:3` we could be using leading infix.

File: src/reflect/scala/reflect/internal/transform/Erasure.scala [hunk 5]
```diff
@@ -134,8 +134,10 @@ trait Erasure {
     def apply(tp: Type): Type = tp match {
       case FoldableConstantType(ct) =>
         // erase classOf[List[_]] to classOf[List]. special case for classOf[Unit], avoid erasing to classOf[BoxedUnit].
-        if (ct.tag == ClazzTag && ct.typeValue.typeSymbol != UnitClass) ConstantType(Constant(apply(ct.typeValue)))
-        else tp
+        if (ct.tag == ClazzTag)
+          if (ct.typeValue.typeSymbol == UnitClass) tp
+          else ConstantType(Constant(apply(ct.typeValue)))
+        else ct.tpe
```
Comment (som-snytt) [inline src/reflect/scala/reflect/internal/transform/Erasure.scala:140]: The fix for erasure. There are really 2 special cases under `Class` constant. Presumably the `Unit` case is handled specially later, but from this perspective, the encoding doesn't look regular.

**Review by lrytz — APPROVED** [review]
"so deep but yet so simple". thank you!
