### PR TITLE
Don't resolve symlinks in -Wconf:src

### LINKED ISSUE #13145: -Wconf:src filter resolves symlinks, breaking `external/` filters in Bazel 9
## Reproduction steps

The following requires [Bazelisk](https://github.com/bazelbuild/bazelisk?tab=readme-ov-file#bazelisk) for selecting the Bazel version.

```sh
$ mkdir wconfsrc-repro
$ cd wconfsrc-repro
$ cat >MODULE.bazel
module(name = "wconfsrc_repro")

bazel_dep(name = "rules_scala", version = "7.1.5")

scala_config = use_extension(
    "@rules_scala//scala/extensions:config.bzl",
    "scala_config",
)
scala_config.settings(scala_version = "2.13.17")

scala_deps = use_extension(
    "@rules_scala//scala/extensions:deps.bzl",
    "scala_deps",
)
scala_deps.scala()

register_toolchains("//...:all")
^D

$ cat >BUILD
load("@rules_scala//scala:scala_toolchain.bzl", "scala_toolchain")

scala_toolchain(
    name = "toolchain_impl",
    scalacopts = [
        "-Xfatal-warnings",
        "-deprecation",
        "-Wconf:src=bazel-out/.*:s",
        "-Wconf:src=external/.*:s",
    ],
)

toolchain(
    name = "toolchain",
    toolchain = ":toolchain_impl",
    toolchain_type = "@rules_scala//scala:toolchain_type",
    visibility = ["//visibility:public"],
)
^D

# Output edited for readability
$ USE_BAZEL_VERSION=9.0.0rc1 bazel build \
  @rules_scala//third_party/dependency_analyzer/src/main:dependency_analyzer

INFO: Analyzed target
  @@rules_scala+//third_party/dependency_analyzer/src/main:dependency_analyzer
  (1 packages loaded, 15 targets and 16 aspects configured).
  [ ...snip... ]
ERROR: /private/var/tmp/_bazel_mbland/.../external/rules_scala+/third_party/dependency_analyzer/src/main/BUILD:4:39:
  scala @@rules_scala+//third_party/dependency_analyzer/src/main:dependency_analyzer failed:
  [ ...snip... ]
external/rules_scala+/third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/Reporter213.scala:21:
  warning: object JavaConverters in package collection is deprecated (since 2.13.0): Use `scala.jdk.CollectionConverters` instead
      case r: DepsTrackingReporter => r.registerAstUsedJars(usedJarPathToPositions.keys.toSet.asJava)
                                                                                        ^
external/rules_scala+/third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/Reporter213.scala:28:
  warning: method doReport in class FilteringReporter is deprecated (since 2.13.12): use the `doReport` overload instead
    global.reporter.doReport(pos, message, global.reporter.ERROR)
                    ^
external/rules_scala+/third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/Reporter213.scala:33:
  warning: method doReport in class FilteringReporter is deprecated (since 2.13.12): use the `doReport` overload instead
    global.reporter.doReport(pos, message, global.reporter.WARNING)
                    ^
error: No warnings can be incurred under -Werror.
3 warnings
1 error
Build failure with errors.
Target @@rules_scala+//third_party/dependency_analyzer/src/main:dependency_analyzer failed to build
[ ...snip... ]
```

## Problem

The `-Wconf:src` filter in 2.12 and 2.13 resolves each source path to its canonical form before matching it. If the original path is a symlink, the actual path may not match the filter. This renders `-Wconf:src=external/.*:s` filters to silence warnings in external source repositories under Bazel 9 ineffective.

- [The -Wconf:src parser creates a SourcePattern object from its regex](https://github.com/scala/scala/blob/v2.13.17/src/compiler/scala/tools/nsc/Reporting.scala#L862-L871).
- [SourcePattern.check() ultimately applies its pattern to java.io.File.getCanonicalPath()](https://github.com/scala/scala/blob/v2.13.17/src/compiler/scala/tools/nsc/Reporting.scala#L777).
- [java.io.File.getCanonicalPath() resolves all symlinks](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getCanonicalPath--).

Scala3 does not have this issue, since [Scala 3.5.0 and later uses toAbsolutePath in its implementation instead](https://github.com/scala/scala3/blob/3.5.0/compiler/src/dotty/tools/dotc/reporting/WConf.scala#L29). Updating the `MODULE.bazel` file to use Scala 3.5.2 and adding/removing the `-Wconf:src=external/.*:s` flag demonstrates this.

Users may currently work around this problem by applying `-Wconf:src=cache/repos/v1/contents/.*:s` when building with Bazel 9. However, the behavior is still surprising, and the workaround isn't particularly discoverable or stable.

I'm happy to send a pull request to update `SourcePattern.check()` to use `absolutePath` instead.

(Granted, I/we should update the `rules_scala` implementations to address the deprecation warnings. But for now, they effectively illustrate the problem.)

---

More detail on the Bazel side: The [Bazel output directory layout](https://bazel.build/remote/output-directories) stores unpacked external source archives, such as [rules_scala](https://github.com/bazel-contrib/rules_scala), in an `external/` directory. This directory contains symlinks to the actual archives elsewhere on the file system.

- Under Bazel 8, the actual path contains an `external/` segment.
- Under Bazel 9, the actual path no longer contains an `external/` segment. It now reflects the changes from bazelbuild/bazel@ad74aa5d9e29e7d4ab3043328ee25901be9e14f6 and bazelbuild/bazel@e66fe55aa187e8eaacbbd949d7e02e2a8cc56ce3.

```sh
# Change to the execroot directory revealed by building with
# `bazel build -s`
$ pushd /private/var/tmp/_bazel_mbland/.../execroot/_main

# Same `external/` symlink for both versions, pointing into the `external/`
# sibling of `execroot/`
$ ls -l external/rules_scala+
lrwxr-xr-x  1 mbland  wheel  85 Dec 11 14:08 external/rules_scala+@ -> /private/var/tmp/_bazel_mbland/.../external/rules_scala+

# The actual `external/rules_scala+` directory exists under 8.4.2
$ ls -l ../../external/rules_scala+
[ ...shows contents of actual external/rules_scala+ directory... ]

# The `external/rules_scala+` symlink under 9.0.0rc1,
# where the `...` segments are hash values
$ ls -l ../../external/rules_scala+
lrwxr-xr-x  1 mbland  wheel  148 Dec 11 16:45 ../../external/rules_scala+@ -> /var/tmp/_bazel_mbland/cache/repos/v1/contents/.../...
```

cc: @fmeum @Wyverald @rafikk

Also cc: @lrytz, author of scala/scala@39d3b3a93cd3cf01303ba9aba487b742943d8e57 and scala/scala#8373, in case there was a rationale for using `canonicalPath` over `absolutePath`.

### PR DESCRIPTION
**Pull request by mbland**
Updates the -Wconf:src filter to resolve each source path to its absolute, normalized form (instead of its canonicalized form) before matching it.

Previously, filters intended to match symlinked paths would not apply when their canonicalized paths didn't contain the same path components. For example, Bazel 9 changed the location of symlinked source repositories for external dependencies such that their canonicalized paths no longer contained an `external/` component. This rendered `-Wconf:src=external/.*:s` filters to silence warnings in these external source repositories ineffective.

This implementation closely matches the Scala3 implementation (as of 3.8.0-RC3), though it does not use `toURI`. Testing revealed that `toURI` prepends the current working directory to Windows-like paths unconditionally, and converts backslashes in such paths to `%5C` escape sequences.

- https://github.com/scala/scala3/blob/3.8.0-RC3/compiler/src/dotty/tools/dotc/reporting/WConf.scala#L33

Fixes scala/bug#13145. Review by @lrytz.

### CODE REVIEW

**Comment by mbland** [comment]
It looks like [Jenkins ran out of space](https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/20228/console):

```txt
Fetching changes from the remote Git repository
ERROR: Checkout failed
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to jenkins-worker-behemoth-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1916)
		[ ...snip... ]
		at java.base/java.lang.Thread.run(Unknown Source)
java.io.IOException: No space left on device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
		[ ...snip... ]
ERROR: Maximum checkout retry attempts reached, aborting
```

File: src/compiler/scala/tools/nsc/Reporting.scala [hunk 1]
```diff
@@ -774,7 +774,8 @@ object Reporting {
       private[this] val cache = mutable.Map.empty[SourceFile, Boolean]
 
       def check(pos: Position) = cache.getOrElseUpdate(pos.source, {
-        val sourcePath = pos.source.file.canonicalPath.replace("\\", "/")
+        val sourceFile = pos.source.file.absolute.file
+        val sourcePath = sourceFile.toPath.normalize.toString.replace("\\", "/")
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/Reporting.scala]: `source.file` is an `AbstractFile`, which has a bunch of subtypes. We need to make sure what we do here works / is safe for all of them; in particular, `VirtualFile.file` seems to be `null`.

Sad that this didn't turn up in our test suite...

```suggestion
        val sourcePath = Option(sourceFile).map(_.toPath.normalize.toString).getOrElse(pos.source.path).replace("\\", "/")
```

Comment (mbland) [reply src/compiler/scala/tools/nsc/Reporting.scala]: Done in ce5c0c68cfd7dca2e7cd838cbd5e95fb3ff8d515. Added `WConfTest.sourcePatternMatchesVirtualFiles` to validate the before and after behavior.

**Review by lrytz — APPROVED** [review]
Thank you!

**Comment by lrytz** [comment]
> Testing revealed that `toURI` prepends the current working directory to Windows-like paths unconditionally, and converts backslashes in such paths to `%5C` escape sequences

Is that something we should fix on the Scala 3 side?

**Comment by mbland** [comment]
> Is that something we should fix on the Scala 3 side?

I can try it today and report back.

**Comment by mbland** [comment]
@lrytz I just filed scala/scala3#24771 and scala/scala3#24772 to avoid `Path.toURI` and to fix Windows paths. I also adapted some of the test cases from this pull request.

**Comment by lrytz** [comment]
Thank you!
