### PR TITLE
More details to forward reference error messages

### LINKED ISSUE #12382: Improve forward reference extends over definition of value
Hello, team,

I encountered compilation error on Scala 2.13.4 and it took sometime to understand what's wrong. Here is minimum example:
```scala
import scala.concurrent.{Await, ExecutionContext, Future}

def foo: Future[Int] = {
  val fInt = Future.successful(1)
  val z = for {
    a <- fInt
  } yield a

  implicit val ec: ExecutionContext = scala.concurrent.ExecutionContext.Implicits.global
  z
}
```
Compiler says:
```
On line 4: error: forward reference extends over definition of value z
```
image

Link to code: https://scastie.scala-lang.org/vLXzS5OwSSSKUnJDvtFQxA

The problem is with `implicit val ec: ExecutionContext`, it is defined after it is referenced in for comprehension. Would be great to improve the error message to provide some hints what causes the problem. 

Thanks

### PR DESCRIPTION
**Pull request by joroKr21**
Include the referenced symbol and the line where it's defined.

Closes scala/bug#12382

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/RefChecks.scala [hunk 1]
```diff
@@ -1215,23 +1215,26 @@ abstract class RefChecks extends Transform {
...
+      s"$refsym defined on line ${refsym.pos.line}"
+    }
+
     def transformStat(tree: Tree, index: Int): Tree = tree match {
       case t if treeInfo.isSelfConstrCall(t) =>
         assert(index == 0, index)
         try transform(tree)
         finally if (currentLevel.maxindex > 0) {
-          // An implementation restriction to avoid VerifyErrors and lazyvals mishaps; see scala/bug#4717
-          debuglog("refsym = " + currentLevel.refsym)
```
Comment (joroKr21) [inline src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:1224]: Funny that it was considered useful to `debuglog` but not reveal to the user

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:1224]: Funny ha-ha or funny just sad.

File: test/files/neg/forward.scala [hunk 2]
```diff
@@ -21,4 +23,13 @@ object Test {
     Console.println("foo");
     def g: Int = f;
   }
+  {
```
Comment (som-snytt) [inline test/files/neg/forward.scala:26]: I'd be remiss as a reviewer if I didn't mention that putting the import in this brace results in smaller diff.

**Review by som-snytt — APPROVED** [review]
It also looks nice in REPL! I expected `fullLocationString` or whatever, but just the line number is very nice and easy. Welcome, and congratulations on your good first issue!

**Review by dwijnand — APPROVED** [review]
Thank you

File: test/files/neg/forward.scala (hunk 2 above)
Comment (joroKr21) [reply test/files/neg/forward.scala:26]: Too late now

File: src/compiler/scala/tools/nsc/typechecker/RefChecks.scala (hunk 1 above)
Comment (joroKr21) [reply src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:1224]: Open to interpretation

**Comment by joroKr21** [comment]
> It also looks nice in REPL! I expected fullLocationString or whatever, but just the line number is very nice and easy.

Yeah I think the full location is useless without a caret.
