### PR TITLE
When expanding macros, evaluate class and enum constants

### LINKED ISSUE #12680: In a macro `c.eval` for `java.lang.Class[_]` produces `c.Type`/`Class[_]` depending on whether to define a variable
## Reproduction steps

Scala version: 2.13.10

- If we define a variable `classValue` in a macro then upon expansion the macro produces `ClassCastException`

```scala
def foo(clazz: Class[_]): Unit = macro fooImpl

def fooImpl(c: blackbox.Context)(clazz: c.Tree): c.Tree = {
  import c.universe._
  val classValue = c.eval(c.Expr[Class[_]](c.untypecheck(clazz))) // HERE!!!
  q"()"
}
```
```scala
foo(classOf[String])
```
```
java.lang.ClassCastException: scala.reflect.internal.Types$ClassNoArgsTypeRef cannot be cast to java.lang.Class
```
https://scastie.scala-lang.org/DmytroMitin/RINjJfNsRNqprn9nR1ZpDQ/9 (toolbox is not used for actual reproduction, it's just for Scastie because it doesn't support multiple files/subprojects).

- If we don't define a variable then the macro expands successfully

```scala
def foo(clazz: Class[_]): Unit = macro fooImpl

def fooImpl(c: blackbox.Context)(clazz: c.Tree): c.Tree = {
  import c.universe._
  println(c.eval(c.Expr[Class[_]](c.untypecheck(clazz)))) // HERE!!!
  q"()"
}
```
```scala
foo(classOf[String]) // ()
// prints: String
```

https://scastie.scala-lang.org/DmytroMitin/RINjJfNsRNqprn9nR1ZpDQ/18

## Problem

The macro should expand successfully both times and `c.eval` should produce `Class[_]` both times.

A workaround is casting (when possible)
```scala
val classValue = c.mirror.asInstanceOf[c.universe.RuntimeMirror]
  .runtimeClass(
    c.eval(c.Expr[Type](c.untypecheck(clazz)))
  ).asInstanceOf[Class[_]
```
https://scastie.scala-lang.org/DmytroMitin/RINjJfNsRNqprn9nR1ZpDQ/33

or runtime reflection in macros
```scala
val rm = scala.reflect.runtime.currentMirror
val classValue =
  rm.runtimeClass(
    c.eval(c.Expr[rm.universe.Type](c.untypecheck(clazz)))
  ).asInstanceOf[Class[_]]
```
https://scastie.scala-lang.org/DmytroMitin/RINjJfNsRNqprn9nR1ZpDQ/32

If we remove `c.untypecheck` or replace it with `c.resetAllAttrs` (from https://github.com/scalamacros/resetallattrs) nothing changes.

If we replace existential with `Class[T]` nothing changes. 

Discovered here: https://stackoverflow.com/questions/71390113/get-annotations-from-class-in-scala-3-macros

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12680

Just in time for Hacktober.

### CODE REVIEW

File: src/compiler/scala/reflect/macros/contexts/Evals.scala [hunk 1]
```diff
@@ -24,8 +24,14 @@ trait Evals {
   private lazy val evalImporter = ru.internal.createImporter(universe).asInstanceOf[ru.Importer { val from: universe.type }]
 
   def eval[T](expr: Expr[T]): T = {
+    def specialK(x: Any) =
```
Comment (som-snytt) [inline src/compiler/scala/reflect/macros/contexts/Evals.scala:27]: `K` is for `Konstant`, of course.

Comment (lrytz) [reply src/compiler/scala/reflect/macros/contexts/Evals.scala:27]: Ja Klar

**Review by lrytz — APPROVED** [review]
Thanks!
