### PR TITLE
Fix TrieMap#{filterInPlace,mapValuesInPlace}

### LINKED ISSUE #12443: Incorrect filterInPlace behavior in TrieMap
## reproduction steps
Method `filterInPlace` is not reimplemented in `TrieMap` and relies instead on the `MapOps` implementation. This implementation does not work on a concurrent map because it uses the code:
```scala
if (!p(k, v)) {
    this -= k
}
```
This could remove a value other than `v`, added concurrently, that does satisfy the predicate.

The bug could be demonstrated with the following code, using Scala 3.0.1:

```scala
val exec = Executors.newCachedThreadPool()

def slowPositive(x: Int): Boolean =
   SECONDS.sleep(2)
   x > 0

val map = TrieMap("K" -> 0)

exec.execute(() => map.filterInPlace((_, v) => slowPositive(v)))

exec.execute { () =>
   SECONDS.sleep(1)
   map += "K" -> 1
}

exec.shutdown()
exec.awaitTermination(10, SECONDS)

assert(map.get("K").contains(1)) // should be true
```
The pair `("K",1)` cannot be removed by filtering positive values and should be present in the map at the end.

## remedy

The quickest solution would be to replace `-=` with `remove(k,v)` in `MapOps`, but this would have an unnecessary performance cost on all the non-concurrent maps.  The next quickest is to copy the implementation of `filterInPlace` from `MapOps` into `TrieMap` and replace `-=` with `remove(k,v)` there.  But this code copies the entire map into an array in order to avoid `ConcurrentModificationException`.  This is overkill in a concurrent map that, presumably, can handle modifications during iterations.  So, the best approach is probably to rewrite the method directly in terms of the `TrieMap` implementation.  It looks like using `iterator` and `remove(k,v)` should work, but may not be the best approach.  There's nothing trickier than non-blocking concurrent code!  Whoever wrote `TrieMap` would know best.

### PR DESCRIPTION
**Pull request by NthPortal**
Fix the behaviour of `TrieMap#filterInPlace` and
`TrieMap#mapValuesInPlace` to respect atomic entry changes.

Built on top of #9726

Fixes scala/bug#12443

### CODE REVIEW

**Comment by NthPortal** [comment]
currently an inefficient but simpler implementation. i'm working on a faster one, but... I think we should merge the reliable one first, and think about optimisation later

**Comment by NthPortal** [comment]
oops I'm going to overengineer a test again 😬

File: src/library/scala/collection/mutable/Map.scala [hunk 1]
```diff
@@ -171,17 +171,19 @@ trait MapOps[K, V, +CC[X, Y] <: MapOps[X, Y, CC, _], +C <: MapOps[K, V, CC, C]]
...
-    if (nonEmpty) {
-      val array = this.toArray[Any] // scala/bug#7269 toArray avoids ConcurrentModificationException
-      val arrayLength = array.length
-      var i = 0
-      while (i < arrayLength) {
-        val (k, v) = array(i).asInstanceOf[(K, V)]
-        if (!p(k, v)) {
-          this -= k
+    if (!isEmpty) this match {
+      case tm: concurrent.TrieMap[_, _] => tm.asInstanceOf[concurrent.TrieMap[K, V]].filterInPlaceImpl(p)
```
Comment (johnynek) [inline src/library/scala/collection/mutable/Map.scala]: Why this pattern vs overriding the method on TrieMap?

File: src/library/scala/collection/mutable/Map.scala [hunk 2]
```diff
@@ -197,8 +199,9 @@ trait MapOps[K, V, +CC[X, Y] <: MapOps[X, Y, CC, _], +C <: MapOps[K, V, CC, C]]
     * @return   the map itself.
     */
   def mapValuesInPlace(f: (K, V) => V): this.type = {
-    if (nonEmpty) this match {
+    if (!isEmpty) this match {
```
Comment (johnynek) [inline src/library/scala/collection/mutable/Map.scala:202]: Why `!isEmpty` instead of nonEmpty?

File: src/library/scala/collection/mutable/Map.scala (hunk 1 above)
Comment (NthPortal) [reply src/library/scala/collection/mutable/Map.scala]: the method returns `this.type`, which is the type of its class in bytecode. thus, the override has a different return type, and it is not binary compatible

File: src/library/scala/collection/mutable/Map.scala (hunk 2 above)
Comment (NthPortal) [reply src/library/scala/collection/mutable/Map.scala:202]: basically, despite the fact that the latter really ought to be always trivially optimisable, `!isEmpty` sometimes has better performance then `nonEmpty`. I don't recall when/where this discovery happened or was mentioned; the best I can find in reference to it is #7898

File: src/library/scala/collection/concurrent/TrieMap.scala [hunk 3]
```diff
@@ -1008,6 +1008,24 @@ final class TrieMap[K, V] private (r: AnyRef, rtupd: AtomicReferenceFieldUpdater
     r.cachedSize(this)
   }
 
+  private[collection] def filterInPlaceImpl(p: (K, V) => Boolean): this.type = {
+    val it = readOnlySnapshot().iterator
```
Comment (lrytz) [inline src/library/scala/collection/concurrent/TrieMap.scala]: could this use `iterator` (which only calls `readOnlySnapshot()` if `nonReadOnly`)?

File: src/library/scala/collection/concurrent/TrieMap.scala [hunk 4]
```diff
@@ -1008,6 +1008,24 @@ final class TrieMap[K, V] private (r: AnyRef, rtupd: AtomicReferenceFieldUpdater
...
+    while (it.hasNext) {
+      val (k, v) = it.next()
+      if (p(k, v)) remove(k, v) // does unnecessary equality checking
```
Comment (lrytz) [inline src/library/scala/collection/concurrent/TrieMap.scala]: what's the unnecessary check? using `==` instead of `eq` when comparing the `v`?

**Review by lrytz — COMMENTED** [review]
LGTM (let's merge https://github.com/scala/scala/pull/9726 first though)

File: src/library/scala/collection/concurrent/TrieMap.scala (hunk 4 above)
Comment (NthPortal) [reply src/library/scala/collection/concurrent/TrieMap.scala]: correct. unfortunately, the contract of `remove` seems to require `==`. at least given that we implement it for `JConcurrentMapWrapper` using a Java method that uses `equals`

File: src/library/scala/collection/concurrent/TrieMap.scala (hunk 3 above)
Comment (NthPortal) [reply src/library/scala/collection/concurrent/TrieMap.scala]: if we're trying to call `filterInPlace` on a read-only snapshot, something has gone horribly, horribly wrong. (this is actually something we thought of when working on it, and arguably something we should have left a comment about, but it's moot anyway due to the following.)

regardless, the implementation needs to be moved up to the `concurrent.Map` trait (see https://github.com/scala/bug/issues/12443#issuecomment-898899755), so it's just going to call `iterator` without `readOnlySnapshot()` after we push that change anyway. we're figuring out how not to duplicate the test for the two implementations before pushing the change though

**Comment by NthPortal** [comment]
@lrytz I think this has changed enough to need a re-review

File: test/junit/scala/collection/concurrent/ConcurrentMapTester.scala [hunk 5]
```diff
@@ -0,0 +1,41 @@
+package scala.collection.concurrent
+
+import java.util.concurrent.Executors
+import java.util.concurrent.atomic.AtomicReference
+import scala.collection.immutable.Queue
+import scala.concurrent.duration.TimeUnit
+
+class ConcurrentMapTester[K, V](map: Map[K, V]) {
+  private[this] val tasks = new AtomicReference[Seq[Runnable]](Queue.empty)
```
Comment (lrytz) [inline test/junit/scala/collection/concurrent/ConcurrentMapTester.scala]: There's no concurrent access to `tasks`, is the `AtomicReference` future-proofing for tests that would do so?

**Review by lrytz — APPROVED** [review]
LGTM, thank you!

Rebased and added MiMa filters.

File: test/junit/scala/collection/concurrent/ConcurrentMapTester.scala (hunk 5 above)
Comment (NthPortal) [reply test/junit/scala/collection/concurrent/ConcurrentMapTester.scala]: honestly, it's an artifact of a substantially different tester design. I'll try to simplify it

Comment (NthPortal) [reply test/junit/scala/collection/concurrent/ConcurrentMapTester.scala]: now a `ConcurrentMapTester` can be used more than once (i.e. `runTasks` then check the results, `runTasks` again, etc.)

**Comment by SethTisue** [comment]
@NthPortal the Scala community build (plus `git bisect`) found that this is making a twitter-util test hang

the problem is reproducible by cloning https://github.com/twitter/util and running `util-logging/testOnly *ThrottledHandler*` in sbt. it succeeds with `++2.13.6` but fails with `++2.13.7-bin-891e58b`

do you have time to dig into it...?

**Comment by NthPortal** [comment]
that's really bad. but also how??? yeah, I'll look into it

**Comment by NthPortal** [comment]
oh noooooooooooo

File: src/library/scala/collection/concurrent/Map.scala [hunk 6]
```diff
@@ -131,4 +131,22 @@ trait Map[K, V] extends scala.collection.mutable.Map[K, V] {
       case _ => this.updateWithAux(key)(remappingFunction)
     }
   }
+
+  private[collection] def filterInPlaceImpl(p: (K, V) => Boolean): this.type = {
+    val it = iterator
+    while (it.hasNext) {
+      val (k, v) = it.next()
+      if (p(k, v)) remove(k, v)
```
Comment (NthPortal) [inline src/library/scala/collection/concurrent/Map.scala:139]: oops I inverted the condition by accident

```suggestion
      if (!p(k, v)) remove(k, v)
```

Comment (NthPortal) [reply src/library/scala/collection/concurrent/Map.scala:139]: fixed in #9737

**Comment by SethTisue** [comment]
followup: #9737
