### PR TITLE
Java imports compete with level 4 definitions

### LINKED ISSUE #12195: java.lang.NoSuchFieldError when mix Scala and Java types
## reproduction steps

using Scala (2.13.3 and Scala 2.12.12, SBT 1.4.1)
Minimal reproducible example: https://github.com/REASY/scala-compiler-bug

## problem
There is a small app https://github.com/REASY/scala-compiler-bug/blob/main/src/main/scala/example/Example.scala#L7 which suppose to print 
```
example.scala.Document.getMember(foo)
```
but instead it fails on runtime with the error `java.lang.NoSuchFieldError: document`:
```
$ sbt ";clean;cleanFiles;runMain example.Example"
[info] welcome to sbt 1.4.1 (Oracle Corporation Java 1.8.0_261)
[info] loading global plugins from C:\Users\User\.sbt\1.0\plugins
[info] loading settings for project scala-compiler-bug-build from plugins.sbt ...
[info] loading project definition from C:\Users\User\AppData\Local\Temp\scala-compiler-bug\project
[info] loading settings for project root from build.sbt ...
[info] set current project to compiler-bug (in build file:/C:/Users/User/AppData/Local/Temp/scala-compiler-bug/)
[success] Total time: 0 s, completed Oct 20, 2020 7:19:17 PM
[success] Total time: 0 s, completed Oct 20, 2020 7:19:18 PM
[info] compiling 2 Scala sources and 2 Java sources to C:\Users\User\AppData\Local\Temp\scala-compiler-bug\target\scala-2.13\classes ...
[info] done compiling
[info] running example.Example
[error] (run-main-0) java.lang.NoSuchFieldError: document
[error] java.lang.NoSuchFieldError: document
[error]         at example.Example$.main(Example.scala:9)
[error]         at example.Example.main(Example.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run 'last Compile / bgRunMain' for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 2 s, completed Oct 20, 2020 7:19:20 PM
```
image

There is Java type [Window](https://github.com/REASY/scala-compiler-bug/blob/main/src/main/java/example/java/Window.java#L8) which has a public field `document` with Scala type [Document](https://github.com/REASY/scala-compiler-bug/blob/main/src/main/scala/example/scala/Document.scala). `Window` class is instantiated and accessed in runnable class https://github.com/REASY/scala-compiler-bug/blob/main/src/main/scala/example/Example.scala
```scala
package example

import example.java.Window

// To run via SBT use in shell: `sbt "runMain example.Example"`
object Example {
  def main(args: Array[String]): Unit = {
    val wnd = new Window()
    val res = wnd.document.getMember("foo").toString
    println(res)
  }
}
```

## Investigation
If I look to the generated bytecode using `javap` I can see that `example.java.Window` is looking as expected, `document` field's type is correct:
```
scala> :javap -c example.java.Window
Compiled from "Window.java"
public class example.java.Window {
  public final example.scala.Document document;

  public example.java.Window();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: aload_0
       5: new           #2                  // class example/scala/Document
       8: dup
       9: invokespecial #3                  // Method example/scala/Document."<init>":()V
      12: putfield      #4                  // Field document:Lexample/scala/Document;
      15: return
}
```
On the other hand, the accessed type of document in `example.Example$.main` method is wrong, it is `example/java/Document` instead of `example/scala/Document`:
```
scala> :javap -c example.Example$
Compiled from "Example.scala"
public final class example.Example$ {
  public static final example.Example$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class example/Example$
       3: dup
       4: invokespecial #12                 // Method "<init>":()V
       7: putstatic     #14                 // Field MODULE$:Lexample/Example$;
      10: return

  public void main(java.lang.String[]);
    Code:
       0: new           #19                 // class example/java/Window
       3: dup
       4: invokespecial #20                 // Method example/java/Window."<init>":()V
       7: astore_2
       8: aload_2
       9: getfield      #24                 // Field example/java/Window.document:Lexample/java/Document;
      12: ldc           #26                 // String foo
      14: invokevirtual #32                 // Method example/java/Document.getMember:(Ljava/lang/String;)Ljava/lang/Object;
      17: invokevirtual #36                 // Method java/lang/Object.toString:()Ljava/lang/String;
      20: astore_3
      21: getstatic     #41                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
      24: aload_3
      25: invokevirtual #45                 // Method scala/Predef$.println:(Ljava/lang/Object;)V
      28: return
}
```
image

### PR DESCRIPTION
**Pull request by som-snytt**
Like Scala, an import in Java can shadow a definition
in another file, if it is not import-on-demand.

The implementation bailed too quickly from searching
enclosing contexts while testing this condition.

Fixes scala/bug#12195

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
Thanks for picking up the ticket

**Comment by lrytz** [comment]
```
!!    1 - pos/t7232b                                [compilation failed with 1 errors]
##### Log file '/home/jenkins/workspace/scala-2.13.x-validate-main@3/test/files/pos/t7232b-pos.log' from failed test #####

Foo.java:7: error: reference to List is ambiguous;
it is both defined in package pack and imported subsequently by
import _root_.java.util._
	public static List list() { throw new Error(); }
	              ^
1 error
```

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 1]
```diff
@@ -1499,26 +1499,41 @@ trait Contexts { self: Analyzer =>
...
+        @inline def importCanShadowAtDepth(imp: ImportInfo) = {
+          @inline def importCompetesWithDefinition =
+            if (thisContext.unit.isJava) imp.depth == symbolDepth && defIsLevel4
+            else defIsLevel4
+          imp.depth > symbolDepth || importCompetesWithDefinition
+        }
+
+        while (!impSym.exists && importCursor.imp1Exists && importCanShadowAtDepth(importCursor.imp1)) {
+          val javaRule = thisContext.unit.isJava && defIsLevel4
+          val (sel, sym) = lookupImport(imp1, requireExplicit = javaRule)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1519]: That `requireExplicit` flag is handy, and setting it is the relevant diff.

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 2]
```diff
@@ -1499,26 +1499,41 @@ trait Contexts { self: Analyzer =>
...
 
       val preferDef: Boolean = defSym.exists && (!impSym.exists || {
         // 4) root imported symbols have same (lowest) precedence as package-owned symbols in different compilation units.
         if (imp1.depth < symbolDepth && imp1.isRootImport && foreignDefined)
           true
         // 4) imported symbols have higher precedence than package-owned symbols in different compilation units.
-        else if (imp1.depth >= symbolDepth && foreignDefined)
+        //    except that in Java, the import must be "explicit" (level 2)
+        else if (thisContext.unit.isJava && imp1.depth == symbolDepth && foreignDefined)
+          !importCursor.imp1Explicit
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1535]: IIUC the cursor will never pick up a wildcard because it will `requireExplicit`. In that case, `imp1Explicit` will be true and `preferDef` will be false.

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 3]
```diff
@@ -1531,8 +1546,8 @@ trait Contexts { self: Analyzer =>
           return ambiguousDefnAndImport(defSym.alternatives.head.owner, imp1)
       })
 
-      // If the defSym is at 4, and there is a def at 1 in scope, then the reference is ambiguous.
-      if (foreignDefined && !defSym.isPackage) {
+      // If the defSym is at 4, and there is a def at 1 in scope due to packaging, then the reference is ambiguous.
+      if (foreignDefined && !defSym.isPackage && !thisContext.unit.isJava) {
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1550]: Since Java does not have nested packagings for visibility, this extra check is unnecessary in Java.

The level one definition in Scala would have to be defined in an enclosing package in the same file. That is, the definition found at level 4 is in a more nested package, but is from a different file.

File: test/files/pos/t7232f/C.java [hunk 4]
```diff
@@ -0,0 +1,8 @@
+
```
Comment (som-snytt) [inline test/files/pos/t7232f/C.java:1]: Structurally same as run/t12195, where the error was not noticed until runtime.

File: test/files/pos/t7232e/Foo.java [hunk 5]
```diff
@@ -0,0 +1,10 @@
+package pack;
+
+import java.util.List;   // does shadow
+import java.awt.*;       // doesn't shadow, keep looking
+import java.util.function.Supplier;  // irrelevant, keep looking
```
Comment (som-snytt) [inline test/files/pos/t7232e/Foo.java:5]: The irrelevant import serves the same role as the other test. However, the `awt` wildcard also does not shadow in Java, so don't pick it during lookup.

This test was the only time it was ever useful to me to have `java.awt.List`, which for years messed with autocomplete.

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 6]
```diff
@@ -1919,7 +1934,7 @@ trait Contexts { self: Analyzer =>
     def sameDepth: Boolean = imp1.depth == imp2.depth
 
     private def imp2Exists = imp2Ctx.importOrNull != null
-    private def imp1Explicit = imp1 isExplicitImport name
+    def imp1Explicit = imp1 isExplicitImport name
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1937]: The usage at L1535 might be extraneous, but keeping this change to be conservative.

**Review by lrytz — APPROVED** [review]
Thank you for the explanations!
