### PR TITLE
fix mutable.HashSet.addAll: remove redundant call to super method

### LINKED ISSUE #11601: 2.13.0: mutable.HashSet.addAll processes parameter twice
`addAll` method of `mutable.HashSet` will process parameter twice if it's not a `mutable.HashSet` or `immutable.HashSet`. It potentially can cause duplicate elements in collection. 

Please refer following testing code.

    import java.util
    import scala.jdk.CollectionConverters._

    object HashSet {
      def main(args: Array[String]): Unit = {
        val jhs = new util.HashSet[Obj]()
        jhs.add(new Obj("A"))
        jhs.add(new Obj("B"))
        val shs = jhs.asScala.map(x => new Obj2(x.f))
        println("java set: " + jhs.size)
        println("scala set: " + shs.size)
      }
    }

    class Obj(val f:String) {
    }

    class Obj2(val f:String) {
    }

It will not cause a problem if proper `hashCode` and `equals` are present in `Obj2`.

### PR DESCRIPTION
**Pull request by miteshaghera**
Removed redundant call to super method.

Fixes scala/bug#11601

### CODE REVIEW

**Comment by dwijnand** [comment]
Hey, @miteshaghera.  Thanks for the PR!  Do you think you could add a unit test that validates this fix and ensures it doesn't regress, please?

**Comment by miteshaghera** [comment]
@dwijnand Give me some time I'll update unit test which validate this PR.

**Review by dwijnand — APPROVED** [review]
Thanks!

**Comment by SethTisue** [comment]
could you squash this into a single commit?

this looks otherwise ready to merge.

File: test/junit/scala/collection/mutable/HashSetTest.scala [hunk 1]
```diff
@@ -70,4 +70,18 @@ class HashSetTest {
...
+
+  import scala.jdk.CollectionConverters._
+
+  @Test
+  def addAll: Unit = {
+    val jhs: java.util.HashSet[Type1] = new java.util.HashSet[Type1]
+    jhs.add(new Type1("A"))
+    jhs.add(new Type1("B"))
+    val shs: scala.collection.mutable.Set[Type2] = jhs.asScala.map(x => new Type2(x.value))
+    assertTrue(jhs.size.equals(shs.size))
```
Comment (som-snytt) [inline test/junit/scala/collection/mutable/HashSetTest.scala]: assertEquals. Actually, I'm not sure what this test is testing, because there are a few moving parts. (It is not minimal.)

**Comment by som-snytt** [comment]
For a test, I'd suggest something direct:
```
package once

import collection.IterableOnce

class OnceOnly extends IterableOnce[Int] {
  override def knownSize = 1
  private var iterated: Boolean = false
  override def iterator = {
    assert(!iterated)
    iterated = true
    new Iterator[Int] {
      private var v = Option(42)
      override def hasNext = v.nonEmpty
      override def next() = { val res = v.get ; v = None ; res }
    }
  }
}

object Test extends App {
  val hs = collection.mutable.HashSet.empty[Int]
  hs.addAll(new OnceOnly)
}
```
Putting it in junit form is left as an exercise for the reader.

**Comment by som-snytt** [comment]
Looking at what I wrote, I'm not sure if knownSize should be zero after the iterator is exhausted?

Ideally, all the API taking an IterableOnce would be tested that it obeys the contract. Is it a contract if it's just a handshake between two good ole boys that they promise not to call it twice?

File: test/junit/scala/collection/mutable/HashSetTest.scala (hunk 1 above)
Comment (dwijnand) [reply test/junit/scala/collection/mutable/HashSetTest.scala]: It's a (slightly modified) copy of the minimised case in the issue.  Perhaps we can keep this as a unit test, but differentiate it by location and/or name?

Comment (som-snytt) [reply test/junit/scala/collection/mutable/HashSetTest.scala]: thanks, that explains what it has to do with the price of beans, as they say.

**Comment by miteshaghera** [comment]
> For a test, I'd suggest something direct:
> 
> ```
> package once
> 
> import collection.IterableOnce
> 
> class OnceOnly extends IterableOnce[Int] {
>   override def knownSize = 1
>   private var iterated: Boolean = false
>   override def iterator = {
>     assert(!iterated)
>     iterated = true
>     new Iterator[Int] {
>       private var v = Option(42)
>       override def hasNext = v.nonEmpty
>       override def next() = { val res = v.get ; v = None ; res }
>     }
>   }
> }
> 
> object Test extends App {
>   val hs = collection.mutable.HashSet.empty[Int]
>   hs.addAll(new OnceOnly)
> }
> ```
> 
> Putting it in junit form is left as an exercise for the reader.

Thanks, I'll add this is as another test as well. Can I use your snippet?

**Comment by som-snytt** [comment]
Yes, please use it in any way if it's helpful.

**Comment by miteshaghera** [comment]
> could you squash this into a single commit?
> 
> this looks otherwise ready to merge.

I squashed the commits.

**Review by lrytz — APPROVED** [review]
Thank you, @miteshaghera!
