### PR TITLE
Fix ArrayBuffer incorrectly reporting the upper bound in IndexOutOfBoundsException

### LINKED ISSUE #12176: ArrayBuffer incorrectly reports the upper bound in IndexOutOfBoundsException
## reproduction steps

using Scala 2.13 and above

```scala
scala> val buf = scala.collection.mutable.ArrayBuffer(1,2,3)
scala> buf(3)
java.lang.IndexOutOfBoundsException: 4 is out of bounds (min 0, max 2)
```

## problem

When requesting for an out of bounds index in an ArrayList, the error report shows an index one higher than what was requested.

The bug was introduced in https://github.com/scala/scala/commit/7e1ed8c01637711f81f868323533f0c963a50330
which made the exception messages more readable. The code is shown below:

```scala
 @inline private def checkWithinBounds(lo: Int, hi: Int) = {
    if (lo < 0) throw new IndexOutOfBoundsException(s"$lo is out of bounds (min 0, max ${size0-1})")
    if (hi > size0) throw new IndexOutOfBoundsException(s"$hi is out of bounds (min 0, max ${size0 - 1})")
  }

  def apply(n: Int): A = {
    checkWithinBounds(n, n + 1)
    array(n).asInstanceOf[A]
  }
```

When `apply` is called with an index `n`, the method calculates two bounds to be checked by `checkWithinBounds`. the parameter `hi` gets a value one higher that the requested value, `lo` is the value as-is. 

The bug is that when checking the upper bound, `hi` (which is the correct value + 1) is shown as the requested value. Using `lo` would give the correct result, but could lead to a regression bug later depending on how checkWithinBounds is called.

### PR DESCRIPTION
**Pull request by mshibuya**
This is the fix scala/bug#12176.
~The solution suggested there seems to work~ , so I've just applied it and added partest for this.

Thanks in advance for reviewing!

### CODE REVIEW

File: src/library/scala/collection/mutable/ArrayBuffer.scala [hunk 1]
```diff
@@ -95,7 +95,7 @@ class ArrayBuffer[A] private (initialElements: Array[AnyRef], initialSize: Int)
 
   @inline private def checkWithinBounds(lo: Int, hi: Int) = {
     if (lo < 0) throw new IndexOutOfBoundsException(s"$lo is out of bounds (min 0, max ${size0-1})")
-    if (hi > size0) throw new IndexOutOfBoundsException(s"$hi is out of bounds (min 0, max ${size0 - 1})")
+    if (hi > size0) throw new IndexOutOfBoundsException(s"${hi - 1} is out of bounds (min 0, max ${size0 - 1})")
```
Comment (mshibuya) [inline src/library/scala/collection/mutable/ArrayBuffer.scala:98]: The solution suggested in scala/bug#12176 uses `$lo` here, but after a bit consideration it is wrong because it breaks with a situation where performing operations targeted for a range of indexes like this:
https://github.com/scala/scala/pull/9249/files#diff-421aa7b6b8733d6090f2148be711352af11cc34b2e6978c84051d2ecf0561bd6R27

Use of `$lo` produces incorrect message of `2 is out of bounds (min 0, max 2)`.

**Comment by NthPortal** [comment]
the tests can probably just be junit tests rather than partests; you only really need to use partest if you need to check the compiler output/result

**Comment by som-snytt** [comment]
The current tests do not check the message.

https://github.com/scala/scala/blob/2.13.x/test/junit/scala/collection/mutable/ArrayBufferTest.scala#L33

Random example checking exception message:

https://github.com/scala/scala/blob/2.13.x/test/junit/scala/reflect/internal/NamesTest.scala#L57

**Comment by eed3si9n** [comment]
> the tests can probably just be junit tests rather than partests; you only really need to use partest if you need to check the compiler output/result

This PR was made during ScalaMatsuri Hackathon. I should've thought about trying JUnit first, but I've probably mislead him since I only talked about partest.

**Comment by som-snytt** [comment]
That is only natural, because we will miss partest during Scala 3. And to think how I hated partest at first! It's kind of like the "rom-com" of testing frameworks.

**Comment by mshibuya** [comment]
Thanks for reviewing, I've moved the test into junit so please take a look!

File: test/junit/scala/collection/mutable/ArrayBufferTest.scala [hunk 2]
```diff
@@ -362,4 +362,22 @@ class ArrayBufferTest {
...
+        case ex: IndexOutOfBoundsException => assertEquals(ex.getMessage, msg)
+      }
+
+    iiobe( newAB.insert(-1, 'x'), "-1 is out of bounds (min 0, max 2)" )
+    iiobe( newAB.insertAll(-2, Array('x', 'y', 'z')), "-2 is out of bounds (min 0, max 2)" )
+    iiobe( newAB.update(-3, 'u'), "-3 is out of bounds (min 0, max 2)" )
+    iiobe( newAB.update(-1, 'u'), "-1 is out of bounds (min 0, max 2)" )
+    iiobe( newAB.update(3, 'u'), "3 is out of bounds (min 0, max 2)" )
+    iiobe( newAB(3), "3 is out of bounds (min 0, max 2)" )
+    iiobe( newAB.remove(2, 2), "3 is out of bounds (min 0, max 2)" )
```
Comment (diesalbla) [inline test/junit/scala/collection/mutable/ArrayBufferTest.scala:382]:
```suggestion
    iiobe( newAB.remove(3), "3 is out of bounds (min 0, max 2)" )
    iiobe( newAB.remove(2, 2), "3 is out of bounds (min 0, max 2)" )
```
Removing one and removing a block of several are separate operations.
https://www.scala-lang.org/api/current/scala/collection/mutable/ArrayBuffer.html#remove(index:Int):A
https://www.scala-lang.org/api/current/scala/collection/mutable/ArrayBuffer.html#remove(index:Int,count:Int):Unit

**Review by diesalbla — APPROVED** [review]

File: test/junit/scala/collection/mutable/ArrayBufferTest.scala (hunk 2 above)
Comment (diesalbla) [reply test/junit/scala/collection/mutable/ArrayBufferTest.scala:381]: https://www.scala-lang.org/api/current/scala/collection/mutable/ArrayBuffer.html#remove(index:Int):A

**Review by dwijnand — APPROVED** [review]
Thanks!
