### PR TITLE
Fix attempt for flaky foldRightAllocations test

### LINKED ISSUE #727: Test scala.collection.immutable.ListMapTest.foldRightAllocations is flaky
example failure: https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/13195/consoleFull  I've seen it repeatedly lately

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes https://github.com/scala/scala-dev/issues/727

Fixes to reinstate it non-flaky are welcome, but meanwhile the cost of the test failure is too high to keep it IMO.

### CODE REVIEW

**Comment by SethTisue** [comment]
fyi @mkeskells — it's notoriously hard to test this kind of thing

**Review by SethTisue — APPROVED** [review]
`exactAllocates` is not unique to this test, so I don't know why this particular test would be especially prone to expose a flaw in it. but in any case, yes, deleting it, at least for now, is what we should do

**Comment by mkeskells** [comment]
It looks not to be an issue with the test /infra counting itself, just that the JIT is optimising away the allocation ( its allocating 0 rather than 72 bytes). we could change the call to `exactAllocates` to `onlyAllocates`
That does the same, but enforces an upper limit on the allocation
As such it doesn't enforce the ratcheting of the values down, but that can be done by other means (periodically, manually)

It would be good to know what is different in 2.13 to make this happen (to encorage this elsewhere) @retronym (as the JitWatch expert :-) ) is JitWatch the best way to find out by the JIT did the right thing here

File: test/junit/scala/collection/immutable/ListMapTest.scala [hunk 1]
```diff
@@ -55,50 +55,6 @@ class ListMapTest extends AllocationTest {
...
-        last = strings(index)
-        last
-      }
-    }
-    acc.dataFrom(m)
-    assertEquals("INIT", nonAllocating(m.foldRight(acc.reset)(acc)))
-
-    m = ListMap(1 -> 1)
-    acc.dataFrom(m)
-    assertEquals("(1,1)XX", exactAllocates(tuples(m.size))(m.foldRight(acc.reset)(acc)))
```
Comment (mkeskells) [inline test/junit/scala/collection/immutable/ListMapTest.scala:91]: can we just change the call from `exactAllocates` to `onlyAllocates`

**Review by mkeskells — CHANGES_REQUESTED** [review]
