### PR TITLE
Follow JDK 11+ spec for signature polymorphic methods

### LINKED ISSUE #12348: Can't invoke `VarHandle.setVolatile` from Scala
## reproduction steps

using Scala 2.13.3 on Java 11.0.10,

```scala
scala> val a = new Array[Object](1)
val a: Array[Object] = Array(null)

scala> val h = java.lang.invoke.MethodHandles.arrayElementVarHandle(a.getClass)
val h: java.lang.invoke.VarHandle = java.lang.invoke.VarHandleObjects$Array@47148f3f

scala> h.setVolatile(a, 0, "foo")
java.lang.NoSuchMethodError: VarHandle.setVolatile(Object[],int,String)Object
  at java.base/java.lang.invoke.MethodHandleNatives.newNoSuchMethodErrorOnVarHandle(MethodHandleNatives.java:576)
  at java.base/java.lang.invoke.MethodHandleNatives.varHandleOperationLinkerMethod(MethodHandleNatives.java:529)
  at java.base/java.lang.invoke.MethodHandleNatives.linkMethodImpl(MethodHandleNatives.java:462)
  at java.base/java.lang.invoke.MethodHandleNatives.linkMethod(MethodHandleNatives.java:450)
  ... 32 elided
```

## problem

I would expect this to succeed without the exception. 

If the code containing these steps is compiled with scalac , it can be seen that it emits the call to `setVolatile` with wrong return type `Object` instead of `void`:
```
invokevirtual java/lang/invoke/VarHandle.setVolatile:([Ljava/lang/Object;ILjava/lang/String;)Ljava/lang/Object;
pop
 ```

Since `VarHandle.setVolatile` is declared to return `void`, scalac is emitting wrong return type, it should emit `void`:
```
invokevirtual java/lang/invoke/VarHandle.setVolatile:([Ljava/lang/Object;ILjava/lang/String;)V
 ```

### PR DESCRIPTION
**Pull request by lrytz**
No test case because JDK 11...

Fixes https://github.com/scala/bug/issues/12348

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 1]
```diff
@@ -3582,15 +3582,18 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
...
           // a fictitious new cloned method symbol for each call site that takes on a signature
           // governed by a) the argument types and b) the expected type
           val args1 = typedArgs(args, forArgMode(fun, mode))
           val clone = fun.symbol.cloneSymbol.withoutAnnotations
           val cloneParams = args1.map(arg => clone.newValueParameter(freshTermName()).setInfo(arg.tpe.deconst))
-          val resultType = if (isFullyDefined(pt)) pt else ObjectTpe
+          val resultType =
+            if (fun.symbol.tpe.resultType.typeSymbol != ObjectClass) fun.symbol.tpe.resultType
+            else if (isFullyDefined(pt)) pt
+            else ObjectTpe
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala:3596]: Thanks for this, I'd just noticed a problem here yesterday!

Before:
```
scala> import java.lang.invoke._
import java.lang.invoke._

scala> class Data { var a: Int = 0; def aHandle = MethodHandles.lookup().findVarHandle(getClass, "a", classOf[Int])}
defined class Data

scala>

scala> val d = new Data
d: Data = Data@15c4b1a4

scala>  d.aHandle.set(d, 2)
java.lang.NoSuchMethodError: VarHandle.set(Data,int)Object
  at java.base/java.lang.invoke.MethodHandleNatives.newNoSuchMethodErrorOnVarHandle(MethodHandleNatives.java:589)
  at java.base/java.lang.invoke.MethodHandleNatives.varHandleOperationLinkerMethod(MethodHandleNatives.java:542)
  at java.base/java.lang.invoke.MethodHandleNatives.linkMethodImpl(MethodHandleNatives.java:475)
  at java.base/java.lang.invoke.MethodHandleNatives.linkMethod(MethodHandleNatives.java:463)
  ... 28 elided

scala>  d.aHandle.set(d, 2): Unit // workaround, fully define expected type as Unit

scala> d.a
res2: Int = 2
```

With your PR:


```
scala> d.aHandle.set(d, 2)

scala> d.a
val res9: Int = 2
```

**Review by retronym — APPROVED** [review]

**Comment by szegedi** [comment]
Thanks, @lrytz!
