### PR TITLE
REPL: improve handling of non-printable characters (to prevent messing up terminal)

### LINKED ISSUE #12276: REPL: broken highlighting
## reproduction steps

using Scala 2.13.4,

```scala
scala> val decoderOut = java.nio.CharBuffer.allocate(5)
val decoderOut: java.nio.CharBuffer = ?????

scala> val decoderOut = java.nio.CharBuffer.allocate(6)
val ?[1m?[34mdecoderOut?[0m: ?[1m?[32mjava.nio.CharBuffer?[0m = ??????
```

## problem

Highlighting is broken.

### PR DESCRIPTION
**Pull request by som-snytt**
So colors can come through unscathed.

Fixes scala/bug#12276

cf https://github.com/scala/scala/commit/aafcc104b6ebe2fa163fc7a9cbfb742bf5f26d08

REPL strips its wrapper identifiers from output, and also tries to suppress output that might mess up the terminal.

This commit simplifies the heuristic on "what to pass" to a regex for the alternatives: control sequences for color output, non-printable chars which are replaced by `?`, and the existing pattern for wrapper names.

### CODE REVIEW

File: src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala [hunk 1]
```diff
@@ -989,18 +989,19 @@ object ILoop {
...
 
+      override val colorOk = colorOutput
+
       // No truncated output, because the result changes on Windows because of line endings
-      override val maxPrintString = {
-        val p = sys.Prop[Int]("wtf")
-        p.set("0")
-        p
-      }
+      override val maxPrintString = sys.Prop[Int]("wtf").tap(_.set("0"))
```
Comment (dwijnand) [inline src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala]: Ah, yes, the "windows truncate format" system property...

File: src/repl/scala/tools/nsc/interpreter/Naming.scala [hunk 2]
```diff
@@ -12,52 +12,56 @@
...
-        case c => c
-      }
-    // Not lots - preserve whitespace and ESC
-    else
-      cleaned map (ch => if (ch.isWhitespace || ch == ESC) ch else if (ch < 32) '?' else ch)
-  }
+//For CSI, or "Control Sequence Introducer" commands, the ESC [ is followed by any number (including none) of "parameter bytes" in the range 0x30–0x3F (ASCII 0–9:;<=>?), then by any number of "intermediate bytes" in the range 0x20–0x2F (ASCII space and !"#$%&'()*+,-./), then finally by a single "final byte" in the range 0x40–0x7E (ASCII @A–Z[\]^_`a–z{|}~)
+  private final val esc = "\u001b"    // "\N{escape}"
+  private val csi = raw"$esc\[[0-9;]*([\x40-\x7E])"
+  private lazy val cleaner = raw"$csi|([^\p{Print}\p{Space}]+)|$linePattern".r
```
Comment (dwijnand) [inline src/repl/scala/tools/nsc/interpreter/Naming.scala:33]: What's the second pattern for?  1-n non-print/space characters?

File: src/repl/scala/tools/nsc/interpreter/Naming.scala [hunk 3]
```diff
@@ -12,52 +12,56 @@
...
+   *
+   *  Attempt to replace dangerous characters with '?', which might otherwise
+   *  put the terminal in a bad state. Allow SGR (select graphic rendition, "m")
+   *  control sequences, but restrict otherwise.
+   */
+  def unmangle(str: String): String = cleaner.replaceSomeIn(str, clean)
+
+  private def clean(m: Regex.Match): Option[String] =
+    if ("m" == m.group(1) ) None
+    else if (m.group(1) != null || m.group(2) != null) Some("?" * (m.end - m.start))
```
Comment (dwijnand) [inline src/repl/scala/tools/nsc/interpreter/Naming.scala:47]: How does this group 1 or group 2 thing work, with the cleaner/linePattern/lambda nested pattern?  I started to try to interpret and inline the various pieces of it, but it's tricky so I thought I would ask directly.

File: test/files/run/t12276.check [hunk 4]
```diff
@@ -0,0 +1,50 @@
+00000000  1b 5b 33 35 6d 0a 73 63  61 6c 61 3e 20 1b 5b 30  |.[35m.scala> .[0|
+00000010  6d 6a 61 76 61 2e 6e 69  6f 2e 43 68 61 72 42 75  |mjava.nio.CharBu|
+00000020  66 66 65 72 2e 61 6c 6c  6f 63 61 74 65 28 35 29  |ffer.allocate(5)|
+00000030  0a 76 61 6c 20 1b 5b 31  6d 1b 5b 33 34 6d 72 65  |.val .[1m.[34mre|
+00000040  73 30 1b 5b 30 6d 3a 20  1b 5b 31 6d 1b 5b 33 32  |s0.[0m: .[1m.[32|
+00000050  6d 6a 61 76 61 2e 6e 69  6f 2e 43 68 61 72 42 75  |mjava.nio.CharBu|
+00000060  66 66 65 72 1b 5b 30 6d  20 3d 20 3f 3f 3f 3f 3f  |ffer.[0m = ?????|
+00000070  0a 1b 5b 33 35 6d 0a 73  63 61 6c 61 3e 20 1b 5b  |..[35m.scala> .[|
+00000080  30 6d 6a 61 76 61 2e 6e  69 6f 2e 43 68 61 72 42  |0mjava.nio.CharB|
+00000090  75 66 66 65 72 2e 61 6c  6c 6f 63 61 74 65 28 36  |uffer.allocate(6|
```
Comment (dwijnand) [inline test/files/run/t12276.check]: The output looks familiar (and nice!) but I feel like I'd find it more useful if it were split by lines before being split by 16 bytes.  Did you do this like so for any reason other than familiarity/similarity?

**Review by dwijnand — COMMENTED** [review]
LGTM on paper, but it's not easy to follow the change.  Could you outline/describe the change some more, please?

File: src/repl/scala/tools/nsc/interpreter/Naming.scala (hunk 3 above)
Comment (som-snytt) [reply src/repl/scala/tools/nsc/interpreter/Naming.scala:47]: The leading groups are the m in color control sequence (or some other sequence we want to turn into ?) and also the non-printables.

File: src/repl/scala/tools/nsc/interpreter/Naming.scala (hunk 2 above)
Comment (som-snytt) [reply src/repl/scala/tools/nsc/interpreter/Naming.scala:33]: Yes, just trying for a reasonable test. The existing ancient heuristic is too brittle.

File: test/files/run/t12276.check (hunk 4 above)
Comment (som-snytt) [reply test/files/run/t12276.check]: On second thought, I almost appended the text, so you could just glance at the line output.

I did not because the test is just to witness that certain non-printables are present (and others are not).

But maybe outputting line at a time would be easier to examine.

**Comment by som-snytt** [comment]
The update takes Dale's suggestion to show test output per line, which is not as pretty, but is much easier to scan. The weird aspect is that the line endings are implicit and not shown in the hex dump. NBD.

Improved comments about the pattern.

Also push the alternative `ILoop.runForTranscript` into `ReplTest`, so the test class only supplies a flag, similar to existing `inSession` flag. These represent config external to settings. It would be nicer to supply a `ShellConfig` directly: `trait ILoop.TestConfig` would delegate, and the test class could override instead of passing arguments. (Edit: made that change.)

**Comment by SethTisue** [comment]
@som-snytt mind squashing into fewer commits? then let's :shipit:

**Comment by SethTisue** [comment]
@som-snytt ping. (if you're busy this week, let me know and I'll take care of it.)

**Comment by lrytz** [comment]
This seems a bit too eager...

2.13.4:

```scala
scala> "\uCAFE caffè"
val res0: String = 쫾 caffè
```

2.13.5

```scala
scala> "\uCAFE caffè"
val res0: String = ? caff?
```

**Comment by som-snytt** [comment]
US-ASCII FTW. "POSIX character classes (US-ASCII only)".

File: src/repl/scala/tools/nsc/interpreter/Naming.scala [hunk 5]
```diff
@@ -12,33 +12,40 @@
...
+  // then by any number of "intermediate bytes" in the range 0x20–0x2F (ASCII space and !"#$%&'()*+,-./),
+  // then finally by a single "final byte" in the range 0x40–0x7E (ASCII @A–Z[\]^_`a–z{|}~)
+  private final val esc = "\u001b"    // "\N{escape}"
+  private val csi = raw"$esc\[[0-9;]*([\x40-\x7E])"
+
+  // Matches one of 3 alternatives:
+  // group 1 is the CSI command letter, where 'm' is color rendition
+  // group 2 is a sequence of chars to be rendered as `?`: anything non-printable and not some space char
+  // additional groups are introduced by linePattern but not used
+  private lazy val cleaner = raw"$csi|([^\p{Print}\p{Space}]+)|$linePattern".r
```
Comment (som-snytt) [inline src/repl/scala/tools/nsc/interpreter/Naming.scala:33]: `([\p{Cntrl}&&[^\p{Space}]]+)` for group 2

Comment (lrytz) [reply src/repl/scala/tools/nsc/interpreter/Naming.scala:33]: 👍
