### PR TITLE
Fixing initialization cycle between object `Predef` and `Vector`

### LINKED ISSUE #13009: Cyclic object initialization between Predef and collection.immutable.Vector
## Description

The source code of the standard library includes object initialization cycles, including a cycle between `Predef` and `collection.immutable.Vector`, which could lead to deadlock when two threads initialize them simultaneously.

## Test

<details>

<summary> deadlock.scala </summary>

```
object Test extends App {
  val createPredef = new Runnable {
    def run = {
      val _ = Predef;
    }
  }
  val createVector = new Runnable {
    def run = {
      val _ = scala.collection.immutable.Vector;
    }
  }
  val t1 = new Thread(createPredef)
  val t2 = new Thread(createVector)
  t1.start()
  t2.start()
  t1.join()
  t2.join()
}

```

</details>

## Reproduction steps

Scala version: (2.13.15)

```
git clone https://github.com/scala/scala.git
cd scala
git checkout 2.13.x
sbt publishLocal
scala-cli -S 2.13.15-bin-SNAPSHOT deadlock.scala --main-class Test
```

## Problem

The test deadlocks due to cyclic initialization between `Predef` and `collection.immutable.Vector`. Specifically, `Predef` triggers initialization of `Vector` through

```
   |├── object Predef extends LowPriorityImplicits {	[ Predef.scala:106 ]
   |│   ^
   |├── scala.`package`                         // to force scala package object to be seen.	[ Predef.scala:151 ]
   |│   ^^^^^^^^^^^^^^^
   |├── package object scala {	[ package.scala:19 ]
   |│   ^
   |└── val Vector = scala.collection.immutable.Vector	[ package.scala:101 ]
   |        
```

and the constructor of Vector contains another call to `Predef.augmentString`, as shown in Vector.tasty
```
private[this] val defaultApplyPreferredMaxLength: scala.Int = try scala.Predef.augmentString(java.lang.System.getProperty("scala.collection.immutable.Vector.defaultApplyPreferredMaxLength", "250")).toInt catch {
      case _: java.lang.SecurityException =>
        250
    }
```

The warning is given by the global initialization checker that is under development to fix initialization warning in standard tasty library (https://github.com/scala/scala3/issues/18882), and this issue is linked to a PR with a fix to manually inline the call to `Predef.augmentString` (https://github.com/scala/scala/pull/10793). Our current conclusion is that such calls must be inlined to ensure soundness, which may happen in released build.

To reproduce the warning using the global initialization checker, apply the following patch to Dotty main branch:

```
diff --git a/compiler/src/dotty/tools/dotc/transform/init/Objects.scala b/compiler/src/dotty/tools/dotc/transform/init/Objects.scala
index bfa684eef8..3bb7b23095 100644
--- a/compiler/src/dotty/tools/dotc/transform/init/Objects.scala
+++ b/compiler/src/dotty/tools/dotc/transform/init/Objects.scala
@@ -864,8 +864,10 @@ class Objects(using Context @constructorOnly):
       Bottom

     case Bottom =>
-      if field.isStaticObject then ObjectRef(field.moduleClass.asClass)
-      else Bottom
+      if field.isStaticObject then
+        accessObject(field.moduleClass.asClass)
+      else
+        Bottom

     case ValueSet(values) =>
       values.map(ref => select(ref, field, receiver)).join
```

and in sbt:
```
sbt> set ThisBuild/Build.scala2Library := Build.Scala2LibraryTasty
sbt> scala3-compiler-bootstrapped/scalac -d out -Ysafe-init-global tests/init-global/pos/deadlock2.scala
```

The checker will report the following warning:
```
-- Warning: out/bootstrap/scala2-library-bootstrapped/scala-3.5.1-RC1-bin-SNAPSHOT-nonbootstrapped/src_managed/main/scala-library-src/scala/collection/immutable/Vector.scala:34:7
34 |object Vector extends StrictOptimizedSeqFactory[Vector] {
   |       ^
   |Cyclic initialization: object Vector -> object Predef -> package object scala -> object Vector. Calling trace:
   |├── object Predef extends LowPriorityImplicits {	[ Predef.scala:106 ]
   |│   ^
   |├── scala.`package`                         // to force scala package object to be seen.	[ Predef.scala:151 ]
   |│   ^^^^^^^^^^^^^^^
   |├── object Vector extends StrictOptimizedSeqFactory[Vector] {	[ Vector.scala:34 ]
   |│   ^
   |├── try System.getProperty("scala.collection.immutable.Vector.defaultApplyPreferredMaxLength",	[ Vector.scala:84 ]
   |│       ^
   |├── package object scala {	[ package.scala:19 ]
   |│   ^
   |└── val Vector = scala.collection.immutable.Vector	[ package.scala:101 ]
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 warning found
```

### PR DESCRIPTION
**Pull request by EnzeXing**
This PR focuses on a bug about deadlock during initialization caused by initialization cycles between object `Predef` and `collection.immutable.Vector`. This test shows two threads initializing `Predef` and `collection.immutable.Vector` separately, and the deadlock can be reproduced with the following steps:

1. `git clone https://github.com/scala/scala.git`
2. `git checkout 2.13.x`
3. `sbt publishLocal`
4. `scalac deadlock2.scala`
5. `java -cp .:[path-to-published-library] Test`

The bug is found by the global initialization checker (option `-Ysafe-init-global`) when analyzing Scala2LibraryTasty. It is caused by the call to `Predef.augmentString` not being inlined in the published library. The fix resolves the bug by manually inlining such call in object `Vector`.

Fixes scala/bug#13009

### CODE REVIEW

**Comment by som-snytt** [comment]
I happen to be fixing `-Wopt` warnings in scala/scala today. I didn't see that warning.

javap on released 2.13.14 shows `Vector$` class init using
```
  private static final int liftedTree1$1();
    descriptor: ()I
    flags: (0x101a) ACC_PRIVATE, ACC_STATIC, ACC_FINAL, ACC_SYNTHETIC
    Code:
      stack=2, locals=0, args_size=0
         0: ldc_w         #285                // String scala.collection.immutable.Vector.defaultApplyPreferredMaxLength         3: ldc_w         #287                // String 250
         6: invokestatic  #293                // Method java/lang/System.getProperty:(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
         9: invokestatic  #299                // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
        12: goto          19
        15: pop
        16: sipush        250
        19: ireturn
      Exception table:
         from    to  target type
             0    15    15   Class java/lang/SecurityException
```
which looks like inlined `string.toInt`.

I don't know anything about tasty support in scala 2 library.

If there is a cycle in the unoptimized code, what is it on the Predef side? Or, what can I run to witness it with `-Ysafe-init-global`?

**Comment by liufengyun** [comment]
> which looks like inlined string.toInt

To add to what @EnzeXing reported: we checked the `javap` output of released 2.13.14 JAR, it's aggressively inlined (both `Predef.augmentString` and `StringOps.toInt`), and the deadlock does not occur with the officially published library.

The deadlock only occurs with the un-optimized version published via `sbt publishLocal` and can be reliably/deterministically reproduced as reported by @EnzeXing and @olhotak.

> If there is a cycle in the unoptimized code, what is it on the Predef side? Or, what can I run to witness it with -Ysafe-init-global?

@EnzeXing has an open PR which can re-produce the problem: https://github.com/scala/scala3/pull/20424

If you apply the following patch to Dotty main branch:

```Scala
diff --git a/compiler/src/dotty/tools/dotc/transform/init/Objects.scala b/compiler/src/dotty/tools/dotc/transform/init/Objects.scala
index bfa684eef8..3bb7b23095 100644
--- a/compiler/src/dotty/tools/dotc/transform/init/Objects.scala
+++ b/compiler/src/dotty/tools/dotc/transform/init/Objects.scala
@@ -864,8 +864,10 @@ class Objects(using Context @constructorOnly):
       Bottom

     case Bottom =>
-      if field.isStaticObject then ObjectRef(field.moduleClass.asClass)
-      else Bottom
+      if field.isStaticObject then
+        accessObject(field.moduleClass.asClass)
+      else
+        Bottom

     case ValueSet(values) =>
       values.map(ref => select(ref, field, receiver)).join
```

And in SBT:

```
sbt> set ThisBuild/Build.scala2Library := Build.Scala2LibraryTasty
sbt> scala3-compiler-bootstrapped/scalac -d out -Ysafe-init-global examples/Vector.scala
```

where `examples/Vector.scala` is 

```Scala
import scala.collection.immutable.Vector

object A:
  val a = Vector.apply(4, 5)
```

The checker will report the following warning:

```Scala
-- Warning: out/bootstrap/scala2-library-bootstrapped/scala-3.5.1-RC1-bin-SNAPSHOT-nonbootstrapped/src_managed/main/scala-library-src/scala/collection/immutable/Vector.scala:34:7
34 |object Vector extends StrictOptimizedSeqFactory[Vector] {
   |       ^
   |Cyclic initialization: object Vector -> object Predef -> package object scala -> object Vector. Calling trace:
   |├── object Predef extends LowPriorityImplicits {	[ Predef.scala:106 ]
   |│   ^
   |├── scala.`package`                         // to force scala package object to be seen.	[ Predef.scala:151 ]
   |│   ^^^^^^^^^^^^^^^
   |├── object Vector extends StrictOptimizedSeqFactory[Vector] {	[ Vector.scala:34 ]
   |│   ^
   |├── try System.getProperty("scala.collection.immutable.Vector.defaultApplyPreferredMaxLength",	[ Vector.scala:84 ]
   |│       ^
   |├── package object scala {	[ package.scala:19 ]
   |│   ^
   |└── val Vector = scala.collection.immutable.Vector	[ package.scala:101 ]
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 warning found
```

Edit: The trace seems to be out of order, we need to improve that.

**Comment by som-snytt** [comment]
Thanks, nice to see further progress on `-Ysafe-init*`.

I never understood the package reference to make it "seen". It's not for init but just resolving the package at compile time? There are mechanisms for opening package objects.

It's suspicious to say "X can't use Predef if it is a privileged alias in scala package". It's just aliasing, it shouldn't break the language.

(I realize there were old-time problems with circular refs in Predef when building the standard library.)

**Comment by EnzeXing** [comment]
To add up, this is the decompiled code from Vector.tasty generated by the bootstrapped compiler, which the checker's analysis is based on:
```
private[this] val defaultApplyPreferredMaxLength: scala.Int = try scala.Predef.augmentString(java.lang.System.getProperty("scala.collection.immutable.Vector.defaultApplyPreferredMaxLength", "250")).toInt catch {
      case _: java.lang.SecurityException =>
        250
    }
```
This shows an implicit call to `Predef::augmentString` (the trace doesn't show that). In the unoptimized bytecode, we also see this call:
```
0: getstatic     #299                // Field scala/collection/StringOps$.MODULE$:Lscala/collection/StringOps$;
         3: getstatic     #304                // Field scala/Predef$.MODULE$:Lscala/Predef$;
         6: ldc_w         #306                // String scala.collection.immutable.Vector.defaultApplyPreferredMaxLength
         9: ldc_w         #308                // String 250
        12: invokestatic  #314                // Method java/lang/System.getProperty:(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        15: invokevirtual #318                // Method scala/Predef$.augmentString:(Ljava/lang/String;)Ljava/lang/String;
        18: invokevirtual #322                // Method scala/collection/StringOps$.toInt$extension:(Ljava/lang/String;)I
```

Our current conclusion is that such calls must be inlined to ensure soundness, just like the released build.

**Comment by liufengyun** [comment]
> It's suspicious to say "X can't use Predef if it is a privileged alias in scala package". It's just aliasing, it shouldn't break the language.

The checker `-Ysafe-init-global` does not forbid such usage. It checks whether there are initialization cycles. Usage is not a problem as long as it does not create initialization cycles.

File: src/library/scala/collection/immutable/Vector.scala [hunk 1]
```diff
@@ -81,8 +81,8 @@ object Vector extends StrictOptimizedSeqFactory[Vector] {
   }
 
   private val defaultApplyPreferredMaxLength: Int =
-    try System.getProperty("scala.collection.immutable.Vector.defaultApplyPreferredMaxLength",
-      "250").toInt
+    try new StringOps(System.getProperty("scala.collection.immutable.Vector.defaultApplyPreferredMaxLength",
```
Comment (lrytz) [inline src/library/scala/collection/immutable/Vector.scala:85]:
```suggestion
    // explicit StringOps to avoid initialization cycle with Predef (scala/bug#13009)
    try new StringOps(System.getProperty("scala.collection.immutable.Vector.defaultApplyPreferredMaxLength",
```

**Review by lrytz — COMMENTED** [review]
LGTM, nice to see the initialization checker at work! Let's just add a comment to the code.

**Comment by lrytz** [comment]
We want to have compact / clean git history in the repo (also applies to scala/scala3), could you squash the changes into a single commit? Sorry for the extra roundtrip.
