### PR TITLE
Get declared fields from superclasses as well

### LINKED ISSUE #5147: Enumerations Sometimes Fail To Correctly Populate The Name of Values
If you have a class that extends Enumeration that defines the actual Enumeration and then have a companion object extends from that class, the string values of the enumeration values is improperly handled.  For example:
```scala
class Foo extends Enumeration {
  val A = Value
}
object Foo extends Foo
```
...and then you try to print Foo.A, it'll print "<Invalid enum: no field for #0>" rather than "A".

### PR DESCRIPTION
**Pull request by Philippus**
fixes https://github.com/scala/bug/issues/5147

### CODE REVIEW

File: src/library/scala/Enumeration.scala [hunk 1]
```diff
@@ -188,7 +188,13 @@ abstract class Enumeration (initial: Int) extends Serializable {
...
 
   private def populateNameMap(): Unit = {
-    val fields: Array[JField] = getClass.getDeclaredFields
+    @tailrec def getFields(clazz: Class[_], acc: Array[JField]): Array[JField] = {
+      if (clazz.getSuperclass == null)
+        acc ++ clazz.getDeclaredFields
+      else
+        getFields(clazz.getSuperclass, acc ++ clazz.getDeclaredFields)
+    }
+    val fields = getFields(getClass, Array.empty)
```
Comment (som-snytt) [inline src/library/scala/Enumeration.scala]: It doesn't matter because Enumeration doesn't matter, but starting with an empty array is suboptimal. I see now `++` means allocate and copy. Usually there's a default size and then resize to actual when done. But here 99.99% is just one go. I'd suggest either `null` or `getFields(getClass, getclass.getDeclaredFields)`.

File: src/library/scala/Enumeration.scala [hunk 2]
```diff
@@ -188,7 +188,13 @@ abstract class Enumeration (initial: Int) extends Serializable {
   protected final def Value(i: Int, name: String): Value = new Val(i, name)
 
   private def populateNameMap(): Unit = {
-    val fields: Array[JField] = getClass.getDeclaredFields
+    @tailrec def getFields(clazz: Class[_], acc: Array[JField]): Array[JField] = {
+      if (clazz.getSuperclass == null)
```
Comment (som-snytt) [inline src/library/scala/Enumeration.scala]: Maybe just a style thing, but I'd suggest `if clazz == null` for termination.
```
getFs(clazz, acc) = if (clazz == null) acc else getFs(clazz.getSuperclass, if (clazz.getDFs.isEmpty) acc else acc ++ clazz.getDFs)
getFs(getClass.getsuperclass, getClass.getDeclaredFields)
```
which will normally allocate one array? Actually not sure yet if `++` is optimal for empty thing to append.

**Review by som-snytt — CHANGES_REQUESTED** [review]
Because it's easy and clear, let's not always allocate twice to append the current fields, which covers most cases.

That said, Who says Enumeration never gets any love?

File: src/library/scala/Enumeration.scala (hunk 2 above)
Comment (som-snytt) [reply src/library/scala/Enumeration.scala]: I guess `appendedAll` means always make a copy and not return this if appending an empty thing.

**Review by lrytz — APPROVED** [review]
👍 thanks!
