### PR TITLE
Fix Process.lazyLines mem leak #12185

### LINKED ISSUE #12185: Memory Leak in Process.lazyLines
## reproduction steps

using Scala 2.13.3 / 2.13.4-SNAPSHOT,

```scala
  scala.sys.process.Process("cat bigfile").lazyLines.foldLeft(0)((a, b) => a + b.size)
```

## Problem 1
It leaks memory until maximum heap size is reached.

## Problem 2
Instead of crashing with OOME it enters an infinite loop of GC cycles. It also prints no OOME messages.

If I start the JVM with `-XX:+CrashOnOutOfMemoryError` then it crashes with 

```
Aborting due to java.lang.OutOfMemoryError: GC overhead limit exceeded
```

## Expected behaviour:

For comparison the`lineStream` works fine, and I would expect the `lazyLines` to work similarly:
```scala
  scala.sys.process.Process("cat bigfile").lineStream.foldLeft(0)((a, b) => a + b.size)
```

## Root cause analysis

The anonymous function allocated as a lazy argument to `Spawn.apply` here https://github.com/scala/scala/blob/2.13.x/src/library/scala/sys/process/ProcessBuilderImpl.scala#L173 closes over the `lazilyListed` which holds a `lazyList`/`ll` reference to the `LazyList` containing output of the process, preventing the head of the list from being GCed once it has been processed by the `foldLeft`.

obraz

As for the reason for not failing with OOME. The https://github.com/scala/scala/blob/2.13.x/src/library/scala/sys/process/ProcessBuilderImpl.scala#L177 swallows the OOME and fails to rethrow it.

### PR DESCRIPTION
**Pull request by RafalSumislawski**
This PR prevents closing over `LazilyListed` leading to mem-leak in `Process.lazyLines`.

It also replaces a `NonFatal` catch with `Exception` catch changing the failure mode in case of out of memory from infinite-gc-loop-and-no-errors to some-threads-crash-logging-oome-to-stderr-but-the-jvm-stays-alive.

I have no idea how to write a regression test for it. I'm open for ideas.

Fixes scala/bug#12185.

### CODE REVIEW

**Comment by RafalSumislawski** [comment]
I just signed the CLA. I don't know how to poke the CI to recheck it.

File: src/library/scala/sys/process/ProcessBuilderImpl.scala [hunk 1]
```diff
@@ -170,11 +170,14 @@ private[process] trait ProcessBuilderImpl {
...
+      // extract done from lazilyListed so that the anonymous function below closes over just the done and not the whole lazilyListed (see https://github.com/scala/bug/issues/12185)
+      val done = lazilyListed.done
+
       Spawn("LazyLines") {
-        lazilyListed.done {
+        done {
           try process.exitValue()
           catch {
-            case NonFatal(_) => -2
+            case _: Exception => -2
```
Comment (julienrf) [inline src/library/scala/sys/process/ProcessBuilderImpl.scala]: I’m not sure about this change. `NonFatal` catches `StackoverflowError`, for instance, which is not anymore caught by your change.

Comment (som-snytt) [reply src/library/scala/sys/process/ProcessBuilderImpl.scala]: OOME is not nonfatal.
```
scala> try { throw new OutOfMemoryError } catch { case NonFatal(_) => println("whew") }
java.lang.OutOfMemoryError
  at liftedTree1$1(<console>:1)
  ... 32 elided
```

Comment (RafalSumislawski) [reply src/library/scala/sys/process/ProcessBuilderImpl.scala]: @julienrf are you sure about that StackoverflowError? I think that changed in some version of Scala and now it doesn't.
@som-snytt I know `OutOfMemoryError` is not `NonFatal`. I don't fully understand what is happening here, but what I observed was that with the NonFatal the JVM kept running GCs infinitely and not printing OOME. With the `_: Exception` I ended up getting the error printed with each run. The problem is I can't reproduce it now, except for the one JVM in the infinite GC state that I haven't restarted yet.

Caching `Error`s is a tricky business, and I should have been running my JVMs with `-XX:+CrashOnOutOfMemoryError` anyway. I would be ok with reverting the change to the `catch`, and proceeding just with the `val done = lazilyListed.done` part, which is IMO the important part of this PR. @julienrf @som-snytt would you like to proceed this way?

Comment (som-snytt) [reply src/library/scala/sys/process/ProcessBuilderImpl.scala]: yes, the other change is a good catch. It took me a few a minutes to get it. I'll try to come up with a test, which would be a mock Process that supplies some data and then (I guess) checking in the middle of the fold that the first "line" is not reachable (from whatever references we know about). We have other unit tests that chase references; it is a bit tricky.

On the OOM, I think there is a threshold you can set for how much time to spend in gc before giving up. Maybe you expected it to fail faster?

Comment (RafalSumislawski) [reply src/library/scala/sys/process/ProcessBuilderImpl.scala]: Ok. I've remove the commit modifying the catch.

It's possible I'm oscillating near the threshold for GC overhead OOME.

**Review by julienrf — APPROVED** [review]

**Comment by som-snytt** [comment]
A regression test is a challenge, aside from brute force.
