### PR TITLE
Prefer knownSize to isEmpty in IterableOnceOps

### LINKED ISSUE #12620: IterableOnceOps.sum creates multiple iterators
## Reproduction steps

Scala version: 2.13.6

```scala
    val someSeq = Seq(1).toSeq
    for (i <- 1 to 100_000) {
      println(someSeq.view.filter(i => Random.nextBoolean()).sum)
    }
```

The above is very likely to produce a stack trace like this:

```
java.lang.UnsupportedOperationException: empty.reduceLeft
  at scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:727)
  at scala.collection.IterableOnceOps.reduceLeft$(IterableOnce.scala:724)
  at scala.collection.AbstractIterable.reduceLeft(Iterable.scala:926)
  at scala.collection.IterableOnceOps.reduce(IterableOnce.scala:698)
  at scala.collection.IterableOnceOps.reduce$(IterableOnce.scala:698)
  at scala.collection.AbstractIterable.reduce(Iterable.scala:926)
  at scala.collection.IterableOnceOps.sum(IterableOnce.scala:889)
  at scala.collection.IterableOnceOps.sum$(IterableOnce.scala:889)
  at scala.collection.AbstractIterable.sum(Iterable.scala:926)
  <snip>
```

## Problem

`IterableOnceOps.sum` creates two different iterators for the source collection. Those iterators can be out of sync if the data source is lazy. This can cause exceptions to be thrown from `sum`.

In order to determine if the source collection is empty, `sum` creates an iterator and calls `hasNext`. If that iterator is non-empty, `sum` delegates to `reduce(num.plus)`, which creates a new, separate iterator to compute the sum. `reduce` fails on empty iterators, and for lazy collections involving filters, there is no guarantee that two separate iterators will agree on the state of the source collection.

I think this can be fixed by making `sum` create an iterator it can pass to `reduce`, instead of having the is-empty check create an iterator that isn't used by the reduce operation.

### PR DESCRIPTION
**Pull request by som-snytt**
Method implementations in `IterableOnceOps` avoid `isEmpty` and instead use `knownSize`.

Generally, if the size is not known, an iterator must be incurred (exactly) once for these operations.

The scaladoc for `isEmpty` now notes that the "default implementation creates and discards an iterator".

Fixes scala/bug#12620

### CODE REVIEW

**Comment by som-snytt** [comment]
Confirmed manually that the OP runs to completion with this change.
```
import scala.util.Random

object Test extends App {
  val someSeq = Seq(1).toSeq
  for (i <- 1 to 100_000) {
    println(someSeq.view.filter(i => Random.nextBoolean()).sum)
  }
}
```
Did not benchmark.

Maximizer/Minimizer tweaked as Maximized, with Mima exception.

Helpers foldl, foldr have tweaked signatures.

Scaladoc bodies that were indented an extra space relative to their first line are aligned.

File: src/library/scala/collection/IterableOnce.scala [hunk 1]
```diff
@@ -700,153 +701,171 @@ trait IterableOnceOps[+A, +CC[_], +C] extends Any { this: IterableOnce[A] =>
...
-      while (it.hasNext) {
-        val x = it.next()
-        if (first) {
-          acc = x
-          first = false
-        }
-        else acc = op(acc, x)
-      }
+    case _ if knownSize == 0 => throw new UnsupportedOperationException("empty.reduceLeft")
+    case _ => reduceLeftIterator[B](throw new UnsupportedOperationException("empty.reduceLeft"))(op)
```
Comment (joshlemer) [inline src/library/scala/collection/IterableOnce.scala:758]: Might be worth handling differently case where `knownSize == -1` and `knownSize != -1`. If the `knownSize` is "known", then we can leverage that knowledge to avoid calls to `hasNext` which might be expensive. 

```scala
val it = iterator
val ks = knownSize
if (ks == -1) {
  while (it.hasNext) {
    // ...
  }
else {
  var i = 0
  while(i < ks) {
    //...
    i += 1
  }
}
```

Comment (joshlemer) [reply src/library/scala/collection/IterableOnce.scala:758]: (It very well may not be worth it though)

Comment (som-snytt) [reply src/library/scala/collection/IterableOnce.scala:758]: That's an interesting idea. hasNext doesn't have to be much more expensive.

Comment (som-snytt) [reply src/library/scala/collection/IterableOnce.scala:758]: Actually, I recently coined "knownSize inconsistent with iterator" https://github.com/scala/scala/pull/10194

Iterators can fail to deliver, perhaps.

Comment (joshlemer) [reply src/library/scala/collection/IterableOnce.scala:758]: May want to override also for LinearSeq to use `head` and `tail` instead of `iterator`

Comment (som-snytt) [reply src/library/scala/collection/IterableOnce.scala:758]: This kind of talk must have inspired me to tweak `sameElements` for case of both known sizes are zero.

File: src/library/scala/collection/IterableOnce.scala [hunk 2]
```diff
@@ -911,200 +930,203 @@ trait IterableOnceOps[+A, +CC[_], +C] extends Any { this: IterableOnce[A] =>
...
+   *   $willNotTerminateInf
+   *
+   *   @param   num  an implicit parameter defining a set of numeric operations
+   *                 which includes the `+` operator to be used in forming the sum.
+   *   @tparam  B    the result type of the `+` operator.
+   *   @return       the sum of all elements of this $coll with respect to the `+` operator in `num`.
+   */
+  def sum[B >: A](implicit num: Numeric[B]): B =
+    knownSize match {
+      case -1 => reduceLeftIterator[B](num.zero)(num.plus)
```
Comment (lrytz) [inline src/library/scala/collection/IterableOnce.scala:943]: If a collection overrides `reduceLeft` but not `knownSize`, then `sum` will use an iterator.

I cannot imagine a case where this would apply and be an issue, but maybe someone else can?

**Review by lrytz — APPROVED** [review]
LGTM, thank you for working through it all!

File: src/library/scala/collection/IterableOnce.scala [hunk 3]
```diff
@@ -911,200 +930,203 @@ trait IterableOnceOps[+A, +CC[_], +C] extends Any { this: IterableOnce[A] =>
...
+   *  @return   the first element of this $coll with the largest value measured by function f
+   *            with respect to the ordering `cmp`.
+   */
+  def maxBy[B](f: A => B)(implicit ord: Ordering[B]): A =
+    knownSize match {
+      case  0 => throw new UnsupportedOperationException("empty.maxBy")
+      case  _ => foldLeft(new Maximized[A, B]("maxBy")(f)(ord.gt))((m, a) => m(m, a)).result
+    }
+
+  private class Maximized[X, B](descriptor: String)(f: X => B)(implicit cmp: (B, B) => Boolean) extends AbstractFunction2[Maximized[X, B], X, Maximized[X, B]] {
```
Comment (som-snytt) [inline src/library/scala/collection/IterableOnce.scala:1046]: spurious `implicit`

File: src/library/scala/collection/IterableOnce.scala (hunk 2 above)
Comment (som-snytt) [reply src/library/scala/collection/IterableOnce.scala:943]: If I wrote a collection as linked array buffers for efficiently concurrently growing the segments, then I might care to provide a fast reduce even though I don't update a size counter.

I wonder if the pristine fix is to provide a protected method with a name less explicit than `reduceLeftIterator`, or to say you must override `sum` for faster sum. 

But your point is about migration: an existing custom collection can change behavior. I don't know if people use `-Xmigration`. I don't know why `-Xmigration` does not default to `previous` or why `-Xlint` doesn't set it automatically.
