### PR TITLE
Align with Scala 3: Under `-Xsource:3`, allow importing `given`, for cross-building

### LINKED ISSUE #12999: Import given
## Reproduction steps

Scala version: 2.13.14

under -Xsource:3-cross, `import ExecutionContext.Implicits.given` is ignored rather than taken as `*`.

## Problem

If cross-compiling, I don't want `*`, even if scala 2 must approximate `given`.

Also, it would probably be easy to just make `given` actually work in imports.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12999

Under `-Xsource:3`, instead of ignoring `import x.given`, use it to import implicits only. Take `import x.{given, *}` as `import x.*`.

Although `import x.*` will import "legacy implicits" under Scala 3 migration rules, it's desirable to express just `import x.given` and have it work in Scala 2..

Import by type is not supported.

The selector is encoded as if it were `_ as given`.

### CODE REVIEW

**Comment by som-snytt** [comment]
spurious spec failure

**Comment by som-snytt** [comment]
add test for `import x.{y as _, given, *}` where y is implicit. Then you ~can't~ reduce to `import x.{y as _, *}`.

Edit: `y` is masked for both subsequent selectors; given is not immune to masked names. `import x.{given_T as _, given}`

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 1]
```diff
@@ -1914,6 +1914,8 @@ trait Contexts { self: Analyzer =>
       case bad              => throw new FatalError(s"symbol ${tree.symbol} has bad type: ${bad}")
     }
 
+    def isGivenImport: Boolean = tree.selectors.exists(_.isGiven)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala]: unused?

**Review by lrytz — COMMENTED** [review]
LGTM otherwsie!

**Comment by som-snytt** [comment]
My previous to-do comment was wrong. `given` is masked in the usual way. For `-Xsource:3`, `given` is subsumed by `*`, so it would be redundant to retain both selectors (since Scala 2 has implicits but no givens).

File: test/files/neg/import-future.scala [hunk 2]
```diff
@@ -25,3 +25,17 @@ object Test {
...
   }
 }
+
+trait T[A] {
+  def t: A
+}
+object T {
+  implicit def tInt: T[Int] = new T[Int] {
+    def t: Int = 42
+  }
```
Comment (som-snytt) [inline test/files/neg/import-future.scala:35]: putting `tInt` in implicit scope is not very useful for testing imports

**Review by lrytz — APPROVED** [review]
Thanks!

File: src/compiler/scala/tools/nsc/typechecker/Contexts.scala [hunk 3]
```diff
@@ -1950,6 +1950,11 @@ trait Contexts { self: Analyzer =>
           renamed = true
         else if (current.isWildcard && !renamed && !requireExplicit)
           result = maybeNonLocalMember(name)
+        else if (current.isGiven && !requireExplicit) {
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1953]: this should have the `!renamed` condition, same as the wildcard case.

`import x.{y as z, given}` means `z` should resolve to `y` not `implicit x.z` via the given selector.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1953]: But this works in Scala 3
```
scala> object Renamer {
     |   import TX.{f as tInt, given}
     |   def test = implicitly[T[Int]]
     | }
```
so a rename is not like a mask. That is, `x.y as z` means `y` is not available in subsequent wildcard selectors. But it does not mean `z` is not made available by wildcard selector!

But Scala 2 now: `diverging implicit expansion for type T[Int]`

**Comment by xuwei-k** [comment]
- https://github.com/scala/bug/issues/13038
