### PR TITLE
Avoid name check when loading repl products

### LINKED ISSUE #12705: Scala REPL (Shell) throws NoClassDefFoundError
## Reproduction steps

Scala version: 2.12.10

```scala
case class Person(name:String)

Thread.currentThread.getContextClassLoader
Thread.currentThread.getContextClassLoader.getParent
classOf[Person].getClassLoader
classOf[Person].getClassLoader.loadClass("Person")
```

## Problem

Running this code from Scala REPL (Shell) throws NoClassDefFoundError

``` scala
java.lang.NoClassDefFoundError: Person (wrong name: Person)
  at java.base/java.lang.ClassLoader.defineClass1(Native Method)
  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:74)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  ... 28 elided
```

### PR DESCRIPTION
**Pull request by som-snytt**
Supplying the name to `defineClass` means the name is checked, but if REPL found the class for a "translated" name, the name will never match. So REPL's class loader supplies `null` to mean DK. Some extra code could be added to preserve the translation and the name check, but for the REPL that might be unnecessary.

Fixes scala/bug#12705

### CODE REVIEW

**Comment by som-snytt** [comment]
The stack trace in the test is jdk-specific. I will just remove that line; it showed that the loadClass fails the second time, but of course it does.

File: src/repl/scala/tools/nsc/interpreter/IMain.scala [hunk 1]
```diff
@@ -347,15 +347,23 @@ class IMain(val settings: Settings, parentClassLoaderOverride: Option[ClassLoade
...
+   *
+   *  \$intp.classLoader classBytes "Bippy" or \$intp.classLoader getResource "Bippy.class" just work.
+   */
   private class TranslatingClassLoader(parent: ClassLoader) extends AbstractFileClassLoader(replOutput.dir, parent) {
     override protected def findAbstractFile(name: String): AbstractFile = super.findAbstractFile(name) match {
       case null if _initializeComplete => translateSimpleResource(name).map(super.findAbstractFile).orNull
       case file => file
     }
+    // if the name was mapped by findAbstractFile, supply null name to avoid name check in defineClass
+    override protected def findClass(name: String): Class[_] = {
```
Comment (lrytz) [inline src/repl/scala/tools/nsc/interpreter/IMain.scala:360]: do `super.findClass` first and use the new code below only as a fallback?

Comment (som-snytt) [reply src/repl/scala/tools/nsc/interpreter/IMain.scala:360]: I considered doing something fancy, but the class loader API is so complex already, plus `ScalaClassLoader` and `AbstractFileClassLoader`, and also throws, that I wasn't "up" for it.

I could imagine a boolean member called `verifyDefiningName` for `AbstractFileClassLoader` to consult.

Comment (lrytz) [reply src/repl/scala/tools/nsc/interpreter/IMain.scala:360]: A complex mix of complex ingredients, so I'm just generally worried about breaking stuff... I just saw now the `AbstractFileClassLoader.findClass` code that's overridden. In that light, LGTM.

**Review by lrytz — APPROVED** [review]
