### PR TITLE
Fix slicing of views of `IndexedSeq`s (including fixing 2.13.7-only `reverseIterator` regression)

### LINKED ISSUE #12479: Incorrect behavior with `take` on empty vector iterator
## reproduction steps

using Scala 2.13.7

```scala
object Test {
  def main(args: Array[String]): Unit = {
    val xx: Vector[Int] = Vector.empty[Int]
    val rev = xx.reverseIterator
    assert(rev.isEmpty)
    val afterTake = rev.take(1)
    assert(afterTake.isEmpty) // fails but shouldn't
  }
}
```

## problem

The second assert failes and shouldn't. Attempting to use `afterTake` will crash with an IndexOutOfBoundException.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12479

### CODE REVIEW

**Comment by som-snytt** [comment]
quickie, must take child to piano lesson.

**Comment by SethTisue** [comment]
review by @scala/collections ?

**Comment by som-snytt** [comment]
If collections drops by, so to speak, maybe they could indicate whether it was intentional that `drop` was made eager. That is, it calls `next` instead of using `sliceIterator` like `take` does.

**Comment by som-snytt** [comment]
I see Stefan reverted the change in laziness for `take`, so maybe I can just propose the same reversion for `drop`.

"An iterator for slicing that does not drop eagerly." at https://github.com/scala/scala/pull/4086

The paulp tweets there are dead links.

**Comment by NthPortal** [comment]
title should be "fixed slice of indexed seq view [...]"

**Comment by SethTisue** [comment]
A plain fix is of course mergeable, but it would be awesome if someone could plug the apparent hole in https://github.com/scala/scala-collection-laws too

File: src/library/scala/collection/Iterator.scala [hunk 1]
```diff
@@ -635,14 +635,7 @@ trait Iterator[+A] extends IterableOnce[A] with IterableOnceOps[A, Iterator, Ite
...
 
-  def drop(n: Int): Iterator[A] = {
-    var i = 0
-    while (i < n && hasNext) {
-      next()
-      i += 1
-    }
-    this
-  }
+  def drop(n: Int): Iterator[A] = sliceIterator(n, -1)
```
Comment (NthPortal) [inline src/library/scala/collection/Iterator.scala:638]: if this is lazy now, we should add a test for laziness

Comment (som-snytt) [reply src/library/scala/collection/Iterator.scala:638]: It was lazy before and the unit tests are still there. It wasn't testing anything for a while.

Comment (NthPortal) [inline src/library/scala/collection/Iterator.scala:638]: I have mixed feelings about this. on the one hand, it's a simplification. on the other hand, there has been some desire (can't recall where it was expressed originally) to change `drop` to return `this.type` once we can break forward bincompat. it's not clear to me that you could make the same guarantee of returning `this.type` for `sliceIterator`, and if not, we would no longer be able to make the improvement to `drop`'s signature in the future.

of course, there's also an argument that perhaps `drop` returning `this.type` precludes laziness, and laziness is a more important trait

Comment (som-snytt) [reply src/library/scala/collection/Iterator.scala:638]: I don't remember discussion 7 yrs about that; the previous fix was because the previous accommodation of laziness was not stack-safe. Also, I didn't see any discussion around reverting `take` to lazy. My only intuition is that `drop` and `take` should behave the same. Thanks for taking a look!

File: src/library/scala/collection/IndexedSeqView.scala [hunk 2]
```diff
@@ -96,23 +96,20 @@ object IndexedSeqView {
...
 
-    override def drop(n: Int): Iterator[A] = {
-      if (n > 0) {
-        pos -= n
-        remainder = Math.max(0, remainder - n)
+    override protected def sliceIterator(from: Int, until: Int): Iterator[A] = {
+      if (_hasNext) {
+        if (remainder <= from) remainder = 0
+        else if (from <= 0) {
+          if (until >= 0 && until < remainder) remainder = until
```
Comment (NthPortal) [inline src/library/scala/collection/IndexedSeqView.scala]: I'm not sure this `if` is correct. what about `sliceIterator(1, -2)` with `remainder = <arbitrary>`—shouldn't that set `remainder = 0`? or perhaps throw an `IllegalArgumentException`? I'm not sure what we specify

**Comment by som-snytt** [comment]
Unfortunately, I broke another test-at-a-distance. I'll also look into The Laws. I didn't feel great tweaking the innards without test coverage.

File: src/library/scala/collection/IndexedSeqView.scala [hunk 3]
```diff
@@ -96,23 +96,20 @@ object IndexedSeqView {
...
+        }
+        else {
+          pos = pos - from
+          if (until >= 0 && until < remainder) remainder = until - from
+          else remainder -= from
```
Comment (NthPortal) [inline src/library/scala/collection/IndexedSeqView.scala]: this doesn't seem right to me. it seems to me that, supposing `until >= from` (which is ideally always), it should always be the case that `remainder = math.max(0, remainder - (until - from))`. with this code, supposing `remainder = 5`, `sliceIterator(1, 2)` will yield `remainder = 4`, when we want `remainder = 1`.

it may even be possible to replace this `if`/`else` with just `remainder = math.max(0, remainder - (until - from))`

**Review by NthPortal — CHANGES_REQUESTED** [review]
while certainly simpler and a lot easier to follow, I'm not certain that the new implementation of `IndexedSeqViewReverseIterator#sliceIterator` is correct. also, I think we probably need more tests for `sliceIterator`, since I didn't see anything directly related to it fail

File: src/library/scala/collection/IndexedSeqView.scala (hunk 2 above)
Comment (som-snytt) [reply src/library/scala/collection/IndexedSeqView.scala]: The doc on sliceIterator is that until < 0 means no limit. That is drop semantics.

File: src/library/scala/collection/IndexedSeqView.scala (hunk 3 above)
Comment (som-snytt) [reply src/library/scala/collection/IndexedSeqView.scala]: I did learn the previous code, BTW. I'll comment the current edit to see if it is really that simple and also easy to maintain.

**Comment by johnynek** [comment]
some laws that might be useful to scalacheck:

```scala
forAll { (v: Vector[Int], n0: Int) =>
  val n = n0 & Int.MaxValue // make it non-neg
  assert(v.iterator.drop(n).toList == v.toList.drop(n))
}
forAll { (v: Vector[Int], n: Int) =>
  val n = n0 & Int.MaxValue // make it non-neg
  assert(v.iterator.take(n).toList == v.toList.take(n))
}
forAll { (v: Vector[Int], n: Int) =>
  val n = n0 & Int.MaxValue // make it non-neg
  assert(v.reverseIterator.drop(n).toList == v.toList.reverse.drop(n))
}

forAll { (v: Vector[Int], n: Int) =>
  val n = n0 & Int.MaxValue // make it non-neg
  assert(v.reverseIterator.take(n).toList == v.toList.reverse.take(n))
}

forAll { (v: Vector[Int], a0: Int, b0: Int) =>
  val a1 = a0 & Int.MaxValue // make it non-neg
  val b1 = b0 & Int.MaxValue // make it non-neg
  val (a, b) = if (a <= b) (a1, b1) else (b1, a1)
  assert(v.view.slice(a, b).toList == v.slice(a, b).toList)
}
```

**Comment by som-snytt** [comment]
@NthPortal there are optimized small Map iterators from last year (to avoid calling Iterator.apply). They override drop to just bump a count; that is probably where it came up to return this.type. But that only makes sense for iterating over these pre-computed values. These iterators do not override `take` because that is too hard? Or is every iterator a slice at heart?

The failing test was to check that empty and single Maps don't allocate on iterating after drop; the fix was to make `Iterator.empty` and `single` not allocate.

File: src/library/scala/collection/IndexedSeqView.scala (hunk 3 above)
Comment (som-snytt) [reply src/library/scala/collection/IndexedSeqView.scala]: `assert(v.reverseIterator.take(5).slice(1,2).size == 1)`. `until - from` is the new `remainder`.

File: src/library/scala/collection/IndexedSeqView.scala (hunk 2 above)
Comment (NthPortal) [reply src/library/scala/collection/IndexedSeqView.scala]: I'll reread and re-evaluate my comments based on that

**Comment by Ichoran** [comment]
@johnynek - The property tests in the Scala Collections Laws repository do *not* use scalacheck because they instead do code generation to also check type inference and such.  It would also be possible to write more property tests in scalacheck.

@som-snytt - Collections Laws are rather idiosyncratic.  Let me know if I should try to carve out time to tackle this part.  I don't remember the code much, but I guess "not much" is better than none, and I have the advantage that I still probably think like 2014-me.  (Or whenever that was.)

**Comment by som-snytt** [comment]
Thanks @Ichoran I saw you on the forum and it was like Casablanca when Rick tells Viktor Laszlo, "Now I know our side will win."

I did take a quick look, but I will need a second look. I also looked at the existing scalachecks. It occurred to me that if I know properties of iterators, and the api for producing iterators, then I'd like to check all those. My task is to convince Nth that I've covered a persuasive extent of the problem space.

My only other thought was that the big problem with the current discord ecosystem is that ichoran posts here and tpolecat posts there. This situation is deflationary, much like the impending retirement of Buster Posey from the local baseball team.

File: src/library/scala/collection/Iterator.scala [hunk 4]
```diff
@@ -972,6 +965,7 @@ object Iterator extends IterableFactory[Iterator] {
     def hasNext = false
     def next() = throw new NoSuchElementException("next on empty iterator")
     override def knownSize: Int = 0
+    override protected def sliceIterator(from: Int, until: Int) = this
```
Comment (NthPortal) [inline src/library/scala/collection/Iterator.scala:968]: I feel like there are definitely more methods we can override to return `this`, but that's not really relevant to this PR

**Comment by johnynek** [comment]
@SethTisue I'm sorry for making noise here (I don't know an appropriate channel) but can you remove me from the collections group? I don't have time to do these reviews at the moment.

**Comment by SethTisue** [comment]
@johnynek done! thanks for all the help you've provided these past months, it's much appreciated 🙇

**Review by NthPortal — APPROVED** [review]
I still think a few more tests for `sliceIterator` (directly or indirectly) would be a good idea; otherwise, LGTM

**Comment by som-snytt** [comment]
Is there an app where you can thank the guy on Maui? I wouldn't mind traveling to Maui and thanking in person, but probably I'd also need a place to stay.

On testing, an interesting idea is to require a first commit with a test that fails, before the fix commit that makes it pass. Maybe that applies to draft PRs only, so that final PRs are a single commit.

On "moar tests", I don't have an opinion.

File: src/library/scala/collection/Iterator.scala (hunk 1 above)
Comment (lrytz) [reply src/library/scala/collection/Iterator.scala:638]: @som-snytt sorry I don't understand what you're saying. There is a change here, `LazyList(1 to 10: _*).map(x => {println(x); x}).iterator.drop(4)` used to evaluate the first 4 elements, now it waits for `hasNext`.

But I assume this doesn't break any guarantees?

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
Thank you all 👍

File: src/library/scala/collection/Iterator.scala (hunk 1 above)
Comment (lrytz) [reply src/library/scala/collection/Iterator.scala:638]: For the record, `LazyList(1 to 10: _*).map(x => {println(x); x}).iterator.slice(4, 10)` also doesn't evaluate anything until `hasNext`. So the change here is either an improvement or neutral.

File: src/library/scala/collection/IndexedSeqView.scala [hunk 5]
```diff
@@ -96,23 +96,25 @@ object IndexedSeqView {
...
+            else remainder = until - from                                 // ...limited by until, less the skip
+          }
+          else remainder -= from                                          // ...otherwise just less the skip
+        }
       }
       this
     }
-
-    override def sliceIterator(from: Int, until: Int): Iterator[A] = {
-      val startCutoff = pos
```
Comment (lrytz) [inline src/library/scala/collection/IndexedSeqView.scala:108]: I guess the wrong assumption here was that `pos` would be in the seq's range, but for an empty one it starts off at `-1`. Also the old implementation of `drop` could make it negative.

So it's good that the new implementation doesn't rely on `pos` in any way.

Comment (som-snytt) [reply src/library/scala/collection/IndexedSeqView.scala:108]: Yes, I remember that part.

File: src/library/scala/collection/Iterator.scala (hunk 1 above)
Comment (som-snytt) [reply src/library/scala/collection/Iterator.scala:638]: I don't remember what I was thinking before the last busy two weeks. I did not follow up yet on improved lawfulness testing, which is required for membership in the collections collective, so I'll add this to things-to-test. I may have had one of these in mind: 
https://github.com/scala/scala/blob/2.13.x/test/junit/scala/collection/IteratorTest.scala#L33 
https://github.com/scala/scala/blob/2.13.x/test/junit/scala/collection/IteratorTest.scala#L208

Comment (som-snytt) [reply src/library/scala/collection/Iterator.scala:638]: I guess by "before", I meant "before 2.13", not "before this change". But I haven't reviewed the tests again yet.

**Comment by lrytz** [comment]
Another follow-up could be to remove the `drop` override in `IndexedSeqViewIterator` (the non-reverse variant).

https://github.com/scala/scala/blob/2131f5b7d96094df50726aa84291e6b0b173ae62/src/library/scala/collection/IndexedSeqView.scala#L66-L72

**Comment by som-snytt** [comment]
Roger that. Collections are more eager (so to speak) to override drop than take.
```
➜  grep "override def drop(" $(findsrc) | wc -l
26
➜  grep "override def take(" $(findsrc) | wc -l
17
```
In this context, I would have expected more symmetry, but I'll report again in the follow-up PR.
