### PR TITLE
Generalize condition when to skip override checking for Java members

### LINKED ISSUE #12407: Cannot inherit java interface that covariantly overrides a method with Array return type
## reproduction steps

using Scala 2.13.6,

Java:
```java
public interface A {
    A[] getArray();
}

public interface B extends A {
    @Override
    B[] getArray();
}
```

Scala:
```scala
trait Test extends B
```

## problem

When compiling the scala code the compiler gives:
```
incompatible type in overriding
def getArray(): Array[A] (defined in trait A)
  with def getArray(): Array[B] (defined in trait B);
 found   : (): Array[B]
 required: (): Array[A]
trait Test extends B
```

This makes it impossible to inherit `B`.

### PR DESCRIPTION
**Pull request by lrytz**
Fixes https://github.com/scala/bug/issues/12407

Follow-up for https://github.com/scala/scala/pull/9629

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/OverridingPairs.scala [hunk 1]
```diff
@@ -55,15 +55,15 @@ abstract class OverridingPairs extends SymbolPairs {
...
-            psym.isNonBottomSubClass(lowClass) || psym.isNonBottomSubClass(highClass)
+      // Two Java-defined methods can be skipped if javac will check the overrides. Skipping is actually necessary to
+      // avoid false errors, as Java doesn't have the Scala's linearization rules and subtyping rules
+      // (`Array[String] <:< Array[Object]`). However, when a Java interface is mixed into a Scala class, mixed-in
+      // methods need to go through override checking (neg/t12394, neg/t12380).
+      lowClass.isJavaDefined && highClass.isJavaDefined && { // skip if both are java-defined, and
+        lowClass.isNonBottomSubClass(highClass) || {         //  - low <:< high, which means they are overrides in Java and javac is doing the check; or
+          base.info.parents.tail.forall(p => {               //  - every mixin parent is unrelated to (not a subclass of) low and high, i.e.,
+            val psym = p.typeSymbol                          //    we're not mixing in high or low, both are coming from the superclass
+            !psym.isNonBottomSubClass(lowClass) && !psym.isNonBottomSubClass(highClass)
```
Comment (smarter) [inline src/compiler/scala/tools/nsc/transform/OverridingPairs.scala:66]: You should also be able to have an early check to skip if both are actual classes and not interfaces, since it means one has to extend the other.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/transform/OverridingPairs.scala:66]: Yeah, that's what was in there before, and I generalized it to `lowClass.isNonBottomSubClass(highClass)`, so I thought it's better to remove the old, now redundant condition; I don't think this would be a performance issue.

**Review by dwijnand — APPROVED** [review]

**Comment by lrytz** [comment]
@SethTisue do you prefer to run the community build on this before merging, or after? It's possible that something will pop up.

**Comment by SethTisue** [comment]
let's do the community build before merging. (but not today, the behemoths are busy)

(reason being that the longer these chains of adjustments and reversions become, the harder it is for archaeologists to follow the plot)

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2831/ queued

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2854/

**Comment by SethTisue** [comment]
Community build run is green. (The one failure is intermittent and unrelated.)
