### PR TITLE
Fix specialization of methods with dependent return types

### LINKED ISSUE #12210: Specialization + dependent method type --> inconsistent symbols
```
trait SpecFun[@specialized T] {
  type Res
  def res: Res
}

object Test {
  // the symbols for the `op` argument get out of synch
  def m[@specialized T](op: SpecFun[T]): op.Res = op.res
}
```

### PR DESCRIPTION
**Pull request by joroKr21**
Substitute both type and value parameter symbols in return type

Fixes scala/bug#12210

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala [hunk 1]
```diff
@@ -1903,32 +1903,35 @@ abstract class SpecializeTypes extends InfoTransform with TypingTransformers {
...
-        false) // don't make private fields public
-
-      val newBody = symSubstituter(body(source).duplicate)
-      tpt modifyType (_.substSym(oldtparams, newtparams))
-      copyDefDef(tree)(vparamss = List(newSyms map ValDef.apply), rhs = newBody)
+      // don't make private fields public
+      val substituter = new ImplementationAdapter(srcParams, newParams, source.enclClass, false)
+      val newRhs = substituter(body(source).duplicate)
+      tpt.modifyType(_.substSym(oldParams, newParams))
+      copyDefDef(tree)(vparamss = newVparams.map(ValDef.apply) :: Nil, rhs = newRhs)
```
Comment (dwijnand) [inline src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala:1934]: I can't spot it after squinting a bit at it... where's the fix?

Comment (joroKr21) [reply src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala:1934]: In `tpt.modifyType(_.substSym(oldParams, newParams))` where `xParams = xVparams ::: xTparams` - I've extracted the intermediate variables to make it more readable because it's confusing with 3 sets of parameters.

**Review by dwijnand — APPROVED** [review]
LGTM
