### PR TITLE
Fix NumericRange#isEmpty to work for very large ranges

### LINKED ISSUE #11911: Wide NumericRange#isEmpty throws an IllegalArgumentException
Current implementation of `isEmpty` uses `length` method which throws an Exception.

## reproduction steps

```scala
(0L to Int.MaxValue.toLong).isEmpty
```

## problem

```
java.lang.IllegalArgumentException: 0 to 2147483647 by 1: seqs cannot contain more than Int.MaxValue elements.
  scala.collection.immutable.Range.fail(Range.scala:175)
  scala.collection.immutable.Range.length(Range.scala:107)
  scala.collection.immutable.NumericRange$.count(NumericRange.scala:306)
  scala.collection.immutable.NumericRange.length$lzycompute(NumericRange.scala:75)
  scala.collection.immutable.NumericRange.length(NumericRange.scala:75)
  scala.collection.immutable.NumericRange.isEmpty(NumericRange.scala:76)
```

## expectation

```
false
```

### PR DESCRIPTION
**Pull request by cahilltr**
Fixes issue 11911 by not using length to check if the NumericRange is empty and using similar code from the Range#isEmpty

review by @Ichoran 
review by @szeiger 

Fixes scala/bug#11911

### CODE REVIEW

File: src/library/scala/collection/immutable/NumericRange.scala [hunk 1]
```diff
@@ -73,7 +73,11 @@ sealed class NumericRange[T](
...
   // See comment in Range for why this must be lazy.
   override lazy val length: Int = NumericRange.count(start, end, step, isInclusive)
-  override def isEmpty = length == 0
+  override def isEmpty = (
+    (start > end && num.gt(step, num.zero))
+      || (start < end && num.lt(step, num.zero))
+      || (start == end && !isInclusive)
+    )
   override def last: T =
     if (length == 0) Nil.head
```
Comment (som-snytt) [inline src/library/scala/collection/immutable/NumericRange.scala]: Should this now test `isEmpty`?

Comment (cahilltr) [reply src/library/scala/collection/immutable/NumericRange.scala]: @som-snytt , I've updated to replace all instances of `length ==0` with isEmpty. As far as I can tell, they're all appropriate replacements. But let me know if they're not.

File: src/library/scala/collection/immutable/NumericRange.scala [hunk 2]
```diff
@@ -73,9 +73,13 @@ sealed class NumericRange[T](
 
   // See comment in Range for why this must be lazy.
   override lazy val length: Int = NumericRange.count(start, end, step, isInclusive)
-  override def isEmpty = length == 0
+  override def isEmpty = (
+    (start > end && num.gt(step, num.zero))
+      || (start < end && num.lt(step, num.zero))
+      || (start == end && !isInclusive)
```
Comment (lrytz) [inline src/library/scala/collection/immutable/NumericRange.scala]: Should we use `num.gt` / `num.lt`/ `num.equiv` for `start` and `end`? In particular, `==` is maybe incorrect as it doesn't consult the ordering.

File: src/library/scala/collection/immutable/NumericRange.scala [hunk 3]
```diff
@@ -73,9 +73,13 @@ sealed class NumericRange[T](
 
   // See comment in Range for why this must be lazy.
   override lazy val length: Int = NumericRange.count(start, end, step, isInclusive)
-  override def isEmpty = length == 0
+  override def isEmpty = (
```
Comment (lrytz) [inline src/library/scala/collection/immutable/NumericRange.scala]: I think we can make `isEmpty` a `val` here, like it's done in `Range`.

**Review by lrytz — COMMENTED** [review]
Thanks for the contribution, @cahilltr!

File: src/library/scala/collection/immutable/NumericRange.scala (hunk 2 above)
Comment (cahilltr) [reply src/library/scala/collection/immutable/NumericRange.scala]: Update to use `num.gt`/`num.lt`/`num.equiv`.  Not sure why I used it for zero comparisons, but not `start`/`end`

**Review by lrytz — APPROVED** [review]
Thanks!
