### PR TITLE
Ensure package objects are opened after namer in interactive

### LINKED ISSUE #12663: Error tpe obtained for type alias defined in package object
Issue originally raised in Metals -  https://github.com/scalameta/metals/issues/4495

## Reproduction steps

Scala version: 2.13.8, 2.13.9, probably earlier ones too

Here's [repo](https://github.com/kpodsiad/package-type) with reproduction.

a/package.scala
```scala
package object a {
  type FancyInt = Int
}
```
a/Main.scala
```scala
package a
object Main extends App {
  def foo(n: FancyInt, k: Int): Unit = {
    n
    k
  }
}
```

## Problem

There are no completions for type alias
Screenshot 2022-10-07 at 07 28 13
Screenshot 2022-10-07 at 07 30 32

I initially thought that this is the problem with Metals but @tgodzik created a testcase with reproduction https://github.com/scalameta/metals/compare/main...tgodzik:metals:add-test?expand=1 which shows that this is the compiler issue.

This is what Metals gets from compiler:
```scala
CompletionProvider.scala:451 typeMembers: List(
  ScopeMember(
    sym = value n,
    tpe = <error>,
    accessible = true,
    viaImport = <empty>,
    aliasInfo = None
  ),
  ScopeMember(
    sym = value k,
    tpe = TypeRef(pre = ThisType(sym = package scala), sym = class Int, args = List()),
    accessible = true,
    viaImport = <empty>,
    aliasInfo = None
  ),
...
```
note `tpe = <error>` for `n` whereas `k` has correct tpe.

### PR DESCRIPTION
**Pull request by tgodzik**
Package objects need to be opened during the packageobjects
phase. This was not happening in presentation compilation
because the phase check looks at `globalPhase`, but in presentation
compilation (completion) the code is processed through `compileLate`
which only advances the SymbolTable phase.

Fixes https://github.com/scala/bug/issues/12663

### CODE REVIEW

**Comment by tgodzik** [comment]
I am not 100% about the fix, but I got kind of lost in what is going on there.

We seem to have two `deferredOpen` sets at the same time and because the package name is the same as a package name of a classfile dependency, there seem to be some weirdness going on.

Maybe it's connected to the lazy analyser in interactive.Global that overrides the other lazy analyser? I am not sure about how that could be involved.

**Comment by tgodzik** [comment]
Looks like this should have been a part of https://github.com/scala/scala/pull/9661 since it makes sense in terms of:
```
This PR takes it a step further and defers forcing the info of all package.class until the packageObjects phase. 
```

File: src/compiler/scala/tools/nsc/typechecker/Analyzer.scala [hunk 1]
```diff
@@ -80,7 +80,7 @@ trait Analyzer extends AnyRef
 
       def apply(unit: CompilationUnit): Unit = {
         openPackageObjectsTraverser(unit.body)
-        deferredOpen.foreach(openPackageModule(_))
+        deferredOpen.foreach(openPackageModule(_, force = true))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Analyzer.scala]: What's confusing: this change is in the `packageobjects` phase, which is after namer.

`openPackageModule` checks `isPast(currentRun.namerPhase)`, so it should not delay opening.

but `isPast` compares with `globalPhase`, and it turns out that in this case we get here through `compileLate`, which only sets `phase` but not `globalPhase`.

```
	at scala.tools.nsc.typechecker.Analyzer$packageObjects$$anon$2.apply(Analyzer.scala:84)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:483)
	at scala.tools.nsc.Global$Run.$anonfun$compileLate$3(Global.scala:1703)
...
	at scala.tools.nsc.Global$Run.compileLate(Global.scala:1702)
	at scala.tools.nsc.interactive.Global.parseAndEnter(Global.scala:669)
```

so yeah, i think this looks right. it should not ever make a difference in batch compilation.

note that there is already some logic in `interactive.Global.openPackageModule` to set `force = true` in more cases, but that doesn't fire here either (`unit.isParsed` is false)

**Review by lrytz — CHANGES_REQUESTED** [review]
running `sbt:scala2> partest test/files/presentation/package-object-issues` locally i get a difference:


```
!! 1 - presentation/package-object-issues        [output differs]
% diff /Users/luc/code/scala/scala13/test/files/presentation/package-object-issues.check /Users/luc/code/scala/scala13/test/files/presentation/package-object-issues-presentation.log
@@ -3,9 +3,8 @@ reload: Main.scala
 askTypeCompletion at Main.scala(7,6)
 ================================================================================
 [response] askTypeCompletion at (7,6)
-retrieved 46 members
-[inaccessible] private[package lang] def getStackTraceDepth(): Int
-[inaccessible] private[package lang] def getStackTraceElement(x$1: Int): StackTraceElement
+retrieved 45 members
+[inaccessible] final private[package lang] def setCause(x$1: Throwable): Unit
 [inaccessible] protected[package lang] def clone(): Object
 [inaccessible] protected[package lang] def finalize(): Unit
 def +(other: String): String
```

can you explain this? maybe it depends on the java version? i'm on `21.0.1+12-LTS`.

File: src/compiler/scala/tools/nsc/typechecker/Analyzer.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Analyzer.scala]: ha, a brief line comment would be nice. `// globalPhase may not be past namer when compileLate`. I looked briefly last night and knew I was missing something.

**Comment by tgodzik** [comment]
> can you explain this? maybe it depends on the java version? i'm on 21.0.1+12-LTS.

Yes, I had the same on JDK 21. I am not 100% sure why it's different, but I don't think it has anything to do with the fixed bug. We would probably get the same if a normal import.

File: src/compiler/scala/tools/nsc/typechecker/Analyzer.scala (hunk 1 above)
Comment (tgodzik) [reply src/compiler/scala/tools/nsc/typechecker/Analyzer.scala]: Added! Let me know if the comment is enough

**Comment by tgodzik** [comment]
I added a similar case without the scala.concurrent package and the result is the same.

**Comment by som-snytt** [comment]
I found my old branch, but I don't remember how the tests work. I'll report on it below.

I got this test to work by changing the pres global to always delegate:
```
  override def openPackageModule(pkgClass: Symbol, force: Boolean): Unit = {
    val isPastNamer = force || currentTyperRun == null || (currentTyperRun.currentUnit match {
      case unit: RichCompilationUnit => unit.isParsed
      case _                         => true
    })
    super.openPackageModule(pkgClass, force = isPastNamer)
```
and `nsc.Global` to add a phase check per lrytz:
```
  override def openPackageModule(pkgClass: Symbol, force: Boolean): Unit = {
    val forceNow = force || isPast(currentRun.namerPhase) ||
      isGlobalInitialized && isAtPhaseAfter(currentRun.namerPhase)
    if (forceNow) super.openPackageModule(pkgClass, force = true)
    else analyzer.packageObjects.deferredOpen.addOne(pkgClass)
  }
```

My printlns indicate that pres Global defers the package, then package objects (PO) dequeues them and pres Global's `isPastNamer` check makes it dump it back to deferred. I don't know anything at this point, however. I don't know if there is a motivation to move the force flag into global. What if there is a good reason for global to move a package back onto the queue?

```
[] parsing: Main.scala
[] OPEN pkgmod package concurrent force? false isPastNamer? false
DEFERRED OPEN package concurrent
PO package concurrent
[] OPEN pkgmod package concurrent force? false isPastNamer? false
DEFERRED OPEN package concurrent
[] responded, delay = 8ms
```
in the working case, nsc Global correctly decides to force based on `phase`.
```
[] parsing: Main.scala
[] OPEN pkgmod package concurrent force? false isPastNamer? false
GLB open package concurrent frc false now false
PO package concurrent
[] OPEN pkgmod package concurrent force? false isPastNamer? false
GLB open package concurrent frc false now true
[] responded, delay = 14ms
```

My test had the package object source in the test dir, not in src. But it works trivially if it is in the src dir. So I don't know yet how the test is structured, or I've long forgotten. 
```
test/files/presentation/t12663:
src  Test.scala

test/files/presentation/t12663/src:
Snippet.scala  Source_1.scala

➜  scala git:(issue/12663-pc-pkgobj-alias) ✗ cat test/files/presentation/t12663/src/*la
package p {
  object Main extends App {
    def i: I = 42
    def f = i./*!*/
  }
}

package object p {
  type I = Int
}
```

**Comment by lrytz** [comment]
> Yes, I had the same on JDK 21

The problem is that this will fail CI after merge. PR validation is on JDK 8 only, but after merging we test on many JDKs.

**Comment by lrytz** [comment]
@som-snytt I agree the change to `interactive.Global` (always delegate to nsc.Global.openPackageModule`) looks right. It doesn't make sense to defer once we're after namer phase.

> val forceNow = force || isPast(currentRun.namerPhase) ||
>       isGlobalInitialized && isAtPhaseAfter(currentRun.namerPhase)

yeah, probably that is the more principled fix. a bit unfortunate we have manually check global initialization. but not unexpected as we're in this difficult area of forcing things not too early, but also not too late...


I pushed those changes.

**Review by lrytz — APPROVED** [review]
LGTM, thanks!

Squashed.
