### PR TITLE
IndexedSeqOps overrides reduce/fold

### LINKED ISSUE #12614: For ArrayBuffer#min and max, Scala 2.13 is slower than 2.12
## Reproduction steps

Scala version: 2.13.8

The test program is as follows

```scala
private def min(numIters: Int, bufferSize: Int, loops: Int): Unit = {
    val benchmark = new Benchmark("Array Buffer", loops, output = output)
    val buffer = new mutable.ArrayBuffer[Int]()
    (0 until bufferSize).foreach(i => buffer += i)
    benchmark.addCase(s"buffer min with $bufferSize items", numIters) { _ =>
      (0 until loops).foreach(_ => buffer.min)
    }
    benchmark.addCase(s"buffer max with $bufferSize items", numIters) { _ =>
      (0 until loops).foreach(_ => buffer.max)
    }
    benchmark.run()
  }

  override def runBenchmarkSuite(mainArgs: Array[String]): Unit = {
    val numIters = 3
    val loops = 20000
    runBenchmark("ArrayBuffer min and max") {
      Seq(1000, 10000, 100000).foreach { bufferSize =>
        min(numIters, bufferSize, loops)
      }
    }
  }
```

The `Benchmark` of spark is used to record time, which can also be changed to manual timing.

In above cases, I test  2 operations: `ArrayBuffer.min`, `ArrayBuffer.max`,  with different buffer size: 1000, 10000, 100000.

**Scala 2.12.16 result:**

```
OpenJDK 64-Bit Server VM 1.8.0_332-b09 on Linux 5.13.0-1031-azure
Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Array Buffer:                             Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
buffer min with 1000 items                          121            121           0          0.2        6043.9       1.0X
buffer max with 1000 items                          134            134           0          0.1        6705.5       0.9X

OpenJDK 64-Bit Server VM 1.8.0_332-b09 on Linux 5.13.0-1031-azure
Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Array Buffer:                             Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
buffer min with 10000 items                        1272           1272           0          0.0       63601.9       1.0X
buffer max with 10000 items                        1339           1340           0          0.0       66972.2       0.9X

OpenJDK 64-Bit Server VM 1.8.0_332-b09 on Linux 5.13.0-1031-azure
Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Array Buffer:                             Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
buffer min with 100000 items                      12785          12788           3          0.0      639232.4       1.0X
buffer max with 100000 items                      13433          13434           1          0.0      671654.2       1.0X
```

**Scala 2.13.8 result:**

```
OpenJDK 64-Bit Server VM 1.8.0_332-b09 on Linux 5.13.0-1031-azure
Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Array Buffer:                             Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
buffer min with 1000 items                          273            273           0          0.1       13646.5       1.0X
buffer max with 1000 items                          162            162           0          0.1        8076.9       1.7X

OpenJDK 64-Bit Server VM 1.8.0_332-b09 on Linux 5.13.0-1031-azure
Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Array Buffer:                             Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
buffer min with 10000 items                        1676           1676           0          0.0       83782.1       1.0X
buffer max with 10000 items                        1610           1610           0          0.0       80485.5       1.0X

OpenJDK 64-Bit Server VM 1.8.0_332-b09 on Linux 5.13.0-1031-azure
Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Array Buffer:                             Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
buffer min with 100000 items                      16849          16856          10          0.0      842469.3       1.0X
buffer max with 100000 items                      15513          15515           4          0.0      775641.0       1.1X
```

## Problem

From the test results, Scala 2.13.8 is slower than Scala 2.12.16 for `ArrayBuffer.min` and `ArrayBuffer.max`. Should they have the same performance? Or should I use other data structures in Scala 2.13?

### PR DESCRIPTION
**Pull request by som-snytt**
Also `ArrayBuffer` which would also benefit from private access to its array and size.
```
// needs to be `private[collection]` or `protected[collection]` for parallel-collections
```
Did ~not~ experiment with private field/protected accessors.

Fixes scala/bug#12614

### CODE REVIEW

**Comment by som-snytt** [comment]
The downside of tailrec method is args stored each iteration even if unchanged.

**Comment by sjrd** [comment]
Are they? In the Scala 3 tailrec no-op assignments like that are elided.

**Comment by som-snytt** [comment]
Thanks, I'll check out the scala 3 transform, as I meant to do already for a recent change.

I was comparing the tailrec in 4 params to an inner tailrec looper that takes the 2 dynamic params, and the only change was the order of the params. I hoped it would take the hint that the params from the outer method were unchanged. But I didn't check with 2.13 optimized.

It's not that I'm too lazy to write a while loop: it's that after Scala 3, I can't go back to Scala 2 syntax.

```
➜  ~ sdk use java 11.0.12-open

Using java version 11.0.12-open in this shell.
➜  ~ sdk use scala 2.12.16

Using scala version 2.12.16 in this shell.
➜  ~ scala -nobootcp
Welcome to Scala 2.12.16 (OpenJDK 64-Bit Server VM, Java 11.0.12).
Type in expressions for evaluation. Or try :help.

scala> :javap -private -verbose scala.collection.IndexedSeqOptimized#foldl
  private <B extends java.lang.Object> B foldl(int, int, B, scala.Function2<B, A, B>);
    descriptor: (IILjava/lang/Object;Lscala/Function2;)Ljava/lang/Object;
    flags: (0x0002) ACC_PRIVATE
    Code:
      stack=6, locals=5, args_size=5
         0: iload_1
         1: iload_2
         2: if_icmpne     7
         5: aload_3
         6: areturn
         7: iload_1
         8: iconst_1
         9: iadd
        10: iload_2
        11: aload         4
        13: aload_3
        14: aload_0
        15: iload_1
        16: invokeinterface #61,  2           // InterfaceMethod apply:(I)Ljava/lang/Object;
        21: invokeinterface #148,  3          // InterfaceMethod scala/Function2.apply:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        26: aload         4
        28: astore        4
        30: astore_3
        31: istore_2
        32: istore_1
        33: goto          0
      StackMapTable: number_of_entries = 2
        frame_type = 0 /* same */
        frame_type = 6 /* same */
      LineNumberTable:
        line 59: 0
        line 60: 7
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      36     0  this   Lscala/collection/IndexedSeqOptimized;
            0      36     1 start   I
            0      36     2   end   I
            0      36     3     z   Ljava/lang/Object;
            0      36     4    op   Lscala/Function2;
    Signature: #140                         // <B:Ljava/lang/Object;>(IITB;Lscala/Function2<TB;TA;TB;>;)TB;
    MethodParameters:
      Name                           Flags
      start                          final
      end                            final
      z                              final
      op                             final
```

**Comment by som-snytt** [comment]
Travis says MiMA says it's not compatible:
```
[error] scala-library: Failed binary compatibility check against org.scala-lang:scala-library:2.13.8! Found 5 potential problems (filtered 25)

[error]  * abstract synthetic method scala$collection$IndexedSeqOps$$super$reduceLeft(scala.Function2)java.lang.Object in interface scala.collection.IndexedSeqOps is present only in current version

[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.collection.IndexedSeqOps.scala$collection$IndexedSeqOps$$super$reduceLeft")

[error]  * abstract synthetic method scala$collection$IndexedSeqOps$$super$reduceRight(scala.Function2)java.lang.Object in interface scala.collection.IndexedSeqOps is present only in current version

[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.collection.IndexedSeqOps.scala$collection$IndexedSeqOps$$super$reduceRight")

[error]  * in other version, classes mixing scala.collection.IndexedSeqOps need be recompiled to wire to the new static mixin forwarder method all super calls to method foldLeft(java.lang.Object,scala.Function2)java.lang.Object

[error]    filter with: ProblemFilters.exclude[NewMixinForwarderProblem]("scala.collection.IndexedSeqOps.foldLeft")

[error]  * in other version, classes mixing scala.collection.IndexedSeqOps need be recompiled to wire to the new static mixin forwarder method all super calls to method reduceLeft(scala.Function2)java.lang.Object

[error]    filter with: ProblemFilters.exclude[NewMixinForwarderProblem]("scala.collection.IndexedSeqOps.reduceLeft")

[error]  * in other version, classes mixing scala.collection.IndexedSeqOps need be recompiled to wire to the new static mixin forwarder method all super calls to method reduceRight(scala.Function2)java.lang.Object

[error]    filter with: ProblemFilters.exclude[NewMixinForwarderProblem]("scala.collection.IndexedSeqOps.reduceRight")
```
That makes sense on the face of it, but installing the change in all desired concrete classes is not appealing. Maybe there are not many: `ArraySec` and `Vector`?

**Comment by som-snytt** [comment]
FWIW, 2.13.8 vs override in IndexedSeqOps vs downcast in IterableOnce.
```
[info] ArraySeqBenchmark.min$minusmax$u0020is$u0020reduction   10000  avgt   20  63600.840 ± 547.558  ns/op
[info] ArraySeqBenchmark.min$minusmax$u0020is$u0020reduction   10000  avgt   20  52197.417 ± 250.352  ns/op
[info] ArraySeqBenchmark.min$minusmax$u0020is$u0020reduction   10000  avgt   20  58188.948 ± 1592.185  ns/op
```
2,13.8, override in ArrayBuffer, indirect array, field access array
```
[info] ArrayBufferBenchmark.min$minusmax$u0020is$u0020reduction   10000  avgt   30  69772.641 ± 136.585  ns/op
[info] ArrayBufferBenchmark.min$minusmax$u0020is$u0020reduction   10000  avgt   30  39887.655 ± 176.183  ns/op
[info] ArrayBufferBenchmark.min$minusmax$u0020is$u0020reduction   10000  avgt   30  38804.464 ± 302.140  ns/op
[info] ArrayBufferBenchmark.min$minusmax$u0020is$u0020reduction   10000  avgt   30  39647.750 ±  451.768  ns/op
```
Not actually sure what I was measuring, if anything.
```
[info] ArrayBufferBenchmark.sum$u0020is$u0020reduction   10000  avgt   30  46113.616 ± 321.367  ns/op
[info] ArrayBufferBenchmark.sum$u0020is$u0020reduction            10000  avgt   30  48967.822 ± 2856.720  ns/op
```

**Comment by lrytz** [comment]
(rebased to test our Jenkins)

**Comment by som-snytt** [comment]
I wonder if this will get into 2.13.9 so I don't have to worry about rebasing on the force-pushed branch.

**Comment by SethTisue** [comment]
collections reviewers...?

File: src/library/scala/collection/IterableOnce.scala [hunk 1]
```diff
@@ -732,7 +748,12 @@ trait IterableOnceOps[+A, +CC[_], +C] extends Any { this: IterableOnce[A] =>
     *           `op( op( ... op(x,,1,,, x,,2,,) ..., x,,n-1,,), x,,n,,)` where `x,,1,,, ..., x,,n,,`
     *           are the elements of this $coll.
     *  @throws UnsupportedOperationException if this $coll is empty.   */
-  def reduceLeft[B >: A](op: (B, A) => B): B = {
+  def reduceLeft[B >: A](op: (B, A) => B): B = this match {
+    case seq: IndexedSeq[A @unchecked] if seq.length > 0 =>
+      foldl(seq, 1, seq(0), op)
+
+    case _ =>
+
```
Comment (lrytz) [inline src/library/scala/collection/IterableOnce.scala:756]: indentation is off below

File: src/library/scala/collection/IterableOnce.scala [hunk 2]
```diff
@@ -650,7 +666,7 @@ trait IterableOnceOps[+A, +CC[_], +C] extends Any { this: IterableOnce[A] =>
    *            are the elements of this $coll.
     *           Returns `z` if this $coll is empty.
     */
-  def foldLeft[B](z: B)(op: (B, A) => B): B = {
+  def foldLeft[B](z: B)(op: (B, A) => B): B = if (this.isInstanceOf[IndexedSeq[_]]) foldl(this.asInstanceOf[IndexedSeq[A]], 0, z, op) else {
```
Comment (lrytz) [inline src/library/scala/collection/IterableOnce.scala:669]: `this match` to make it like the others?

File: src/library/scala/collection/mutable/ArrayBuffer.scala [hunk 3]
```diff
@@ -258,6 +259,22 @@ class ArrayBuffer[A] private (initialElements: Array[AnyRef], initialSize: Int)
     }
     this
   }
+
+  @tailrec private def foldl[B](start: Int, end: Int, z: B, op: (B, A) => B): B =
+    if (start == end) z
+    else foldl(start + 1, end, op(z, array(start).asInstanceOf[A]), op)
```
Comment (lrytz) [inline src/library/scala/collection/mutable/ArrayBuffer.scala:265]: Is this more efficient than the version for IndexedSeqOps because it avoids the indirection through `apply`? Does that difference show up in benchmarks?

File: src/library/scala/collection/IterableOnce.scala (hunk 2 above)
Comment (som-snytt) [reply src/library/scala/collection/IterableOnce.scala:669]: ichoran made me feel foolish for using match all the time.

File: src/library/scala/collection/IterableOnce.scala (hunk 1 above)
Comment (som-snytt) [reply src/library/scala/collection/IterableOnce.scala:756]: I can't see it in the github UI. Is this scala 2 or 3? I'll have to look at my local file. Modern github tech is so amazing. I'm usually impeccable on indents, unless it is happy hour.

File: src/library/scala/collection/mutable/ArrayBuffer.scala (hunk 3 above)
Comment (som-snytt) [reply src/library/scala/collection/mutable/ArrayBuffer.scala:265]: Yes, I saw a diff in benchmark, but I did not analyze. I mention it somewhere.

File: src/library/scala/collection/IterableOnce.scala (hunk 1 above)
Comment (som-snytt) [reply src/library/scala/collection/IterableOnce.scala:756]: oh I resolved the comment so I could see the alignment. I think that was intentional because Scala 3 has messed with my sense of indent. Also I prefer to avoid the diff if possible.

For example, should the `case` and `if` guard align?

I don't mind indenting before squashing.
