### PR TITLE
Avoid compiler deadlock with `-Ybackend-parallelism` (use lock-free fifo cache for `parsedClasses` in backend)

### LINKED ISSUE #12978: Compiler deadlock in `scalac-jvm-non-ast-*` threads
## Reproduction steps

Scala version: 2.13.13

Sometimes when compiling, the compiler seems to deadlock.

Unfortunately I have no idea how to reproduce. Sometimes I see it in CI logs. One example is here: https://github.com/durban/choam/actions/runs/8499930606/job/23281252612#step:24:1120. If I see it again, I'll try to add more links.

The relevant part copied from the log above:

```
Found one Java-level deadlock:
=============================
"pool-8-thread-4":
  waiting to lock monitor 0x00000231c154a200 (object 0x00000006c94938f8, a java.lang.Object),
  which is held by "scalac-jvm-non-ast-1"

"scalac-jvm-non-ast-1":
  waiting to lock monitor 0x00000231c1548b40 (object 0x00000006c9527430, a java.util.Collections$SynchronizedMap),
  which is held by "scalac-jvm-non-ast-3"

"scalac-jvm-non-ast-3":
  waiting to lock monitor 0x00000231c154a200 (object 0x00000006c94938f8, a java.lang.Object),
  which is held by "scalac-jvm-non-ast-1"
```

<details>
<summary>Stacktrace for these 3 threads:</summary>

```
Java stack information for the threads listed above:
===================================================
"pool-8-thread-4":
	at scala.tools.nsc.backend.jvm.BTypes$LazyVar.get(BTypes.scala:1096)
	- waiting to lock <0x00000006c94938f8> (a java.lang.Object)
	at scala.tools.nsc.backend.jvm.CoreBTypesFromSymbols.lambdaDeserializeBootstrapHandle(CoreBTypes.scala:407)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils.emitLambdaDeserializeIndy$1(BackendUtils.scala:134)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils.addLambdaDeserialize(BackendUtils.scala:155)
	at scala.tools.nsc.backend.jvm.PostProcessor.sendToDisk(PostProcessor.scala:68)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$postProcessUnit$3(GeneratedClassHandler.scala:131)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$postProcessUnit$2(GeneratedClassHandler.scala:131)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler$$Lambda/0x00000231828665d8.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$PostProcessorFrontendAccessImpl.withThreadLocalReporter(PostProcessorFrontendAccess.scala:242)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$postProcessUnit$1(GeneratedClassHandler.scala:130)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler$$Lambda/0x00000231828643c8.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler$$Lambda/0x00000231828649a8.apply(Unknown Source)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(java.base@21.0.2/ThreadPoolExecutor.java:2053)
	at java.util.concurrent.ThreadPoolExecutor.reject(java.base@21.0.2/ThreadPoolExecutor.java:841)
	at java.util.concurrent.ThreadPoolExecutor.execute(java.base@21.0.2/ThreadPoolExecutor.java:1376)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
	at scala.concurrent.impl.Promise$DefaultPromise.map(Promise.scala:182)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.postProcessUnit(GeneratedClassHandler.scala:126)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.process(GeneratedClassHandler.scala:119)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$GlobalOptimisingGeneratedClassHandler.$anonfun$complete$1(GeneratedClassHandler.scala:99)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$GlobalOptimisingGeneratedClassHandler.complete(GeneratedClassHandler.scala:99)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.$anonfun$run$1(GenBCode.scala:81)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:78)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1549)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1533)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1525)
	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1638)
	at scala.tools.xsbt.CachedCompiler0.run(CompilerBridge.scala:176)
	at scala.tools.xsbt.CachedCompiler0.run(CompilerBridge.scala:139)
	- locked <0x00000006c94bfa18> (a scala.tools.xsbt.CachedCompiler0)
	at scala.tools.xsbt.CompilerBridge.run(CompilerBridge.scala:43)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
	at sbt.internal.inc.MixedAnalyzingCompiler$$Lambda/0x0000023181ff4f50.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.MixedAnalyzingCompiler$$Lambda/0x0000023181fecbd0.apply(Unknown Source)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl$$Lambda/0x00000231819cb200.apply(Unknown Source)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:180)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:178)
	at sbt.internal.inc.Incremental$$$Lambda/0x00000231819f05f0.apply(Unknown Source)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:464)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:419)
	at sbt.internal.inc.Incremental$$$Lambda/0x0000023181a04fe8.apply(Unknown Source)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:406)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:172)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
	at sbt.internal.inc.IncrementalCompilerImpl$$Lambda/0x00000231819c6a90.apply(Unknown Source)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2371)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2321)
	at sbt.Defaults$$$Lambda/0x00000231819b88f8.apply(Unknown Source)
	at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:31)
	at sbt.internal.server.BspCompileTask$$$Lambda/0x00000231819c5228.apply(Unknown Source)
	at sbt.internal.io.Retry$.apply(Retry.scala:47)
	at sbt.internal.io.Retry$.apply(Retry.scala:29)
	at sbt.internal.io.Retry$.apply(Retry.scala:24)
	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2319)
	at sbt.Defaults$$$Lambda/0x00000231814c83d0.apply(Unknown Source)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at scala.Function1$$Lambda/0x00000231812d5000.apply(Unknown Source)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
	at sbt.internal.util.$tilde$greater$$Lambda/0x00000231818497c8.apply(Unknown Source)
	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
	at sbt.Execute$$Lambda/0x00000231818542e8.apply(Unknown Source)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
	at sbt.Execute.work(Execute.scala:292)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
	at sbt.Execute$$Lambda/0x000002318184c110.apply(Unknown Source)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.ConcurrentRestrictions$$anon$4$$Lambda/0x000002318184e550.apply(Unknown Source)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
	at java.util.concurrent.FutureTask.run(java.base@21.0.2/FutureTask.java:317)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@21.0.2/Executors.java:572)
	at java.util.concurrent.FutureTask.run(java.base@21.0.2/FutureTask.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@21.0.2/ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@21.0.2/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@21.0.2/Thread.java:1596)
	at java.lang.Thread.run(java.base@21.0.2/Thread.java:1583)
"scalac-jvm-non-ast-1":
	at java.util.Collections$SynchronizedMap.computeIfAbsent(java.base@21.0.2/Collections.java:2980)
	- waiting to lock <0x00000006c9527430> (a java.util.Collections$SynchronizedMap)
	at scala.collection.convert.JavaCollectionWrappers$JMapWrapperLike.getOrElseUpdate(JavaCollectionWrappers.scala:369)
	at scala.collection.convert.JavaCollectionWrappers$JMapWrapperLike.getOrElseUpdate$(JavaCollectionWrappers.scala:368)
	at scala.collection.convert.JavaCollectionWrappers$AbstractJMapWrapper.getOrElseUpdate(JavaCollectionWrappers.scala:344)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.parsedClassNode(ByteCodeRepository.scala:73)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.classNode(ByteCodeRepository.scala:94)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.buildInlineInfo(BTypesFromSymbols.scala:544)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.computeClassInfo(BTypesFromSymbols.scala:456)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.$anonfun$classBTypeFromSymbolInit$1(BTypesFromSymbols.scala:116)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$Lambda/0x00000231822a5d28.apply(Unknown Source)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType$.apply(BTypes.scala:828)
	- locked <0x00000006c9527810> (a scala.tools.nsc.backend.jvm.BTypes$ClassBTypeFromSymbol)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.classBTypeFromSymbol(BTypesFromSymbols.scala:106)
	at scala.tools.nsc.backend.jvm.CoreBTypesFromSymbols.$anonfun$_srLambdaDeserialize$1(CoreBTypes.scala:226)
	at scala.tools.nsc.backend.jvm.CoreBTypesFromSymbols$$Lambda/0x0000023182d5b578.apply(Unknown Source)
	at scala.tools.nsc.backend.jvm.BTypes$LazyVar.$anonfun$get$1(BTypes.scala:1097)
	at scala.tools.nsc.backend.jvm.BTypes$LazyVar.get(BTypes.scala:1096)
	- locked <0x00000006c94938f8> (a java.lang.Object)
	at scala.tools.nsc.backend.jvm.CoreBTypesFromSymbols.srLambdaDeserialize(CoreBTypes.scala:225)
	at scala.tools.nsc.backend.jvm.CoreBTypesFromSymbols.$anonfun$_lambdaDeserializeBootstrapHandle$1(CoreBTypes.scala:410)
	at scala.tools.nsc.backend.jvm.CoreBTypesFromSymbols$$Lambda/0x0000023182d5b2c0.apply(Unknown Source)
	at scala.tools.nsc.backend.jvm.BTypes$LazyVar.$anonfun$get$1(BTypes.scala:1097)
	at scala.tools.nsc.backend.jvm.BTypes$LazyVar.get(BTypes.scala:1096)
	- locked <0x00000006c94938f8> (a java.lang.Object)
	at scala.tools.nsc.backend.jvm.CoreBTypesFromSymbols.lambdaDeserializeBootstrapHandle(CoreBTypes.scala:407)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils.emitLambdaDeserializeIndy$1(BackendUtils.scala:134)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils.addLambdaDeserialize(BackendUtils.scala:155)
	at scala.tools.nsc.backend.jvm.PostProcessor.sendToDisk(PostProcessor.scala:68)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$postProcessUnit$3(GeneratedClassHandler.scala:131)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$postProcessUnit$2(GeneratedClassHandler.scala:131)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler$$Lambda/0x00000231828665d8.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$PostProcessorFrontendAccessImpl.withThreadLocalReporter(PostProcessorFrontendAccess.scala:242)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$postProcessUnit$1(GeneratedClassHandler.scala:130)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler$$Lambda/0x00000231828643c8.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler$$Lambda/0x00000231828649a8.apply(Unknown Source)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@21.0.2/ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@21.0.2/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@21.0.2/Thread.java:1596)
	at java.lang.Thread.run(java.base@21.0.2/Thread.java:1583)
"scalac-jvm-non-ast-3":
	at scala.tools.nsc.backend.jvm.BTypes$LazyVar.get(BTypes.scala:1096)
	- waiting to lock <0x00000006c94938f8> (a java.lang.Object)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.parseClass(ByteCodeRepository.scala:328)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.$anonfun$parsedClassNode$1(ByteCodeRepository.scala:73)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository$$Lambda/0x00000231827c53a8.apply(Unknown Source)
	at scala.collection.convert.JavaCollectionWrappers$JMapWrapperLike.$anonfun$getOrElseUpdate$1(JavaCollectionWrappers.scala:369)
	at scala.collection.convert.JavaCollectionWrappers$JMapWrapperLike$$Lambda/0x000002318278e2a0.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(java.base@21.0.2/HashMap.java:1228)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(java.base@21.0.2/Collections.java:2980)
	- locked <0x00000006c9527430> (a java.util.Collections$SynchronizedMap)
	at scala.collection.convert.JavaCollectionWrappers$JMapWrapperLike.getOrElseUpdate(JavaCollectionWrappers.scala:369)
	at scala.collection.convert.JavaCollectionWrappers$JMapWrapperLike.getOrElseUpdate$(JavaCollectionWrappers.scala:368)
	at scala.collection.convert.JavaCollectionWrappers$AbstractJMapWrapper.getOrElseUpdate(JavaCollectionWrappers.scala:344)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.parsedClassNode(ByteCodeRepository.scala:73)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.classNode(ByteCodeRepository.scala:94)
	at scala.tools.nsc.backend.jvm.BTypesFromClassfile.$anonfun$classBTypeFromParsedClassfile$1(BTypesFromClassfile.scala:69)
	at scala.tools.nsc.backend.jvm.BTypesFromClassfile$$Lambda/0x00000231828225e0.apply(Unknown Source)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType$.apply(BTypes.scala:828)
	- locked <0x00000006ebcf5e80> (a scala.tools.nsc.backend.jvm.BTypes$ClassBTypeFromClassfile)
	at scala.tools.nsc.backend.jvm.BTypesFromClassfile.classBTypeFromParsedClassfile(BTypesFromClassfile.scala:68)
	at scala.tools.nsc.backend.jvm.BTypesFromClassfile.bTypeForDescriptorFromClassfile(BTypesFromClassfile.scala:59)
	at scala.tools.nsc.backend.jvm.BTypesFromClassfile.bTypeForDescriptorOrInternalNameFromClassfile(BTypesFromClassfile.scala:44)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.isSubType$1(LocalOpt.scala:700)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.eliminateRedundantCastsAndRewriteSomeIntrinsics(LocalOpt.scala:749)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.removalRound$2(LocalOpt.scala:321)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.methodOptimizations(LocalOpt.scala:380)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.$anonfun$methodOptimizations$1(LocalOpt.scala:215)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.$anonfun$methodOptimizations$1$adapted(LocalOpt.scala:214)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt$$Lambda/0x0000023182866e38.apply(Unknown Source)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:727)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:721)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:935)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.methodOptimizations(LocalOpt.scala:214)
	at scala.tools.nsc.backend.jvm.PostProcessor.$anonfun$localOptimizations$1(PostProcessor.scala:131)
	at scala.tools.nsc.backend.jvm.PostProcessor.localOptimizations(PostProcessor.scala:131)
	at scala.tools.nsc.backend.jvm.PostProcessor.sendToDisk(PostProcessor.scala:65)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$postProcessUnit$3(GeneratedClassHandler.scala:131)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$postProcessUnit$2(GeneratedClassHandler.scala:131)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler$$Lambda/0x00000231828665d8.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$PostProcessorFrontendAccessImpl.withThreadLocalReporter(PostProcessorFrontendAccess.scala:242)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$postProcessUnit$1(GeneratedClassHandler.scala:130)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler$$Lambda/0x00000231828643c8.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler$$Lambda/0x00000231828649a8.apply(Unknown Source)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@21.0.2/ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@21.0.2/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@21.0.2/Thread.java:1596)
	at java.lang.Thread.run(java.base@21.0.2/Thread.java:1583)

Found 1 deadlock.
```
</details>

### PR DESCRIPTION
**Pull request by lrytz**
Use a lock-free fifo cache for `parsedClasses` in the backend when `-Ybackend-parallelism` is enabled.

Fixes https://github.com/scala/bug/issues/12978.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/backend/jvm/opt/FifoCache.scala [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+      cache.remove(key)
+      queue.remove(key)
+      this
+    }
+
+    def addOne(elem: (K, V)): this.type = {
+      if (cache.size() >= maxSize) {
+        val oldest = queue.poll()
+        if (oldest != null) cache.remove(oldest)
+      }
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/backend/jvm/opt/FifoCache.scala:48]: N threads may `addOne` resulting in size >maxSize. That's OK, but it should draw down `while (size > maxSize)`. N is probably small and the difference might not matter. This speculation is pre-coffee and pre-dawn.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/backend/jvm/opt/FifoCache.scala:48]: 👍 agree `while` makes sense

File: src/compiler/scala/tools/nsc/settings/ScalaSettings.scala [hunk 2]
```diff
@@ -350,7 +350,7 @@ trait ScalaSettings extends StandardScalaSettings with Warnings { _: MutableSett
 
   // Allows a specialised jar to be written. For instance one that provides stable hashing of content, or customisation of the file storage
   val YjarFactory = StringSetting   ("-YjarFactory", "classname", "factory for jar files", classOf[DefaultJarFactory].getName)
-  val YaddBackendThreads = IntSetting   ("-Ybackend-parallelism", "maximum worker threads for backend", 1, Some((1,16)), (x: String) => None )
+  val YaddBackendThreads = IntSetting   ("-Ybackend-parallelism", "maximum worker threads for backend", 8, Some((1,16)), (x: String) => None )
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/settings/ScalaSettings.scala]: `8` sounds likely, but some number not greater than `Runtime.availableProcessors` is also likely. Filing under "things I thought I knew", the JavaDoc says the number can change (during the life of the vm), so you should poll and adapt. At home I don't care, but maybe it matters to CI jobs.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/settings/ScalaSettings.scala]: This change is only for testing, I will revert it before merging

File: test/files/neg/case-collision-multifile/one.scala [hunk 3]
```diff
@@ -1,2 +1,2 @@
-// scalac: -Werror
+// scalac: -Werror -Ybackend-parallelism 1
```
Comment (som-snytt) [inline test/files/neg/case-collision-multifile/one.scala]: opportunity for `using options`, which is not a big deal to an `haut dawg` such as yourself.

Setting to 1 is to avoid re-ordering of `hotDog` and `HotDog` in message?

Comment (lrytz) [reply test/files/neg/case-collision-multifile/one.scala]: Yes, in concurrent cooking of hot dogs you never know which one jumps out first

File: src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala [hunk 4]
```diff
@@ -47,7 +47,7 @@ abstract class ByteCodeRepository extends PerRunInit {
   * Prevent the code repository from growing too large. Profiling reveals that the average size
   * of a ClassNode is about 30 kb. I observed having 17k+ classes in the cache, i.e., 500 mb.
   */
-  private val maxCacheSize = 1500
+  private val maxCacheSize = 100
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala]: an order of mag change in cache size is above my pay grade. What does it mean for large builds?

**Review by som-snytt — APPROVED** [review]
Very nice. Only some questions. Nothing to stop the show.

File: src/compiler/scala/tools/nsc/settings/ScalaSettings.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/ScalaSettings.scala]: Ah, I read "for testing" but the words did not register. So why not parallel by default? It seems natural to me, so there must be a terrible downside.

File: src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala (hunk 4 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala]: Also for testing only. It actually triggered a failure in `CallGraphTest` where we were comparing MethodNode instances using reference equality, the two instances were no longer the same with a smaller cache.

File: src/compiler/scala/tools/nsc/settings/ScalaSettings.scala (hunk 2 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/settings/ScalaSettings.scala]: Not sure :-) Good to know that sbt-typelevel-settings enables it, so the feature seems to be somewhat used / tested at least.

File: src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala (hunk 4 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala]: ah, I saw that test change and didn't ask what motivated it. So the question remains, what's a good constant here. Maybe it doesn't matter greatly, but there may be a formula. Trying to minimize both cache size and reloads. An initial value might depend on how many compilation units in run.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala]: The motivation is limiting the absolute cache size in memory. The value I came up is based on some profiling and gut feeling 🤷‍♂️ Would we gain anything by making it relative to the number of compilation units?

**Comment by lrytz** [comment]
Moved to 2.13.14 for consideration. The changes are limited to users of `-Ybackend-parallelism`.
