### PR TITLE
Fix lack of incompatible type warnings

### LINKED ISSUE #12304: Pattern matching incompatible type does not result compiler error
## reproduction steps

using Scala 2.13.2,

```scala
scala> class Foo
class Foo

scala> val m: Map[String, Map[String, Foo]] = Map("outer" -> Map("inner" -> new Foo))
val m: Map[String,Map[String,Foo]] = Map(outer -> Map(inner -> Foo@28bd5015))

scala> m.collect { case (_, foo: Foo) => "This should be type error" }
val res1: scala.collection.immutable.Iterable[String] = List()

```

## problem

In the example when I tried to match Map as a Foo, it should result in compiler error because they are incompatible non-covariant types and should result a compiler error.

### LINKED ISSUE #12438: Pattern matching incompatible type does not always warn
```
trait UnsealedTrait
def c(c: Option[Int]) = c match { case _: UnsealedTrait =>; case _ =>  }
```

This should warn, as an `Option` cannot possibly be an `UnsealedTrait`.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes scala/bug#12438
Closes scala/bug#12304

### CODE REVIEW

File: test/files/neg/patmat-sealed-reachable.scala [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// scalac: -Werror
```
Comment (som-snytt) [inline test/files/neg/patmat-sealed-reachable.scala:1]: `//> using options -Werror`

You probably think we are so provincial and backwater here.

**Review by lrytz — APPROVED** [review]
Great, thank you!
