### PR TITLE
Fix `ArrayOps` bugs (by avoiding `ArraySeq#array`, which does not guarantee element type)

### LINKED ISSUE #12403: Behavior changes of `intersect` operations related to `Array.empty[T]` between 2.13.5 and 2.13.6
## reproduction steps

using Scala 2.13.6,

```scala
Welcome to Scala 2.13.6 (OpenJDK 64-Bit Server VM, Java 1.8.0_232).
Type in expressions for evaluation. Or try :help.

scala> Array.empty[Double].intersect(Array(0.0))
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [D
  ... 32 elided

scala> Array(0.0).intersect(Array.empty[Double])
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [D
  ... 32 elided

scala> Array.empty[Double].intersect(Array.empty[Double])
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [D
  ... 32 elided
```

but using Scala 2.13.5

```scala
Welcome to Scala 2.13.5 (OpenJDK 64-Bit Server VM, Java 1.8.0_232).
Type in expressions for evaluation. Or try :help.

scala> Array.empty[Double].intersect(Array(0.0))
val res0: Array[Double] = Array()

scala> Array(0.0).intersect(Array.empty[Double])
val res1: Array[Double] = Array()

scala> Array.empty[Double].intersect(Array.empty[Double])
val res2: Array[Double] = Array()
```

## problem

There are behavior changes of `intersect` operations related to `Array.empty[T]`, `return Array()` is replaced by throw `ClassCastException`, Is this expected or a bug?

### PR DESCRIPTION
**Pull request by som-snytt**
In a way,

Fixes scala/bug#12403

(which regressed in https://github.com/scala/scala/pull/9365)

### CODE REVIEW

**Comment by SethTisue** [comment]
On the face of it, this looks like a quick merge. But (after discussion with Dale) I actually want to slow down and understand if a better fix is possible.

According to the Scaladoc for `ArraySeq`, `ArraySeq` is within its rights to be using an `Array[Object]` here:

>   /** The underlying array. Its element type does not have to be equal to the element type of this ArraySeq. A primitive
>    * ArraySeq can be backed by an array of boxed values and a reference ArraySeq can be backed by an array of a supertype
>    * or subtype of the element type. */

so if `empty` is within contract here, why is it wrong for `intersect` to use it?

Must `empty` be a footgun?

**Comment by SethTisue** [comment]
in `ArrayOps.scala` we see:

```
  def intersect[B >: A](that: Seq[B]): Array[A] =
    mutable.ArraySeq.make(xs).intersect(that).array.asInstanceOf[Array[A]]
```

this seems incorrect to me -- it assumes behavior from `ArraySeq` that `ArraySeq` explicitly does not promise -- if we fixed this instead, then Martijn's code would be correct and the change in this PR would not be needed. (right?)

one thing I don't understand here yet is _why_ `ArraySeq` claims this freedom for itself. you can't make an `ArraySeq` without a `ClassTag`, so why does `ArraySeq` need the freedom to perhaps be using an `Array[java.lang.Double]` or `Array[AnyRef]` internally instead of the `Array[Double]` one would normally expect?

**Comment by SethTisue** [comment]
maybe the @scala/collections crew would like to pile on, here

**Comment by NthPortal** [comment]
I am inclined to agree with Seth that the thing that needs fixing is the `ArrayOps` code, not the base implementation of `intersect`. I'm especially not fond of the fact that there's no apparent reason to use `newSpecificBuilder.result()` over `empty`, and that someone might innocently refactor it back, to much confusion.

**Comment by som-snytt** [comment]
Yes, my comment was it fixes the issue "in a way" because there are alternatives and the quick fix is not compelling.

ArrayOps says "The remaining methods are provided for completeness but they delegate to mutable.ArraySeq implementations which may not provide the best possible performance." So all those calls could rebuild the desired array as necessary without violating the lightbend support contract.

The original sin is
```
  // This is reused for all calls to empty.
  private[this] val EmptyArraySeq  = new ofRef[AnyRef](new Array[AnyRef](0))
  def empty[T : ClassTag]: ArraySeq[T] = EmptyArraySeq.asInstanceOf[ArraySeq[T]]
```
https://github.com/scala/scala/pull/6648
https://github.com/scala/bug/issues/10851
where lrytz asks
> Also, can we avoid this problem here:
```
scala> a.array
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [I
```
Here is the unused (`-Xlint` would have told you that) tag:
```
scala> ArraySeq.make(Array(42)).array.getClass.getComponentType
val res16: Class[_] = int

scala> ArraySeq.empty(ArraySeq.make(Array(42)).elemTag).array.getClass.getComponentType
val res17: Class[_] = class java.lang.Object
```

**Comment by johnynek** [comment]
First, is it important to do the `def empty` optimization? It seems strange to me that we accept `ClassTag[A]` on that method, but then discard it. I am skeptical that allocation is really costing us much, and I would consider just always using the ClassTag that comes in (note both immutable and mutable do discard the ClassTag in empty).

Second, the ArrayOps intersect implementation should be rewritten to avoid the cast IMO. The cast is assuming something is too strong. I think something as simple as:
```scala
val bs = that.toSet
val resultSize = count(bs)
val result = new Array[A](resultSize)
var idx = 0
var cnt = 0
while (cnt < resultSize) {
  val a = apply(idx)
  if (bs(a)) {
    result(cnt) = a
    cnt += 1
  }
  idx += 1
}
result
```

Third, the change in this PR *also* seems worthwhile to me, except I think we should weaken the tests so that we aren't testing the classtypes (since I don't think that is part of the signature).

File: test/junit/scala/collection/StrictOptimizedSeqTest.scala [hunk 1]
```diff
@@ -20,4 +20,24 @@ class StrictOptimizedSeqTest {
...
     assertEquals(Vector("a", "aa", "aaa", "bbbb"), result)
   }
+
+  @Test
+  def `empty intersection has correct component type for array`(): Unit = {
+    val something = Array(3.14)
+    val nothing   = Array[Double]()
+    val empty     = Array.empty[Double]
+
+    assertEquals(classOf[Double], nothing.intersect(something).getClass.getComponentType)
```
Comment (johnynek) [inline test/junit/scala/collection/StrictOptimizedSeqTest.scala]: I think we should remove the classOf asserts because I think they are stronger than the contract really is.

**Comment by som-snytt** [comment]
Thanks, I'll do a quickie PR with re-building the result in ArrayOps as necessary. I don't mind doing it as an exercise, if that is also not desirable.

File: test/junit/scala/collection/StrictOptimizedSeqTest.scala (hunk 1 above)
Comment (som-snytt) [reply test/junit/scala/collection/StrictOptimizedSeqTest.scala]: I just assumed someone working with an array of primitive double always wants that. Ichoran always complains if something is unexpectedly boxed and performance suffers. or he used to complain. I'll give it some naive thought.

**Comment by som-snytt** [comment]
I don't have a knowledgeable opinion about empty and caching it.

Let me add that "knowledgeable" is a very strange word. What does it even mean?

**Comment by dwijnand** [comment]
> The original sin is
> 
> ```
>   // This is reused for all calls to empty.
>   private[this] val EmptyArraySeq  = new ofRef[AnyRef](new Array[AnyRef](0))
>   def empty[T : ClassTag]: ArraySeq[T] = EmptyArraySeq.asInstanceOf[ArraySeq[T]]
> ```

It was less sinful originally when it was `def empty[T <: AnyRef]: WrappedArray[T] = ...`.

> First, is it important to do the `def empty` optimization? It seems strange to me that we accept `ClassTag[A]` on that method, but then discard it. I am skeptical that allocation is really costing us much, and I would consider just always using the ClassTag that comes in (note both immutable and mutable do discard the ClassTag in empty).

Yes and no?  https://github.com/scala/scala/commit/fdb1e699911ccf4467c6663a799736e42c18eb83 states it avoids allocating 100+ million empty arrays but at the same time how it didn't make as much as a difference as it sounds like it should. 🤷🏼‍♂️

File: test/junit/scala/collection/StrictOptimizedSeqTest.scala (hunk 1 above)
Comment (dwijnand) [reply test/junit/scala/collection/StrictOptimizedSeqTest.scala]: It's a good point that it's stronger than the contract.  But I agree it's good to have the assertion to track the behaviour nonetheless.

File: src/library/scala/collection/ArrayOps.scala [hunk 2]
```diff
@@ -1637,4 +1637,12 @@ final class ArrayOps[A](private val xs: Array[A]) extends AnyVal {
     *  @return `true` if this array has `that` as a suffix, `false` otherwise.
     */
   def endsWith[B >: A](that: Iterable[B]): Boolean = mutable.ArraySeq.make(xs).endsWith(that)
+
+  /** Ensure we are providing an array of the correct element type.
+   */
+  private def narrowly(ys: Array[_]): Array[A] =
```
Comment (johnynek) [inline src/library/scala/collection/ArrayOps.scala]: is this cast safe? It seems like this `Array[_ <: A]` because we know we can assign A from an argument?

Can we add a comment explaining the argument of why this cast is safe? I wonder if we don't need `implicitly[ClassTag[A]].runtimeClass == ys.getClass.getComponentType` for this to be safe.

Comment (johnynek) [inline src/library/scala/collection/ArrayOps.scala]: can we make this method accept `mutable.ArraySeq` instead since all callers seem to use it:

```scala
private def narrowArray(ys: mutable.ArraySeq[A]): Array[A] = ...
```
this makes it somewhat safer, IMO, in that the contract on the input is strengthened.

File: src/library/scala/collection/ArrayOps.scala [hunk 3]
```diff
@@ -1637,4 +1637,12 @@ final class ArrayOps[A](private val xs: Array[A]) extends AnyVal {
...
+    if (implicitly[ClassTag[A]].runtimeClass.isAssignableFrom(ys.getClass.getComponentType))
+      ys.asInstanceOf[Array[A]]
+    else
+      Array[A](immutable.ArraySeq.unsafeWrapArray(ys).asInstanceOf[immutable.Seq[A]]: _*)
```
Comment (johnynek) [inline src/library/scala/collection/ArrayOps.scala]: if the argument is `mutable.ArraySeq[A]` I think we could just call `.toArray` here and be safer (no need for cast here).

**Comment by NthPortal** [comment]
please note that the problematic method is `ArraySeq#empty` not `ArraySeq.empty`

**Comment by NthPortal** [comment]
thoughts about adding a private `intersect` (and `diff`, etc.) method in one of the companion objects that takes the collections and a factory or builder, so that `ArrayOps` doesn't need to `mutable.ArraySeq#intersect` returning an array with the same element type, but we also don't duplicate code?

File: src/library/scala/collection/ArrayOps.scala [hunk 4]
```diff
@@ -1637,4 +1637,12 @@ final class ArrayOps[A](private val xs: Array[A]) extends AnyVal {
     *  @return `true` if this array has `that` as a suffix, `false` otherwise.
     */
   def endsWith[B >: A](that: Iterable[B]): Boolean = mutable.ArraySeq.make(xs).endsWith(that)
+
+  /** Ensure we are providing an array of the correct element type.
+   */
+  private def narrowly(ys: Array[_]): Array[A] =
+    if (implicitly[ClassTag[A]].runtimeClass.isAssignableFrom(ys.getClass.getComponentType))
```
Comment (lrytz) [inline src/library/scala/collection/ArrayOps.scala]:
```suggestion
    if (xs.getClass.getComponentType == ys.getClass.getComponentType))
```

We should not go into subtyping here, returning an `Array[String]` when `A == Object` could lead to `ArrayStoreException`s.

**Review by lrytz — COMMENTED** [review]
This LGTM otherwise, `arraySeq.array` is doing what it says, so such workarounds are needed if we want to use it.

I'm also fine if someone wants to come up with a solution that doesn't use `ArraySeq`.

**Comment by som-snytt** [comment]
I simplified to just do @johnynek `toArray`. Did I over-simplify? Not copying the result may be unexpected if it is exactly the input array. Do we expect `(xs op ys) ne xs`?

I leveraged the comment about "these are for completeness not efficiency".

@NthPortal 's last comment went over my head, so I'll leave that for the collections collective.

File: src/library/scala/collection/ArrayOps.scala (hunk 4 above)
Comment (som-snytt) [reply src/library/scala/collection/ArrayOps.scala]: I assumed the Y is wider than A, but I also did not devise a use case where Y is narrower than A. I took this suggestion before just `toArray`.

**Comment by lrytz** [comment]
> Do we expect `(xs op ys) ne xs`?

Yes, I think so, but `toArray` does create a copy, so it should be good.

File: src/library/scala/collection/ArrayOps.scala (hunk 3 above)
Comment (som-snytt) [reply src/library/scala/collection/ArrayOps.scala]: Thanks I forgot about `toArray`. You didn't hear the words I uttered aloud when asking myself how do I get an array. I wound up just doing `.toArray` instead of `.array`.

File: test/junit/scala/collection/StrictOptimizedSeqTest.scala (hunk 1 above)
Comment (som-snytt) [reply test/junit/scala/collection/StrictOptimizedSeqTest.scala]: `Array` says I get back an array of the same type. I don't know what `A` is in the scaladoc, but I hope it is `T`.
```
def intersect[B >: A](that: collection.Seq[B]): Array[T]
```

**Review by SethTisue — APPROVED** [review]
I believe this PR is now mergeable as-is. Along the way some questions and suggestions came up about possible future PRs in the same area, but this PR seems like the right minimal fix to me.

**Review by johnynek — APPROVED** [review]
I think we should change the title of the PR to "Avoid using ArraySeq#array inside of ArrayOps" or something similar.

**Review by RubenVerg — APPROVED** [review]

**Review by lrytz — APPROVED** [review]

**Comment by johnynek** [comment]
what's the story with changes like this wrt to scala 3?

I guess it has the same bug, right?

**Comment by dwijnand** [comment]
Periodically scala 3 bumps their scala-library version.  So the Scala 3 release after 2.13.7 will have this.
