### PR TITLE
Fix bugginess in `immutable.HashSet#subsetOf` [ci: last-only]

### LINKED ISSUE #12944: `scala.collection.immutable.HashSet.subsetOf` can throw an error on valid data in 2.13
## Reproduction steps

Scala version: 2.13.12

There are 4 tuples of sets to identify whether the 1st one is a subset of the second.

```scala
import scala.collection.immutable.HashSet

val set_tuples = Seq(
  (HashSet("ian", "cra"), HashSet("john", "michael", "mills")),
  (HashSet("ian", "cras"), HashSet("john", "michael", "mills")),
  (HashSet("ian", "crasto"), HashSet("john", "michael", "mills")),
  (HashSet("ian", "craston"), HashSet("john", "michael", "mills")),
  )

set_tuples.foreach(tuple => {
    val s1 = tuple._1
    val s2 = tuple._2
    try {
      val result = s1.subsetOf(s2)
      println(s"Result is $result for $s1 <= $s2")
    } catch {
      case _: ClassCastException => println(s"Class cast exception for $s1 <= $s2")
      case exc: Throwable => println(s"Exception $exc for $s1 <= $s2")
    }
  }
)
```

## Expected behavior

For all 4 tuples the result should be false.

## Actual behavior

```
Result is false for HashSet(cra, ian) <= HashSet(michael, john, mills)
Class cast exception for HashSet(cras, ian) <= HashSet(michael, john, mills)
Result is false for HashSet(ian, crasto) <= HashSet(michael, john, mills)
Class cast exception for HashSet(craston, ian) <= HashSet(michael, john, mills)
```

Exceptions for tuples 2 and 4.

## Additional information

For Scala version 2.12.18.

```
Result is false for Set(cra, ian) <= Set(michael, john, mills)
Result is false for Set(cras, ian) <= Set(michael, john, mills)
Result is false for Set(ian, crasto) <= Set(michael, john, mills)
Result is false for Set(craston, ian) <= Set(michael, john, mills)
```

### PR DESCRIPTION
**Pull request by som-snytt**
`subsetOf` failed if, for a prefix, lhs had a subnode but rhs had a data item.

(In the example, the prefix is for the hash of the "improved" hash, which does collide in the prefix value `0xC`, where the prefix is "take right".)

Fixes scala/bug#12944

### CODE REVIEW

File: src/library/scala/collection/immutable/HashSet.scala [hunk 1]
```diff
@@ -988,7 +988,7 @@ private final class BitmapIndexedSetNode[A](
               val elementHash = improve(elementUnimprovedHash)
               subNode.contains(payload, elementUnimprovedHash, elementHash, shift + BitPartitionSize)
             }
-          } else {
+          } else ((node.dataMap & bitpos) == 0) && {
```
Comment (lrytz) [inline src/library/scala/collection/immutable/HashSet.scala:991]: One-element subnodes are eliminated it seems, so if `this` has a subnode at `bitpos` there are at least 2 elements, so there needs to be a subnode in `that`

**Review by lrytz — APPROVED** [review]
Thank you!

File: src/library/scala/collection/immutable/HashSet.scala (hunk 1 above)
Comment (som-snytt) [reply src/library/scala/collection/immutable/HashSet.scala:991]: At first I wrote `else if (x != 0) false` which I could have commented appropriately, but then I was seduced by the boolean expression.

File: src/library/scala/collection/immutable/HashSet.scala [hunk 2]
```diff
@@ -190,10 +190,10 @@ final class HashSet[A] private[immutable](private[immutable] val rootNode: Bitma
     * Stops iterating the first time that f returns `false`.*/
   @`inline` private[collection] def foreachWithHashWhile(f: (A, Int) => Boolean): Unit = rootNode.foreachWithHashWhile(f)
 
-  def subsetOf(that: Set[A]): Boolean = if (that.isEmpty) true else that match {
+  def subsetOf(that: Set[A]): Boolean = isEmpty || !that.isEmpty && (that match {
```
Comment (retronym) [inline src/library/scala/collection/immutable/HashSet.scala:193]: LGTM.

I was wondering whether the fix should be here or in each of the receivers of `rootNode.subsetOf`. That initially felt preferable to also avoid this edge case when recursing into the trie. But I'm pretty sure `that.rootNode` is the only possible empty node in `that`.

There may be an optimization opportunity available here too, by short-circuiting when `this.size > that.size`. Or maybe that already falls out of the underlying implementation. The goal would be to avoid needless `.equals` calls.

**Review by retronym — APPROVED** [review]

File: src/library/scala/collection/immutable/HashSet.scala (hunk 2 above)
Comment (som-snytt) [reply src/library/scala/collection/immutable/HashSet.scala:193]: Thanks for :eyes:. On my exercise run just now, considered the case in the OP example, where common prefix is long. You could keep the prefix length at the node and avoid one-legged depth. Not sure if that will work out, but once bitten by the algo bug so to speak, one looks for more to do.
