### PR TITLE
Do not rely on `ArrayIndexOOBE` in new-Vector `Vector.{head,last}`.

### LINKED ISSUE #11920: The new Vector relies on catch AIOOBEs, which are UB in Scala.js
See https://contributors.scala-lang.org/t/new-vector-performance-on-scala-js/4135 for some context. The new `Vector` implementation relies on catching `ArrayIndexOutOfBoundsException`s happening on its internal arrays, to then throw user-level exceptions.

This doesn't work on Scala.js, because AIOOBEs are Undefined Behavior (they have always been). This means that accessing out of bounds of a `Vector` now throws an `UndefinedBehaviorError` with internal details of `Vector`, instead of user-level `IndexOutOfBoundsException` (mentioning the size of the vector, not the size of some internal array) or `NoSuchElementException`.

I have already sent a PR to fix the two `NoSuchElementException`s (https://github.com/scala/scala/pull/8827), because NSEEs really don't have any precedent for being UB. There are still a bunch of cases to throw `IndexOutOfBoundsException`s. Those are less bad but they're still pretty bad, as index out of bounds on Scala collections have never been UB before.

### PR DESCRIPTION
**Pull request by sjrd**
This is necessary for Scala.js, where `ArrayIndexOutOfBoundsException`s are Undefined Behavior, and cannot be reliably caught.

Those methods throw a `NoSuchElementException` for an empty vector, and those exceptions have never been considered UB in Scala.js before. It is therefore a breach of contract for `Vector.{head,last}` to become UB on empty vectors.

There are many other places where we catch AIOOBEs, but in those other places we throw an `IndexOutOfBoundsException` instead. While it is not quite correct to turn them into UBs either, at *least* there is precedent for OOBEs to be considered UB in Scala.js. So this commit does not change them, being afraid of the consequences to JVM performance.

It *is* still bad, though (index out of bounds on Scala collections were never UB before), but at least it is a bit less bad than before.

---

This combines with #8828 to fix https://github.com/scala/bug/issues/11920.

### CODE REVIEW

File: src/library/scala/collection/immutable/Vector.scala [hunk 1]
```diff
@@ -250,15 +250,16 @@ sealed abstract class Vector[+A] private[immutable] (private[immutable] final va
...
-    if(this.isInstanceOf[BigVector[_]]) {
-      val v = this.asInstanceOf[BigVector[_]]
-      v.suffix1(v.suffix1.length-1)
-    } else prefix1(prefix1.length-1)
-  }.asInstanceOf[A] catch { case _: ArrayIndexOutOfBoundsException => throw new NoSuchElementException("empty.tail") }
+  override final def last: A = {
+    val suffix =
+      if(this.isInstanceOf[BigVector[_]]) this.asInstanceOf[BigVector[_]].suffix1
+      else prefix1
+    if(suffix.length == 0) throw new NoSuchElementException("empty.tail")
```
Comment (szeiger) [inline src/library/scala/collection/immutable/Vector.scala]: The check is only needed in the `BigVector` case (actually only for `Vector0` which counter-intuitively extends `BigVector`)

Comment (sjrd) [reply src/library/scala/collection/immutable/Vector.scala]: Good point. Fixed.

**Review by szeiger — APPROVED** [review]
I haven't run new benchmarks yet but this is basically the same as the changes in `apply`. It will cost us a few percent of performance to avoid accessing invalid array indices.

**Comment by sjrd** [comment]
Thanks!
