### PR TITLE
ObjectTpeJava is truly unique; bounds; isAnyTpe

### LINKED ISSUE #11525: scala-js file order sensitive bug related to https://github.com/scala/scala/pull/7966?
to reproduce, checkout branch t11525 from https://github.com/adriaanm/scala-js

`sbt javalanglib/compile`:

```
> javalanglib/compile
[info] Compiling 42 Scala sources to /Users/adriaan/git/scala-js/javalanglib/target/scala-2.13.0-pre-2ef2f9f/classes...
ArrayBuffer(/Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Long.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Math.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/InheritableThreadLocal.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Appendable.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Comparable.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/StringBuffer.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/StackTraceElement.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Runtime.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/ThreadLocal.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Character.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Void.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Cloneable.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/StackTrace.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Number.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Thread.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Readable.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Integer.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/StringBuilder.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/AutoCloseable.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/System.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/ClassLoader.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Byte.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Class.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Throwables.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/FloatingPointBits.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Double.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/ObjectClone.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/CharSequence.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Iterable.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/_String.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Short.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Enum.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Runnable.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Boolean.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Float.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/ref/PhantomReference.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/ref/Reference.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/ref/SoftReference.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/ref/ReferenceQueue.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/ref/WeakReference.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/reflect/Array.scala, /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/annotation/Annotation.scala)
[error] /Users/adriaan/git/scala-js/javalanglib/src/main/scala/java/lang/Iterable.scala:18: error: type arguments [T] do not conform to trait Iterator's type parameter bounds [E <: Object]
[error]   def iterator(): Iterator[T]
[error]                   ^
[info] one error found
```

### PR DESCRIPTION
**Pull request by adriaanm**
Make sure the TypeRef is truly unique, even when embedded
in other types, such as a TypeBounds. Since we're dealing
with structural equality, `TypeBounds(lo, hi) == TypeBounds(lo', hi')`
if `lo == lo'` and `hi == hi'`, if `hi = ObjectTpe` and `hi' = ObjectTpe'`,
`unique`'ing (hashconsing) such a `TypeBounds` would indirectly
replace `ObjectTpe` with `ObjectTpeJava` or vice versa.

We can't use `eq` when trying to identify `ObjectTpeJava` in `unique`
due to cycles.

`isAnyTpe` returns `true` for `ObjectTpeJava`.

Further fixes by Lukas:
  - Don't show ObjectTpeJava upper bound in TypeBounds.toString
  - Upper bounds of wildcards should be ObjectTpeJava
  - Fix wildcardExtrapolation for BoundedWildcardType with hi ObjectTpeJava

Reduce `_ >: lo <: ObjectTpeJava` to `lo`. This eliminates the
`BoundedWildcardType` in the expected type when type-checking the
lambda

    (c: java.util.Collection[String]).removeIf(x => true)

where

    boolean removeIf(Predicate<? super E> filter)

Follow up for #7966 

Fix https://github.com/scala/bug/issues/11525

### CODE REVIEW

**Comment by adriaanm** [comment]
Strawman fix. Not sure this is ok for performance, but the test reliably shows that if we don't do something like this, `unique` will collapse our two ObjectTpe variants.

`ObjectTpeJava` could still be replaced by `ObjectTpe` when `unique`ing a Type that contains `ObjectTpeJava`, since e.g. `TypeBounds(...ObjectTpeJava...).equalsTypeBounds(...ObjectTpe...)` and thus `unique`ing the `TypeBounds` will also replace our precious `ObjectTpeJava` by `ObjectTpe`.

File: src/reflect/scala/reflect/internal/Types.scala [hunk 1]
```diff
@@ -2408,7 +2408,7 @@ trait Types
     override final def equals(other: Any): Boolean = {
       if (this eq other.asInstanceOf[AnyRef]) true
       else other match {
-        case otherTypeRef: TypeRef =>
+        case otherTypeRef: TypeRef if !(otherTypeRef.isInstanceOf[ObjectTpeJavaRef] || this.isInstanceOf[ObjectTpeJavaRef]) =>
           Objects.equals(pre, otherTypeRef.pre) && sym.eq(otherTypeRef.sym) && sameElementsEquals(args, otherTypeRef.args)
```
Comment (retronym) [inline src/reflect/scala/reflect/internal/Types.scala]: We could put the new conditions after the existing ones if we're paranoid about performance.

```
 case otherTypeRef: TypeRef =>
  Objects.equals(pre, otherTypeRef.pre) && sym.eq(otherTypeRef.sym) && sameElementsEquals(args, otherTypeRef.args) && !(otherTypeRef.isInstanceOf[ObjectTpeJavaRef] || this.isInstanceOf[ObjectTpeJavaRef])
```

**Comment by retronym** [comment]
This fix exposed another bug in my attempt at this: `Optional<?>` in Java code should be translated to `Optional[_ <: Object[Java]]`. Pushed an attempted fix.

**Comment by adriaanm** [comment]
Regressed on 
```
!!  545 - pos/t11469_2                              [compilation failed with 1 errors]
##### Log file '/home/jenkins/workspace/scala-2.13.x-validate-main@2/test/files/pos/t11469_2-pos.log' from failed test #####

Test_2.scala:5: error: name clash between defined and inherited member:
def m(x$1: java.util.Optional[_]): Unit in class B and
override def m(a: java.util.Optional[_ <: Object]): Unit at line 5
have same type after erasure: (x$1: java.util.Optional)Unit
    override def m(a: java.util.Optional[_ <: Object]): Unit = { }
                 ^
one error found
```

**Comment by retronym** [comment]
Minimisation of the latest mole: 

```
class Test {
  def foo(c: java.util.Collection[String]): Unit = {
    c.removeIf(x => true)
  }
}
```

File: src/reflect/scala/reflect/internal/Types.scala [hunk 2]
```diff
@@ -2408,7 +2408,7 @@ trait Types
     override final def equals(other: Any): Boolean = {
       if (this eq other.asInstanceOf[AnyRef]) true
       else other match {
-        case otherTypeRef: TypeRef =>
+        case otherTypeRef: TypeRef if !(otherTypeRef.isInstanceOf[ObjectTpeJavaRef] || this.isInstanceOf[ObjectTpeJavaRef]) =>
```
Comment (lrytz) [inline src/reflect/scala/reflect/internal/Types.scala]: can we use `eq`/`ne` here instead of the type test?

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Types.scala]: I tried that, but it caused cycles.

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala [hunk 3]
```diff
@@ -674,9 +674,9 @@ abstract class ClassfileParser(reader: ReusableInstance[ReusableDataReader]) {
                           val tp = sig2type(tparams, skiptvs)
                           // sig2type seems to return AnyClass regardless of the situation:
                           // we don't want Any as a LOWER bound.
-                          if (tp.typeSymbol == AnyClass) TypeBounds.empty
-                          else TypeBounds.lower(tp)
-                        case '*' => TypeBounds.empty
+                          if (tp.typeSymbol == AnyClass) TypeBounds.upper(definitions.ObjectTpeJava)
```
Comment (adriaanm) [inline src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala:677]: Can you add an example for the importance of distinguishing `AnyTpe` and `ObjectTpeJava` here?

File: src/reflect/scala/reflect/internal/Types.scala [hunk 4]
```diff
@@ -1542,7 +1542,7 @@ trait Types
       case _                => lo <:< that && that <:< hi
     }
     private def emptyLowerBound = typeIsNothing(lo) || lo.isWildcard
-    private def emptyUpperBound = typeIsAny(hi) || hi.isWildcard
+    private def emptyUpperBound = typeIsAny(hi) || hi.eq(definitions.ObjectTpeJava) || hi.isWildcard
```
Comment (adriaanm) [inline src/reflect/scala/reflect/internal/Types.scala]: should we actually move `hi.eq(definitions.ObjectTpeJava)` into `typeIsAny`?

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Types.scala]: Added that in my squashed version

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Types.scala]: Well, that didn't work -- compiler won't bootstrap. Didn't investigate.

Comment (retronym) [reply src/reflect/scala/reflect/internal/Types.scala]: The (first?) bootstrap error:

```
src/library/scala/collection/concurrent/TrieMap.scala:285: error: type mismatch;
 found   : Any
 required: AnyRef
        ln.get(k).asInstanceOf[Option[AnyRef]].getOrElse(NO_SUCH_ELEMENT_SENTINEL)
                                                        ^
one error found
```

Amounts to:

```
$ tail sandbox/J.java sandbox/test.scala
==> sandbox/J.java <==
public class J {
   static final Object x = new Object();
}
==> sandbox/test.scala <==
class Test {
  def test(c: Option[AnyRef]): AnyRef = {
    c.getOrElse(J.x)
  }
}
```

I pushed a commit that pushed the check into `typeIsAny` except in the one place that doesn't make sense.
```

**Review by retronym — APPROVED** [review]
