### PR TITLE
Lint unset private[this] vars

### LINKED ISSUE #12515: Missing "consider using immutable val" for private[this] var
## reproduction steps

```scala
➜  scala -Xlint
Welcome to Scala 2.13.7 (OpenJDK 64-Bit Server VM, Java 17).
Type in expressions for evaluation. Or try :help.

scala> private var v = 0
                   ^
       warning: private var v in class $iw is never used

scala> private var v = 0 ; def f = v
                   ^
       warning: private var v in class $iw is never updated: consider using immutable val
def f: Int

scala> private[this] var v = 0
                         ^
       warning: private var v in class $iw is never used

scala> private[this] var v = 0 ; def f = v
def f: Int

scala>
```

## problem

I didn't expect to lose my linting.

Noticed at https://github.com/scala/scala/pull/9818#discussion_r767593728

### PR DESCRIPTION
**Pull request by joroKr21**
`private[this]` vars don't have setters except in traits, where both `isVar` and `isSetter` is true

Fixes scala/bug#12515 but there is still a limitation - no warning on vars without setters which are only updated

### CODE REVIEW

**Comment by som-snytt** [comment]
This will be interesting. Glance at validation failures are false pos.

**Comment by joroKr21** [comment]
I need to take a look, maybe go back to solving only the unset var issue and leave the set but not read for another time.

**Comment by som-snytt** [comment]
Ask and ye shall receive.

**Comment by SethTisue** [comment]
LGTM, but let's see what Som the warningsmeister has to say

**Comment by joroKr21** [comment]
@som-snytt if you want to add the other missing warning for local vars which are only updated but never read, feel free to take over this PR. I think they are marked as "used" when we traverse the LHS of `Assign` nodes. There's an even more difficult edge case for stuff like `x += 42` or even `x = someComplexExpression(x)` where the var is used only to update itself. Although I guess those could be side effecting so skipping them is expected.

**Comment by som-snytt** [comment]
I'll take a look today. I ran out of time or daylight yesterday, and I owe @joroKr21 my awake eyeballs.

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 1]
```diff
@@ -512,8 +512,8 @@ trait TypeDiagnostics extends splain.SplainDiagnostics {
     val params    = mutable.Set[Symbol]()
     val patvars   = mutable.Set[Symbol]()
 
-    def defnSymbols = defnTrees.toList map (_.symbol)
-    def localVars   = defnSymbols filter (t => t.isLocalToBlock && t.isVar)
+    def defnSymbols = defnTrees.iterator.map(_.symbol)
+    def varsWithoutSetters = defnSymbols.filter(t => t.isVar && !isExisting(t.setter))
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala]:
```suggestion
    def varsWithoutSetters = defnTrees.iterator.map(_.symbol).filter(t => t.isVar && !t.setter.exists)
```

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 2]
```diff
@@ -707,23 +707,15 @@ trait TypeDiagnostics extends splain.SplainDiagnostics {
           )
           val why = if (sym.isPrivate) "private" else "local"
           var cond = "is never used"
-          val what = (
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:710]: goodbye, paulparens!

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 3]
```diff
@@ -707,23 +707,15 @@ trait TypeDiagnostics extends splain.SplainDiagnostics {
...
-              sym.isVar
-                || sym.isGetter && (sym.accessed.isVar || (sym.owner.isTrait && !sym.hasFlag(STABLE)))
-            ) s"var ${sym.name.getterName.decoded}"
-            else if (
-              sym.isVal
-                || sym.isGetter && (sym.accessed.isVal || (sym.owner.isTrait && sym.hasFlag(STABLE)))
-                || sym.isLazy
-            ) s"val ${sym.name.decoded}"
-            else if (sym.isSetter) { cond = valAdvice ; s"var ${sym.name.getterName.decoded}" }
+            else if (sym.isSetter) { cond = valAdvice; s"var ${sym.name.getterName.decoded}" }
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala]: `x ; y` is a style reminder that semi is a separator, not a terminator. Also a reminder I'm not writing java. That may also be a paulpism.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala]:
```suggestion
            else if (sym.isSetter) { cond = valAdvice ; s"var ${sym.getterName.decoded}" }
```

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 4]
```diff
@@ -707,23 +707,15 @@ trait TypeDiagnostics extends splain.SplainDiagnostics {
...
+            else if (sym.isVar || sym.isGetter && sym.accessed.isVar) s"var ${sym.name.getterName.decoded}"
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala]:
```suggestion
            else if (sym.isVar || sym.isGetter && sym.accessed.isVar) s"var ${sym.getterName.decoded}"
```

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 5]
```diff
@@ -707,23 +707,15 @@ trait TypeDiagnostics extends splain.SplainDiagnostics {
...
           val why = if (sym.isPrivate) "private" else "local"
           var cond = "is never used"
-          val what = (
+          val what =
             if (sym.isDefaultGetter) "default argument"
             else if (sym.isConstructor) "constructor"
-            else if (
-              sym.isVar
-                || sym.isGetter && (sym.accessed.isVar || (sym.owner.isTrait && !sym.hasFlag(STABLE)))
-            ) s"var ${sym.name.getterName.decoded}"
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:716]: I guess it was trying to notice `x/x_=` pairs in traits? I would have to try it out.

**Review by som-snytt — APPROVED** [review]
Thanks, I would not have cracked this open again. Now I see eagerly built lists everywhere.

**Comment by som-snytt** [comment]
I think I noticed that to say `sym.setter` we need in `internal.Symbols`
```
+    // required because otherwise it's ambiguous with following deprecated method
+    override def setter: Symbol = super.setter
+
     @deprecated("use `setterIn` instead", "2.11.0")
     final def setter(base: Symbol, hasExpandedName: Boolean = needsExpandedSetterName): Symbol =
       setterIn(base, hasExpandedName)
```
Right, otherwise
```
src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:515:89: ambiguous reference to overloaded definition,
[error] both method setter in class Symbol of type (base: TypeDiagnostics.this.global.Symbol, hasExpandedName: Boolean): TypeDiagnostics.this.global.Symbol
[error] and  method setter in class SymbolContextApiImpl of type TypeDiagnostics.this.global.Symbol
[error] match expected type ?
[error]     def varsWithoutSetters = defnTrees.iterator.map(_.symbol).filter(t => t.isVar && !t.setter.exists)
[error]                                                                                         ^
[error] one error found
```
Spouse just sent child from table to pick up in her room, but we can't clean up old trash in `reflect`.

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala (hunk 5 above)
Comment (joroKr21) [reply src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:716]: It looked redundant to me. `isVar` is already defined as:
```scala
def isVar: Boolean = isField && !isLazy && isMutableVal
def isMutableVal = if (owner.isTrait) !hasFlag(STABLE) else isMutable
```

**Comment by joroKr21** [comment]
I don't know the history of `sym.setter` and I'd rather not get into it if I can avoid it 😄

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala (hunk 5 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:716]: also I only read the first comment afterward.

**Comment by som-snytt** [comment]
Just to clarify, no changes requested.

**Comment by joroKr21** [comment]
> Just to clarify, no changes requested.

Your comments make sense though, why not apply them?
I only won't touch `sym.setter` - I assume `getter` has the same problem.

**Review by SethTisue — APPROVED** [review]
I'm hitting approve, but perhaps @lrytz or another Lightbender would like to give the implementation a once-over before merge.

**Review by lrytz — APPROVED** [review]

**Comment by som-snytt** [comment]
> Your comments make sense though

I'm not accustomed to my comments making sense.
