### PR TITLE
Vector: Fix 2.13.2 performance regression: Restore special cases for small operands in {append,prepend}edAll

### LINKED ISSUE #12027: Scala 2.13.2 Vector prepending performance regression
I have a mature application currently running scala 2.13.1 and performing its daily task comfortably with `-Xmx4g` and taking about 30-60s. If I make the change to compile/run using 2.13.2 (with no other changes) and run, it goes out of memory (even when increased to `-Xmx16g`) after about 5 minutes of running. If I capture a stack trace when running (and when it throws an `OutOfMemoryError`), it looks like this:
```
04-Jun-2020 18:30:19:915: [stdout - STDOUT] [1]: java.lang.OutOfMemoryError: Java heap space
        at scala.collection.immutable.VectorBuilder.advance1(Vector.scala:1518)
        at scala.collection.immutable.VectorBuilder.advance(Vector.scala:1512)
        at scala.collection.immutable.VectorBuilder.addArr1(Vector.scala:1478)
        at scala.collection.immutable.VectorBuilder.$anonfun$addVector$1(Vector.scala:1492)
        at scala.collection.immutable.VectorBuilder.$anonfun$addVector$1$adapted(Vector.scala:1492)
        at scala.collection.immutable.VectorBuilder$$Lambda$810/0x000000080103f840.apply(Unknown Source)
        at scala.collection.immutable.VectorStatics$.foreachRec(Vector.scala:1794)
        at scala.collection.immutable.VectorStatics$.foreachRec(Vector.scala:1800)
        at scala.collection.immutable.VectorBuilder.addVector(Vector.scala:1800)
        at scala.collection.immutable.VectorBuilder.addAll(Vector.scala:1502)
        at scala.collection.immutable.Vector.appendedAll0(Vector.scala:211)
        at scala.collection.immutable.Vector1.appendedAll0(Vector.scala:394)
        at scala.collection.immutable.Vector.appendedAll(Vector.scala:199)
        at scala.collection.immutable.Vector.appendedAll(Vector.scala:113)
        at scala.collection.SeqOps.concat(Seq.scala:192)
        at scala.collection.SeqOps.concat$(Seq.scala:192)
        at scala.collection.AbstractSeq.concat(Seq.scala:1152)
        at scala.collection.IterableOps.$plus$plus(Iterable.scala:723)
        at scala.collection.IterableOps.$plus$plus$(Iterable.scala:723)
        at scala.collection.AbstractIterable.$plus$plus(Iterable.scala:920)
```
This is a single Vector being built up by repeatedly *prepending* Vectors which would typically be of size 1 and occasionally of size 2. There would be around 250_000 such vectors. 

**Here is the reproduction.**

**Scala 2.13.1**
```
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 13.0.3).
Type in expressions for evaluation. Or try :help.

scala> (1 to 1_000_000).foldLeft(Vector.empty[Int]) { (v, i) => Vector(i) ++ v }
res0: scala.collection.immutable.Vector[Int] = Vector(1000000, 999999, 999998, 999997, 999996, 999995, 999994, 999993, 999992, 999991, 999990, 999989, 999988, 999987, 999986, 999985...
```

**Scala 2.13.2**
```
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 13.0.3).
Type in expressions for evaluation. Or try :help.

scala> (1 to 1_000_000).foldLeft(Vector.empty[Int]) { (v, i) => Vector(i) ++ v }
<WAIT FOR A LONG TIME>
```

### PR DESCRIPTION
**Pull request by retronym**
Fixes scala/bug#12027

### CODE REVIEW

**Review by diesalbla — APPROVED** [review]

**Review by lrytz — APPROVED** [review]
Pushed a small cleanup.

File: src/library/scala/collection/immutable/Vector.scala [hunk 1]
```diff
@@ -191,14 +191,33 @@ sealed abstract class Vector[+A] private[immutable] (private[immutable] final va
...
 
   override final def appendedAll[B >: A](suffix: collection.IterableOnce[B]): Vector[B] = {
     val k = suffix.knownSize
     if(k == 0) this
     else appendedAll0(suffix, k)
   }
 
+  protected[this] def prependedAll0[B >: A](prefix: collection.IterableOnce[B], k: Int): Vector[B] = {
+    val tinyAppendLimit = 4 + vectorSliceCount
+    if (k < tinyAppendLimit /*|| k < (this.size >>> Log2ConcatFaster)*/) {
```
Comment (NthPortal) [inline src/library/scala/collection/immutable/Vector.scala:208]: incorrect assumption that `k` is positive

Comment (NthPortal) [reply src/library/scala/collection/immutable/Vector.scala:208]: I have no idea if this is the source of scala/bug#12564, but it might be
