### PR TITLE
Make `-release` more useful, deprecate `-target`, align with Scala 3

### LINKED ISSUE #12543: Align -release and -target with Scala 3
## reproduction steps

As proposed at https://github.com/lampepfl/dotty/pull/14606

## problem

Everything is easier when compiler options align on Scala2/3 especially for cross-compilers and migrators.

### PR DESCRIPTION
**Pull request by som-snytt**
## Why `-release`?

Use `-release` to specify the minimum JVM version that your code requires. This can be version 8 or higher, but is typically an LTS (Long Term Support) version such as `-release 8`, `-release 11`, or `-release 17`.

The compiler will compile your code with the Java standard library for the specified version, and it will output class files for that version (that is, that can only even be classloaded by that JVM version or higher).

Using `-release` allows you to decouple the JVM version on which your code is _built_ from the minimum JVM version on which it _runs_. For example, you might specify `-release 8` so your users are free to use 8, but you yourself can use 11 or 17 at build time (locally, or in CI).

## What has changed?

`-release` already existed in earlier Scala versions, but it only controlled the Java standard library version, not the bytecode version (which was controlled by `-target`).

The old `-target` option is now deprecated, because `-release` now includes `-target`'s behavior.

`-java-output-version` is now supported as an alias for `-release`.

## Motivation

Improves ergonomics and avoids accidental misuse, since now only `-release` is needed, whereas before two flags were needed.

Aligns `-release`s behavior on Scala 2 with its behavior on Scala 3.

Fixes scala/bug#12543.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala [hunk 1]
```diff
@@ -52,7 +51,26 @@ trait StandardScalaSettings { _: MutableSettings =>
...
   val print =          BooleanSetting ("-print", "Print program with Scala-specific features removed.") withAbbreviation "--print"
-  val target =         ChoiceSetting  ("-target", "target", "Target platform for object files.", AllTargetVersions, "8") withPreSetHook normalizeTarget _ withAbbreviation "--target"
+  val release =
+    ChoiceSetting("-release", "release", "Compile for a version of the Java API and target class file.", AllTargetVersions, normalizeTarget(javaSpecVersion))
+      .withPostSetHook { setting =>
+        val current = setting.value.toInt
+        if (!isJavaAtLeast("9") && current > 8) errorFn.apply("-release is only supported on JVM 9 and higher")
+        if (target.valueSetByUser.map(_.toInt > current).getOrElse(false)) errorFn("-release cannot be less than -target")
+        //target.value = setting.value  // this would trigger deprecation
+      }
```
Comment (prolativ) [inline src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:61]: There seems to be no check here preventing one from using e.g. `-release 17` when running the compiler on JDK 11

File: src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala [hunk 2]
```diff
@@ -52,7 +51,26 @@ trait StandardScalaSettings { _: MutableSettings =>
...
+      .withAbbreviation("--release")
+      .withAbbreviation("-java-output-version")
+  def releaseValue: Option[String] = release.valueSetByUser
+  val target =
+    ChoiceSetting("-target", "target", "Target platform for object files.", AllTargetVersions, "8")
+      .withPreSetHook(normalizeTarget)
+      .withPostSetHook { setting =>
+        if (releaseValue.map(_.toInt < setting.value.toInt).getOrElse(false)) errorFn("-release cannot be less than -target")
+      }
+      .withAbbreviation("--target")
```
Comment (prolativ) [inline src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:71]: Scala 3 uses `-Xunchecked-java-output-version`, `-Xtarget` and `--Xtarget`. As the first variant is currently preferred I think we should just add `-Xunchecked-java-output-version` here for compatibility without unnecessary confusion with the other aliases

File: src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala [hunk 3]
```diff
@@ -52,7 +51,26 @@ trait StandardScalaSettings { _: MutableSettings =>
   val nowarn =         BooleanSetting ("-nowarn", "Generate no warnings.") withAbbreviation "--no-warnings" withPostSetHook { s => if (s) maxwarns.value = 0 }
   val optimise:        BooleanSetting // depends on post hook which mutates other settings
   val print =          BooleanSetting ("-print", "Print program with Scala-specific features removed.") withAbbreviation "--print"
-  val target =         ChoiceSetting  ("-target", "target", "Target platform for object files.", AllTargetVersions, "8") withPreSetHook normalizeTarget _ withAbbreviation "--target"
+  val release =
+    ChoiceSetting("-release", "release", "Compile for a version of the Java API and target class file.", AllTargetVersions, normalizeTarget(javaSpecVersion))
+      .withPostSetHook { setting =>
+        val current = setting.value.toInt
+        if (!isJavaAtLeast("9") && current > 8) errorFn.apply("-release is only supported on JVM 9 and higher")
+        if (target.valueSetByUser.map(_.toInt > current).getOrElse(false)) errorFn("-release cannot be less than -target")
```
Comment (prolativ) [inline src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:59]: I think if `target` and `release` are both set then they should match exactly. If that's not  case, however, we should probably raise a warning rather than an error for compatibility with earlier compiler versions

File: src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:71]: I was reluctant to add the excessively long option names, but as aliases they don't spoil the `-help`.

File: src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala [hunk 4]
```diff
@@ -66,8 +84,14 @@ trait StandardScalaSettings { _: MutableSettings =>
   // Support passe prefixes of -target values:
   //   - `jvm-` (from back when we also had `msil`)
   //   - `1.` (from back when Java 2 was a possibility)
-  // `-target:1.jvm-13` is ridiculous, though.
-  private[this] def normalizeTarget(in: String): String = in.stripPrefix("jvm-").stripPrefix("1.")
+  private def normalizeTarget(in: String): String = {
+    val jvmish = raw"jvm-(\d*)".r
+    in match {
+      case "1.8" | "jvm-1.8" => "8"
```
Comment (prolativ) [inline src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:94]: I've just realized that we should also raise deprecation warnings for these first 2 cases as scala 3 accepts only bare numbers `8`, `9`, ...

File: src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala (hunk 3 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:59]: I gave this a bit of thought. They are adding features that are target-dependent, see the fun work by harpocrates, but not API-dependent. But probably there is no use case for release > target. I don't know how to warn from settings, but maybe it's OK to silently bump the target.

File: src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala (hunk 4 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:94]: They will find out quickly.

File: src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:61]: I think it can just build the "choices" correctly.

There's also a compatibility problem, current is `-release 8`, but choice accepts only `-release:8` for some reason. I think it is OK to fix choice processing to accept either form, which I will try.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:61]: Also thanks, now I see I forgot
`// TODO validate release <= java.specification.version`

**Comment by som-snytt** [comment]
The test is missing. It said `-release 8` which would have failed. It must be sitting on a different branch.

edit: https://github.com/scala/scala/pull/9981

**Comment by som-snytt** [comment]
I would like to take a moment to thank Travis for actually showing me the exception, looking at you, Jenkins.

`Caused by: java.lang.NumberFormatException: For input string: "1.8"`

oh, yeah.

**Comment by som-snytt** [comment]
oh right, that thing where CI settings differ from "home" settings even if I bootstrapped publishLocal etc etc etc.
```
[error] /home/travis/build/scala/scala/src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:103:38: match may not be exhaustive.

[error] It would fail on the following inputs: AnyScalaVersion, NoScalaVersion

[error]   val MaxTargetVersion = ScalaVersion(javaSpecVersion) match {
```

**Comment by som-snytt** [comment]
Re-rebuilt under 8 and confirmed `-help` shows
```
  -release:<release>           Compile for a version of the Java API and target class file. ([8])
```
and also compiled my 8-averse test file.

I wonder if "metaverse" is a contraction of "meta-averse"?

**Comment by som-snytt** [comment]
The glitch at 06d85a5
```
!!  1 - presentation/t12308                       [output differs]
% diff /home/jenkins/workspace/scala-2.13.x-validate-main/test/files/presentation/t12308.check /home/jenkins/workspace/scala-2.13.x-validate-main/test/files/presentation/t12308-presentation.log
@@ -46,5 +46,4 @@ askType at Foo.scala(4,37)
 [response] askTypeAt (4,37)
 1
 ================================================================================
-Problem(RangePosition(t12308/src/Foo.scala, 67, 67, 72),A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.,1)
-Problem(RangePosition(t12308/src/Foo.scala, 109, 109, 114),A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.,1)
```

**Comment by som-snytt** [comment]
That commit passes locally, so pushing rebase.

**Comment by dwijnand** [comment]
We might drop `-scala-output-version`, so let's wait on aligning things here.

**Comment by som-snytt** [comment]
Noting that the `-scala-output-version` is just an alias.

Edit: `-java-output-version`. The other option is not optionable on Scala 2.

**Comment by som-snytt** [comment]
Rebased and commented out the Scala 3 aliases so that there can be no objection to this PR.

**Comment by som-snytt** [comment]
@SethTisue I need this right now. OK to merge? I'm making partest compile `-release 8` if test file doesn't specify `javaVersion`. I was hoping to `-release:8`.

**Review by lrytz — APPROVED** [review]

**Comment by SethTisue** [comment]
@som-snytt can you write a good user-facing PR description here?

**Comment by som-snytt** [comment]
@SethTisue 🤞

**Comment by SethTisue** [comment]
@som-snytt thanks! I did a further round of revision and expansion — wdyt?

**Comment by som-snytt** [comment]
@SethTisue also 🤞 Sorry I am so lame, I wish I had the gift for all the things you do.

**Comment by SethTisue** [comment]
I'm helpless without someone else's draft to revise! No joke.

**Comment by som-snytt** [comment]
OK here's a draft 🍺

**Comment by xuwei-k** [comment]
- https://github.com/scala/bug/issues/12643 🤔

**Comment by He-Pin** [comment]
@som-snytt @SethTisue Will this been backport to 2.12.x? thanks.

**Comment by som-snytt** [comment]
@He-Pin Yes, but https://github.com/scala/scala/pull/10109

**Comment by He-Pin** [comment]
Thank you @som-snytt

File: src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala [hunk 5]
```diff
@@ -52,7 +51,29 @@ trait StandardScalaSettings { _: MutableSettings =>
...
+  val release =
+    ChoiceSetting("-release", "release", "Compile for a version of the Java API and target class file.", AllTargetVersions, normalizeTarget(javaSpecVersion))
+      .withPostSetHook { setting =>
+        val current = setting.value.toInt
+        if (!isJavaAtLeast("9") && current > 8) errorFn.apply("-release is only supported on JVM 9 and higher")
+        if (target.valueSetByUser.map(_.toInt > current).getOrElse(false)) errorFn("-release cannot be less than -target")
+        //target.value = setting.value  // this would trigger deprecation
+      }
+      .withAbbreviation("--release")
+      // .withAbbreviation("-java-output-version")
```
Comment (rtyley) [inline src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:63]: In Scala 3, [`-java-output-version` is the preferred flag name](https://github.com/lampepfl/dotty/pull/14606) (with the alias of `-release` still permitted) - would it be reasonable to uncomment this line, and allow Scala 2.13 to use `-java-output-version` as well?

Comment (SethTisue) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:63]: I believe we'd accept a PR that did that — at least I can't think why not

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:63]: Because the dotty project is really bad at choosing option names.

Comment (SethTisue) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:63]: (to be clear: not suggesting we make it canonical in Scala 2, just an accepted alternative)

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:63]: see also `-Xunchecked-java-output-version`. I didn't want to encourage them (the folks inventing these names). I came close to enabling them (the alt names) on this PR.

Comment (rtyley) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:63]: > I believe we'd accept a PR that did that — at least I can't think why not

Thanks! Opened with https://github.com/scala/scala/pull/10654.

> Because the dotty project is really bad at choosing option names.

This comment reminded me of my favourite video on software development, the 2012 talk by Andrew Dupont [_How to Argue About Code_](https://vimeo.com/53218578#t=477s) (sadly, as it's 'Not Yet Rated' on Vimeo, you have to login to view it in UK & EU, but at least after that there's no ads).

Regarding the option name, for myself, when I'm trying to help junior devs understand that if they want to run their code on Java 11, they need to specify `-java-output-version 11`, the conversation is a little easier than it is if I say `-release 11`. The first name, because it includes 'java', is more self-explanatory. The junior dev is _aware_ of Scala and Java, but doesn't automatically realise that when Scala says `-release`, it's referring to a Java-related concern.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala:63]: I'm revisiting the PR over why target was deprecated, and wanted to clarify that I was teasing about option names. This is all in the service of making it easy for people to compile stuff safely.
