### PR TITLE
No exhaustive warning for switchable cases

### LINKED ISSUE #12770: Exhaustive match checking doesn't work on strings
## Reproduction steps

Scala version: 2.13.10

compile the following with `scalac -Xlint Test.scala`
```scala
object Test {
  def doesntWarn(input: String) = input match {
    case "a" =>
    case "b" =>
  }
  def warns(input: String) = input match {
    case "b" =>
  }
}
```
The output is
```
Test.scala:8: warning: match may not be exhaustive.
It would fail on the following input: (x: String forSome x not in "b")
  def warns(input: String) = input match {
                             ^
1 warning
```

## Problem

There are two inexhaustive matches, there should be two warnings

Both `match` statements are clearly inexhaustive, but match statements on `String`s (or `Int`s or `Char`s and probably other things too) with two or more literal cases don't trigger a `match not may be exhaustive` warning.

Adding a third `case "c" if false =>` to `doesntWarn` results in an inexhaustive match warning and an unreachable code warning.

Adding just `case "c" =>` or `case other if other.isEmpty =>` (any condition will do as long as it's not a boolean literal, afaict) has no effect.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12770

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala [hunk 1]
```diff
@@ -650,6 +650,28 @@ trait MatchTreeMaking extends MatchCodeGen with Debugging {
       }
     }
 
+    private object Switchable {
+      val switchableTpe = Set(ByteTpe, ShortTpe, IntTpe, CharTpe, StringTpe)
```
Comment (dwijnand) [inline src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala:655]: LGTM how to fix this.  But could we dedupe/reuse the switchableTpe/SwitchablePattern/etc that's in RegularSwitchMaker?  We wouldn't want the logic to become askew.

**Review by dwijnand — CHANGES_REQUESTED** [review]

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala:655]: When I saw that the pieces are disjoint, I realized also that they are logically disjoint: that is, my first attempt was to use a `RSM` to judge switchability, though it would need a tweak and was not accessible. But it was cleaner just to squint and sketch a few lines of code. This code doesn't care whether the optimization is actually applied; for example, the judgment about how many cases are required happens in two places; and `SwitchMaker` is generally subtle and buried in the cake somewhere. I think in this case, local duplication is cleaner.

Have we punned on cake and mix-in as in "cake mix", the kind in a box from the grocery? Or was that an ingredient of the foundational pun of the cake pattern?

Comment (dwijnand) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala:655]: I think the pun was missed initially, as it went mixins -> layers -> cake.

Seems like a bit of code to have in common, so if it's too hard, let's at least have a common reference to one another, for future spelunkers - as in a comment.

**Review by dwijnand — APPROVED** [review]

**Comment by som-snytt** [comment]
@dwijnand thanks for the review!
