### PR TITLE
Increase laziness of #:: for LazyList

### LINKED ISSUE #11984: LazyList.isEmpty forces tail
I am trying to replace usages of the deprecated Stream with the recommended LazyList. But my code is now failing because it turns out that calling `isEmpty` on a LazyList actually forces the tail.

## reproduction steps

Compile and run this code with Scala 2.13.2:

```scala
object StreamTest {

  def main(args: Array[String]): Unit = {
    println(stream2.isEmpty)
    println(lazyList2.isEmpty)
  }

  def stream1: Stream[Int] = {
    println("stream1")
    Stream(1)
  }
  def stream2: Stream[Int] = 2 #:: stream1

  def lazyList1: LazyList[Int] = {
    println("lazyList1")
    LazyList(1)
  }
  def lazyList2: LazyList[Int] = 2 #:: lazyList1
}
```

## problem

The output is the following, which shows that the tail argument of the LazyList is called, which is not the case for Stream.

```
false
lazylist1
false
```

## expectation

I expect the behavior of LazyList to be at least as lazy as Stream.

### PR DESCRIPTION
**Pull request by NthPortal**
Change `#::` for `LazyList` so that the tail computation
is wrapped as a state computation for a new `LazyList`,
thus deferring its execution as long as possible.

Fixes scala/bug#11984

--------

Before (2.13.2-):

```scala
scala 2.13.2> 1 #:: { println("hey"); LazyList() }
val res4: scala.collection.immutable.LazyList[Int] = LazyList(<not computed>)

scala 2.13.2> res1.head
hey
val res5: Int = 1
```

After (2.13.3+):

```scala
scala 2.13.3> 1 #:: { println("hey"); LazyList() }
val res4: scala.collection.immutable.LazyList[Int] = LazyList(<not computed>)

scala 2.13.3> res1.head
val res5: Int = 1
```

### CODE REVIEW

**Comment by NthPortal** [comment]
Interestingly, `#:::` is already sufficiently lazy and doesn't need to be changed. I found it quite difficult to reason about this, however, and was only fully convinced of it after writing a test to prove it.

**Comment by som-snytt** [comment]
Nice!

File: test/junit/scala/collection/immutable/LazyListTest.scala [hunk 1]
```diff
@@ -163,7 +163,7 @@ class LazyListTest {
     cyc.tail.tail.head
     assertEquals("LazyList(1, 2, 3, <not computed>)", cyc.toString)
     cyc.tail.tail.tail.head
-    assertEquals("LazyList(1, 2, 3, 4, <cycle>)", cyc.toString)
+    assertEquals("LazyList(1, 2, 3, 4, <not computed>)", cyc.toString)
```
Comment (julienrf) [inline test/junit/scala/collection/immutable/LazyListTest.scala:166]: Could you also evaluate `cyc.tail.tail.tail.tail.head` and check that `toString` returns `"LazyList(1, 2, 3, 4, <cycle>)"`?

**Review by julienrf — APPROVED** [review]

**Review by sjrd — APPROVED** [review]

File: test/junit/scala/collection/immutable/LazyListTest.scala (hunk 1 above)
Comment (NthPortal) [reply test/junit/scala/collection/immutable/LazyListTest.scala:166]: sure!

Comment (NthPortal) [reply test/junit/scala/collection/immutable/LazyListTest.scala:166]: I believe that is immediately below

Comment (julienrf) [reply test/junit/scala/collection/immutable/LazyListTest.scala:166]: Haha, perfect, I didn’t see it!

**Comment by SethTisue** [comment]
@NthPortal should `LazyList.cons` have changed as well? see discussion at https://www.reddit.com/r/scala/comments/hgv8k3/lazylist_or_lazylistcons/

```
scala 2.13.3> 1 #:: { println("hey"); LazyList() }
val res4: scala.collection.immutable.LazyList[Int] = LazyList(<not computed>)

scala 2.13.3> res1.head
val res5: Int = 1

scala 2.13.3> LazyList.cons(1, { println("hey"); LazyList() })
val res6: scala.collection.immutable.LazyList[Int] = LazyList(<not computed>)

scala 2.13.3> res6.head
hey
val res7: Int = 1
```

**Comment by NthPortal** [comment]
yeah, probably :(

**Comment by NthPortal** [comment]
see #9095
