### PR TITLE
Parameter names are encoded

### LINKED ISSUE #12306: It is possible to set a parameter name to a method parameter that is illegal in Java
## reproduction steps

using Scala 2.13.4,

```scala
scala> case class Person(`user.id`: String)
class Person

scala> classOf[Person].getConstructors.head.getParameters.map(_.getName)
java.lang.reflect.MalformedParametersException: Invalid parameter name "user.id"
  at java.base/java.lang.reflect.Executable.verifyParameters(Executable.java:392)
  at java.base/java.lang.reflect.Executable.privateGetParameters(Executable.java:422)
  at java.base/java.lang.reflect.Executable.getParameters(Executable.java:363)
  ... 32 elided

scala> val p = Person(`user.id` = "ID1")
val p: Person = Person(ID1)
```

## problem

Parameter names containing dots are reasonable in Scala, but not in Java.

The method name of the accessor generated from the parameter is converted to an appropriate method name in Java and stored in the bytecode, but the parameter name is stored as is.

When the parameter name is accessed via Java reflection, an exception will be thrown due to the presence of invalid characters.

However, the accessor method works properly.

This check has been introduced in the following Java commit.

https://github.com/openjdk/jdk/commit/367fa5ac0ee697dd6afb71fe7f860d7719199146

---

It might be more appropriate to warn about the behavior of Scala 2, when defining methods.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12306

### CODE REVIEW

File: src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala [hunk 1]
```diff
@@ -631,7 +631,7 @@ abstract class BCodeHelpers extends BCodeIdiomatic {
         var access = asm.Opcodes.ACC_FINAL
         if (param.isArtifact)
           access |= asm.Opcodes.ACC_SYNTHETIC
-        jmethod.visitParameter(param.name.decoded, access)
+        jmethod.visitParameter(param.name.encoded, access)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala:634]: 👍

Scala's name encoding keeps `isJavaIdentifierPart` characters, so there should not be any drawback in Java interop for legal Java identifiers.

**Review by lrytz — APPROVED** [review]

**Comment by som-snytt** [comment]
Documenting here that, as seen in the test, underscore is not encoded but is now an illegal ident in Java.
