### PR TITLE
Extend the Gradle / sbt 0.13 leniency to Windows

### LINKED ISSUE #11731: Scala 2.13 does not compile with Gradle on Windows
The [original bug](https://github.com/gradle/gradle/issues/9857) is reported in the Gradle repository, but I believe it should be brought into attention in this repository as well.

## steps

Use Gradle to compile Scala 2.13.0 project.

## problem

```
Compiling with Zinc Scala compiler.
'compiler-interface-2.13.0-55.0.jar' not yet compiled for Scala 2.13.0. Compiling...
C:\Users\petzold\AppData\Local\Temp\sbt_76a43d36\xsbt\Compat.scala:152: error: postfix operator headOption needs to be enabled
by making the implicit value scala.language.postfixOps visible.
This can be achieved by adding the import clause 'import scala.language.postfixOps'
or by setting the compiler option -language:postfixOps.
See the Scaladoc for value scala.language.postfixOps for a discussion
why the feature needs to be explicitly enabled.
} headOption
^
one error found
```

## expectation

compiles.

## notes

As I described in one of the comments on the original issue, I suspect that [this Scala change](https://github.com/scala/scala/pull/6559) is responsible for Gradle's inability to compile Scala 2.13, as this change makes Scala 2.13 incompatible with SBT 0.13.15, which is what Gradle uses for compilation.

Perhaps all it takes is to build and publish the [old Zinc project](https://github.com/typesafehub/zinc) with SBT 0.13.18. I was able to do it locally, but I can't really be sure I've done it properly as I'm quite unfamiliar with this project.

Furthermore, there might be other Scala 2.13 changes which are incompatible with SBT 0.13.18.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/scala/bug/issues/11731

postfixOps error exempts `/xsbt/Compat.scala` specifically to allow sbt 0.13 to work
with Scala 2.13.0. Because this uses forward slash, apparently this did not work on Windows. This extends the compassion to Gradle + Windows users.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/Reporting.scala [hunk 1]
```diff
@@ -115,7 +115,9 @@ trait Reporting extends scala.reflect.internal.Reporting { self: ast.Positions w
       val msg = s"$featureDesc $req be enabled\nby making the implicit value $fqname visible.$explain" replace ("#", construct)
       // don't error on postfix in pre-0.13.18 xsbt/Compat.scala
       def isSbtCompat =
-        (featureName == "postfixOps" && pos.source.path.endsWith("/xsbt/Compat.scala") && Thread.currentThread.getStackTrace.exists(_.getClassName.startsWith("sbt.")))
+        (featureName == "postfixOps" &&
+        (pos.source.path.endsWith("/xsbt/Compat.scala") || pos.source.path.endsWith("""\xsbt\Compat.scala""")) &&
```
Comment (eed3si9n) [inline src/compiler/scala/tools/nsc/Reporting.scala:119]: I thought about converting this to URL etc to make `/` and `\` checking more elegant, but in the end figured doing the String#endsWith twice would be cheaper.

Comment (SimY4) [reply src/compiler/scala/tools/nsc/Reporting.scala:119]: You can also use `java.io.File.pathSeparator` in the cross-platform project setup.

Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/Reporting.scala:119]: You mean `java.io.File.separator` I assume. I'm not sure how Cygwin etc interacts on Windows in that regard.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/Reporting.scala]: I used the manly reflect.io abstraction in combination with java.io. It's part of my regime to get back into shape before the company health expo at the end of October. BTW, last time I watched "Rocky", I noticed that he had six weeks to train. No, not "Rocky and Bullwinkle."

**Comment by som-snytt** [comment]
You use words such as "compassion" and "leniency" when I feel that WIndows deserves nothing but the extremest of sanctions. OK, I could go for compassion for the hapless Windows users. I went to church yesterday after a yearlong lapse; probably I am preconditioned for some agape.
