### PR TITLE
Dealias val aliases to modules so they're =:=

### LINKED ISSUE #12186: Incorrect exhaustiveness warning when pattern matching on Nil.type
## reproduction steps

using Scala 2.13.4-20201011-114304-1c1fa0c (equivalent roughly to HEAD a few days ago)

```scala
scala> def test(list: List[Int]): Boolean = list match {
     |   case h :: t => true
     |   case _: Nil.type => false
     | }
                                            ^
       warning: match may not be exhaustive.
       It would fail on the following input: Nil
def test(list: List[Int]): Boolean

scala> test(Nil)
val res0: Boolean = false

scala> def test(list: List[Int]): Boolean = list match {
     |   case h :: t => true
     |   case _: scala.collection.immutable.Nil.type => false
     | }
def test(list: List[Int]): Boolean
```

## problem

`Nil.type` is the type of `Nil`, so the match is exhaustive.

In 2.13.3, the same code does not raise an exhaustiveness warning.

Note: it only warns if you use the value alias of `Nil` (from the `scala` package, but presumably any value alias as well), and does not warn if you use the fully qualified type.

### PR DESCRIPTION
**Pull request by dwijnand**
This changes the definition of `=:=` in the smallest possible way:
if you have a singleton type that widens to a module,
then widen to that module.

Fixes scala/bug#12186.

### CODE REVIEW

**Comment by lrytz** [comment]
Here's an example. In 2.13.3:

```scala
scala> :power
scala> import reflect.internal.util.{shortClassOfInstance => c}

scala> object O; val x: O.type = O
object O
val x: O.type = O$@1545b9da

scala> val oSingle = typeOf[O.type]; println(c(oSingle))
UniqueSingleType
val oSingle: $r.intp.global.Type = O.type

scala> val oModule = oSingle.underlying; println(c(oModule))
ModuleTypeRef
val oModule: $r.intp.global.Type = O.type

scala> val xSingle = typeOf[x.type]; println(c(xSingle))
UniqueSingleType
val xSingle: $r.intp.global.Type = x.type

scala> xSingle =:= oSingle
val res3: Boolean = true

scala> xSingle =:= oModule
val res4: Boolean = false
```

This PR fixes the last line.

**Comment by retronym** [comment]
We should unit test this by adding some test cases to https://github.com/scala/scala/blob/33478bdc9792ee13baa8208e326278695b1bd4e4/test/junit/scala/reflect/internal/TypesTest.scala#L39

See the previous tweaks to `normalizePlus` that I test drive with that test: https://github.com/scala/scala/commit/6f8c05722ba4452279e353df2d81b58f260277d2

**Comment by retronym** [comment]
e.g. 

```diff
diff --git a/test/junit/scala/reflect/internal/TypesTest.scala b/test/junit/scala/reflect/internal/TypesTest.scala
index ab0cdd954e..fc30775b4a 100644
--- a/test/junit/scala/reflect/internal/TypesTest.scala
+++ b/test/junit/scala/reflect/internal/TypesTest.scala
@@ -46,9 +46,15 @@ class TypesTest {
     val tp1 = TypeRef(ThisType(EmptyPackageClass), moduleClass, Nil)
     val tp2 = SingleType(ThisType(EmptyPackageClass), module)
     val tp3 = ThisType(moduleClass)
-    val tps = List(tp1, tp2, tp3)
+
+    val (otherModule, otherModuleClass) = EmptyPackageClass.newModuleAndClassSymbol(TermName("Other"), NoPosition, 0L)
+    val aliasSym = otherModuleClass.newTermSymbol(TermName("alias")).setInfo(tp2)
+    val tp4 = singleType(TypeRef(ThisType(EmptyPackageClass), otherModuleClass, Nil), aliasSym)
+
+
+    val tps = List(tp1, tp2, tp3, tp4)
     val results = mutable.Buffer[String]()
-    tps.permutations.foreach {
+    tps.combinations(3).foreach {
       case ts @ List(a, b, c) =>
         def tsShownRaw = ts.map(t => showRaw(t)).mkString(", ")
         if (a <:< b && b <:< c && !(a <:< c)) results += s"<:< intransitive: $tsShownRaw"

```

**Comment by dwijnand** [comment]
Thanks, Jason.  I was getting some detail there wrong so I was struggling.  Yours works very well, failing without the patch.

File: test/junit/scala/reflect/internal/TypesTest.scala [hunk 1]
```diff
@@ -61,6 +66,20 @@ class TypesTest {
     }
   }
 
+  @Test
+  def testNilModuleUnification(): Unit = {
+    import rootMirror.RootClass
+    val nil1 = singleType(ThisType(RootClass), typeOf[scala.`package`.type].member(TermName("Nil")))
+    val nil2 = typeOf[scala.collection.immutable.Nil.type]
```
Comment (lrytz) [inline test/junit/scala/reflect/internal/TypesTest.scala]: this is a `UniqueSingleType` (at least in the repl) not a `ModuleTypeRef`, so probably this test was passing already before your fix?

Comment (dwijnand) [reply test/junit/scala/reflect/internal/TypesTest.scala]: Ah, yeah, I'd noticed that and then forgotten about it.  Good catch - fixed.

**Comment by dwijnand** [comment]
Briefly touched on this one with Adriaan and he said he agrees that `scala.Nil.type` shouldn't be different to `scala.collection.immutable.Nil.type`.  Any chance we can merge this?

**Review by lrytz — APPROVED** [review]
