### PR TITLE
Avoid exception in post-typer checks

### LINKED ISSUE #12726: ConcurrentModificationException in the compiler
Now this is something I haven't seen. `StackOverflowError` sure, half a dozen a day, I can understand them. But this?
```
java.util.ConcurrentModificationException: mutation occurred during iteration
	at scala.collection.mutable.MutationTracker$.checkMutations(MutationTracker.scala:43)
	at scala.collection.mutable.MutationTracker$CheckedIterator.hasNext(MutationTracker.scala:59)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:120)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:106)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1530)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1514)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1506)
	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1619)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
	at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
```
I haven't a faintest idea in what class, file or even package this happens, so I have no points of extracting it. Maybe it will tell something to someone. Any ideas of how to look for clues? I have about every logging option enabled which doesn't throw an `AssertionError`, or `NullPointerException` itself. Unfortunately, the last line from `-Xprint:0-100` seems to be from a successfully processed file (I got a summary of warnings for the file), so I am at a loss.

### PR DESCRIPTION
**Pull request by som-snytt**
"Post-typer" checks which in turn registered more checks would throw an exception.

The example from the ticket was a refinement that also required a feature check.

This commit allows arbitrary checks.

Fixes scala/bug#12726

### CODE REVIEW

**Comment by som-snytt** [comment]
TIL `typedRefinement` was the original use case for deferred checks (Jan 2009). I idly wonder where that happens in dotty.

`recheckFruitless` which may fall under checks which should possibly occur post-erasure.

`nullary overrides nilary` check in Namers, which requires consulting overrides. Attachment used in refchecks.

Delay `setError` in namer, scala/bug#10748

infer feature trait (maybe the 2nd deferred check)

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 1]
```diff
@@ -3225,20 +3232,24 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
...
-        for (stat <- stats1 if stat.isDef && stat.symbol.isOverridingSymbol)
-          stat.symbol setFlag OVERRIDE
-      })
+      if (!stats.isEmpty) {
+        namer.enterSyms(stats)
+
+        // need to delay rest of typedRefinement to avoid cyclic reference errors
+        debuglog(s"deferred typed refinement $stats")
+        unit.addPostUnitCheck(() => {
+          //debuglog(s"deferred typed refinement $stats")
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: delete me

File: test/files/neg/t5429.check [hunk 2]
```diff
@@ -1,9 +1,3 @@
-t5429.scala:68: warning: method without a parameter list overrides a method with a single empty one
```
Comment (som-snytt) [inline test/files/neg/t5429.check]: hidden now by missing `override` error

File: test/files/neg/nullary-override-3b.check [hunk 3]
```diff
@@ -1,7 +1,9 @@
 nullary-override-3b.scala:6: error: method without a parameter list overrides a method with a single empty one
+def x(): Int (defined in class P)
```
Comment (som-snytt) [inline test/files/neg/nullary-override-3b.check]: Now same reporting style as in `nullary-override-3a` for the converse case.

File: src/compiler/scala/tools/nsc/typechecker/Checkable.scala [hunk 4]
```diff
@@ -371,6 +371,7 @@ trait Checkable {
               val Xsym = X.typeSymbol
               val Psym = P.typeSymbol
               if (isSealedOrFinal(Xsym) && isSealedOrFinal(Psym) && (currentRun.compiles(Xsym) || currentRun.compiles(Psym)))
+                debuglog(s"deferred recheckFruitless($X, $P)")
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Checkable.scala]: typo implies test is not complete, or is the check merely redundant?

**Comment by SethTisue** [comment]
Mind updating the PR title and description to give a user-facing view of the changes?

**Comment by noresttherein** [comment]
I don't know if you deleted my comments because I violated some rules, or if the conversation happened elsewhere, but I have a commit which causes infinite recursion in the compiler in this branch. Granted, it is very likely because both `2.13.10` release and current `2.13.x` branch crash with the exception which this issue is about and simply don't reach that point. No, I have no idea how to reproduce it in a snippet. It seems to happen however in the smallest and simplest file in the whole project, so I don't have much to go on. Since the last conversation, I fixed all other errors reported by the compiler in my project, so if anyone is interested in reproducing, it will be a bit more user-friendly.

**Comment by SethTisue** [comment]
Hmm, I don't recall deleting any comments

**Comment by SethTisue** [comment]
I don't recall deleting any comments. (That rarely happens at all, unless something is really egregious.)

There's discussion on https://github.com/scala/bug/issues/12726 , is that what you're referring to?

**Comment by som-snytt** [comment]
@noresttherein comment removal is always reflected in history on the page, I think. I remember I tried a project, but I've got brain fuzz from a fever, so I'll have to try it again.

This PR also has debug for when extra checks are not run (or is it an error). I have not yet concocted a test for a post-typer check that in turn incurs a post-typer check.

**Comment by noresttherein** [comment]
@SethTisue I remember that and one minor comment on my part which didn't bring much was removed, but then I also talked with @som-snytt about the *next* bug in my project and I don't know where. If you tell me to test against some particular branch, so this commit can be freed from any suspicion, please let me know. If I can do anything that would interest someone or help me diagnose the issue, I'd love to know, too. Sadly, extracting it is beyond me.

**Comment by noresttherein** [comment]
Ok, this commit [https://github.com/noresttherein/oldsql/commit/d0257976551d70561fafede4331384127a3fe4bd](commit) (in my project, sorry, no luck) fixed the issue. The types of the implicit parameters were too difficult, and the compiler got lost. It was persistent at that, I'll give it that.

**Comment by som-snytt** [comment]
@noresttherein Great! I added more info on the ticket, including details tag for stack traces.

File: src/compiler/scala/tools/nsc/typechecker/Analyzer.scala [hunk 5]
```diff
@@ -111,7 +111,11 @@ trait Analyzer extends AnyRef
           undoLog.clear()
         }
         finishComputeParamAlias()
-        for (work <- toCheckAfterTyper) work()
+        val afterWork = toCheckAfterTyper.toList
+        toCheckAfterTyper.clear()
+        for (work <- afterWork) work()
+        if (toCheckAfterTyper.nonEmpty)
+          reporter.error(NoPosition, s"${toCheckAfterTyper.size} spurious post-typer actions")
         toCheckAfterTyper.clear()
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Analyzer.scala]: no longer needed?

File: src/compiler/scala/tools/nsc/typechecker/Analyzer.scala [hunk 6]
```diff
@@ -111,7 +111,11 @@ trait Analyzer extends AnyRef
           undoLog.clear()
         }
         finishComputeParamAlias()
-        for (work <- toCheckAfterTyper) work()
+        val afterWork = toCheckAfterTyper.toList
+        toCheckAfterTyper.clear()
+        for (work <- afterWork) work()
+        if (toCheckAfterTyper.nonEmpty)
+          reporter.error(NoPosition, s"${toCheckAfterTyper.size} spurious post-typer actions")
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Analyzer.scala]: IIUC, where before the compiler crashed with a ConcurrentModificationException, now it would report an error?

Can this happen due to a bug in the build tool that invokes the compiler? Does the new error help identifying that bug?

**Comment by SethTisue** [comment]
scala/bug#12726 is about `ConcurrentModificationException`s in the compiler, but the PR title and description here seem to be about something else? How are these two strands of work related?

File: src/compiler/scala/tools/nsc/typechecker/Analyzer.scala (hunk 6 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Analyzer.scala]: I don't think I nailed down the root cause. I intended to find "post-typer checks" that could add more "post-typer checks".

I don't know if CME would be intermittent or if checks could get dropped.

I also intended at that point to experiment with looping N times.

**Comment by som-snytt** [comment]
For `sealed`, I tried running java completions in post-typer checks and
```
Crashed running test pos/t11525a: java.util.ConcurrentModificationException: mutation occurred during iteration
Crashed running test pos/t9111-inliner-workaround: java.util.ConcurrentModificationException: mutation occurred during iteration
?! 2 - pos/t9111-inliner-workaround              [caught ConcurrentModificationException - mutation occurred during iteration]
?! 1 - pos/t11525a                               [caught ConcurrentModificationException - mutation occurred during iteration]
```
so I will get a clearer picture tomorrow.

(That was just completer on one java class adding a check to complete another java class.)

**Comment by som-snytt** [comment]
Moved the supplementary commits to individual PRs because we provide individualized service.

This PR just uses `ArrayDeque` instead of `ListBuffer` for simplicity.

In this form, there is no check that checks don't produce more checks ad infinitum.

I verified that `oldsql` test completes with compilation errors.

Forgot to `partest --realeasy`.

**Review by lrytz — APPROVED** [review]
Thank you!
