### PR TITLE
Disable event expansion in REPL JLine reader

### LINKED ISSUE #11922: raw-interpolator escapes backslashes in REPL
## reproduction steps

```scala
Welcome to Scala 2.13.2-pre-bc1cad4 (OpenJDK 64-Bit Server VM, Java 1.8.0_232).

scala> raw"\n".toArray
```

## problem

```scala
scala> raw"\n".toArray
val res0: Array[Char] = Array(n)
```

## expectation

```scala
scala> raw"\n".toArray
res0: Array[Char] = Array(\, n)
```

### PR DESCRIPTION
**Pull request by retronym**
Our ReplTest-s disable JLine so only manual testing discovered
that:

```
scala> raw"\n".toArray
val res0: Array[Char] = Array(n)
```

Now, we're back to:

```
scala> raw"\n".toArray
res0: Array[Char] = Array(\, n)
```

Fixes scala/bug#11922

### CODE REVIEW

**Comment by som-snytt** [comment]
Was https://github.com/scala/scala/pull/2740

File: src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala [hunk 1]
```diff
@@ -14,15 +14,13 @@ package scala.tools.nsc.interpreter
...
-  Candidate, Completer, CompletingParsedLine,
-  EndOfFileException, UserInterruptException, EOFError,
-  History, LineReader, ParsedLine, Parser}, Parser.ParseContext
+import org.jline.reader.{Candidate, Completer, CompletingParsedLine, EOFError, EndOfFileException, History, LineReader, ParsedLine, Parser, UserInterruptException}
+import Parser.ParseContext
 import org.jline.reader.impl.DefaultParser
-
 import java.util.{List => JList}
 
+import org.jline.reader.LineReader.Option
```
Comment (som-snytt) [inline src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala:22]: unused import
