### PR TITLE
Fix prefixAligns, avoid spurious outer test warnings on patdep types

### LINKED ISSUE #12398: Path-dependent type on singleton value emits spurious outer test warnings
## reproduction steps

using Scala 2.13.6,

```scala
object AnnotationTools {
  def getAllTypeAnnotations(u: Universe)(typ: u.Type): List[u.Annotation] = {
    typ.finalResultType.dealias match {
      case t: u.AnnotatedTypeApi =>
        t.annotations
      case _ =>
        Nil
    }
  }
}
```

## problem

Results in a warning:

```
/izumi/fundamentals/fundamentals-reflection/src/main/scala/izumi/fundamentals/reflection/AnnotationTools.scala:16:12
The outer reference in this type test cannot be checked at run time.
      case t: u.AnnotatedTypeApi =>
```

When decompiled, the warning is true, the outer reference is in fact not checked:

```java
   public List getAllTypeAnnotations(final Universe u, final TypeApi typ) {
      TypeApi var6 = .MODULE$.stripByName(u, typ.finalResultType().dealias());
      Object var3;
      if (var6 instanceof AnnotatedTypeApi && true) {
         var3 = ((AnnotatedTypeApi)var6).annotations();
      } else {
         var3 = scala.package..MODULE$.Nil();
      }

      return (List)var3;
   }
```

However, since `u.` is a literal prefix of `AnnotatedTypeApi`, is it not supposed to be checkable at runtime?

### clarification

I've submitted this report assuming the new warning in 2.13.6 was incorrect and the type prefix was checked. On decompiling I found the warning is correct, and the behavior of all previous Scala versions was incorrect – they did not check the prefix AND did not issue the warning. So I rewrote the report to complain about lack of runtime type prefix comparison; 🤦
I am not sure if the behavior is incorrect, although from a language perspective it would seem that the implementation should always be able to compare prefixes when they are present syntactically in the type.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes https://github.com/scala/bug/issues/12398

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala [hunk 1]
```diff
@@ -393,8 +393,13 @@ trait MatchTreeMaking extends MatchCodeGen with Debugging {
...
                     false
                   case TypeRef(pre, sym, args) =>
-                    val testedBinderClass = testedBinder.info.upperBound.typeSymbol
+                    val testedBinderUpper = testedBinder.info.upperBound
                     // alternatively..... = testedBinder.info.baseClasses.find(_.isClass).getOrElse(NoSymbol)
+                    val testedBinderUpperBound = testedBinderUpper match { // shed an empty (useless?) refinement
+                      case RefinedType(List(AnyRefTpe, parent), Scope()) => parent
+                      case _                                             => testedBinderUpper
+                    }
+                    val testedBinderClass = testedBinderUpperBound.typeSymbol
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala]: Maybe we can go back to the commented suggestion?

```
testedBinder.info.baseClasses.find(sym => sym.isClass && !sym.isRefinementClass)
```
