### PR TITLE
Prevent table length from integer overflow.

### LINKED ISSUE #12076: mutable.HashMap#growTable is broken
`mutable.HashMap#growTable` is broken (it does not handle integer overflow, computes a threshold value but never uses it). `growTable` is called with `length * 2` (see https://github.com/scala/scala/pull/9101#discussion_r450029320), and without overflow checks, something will go wrong. Unfortunately, it's difficult to say what the actual failure mode is, as creating a `HashMap` that big uses a tremendous amount of memory, and I cannot do it on my system.

### PR DESCRIPTION
**Pull request by RadoBuransky**
~~Related to~~ Fixes scala/bug#12076

### CODE REVIEW

**Review by lrytz — COMMENTED** [review]
LGTM; not entirely sure about `BufferOverflowException` though.

File: src/library/scala/collection/mutable/HashMap.scala [hunk 1]
```diff
@@ -358,7 +360,10 @@ class HashMap[K, V](initialCapacity: Int, loadFactor: Double)
     s.asInstanceOf[S with EfficientSplit]
   }
 
-  private[this] def growTable(newlen: Int) = {
+  private[this] def growTable(newlenLong: Long) = {
+    if (newlenLong > Int.MaxValue)
+      throw new BufferOverflowException()
```
Comment (NthPortal) [inline src/library/scala/collection/mutable/HashMap.scala]: I'm not sure exactly what exception should be thrown, but I don't think it should be this one, which has to do with I/O. Perhaps an `IllegalStateException` with the message `"new HashMap table size exceeds maximum"`, or perhaps just a `RuntimeException`.

File: src/library/scala/collection/mutable/HashMap.scala [hunk 2]
```diff
@@ -358,7 +360,10 @@ class HashMap[K, V](initialCapacity: Int, loadFactor: Double)
     s.asInstanceOf[S with EfficientSplit]
   }
 
-  private[this] def growTable(newlen: Int) = {
+  private[this] def growTable(newlenLong: Long) = {
```
Comment (NthPortal) [inline src/library/scala/collection/mutable/HashMap.scala]: we could probably just leave it as an `Int` and check if it is negative (and assume it has overflowed). if this were being called for every action, I would be concerned about potentially unnecessary conversions, but as it is only called when growing the table, and as that action is already quite expensive, I don't think it has a meaningful performance cost. I'm happy with either the way it is, or checking if it's a negative `Int`; whichever folks think is clearer.

File: src/library/scala/collection/mutable/HashMap.scala [hunk 3]
```diff
@@ -358,7 +360,10 @@ class HashMap[K, V](initialCapacity: Int, loadFactor: Double)
...
+    if (newlenLong > Int.MaxValue)
+      throw new BufferOverflowException()
+    val newlen = newlenLong.toInt
     var oldlen = table.length
     threshold = newThreshold(newlen)
```
Comment (NthPortal) [inline src/library/scala/collection/mutable/HashMap.scala:365]: while this PR does address the overflow problem (and I think that is sufficiently valuable to move this PR forward), it still does not address one of the concerns in the linked issue - namely that we compute some `threshold` value here but never use it. I think it is important to investigate and determine the original intention of computing `threshold`/calling `newThreshold`, and clean up the method accordingly.

consequently, I don't think we should say that this PR fixes the issue (especially because GitHub will then automatically close the issue), but rather that it partially addresses the issue.

**Review by NthPortal — CHANGES_REQUESTED** [review]
I'm sorry it's taken me so long to review this. I think once the exception is changed (and I'm open to ideas of other appropriate exceptions), and the description tweaked, this is good to merge.

File: src/library/scala/collection/mutable/HashMap.scala (hunk 3 above)
Comment (RadoBuransky) [reply src/library/scala/collection/mutable/HashMap.scala:365]: I've fixed the comment which said that this PR fixes the issue. I'll try to address the problem with `threshold` separately.

File: src/library/scala/collection/mutable/HashMap.scala (hunk 2 above)
Comment (RadoBuransky) [reply src/library/scala/collection/mutable/HashMap.scala]: I followed your recommendation and switched back to `Int`. Thanks

File: src/library/scala/collection/mutable/HashMap.scala (hunk 1 above)
Comment (RadoBuransky) [reply src/library/scala/collection/mutable/HashMap.scala]: Yeah, right. Done.

**Review by NthPortal — APPROVED** [review]

File: src/library/scala/collection/mutable/HashMap.scala (hunk 3 above)
Comment (Ichoran) [reply src/library/scala/collection/mutable/HashMap.scala:365]: Huh?  I don't understand the comment.  `threshold` is used all over the code to determine when it's time to grow again.

You might want to special-case it for being unable to grow (e.g. make it bigger), but it's used in every method that creates a new entry.

Comment (NthPortal) [reply src/library/scala/collection/mutable/HashMap.scala:365]: my mistake. I missed the fact that it's not a local `var`/`val`

**Comment by SethTisue** [comment]
fixes https://github.com/scala/bug/issues/12076 after all
