### PR TITLE
Maintain iteration order in SetOps.--

### LINKED ISSUE #12580: LinkedHashSet ordering broken in 2.13
## Reproduction steps

```scala
import scala.collection.mutable
val res = mutable.LinkedHashSet(1, 2, 3, 4, 5, 6) -- Set(2, 4)
println(res)
```

In Scala 2.12 you get (https://scastie.scala-lang.org/yLA5K8bYTIySDhRiwFFhTQ):
```
Set(1, 3, 5, 6)
```

In Scala 2.13 (tried 2.13.8 and 2.13.0) you get (https://scastie.scala-lang.org/jELVkBT1QDKV37m22vknRA):
```
LinkedHashSet(5, 1, 6, 3)
```

## Problem

I would expect the order to be maintained.

h/t @SethTisue for answering my questions and helping me minimize the issue.

### PR DESCRIPTION
**Pull request by lrytz**
Fixes https://github.com/scala/bug/issues/12580

### CODE REVIEW

File: test/scalacheck/scala/collection/mutable/LinkedHashMapProperties.scala [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package scala.collection.mutable
+
+import org.scalacheck.Prop._
+import org.scalacheck.Properties
+
+import scala.annotation.nowarn
+
+object LinkedHashMapProperties extends Properties("mutable.HashSet") {
```
Comment (som-snytt) [inline test/scalacheck/scala/collection/mutable/LinkedHashMapProperties.scala]: `s/Set/Map`

**Review by som-snytt — APPROVED** [review]
Quite orderly.
