### PR TITLE
Fixed updateWith so that the table grows when new value is added

### LINKED ISSUE #12069: mutable.HashMap doesn't grow when values are added with updateWith
## reproduction steps

using Scala 2.13.3,

```scala
scala> 
import java.util.UUID
import scala.collection.mutable

def updateWithBenchmark(): Unit = {

    val k = 10000000
    val s = 10000

    val map = mutable.HashMap.empty[UUID, UUID]

    val ts = System.currentTimeMillis()

    for(n <- 1 to k) {
      if(n % s == 0) println(s"$n/$k")
      val x = UUID.randomUUID()
      val v = UUID.randomUUID()
        map.updateWith(x) {
            case None => Some(UUID.randomUUID)
            case Some(s) => Some(UUID.randomUUID)
        }
    }

    println(s"mutable.HashMap.updateWith: ${System.currentTimeMillis() - ts} millis")
}

updateWithBenchmark()
```

## problem

Running above code shows a significant performance drop since map's underlying hash table is not growing after reaching threshold.

### PR DESCRIPTION
**Pull request by mwielocha**
Fixes https://github.com/scala/bug/issues/12069

I'd love to add a test but this affects HasMap's internals so not sure how to proceed with that.

### CODE REVIEW

**Comment by mwielocha** [comment]
On second thought the table growth should be before computing the index... @lihaoyi maybe you have a suggestion?

File: src/library/scala/collection/mutable/HashMap.scala [hunk 1]
```diff
@@ -161,7 +161,9 @@ class HashMap[K, V](initialCapacity: Int, loadFactor: Double)
           else table(indexedHash) = foundNode.next
           contentSize -= 1
 
-        case (None, Some(value)) => put0(key, value, false, hash, indexedHash)
+        case (None, Some(value)) =>
+          if(contentSize + 1 >= threshold) growTable(table.length * 2)
+          put0(key, value, false, hash, indexedHash)
```
Comment (Jasper-M) [inline src/library/scala/collection/mutable/HashMap.scala]: Isn't `indexedHash` invalidated once you grow the table?

Comment (mwielocha) [reply src/library/scala/collection/mutable/HashMap.scala]: Yeah, just noticed that.

Comment (mwielocha) [reply src/library/scala/collection/mutable/HashMap.scala]: So it's not possible to never re-compute the hash. If we're at the threshold the implementation pretty much falls back to the original one. Anyway, this could also just call `put0` but then we're doing threshold check twice so it's either that or DRY.

Comment (mwielocha) [reply src/library/scala/collection/mutable/HashMap.scala]: Sorry, what I meant is *compute the index*, hash stays the same.

File: src/library/scala/collection/mutable/HashMap.scala [hunk 2]
```diff
@@ -161,7 +161,13 @@ class HashMap[K, V](initialCapacity: Int, loadFactor: Double)
...
           contentSize -= 1
 
-        case (None, Some(value)) => put0(key, value, false, hash, indexedHash)
+        case (None, Some(value)) =>
+          if(contentSize + 1 >= threshold) {
+            growTable(table.length * 2)
+            val newIndexedHash = index(hash)
+            put0(key, value, false, hash, newIndexedHash)
+          }
+          else put0(key, value, false, hash, indexedHash)
```
Comment (plokhotnyuk) [inline src/library/scala/collection/mutable/HashMap.scala]: It could be simplified to:
```
val newIndexedHash = 
  if(contentSize + 1 >= threshold) {
    growTable(table.length * 2)
    index(hash)
  } else indexedHash
put0(key, value, false, hash, newIndexedHash)
```
or even:
```
put0(key, value, false, hash, {
  if(contentSize + 1 >= threshold) {
    growTable(table.length * 2)
    index(hash)
  } else indexedHash
})
```

Comment (mwielocha) [reply src/library/scala/collection/mutable/HashMap.scala]: Indeed!

Comment (mwielocha) [reply src/library/scala/collection/mutable/HashMap.scala]: Uhm that I think I consider as being a little less readable...

File: src/library/scala/collection/mutable/HashMap.scala [hunk 3]
```diff
@@ -161,7 +161,13 @@ class HashMap[K, V](initialCapacity: Int, loadFactor: Double)
...
           contentSize -= 1
 
-        case (None, Some(value)) => put0(key, value, false, hash, indexedHash)
+        case (None, Some(value)) =>
+          val newIndexedHash =
+            if(contentSize + 1 >= threshold) {
+              growTable(table.length * 2)
+              index(hash)
+            } else indexedHash
+          put0(key, value, false, hash, newIndexedHash)
```
Comment (som-snytt) [inline src/library/scala/collection/mutable/HashMap.scala:170]: Should write `getOld = false`, named arg is used inconsistently in this file. This would be an opportunity to amend that. (I was about to contribute a lint and/or scalafix for that, which occurred to me while using rust fsr.)

The previous version could have been:
```
if (contentSize + 1 >= threshold) put0(key, value, hash, getOld = false) else put0(key, value, getOld = false, hash, indexedHash)
```
which also makes it obvious that the parameter order for the `put0` overload is inconsistent. One also notices that `getOld = true` for only one usage; this would be an opportunity to forgo the overload in favor of named variants.

Comment (mwielocha) [reply src/library/scala/collection/mutable/HashMap.scala:170]: Honestly? The code style quality is a bit lacking with this override, there is a ton of inconsistencies around, for example, how nodes are being search for. We have `while` loops alongside `@tailrec` implementing pretty much same scenarios. Also the hole part with `if(contentSize + 1 >= threshold) growTable(table.length * 2)` is being copied all over the place. But the point is that this is actually a critical problem that for some scenarios makes `mutable.HashMap` quite unusable. The way I found this was while debugging poor performance of `mutable.MultiDict` from collection.contrib that utilises `updateWith` quite heavily. 
But I'm new here so not sure what style adjustments I'm allowed to propose.

Comment (som-snytt) [reply src/library/scala/collection/mutable/HashMap.scala:170]: Yes, the only style issue I feel strongly about is having a space between `if` and open paren. /humor. I didn't mean to nit-pick, and you're right that tweaks can wait.

Comment (plokhotnyuk) [reply src/library/scala/collection/mutable/HashMap.scala:170]: Sorry, the missing space was my misprinting.

Also, the latest recommendation is to have `if` and `else` aligned to the same column even if curly brackets are used between them.

Comment (mwielocha) [reply src/library/scala/collection/mutable/HashMap.scala:170]: Fixed.

File: src/library/scala/collection/mutable/HashMap.scala [hunk 4]
```diff
@@ -161,7 +161,13 @@ class HashMap[K, V](initialCapacity: Int, loadFactor: Double)
           else table(indexedHash) = foundNode.next
           contentSize -= 1
 
-        case (None, Some(value)) => put0(key, value, false, hash, indexedHash)
+        case (None, Some(value)) =>
+          val newIndexedHash =
+            if (contentSize + 1 >= threshold) {
+              growTable(table.length * 2)
```
Comment (NthPortal) [inline src/library/scala/collection/mutable/HashMap.scala:167]: not really specific to this PR, but the `growTable` method is broken (does not handle integer overflow, computes a `threshold` value but never uses it)

Comment (mwielocha) [reply src/library/scala/collection/mutable/HashMap.scala:167]: That might be true I haven't gotten that deep but performance tests are much better with this change and the table expands so, as you said, this should probably be a separate issue.

**Review by lrytz — APPROVED** [review]
Thanks, @mwielocha! I squashed the commits into one (as we usually do in this repo).

**Comment by mwielocha** [comment]
Thank you!
