### PR TITLE
Fix suppressed stack trace frame count in REPL

### LINKED ISSUE #11945: Repl stack trace summary doesn't count suppressed frames correctly
## reproduction steps

```scala
scala> val e = new AssertionError("oops")
e: AssertionError = java.lang.AssertionError: oops

scala> e.addSuppressed(new java.io.IOException("bad io"))

scala> e.printStackTrace
java.lang.AssertionError: oops
        at $line3.$read$$iw$$iw$.<clinit>(<console>:1)
        at $line3.$eval$.$print$lzycompute(<synthetic>:6)
        at $line3.$eval$.$print(<synthetic>:5)
        at $line3.$eval.$print(<synthetic>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:632)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:946)
        at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:474)
        at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:40)
        at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:40)
        at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:473)
        at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$3(IMain.scala:487)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:487)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:470)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:931)
        at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:788)
        at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:462)
        at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:485)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:1020)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
        Suppressed: java.io.IOException: bad io
                at $line5.$read$$iw$$iw$.<clinit>(<console>:1)
                at $line5.$eval$.$print$lzycompute(<synthetic>:6)
                at $line5.$eval$.$print(<synthetic>:5)
                at $line5.$eval.$print(<synthetic>)
                ... 24 more

scala> throw e
java.lang.AssertionError: oops
  ... 28 elided
  Suppressed: java.io.IOException: bad io
    ... 24 more

scala>
```

## problem

```scala
scala> e.getSuppressed.head.printStackTrace
java.io.IOException: bad io
        at $line5.$read$$iw$$iw$.<clinit>(<console>:1)
        at $line5.$eval$.$print$lzycompute(<synthetic>:6)
        at $line5.$eval$.$print(<synthetic>:5)
        at $line5.$eval.$print(<synthetic>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[snip]
```

## expectation

Printing the suppressed exception doesn't seem to count frames correctly, as the depth is 28. Here, the top four differ in the two exceptions.

### PR DESCRIPTION
**Pull request by NthPortal**
Fixes scala/bug#11945

### CODE REVIEW

File: src/compiler/scala/tools/nsc/util/StackTracing.scala [hunk 1]
```diff
@@ -54,16 +54,26 @@ private[util] trait StackTracing extends Any {
...
+        if (framesPrefixLenDiff > 0) lines += s"${margin}  ... ${framesPrefixLenDiff} elided and ${traceFramesLenDiff} more"
+        else lines += s"${margin}  ... ${traceFramesLenDiff} more"
+      } else if (framesPrefixLenDiff > 0) {
+        lines += s"${margin}  ... ${framesPrefixLenDiff} elided"
+      }
+
+//      if (frames.length < trace.length) lines += s"${margin}  ... ${trace.length - frames.length} more"
+//      if (r == Self && prefix.length < frames.length) lines += s"${margin}  ... ${frames.length - prefix.length} elided"
       print(e.getCause, CausedBy, trace, indents)
       e.getSuppressed.foreach(print(_, Suppressed, frames, indents + 1))
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/util/StackTracing.scala:74]: Thanks, and sorry you had to crack that open.

Did you prefer one liner or stacked for saying elided and more? Either way, this fix looks good.

I'm not sure why print recurses with trace for cause and frames for suppress. I wonder if there is a reason it says elided only at top level (Self).

Is it true there is no necessary relationship between the stack traces of an exception, its cause, and other exceptions it suppresses? Although suppressions are paradigmatically due to exceptions on close, one could imagine suppressing async errors on a different stack. I wonder if anything in scala.concurrent does that.

I forgot I had touched this in January, before work started up again. I remember I intended to make it readable. Ha.

I'll have a follow-up edit which I'll let you pull if you like, or I'll use it later. There's also a junit test. I was linting junit tests today, so you inspired me to take another whack at this one. For instance, I wanted to compare stack trace and the trimmed representation side-by-side.

File: src/compiler/scala/tools/nsc/util/StackTracing.scala [hunk 2]
```diff
@@ -54,16 +54,26 @@ private[util] trait StackTracing extends Any {
...
         trimmed.reverse
       }
       val prefix = frames.takeWhile(p)
       val margin = "  " * indents
       lines += s"${margin}${r}${header(e)}"
       prefix.foreach(f => lines += s"${margin}  at $f")
-      if (frames.size < trace.size) lines += s"${margin}  ... ${trace.size - frames.size} more"
-      if (r == Self && prefix.size < frames.size) lines += s"${margin}  ... ${frames.size - prefix.size} elided"
+
+      val traceFramesLenDiff = trace.length - frames.length
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/util/StackTracing.scala]: oh no the equals do not line up.

File: test/files/run/repl-trace-elided-more.scala [hunk 3]
```diff
@@ -0,0 +1,5 @@
+import scala.tools.partest.{SessionTest, StackCleaner}
+
+// scala/bug#11945 print stack trace elided count correctly
```
Comment (som-snytt) [inline test/files/run/repl-trace-elided-more.scala:3]: Of course, we'll never know, because the check file is redacted.

File: test/files/run/repl-trace-elided-more.scala [hunk 4]
```diff
@@ -0,0 +1,5 @@
+import scala.tools.partest.{SessionTest, StackCleaner}
```
Comment (som-snytt) [inline test/files/run/repl-trace-elided-more.scala:1]: People make fun of SessionTest for some reason.

File: test/files/run/repl-trace-elided-more.scala (hunk 3 above)
Comment (NthPortal) [reply test/files/run/repl-trace-elided-more.scala:3]: LOL

File: src/compiler/scala/tools/nsc/util/StackTracing.scala (hunk 2 above)
Comment (NthPortal) [reply src/compiler/scala/tools/nsc/util/StackTracing.scala]: I'll fix it

File: src/compiler/scala/tools/nsc/util/StackTracing.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/util/StackTracing.scala:74]: FYI, `header` is easier to read when aligned. I'll get back to the unit test later.

https://github.com/som-snytt/scala/commit/0009dc9d682f45e4eb87aa16fc5d79c6eef8b7d9

Comment (NthPortal) [reply src/compiler/scala/tools/nsc/util/StackTracing.scala:74]: > sorry you had to crack that open

I was happy to - I think I learned quite a bit :)

> Did you prefer one liner or stacked for saying elided and more?

I think I prefer the one liner. I only asked because stacked is a much smaller change

> Is it true there is no necessary relationship between the stack traces of an exception, its cause, and other exceptions it suppresses?

pretty much, yeah

> Although suppressions are paradigmatically due to exceptions on close

it doesn't have to be from closing the same resource though. you could have one exception thrown from using one resource, and then another thrown by closing a different resource you had open

> I'll have a follow-up edit which I'll let you pull if you like

I'm happy to make edits if there are issues. I know there are a few things I forgot to clean up after working on it

Comment (NthPortal) [reply src/compiler/scala/tools/nsc/util/StackTracing.scala:74]: @som-snytt feel free to push changes if you'd like

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/util/StackTracing.scala:74]: I don't want to be that guy, but thanks for taking the PRETY version of header method.

**Review by som-snytt — APPROVED** [review]
Forgot to say squash for merge. I think there may be a squash and merge button, but then you have a squash commit without a green check. Does that matter? I don't know. It might affect bisection with CI artifacts. Also, hey, it's April!

**Comment by som-snytt** [comment]
Yes, @SethTisue  says please don't use squash-and-merge button. I wonder if he wants this for the 2.13.2 in the morning?

**Comment by NthPortal** [comment]
(for future reference, in case anyone needs to do it for me, my commits are set up so that a `git rebase -i --autosquash <target>` will squash things properly, without needing to do anything other than write the rebase plan)

**Comment by som-snytt** [comment]
I thought autosquash was when you don't bother driving around roadkill.
