### PR TITLE
Fixes x.toString and value classes causing auto-application warnings under -Xsource:2.14

### LINKED ISSUE #11639: Spurious auto-application warnings with java methods with `-Xsource:2.14`
With `-Xsource:2.14` my build produces warnings when calling java methods without parentheses, which is the currently recommended Scala style:

```
Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method toString,
[warn] or remove the empty argument list from its definition (Java-defined methods are exempt).
[warn] In Scala 3, an unapplied method like this will be eta-expanded into a function.
[warn]         case o => o.toString
```

However, `toString` is a Java method, which as the warning itself suggests, is excluded from deprecation!

### LINKED ISSUE #11657: -Xsource:2.14 produces warning for value classes which are wrapping case classes in Scala 2.13.0
The following code produces a warning with `-Xsource:2.14` (and `-deprecation`) enabled for the following code:

```scala
case class Bar(x: Int)
class Foo(val bar: Bar) extends AnyVal
```

The warning is:

> Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method hashCode, or remove the empty argument list from its definition (Java-defined methods are exempt). In Scala 3, an unapplied method like this will be eta-expanded into a function. class Foo(val bar: Bar) extends AnyVal

Seems like the inspection is called on the compiler generated code for AnyVal (and only when the contained value type is some case class) instead of the original one.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/scala/bug/issues/11639
Fixes https://github.com/scala/bug/issues/11657

The compiler gets confused about the lineage of `toString` apparently, so instead of trying to look for the Java flag, I am just going to see if the name exists under `AnyTpe`.

### CODE REVIEW

File: test/files/pos/auto-application.scala [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+class A() {
+  override def toString(): String = "A()"
+}
+
+class B() {
+  override def toString: String = "B()"
+}
+
+case class C(c: Int) extends AnyVal
```
Comment (eed3si9n) [inline test/files/pos/auto-application.scala:31]: Value class generates `this.underlying.hashCode`.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 2]
```diff
@@ -971,10 +972,11 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
         //          > val vparamSymssOrEmptyParamsFromOverride =
         //          This means an accessor that overrides a Java-defined method gets a MethodType instead of a NullaryMethodType, which breaks lots of assumptions about accessors)
         def checkCanAutoApply(): Boolean = {
-          if (sourceLevel2_14 && !meth.isJavaDefined)
+          if (sourceLevel2_14 && !meth.isJavaDefined && !isAnyDerived(meth)) {
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: I had the same idea, as cheaper than checking for a java-defined override. 👍

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 3]
```diff
@@ -971,10 +972,11 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
...
             context.deprecationWarning(tree.pos, NoSymbol, s"Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method ${meth.decodedName},\n" +
                                                            s"or remove the empty argument list from its definition (Java-defined methods are exempt).\n"+
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: You could fix the wording here to "immediate overrides that are Java-defined and members of Any (if you're seeing this message then something is broken)."

**Review by smarter — APPROVED** [review]

**Review by lrytz — CHANGES_REQUESTED** [review]
Shouldn't we also skip the warning for other overrides of java-defined methods?

```
$> java -cp $(coursier fetch -p -r https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots org.scala-lang:scala-compiler:2.13.1-bin-67462b5-SNAPSHOT) scala.tools.nsc.MainGenericRunner -usejavacp -deprecation -Xsource:2.14
Welcome to Scala 2.13.1-20190801-071814-67462b5 (Java HotSpot(TM) 64-Bit GraalVM EE 19.1.0, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> class A extends Runnable { def run(): Unit = () }
defined class A

scala> val a = new A
a: A = A@5b1e88f

scala> a.run
         ^
       warning: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method run,
       or remove the empty argument list from its definition (Java-defined methods are exempt).
       In Scala 3, an unapplied method like this will be eta-expanded into a function.
```

**Comment by lrytz** [comment]
Or, in other words, why are `toString` / `hashCode` special?

(`Runnable.run` is not a good example as it's a side-effecting method, but my question is the same.)

**Comment by eed3si9n** [comment]
> Or, in other words, why are `toString` / `hashCode` special?

Because they come from `scala.Any`, and it doesn't extend `java.lang.Object`, but in spirit `toString` are Java-inspired even though it may not be `isJavaDefined`.

**Comment by lrytz** [comment]
OK, thanks.

But the source of the issue seems to be the empty param list `()` when overriding `toString` / `hashCode` definitions in Scala? It seems the recommendation should be to override without param list, instead of relaxing the call-site check.

**Comment by som-snytt** [comment]
In 2.13, you still can't define parenless `toString`, though I contributed a lint in Namers to warn that your `def toString` is really `def toString()`. https://github.com/scala/scala/pull/8293

The exclusion test should be `m.overrides.exists(_.isJavaDefined)`, since the idea is that you can't help but introduce parens in Java, even aside from `m.overrides.last`.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 4]
```diff
@@ -959,6 +959,7 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
           doIt
         }
 
+        def isAnyDerived(sym: Symbol): Boolean = AnyTpe.nonPrivateMember(sym.name) != NoSymbol
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: TIL `isUniversalMember(sym)`, which is more precise.

So `sym.overrides.exists(isUniversalMember)`.

Or `sym.overrides.lastOption.map(isUniversalMember).getOrElse(false)`.

`class C { def equals() = false } ; new C().equals` for example. Hopefully their lint for overloading `equals` also alerted.

**Review by som-snytt — DISMISSED** [review]
Maybe less namely.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 4 above)
Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: Members get the secret fifth [churro flavor](https://www.universalstudioshollywood.com/park-tips/4-all-new-churro-flavors) at our theme park.

Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: Addressed in d090b8002bb965f1e6f11f82bcf26417aead5636. `meth.overrides` returned `Nil` for value class's `hashCode` so I went with `!isUniversalMember(meth.overrides.lastOption.getOrElse(meth))`.

**Comment by lrytz** [comment]
> In 2.13, you still can't define parenless `toString`

Ah I get it now. You can write

```
scala> class A { override def toString = "" }
defined class A
```

but the compiler makes `toString()` out of it, and then issues the warning under `Xsource:2.14`.

Did we ever try to fix this instead? Maybe we can use a symbol attachment for nullary methods that became nilary.

File: test/files/pos/auto-application.scala (hunk 1 above)
Comment (som-snytt) [reply test/files/pos/auto-application.scala:31]: Another test:
```
$ skala -Xsource:2.14
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM 11.0.3)

scala> class C(val i: Int) extends AnyVal { override def toString = "hi" }
                                                                    ^
       warning: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method toString$extension,
       or remove the empty argument list from its definition (Java-defined methods are exempt).
       In Scala 3, an unapplied method like this will be eta-expanded into a function.
defined class C

scala> class C(val i: Int) extends AnyVal { override def toString() = "hi" }
defined class C

```
My diff:
```
-          if (sourceLevel2_14 && !meth.isJavaDefined)
+          def isJavaOrUniversal(sym: Symbol) = sym.isJavaDefined || isUniversalMember(sym)
+          if (sourceLevel2_14 && !isJavaOrUniversal(meth) && !meth.overrides.exists(isJavaOrUniversal))
```

**Comment by som-snytt** [comment]
This handles `run` but not `toString` extension, in my comment to the test.
```
          def isJavaOrUniversal(sym: Symbol) = sym.isJavaDefined || isUniversalMember(sym)
          if (sourceLevel2_14 && !isJavaOrUniversal(meth) && !meth.overrides.exists(isJavaOrUniversal))
```

**Comment by eed3si9n** [comment]
It's ugly but if I resurrect the name search I can do this:

```scala
        def isJavaOrUniversal(sym: Symbol) = {
          sym.isJavaDefined ||
          isUniversalMember(sym) ||
          (if (sym.name.endsWith("$extension")) AnyTpe.nonPrivateMember(sym.name.dropRight(10)) != NoSymbol else false)
        }
```

This is to filter out `toString$extension`:

```scala
Welcome to Scala 2.13.1-pre-d090b80 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.
scala> class Bibbity(val i: Int) extends AnyVal { override def toString = "hi" }
defined class Bibbity
```

Is there a way for an extension sym to look up the original method?

File: test/files/pos/auto-application.scala [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+
+// This generates toString$extension
+class Bibbity(val i: Int) extends AnyVal {
+  override def toString = "hi"
+}
+
+class City extends Runnable { override def run(): Unit = () }
+object City {
+  val c = new City
+  c.run // should be ok without parens
```
Comment (eed3si9n) [inline test/files/pos/auto-application.scala:41]: Added Runnable example here.

**Comment by som-snytt** [comment]
@lrytz can we get this in 2.13.2? Any mitigation reduces new tickets such as https://github.com/scala/bug/issues/11889

It doesn't have to be perfect or update the spec as to whether matching members may differ in an empty parameter list, etc.

The minimum viable compiler should not warn about `toString`, `hashCode`, etc.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 6]
```diff
@@ -959,7 +959,11 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
           doIt
         }
 
-
+        def isJavaOrUniversal(sym: Symbol) = {
+          sym.isJavaDefined ||
+          isUniversalMember(sym) ||
+          (if (sym.name.endsWith("$extension")) AnyTpe.nonPrivateMember(sym.name.dropRight(10)) != NoSymbol else false)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: Can we avoid this by running `checkCanAutoApply` only if `!phase.erasedTypes`?

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 7]
```diff
@@ -959,7 +959,11 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
           doIt
         }
 
-
+        def isJavaOrUniversal(sym: Symbol) = {
+          sym.isJavaDefined ||
+          isUniversalMember(sym) ||
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: This includes `wait`, `notify`, `notifyAll`, `clone`, `finalize`. [Dotty does](https://github.com/lampepfl/dotty/blob/811dc19f418f26d6b830bb08bfb49aeee3853a49/compiler/src/dotty/tools/dotc/core/SymDenotations.scala#L950-L957) `sym.owner == defn.AnyClass || sym == defn.Object_clone`, I think we should align with that.

**Review by lrytz — COMMENTED** [review]
I'm fine getting this in 2.13.2 since (once) it aligns with dotty. There will still be things to clean up after, for example
  - `Any.##` is nullary in dotc, nilary in scalac
  - Overriding nilary with nullary and vice-versa is not allowed in dotty

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 7 above)
Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: addressed it here - https://github.com/scala/scala/pull/8296/commits/e18dd0d592c82ed8a7e1b082bafb0c4c59305f0a

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 6 above)
Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: `!phase.erasedTypes` didn't work but the following did:

```scala
val afterExtMethods = phaseId(currentPeriod) >= currentRun.phaseNamed("extmethods").id
```

and then `!afterExtMethods`.

**Comment by eed3si9n** [comment]
Looks like I need to update the check file.

```diff
!!    1 - neg/t7187-deprecation.scala               [output differs]
% diff /home/jenkins/workspace/scala-2.13.x-validate-main@3/test/files/neg/t7187-deprecation.check /home/jenkins/workspace/scala-2.13.x-validate-main@3/test/files/neg/t7187-deprecation-neg.log
@@ -13,5 +13,5 @@ or remove the empty argument list from its definition (Java-defined methods are
 In Scala 3, an unapplied method like this will be eta-expanded into a function.
   a.boom // error
     ^
-two warnings found
-one error found
+2 warnings
+1 error
```

**Comment by eed3si9n** [comment]
Rebased and squashed.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 8]
```diff
@@ -977,10 +983,12 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
         //          > val vparamSymssOrEmptyParamsFromOverride =
         //          This means an accessor that overrides a Java-defined method gets a MethodType instead of a NullaryMethodType, which breaks lots of assumptions about accessors)
         def checkCanAutoApply(): Boolean = {
-          if (sourceLevel2_14 && !meth.isJavaDefined)
+          val afterExtMethods = phaseId(currentPeriod) >= currentRun.phaseNamed("extmethods").id
+          if (sourceLevel2_14 && !afterExtMethods && !matchNullaryLoosely) {
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: I should have suggested `!isPastTyper`, it seems that's what's used for guarding warnings. Will push a fix.

**Review by lrytz — APPROVED** [review]

**Review by som-snytt — APPROVED** [review]

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 8 above)
Comment (dwijnand) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: > I should have suggested `!isPastTyper`, it seems that's what's used for guarding warnings.

Side: I wonder if that (1) can and (2) should be always considered in the behaviour of `context.deprecationWarning`.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: Uncurry has one. Deprecation is used for all sorts of behaviors, and not just API. I'm not sure that is kosher, but I'm not a purist.
