### PR TITLE
Don't insert box instructions around label jumps

### LINKED ISSUE #13043: "Error while emitting" from scalac on pattern matching with AnyVal result
## Reproduction steps
openjdk 17 and 21
scala version 2.13.10 and  2.13.14  and  2.13.15
sbt version 1.10.1  and 1.10.2 

build.sbt
```
scalaVersion := "2.13.14" // or other 2.13.x versions
```

```scala

trait ParentTrait extends Any {
  def value: String
}
class Child2(val value: String) extends AnyVal with ParentTrait


object Sample {
    def test( sample: String): ParentTrait = 
      sample match {
        case "0" if true   =>  ???
        case _             => new Child2(???)
      }
}
```
I also tested with case classes and sealed traits. 
Also, the predicate in if statement (`true` in this sample code) can be anything,  the issue will be the same.

## Problem

Compilation fails with unhelpful message:
```
[info] compiling 1 Scala source to .../target/scala-2.13/classes ...
[error] Error while emitting Sample$
[error] Index 0 out of bounds for length 0
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```
And sometimes

```
[info] compiling 1 Scala source to .../target/scala-2.13/classes ...
[error] Error while emitting Sample$
[error] null
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

### PR DESCRIPTION
**Pull request by lrytz**
For match trees that are not eliminated during patmat, to be emitted as switches in bytecode, make sure erasure doesn't introduce boxing instructions around label jumps.

A label jump is a jump in bytecode, it doesn't produce a value on the stack that can be boxed. If the label type would need boxing, nothing needs to be done: the boxing instructions are already introduced at the jump target, where the label is defined.

Fixes https://github.com/scala/bug/issues/13043

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/TypeAdaptingTransformer.scala [hunk 1]
```diff
@@ -51,14 +51,18 @@ trait TypeAdaptingTransformer { self: TreeDSL =>
...
+          case _ => tree.setType(ObjectTpe)
+        }
       case _ =>
         val tree1 = tree.tpe match {
           case ErasedValueType(clazz, _) => New(clazz, cast(tree, underlyingOfValueClass(clazz)))
           case _ => tree.tpe.typeSymbol match {
             case UnitClass =>
               if (treeInfo isExprSafeToInline tree) REF(BoxedUnit_UNIT)
               else BLOCK(tree, REF(BoxedUnit_UNIT))
-            case NothingClass => tree // a non-terminating expression doesn't need boxing
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/transform/TypeAdaptingTransformer.scala:61]: This was added in 4074f0e1c2, but no longer seems needed, test/files/pos/t4593.scala passes without it.

**Comment by lrytz** [comment]
For reference, 2.13.15 adds boxing around label jumps. The backend just happens to skip over these instructions in the case of a primitive type.

```scala
class T {
  def test(v: Int): Any =
    v match {
      case 1 if true => 1
      case _ => 2
    }
}
```

`-Vprint:erasure`

```scala
    def test(v: Int): Object = {
      case <synthetic> val x1: Int = v;
      (x1: Int) match {
        case 1 => if (true)
          scala.Int.box(1)
        else
          scala.Int.box(default3()) // <<<<<<<<< `box` not emitted
        case _ => default3(){
          scala.Int.box(2)
        }
      }
    }
```

**Comment by sjrd** [comment]
Huh, even the `Int` case crashes the JS backend, though. I guess the fix here applies to the `Int` case as well, even though the JVM backend tolerates it?

**Comment by lrytz** [comment]
Yup, the trees should now be clean for primitive and user defined value classes.

**Review by SethTisue — APPROVED** [review]

**Comment by SethTisue** [comment]
fixup in #10926

UPDATE: and #10941 too
