### PR TITLE
No protected accessor when accessing through self type

### LINKED ISSUE #11924: inconsistent logic when override self type method
## reproduction steps

+ pk1/A.scala
```scala
package pk1
class A {
  protected def f(): Unit = print("A")
}
```
+ Main.scala
```scala
import pk1.A

trait B { self: A =>
  override def f(): Unit = {
    print("B")
    self.f()
  }
}
class C extends A with B
object Main {
  def main(args: Array[String]): Unit = {
    new C().f()
  }
}
```

## problem
+ The code above run successfully
```
[info] running Main 
BA[success]...
```
+ But when remove the `protected` modifier from `A.f` =>
```scala
[info] running Main 
BBB...//many Bs
[error] java.lang.StackOverflowError
...
[error] 	at scala.Predef$.print(Predef.scala:385)
[error] 	at B.f(Main.scala:5)
[error] 	at B.f$(Main.scala:4)
[error] 	at C.f(Main.scala:9)
[error] 	at B.f(Main.scala:6)
[error] 	at B.f$(Main.scala:4)
[error] 	at C.f(Main.scala:9)
...
```
+ similar (StackOverflowError) if we move `A` from `pkg1` to default package (same package as B)
## expectation
IDK :)

### PR DESCRIPTION
**Pull request by lrytz**
Fixes https://github.com/scala/bug/issues/11924

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala [hunk 1]
```diff
@@ -355,6 +355,7 @@ abstract class SuperAccessors extends transform.Transform with transform.TypingT
                     && !sym.owner.isTrait
                     && sym.owner.enclosingPackageClass != currentClass.enclosingPackageClass
                     && qual.symbol.info.member(sym.name).exists
+                    && !(currentClass.typeOfThis <:< sym.owner.tpe) // scala/bug#11924
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala]: Hmm, this is not enough for the REPL. Imitating the REPL, the following still prints `BA` instead of recursing:

```scala
package l1 {
class I {
  class A {
    protected def f(): Unit = print("A")
  }
}
object O extends I
}

package l2 {
class I {
  trait B { self: l1.O.A =>
    override def f(): Unit = {
      print("B")
      self.f()
    }
  }
}
object O extends I
}

class C extends l1.O.A with l2.O.B
object Test {
  def main(args: Array[String]): Unit = {
    new C().f()
  }
}
```

Comment (lrytz) [reply src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala]: Fixed.

**Comment by lrytz** [comment]
```
[error] scala-reflect: Failed binary compatibility check against org.scala-lang:scala-reflect:2.13.0! Found 1 potential problems (filtered 271)
[error]  * abstract synthetic method scala$reflect$runtime$SynchronizedOps$SynchronizedBaseTypeSeq$$super$maxDepthOfElems()Int in interface scala.reflect.runtime.SynchronizedOps#SynchronizedBaseTypeSeq is present only in other version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("scala.reflect.runtime.SynchronizedOps#SynchronizedBaseTypeSeq.scala$reflect$runtime$SynchronizedOps$SynchronizedBaseTypeSeq$$super$maxDepthOfElems")
```

Heh, so the fix removed an unnecessary protected accessor

**Comment by SethTisue** [comment]
@lrytz is this ready for review? want to suggest a reviewer?

(the merge conflict is just in the mima filters)

**Comment by lrytz** [comment]
Yep, this is ready. Review by @retronym.

**Comment by dwijnand** [comment]
This needs a rebase.  And a review/merge!

**Comment by SethTisue** [comment]
Rebased.

**Comment by SethTisue** [comment]
Rebased

**Review by retronym — APPROVED** [review]
