### PR TITLE
Lift try blocks to methods in value class invocations

### LINKED ISSUE #12550: VerifyError involving try/catch returning a value class
## Reproduction steps

Scala version: 2.13.7

```scala

class Opt[+T](private val self :T) extends AnyVal {
	def orSelf :Opt[T] = this
}

object Error extends App {
	def test =
		(
			try { new Opt(null) } catch { case _ :Throwable => new Opt(null) }
		).orSelf 
}
```

## Problem
```
Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 12
Exception Details:
  Location:
    Error$.test()Lscala/runtime/Null$; @9: goto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @9
    flags: { }
    locals: { 'Error$' }
    stack: { null }
  Stackmap Frame:
    bci: @12
    flags: { }
    locals: { 'Error$' }
    stack: { 'Opt$', null }
  Bytecode:
    0000000: b200 4a01 a700 0857 01a7 0003 4c2b 5701
    0000010: b600 4ec0 0050 b0                      
  Exception Handler Table:
    bci [3, 4] => handler: 7
  Stackmap Table:
    same_locals_1_stack_item_frame(@7,Object[#69])
    full_frame(@12,{Object[#2]},{Object[#71],Null})

	at Error.main(Error.scala)
```

### PR DESCRIPTION
**Pull request by lrytz**
In `def t = (try c catch { .. }).meth`, it looks like the stack
is empty when loading `c`. But if `c` is a value class, the call is
translated to `C.meth$extension(try c catch { .. })`, so the
`try` expression needs to be lifted to a local method.

Make UnCurry aware of this.

Fixes https://github.com/scala/bug/issues/12550

### CODE REVIEW

File: test/files/run/t12550.scala [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+  def u(c: C) = (try c catch { case _ :Throwable => c }).j(-1)(1)
+  def v(c: C) = (try c catch { case _ :Throwable => c }).k(try c catch { case _ :Throwable => c })
+
+  def tt(c: C) = (try c catch { case _ :Throwable => c }).ti
+  def tu(c: C) = (try c catch { case _ :Throwable => c }).tj(-1)(1)
+  def tv(c: C) = (try c catch { case _ :Throwable => c }).tk(try c catch { case _ :Throwable => c })
+
+  def ttt(c: T) = (try c catch { case _ :Throwable => c }).ti
+  def ttu(c: T) = (try c catch { case _ :Throwable => c }).tj(-1)(1)
+  def ttv(c: T) = (try c catch { case _ :Throwable => c }).tk(try new C(42) catch { case _ :Throwable => new C(42) })
```
Comment (som-snytt) [inline test/files/run/t12550.scala:41]: The orthography sent me back to the spec. It has to be
```
case __: Int =>
```
to cause a problem, an id with an underscore followed by op char. With one underscore, it is safe.

Comment (lrytz) [reply test/files/run/t12550.scala:41]: Ah, that's a copy-paste from the bug report which got all of those the other way...

Comment (som-snytt) [reply test/files/run/t12550.scala:41]: What a thorough bug report. edit: oh I see, _you_ copy pasted a line. :)

Comment (som-snytt) [reply test/files/run/t12550.scala:41]: Maybe I'll contribute a FAQ, "When do I need a space?" or for Scala 3, "What are all the uses of space in Scala?"

**Review by dwijnand — APPROVED** [review]

**Comment by som-snytt** [comment]
There ought to be a special award for one-line fixes where the code comment is more than one line.

**Review by retronym — APPROVED** [review]
