### PR TITLE
Stricter refchecks: subclassing on traits does not imply suffixing for their linearisations [ci: last-only]

### LINKED ISSUE #11136: deadly diamond of death, mixin edition
scala/bug#10853 caused extraneous bridge methods to be generated, causing certain methods in the new collections to be unable to be marked final (otherwise, the bridge would override a final method). That was fixed in 2.13.0-M5.

Now comes a second complication:

```scala
// names changed and type parameters removed to protect the innocent
trait IO {
  def c(x: Int): Int = ???
}
trait SO extends IO {
  override final def c(x: Int): Int = ???
}
trait SOIO extends IO {
  override def c(x: Int): Int = ???
}
trait SOSO extends SOIO with SO
abstract class AS extends SO
class L extends AS with SOSO
```

which, on 2.13.0-M5, produces a `java.lang.VerifyError: class L overrides final method c.(I)I`.

So we still can't make them final, after all.

This may be almost by design; removing the extra layer of `SOSO` causes the compiler to complain with
```scala
       class L extends AS with SOIO
             ^
<pastie>:17: error: overriding method c in trait SO of type (x: Int)Int;
         method c in trait SOIO of type (x: Int)Int cannot override final member
There were compilation errors!
```

Gonna look at the spec and see if this is `should-not-compile` or not. (`should-not-compile` on the 2.13 collections, 🙀...)

### PR DESCRIPTION
**Pull request by adriaanm**
this is true for non-trait classes: the linearisation of a class C contains
as segments the linearisations of its (non-trait) super classes, so we can
just treat those at the lowest point in the hierarchy

this optimization breaks down when considering traits and their linearisations,
as shown in the tests

attempt to fix scala/bug#11136

TODO: 
  - [x] there's actually a second problem in refchecks that allows the neg test to compile currently
  - [x] consider including some of the refactoring i did in my overridingPairs branch
  - [X] check performance
  - [x] see if we can collapse similar warnings (mixing in the same traits will give the same error each time, but which one is canonical?)
  - [x] bytecode diff
  - [x] community build run on 2.12 backport: https://github.com/scala/scala/pull/7746
  - [ ] 2.13 community build run

### CODE REVIEW

**Comment by adriaanm** [comment]
and now the fun can really begin :-) 

in src/library/scala/collection/convert/Wrappers.scala:
```
class ConcurrentMapWrapper inherits conflicting members:
 method getOrDefault in trait Map of type (x$1: Any, x$2: V)V and
 method getOrDefault in trait ConcurrentMap of type (x$1: Any, x$2: V)V
 (note: this can be resolved by declaring an `override' in class ConcurrentMapWrapper.);
other members with override errors are: forEach, replaceAll, computeIfAbsent, computeIfPresent, compute, merge
```
error in the library or compiler bug? we'll find out after this short break

**Comment by adriaanm** [comment]
it was a compiler bug -- see my [force-push](https://github.com/scala/scala/compare/ee57a98ae3123e6da038399543192678ed2a5e5e..aa613fd90d14dddf5e3a3f671761a59461f23a54). Java methods don't get OVERRIDE flags -- they are allowed to override implicitly...

This diamond is proving deadlier and deadlier. Take a look at the test failures. For example, the *pos* test for scala/bug#4731:
```
trait Trait1[T] { def foo(arg: Comparator[T]): Unit }
trait Trait2[T] extends Trait1[T] { def foo(arg: Comparator[String]): Int = 0 }

class Class1 extends Trait2[String] { }
```

The return types for `foo` are not refined covariantly, so this override should not be allowed. (That was the real bug, the fix we implemented was more focussed on the the backend going off the rails given this input.)

**Comment by adriaanm** [comment]
@retronym, I could use your help on this one

**Comment by adriaanm** [comment]
I dumped my thoughts as comments in the code. The main idea is that we have to find a sound and cheap predicate to check overlap between different parts of the inheritance DAG. Conceptually, if two classes/traits have the same base classes in the same order, we need only check overriding once.

**Comment by retronym** [comment]
What would `javac` say?

```java
import java.util.Comparator;

class Test {
  interface Trait1<T> { default void foo(Comparator<T> arg) {} };
  interface Trait2<T> extends Trait1<T> { default int foo(Comparator<String> arg) { return 0; } };
  static class Class1 implements Trait2<String> { }
}
```

```
sandbox/Test.java:5: error: name clash: foo(Comparator<String>) in Trait2 and foo(Comparator<T>) in Trait1 have the same erasure, yet neither overrides the other
  interface Trait2<T> extends Trait1<T> { default int foo(Comparator<String> arg) { return 0; } };
                                                      ^
  where T is a type-variable:
    T extends Object declared in interface Trait1
sandbox/Test.java:6: error: types Trait2<String> and Trait1<String> are incompatible; both define foo(java.util.Comparator<java.lang.String>), but with unrelated return types
  static class Class1 implements Trait2<String> { }
         ^
2 errors
```

Here's the archaeology for the errant optimization: https://github.com/scala/scala/commit/266df9f05ecd11e67166e57cc58236646f2f50bb#diff-4289e732d819f21580d21ffcf92da620R132

File: src/reflect/scala/reflect/internal/SymbolPairs.scala [hunk 1]
```diff
@@ -187,59 +154,16 @@ abstract class SymbolPairs {
...
-        val index2 = index(sym2.owner)
-        (index2 >= 0) && {
-          intersectionContainsElementLeq(
-            subParents(index1), subParents(index2), index1 min index2)
-        }
-      }
-    }
+    // Also prune top classes, since they are common while not contributing any optimization opportunities below.
+    private lazy val nonTraitParent: Symbol =
+      base.info.parents.headOption.map(_.typeSymbol).filterNot(sym => sym.isTrait || sym == definitions.ObjectClass || sym == definitions.AnyClass).getOrElse(NoSymbol)
```
Comment (retronym) [inline src/reflect/scala/reflect/internal/SymbolPairs.scala]: I think this could be:

```
base.info.firstParent.typeSymbol.filterNot(sym => sym.isTrait || sym == definitions.ObjectClass || sym == definitions.AnyClass)
```

**Comment by adriaanm** [comment]
I don't think I'll be able to figure this out in time for 2.13.0.

**Comment by smarter** [comment]
@adriaanm 

> I don't think I'll be able to figure this out in time for 2.13.0.

That's OK, but we should try to get some guarantee that the standard library of 2.13.0-RC1 will work once the fix is in, @hrhino in https://github.com/scala/bug/issues/11136#issuecomment-419886950 implied this might be broken.

**Comment by adriaanm** [comment]
Well, I took another stab at this. I couldn't find a good way to save more work in soundly skipping pairs in refchecks that would actually be triggered on bootstrapping (I tried checking whether there's a shared suffix in the baseClasses of the non-trait owners of a pair, but this never actually fired in the library). 

Note that we already have a basic check against duplicate work in symbol pairs: 

```scala
// Skip nextEntry if the (non-trait) class in `parents` is a subclass of the owners of
// both low and high. this means we'll come back to this entry when we consider
// `nonTraitParent`, and the linearisation order will be the same (this only works for
// non-trait classes, since subclassing on traits does not imply one's linearisation is
// contained in the other's) 
// This is not just an optimization -- bridge generation relies on visiting each such
// class only once.

if (!isMatch || (nonTraitParent.isNonBottomSubClass(low.owner) && nonTraitParent.isNonBottomSubClass(high.owner)))
   advanceNextEntry()
```

**Comment by retronym** [comment]
Following are the errors reported compiling the the `scala` corpus in the compiler becnhmark. That is based on the 2.12.x library with minimal changes required to be compilable by 2.13.x.

I presume they are valid error messages, but we should double check, as it could instead be a bug in the subtyping check for the covariant return type.

Category 1:
```
/home/jenkins/.compilerBenchmark/sourceAssembly/library/scala/collection/IterableViewLike.scala:30: 
error: overriding
method flatten in trait GenericTraversableTemplate of type [B](implicit asTraversable: A => scala.collection.GenTraversableOnce[B])Iterable[B];
method flatten in trait TraversableViewLike of        type [B](implicit asTraversable: A => scala.collection.GenTraversableOnce[B])IterableViewLike.this.Transformed[B] has incompatible type;
other members with override errors are: unzip, unzip3
```

Category 2:

```
/home/jenkins/.compilerBenchmark/sourceAssembly/library/scala/collection/IterableViewLike.scala:115: error: <$anon: IterableViewLike.this.AbstractTransformed[B] with IterableViewLike.this.Forced[B]> inherits conflicting members:
  method foreach in trait Transformed of type [U](f: B => U)Unit and
  method foreach in trait Forced of type [U](f: B => U)Unit
  (note: this can be resolved by declaring an `override` in <$anon: IterableViewLike.this.AbstractTransformed[B] with IterableViewLike.this.Forced[B]>.)
  protected override def newForced[B](xs: => GenSeq[B]): Transformed[B] = new { val forced = xs } with AbstractTransformed[B] with Forced[B]
                                                                              ^
```

[Full List](https://gist.github.com/e1f35de90f636f6547cc38de9ed55b90)

-------------------

```
scala> val TVL_flatten = typeOf[scala.collection.TraversableViewLike[_, _, _]].decl(TermName("flatten"))
TVL_flatten: $r.intp.global.Symbol = method flatten

scala> val GTL_flatten = typeOf[scala.collection.generic.GenericTraversableTemplate[_, Nothing]].decl(TermName("flatten"))
GTL_flatten: $r.intp.global.Symbol = method flatten

scala> TVL_flatten.defString
res26: String = override def flatten[B](implicit asTraversable: A => scala.collection.GenTraversableOnce[B]): TraversableViewLike.this.Transformed[B]

scala> GTL_flatten.defString
res27: String = def flatten[B](implicit asTraversable: A => scala.collection.GenTraversableOnce[B]): CC[B]


scala> println(TVL_flatten.owner.info.baseTypeSeq.toList.mkString("\n"))
scala.collection.TraversableViewLike[A,Coll,This]
Traversable[A]
scala.collection.GenTraversable[A]
scala.collection.TraversableLike[A,This] with scala.collection.TraversableLike[A,Traversable[A]]
scala.collection.GenTraversableLike[A,This] with scala.collection.GenTraversableLike[A,Traversable[A]] with scala.collection.GenTraversableLike[A,scala.collection.GenTraversable[A]]
scala.collection.generic.GenericTraversableTemplate[A,scala.collection.GenTraversable] with scala.collection.generic.GenericTraversableTemplate[A,Traversable]
scala.collection.TraversableOnce[A]
scala.collection.ViewMkString[A]
Object
scala.collection.Parallelizable[A,scala.collection.parallel.ParIterable[A]]
scala.collection.GenTraversableOnce[A]
scala.collection.generic.HasNewBuilder[A,This] with scala.collection.generic.HasNewBuilder[A,Traversable[A]] with scala.collection.generic.HasNewBuilder[A,scala.collection.GenTraversable[A] @scala.annotation.unchecked.uncheckedVariance]
scala.collection.generic.FilterMonadic[A,This] with scala.collection.generic.FilterMonadic[A,Traversable[A]]
Any

scala>  TVL_flatten.owner.info.baseType(symbolOf[scala.collection.generic.GenericTraversableTemplate[_, Nothing]])
res29: $r.intp.global.Type = scala.collection.generic.GenericTraversableTemplate[A,Traversable]

scala>  TVL_flatten.owner.info.baseTypeSeq.toList.find(_.typeSymbol == (symbolOf[scala.collection.generic.GenericTraversableTemplate[_, Nothing]]))
res30: Option[$r.intp.global.Type] = Some(scala.collection.generic.GenericTraversableTemplate[A,scala.collection.GenTraversable] with scala.collection.generic.GenericTraversableTemplate[A,Traversable])
```

**Comment by adriaanm** [comment]
Looks like the power mode snippet confirms the error in cat 1, then?

**Comment by adriaanm** [comment]
With the `concat` method `final`, M5 does report override errors  when i uncomment the methods below:

```
// scala/collection/Seq.scala
@`inline` final override def concat[B >: A](suffix: IterableOnce[B]): CC[B] = appendedAll(suffix)

// scala/collection/StrictOptimizedSeqOps.scala
//  override def concat[B >: A](suffix: IterableOnce[B]): CC[B] = appendedAll(suffix)

// scala/collection/StrictOptimizedIterableOps.scala
//  override def concat[B >: A](suffix: IterableOnce[B]): CC[B] =
//    strictOptimizedConcat(suffix, iterableFactory.newBuilder[B])

```

**Comment by adriaanm** [comment]
I feel like we've done our due diligence here, and I'm worried about performance regressions. I've tried to come up with a sound condition for omitting duplicative checks, but no luck so far. This PR also needs more work in suppressing duplicate errors for mixed in members.

**Comment by adriaanm** [comment]
queued performance run as https://scala-ci.typesafe.com/view/scala-bench/job/compiler-benchmark/2361

**Comment by adriaanm** [comment]
I'm encouraged that it doesn't seem to impact compiler performance, even when compiling the stdlib, which is expected to exercise this code path heavily: https://scala-ci.typesafe.com/grafana/dashboard/db/pr-validation?orgId=1&from=1548641091926&to=1549969905480&var-scalaSha=1abd765%7C74aee2a%7C4404f62%7Ce959f6c&var-source=All&var-bench=HotScalacBenchmark.compile&var-host=scalabench@scalabench@

**Comment by adriaanm** [comment]
Looking at this stuff is causing some serious `forSome` doubt. What's the point of warning about overriding final members in traits if later we could get the linearisation right?

File: test/files/pos/t11136_final_in_trait.scala [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+}
+
+trait LinearSeqOps[+A, +CC[_]] extends SeqOps[A, CC]
+
+
+trait StrictOptimizedIterableOps[+A, +CC[_]] extends IterableOps[A, CC] {
+  override def concat[B >: A](suffix: IterableOnce[B]): CC[B] = ???
+}
+
+// error reported, but is this really needed?
```
Comment (adriaanm) [inline test/files/pos/t11136_final_in_trait.scala]: when skipping `printMixinOverrideErrors`, we seem to emit perfectly valid bytecode for this example /cc @retronym

Comment (retronym) [reply test/files/pos/t11136_final_in_trait.scala]: > Methods of interfaces may have any of the flags in Table 4.6-A set except
ACC_PROTECTED, ACC_FINAL, ACC_SYNCHRONIZED, and ACC_NATIVE (JLS §9.4).

We don't/can't emit default methods as ACC_FINAL. That doesn't mean the error is invalid -- I think it is correctly enforcing Scala language rules.

Comment (retronym) [reply test/files/pos/t11136_final_in_trait.scala]: Hmm, now I see your point: given that the override is not user-written, why don't we take advantage of the fact that default methods are known to be non-`ACC_FINAL`. 

```
$ scalac -d /tmp/override-check-old sandbox/test.scala
sandbox/test.scala:19: error: overriding method concat in trait SeqOps of type [B >: A](suffix: IterableOnce[B])CC[B];
 method concat in trait StrictOptimizedIterableOps of type [B >: A](suffix: IterableOnce[B])CC[B] cannot override final member
trait StrictOptimizedSeqOps[+A, +CC[_]] extends SeqOps[A, CC] with StrictOptimizedIterableOps[A, CC] {}
      ^
one error found
```

Comment (smarter) [reply test/files/pos/t11136_final_in_trait.scala]: > why don't we take advantage of the fact that default methods are known to be non-`ACC_FINAL`.

That seems kind of crazy to me, I could imagine myself debugging a piece of code for hours, assuming that a given method must be called since it's `final`, only to discover the compiler ignored the language semantics and sneakily added an override while I wasn't looking...

Comment (adriaanm) [reply test/files/pos/t11136_final_in_trait.scala]: I agree it's counter-intuitive to allow the trait definition, and I'm not necessarily saying we must, but as my meta-point: is it any less weird that you can "fix" the problem later by mixing in the traits in the right order? This, we do all the time to get the desired linearisation order.  I mean, that's the whole reason I'm looking at this bug, because the collections pulled tricks like this. 

I guess you'd say they should not change the linearisation as drastically in subclasses.

Comment (adriaanm) [reply test/files/pos/t11136_final_in_trait.scala]: Also, to be clear. There would be an error in the class of course, because there we know for sure that you're trying to override a final method. We don't know that in the trait, anymore than where a super is going to go (which we acknowledge by having abstract super accessors, but we don't admit that we don't know whether you will actually be overriding a final method or not until the linearisation is decided in a class)

**Comment by adriaanm** [comment]
I spent a lot of time staring at our error messages while working on this PR, and I found them quite obscure. Tried to improve them. @SethTisue could you go over the last commit and see what you think about the new errors?

**Comment by SethTisue** [comment]
the better error messages are a very nice improvement!

**Comment by lrytz** [comment]
I rebased this, but now getting

```
../src/library/scala/collection/mutable/ArrayBuffer.scala:40: error: cannot override a concrete member without a third member that's overridden by both (this rule is designed to prevent ``accidental overrides'')
def knownSize: Int (defined in trait Growable)
  with override def knownSize: Int (defined in trait IndexedSeqOps)
class ArrayBuffer[A] private (initialElements: Array[AnyRef], initialSize: Int)
      ^
../src/library/scala/collection/mutable/ArrayDeque.scala:45: error: cannot override a concrete member without a third member that's overridden by both (this rule is designed to prevent ``accidental overrides'')
def knownSize: Int (defined in trait Growable)
  with override def knownSize: Int (defined in trait IndexedSeqOps)
class ArrayDeque[A] protected (
      ^
two errors found
```

It seems to be an interaction with https://github.com/scala/scala/commit/f293db4572. @szeiger do we just need manual overrides in ArrayBuffer and ArrayDeque? I actually don't understand what the error message is trying to express..

**Comment by lrytz** [comment]
OK, here's an example to trigger that message

```
trait A { def f: Int }
trait AA extends A { def f = -1 }
trait AAA extends A { override def f = 1 }
trait B { def f = -1 }
class C extends B with AAA
```

I guess the improved override checking is catching missing overrides in ArrayBuffer/ArrayDeque, I'll check.

File: test/files/neg/sd128.check [hunk 3]
```diff
@@ -4,14 +4,8 @@ Test.scala:4: error: class C1 inherits conflicting members:
   (note: this can be resolved by declaring an `override` in class C1.)
 class C1 extends A with T // error
       ^
-Test.scala:5: error: class C2 inherits conflicting members:
-  method f in trait T of type => Int and
-  method f in trait A of type ()Int
-  (note: this can be resolved by declaring an `override` in class C2.)
-class C2 extends T with A // error
-      ^
```
Comment (lrytz) [inline test/files/neg/sd128.check]: Shouldn't we get an error about "accidental override" here?

```
$> cat A.java
interface A {
  default int f() { return -10; }
}
$> cat Test.scala
trait T { def f = 99 }
object C {
  new T with A // compiles, A.f overrides T.f, but A and T are unrelated
}
```

File: src/library/scala/collection/Iterable.scala [hunk 4]
```diff
@@ -31,7 +31,7 @@ trait Iterable[+A] extends IterableOnce[A] with IterableOps[A, Iterable, Iterabl
   final def toIterable: this.type = this
 
   //TODO scalac generates an override for this in AbstractMap; Making it final leads to a VerifyError
```
Comment (lrytz) [inline src/library/scala/collection/Iterable.scala]: remove "TODO"

File: src/library/scala/collection/StrictOptimizedSeqOps.scala [hunk 5]
```diff
@@ -65,8 +65,8 @@ trait StrictOptimizedSeqOps [+A, +CC[_], +C]
   }
 
   // Must override here to ensure that `concat` is still an alias for `appendedAll` since it is overridden in `StrictOptimizedIterableOps`
-  @deprecatedOverriding("Compatibility override", since="2.13.0")
-  override def concat[B >: A](suffix: IterableOnce[B]): CC[B] = appendedAll(suffix)
+//  @deprecatedOverriding("Compatibility override", since="2.13.0")
+//  override def concat[B >: A](suffix: IterableOnce[B]): CC[B] = appendedAll(suffix)
```
Comment (lrytz) [inline src/library/scala/collection/StrictOptimizedSeqOps.scala]: just remove them instead of leaving as comments?

**Review by lrytz — COMMENTED** [review]
Looks great..!

File: test/files/neg/sd128.check (hunk 3 above)
Comment (adriaanm) [reply test/files/neg/sd128.check]: Right, it probably doesn't fire because `override` is implied for Java members (the flag won't be set explicitly)

Comment (lrytz) [reply test/files/neg/sd128.check]: Should https://github.com/scala/scala/blob/cc8ba5e39b46a3ed78f9575b96764939587c0d71/src/compiler/scala/tools/nsc/typechecker/RefChecks.scala#L442-L447 catch it?

Comment (adriaanm) [reply test/files/neg/sd128.check]: yeah, the isAnyOverride should also consider all concrete Java members to be overrides

Comment (adriaanm) [reply test/files/neg/sd128.check]: well, i guess it should be an additional check (or maybe all callers of isAnyOverride would benefit... not sure)

Comment (adriaanm) [reply test/files/neg/sd128.check]: see also https://github.com/scala/scala/pull/7439/files#diff-e2cfc09e4d7c753232666c6e31bd1926R429

**Comment by adriaanm** [comment]
Addresses review feedback.

**Comment by adriaanm** [comment]
The 2.12 community build (link in description above) reported the following errors:

```

[dispatch] ufcheck/src/test/scala/cleanup.scala:15:29: !!! overriding def intersect(that: scala.collection.GenSet[unfiltered.spec.Cleanup]): scala.collection.mutable.HashSet[unfiltered.spec.Cleanup] (defined in trait GenSetLike);
[dispatch]  override def intersect(that: scala.collection.GenSet[unfiltered.spec.Cleanup]): scala.collection.mutable.Set[unfiltered.spec.Cleanup] (defined in trait SynchronizedSet) has incompatible type
[dispatch]   private val dirties = new HashSet[Cleanup] with SynchronizedSet[Cleanup]

[akka-http] akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala:219:25: !!! class General inherits conflicting members:
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.Strict (defined in trait Multipart) and
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.General.Strict (defined in trait General)
[akka-http] (note: this can be resolved by declaring an `override` in class General.);
[akka-http]  other members with override errors are: BodyPart
[akka-http]   sealed abstract class General extends Multipart with jm.Multipart.General {
[akka-http]                         ^
[akka-http] akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala:269:27: !!! class BodyPart inherits conflicting members:
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.BodyPart.Strict (defined in trait BodyPart) and
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.General.BodyPart.Strict (defined in trait BodyPart)
[akka-http] (note: this can be resolved by declaring an `override` in class BodyPart.)
[akka-http]     sealed abstract class BodyPart extends Multipart.BodyPart with jm.Multipart.General.BodyPart {
[akka-http]                           ^
[akka-http] akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala:328:25: !!! class FormData inherits conflicting members:
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.Strict (defined in trait Multipart) and
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.FormData.Strict (defined in trait FormData)
[akka-http] (note: this can be resolved by declaring an `override` in class FormData.);
[akka-http]  other members with override errors are: BodyPart
[akka-http]   sealed abstract class FormData extends Multipart with jm.Multipart.FormData {
[akka-http]                         ^
[akka-http] akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala:417:27: !!! class BodyPart inherits conflicting members:
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.BodyPart.Strict (defined in trait BodyPart) and
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.FormData.BodyPart.Strict (defined in trait BodyPart)
[akka-http] (note: this can be resolved by declaring an `override` in class BodyPart.)
[akka-http]     sealed abstract class BodyPart extends Multipart.BodyPart with jm.Multipart.FormData.BodyPart {
[akka-http]                           ^
[akka-http] akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala:533:25: !!! class ByteRanges inherits conflicting members:
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.Strict (defined in trait Multipart) and
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.ByteRanges.Strict (defined in trait ByteRanges)
[akka-http] (note: this can be resolved by declaring an `override` in class ByteRanges.);
[akka-http]  other members with override errors are: BodyPart
[akka-http]   sealed abstract class ByteRanges extends Multipart with jm.Multipart.ByteRanges {
[akka-http]                         ^
[akka-http] akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala:579:27: !!! class BodyPart inherits conflicting members:
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.BodyPart.Strict (defined in trait BodyPart) and
[akka-http] protected type Strict = akka.http.javadsl.model.Multipart.ByteRanges.BodyPart.Strict (defined in trait BodyPart)
[akka-http] (note: this can be resolved by declaring an `override` in class BodyPart.)
[akka-http]     sealed abstract class BodyPart extends Multipart.BodyPart with jm.Multipart.ByteRanges.BodyPart {
[akka-http]                           ^


[akka-more] akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala:441:16: !!! class AbstractPersistentFSM inherits conflicting members:
[akka-more] override def receive: AbstractPersistentFSM.this.Receive (defined in trait PersistentFSMBase) and
[akka-more] def receive: AbstractPersistentFSM.this.Receive (defined in trait PersistentActor)
[akka-more] (note: this can be resolved by declaring an `override` in class AbstractPersistentFSM.)
[akka-more] abstract class AbstractPersistentFSM[S <: FSMState, D, E] extends AbstractPersistentFSMBase[S, D, E] with PersistentFSM[S, D, E] {
[akka-more]                ^

[cats] core/src/main/scala/cats/data/WriterT.scala:145:9: !!! <$anon: cats.data.WriterTMonadError[F,L,E]> inherits conflicting members:
[cats] override def ap[A, B](ff: cats.data.WriterT[F,L,A => B])(fa: cats.data.WriterT[F,L,A]): cats.data.WriterT[F,L,B] (defined in trait FlatMap) and
[cats] def ap[A, B](f: cats.data.WriterT[F,L,A => B])(fa: cats.data.WriterT[F,L,A]): cats.data.WriterT[F,L,B] (defined in trait WriterTApply)
[cats] (note: this can be resolved by declaring an `override` in <$anon: cats.data.WriterTMonadError[F,L,E]>.)
[cats]     new WriterTMonadError[F, L, E] {
[cats]         ^
[cats] core/src/main/scala/cats/data/WriterT.scala:438:28: !!! trait WriterTMonadError inherits conflicting members:
[cats] override def ap[A, B](ff: cats.data.WriterT[F,L,A => B])(fa: cats.data.WriterT[F,L,A]): cats.data.WriterT[F,L,B] (defined in trait FlatMap) and
[cats] def ap[A, B](f: cats.data.WriterT[F,L,A => B])(fa: cats.data.WriterT[F,L,A]): cats.data.WriterT[F,L,B] (defined in trait WriterTApply)
[cats] (note: this can be resolved by declaring an `override` in trait WriterTMonadError.)
[cats] sealed private[data] trait WriterTMonadError[F[_], L, E]
[cats]                            ^

[algebra] core/src/main/scala/algebra/lattice/Bool.scala:77:7: !!! class BoolFromBoolRing inherits conflicting members:
[algebra] override def meet(a: A,b: A): A (defined in trait GenBool) and
[algebra] def meet(a: A,b: A): A (defined in trait Heyting)
[algebra] (note: this can be resolved by declaring an `override` in class BoolFromBoolRing.);
[algebra]  other members with override errors are: join
[algebra] class BoolFromBoolRing[A](orig: BoolRing[A]) extends GenBoolFromBoolRng(orig) with Bool[A] {
[algebra]       ^

```

They are likely correct, but will check.

**Comment by adriaanm** [comment]
Working on reproducing these in isolation, but so far haven't managed for akka-http with:
```java
public interface JmMultipart {
    interface Strict extends JmMultipart { }

    interface BodyPart {
        interface Strict extends JmMultipart.BodyPart {  }
    }

    interface General extends JmMultipart {
        interface Strict extends JmMultipart.General, JmMultipart.Strict {  }

        interface BodyPart extends JmMultipart.BodyPart {
            interface Strict extends JmMultipart.General.BodyPart, JmMultipart.BodyPart.Strict {  }
        }
    }
}
```

```scala
sealed trait Multipart extends JmMultipart

object Multipart {
  trait Strict extends Multipart with JmMultipart.Strict

  trait BodyPart extends JmMultipart.BodyPart

  object BodyPart {
    trait Strict extends Multipart.BodyPart with JmMultipart.BodyPart.Strict
  }

  sealed abstract class General extends Multipart with JmMultipart.General

  object General {
    class Strict extends Multipart.General with Multipart.Strict with JmMultipart.General.Strict
  }
}
```

**Review by lrytz — APPROVED** [review]
LGTM, feel free to merge once you convinced yourself that the akka errors are correct.

**Comment by adriaanm** [comment]
Ok, found the repro -- compile these two java files and scala source with scalac to get the error:

```
public interface Multipart { interface Strict { } }
```

```
public interface General { interface Strict {} }
```

```
class Clash extends Multipart with General
```


```
error: cannot override a concrete member without a third member that's overridden by both (this rule is designed to prevent ``accidental overrides'')
protected type Strict = Multipart.Strict (defined in trait Multipart)
  with protected type Strict = General.Strict (defined in trait General)
class Clash extends Multipart with General
      ^
```

(The error is slightly different because this is coming from a compiler that give this synthetic alias the `JAVA` flag.)

**Comment by adriaanm** [comment]
The underlying cause is that these static nested interfaces are represented by our java parser as protected type aliases, which are inherited -- unlikely the interfaces they're attempting to encode.

**Comment by smarter** [comment]
From https://github.com/scala/scala/commit/f01092ade64917a1481607fe5456d1eb912f34b4:
> Also, pull up exemption for synthetic members from refchecks; it makes no sense to bother the user about members synthesized by the compiler. We could get early warnings this way, but eventually they'll pop up as VerifyErrors...

If my compiler is miscompiling I'd really rather learn about it at compile-time than runtime.

**Comment by adriaanm** [comment]
Dropped that part.

**Comment by adriaanm** [comment]
The related errors in akka-http are fixed by:
```
package ccompat {
  import akka.http.scaladsl.model.Uri.Query

   import scala.collection.immutable.LinearSeq
  import scala.collection.{ IterableOnce, StrictOptimizedLinearSeqOps }
  import scala.collection.mutable.Builder

  trait QuerySeqOptimized extends LinearSeq[(String, String)]
    with StrictOptimizedLinearSeqOps[(String, String), LinearSeq, Query] { self: Query ⇒

    override protected def newSpecificBuilder: Builder[(String, String), Query] = akka.http.scaladsl.model.Uri.Query.newBuilder
    override protected def fromSpecific(coll: IterableOnce[(String, String)]): Query =
      Query(coll.iterator.to(Seq): _*)
  }
}
```

in akka-http-core/src/main/scala-2.13+/akka/http/ccompat/package.scala

**Comment by adriaanm** [comment]
Merging -- the Travis issue is unrelated.

**Comment by adriaanm** [comment]
Submitted as https://github.com/akka/akka-http/pull/2479

**Comment by hrhino** [comment]
Wow! :tada:
