### PR TITLE
[10765] TrieMaps handle null values, and TrieMapTest tests TrieMaps

### LINKED ISSUE #10765: Odd Undocumented TrieMap Behavior with null Values
Scala version: 2.12.4
java version: 1.8.0_161
OS:  ubuntu 16.04 LTS

The following is an issue I encountered with mapping a key to null in TrieMap (I have not confirmed that this behavior occurs with other Map implementations):

```scala
scala> /* let's start with a TrieMap with "a" mapped to null */
     | val trieMap = scala.collection.concurrent.TrieMap[String, String]("a" -> null)
trieMap: scala.collection.concurrent.TrieMap[String,String] = TrieMap(a -> null)

scala> /* looks good, let's retrieve the value associated with "a" */
     | trieMap("a")
java.util.NoSuchElementException
  at scala.collection.concurrent.TrieMap.apply(TrieMap.scala:837)
  ... 35 elided

scala> /* wait... what?  It just showed it was mapped to null */
     | trieMap.get("a")
res4: Option[String] = None

scala> /* really?  So this should return false */
     | trieMap contains "a"
res6: Boolean = false

scala> /* And so it does.  So how many entries are there? */
     | trieMap.size
res8: Int = 1

scala> /* So... to what is that one entry mapped? */
     | val iterator = trieMap.iterator
iterator: Iterator[(String, String)] = non-empty iterator

scala> /* there is an item there, isn't there? */
     | iterator.hasNext
res11: Boolean = true

scala> /* ok, so what is it? */
     | iterator.next
res13: (String, String) = (a,null)

scala> /* right back where we started... */
```
So is TrieMap supposed allow null values?  If so, let them be queried and retrieved just like all other mapped values.  If not, don't allow it as a value in the first place.  My preference is to allow null values, but either way, please document the behavior thoroughly.

### PR DESCRIPTION
**Pull request by joshlemer**
closes scala/bug#10765 

This fixes TrieMaps so that they can handle null values.

### Reasons why TrieMaps were not able to support null values previously

`null`s were not able to be stored in `TrieMap`s previously because of two reasons
* `INode#rec_lookup(...): AnyRef` method returned `null` to indicate that there is no value associated with key `k`. However, if `null` is associated with `k`, then callers of this method would of course interpret this return value to mean that no value is associated with `k`.
* `INode#rec_remove(..., v: V, ...): Option[V]` interpreted `v == null` to mean "remove key `k` from the map, no matter what value is associated with it". Otherwise, the behaviour is "remove `k` only if its value is equal to `v`. 

### Summary of changes

* `INode#rec_lookup(...): AnyRef` method now returns a newly added, package-private sentinel value `INodeBase.NO_SUCH_ELEMENT_SENTINEL`, in the case that there is no value associated to `k`. This allows callers to distinguish missing values from null values.
* All callers of `rec_lookup` now check for `NO_SUCH_ELEMENT_SENTINEL` and convert the result to appropriate exception throws / `Option[V]` / etc
* `INode#rec_remove` has a new argument `removeAlways: Boolean`. When `removeAlways` is `true`, `(k, v)` will be removed regardless of what `v`'s value is. When `removeAlways` is false, `(k, v)` is removed only when `v` matches the passed value of `v`.

* `INode#rec_insertif`'s argument `cond: AnyRef` had three valid arguments:
```
null - don't care if the key was there; KEY_ABSENT - key wasn't there; KEY_PRESENT - key was there; other value `v` - key must be bound to `v`
```

It now has an explicitly named non-null value, `KEY_PRESENT_OR_ABSENT`, to represent the previous null condition. While this is not directly related to handling null values in TrieMaps, I thought it is good practice to not use `null` sentinel values because of the trouble it is causing us already in this issue.

* `TrieMap#lookup(k: K): V` has been deprecated, but maintains its previous behavior to not break existing code. That is, it returns `null` if `k` is not absent. However, it also will return `null` if the value associated with `k` was `null`. Users are now directed to:
```scala
  @deprecated("Use getOrElse(k, null) instead.", "2.13.0")
```

* Extensive unit tests for behavior with respect to null values.

### CODE REVIEW

File: src/library/scala/collection/concurrent/TrieMap.scala [hunk 1]
```diff
@@ -988,6 +992,8 @@ object TrieMap extends MapFactory[TrieMap] {
 
   val inodeupdater = AtomicReferenceFieldUpdater.newUpdater(classOf[INodeBase[_, _]], classOf[MainNode[_, _]], "mainnode")
 
+  private[concurrent] val NoSuchElementSentinel: AnyRef = new AnyRef
```
Comment (Jasper-M) [inline src/library/scala/collection/concurrent/TrieMap.scala]: The `RESTART` sentinel is defined in a separate Java class. Don't know if it really makes a difference, but just saying...

File: src/library/scala/collection/concurrent/TrieMap.scala [hunk 2]
```diff
@@ -839,13 +842,14 @@ final class TrieMap[K, V] private (r: AnyRef, rtupd: AtomicReferenceFieldUpdater
   override def apply(k: K): V = {
     val hc = computeHash(k)
     val res = lookuphc(k, hc)
-    if (res eq null) throw new NoSuchElementException
+    if (res eq NoSuchElementSentinel) throw new NoSuchElementException
```
Comment (Jasper-M) [inline src/library/scala/collection/concurrent/TrieMap.scala]: I think `lookup` also needs to be adjusted. I don't know why that method is even public. And `getOrElseUpdate` seems to depend on `lookup` returning `null` for missing keys. The fix is probably explicitly returning `null` in `lookup` (and deprecating it...), and using something else than `lookup` in `getOrElseUpdate`.

File: test/junit/scala/collection/concurrent/TrieMapTest.scala [hunk 3]
```diff
@@ -72,7 +72,7 @@ class TrieMapTest {
 
   @Test
   def nullValues_t10765: Unit = {
-    val trieMap = TreeMap[String, String]("a" -> null)
+    val trieMap = TrieMap[String, String]("a" -> null)
```
Comment (Jasper-M) [inline test/junit/scala/collection/concurrent/TrieMapTest.scala:75]: Probably best to also remove the import at the top.

**Review by Jasper-M — COMMENTED** [review]
I suspect this change is probably fine, modulo my comments below, but I'm not even going to try to understand this algorithm and the test coverage is not exactly overwhelming, so I'm not sure we're not still missing some things.

**Comment by joshlemer** [comment]
@SethTisue @Jasper-M I think this is ticket is ready for a review now.

**Comment by Jasper-M** [comment]
LGTM as far as I can tell.
Great job!

**Comment by joshlemer** [comment]
@Jasper-M can I merge this?

**Comment by Jasper-M** [comment]
I think it's probably best if someone else takes another look.

**Review by julienrf — APPROVED** [review]

**Comment by SethTisue** [comment]
@joshlemer looks like this is ready to merge. can you rebase+squash?

**Comment by joshlemer** [comment]
@SethTisue now squashed/rebased

**Comment by joshlemer** [comment]
@SethTisue @julienrf let's launch the 🚀 🚀 🚀's  😄

**Comment by SethTisue** [comment]
`unsafePerformIO $ mergePullRequest 7087`
