### PR TITLE
Trailing comma is parsed

### LINKED ISSUE #11900: Trailing commas in function bodies and constructors
Hello! Scala compiler allows trailing comma in the lambda body, function body and constructors. Is it bug or correct behavior? Looks a little weird.

In a [SIP-27](https://docs.scala-lang.org/sips/trailing-commas.html) I've read:

> Following Dr. Martin Odersky’s suggestion, the proposal is that trailing commas are only supported in comma-separated elements that are enclosed by parentheses, square brackets or curly braces (), ], and }, respectively).

Is function bodies comma-separated elements?

## reproduction steps

```scala
List(1, 2, 3).map {
  a => a + 1,
}

class A() {
  println("a"),
}

def b() = {
  println("b"),
}

new A()
b()
```

## problem

Code compiles

## expectation

Code doesn't compile

Related https://github.com/scalameta/scalafmt/issues/1410#issuecomment-593132277

### PR DESCRIPTION
**Pull request by som-snytt**
Instead of taking any old comma in scanner, let parser
target when skipping a trailing comma makes sense.

Bring the implementation closer to the SIP.

Fixes scala/bug#11900

### CODE REVIEW

**Comment by som-snytt** [comment]
The quasiquote error also progressed.

This is no longer given a pass:
```

Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 11.0.3).
Type in expressions for evaluation. Or try :help.

scala> import concurrent._, ExecutionContext.Implicits._
import concurrent._
import ExecutionContext.Implicits._

scala> Future { 42,
     | }
res0: scala.concurrent.Future[Int] = Future(<not completed>)

scala> Future { 42,
     | 27,
                  ^
       error: ';' expected but ',' found.

scala>
```

**Comment by som-snytt** [comment]
I think I punned on the song title recently, but was it "Comma Chameleon"?

I wonder if @SethTisue happens to remember.

**Review by dwijnand — APPROVED** [review]
LGTM.  Thanks, @som-snytt!

**Comment by som-snytt** [comment]
I'll tweak for those couple of test errors: the syntax check for `_*` error messaging (my early contribution inn 2012!) changed to post-parser. I'll either `--update-check` or tweak the parser.

**Comment by som-snytt** [comment]
Probably the old parser code to detect misplaced sequence pattern doesn't provide a lot of value; the error messaging in `badPattern3` was catering to XML.

Currently, doti doesn't even support `case x * y =>` let alone `case _ * y =>`.

**Comment by som-snytt** [comment]
I restored the EOF check for REPL, since REPL can't see around the corner to the next line, which hasn't been input yet. That's another argument for deferring the error for "position of `_*`" to typer.

**Comment by som-snytt** [comment]
The LOC in `lookingAhead` to restore `sepRegions` is not required, but I had an intermediate version break by looking ahead into parens, which mutates `sepRegions` on `nextToken`.

**Comment by som-snytt** [comment]
@dwijnand Sorry for the premature squash (and rebase). The tweak was to `tupleInfixType`, which distinguishes `()` and `(tuple)` and either of those followed by `=> R`. It goes though `inParens` for trailing comma handling.

The other bit that does trailing comma is still `commaSeparated`.

I plan to forward port to Scala 3, which is mechanically similar. I won't be able to port the name `inGroupers`, however, as Scala 3 already has a boring name for that method.

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala [hunk 1]
```diff
@@ -287,8 +275,12 @@ self =>
      */
     @inline final def lookingAhead[T](body: => T): T = {
       val saved = new ScannerData {} copyFrom in
+      val seps  = in.sepRegions
```
Comment (dwijnand) [inline src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:278]: Do you think this should be part of copyFrom?

**Review by dwijnand — APPROVED** [review]
Difficult for me to be sure of all the changes, but the code+test changes all seem reasonable and everything's passing so LGTM.

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:278]: The scope is clear here: looking ahead into a bracket shouldn't change state. copyFrom is a low-level op used by nextToken, which reasons about sepRegions and mutates next/prev.

The use case here is: inParens, looking ahead sees a close paren, which is legal for empty parens.

**Comment by som-snytt** [comment]
@SethTisue I wonder if this is a candidate for 2.13.2. The bug is minor, the fix is fundamental. I haven't seen if the milestone is pushed to post-covid-19, depending on your time zone: it's already post-covid in Shanghai.

**Comment by SethTisue** [comment]
let's see what the community build has to say: ~~https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3303/~~ https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3305/

**Comment by som-snytt** [comment]
Community build errors...

Look Ma, caught an illegal trailing comma!

https://github.com/vlovgr/ciris/pull/329

```
[ciris] [info] Done compiling.
[ciris] Running "test" in: core
[ciris] [info] Compiling 15 Scala sources to /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/ciris-75d2ddeeb7ee1a9d90de9a4aaeedddec54eaaada/modules/core/target/scala-2.13/test-classes ...
[ciris] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/ciris-75d2ddeeb7ee1a9d90de9a4aaeedddec54eaaada/modules/core/src/test/scala/ciris/ConfigValueSpec.scala:301:86: ';' expected but ',' found.
[ciris] [error]       ConfigValue.eval(IO.raiseError[ConfigValue[String]](ConfigError("").throwable)),
[ciris] [error]                                                                                      ^
[ciris] [error] one error found
[ciris] [error] (core / Test / compileIncremental) Compilation failed
```
and presumably unrelatedly
```
[parboiled] [info] Done compiling.
[parboiled] [info] CoreTest:
[parboiled] [info] CoreTest *** ABORTED ***
[parboiled] [info]   java.lang.AbstractMethodError: Method CoreTest.org$scalatest$Assertions$_setter_$assertionsHelper_$eq(Lorg/scalatest/Assertions$AssertionsHelper;)V is abstract
[parboiled] [info]   at CoreTest.org$scalatest$Assertions$_setter_$assertionsHelper_$eq(CoreTest.java)
[parboiled] [info]   at org.scalatest.Assertions.$init$(Assertions.scala:527)
[parboiled] [info]   at org.scalatestplus.testng.TestNGSuite.&lt;init&gt;(TestNGSuite.scala:67)
[parboiled] [info]   at org.scalatestplus.testng.TestNGWrapperSuite.&lt;init&gt;(TestNGWrapperSuite.scala:51)
[parboiled] [info]   at CoreTest.&lt;init&gt;(CoreTest.java:12)
[parboiled] [info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[parboiled] [info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[parboiled] [info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[parboiled] [info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[parboiled] [info]   at java.lang.Class.newInstance(Class.java:442)
[parboiled] [info]   ...
```
footnote: it doesn't say if scalatestplus and scalatest must have same point release (as they do in the parboiled build).
```
[parboiled] All Dependencies for subproject parboiled-core:
[parboiled]    org.scala-lang:scala-compiler:2.13.2-bin-c3f67e5-SNAPSHOT:scala-tool-&gt;default,optional(default)
[parboiled]    org.scala-lang:scala-library:2.13.2-bin-c3f67e5-SNAPSHOT:scala-tool-&gt;default,optional(default)
[parboiled]    com.lightbend:cloc-plugin:0.0.1-dbuildxac0b200f66a81959c03a4acbc81a89b75f6bb1da:plugin-&gt;default(compile)
[parboiled]    scalacommunitybuild:scalatest:3.0.8-dbuildxdf967da13d943304e5ff309623f2ece41dca02f3:test
[parboiled]    org.scalatestplus:testng-6-7:3.1.0.0-dbuildx2a7aa0124b1224b709b1031a4cee29bac1b315f9:test
```

**Comment by SethTisue** [comment]
I pushed a fix for the parboiled thing, which is indeed unrelated.
