### PR TITLE
Exhaustivity: don't widen & then warn on singleton types

### LINKED ISSUE #11603: Match exhaustion warning on literal type
```scala
class C {
  def m(x: true) = x match {
    case true => println("the one true path")
  }
}
```

```
14:53:27 $ scala exhaustive-literals.scala
exhaustive-literals.scala:2: warning: match may not be exhaustive.
It would fail on the following input: false
  def m(x: true) = x match {
                   ^
```

Scala 2.13.0

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes https://github.com/scala/bug/issues/11603

### CODE REVIEW

**Comment by dwijnand** [comment]
An ambitious attempt at "just" shuffling some widen's around... but it didn't seem to produce unwanted effects after a quick `partest --update-check --grep patmat` run.  So let's see what the whole suite (+ bootstrapped) says...

File: src/compiler/scala/tools/nsc/transform/patmat/MatchOptimization.scala [hunk 1]
```diff
@@ -556,7 +556,7 @@ trait MatchOptimization extends MatchTreeMaking with MatchAnalysis {
         else {
           // match on scrutSym -- converted to an int if necessary -- not on scrut directly (to avoid duplicating scrut)
           Some(BLOCK(
-            ValDef(scrutSym, scrut),
+            ValDef(scrutSym.setInfo(scrutSym.tpe.widen), scrut),
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/transform/patmat/MatchOptimization.scala]: What happens if the type is not changed here?

**Review by lrytz — COMMENTED** [review]
Not so easy for me to really review as I barely know anything about the patamat implementation. Generally it looks fine, the check file updates look OK. The `setInfo` down in `emitSwitch` is a little suspicious.

File: src/compiler/scala/tools/nsc/transform/patmat/MatchOptimization.scala (hunk 1 above)
Comment (dwijnand) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchOptimization.scala]: Then the typechecking that happens in `MatchTransformer#transform` (i.e. when the `translateMatch` there returns) will rewrite `x match {` into `true match {` which isn't an Ident and thus will blows up in CleanUp (look for "these assumptions about the shape of the tree are justified by the codegen in MatchOptimization" in `CleanUp`). 

I don't understand why that type-checking is done there, but if it helps I could unpack the Tree into Block/Match/scrutinee right before it and shift this change to there.

As I see it `setInfo` is what `freshSym` does, so, apart from also dodging some `elimAnonymousClass` and `repeatedToSeq` modifiers, this is pretty much applying that delayed widening now that it matters.

I think it would be nice if singleton types started to work properly in the pattern matching analysis code, but it's tricky business...

Comment (lrytz) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchOptimization.scala]: Maybe it's not too hard to generalize this assumption in CleanUp, let's give that a try.

File: src/compiler/scala/tools/nsc/transform/CleanUp.scala [hunk 2]
```diff
@@ -398,12 +398,15 @@ abstract class CleanUp extends Statics with Transform with ast.TreeDSL {
...
     def transformSwitch(sw: Match): Tree = { import CODE._
-      sw.selector.tpe match {
+      sw.selector.tpe.widen match {
         case IntTpe => sw // can switch directly on ints
         case StringTpe =>
           // these assumptions about the shape of the tree are justified by the codegen in MatchOptimization
-          val Match(Typed(selTree: Ident, _), cases) = sw
-          val sel = selTree.symbol
+          val Match(Typed(selTree, _), cases) = sw
+          val selArg = selTree match {
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/transform/CleanUp.scala]: I'm not sure if this should be a `def` to avoid structural sharing in the AST. Since trees have mutable fields (`.tpe`, `.pos`) this might be a problem - I'm really not sure if it matters in practice. @retronym what's your intuition?

**Review by lrytz — COMMENTED** [review]
Very nice!

File: src/compiler/scala/tools/nsc/transform/CleanUp.scala (hunk 2 above)
Comment (dwijnand) [reply src/compiler/scala/tools/nsc/transform/CleanUp.scala]: Oh!  Wow, yeah, good catch, thanks.  Let's do that.

**Review by lrytz — APPROVED** [review]
