### PR TITLE
Avoid comparing RefinementClassSymbols with isSubClass in RefChecks

### LINKED ISSUE #13013: Infinite recursion in RefChecks
```scala
object Node {
  trait Root { self: Node =>
    val root = this
  }
}
trait Node {
  def root: Node
}
final class RootNode extends Node with Node.Root
```

Compiles on 2.12, crashes in RefChecks on 2.13.14

```
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkOverrideTerm$1(RefChecks.scala:557)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkOverrideTypes$1(RefChecks.scala:565)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkOverride$1(RefChecks.scala:393)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkAllOverrides(RefChecks.scala:582)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkOverrideTerm$1(RefChecks.scala:557)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkOverrideTypes$1(RefChecks.scala:565)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkOverride$1(RefChecks.scala:393)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkAllOverrides(RefChecks.scala:582)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkOverrideTerm$1(RefChecks.scala:557)
```

### PR DESCRIPTION
**Pull request by lrytz**
RefinementClassSymbols are created ad hoc for types in asSeenFrom, two symbols with the same parents don't compare `isSubClass`.

This regressed compared to 2.12.x in https://github.com/scala/scala/pull/7439, which is a pretty complex PR. I didn't revisit all the discussions from back then, so it's possible I missed something.

Fixes https://github.com/scala/bug/issues/13013

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/RefChecks.scala [hunk 1]
```diff
@@ -97,11 +97,17 @@ abstract class RefChecks extends Transform {
...
-        case (prevBase, prevTp) => currentBase.isSubClass(prevBase) && rt =:= prevTp.asSeenFrom(currentBase.thisType, prevBase)
+        case (prevBase, prevTp) =>
+          val isSub = (currentBase, prevBase) match {
+            case (cRef: RefinementClassSymbol, pRef: RefinementClassSymbol) =>
+              cRef.info.parents.map(_.typeSymbol) == pRef.info.parents.map(_.typeSymbol)
+            case _ =>
+              currentBase.isSubClass(prevBase)
+          }
+          val sameTp = rt =:= prevTp.asSeenFrom(currentBase.thisType, prevBase)
+          isSub && sameTp
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:108]: I'm wondering if instead we should just return "true" (== "not yet checked" for the `case (cRef: RefinementClassSymbol, pRef: RefinementClassSymbol)`.  If I understand this correctly, this is a caching optimization, so returning false would always be correct, at the risk of repeating some work.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:108]: I think it's rather a visit log to stop recursion than a cache; that said

```scala
    private def notYetCheckedOrAdd(rt: RefinedType, currentBase: Symbol) = currentBase match {
      case _: RefinementClassSymbol => false
      case _ => // old code
    }
```

passes the test and doesn't break any existing ones. So maybe it's correct to assume that once the SymbolPair.base is a `RefinementClassSymbol` we don't need to keep calling `checkAllOverrides`? I'm not too sure. We're in

```
def checkOverride(pair: SymbolPair)
  ...
  if (member.isStable)
    ...
    lowType.normalize.resultType match {
      case rt: RefinedType if notYetCheckedOrAdd(rt, pair.base) =>
        ...
        checkAllOverrides(rt.typeSymbol) // needed if `pair.base` is `RefinementClassSymbol`?
```

The bug we're fixing is an endless recursion through this `checkAllOverrides` call.

Comment (retronym) [reply src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:108]: Let's go with the version you proposed... its hard to trust the test coverage enough to short circuit.

**Review by retronym — APPROVED** [review]
