### PR TITLE
Prevent accidentally dropping annotations

### LINKED ISSUE #13140: Some annotations are not visible in macros since 2.13.17
I've got a macro which inspects the annotations on the fields of a case class. Starting with 2.13.17, annotations which extend a class with a parameter are no longer visible in the macro.

Given the following annotations:

```scala
import scala.annotation.StaticAnnotation

sealed trait InputAnnotation extends StaticAnnotation

// works
class path extends InputAnnotation
class query(val name: String = "") extends InputAnnotation

// problematic
class body(val s: String) extends InputAnnotation
class jsonbody extends body("x")
```

and the given class:

```scala
case class Product(
    @jsonbody id: String,
    @path name: String,
    @query("age") age: Int
)
```

The `path` and `query` annotations are visible in the macro (through the field's `Symbol.annotations`), while the `jsonbody` is not.

This used to work fine in 2.13.16. Specifically, I found this bug through a failing [tapir dependency update](https://github.com/softwaremill/tapir/pull/4856). This continues to work fine in Scala 2.12 and 3.

Here's a macro to reproduce the problem: https://github.com/adamw/scala2-ann-bug

When you compile the code, it will output the found annotations:

```
sbt:root> tc
[info] compiling 2 Scala sources to /Users/adamw/projects/temp/scala2-ann-bug/macros/target/scala-2.13/classes ...
[info] compiling 1 Scala source to /Users/adamw/projects/temp/scala2-ann-bug/test/target/scala-2.13/classes ...
[info] /Users/adamw/projects/temp/scala2-ann-bug/test/src/main/scala/test/TestMacro.scala:14:26: Inspecting case class: test.Product
[info]     printFieldAnnotations[Product]
[info]                          ^
[info] /Users/adamw/projects/temp/scala2-ann-bug/test/src/main/scala/test/TestMacro.scala:14:26: Field: id : String
[info]     printFieldAnnotations[Product]
[info]                          ^
[info] /Users/adamw/projects/temp/scala2-ann-bug/test/src/main/scala/test/TestMacro.scala:14:26:   - No annotations
[info]     printFieldAnnotations[Product]
[info]                          ^
[info] /Users/adamw/projects/temp/scala2-ann-bug/test/src/main/scala/test/TestMacro.scala:14:26: Field: name : String
[info]     printFieldAnnotations[Product]
[info]                          ^
[info] /Users/adamw/projects/temp/scala2-ann-bug/test/src/main/scala/test/TestMacro.scala:14:26:   - Annotation: macros.path = new macros.path()
[info]     printFieldAnnotations[Product]
[info]                          ^
[info] /Users/adamw/projects/temp/scala2-ann-bug/test/src/main/scala/test/TestMacro.scala:14:26: Field: age : Int
[info]     printFieldAnnotations[Product]
[info]                          ^
[info] /Users/adamw/projects/temp/scala2-ann-bug/test/src/main/scala/test/TestMacro.scala:14:26:   - Annotation: macros.query = new macros.query("age")
[info]     printFieldAnnotations[Product]
[info]                          ^
```

Note that there are no annotations found on the `id` field. If you change the Scala version in the build to 2.13.16, clean and recompile, the annotation appears:

```
[info] /Users/adamw/projects/temp/scala2-ann-bug/test/src/main/scala/test/TestMacro.scala:14:26: Field: id : String
[info]     printFieldAnnotations[Product]
[info]                          ^
[info] /Users/adamw/projects/temp/scala2-ann-bug/test/src/main/scala/test/TestMacro.scala:14:26:   - Annotation: macros.jsonbody = new macros.jsonbody()
```

### PR DESCRIPTION
**Pull request by lrytz**
Explicitly define "target meta annotations" in the compiler.

When target annotations `@(deprecated @getter)` were introduced, all annotations in the package `annotation.meta` were target annotations.

In the meantime there are others, which broke annotation filtering.

```
    def mkFilter(category: Symbol, defaultRetention: Boolean)(ann: AnnotationInfo) =
      (ann.targetAnnotations, ann.defaultTargets) match {
        case (Nil, Nil)      => defaultRetention
        case (Nil, defaults) => defaults contains category
        case (metas, _)      => metas exists (_ matches category)
      }
```

we ended up in the second case with `defaults` being the `superArg` meta annotation, which is not a target annotation.

Fixes https://github.com/scala/bug/issues/13140

### CODE REVIEW

File: src/reflect/scala/reflect/internal/AnnotationInfos.scala [hunk 1]
```diff
@@ -348,20 +347,18 @@ trait AnnotationInfos extends api.Annotations { self: SymbolTable =>
...
+     *  targetAnnotations = List(getter).
      */
     def symbol = atp.typeSymbol
 
-    /** These are meta-annotations attached at the use site; they
-     *  only apply to this annotation usage.  For instance, in
-     *    `@(deprecated @setter @field) val ...`
-     *  metaAnnotations = List(setter, field).
+    /** These are target annotations attached at the use site; they only apply to this annotation usage.
+     * For instance, in `@(deprecated @setter @field) val ...` we get `targetAnnotations = List(setter, field)`.
```
Comment (som-snytt) [inline src/reflect/scala/reflect/internal/AnnotationInfos.scala:360]: One last chance to make the stars align. Edit: the stars are fine. A space for For.

**Review by som-snytt — APPROVED** [review]
I never met a Anne O'Tayshun I didn't like.

File: src/reflect/scala/reflect/internal/AnnotationInfos.scala (hunk 1 above)
Comment (lrytz) [reply src/reflect/scala/reflect/internal/AnnotationInfos.scala:360]: Right, what I did here is not even one of the options.

Personally I can enjoy all formatting styles equally, the only thing that bothers me is not knowing which one I'm supposed to use.

Comment (som-snytt) [reply src/reflect/scala/reflect/internal/AnnotationInfos.scala:360]: You are very easy-going, which benefits everyone.
