### PR TITLE
Under `-Xsource:3`, adjust 2.13.9 change to ignore override type for whitebox macro expansion

### LINKED ISSUE #12647: [2.13.9, 2.13.10] Issue with zio-prelude `1.0.0-RC8-1` (zio1) macros
There's an issue between Scala 2.13.9 and zio-prelude `1.0.0-RC8-1` (last version published supporting ZIO1) macros:

```scala
import zio.prelude.*

object LongNatural extends Subtype[Long] {
  //noinspection TypeAnnotation                            // IntelliJ annnotation
  @SuppressWarnings(Array("scalafix:ExplicitResultTypes")) // scalafix annotation
  override def assertion = assert(greaterThanOrEqualTo(0L))

  def zero: LongNatural = LongNatural(0L)
}
```

is failing to compile with the following error:
```scala
[error]  Newtype Assertion Failed 
[error] We were unable to read your assertion at compile-time.
[error] This is because you have annotated `def assertion` with its type signature:
[error] 
[error]     override def assertion: QuotedAssertion[Long] = assert(...)
[error]    
[error] Due to the macro machinery powering this feature, you MUST NOT ANNOTATE this method. 
[error] Try deleting the type annotation and recompiling. Something like:
[error] 
[error]     override def assertion = assert(...)
[error]     
[error]     def zero: LongNatural = LongNatural(0L)
[error]                                        ^
```

This was compiling fine with Scala 2.13.8.
Note that we're using the `-Xsource:3` flag.

### PR DESCRIPTION
**Pull request by som-snytt**
Improve the condition for inferring the type of an overriding def under `-Xsource:3`: use the precise type of the RHS if the RHS is the expansion of a whitebox macro.

Adjusts scala/scala#9891
Fixes scala/bug#12647

### CODE REVIEW

**Comment by som-snytt** [comment]
Probably the `openMacros` check can be removed.

`//t.tpe.typeSymbol.isAnonOrRefinementClass &&` also note it doesn't matter what the narrower type is, but this is the use case.

File: src/compiler/scala/tools/nsc/typechecker/Namers.scala [hunk 1]
```diff
@@ -1120,14 +1120,34 @@ trait Namers extends MethodSynthesis {
...
+     *  For `def m = f`, retrieve the typed RHS and check if it is an expansion;
+     *  in that case, check if the expandee `f` is whitebox and preserve
+     *  the precise type if it is. The user must provide an explicit type
+     *  to "opt out" of the inferred narrow type; in Scala 3, they would
+     *  inline the def to "opt in".
      */
     private def assignTypeToTree(tree: ValOrDefDef, defnTyper: Typer, pt: Type): Type = {
       val rhsTpe = tree match {
-        case ddef: DefDef if tree.symbol.isTermMacro => defnTyper.computeMacroDefType(ddef, pt)
+        case ddef: DefDef if tree.symbol.isTermMacro => defnTyper.computeMacroDefType(ddef, pt) // unreached, see methodSig
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Namers.scala:1136]: So this can be removed?

There's also a comment in `computeMacroDefType` saying

> if a macro def doesn't have explicitly specified return type, this method will be called again by `assignTypeToTree`

is that stale?

**Review by lrytz — APPROVED** [review]
LGTM otherwise, thank you! This fix makes sense 👍

File: src/compiler/scala/tools/nsc/typechecker/Namers.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Namers.scala:1136]: I was reluctant to expand the scope, as macros remain experimental.

**Comment by SethTisue** [comment]
@lrytz want to press "merge", here?
