### PR TITLE
Fix existential types toString

### LINKED ISSUE #10769: REPL confused by existential types
Those are bugs in the printer:
```scala
scala> val x: Int forSome { type A } = 42
x: Int[] = 42
```
this one by @alexknvl
```scala
scala> val x: x.type forSome { val x: x.type forSome { val x: String } } = "a"
x: x.type forSome { val x: x.type forSome { type x.type <: String } } = a
```
on Scala 2.12.4

### PR DESCRIPTION
**Pull request by joroKr21**
* `isSingletonExistential` - don't restrict upper bound
  * Refactor `safeToString` - don't print brackets for empty list

Fixes scala/bug#10769

### CODE REVIEW

File: src/reflect/scala/reflect/internal/Symbols.scala [hunk 1]
```diff
@@ -2836,8 +2836,8 @@ trait Symbols extends api.Symbols { self: SymbolTable =>
     /** Concatenate strings separated by spaces */
     private def compose(ss: String*) = ss filter (_ != "") mkString " "
 
-    def isSingletonExistential =
-      nme.isSingletonName(name) && (info.upperBound.typeSymbol isSubClass SingletonClass)
+    def isSingletonExistential: Boolean =
+      nme.isSingletonName(name)
```
Comment (dwijnand) [inline src/reflect/scala/reflect/internal/Symbols.scala:2840]: Wow, really surprised this doesn't change any tests.

Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Symbols.scala:2840]: I guess it didn't make any sense

**Review by lrytz — APPROVED** [review]
