### PR TITLE
Fix false-positive by-name implicit warnings with `-Wmacros`

### LINKED ISSUE #12072: Lints should respect `-Wmacros`
## reproduction steps

using Scala `2.13.3`:

Scastie showing the warning: https://scastie.scala-lang.org/r3Fnc5YcSzeA91CKs06EtQ

```scala
// libraryDependencies += "com.github.alexarchambault" %% "scalacheck-shapeless_1.14" % "1.2.5"

import org.scalacheck.Arbitrary

final case class X(s: String)
object X {
  implicit val arb: Arbitrary[X] = org.scalacheck.derive.MkArbitrary[X].arbitrary
}
```

## problem

Getting a warning:

```
Block result was adapted via implicit conversion (method apply) taking a by-name parameter
```

But the warning applies to the code generated by `shapeless.Lazy` macro, not user-written code. This makes it mandatory to disable the `-Xlint:byname-implicit` due to the massive amount of false positives whenever implicit derivation is used.

### PR DESCRIPTION
**Pull request by som-snytt**
Only warn about a block arg passed into the by-name param of an implicit method if it was an implicit view.

Fixes scala/bug#12072

This implements lrytz's suggestion on the ticket.
https://github.com/scala/bug/issues/12072#issuecomment-738812622

Confirmed that the Shapeless 2 solutions to the guide exercises now compile cleanly.

Since Shapeless is not relying on conversions, this PR ignores the ticket title as a red herring.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/RefChecks.scala [hunk 1]
```diff
@@ -2060,15 +2060,20 @@ abstract class RefChecks extends Transform {
...
-                    case _ =>
-                  }
-                case _ =>
-              }
+            def checkImplicitlyAdaptedBlockResult(t: Tree): Unit = {
+              def loop(t: Tree): Unit =
+                t match {
+                  case Apply(coercion, _) if t.isInstanceOf[ApplyImplicitView] =>
+                    coercion.symbol.paramLists match {
+                      case (p :: Nil) :: _ if p.isByNameParam => refchecksWarning(t.pos, s"Block result was adapted via implicit conversion (${coercion.symbol}) taking a by-name parameter", WarningCategory.LintBynameImplicit)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/RefChecks.scala]:
```suggestion
                      case (p :: Nil) :: _ if p.isByNameParam => refchecksWarning(t.pos, s"Block result was adapted via implicit conversion (${coercion.symbol}) taking a by-name parameter; statements are not evaluated eagerly", WarningCategory.LintBynameImplicit)
```

or something like that?

**Review by lrytz — COMMENTED** [review]
LGTM

File: src/compiler/scala/tools/nsc/typechecker/RefChecks.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/RefChecks.scala]: Or just the opposite. This is the opposite where only the result expression is adapted. I'll upgrade both messages!

**Comment by som-snytt** [comment]
I pushed messages for the two cases that are less cryptic.

The OP confusing case is that if a block is converted, the conversion applies only to the result expression. This matters if the method parameter is by-name.

The related confusing case is that if the method is overloaded, the conversion applies to the whole block, the opposite of the first case.

**Review by lrytz — APPROVED** [review]
Thanks!
