### PR TITLE
Fix BigDecimal.Range for some very small step sizes

### LINKED ISSUE #12073: Range.BigDecimal illegitim IllegalArgumentException (more than Int.MaxValue ) when end and inc are really small
## reproduction steps

using Scala (2.13.1),

```scala
object RangeBug extends App {
  val start = BigDecimal(-2E-34)
  val inc = BigDecimal(1E-34)
  val end = BigDecimal(1E-64)
  println(List.unfold(start){ prec =>
    Option.when(prec < end)(prec -> (prec + inc))
  })

  //this one fail
  println(Range.BigDecimal(start, end, inc).toList)
}

```

## Range.BigDecimal throws java.lang.IllegalArgumentException: More than Int.MaxValue elements

In this case, we can see constructing the range using List.unfold that this range only contain three elements:
```
List(-2.0E-34, -1.0E-34, 0E-35)
```
Therefore there is no reason for the Range.BigDecimal to fail.

### PR DESCRIPTION
**Pull request by cahilltr**
Checks if the start value is closer to zero than startlim because of issues caused by `num.minus(startlim, start)`.

These issues were caused by BigDecimal precision (underflow) during `num.minus(startlim, start)`, which caused the downstream values to be incorrect.  This resulted in operations where `num.quot(startdiff, step)` and/or `num.quot(enddiff, step)` were dividing a "larger number" by a "very small number" e.g. (1E-34/1E-64) where the result was larger than Int.MaxValue.

Fixes scala/bug#12073

review by @szeiger 
review by @Ichoran 
review by @lrytz

### CODE REVIEW

File: src/library/scala/collection/immutable/NumericRange.scala [hunk 1]
```diff
@@ -340,10 +340,18 @@ object NumericRange {
...
+          //   * (except with really small numbers)
           //   * there to the end
           val negone = num.fromInt(-1)
           val startlim  = if (posStep) negone else one
-          val startdiff = num.minus(startlim, start)
+          //Use start value if the start value is closer to zero than startlim
+          //   * e.g. .5 is closer to zero than 1 and -.5 is closer to zero than -1
+          val startdiff = {
+            if ((posStep && num.lt(startlim, start)) || (!posStep && num.gt(startlim, start)))
+              start
```
Comment (lrytz) [inline src/library/scala/collection/immutable/NumericRange.scala:351]: I don't know this code, but what surprises me here is that `startdiff` can be negative in the first case, if `posStep && num.lt(startlim, start)`.

Reading on, `waypointA` can be smaller than `start`. Is that intended?

Maybe it just doesn't matter, but I'd like to double-check.

Comment (cahilltr) [reply src/library/scala/collection/immutable/NumericRange.scala:351]: So `startdiff` is negative when crossing zero from negative to positive and the start is greater than -1 (between -1 and 0).
For example, in the original code, if  `start == -.75`, then `startdiff == -.25`.

`waypointA` can be smaller than start because it trips [num.lt(waypointB, end)](https://github.com/scala/scala/pull/9155/files#diff-82fe528d34183eb1be9c0c90e48cb447R359).  

[This test case](https://github.com/scala/scala/pull/9155/files#diff-b1c2caabda073bf0b48349132118c517R119), where range is `Range.BigDecimal(BigDecimal(-2E-34), BigDecimal(1E-64), BigDecimal(1E-34))` is an example of when `waypointA` would be less than `start` and how it works.

Apologies for the subpar explanation; if needed, I can work back through the changes and better document the what/why.

Comment (lrytz) [reply src/library/scala/collection/immutable/NumericRange.scala:351]: OK, thank you for confirming. I looked a bit more at the code with a number of examples and I see now how your fix works. Together with the new and existing tests, LGTM.

**Review by lrytz — APPROVED** [review]
