### PR TITLE
Check if setter is shadowed for assignment

### LINKED ISSUE #3194: this qualified field masked by argument
I can't say definitively this is a bug.  But I think it should be.  There is only one thing which "this.x" can mean.  It looks to me like this could be implemented with some extra logic in typedAssign.
```scala
class A(var x: Int)
class B(x: Int) extends A(x) { def update(z: Int) = this.x = z }
```
```scala
a.scala:2: error: reassignment to val
class B(x: Int) extends A(x) { def update(z: Int) = this.x = z }
                                                           ^
one error found
```
I would expect it to work like the common situation (common in java anyway) where one does:
```scala
def f(x: Int) = this.x = x
```

### PR DESCRIPTION
**Pull request by som-snytt**
Since a class parameter is an object-private member,
at least until it is eliminated in constructors,
it may shadow the setter of an actual member.

Check for this case before failing assignment.

Fixes scala/bug#3194

### CODE REVIEW

**Comment by som-snytt** [comment]
I remembered to do "draft" as in "free as in draft beer".

File: test/files/run/t3194.scala [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// scalac: -language:_
+import scala.util.chaining._
+
+class A(var x: Int)
+class B(x: Int) extends A(x) {
+  def update(v: Int): Unit = x = v
+}
+
+object Test extends App {
+  new B(27).tap(_.update(42)).ensuring(_.x == 42)
```
Comment (hrhino) [inline test/files/run/t3194.scala:10]: What do we need https://github.com/scala/nanotest-strawman/ for, again?

**Comment by lrytz** [comment]
Even if it's a bit of an anti-pattern, it's probably still good for the compiler to just do the right thing. So lgtm - @adriaanm wdyt?

**Comment by adriaanm** [comment]
sgtm!

**Comment by lrytz** [comment]
it works in dotty already (cc @smarter, see test case)

**Comment by som-snytt** [comment]
Looks like I was drafted. That's OK, I wasn't sure if this was too ad-hokey. It doesn't address the problem directly, which is `fixed in dotty`.

Edit: I see I actually implemented per paulp's suggestion on the ticket.
