### PR TITLE
fix `Range#contains` for very large negative starting values

### LINKED ISSUE #12635: Range.contains appears to have issues when start is sufficiently negative
## Reproduction steps

Scala Version: 2.13.8

```scala
def comment(s: String): Unit = {
  println()
  println(s)
}

def check(r: Range) = {
  val rejected = r.toList.filterNot(r.contains)
  println(s"$r does not contain $rejected")
}

comment("I'm not sure what makes this Range special, as an org.scalacheck.Gen[Range] I'm working on produced it.")
val testCase = Int.MinValue until 1092265081 by 359972081

comment(s"$testCase is small, and only contains a few elements:")
println(s"testCase: ${testCase.toList}")

comment("Expectation: a range will contain every value it produces, so check should produce List()")
check(testCase)

comment("Attempting to minimize the problematic range starts correctly identifying some of the elements, but doesn't fully solve the issue")
check(testCase.drop(1))
check(testCase.drop(2))

comment("I'm not sure why -1067567405 is the threshold at which it starts working again")
check(testCase.drop(3))

comment("Quick check using Interator.iterate to verify that Range.toList is not the issue:")
println(Iterator.iterate(Int.MinValue)(_ + 359972081).take(9).toList)

comment("Eliminating the range's gap doesn't change the behavior")
check(testCase.start to testCase.last by testCase.step)

comment("Likewise, switching `until` for `to` doesn't change the behavior")
check(testCase.inclusive)
```

Reproduced using Scastie for versions:
- [3.1.3](https://scastie.scala-lang.org/2DZzoW75R6eaAM5tpbbIog)
- [2.13.8](https://scastie.scala-lang.org/a8vEyjT1RfyMqvwSBGRK4Q)
- [2.12.16](https://scastie.scala-lang.org/8ViIH4xNSmGLk0wV71LhwA)
- [2.11.12](https://scastie.scala-lang.org/BjQtR73fSlu6eyFPl8DMYQ)

### Reproduction Output
```
I'm not sure what makes this Range special, as an org.scalacheck.Gen[Range] I'm working on produced it.

Range -2147483648 until 1092265081 by 359972081 is small, and only contains a few elements:
testCase: List(-2147483648, -1787511567, -1427539486, -1067567405, -707595324, -347623243, 12348838, 372320919, 732293000)

Expectation: a range will contain every value it produces, so check should produce List()
Range -2147483648 until 1092265081 by 359972081 does not contain List(12348838, 372320919, 732293000)

Attempting to minimize the problematic range starts correctly identifying some of the elements, but doesn't fully solve the issue
Range -1787511567 until 1092265081 by 359972081 does not contain List(372320919, 732293000)
Range -1427539486 until 1092265081 by 359972081 does not contain List(732293000)

I'm not sure why -1067567405 is the threshold at which it starts working again
Range -1067567405 until 1092265081 by 359972081 does not contain List()

Quick check using Interator.iterate to verify that Range.toList is not the issue:
List(-2147483648, -1787511567, -1427539486, -1067567405, -707595324, -347623243, 12348838, 372320919, 732293000)

Eliminating the range's gap doesn't change the behavior
Range -2147483648 to 732293000 by 359972081 does not contain List(12348838, 372320919, 732293000)

Likewise, switching `until` for `to` doesn't change the behavior
Range -2147483648 to 1092265081 by 359972081 does not contain List(12348838, 372320919, 732293000, 1092265081)
```

## Problem
`Range.contains` produces false negatives for several elements that it should contain, based on `Range.toList` and reproducing the stepwise calculation manually (see `res0` and `res5`).

### PR DESCRIPTION
**Pull request by jxnu-liguobin**
fix scala/bug#12635

### CODE REVIEW

File: src/library/scala/collection/immutable/Range.scala [hunk 1]
```diff
@@ -373,11 +373,11 @@ sealed abstract class Range(
     if (x == end && !isInclusive) false
     else if (step > 0) {
       if (x < start || x > end) false
-      else (step == 1) || (((x - start) % step) == 0)
+      else (step == 1) || (Integer.remainderUnsigned(x - start, step) == 0)
     }
     else {
       if (x < end || x > start) false
-      else (step == -1) || (((x - start) % step) == 0)
+      else (step == -1) || (Integer.remainderUnsigned(x - start, step) == 0)
```
Comment (sjrd) [inline src/library/scala/collection/immutable/Range.scala]: In this case, `x - start` and `step` are `< 0`. That was fine with the signed `%`, but with unsigned remainder, we need to make sure to pass in non-negative values:
```suggestion
      else (step == -1) || (Integer.remainderUnsigned(start - x, -step) == 0)
```

Comment (jxnu-liguobin) [reply src/library/scala/collection/immutable/Range.scala]: Thanks a lot, and I missed this part in my test.

**Comment by SethTisue** [comment]
Thank you!
