### PR TITLE
Deduplicate JavaDeprecatedAttr in ClassfileParser

### LINKED ISSUE #12799: java.lang.annotation.AnnotationFormatError thrown when accessing @Deprecated java method through scala class
## Reproduction steps

Scala version: 2.13.11

Reproducer is here: run `sbt test` showcases the behavior.
Changing scala version to 2.13.10 solves it.

https://github.com/DieBauer/scala-reproducer/tree/master

```java 
package example;

interface A {
  @Deprecated
    default String a() {
        return "a";
    }
}
```
this is compiled in a separate stage (module)

and the scala class is 
```scala 
package example

class B extends A
```

then checking that the Deprecated annotation is present on the Scala class/method fails

```java
Method deprecatedMethod = B.class.getMethod("a");
deprecatedMethod.isAnnotationPresent(Deprecated.class);
```

This fails with `java.lang.annotation.AnnotationFormatError: Duplicate annotation for class: interface java.lang.Deprecated: @java.lang.Deprecated(forRemoval=false, since="")`

## Problem

This issue is reproduced on Java 8, 11 and 17 (potentially higher versions as well). 
On 2.13.10 it does not occur.

When a Java class has a Deprecated method that is inherited in a Scala class, accessing the method through the scala class throws a `java.lang.annotation.AnnotationFormatError: Duplicate annotation for class: interface java.lang.Deprecated: @java.lang.Deprecated(forRemoval=false, since="")`
```
[error]     at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:126)
[error]     at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
[error]     at java.lang.reflect.Executable.declaredAnnotations(Executable.java:604)
[error]     at java.lang.reflect.Executable.declaredAnnotations(Executable.java:602)
[error]     at java.lang.reflect.Executable.getAnnotation(Executable.java:572)
[error]     at java.lang.reflect.Method.getAnnotation(Method.java:695)
[error]     at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:274)
[error]     at java.lang.reflect.AccessibleObject.isAnnotationPresent(AccessibleObject.java:517)
[error]     at example.ExampleTest.java(ExampleTest.java:10)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
```

The issue is the duplicate Deprecated annotation in the bytecode when compiled with Scala 2.13.11
```
    RuntimeVisibleAnnotations:
      0: #13()
        java.lang.Deprecated
      1: #13()
        java.lang.Deprecated
```

The java class looks like

The java class bytecode looks like: 
```
  Last modified 6 Jun 2023; size 277 bytes
  SHA-256 checksum 3b809a1b555c263005052518a2f9c1b04188c5c7a42c4a58761e0bc6eaef6863
  Compiled from "A.java"
public interface A
  minor version: 0
  major version: 55
  flags: (0x0601) ACC_PUBLIC, ACC_INTERFACE, ACC_ABSTRACT
  this_class: #1                          // A
  super_class: #2                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 1, attributes: 1
Constant pool:
   #1 = Class              #12            // A
   #2 = Class              #13            // java/lang/Object
   #3 = Utf8               a
   #4 = Utf8               (Ljava/lang/String;)Ljava/lang/String;
   #5 = Utf8               Code
   #6 = Utf8               LineNumberTable
   #7 = Utf8               Deprecated
   #8 = Utf8               RuntimeVisibleAnnotations
   #9 = Utf8               Ljava/lang/Deprecated;
  #10 = Utf8               SourceFile
  #11 = Utf8               A.java
  #12 = Utf8               A
  #13 = Utf8               java/lang/Object
{
  public default java.lang.String a(java.lang.String);
    descriptor: (Ljava/lang/String;)Ljava/lang/String;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=2, args_size=2
         0: aload_1
         1: areturn
      LineNumberTable:
        line 4: 0
    Deprecated: true
    RuntimeVisibleAnnotations:
      0: #9()
        java.lang.Deprecated
}
SourceFile: "A.java"
```

While the scala class bytecode looks like

```
Classfile /example/B.class
  Last modified 6 Jun 2023; size 687 bytes
  SHA-256 checksum 96fc9a1b3e19402a3137845a9e72d7057ebe0b7ea2913e2a0020b23949db7819
  Compiled from "B.scala"
public class example.B implements example.A
  minor version: 0
  major version: 52
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #2                          // example/B
  super_class: #4                         // java/lang/Object
  interfaces: 1, fields: 0, methods: 2, attributes: 4
Constant pool:
   #1 = Utf8               example/B
   #2 = Class              #1             // example/B
   #3 = Utf8               java/lang/Object
   #4 = Class              #3             // java/lang/Object
   #5 = Utf8               example/A
   #6 = Class              #5             // example/A
   #7 = Utf8               B.scala
   #8 = Utf8               Lscala/reflect/ScalaSignature;
   #9 = Utf8               bytes
  #10 = Utf8               \u0006\u0005Y1AAA\u0002\u0001\r!)1\u0003\u0001C\u0001)\t\t!IC\u0001\u0005\u0003\u001d)\u00070Y7qY\u0016\u001c\u0001aE\u0002\u0001\u000f=\u0001\"\u0001C\u0007\u000e\u0003%Q!AC\u0006\u0002\t1\fgn\u001a\u0006\u0002\u0019\u0005!!.\u0019<b\u0013\tq\u0011B\u0001\u0004PE*,7\r\u001e\t\u0003!Ei\u0011aA\u0005\u0003%\r\u0011\u0011!Q\u0001\u0007y%t\u0017\u000e\u001e \u0015\u0003U\u0001\"\u0001\u0005\u0001
  #11 = Utf8               a
  #12 = Utf8               ()Ljava/lang/String;
  #13 = Utf8               Ljava/lang/Deprecated;
  #14 = NameAndType        #11:#12        // a:()Ljava/lang/String;
  #15 = InterfaceMethodref #6.#14         // example/A.a:()Ljava/lang/String;
  #16 = Utf8               this
  #17 = Utf8               Lexample/B;
  #18 = Utf8               <init>
  #19 = Utf8               ()V
  #20 = NameAndType        #18:#19        // "<init>":()V
  #21 = Methodref          #4.#20         // java/lang/Object."<init>":()V
  #22 = Utf8               Code
  #23 = Utf8               LineNumberTable
  #24 = Utf8               LocalVariableTable
  #25 = Utf8               Deprecated
  #26 = Utf8               RuntimeVisibleAnnotations
  #27 = Utf8               SourceFile
  #28 = Utf8               ScalaInlineInfo
  #29 = Utf8               ScalaSig
{
  public java.lang.String a();
    descriptor: ()Ljava/lang/String;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #15                 // InterfaceMethod example/A.a:()Ljava/lang/String;
         4: areturn
      LineNumberTable:
        line 3: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lexample/B;
    Deprecated: true
    RuntimeVisibleAnnotations:
      0: #13()
        java.lang.Deprecated
      1: #13()
        java.lang.Deprecated

  public example.B();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #21                 // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 3: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lexample/B;
}
SourceFile: "B.scala"
RuntimeVisibleAnnotations:
  0: #8(#9=s#10)
    scala.reflect.ScalaSignature(
      bytes="\u0006\u0005Y1AAA\u0002\u0001\r!)1\u0003\u0001C\u0001)\t\t!IC\u0001\u0005\u0003\u001d)\u00070Y7qY\u0016\u001c\u0001aE\u0002\u0001\u000f=\u0001\"\u0001C\u0007\u000e\u0003%Q!AC\u0006\u0002\t1\fgn\u001a\u0006\u0002\u0019\u0005!!.\u0019<b\u0013\tq\u0011B\u0001\u0004PE*,7\r\u001e\t\u0003!Ei\u0011aA\u0005\u0003%\r\u0011\u0011!Q\u0001\u0007y%t\u0017\u000e\u001e \u0015\u0003U\u0001\"\u0001\u0005\u0001"
    )
  ScalaInlineInfo: length = 0xE (unknown attribute)
   01 00 00 02 00 12 00 13 00 00 0B 00 0C 00
  ScalaSig: length = 0x3 (unknown attribute)
   05 02 00
```

The same class compiled with Scala 2.13.10 gives this bytecode:
```
Classfile /Users/VS45BP/Developer/jens/reproducer/target/scala-2.13/classes/example/B.class
  Last modified 6 Jun 2023; size 683 bytes
  SHA-256 checksum a9eb082e246c34c97139612b4af5b9d7024faff53086bc427fb7159894d688b4
  Compiled from "B.scala"
public class example.B implements example.A
  minor version: 0
  major version: 52
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #2                          // example/B
  super_class: #4                         // java/lang/Object
  interfaces: 1, fields: 0, methods: 2, attributes: 4
Constant pool:
   #1 = Utf8               example/B
   #2 = Class              #1             // example/B
   #3 = Utf8               java/lang/Object
   #4 = Class              #3             // java/lang/Object
   #5 = Utf8               example/A
   #6 = Class              #5             // example/A
   #7 = Utf8               B.scala
   #8 = Utf8               Lscala/reflect/ScalaSignature;
   #9 = Utf8               bytes
  #10 = Utf8               \u0006\u0005Y1AAA\u0002\u0001\r!)1\u0003\u0001C\u0001)\t\t!IC\u0001\u0005\u0003\u001d)\u00070Y7qY\u0016\u001c\u0001aE\u0002\u0001\u000f=\u0001\"\u0001C\u0007\u000e\u0003%Q!AC\u0006\u0002\t1\fgn\u001a\u0006\u0002\u0019\u0005!!.\u0019<b\u0013\tq\u0011B\u0001\u0004PE*,7\r\u001e\t\u0003!Ei\u0011aA\u0005\u0003%\r\u0011\u0011!Q\u0001\u0007y%t\u0017\u000e\u001e \u0015\u0003U\u0001\"\u0001\u0005\u0001
  #11 = Utf8               a
  #12 = Utf8               ()Ljava/lang/String;
  #13 = Utf8               Ljava/lang/Deprecated;
  #14 = NameAndType        #11:#12        // a:()Ljava/lang/String;
  #15 = InterfaceMethodref #6.#14         // example/A.a:()Ljava/lang/String;
  #16 = Utf8               this
  #17 = Utf8               Lexample/B;
  #18 = Utf8               <init>
  #19 = Utf8               ()V
  #20 = NameAndType        #18:#19        // "<init>":()V
  #21 = Methodref          #4.#20         // java/lang/Object."<init>":()V
  #22 = Utf8               Code
  #23 = Utf8               LineNumberTable
  #24 = Utf8               LocalVariableTable
  #25 = Utf8               Deprecated
  #26 = Utf8               RuntimeVisibleAnnotations
  #27 = Utf8               SourceFile
  #28 = Utf8               ScalaInlineInfo
  #29 = Utf8               ScalaSig
{
  public java.lang.String a();
    descriptor: ()Ljava/lang/String;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #15                 // InterfaceMethod example/A.a:()Ljava/lang/String;
         4: areturn
      LineNumberTable:
        line 3: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lexample/B;
    Deprecated: true
    RuntimeVisibleAnnotations:
      0: #13()
        java.lang.Deprecated

  public example.B();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #21                 // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 3: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lexample/B;
}
SourceFile: "B.scala"
RuntimeVisibleAnnotations:
  0: #8(#9=s#10)
    scala.reflect.ScalaSignature(
      bytes="\u0006\u0005Y1AAA\u0002\u0001\r!)1\u0003\u0001C\u0001)\t\t!IC\u0001\u0005\u0003\u001d)\u00070Y7qY\u0016\u001c\u0001aE\u0002\u0001\u000f=\u0001\"\u0001C\u0007\u000e\u0003%Q!AC\u0006\u0002\t1\fgn\u001a\u0006\u0002\u0019\u0005!!.\u0019<b\u0013\tq\u0011B\u0001\u0004PE*,7\r\u001e\t\u0003!Ei\u0011aA\u0005\u0003%\r\u0011\u0011!Q\u0001\u0007y%t\u0017\u000e\u001e \u0015\u0003U\u0001\"\u0001\u0005\u0001"
    )
  ScalaInlineInfo: length = 0xE (unknown attribute)
   01 00 00 02 00 12 00 13 00 00 0B 00 0C 00
  ScalaSig: length = 0x3 (unknown attribute)
   05 02 00
```

This has only 1
```
    RuntimeVisibleAnnotations:
      0: #13()
        java.lang.Deprecated
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12799

### CODE REVIEW

**Comment by SethTisue** [comment]
👀 

```
!!    1 - run/t9644.scala                           [output differs]
% diff /home/jenkins/workspace/scala-2.13.x-validate-main/test/files/run/t9644.check /home/jenkins/workspace/scala-2.13.x-validate-main/test/files/run/t9644-run.log--- empty
+++ t9644-run.log
@@ -1,0 +1,42 @@
+scala.MatchError: new java.lang.annotation.Retention(value = RUNTIME) (of class scala.reflect.internal.Trees$Apply)
+	at Test$.delayedEndpoint$Test$1(t9644.scala:14)
+	at Test$delayedInit$body.apply(t9644.scala:5)
+	at scala.Function0.apply$mcV$sp(Function0.scala:42)
```

**Comment by som-snytt** [comment]
This implements the old hrhino suggestion to maintain annotation order in `sym.addAnnotation`, which changes the order for annotations other than runtime attrs read by class file parser.

Still need to check whether there was a general assumption that annotations from source were built in reverse.

**Comment by som-snytt** [comment]
My first edit retained last added annotation, which I changed when I fixed the failing test. It makes sense to prefer the `DeprecatedAttr` to its runtime twin; probably they are identical. Scala annotations maybe be multiple, such as `throws`.

File: src/reflect/scala/reflect/internal/Symbols.scala [hunk 1]
```diff
@@ -1913,8 +1913,23 @@ trait Symbols extends api.Symbols { self: SymbolTable =>
...
       setAnnotations(annotations filter p)
 
-    def addAnnotation(annot: AnnotationInfo): this.type =
-      setAnnotations(annot :: annotations)
+    // Retain first matching AnnotationInfo, preserving order.
+    def addAnnotation(annot: AnnotationInfo): this.type = {
+      def loop(annots: List[AnnotationInfo], rest: List[AnnotationInfo]): List[AnnotationInfo] =
+        rest match {
+          case h :: t =>
+            if (h.atp.typeSymbol.initialize.isJavaDefined && h.matches(annot.atp.typeSymbol.initialize)) Nil
```
Comment (lrytz) [inline src/reflect/scala/reflect/internal/Symbols.scala]: I think we should not force symbols here, but do that externally when necessary.

I would also narrow the fix down to the specific issue, i.e., skip adding the annotation in the classfile parser if the symbol already has it.

In general, it's valid to have multiple annotations of the same Java annotation type on a symbol: https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html

Comment (lrytz) [reply src/reflect/scala/reflect/internal/Symbols.scala]: I should actually read pages I link to before posting 🙈

It's valid to repeat annotations, they are emitted in bytecode using a "container annotation". We have `groupRepeatableAnnotations` in scalac to support that (and emit an error if the annotation is not repeatable).

Comment (som-snytt) [reply src/reflect/scala/reflect/internal/Symbols.scala]: I didn't like forcing and I didn't like the brittle distinction for "java-defined" annotations. I moved closer to, "Scala should just support all the Java behaviors instead of trying to be clever and different."

**Comment by som-snytt** [comment]
Reminder to self to check how deprecation is emitted.

**Comment by som-snytt** [comment]
This now implements the lrytz suggestion to confine the special handling to class file parser.

**Comment by som-snytt** [comment]
Of course the `since` test must be constrained to `javaVersion: 9+`, as Lukas had mentioned on an old ticket somewhere. So the `neg` test is for that check, and the `run` test always runs (so however CI is set up, it must undergo a jdk 8 test).

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala [hunk 2]
```diff
@@ -1514,6 +1506,19 @@ abstract class ClassfileParser(reader: ReusableInstance[ReusableDataReader]) {
...
+
+  // Preserve order, but discard a previous matching attibute and keep the last, since runtime attrs include args.
+  private def addUniqueAnnotation(symbol: Symbol, annot: AnnotationInfo): symbol.type = {
+    def addIt(annots: List[AnnotationInfo], rest: List[AnnotationInfo]): List[AnnotationInfo] =
+      rest match {
+        case h :: t =>
+          val loopy = addIt(annots, t)
+          if (h.atp.typeSymbol.initialize.isJavaDefined && h.matches(annot.atp.typeSymbol.initialize)) loopy
+          else h :: loopy
+        case Nil => annots
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala]:
```suggestion
        case Nil => List(annot)
```
then we don't need `annots`

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala [hunk 3]
```diff
@@ -857,16 +856,9 @@ abstract class ClassfileParser(reader: ReusableInstance[ReusableDataReader]) {
 
         case tpnme.RuntimeAnnotationATTR =>
           val numAnnots = u2()
-          val annots = new ListBuffer[AnnotationInfo]
           numAnnots times {
-            parseAnnotation(u2()).foreach(annots.addOne)
+            parseAnnotation(u2()).foreach(addUniqueAnnotation(sym, _))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala:855]: Should we restrict to `@Deprecated`, avoid forcing existing symbol annotations for other cases?

File: test/files/run/t9644.scala [hunk 4]
```diff
@@ -9,7 +9,7 @@ object Test extends App {
 
   import reflect.runtime.universe._
 
-  val List(d, r) = symbolOf[Foo].annotations
+  val List(r, d) = symbolOf[Foo].annotations
```
Comment (lrytz) [inline test/files/run/t9644.scala]: Is `r, d` the order in the pickle? Where is the order being reversed (compared to the source file)?

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala (hunk 3 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala:855]: Indeed, I wondered if only deprecation has this behavior but did not follow up. (Also whether a name-based check suffices.)

File: test/files/run/t9644.scala (hunk 4 above)
Comment (som-snytt) [reply test/files/run/t9644.scala]: This is addAnnotation preserving order, so this is typing order. Somewhere I said we should verify that it wasn't intentional to reverse order for that reason, or whether order is meaningful.

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala]: That was my original version. I tired of editing back and forth, so I made it a fold just to keep my interest. But I decided not to rely on "order" (whether Deprecated attribute is seen before the RuntimeVisible annotation), so for simplicity it probes for deprecation first.

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala (hunk 3 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala:855]: Deprecated is the only "predefined attribute" that becomes an AnnotationInfo. The check is not name-based because we have a symbol.

File: test/files/run/t9644.scala (hunk 4 above)
Comment (som-snytt) [reply test/files/run/t9644.scala]: I added a test for separate compilation, demonstrating the same order. Because I mostly use a landscape-mode monitor with a text editor, I didn't notice that in the presence of a scala sig, we don't see other runtime attributes. Also, I see that on the emitting end, we just set a flag, so I assume asm emits the attribute, which is present in the Scala class file in the test. Probably, adding JavaDeprecatedAttr in class file parser was deemed duplicative; mental Edit: not because of Scala deprecated but because of the runtime annotation. The whole point of this exercise is that we can't rely on the runtime annotation (which scalac itself does not emit, but possibly should, so that Java tooling would see since value written in Scala). Further mental note: Reviewing the long history (2014-2020) of trying to handle java annotations, it's hard to see what worked when. I agree with the original lrytz ticket advocating uniformity.

I probably misunderstood the hrhino comment about order, since the commit says compile order is different. Does order mean source order or insertion order? JVMS does not suggest that attributes or annotations have a natural or unnatural order.

Order could matter, such as `@nowarn` interleaved with buggy annotations. (Hypothetically.)

File: test/files/neg/t12799.check
Comment (lrytz) [inline test/files/neg/t12799.check:1]: stale check file?

File: test/files/run/t9644.scala (hunk 4 above)
Comment (lrytz) [reply test/files/run/t9644.scala]: https://github.com/scala/scala/blob/v2.13.11/src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala#L307

The root: https://github.com/scala/scala/commit/828377d9c0#diff-557cf0e98a6fedea5b17028c45a6b2fc2c16a00fb829157721142b4d3e04a606R112

Looking at more history, it seems adding an annotation was always prepending, I guess order wasn't considered important (except for the `reverse` added to the pickler at some point), and prepending is cheaper. Not sure, but if we fix `addAnnotation` we should probably remove the reversal from the pickler.

**Comment by som-snytt** [comment]
Thanks, I was so consumed with the previous edit that I did not drill down to answer your question.

**Comment by lrytz** [comment]
Are we sure that the `DeprecatedATTR` is visited before the anntoation, or should we safe-guard there too? https://github.com/scala/scala/blob/v2.13.11/src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala#L827-L831

Also, for the attribute we also add an annotation to the synthetic companion module symbol, but we don't do so for the annotation. This means the "since" message doesn't show when accessing a static member:

```scala
scala> new A
           ^
       warning: class A is deprecated (since you like it)
val res0: A = A@2c26ba07

scala> A.foo
       ^
       warning: class A is deprecated
```

**Comment by som-snytt** [comment]
I intended not to assume `DeprecatedATTR` is seen before the runtime attr, which is why the previous edit touched addAnnotation, but I neglected to update that spot to use the new method on the last refactor.

I'll tackle Nr 2 after coffee.

**Comment by som-snytt** [comment]
I noticed on a recent dotty ticket about `@BeanProperty` that Scala treats `@Deprecated` as an ordinary annotation only. But `@deprecated` distributes deprecation attribute to all `var` accessors. I haven't checked for the Scala annotation yet.

Edit: `@deprecated` winds up on everything, including both mutators if `@BeanProperty`. Actually the meta annots are listed in the Scaladoc.
```
bean.scala:34: warning: variable y in class Bean is deprecated (since 0.1): Bad var
  def reset() = b.y = 0
                  ^
bean.scala:35: warning: method setY in class Bean is deprecated (since 0.1): Bad var
  def kill() = b.setY(0)
                 ^
```

**Comment by som-snytt** [comment]
Last commit addresses both review comments: There is no reason to assume attribute ordering, so don't add plain deprecated if it already has it. There is no test. When adding the annotation, also check the static module, verified by test.

Did not squash! (My tweaking should be squashed.)

File: test/files/run/t12799/C.java [hunk 5]
```diff
@@ -0,0 +1,11 @@
+
+package example;
+
+@Deprecated(since="you like it")
```
Comment (lrytz) [inline test/files/run/t12799/C.java]: Didn't take arguments back on Java 8. We can make this test `// javaVersion: 9+`

**Review by lrytz — APPROVED** [review]
LGTM otherwise. I think this can be a single commit.

File: test/files/run/t12799/C.java (hunk 5 above)
Comment (som-snytt) [reply test/files/run/t12799/C.java]: oh right. You always say that, yet I always forget. What is Java 8 again?

Comment (som-snytt) [reply test/files/run/t12799/C.java]: For the record, made everything a single test because Swiss frugality, but I could also split out the last test. In fact, I will do that because jdk 8 is a major platform.

**Review by lrytz — APPROVED** [review]
Thank you !
