### PR TITLE
Avoid CCE with in seq-pattern on case class with lengthCompare

### LINKED ISSUE #11476: ClassCastException (ArraySeq) when pattern-matching on varargs case class
We encounter a weird ClassCastException when running our tests in ScalaTest for org.scalactic.Every, that looks like this: 

```
[error] (run-main-0) java.lang.ClassCastException: scala.collection.immutable.ArraySeq$ofInt cannot be cast to com.test.Every
[error] java.lang.ClassCastException: scala.collection.immutable.ArraySeq$ofInt cannot be cast to com.test.Every
[error] 	at com.test.TestMain$.main(TestMain.scala:7)
[error] 	at com.test.TestMain.main(TestMain.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
```

I tried to minimize the problem but not quite successful, the best I can do is to include the source of Every as com.test.Every, in the attached zip (a sbt project), you can reproduce the problem by running: 

```
> sbt run
```

If you change the scala version to 2.12.8, it works without problem.

[test-bug.zip](https://github.com/scala/bug/files/3054790/test-bug.zip)

### PR DESCRIPTION
**Pull request by retronym**
Fixes scala/bug#11476

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala [hunk 1]
```diff
@@ -453,14 +453,16 @@ trait MatchTranslation {
...
-
           // `binder.lengthCompare(expectedLength)`
           // ...if binder has a lengthCompare method, otherwise
           // `scala.math.signum(binder.length - expectedLength)`
-          def checkExpectedLength = lengthCompareSym match {
-            case NoSymbol => compareInts(Select(seqTree(binder, forceImmutable = false), nme.length), LIT(expectedLength))
-            case lencmp   => (seqTree(binder, forceImmutable = false) DOT lencmp)(LIT(expectedLength))
+          def checkExpectedLength = {
+            val tree = seqTree(binder, forceImmutable = false)
+            val lengthCompareSym = tree.symbol.info.member(nme.lengthCompare)
```
Comment (adriaanm) [inline src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala]: Interesting! I think we should try to have `seqTree` produce a typed tree, so that we can do `tree.tpe.member(nme.lengthCompare)`. It seems to already do that in most cases, but not quite. It also doesn't produce a tree with a symbol in all cases currently: `Select(ref, nme.toSeq)`

Comment (retronym) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala]: Yeah, that sounds a bit safer. Will give it a shot. The `Select(ref, nme.toSeq)` case actually doesn't flow in here because we're of `forceImmutable = false`.

Comment (retronym) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala]: I managed to get things working by typing the result of `seqTree` within this method.

File: src/reflect/scala/reflect/internal/Types.scala [hunk 2]
```diff
@@ -5068,6 +5068,7 @@ trait Types
 
   /** A throwable signalling a type error */
   class TypeError(var pos: Position, val msg: String) extends Throwable(msg) {
+    getClass
```
Comment (lrytz) [inline src/reflect/scala/reflect/internal/Types.scala]: debug

File: src/reflect/scala/reflect/internal/Definitions.scala [hunk 3]
```diff
@@ -1659,6 +1660,7 @@ trait Definitions extends api.StandardDefinitions {
       lazy val ensureAccessibleMethod = getMemberMethod(ScalaRunTimeModule, nme.ensureAccessible)
       lazy val arrayClassMethod       = getMemberMethod(ScalaRunTimeModule, nme.arrayClass)
       lazy val wrapVarargsRefArrayMethod = getMemberMethod(getWrapVarargsArrayModule, nme.wrapRefArray)
+      lazy val IterableOnce_toSeq     = getMemberMethod(IterableOnceClass, nme.toSeq)
```
Comment (lrytz) [inline src/reflect/scala/reflect/internal/Definitions.scala]: unused?

**Review by lrytz — APPROVED** [review]

**Review by adriaanm — APPROVED** [review]
👌
