### PR TITLE
Revert invert type signature change

### LINKED ISSUE #11766: Cannot call invert in Tuple2Zipped and Tuple3Zipped
in scala 2.13.1

```
[info] Starting scala interpreter...
Welcome to Scala 2.13.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> (Seq("a","b","c"), Seq("4","5","6")).invert
                                            ^
       error: Cannot prove that Seq[String] <:< It1.

scala> (Seq("a","b","c"), Seq("4","5","6"), Seq(1,2,3)).invert
                                                        ^
       error: Cannot prove that Seq[String] <:< It1.
```

in Scala 2.12.10

```
[info] Starting scala interpreter...
Welcome to Scala 2.12.10 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> (Seq("a","b","c"), Seq("4","5","6")).invert
res0: Seq[(String, String)] = List((a,4), (b,5), (c,6))

scala> (Seq("a","b","c"), Seq("4","5","6"), Seq(1,2,3)).invert
res1: Seq[(String, String, Int)] = List((a,4,1), (b,5,2), (c,6,3))
```

### PR DESCRIPTION
**Pull request by hrhino**
This aligns it with what 2.12 has. I was going to justify this with a comment on how Dotty also can't infer the types, but as it turns out Dotty can do so just fine, so now I need to justify this with a comment on how much more difficult type-inference bugs are to fix.

Plus, the bug's milestoned for 2.13.2, and I'd hate to let perfect be the enemy of gets-released-on-time.

Deprecation changes are to give a nicer error message for `(xs, ys).invert`... `use xs.lazyZip(ys)` isn't obvious enough IMO.

Fixes scala/bug#11766.

### CODE REVIEW

File: src/library/scala/Predef.scala [hunk 1]
```diff
@@ -430,7 +430,7 @@ object Predef extends LowPriorityImplicits {
    *  Consider using the [[scala.StringContext.f f interpolator]] as more type safe and idiomatic.
    *
    *  @param text the pattern for formatting the arguments.
-   *  @param args the arguments used to instantiating the pattern.
+   *  @param xs   the arguments used to instantiating the pattern.
```
Comment (hrhino) [inline src/library/scala/Predef.scala]: shoot, now that's got my name on it.

File: src/library/scala/runtime/Tuple2Zipped.scala [hunk 2]
```diff
@@ -117,13 +117,14 @@ final class Tuple2Zipped[El1, It1 <: Iterable[El1], El2, It2 <: Iterable[El2]](p
   override def toString = s"($coll1, $coll2).zipped"
 }
 
-@deprecated("Use scala.collection.LazyZip2.", "2.13.0")
+@deprecated("Use scala.collection.LazyZip2.", since = "2.13.0")
```
Comment (som-snytt) [inline src/library/scala/runtime/Tuple2Zipped.scala:120]: 🚀

File: src/library/scala/Predef.scala [hunk 3]
```diff
@@ -440,9 +440,9 @@ object Predef extends LowPriorityImplicits {
 
   // views --------------------------------------------------------------
 
-  @deprecated("Use xs.lazyZip(ys).", "2.13.0")
+  // these two are morally deprecated but the @deprecated annotation has been moved to the extension method themselves,
+  // in order to provide a more specific deprecation method.
```
Comment (som-snytt) [inline src/library/scala/Predef.scala]: the usual phrase is "morally depraved".

**Review by julienrf — APPROVED** [review]

**Comment by szeiger** [comment]
Is breaking source compatibility something we should do in 2.13.2? Or is it better to leave it alone since it's deprecated anyway?

**Comment by lrytz** [comment]
> breaking source compatibility

In what way is it breaking source compat?

**Comment by hrhino** [comment]
It's not breaking source compatibility in a meaningful way because no one could have called it before.

**Comment by szeiger** [comment]
You can call it but it's not pretty:
```
scala> (List(1,2,3),Seq("a","b","c")).invert[Int, List[Int], String, Seq[String], List[(Int, String)]]
       ^
       warning: method tuple2ToZippedOps in object Predef is deprecated (since 2.13.0): Use xs.lazyZip(ys).
val res2: List[(Int, String)] = List((1,a), (2,b), (3,c))
```
The new type parameters make it incompatible. It's probably not a big deal. Who would add those type parameters when upgrading to 2.13 instead of following the deprecation warning when both options are incompatible with 2.12?

**Comment by hrhino** [comment]
Yeah, @martijnhoekstra noted that in the ticket. I think the hypothetical author of that code would be glad simply to remove that whole bit.

**Review by lrytz — APPROVED** [review]
Thanks for the details, @szeiger and @hrhino
