### PR TITLE
Tweak test to wait for expiring thread

### LINKED ISSUE #12423: `testUncaughtExceptionReporting` fails on JDK 17 only
even though it passed on 16

This came up at https://github.com/scala/scala/pull/9679 .

The failure is non-intermittent and is happens on both Windows (it happened on GitHub Actions) and MacOS (locally). Probably Linux too, I haven't checked.

The failure mode is that the thread the exception was thrown from doesn't die. `Thread#isAlive` remains true, whereas the test expects it to go false.

Even much simpler test code such as

```scala
  def testUncaughtExceptionReporting(): Unit = {
    @volatile var thread: Thread = null
    val exec = java.util.concurrent.Executors.newFixedThreadPool(4)
    exec.submit{(() => {
      thread = Thread.currentThread
      throw new RuntimeException}
    ): Runnable}
    Thread.sleep(1000)
    assert(!thread.isAlive)
  }
```

tickles the 16/17 difference.

https://github.com/scala/bug/issues/10587 is exactly in this same area, I need to study it

Also, @retronym thinks https://github.com/openjdk/jdk/pull/1646 may be related (oh hai Doug Lea!), specifically https://github.com/openjdk/jdk/commit/5cfa8c94d6765b93f910fc01cd1ac2a56b16d78a#diff-4a89be3fb7dbae3cacde2a52201a0d10b60bf4157e840d9be7328af549a08a53R75 .

fyi @viktorklang

### PR DESCRIPTION
**Pull request by som-snytt**
The test for exception handling waits for thread
to die, perhaps to ensure all actions are complete.
Previously, throwing terminated the thread, but in
JDK 17, not  ~the thread's exception handler is the pool's~.
The test is updated to wait some long period for
the thread to expire of natural causes. Wonder why
the replicants in Blade Runner didn't change their
thinking from "retirement" and "termination" to
"Hey, I've got a pretty healthy keepAlive."

Fixes scala/bug#12423

### CODE REVIEW

File: test/files/jvm/scala-concurrent-tck.scala [hunk 1]
```diff
@@ -989,36 +986,34 @@ class CustomExecutionContext extends TestBase {
...
 
-      @tailrec def waitForThreadDeath(turns: Int): Boolean =
-          if (turns <= 0) false
-          else if ((thread ne null) && thread.isAlive == false) true
-          else {
-            Thread.sleep(10)
-            waitForThreadDeath(turns - 1)
-          }
+    @tailrec def waitForThreadDeath(turns: Int): Boolean =
+      turns > 0 && (thread != null && !thread.isAlive || { Thread.sleep(10L) ; waitForThreadDeath(turns - 1) })
```
Comment (NthPortal) [inline test/files/jvm/scala-concurrent-tck.scala:1000]: why are we testing `Thread#isAlive` and not `Thread#isInterrupted`, or at least testing both? at least from my reading of it, [`isAlive`](https://download.java.net/java/early_access/jdk17/docs/api/java.base/java/lang/Thread.html#isAlive()) tests if the thread has fallen victim to `ThreadDeath`, which is only thrown by deprecated methods on `Thread` (such as `Thread#stop`). If a thread is a member of a pool, there's no particular reason it ought to die unnecessarily.

Comment (som-snytt) [reply test/files/jvm/scala-concurrent-tck.scala:1000]: I don't know yet why the thread used to terminate. The ueh was always set, so something else is going on. I might have to up my Klang level.

The test wants to ensure that the exception is reported exactly once; it could also do that by waiting for pool to shutdown instead of state of a particular thread.

**Comment by som-snytt** [comment]
@dwijnand This is just a tweak to let the test pass on jdk17 (after waiting a minute for pool thread to die). It should be an easy merge so folks at home can have a green test run. (Green except for that serialization test.)

**Review by dwijnand — APPROVED** [review]
Looks reasonable to me, thanks Som
