### PR TITLE
Inline from classpath: list all lambda methods in `$deserializeLambda$`

### LINKED ISSUE #11255: Incomplete `$deserializeLambda$` with inlining under separate compilation
A.scala

```scala
class K(val f: Int => Int) extends Serializable
class A {
  @inline final def f = new K(x => x + 1)
}
```

Test.scala
```scala
object Test {
  def serializeDeserialize(obj: Object): Object = {
    import java.io._
    val buffer = new ByteArrayOutputStream
    val out = new ObjectOutputStream(buffer)
    out.writeObject(obj)
    val in = new ObjectInputStream(new ByteArrayInputStream(buffer.toByteArray))
    in.readObject
  }

  def main(args: Array[String]): Unit = {
    println(serializeDeserialize((new A).f))
  }
}
```

In joint compilation, `Test$.scala` mentions `A.$anonfun$f$1` in its ` $deserializeLambda$`. In separate compilation it doesn't, leading to
```
$> qsc Test.scala -opt:l:inline '-opt-inline-from:**' -Yopt-log-inline _ && qs Test
Caused by: java.lang.NoSuchMethodException: Test$.$deserializeLambda$(java.lang.invoke.SerializedLambda)
```

### PR DESCRIPTION
**Pull request by lrytz**
When inlining an IndyLambda from the classpath, ensure that the lambda
impl method is listed in the class's `$deserializeLambda$`.

Fixes scala/bug#11255.

### CODE REVIEW

**Comment by lrytz** [comment]
Should be backported, I'd like to have it in 2.12.8 actually.

File: src/compiler/scala/tools/nsc/backend/jvm/opt/Inliner.scala [hunk 1]
```diff
@@ -285,8 +287,14 @@ abstract class Inliner {
...
 
-      for (m <- inlinerState.keySet if !changedByClosureOptimizer(m))
-        inlinerState.remove(m).get.inlineLog.print()
+      var logs = List.empty[(MethodNode, InlineLog)]
+      for (m <- inlinerState.keySet if !changedByClosureOptimizer(m)) {
+        val log = inlinerState.remove(m).get.inlineLog
+        if (log.nonEmpty) logs ::= (m, log)
+      }
+      // deterministic inline log
+      for ((_, log) <- logs.sorted(Ordering.by[(MethodNode, InlineLog), (String, String)](p => (p._1.name, p._1.desc))))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/backend/jvm/opt/Inliner.scala]: We could use a `LinkedHashMap` for `inlinerState` instead of sorting here. Since we only need the deterministic traversal order for inline logging, I opted for sorting.

**Comment by SethTisue** [comment]
> Should be backported, I'd like to have it in 2.12.8 actually.

@lrytz are you still hoping to get a backport into 2.12.8?

**Comment by lrytz** [comment]
Hm, I forgot about this. Let's first review it here (cc @retronym)

File: src/compiler/scala/tools/nsc/backend/jvm/opt/Inliner.scala (hunk 1 above)
Comment (retronym) [reply src/compiler/scala/tools/nsc/backend/jvm/opt/Inliner.scala]: Wrap this in `if (compilerSettings.optLogInline.isDefined)` to avoid sorting when we don't output the diagnostic logs.

**Comment by retronym** [comment]
LGTM other than the comment above.

File: src/compiler/scala/tools/nsc/backend/jvm/opt/Inliner.scala (hunk 1 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/backend/jvm/opt/Inliner.scala]: Logs are not collected if logging is disabled, but I'll mention it for clarity.
