### PR TITLE
Constructors handles private local early defs

### LINKED ISSUE #10561: Compiler crashes when a private early initializer is referenced in an inner class
Reproducer:

```
class Parent {
    private val field: Int = 3
}

class Child(n: Int) extends {
    private val field = n
} with Parent {
    class Inner {
        def f = field
    }
}
```

Here's the stack trace:

```
error: java.lang.AssertionError: assertion failed:
  expected exactly one field by name field in List(private[this] val field: Int = _) of class Child's early initializers
     while compiling: Test.scala
        during phase: constructors
     library version: version 2.12.3
    compiler version: version 2.12.3
  reconstructed args: -Ystop-before:jvm

  last tree to typer: This(class Inner)
       tree position: line 11 of Test.scala
            tree tpe: Child#Inner
              symbol: class Inner in class Child
   symbol definition: class Inner extends Object (a ClassSymbol)
      symbol package: <empty>
       symbol owners: class Inner -> class Child
           call site: class Child in package <empty>

== Source file context for tree position ==

     8     private val field = n
     9 } with Parent {
    10     class Inner {
    11         def f = field
    12     }
    13 }
    14
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.$anonfun$triage$1(Constructors.scala:613)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.triage(Constructors.scala:607)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.<init>(Constructors.scala:591)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer.transformed(Constructors.scala:694)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.$anonfun$transform$1(Constructors.scala:85)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:85)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:29)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
        at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1437)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1437)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1347)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:89)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:29)
        at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
        at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1431)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1416)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1412)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1515)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:35)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
        at scala.tools.nsc.Driver.process(Driver.scala:55)
        at scala.tools.nsc.Driver.main(Driver.scala:68)
        at scala.tools.nsc.Main.main(Main.scala)
Exception in thread "main" java.lang.AssertionError: assertion failed:
  expected exactly one field by name field in List(private[this] val field: Int = _) of class Child's early initializers
     while compiling: Test.scala
        during phase: constructors
     library version: version 2.12.3
    compiler version: version 2.12.3
  reconstructed args: -Ystop-before:jvm

  last tree to typer: This(class Inner)
       tree position: line 11 of Test.scala
            tree tpe: Child#Inner
              symbol: class Inner in class Child
   symbol definition: class Inner extends Object (a ClassSymbol)
      symbol package: <empty>
       symbol owners: class Inner -> class Child
           call site: class Child in package <empty>

== Source file context for tree position ==

     8     private val field = n
     9 } with Parent {
    10     class Inner {
    11         def f = field
    12     }
    13 }
    14
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.$anonfun$triage$1(Constructors.scala:613)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.triage(Constructors.scala:607)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.<init>(Constructors.scala:591)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer.transformed(Constructors.scala:694)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.$anonfun$transform$1(Constructors.scala:85)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:85)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:29)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
        at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1437)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1437)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1347)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:89)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:29)
        at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
        at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1431)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1416)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1412)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1515)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:35)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
        at scala.tools.nsc.Driver.process(Driver.scala:55)
        at scala.tools.nsc.Driver.main(Driver.scala:68)
        at scala.tools.nsc.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#10561

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/Constructors.scala [hunk 1]
```diff
@@ -617,8 +620,19 @@ abstract class Constructors extends Statics with Transform with TypingTransforme
           stat match {
             case ValDef(mods, name, _, _) if mods.hasFlag(PRESUPER) => // TODO trait presupers
               // stat is the constructor-local definition of the field value
-              val fields = presupers filter (_.getterName == name)
-              assert(fields.length == 1, s"expected exactly one field by name $name in $presupers of $clazz's early initializers")
+              val fields = presupers.filter { v =>
+                val nm =
+                  if (v.symbol.isPrivateLocal) {
+                    val g = v.getterName
+                    val i = g.lastPos(scala.reflect.NameTransformer.NAME_JOIN_STRING(0))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/transform/Constructors.scala]: This is to undo `expandName` right? Checking `v.symbol.hasFlag(EXPANDEDNAME)` above and splitting the name at `EXPAND_SEPARATOR_STRING` would be a bit more precise?

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/transform/Constructors.scala]: thanks

**Comment by som-snytt** [comment]
Rebased and squashed. I see that the diff could have been more minimal.

**Review by lrytz — APPROVED** [review]
Thanks!
