### PR TITLE
When parsing Java sources, skip JDK 21+’s JEP 445 compact compilation units

### LINKED ISSUE #12878: JavaParsers doesn't support `JEP 445: Unnamed Classes and Instance Main Methods`
## Reproduction steps

- Scala 2.13.12
- JDK 21
- https://openjdk.org/jeps/445
- https://github.com/xuwei-k/Scala-JEP-445/commit/c96fe40572021d937935d448026e7b2cdff0dca1
- https://github.com/xuwei-k/Scala-JEP-445/actions/runs/6268842307/job/17024415920

### `A.java`

```java
void main() {
  System.out.println("hello");
}
```

### `B.scala`

```scala
class B
```

### `build.sbt`

```scala
javacOptions ++= Seq(
  "-Xlint:preview",
  "--enable-preview",
  "--release",
  scala.util.Properties.javaSpecVersion
)

scalaVersion := "2.13.12"
```

### `project/build.properties`

```properties
sbt.version=1.9.6
```

## Problem

`sbt -J--enable-preview compile`

https://github.com/scala/scala/blob/e67d287447c09720468f8bebcb0302bd92d75f43/src/compiler/scala/tools/nsc/javac/JavaParsers.scala#L1074

```
[error] /home/runner/work/Scala-JEP-445/Scala-JEP-445/A.java:1:6: illegal start of type declaration
[error] void main() {
[error]      ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

### PR DESCRIPTION
**Pull request by lrytz**
Compact compilation units are not referenceable, so we can skip over them.

Fixes https://github.com/scala/bug/issues/12878

### CODE REVIEW

File: test/files/pos/t12878/T.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+//> using jvm 21+
+//> using javacOpt --enable-preview --release 21
+
+int k = 0;
+// This should work as compact units have an implicit `import module java.base`, but that doesn't seem to be the case with Java 21 preview
```
Comment (som-snytt) [inline test/files/pos/t12878/T.java]: could use 25 directly, as no one cares about regression on old preview

Comment (som-snytt) [reply test/files/pos/t12878/T.java]: I recognize you might wish to see it run and pass today, however.

File: src/compiler/scala/tools/nsc/javac/JavaParsers.scala [hunk 2]
```diff
@@ -1092,6 +1092,14 @@ trait JavaParsers extends ast.parser.ParsersCommon with JavaScanners {
...
      */
     def compilationUnit(): Tree = {
+      var compact = false
+      def typeDeclOrCompact(mods: Modifiers): List[Tree] = in.token match {
+        case ENUM | INTERFACE | AT | CLASS | RECORD => typeDecl(mods)
+        case _ =>
+          val ts = termDecl(mods, CLASS)
+          if (ts.nonEmpty) compact = true
+          Nil
+      }
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/javac/JavaParsers.scala]: I might have generalized `typeDeclOrCompactTerm(mods)(orElse: Tree)` which `typeDecl` would call.

I might have orElse throw here to long jump back to a  try in compilationUnit.

That would be to avoid listing tokens at L1097. OTOH, the method is so small this is fine.

There is a `return` in that `interactive` code, so maybe I have early return on the brain.

**Review by som-snytt — APPROVED** [review]
There is a Peanuts cartoon (as I recall from childhood) in which Linus explains that when he's reading the Bible and encounters a word he doesn't know, he just "bloops right over it".

**Comment by som-snytt** [comment]
TIL `referrible`, in OED via https://english.stackexchange.com/questions/51527/use-of-the-word-referable

OED notes intransitive "reference" having to do with (I think) cataloguing properties which must be acquired by eminent domain for a railroad. That strikes me as a very British coinage, that is, putting that disruptive practice behind a neutral term that doesn't even take a direct object. In the U.S., it's just called capitalism.

To make too fine a distinction, does "reference" imply authoritative reference? Then one could reference a stable reference (in our terminology). Or perhaps conversely, every reference in computing is authoritative to mean correct and not erroneous, and therefore can be referenced.

From C pointer days, we would say "dereference" for this action of actually finding the referent. That is at runtime.

That might imply that at compiletime, one does not reference simply any identifier, but only identifiers with the strongest guarantees (that they are not null, perhaps).

The weak sense is that referrible means in the namespace and accessible.

File: test/files/pos/t12878/T.java (hunk 1 above)
Comment (lrytz) [reply test/files/pos/t12878/T.java]: Right, though we run 25 already on CI. I'll do that.
