### PR TITLE
Limit productElementName to productArity

### LINKED ISSUE #12402: productElementName includes extra names
## reproduction steps

using Scala 2 with its built-in versioned prompt,

```scala
scala 2.13.6> case class C[A: Ordering](a: A)
class C

scala 2.13.6> C(42)
val res1: C[Int] = C(42)

scala 2.13.6> C(42).productArity
val res4: Int = 1

scala 2.13.6> C(42).productElementNames
val res8: Iterator[String] = <iterator>

scala 2.13.6> .toList
val res9: List[String] = List(a)

scala 2.13.6> C(42).productElementName
override def productElementName(x$1: Int): String
scala 2.13.6> C(42).productElementName(0)
val res11: String = a

scala 2.13.6> C(42).productElementName(1)
val res12: String = evidence$1
```

## problem

The case class should not report a name for non-product element members.

### PR DESCRIPTION
**Pull request by VladKopanev**
Fixes scala/bug#12402

### CODE REVIEW

**Comment by VladKopanev** [comment]
review by @som-snytt

**Comment by som-snytt** [comment]
`arity` is the limit. A test case with curried constructor, in Scala 3:

```
Using scala version 3.0.0 in this shell.
➜  ~ scala
scala> case class C[A: Ordering](a: A)(b: String)
// defined case class C

scala> C(42)("hi").productElementNames.toList
val res0: List[String] = List(a)

scala> C(42)("hi").productElementName(2)
java.lang.IndexOutOfBoundsException: 2
  at rs$line$1$C.productElementName(rs$line$1:1)
  ... 28 elided

scala> C(42)("hi").productElementName(1)
java.lang.IndexOutOfBoundsException: 1
  at rs$line$1$C.productElementName(rs$line$1:1)
  ... 28 elided

scala> C(42)("hi").productElementName(0)
val res3: String = a
```

File: src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala [hunk 1]
```diff
@@ -126,7 +126,7 @@ trait SyntheticMethods extends ast.TreeDSL {
       createSwitchMethod(name, accessors.indices, returnType)(idx => caseFn(accessors(idx)))
 
     def productElementNameMethod = {
-      val constrParamAccessors = clazz.constrParamAccessors
+      val constrParamAccessors = clazz.constrParamAccessors.filterNot(_.isImplicit)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala]:
```suggestion
      val constrParamAccessors = accessors
```

Comment (VladKopanev) [reply src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala]: Oh, thanks, 🙏 didn't see that

Comment (VladKopanev) [reply src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala]: Fixed

File: src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala [hunk 2]
```diff
@@ -126,8 +126,9 @@ trait SyntheticMethods extends ast.TreeDSL {
       createSwitchMethod(name, accessors.indices, returnType)(idx => caseFn(accessors(idx)))
 
     def productElementNameMethod = {
-      val constrParamAccessors = clazz.constrParamAccessors
-      createSwitchMethod(nme.productElementName, constrParamAccessors.indices, StringTpe)(idx => LIT(constrParamAccessors(idx).name.dropLocal.decode))
+      createSwitchMethod(nme.productElementName, accessors.indices, StringTpe)(idx =>
+        LIT(accessors(idx).name.dropLocal.decode)
+      )
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala]: That was bad advice because mangled names. `clazz.constrParamAccessors.take(arity)`.

You might think these go through `paramLists` aka `paramss` but [actually no](https://github.com/scala/scala/blob/2.13.x/src/reflect/scala/reflect/internal/Symbols.scala#L2137).

https://github.com/scala/scala/pull/9645/files#diff-205537ac4c08ea690ada72e398df0018dcaf2a7c4987c0d8d8df322314469578R129

**Comment by dwijnand** [comment]
Looks like #9645 fixes this, but I think Som is happy for you to take his arity idea and apply it here, so we can merge this PR.

**Comment by som-snytt** [comment]
I tried that pushy thing @lrytz does, I hope I did it right.
