### PR TITLE
Deprecate multiarg `+=` on `AnyRefMap` and `LongMap`

### LINKED ISSUE #12012: `AnyRefMap` and `LongMap`'s `+=` method's signature is incorrect, should be a tuple
e.g. `AnyRefMap` has:

```
  def +=(key: K, value: V): this.type = { update(key, value); this }
  @inline final def addOne(key: K, value: V): this.type = { update(key, value); this }
  @inline override final def addOne(kv: (K, V)): this.type = { update(kv._1, kv._2); this }
```

But the `+=` signature is inconsistent with other maps, where the method of the same name takes a tuple. It's also inconsistent with Scala's gradual move away from allowing multi-arg infix calls.

This turned up in https://github.com/scala/scala/pull/8998, which increases the level of linting we do in `src/library`, resulting in:

```scala
[error] /Users/tisue/scala.213/src/library/scala/collection/mutable/AnyRefMap.scala:297:7: multiarg infix syntax looks like a tuple and will be deprecated
[error]   def +=(key: K, value: V): this.type = { update(key, value); this }
[error]       ^
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12012

### CODE REVIEW

**Comment by som-snytt** [comment]
Obviously I didn't check build output yet.

File: src/library/scala/collection/mutable/AnyRefMap.scala [hunk 1]
```diff
@@ -293,6 +293,7 @@ class AnyRefMap[K <: AnyRef, V] private[collection] (defaultEntry: K => V, initi
   }
 
   /** Adds a new key/value pair to this map and returns the map. */
+  @deprecated("Use `addOne` or `update` instead; infix operations with an operand of multiple args will be deprecated", "2.13.3")
```
Comment (smarter) [inline src/library/scala/collection/mutable/AnyRefMap.scala:296]: I would just mention update and not addOne, since they're equivalent except addOne will box.

Comment (som-snytt) [reply src/library/scala/collection/mutable/AnyRefMap.scala:296]: There is specialized `addOne`. Or was that only `LongMap`? I'll doubly check.

Comment (som-snytt) [reply src/library/scala/collection/mutable/AnyRefMap.scala:296]:
```
  /** Adds a new key/value pair to this map and returns the map. */
  @inline final def addOne(key: K, value: V): this.type = { update(key, value); this }

  @inline override final def addOne(kv: (K, V)): this.type = { update(kv._1, kv._2); this }
```

Comment (som-snytt) [reply src/library/scala/collection/mutable/AnyRefMap.scala:296]: There is the caveat about which interface is in use, but we know they're selecting from the subtype for `+=`.

Comment (som-snytt) [reply src/library/scala/collection/mutable/AnyRefMap.scala:296]: This would be a good place to say `"Use adderAll instead"`.

**Comment by som-snytt** [comment]
I wasn't clever enough to remember that I have to turn on deprecations and try it locally. At least the multiarg warnings went away. Let me check that I'm wearing my computer glasses.
