### PR TITLE
Fix outer tests when pattern has a refined prefix

### LINKED ISSUE #12467: Scala 2.13.6 Compiler Throws AssertionError
## reproduction steps

using Scala (add version here),

```scala
import akka.stream.scaladsl.Source
import akka.stream.stage._
import akka.stream.{Attributes, Outlet, SourceShape}
import cats.syntax.all._

import scala.concurrent.duration.{Duration, _}
import scala.concurrent.{Await, ExecutionContext, Future}

trait PagedRequest[A, PageIdentifier, Response] {
  def getPage(a: A)(id: PageIdentifier): Future[Response]
  def start(a: A)(implicit pagedResponse: PagedResponse[Response, PageIdentifier]): pagedResponse.NextPage
}

// scalastyle:off structural.type
object PagedResponse {
  type Aux[A0, PageIdentifier0, Item0] = PagedResponse[A0, PageIdentifier0] { type Item = Item0 }
}

trait PagedResponse[A, PageIdentifier] {
  type Item
  sealed trait NextPage
  case class Next(page: PageIdentifier) extends NextPage
  case class NoMorePages() extends NextPage

  def nextPage(a: A): NextPage
  def elements(a: A): List[Item]
}

object PagingSource {
  def apply[Request : ({ type PR[A] = PagedRequest[A, PageIdentifier, Response] })#PR, Response, PageIdentifier, Item](
    paged: Request,
    timeout: Duration = 5.seconds
  )(
    implicit ec: ExecutionContext,
    responseOps: PagedResponse.Aux[Response, PageIdentifier, Item]
  ): Source[Item, akka.NotUsed] =
    Source.fromGraph(new PagingSource(paged, timeout))
}

class PagingSource[
  Request : ({ type PR[A] = PagedRequest[A, PageIdentifier, Response] })#PR,
  Response,
  PageIdentifier,
  Item
](paged: Request, timeout: Duration)(
  implicit ec: ExecutionContext,
  responseOps: PagedResponse.Aux[Response, PageIdentifier, Item]
) extends GraphStage[SourceShape[Item]] {

  val out: Outlet[Item] = Outlet("Output")
  override val shape: SourceShape[Item] = SourceShape(out)

  val pagedOps = implicitly[PagedRequest[Request, PageIdentifier, Response]]

  override def createLogic(inheritedAttributes: Attributes): GraphStageLogic = new GraphStageLogic(shape) {
    var nextPage: PagedResponse.Aux[Response, PageIdentifier, Item]#NextPage = pagedOps.start(paged)
    val queue = scala.collection.mutable.Queue.empty[Item]

    setHandler(
      out,
      new OutHandler {
        override def onPull(): Unit =
          if (queue.nonEmpty) {
            push(out, queue.dequeue())
          } else {
            nextPage match {
              case _: PagedResponse.Aux[Response, PageIdentifier, Item]#NoMorePages => completeStage()
              case next: PagedResponse.Aux[Response, PageIdentifier, Item]#Next =>
                (for {
                  returnedPage <- Either.catchNonFatal {
                    Await.result(pagedOps.getPage(paged)(next.page), timeout)
                  }
                } yield {
                  queue ++= responseOps.elements(returnedPage)
                  nextPage = responseOps.nextPage(returnedPage)
                }).bimap(
                  exception => fail(out, exception),
                  _ => if (queue.nonEmpty) push(out, queue.dequeue()) else completeStage()
                )
            }
          }
      }
    )
  }
}
```

Produces error:

```
## reproduction steps

using Scala (add version here),

```scala
import akka.stream.scaladsl.Source
import akka.stream.stage._
import akka.stream.{Attributes, Outlet, SourceShape}
import cats.syntax.all._

import scala.concurrent.duration.{Duration, _}
import scala.concurrent.{Await, ExecutionContext, Future}

trait PagedRequest[A, PageIdentifier, Response] {
  def getPage(a: A)(id: PageIdentifier): Future[Response]
  def start(a: A)(implicit pagedResponse: PagedResponse[Response, PageIdentifier]): pagedResponse.NextPage
}

// scalastyle:off structural.type
object PagedResponse {
  type Aux[A0, PageIdentifier0, Item0] = PagedResponse[A0, PageIdentifier0] { type Item = Item0 }
}

trait PagedResponse[A, PageIdentifier] {
  type Item
  sealed trait NextPage
  case class Next(page: PageIdentifier) extends NextPage
  case class NoMorePages() extends NextPage

  def nextPage(a: A): NextPage
  def elements(a: A): List[Item]
}

object PagingSource {
  def apply[Request : ({ type PR[A] = PagedRequest[A, PageIdentifier, Response] })#PR, Response, PageIdentifier, Item](
    paged: Request,
    timeout: Duration = 5.seconds
  )(
    implicit ec: ExecutionContext,
    responseOps: PagedResponse.Aux[Response, PageIdentifier, Item]
  ): Source[Item, akka.NotUsed] =
    Source.fromGraph(new PagingSource(paged, timeout))
}

class PagingSource[
  Request : ({ type PR[A] = PagedRequest[A, PageIdentifier, Response] })#PR,
  Response,
  PageIdentifier,
  Item
](paged: Request, timeout: Duration)(
  implicit ec: ExecutionContext,
  responseOps: PagedResponse.Aux[Response, PageIdentifier, Item]
) extends GraphStage[SourceShape[Item]] {

  val out: Outlet[Item] = Outlet("Output")
  override val shape: SourceShape[Item] = SourceShape(out)

  val pagedOps = implicitly[PagedRequest[Request, PageIdentifier, Response]]

  override def createLogic(inheritedAttributes: Attributes): GraphStageLogic = new GraphStageLogic(shape) {
    var nextPage: PagedResponse.Aux[Response, PageIdentifier, Item]#NextPage = pagedOps.start(paged)
    val queue = scala.collection.mutable.Queue.empty[Item]

    setHandler(
      out,
      new OutHandler {
        override def onPull(): Unit =
          if (queue.nonEmpty) {
            push(out, queue.dequeue())
          } else {
            nextPage match {
              case _: PagedResponse.Aux[Response, PageIdentifier, Item]#NoMorePages => completeStage()
              case next: PagedResponse.Aux[Response, PageIdentifier, Item]#Next =>
                (for {
                  returnedPage <- Either.catchNonFatal {
                    Await.result(pagedOps.getPage(paged)(next.page), timeout)
                  }
                } yield {
                  queue ++= responseOps.elements(returnedPage)
                  nextPage = responseOps.nextPage(returnedPage)
                }).bimap(
                  exception => fail(out, exception),
                  _ => if (queue.nonEmpty) push(out, queue.dequeue()) else completeStage()
                )
            }
          }
      }
    )
  }
}
```

Produces error:

```
[error] ## Exception when compiling 1 sources to /Users/user/workspace/playground/clone-error-test/target/scala-2.13/classes
[error] java.lang.AssertionError: assertion failed:
[error]   mkAttributedQualifier(example.PagedResponse[Response,PageIdentifier]{type Item = Item}, <none>) parents = List(example.PagedResponse[Response,PageIdentifier])
[error]      while compiling: /Users/user/workspace/playground/clone-error-test/src/main/scala/example/Hello.scala
[error]         during phase: patmat
[error]      library version: version 2.13.6
[error]     compiler version: version 2.13.6
[error]   reconstructed args: -bootclasspath /Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar -classpath /Users/user/workspace/playground/clone-error-test/target/scala-2.13/classes:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/akka/akka-stream_2.13/2.5.32/akka-stream_2.13-2.5.32.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/typelevel/cats-core_2.13/2.4.2/cats-core_2.13-2.4.2.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/akka/akka-actor_2.13/2.5.32/akka-actor_2.13-2.5.32.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/akka/akka-protobuf_2.13/2.5.32/akka-protobuf_2.13-2.5.32.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/ssl-config-core_2.13/0.3.8/ssl-config-core_2.13-0.3.8.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/typelevel/cats-kernel_2.13/2.4.2/cats-kernel_2.13-2.4.2.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/typelevel/simulacrum-scalafix-annotations_2.13/0.5.4/simulacrum-scalafix-annotations_2.13-0.5.4.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/config/1.3.3/config-1.3.3.jar:/Users/user/.m2/repository/org/scala-lang/modules/scala-java8-compat_2.13/0.9.0/scala-java8-compat_2.13-0.9.0.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/scala-lang/modules/scala-parser-combinators_2.13/1.1.2/scala-parser-combinators_2.13-1.1.2.jar
[error]
[error]   last tree to typer: Ident(x)
[error]        tree position: line 25 of /Users/user/workspace/playground/clone-error-test/src/main/scala/example/Hello.scala
[error]             tree tpe: Boolean
[error]               symbol: value x
[error]    symbol definition: x: Boolean (a TermSymbol)
[error]       symbol package: <none>
[error]        symbol owners: value x
[error]            call site: method onPull in package example
[error]
[error] == Source file context for tree position ==
[error]
[error]     22   type Item
[error]     23   sealed trait NextPage
[error]     24   case class Next(page: PageIdentifier) extends NextPage
[error]     25   case class NoMorePages() extends NextPage
[error]     26
[error]     27   def nextPage(a: A): NextPage
[error]     28   def elements(a: A): List[Item]
[error] scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:171)
[error] scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:117)
[error] scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:74)
[error] scala.reflect.internal.TreeGen.mkAttributedQualifierIfPossible(TreeGen.scala:152)
[error] scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker$treeCondStrategy$.withOuterTest(MatchTreeMaking.scala:431)
[error] scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker$treeCondStrategy$.withOuterTest(MatchTreeMaking.scala:339)
[error] scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker.addOuterTest$1(MatchTreeMaking.scala:520)
[error] scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker.mkDefault$1(MatchTreeMaking.scala:530)
[error] scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker.renderCondition(MatchTreeMaking.scala:554)
[error] scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker.<init>(MatchTreeMaking.scala:558)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.typeTestStep(MatchTranslation.scala:96)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.nextStep(MatchTranslation.scala:163)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.translate(MatchTranslation.scala:170)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translatePattern(MatchTranslation.scala:315)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translatePattern$(MatchTranslation.scala:315)
[error] scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translatePattern(PatternMatching.scala:100)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateCase(MatchTranslation.scala:311)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateCase$(MatchTranslation.scala:309)
[error] scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translateCase(PatternMatching.scala:100)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch(MatchTranslation.scala:224)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch$(MatchTranslation.scala:192)
[error] scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translateMatch(PatternMatching.scala:100)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:69)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.internal.Trees$If.transform(Trees.scala:679)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.internal.Trees$DefDef.$anonfun$transform$5(Trees.scala:453)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] scala.reflect.internal.Trees$DefDef.transform(Trees.scala:451)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
[error] scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] scala.reflect.internal.Trees$Block.transform(Trees.scala:556)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2591)
[error] scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.$anonfun$transformStats$2(Trees.scala:2621)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2621)
[error] scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
[error] scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] scala.reflect.internal.Trees$Block.transform(Trees.scala:556)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.internal.Trees$DefDef.$anonfun$transform$5(Trees.scala:453)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] scala.reflect.internal.Trees$DefDef.transform(Trees.scala:451)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
[error] scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:342)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:342)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:55)
[error] scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
[error] scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:183)
[error] scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:32)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
[error] scala.tools.nsc.Global$GlobalPhase.run(Global.scala:401)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1519)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1503)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1495)
[error] scala.tools.nsc.Global$Run.compileFiles(Global.scala:1609)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
[error] xsbt.CompilerBridge.run(CompilerBridge.scala:39)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:175)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:173)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:501)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:167)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2357)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2310)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:833)
[error]
[error] java.lang.AssertionError: assertion failed:
[error]   mkAttributedQualifier(example.PagedResponse[Response,PageIdentifier]{type Item = Item}, <none>) parents = List(example.PagedResponse[Response,PageIdentifier])
[error]      while compiling: /Users/user/workspace/playground/clone-error-test/src/main/scala/example/Hello.scala
[error]         during phase: patmat
[error]      library version: version 2.13.6
[error]     compiler version: version 2.13.6
[error]   reconstructed args: -bootclasspath /Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar -classpath /Users/user/workspace/playground/clone-error-test/target/scala-2.13/classes:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/akka/akka-stream_2.13/2.5.32/akka-stream_2.13-2.5.32.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/typelevel/cats-core_2.13/2.4.2/cats-core_2.13-2.4.2.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/akka/akka-actor_2.13/2.5.32/akka-actor_2.13-2.5.32.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/akka/akka-protobuf_2.13/2.5.32/akka-protobuf_2.13-2.5.32.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/ssl-config-core_2.13/0.3.8/ssl-config-core_2.13-0.3.8.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/typelevel/cats-kernel_2.13/2.4.2/cats-kernel_2.13-2.4.2.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/typelevel/simulacrum-scalafix-annotations_2.13/0.5.4/simulacrum-scalafix-annotations_2.13-0.5.4.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/config/1.3.3/config-1.3.3.jar:/Users/user/.m2/repository/org/scala-lang/modules/scala-java8-compat_2.13/0.9.0/scala-java8-compat_2.13-0.9.0.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/scala-lang/modules/scala-parser-combinators_2.13/1.1.2/scala-parser-combinators_2.13-1.1.2.jar
[error]
[error]   last tree to typer: Ident(x)
[error]        tree position: line 25 of /Users/user/workspace/playground/clone-error-test/src/main/scala/example/Hello.scala
[error]             tree tpe: Boolean
[error]               symbol: value x
[error]    symbol definition: x: Boolean (a TermSymbol)
[error]       symbol package: <none>
[error]        symbol owners: value x
[error]            call site: method onPull in package example
[error]
[error] == Source file context for tree position ==
[error]
[error]     22   type Item
[error]     23   sealed trait NextPage
[error]     24   case class Next(page: PageIdentifier) extends NextPage
[error]     25   case class NoMorePages() extends NextPage
[error]     26
[error]     27   def nextPage(a: A): NextPage
[error]     28   def elements(a: A): List[Item]
[error] 	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:171)
[error] 	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:117)
[error] 	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:74)
[error] 	at scala.reflect.internal.TreeGen.mkAttributedQualifierIfPossible(TreeGen.scala:152)
[error] 	at scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker$treeCondStrategy$.withOuterTest(MatchTreeMaking.scala:431)
[error] 	at scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker$treeCondStrategy$.withOuterTest(MatchTreeMaking.scala:339)
[error] 	at scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker.addOuterTest$1(MatchTreeMaking.scala:520)
[error] 	at scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker.mkDefault$1(MatchTreeMaking.scala:530)
[error] 	at scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker.renderCondition(MatchTreeMaking.scala:554)
[error] 	at scala.tools.nsc.transform.patmat.MatchTreeMaking$TreeMakers$TypeTestTreeMaker.<init>(MatchTreeMaking.scala:558)
[error] 	at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.typeTestStep(MatchTranslation.scala:96)
[error] 	at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.nextStep(MatchTranslation.scala:163)
[error] 	at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.translate(MatchTranslation.scala:170)
[error] 	at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translatePattern(MatchTranslation.scala:315)
[error] 	at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translatePattern$(MatchTranslation.scala:315)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translatePattern(PatternMatching.scala:100)
[error] 	at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateCase(MatchTranslation.scala:311)
[error] 	at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateCase$(MatchTranslation.scala:309)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translateCase(PatternMatching.scala:100)
[error] 	at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch(MatchTranslation.scala:224)
[error] 	at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch$(MatchTranslation.scala:192)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translateMatch(PatternMatching.scala:100)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:69)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.internal.Trees$If.transform(Trees.scala:679)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.internal.Trees$DefDef.$anonfun$transform$5(Trees.scala:453)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] 	at scala.reflect.internal.Trees$DefDef.transform(Trees.scala:451)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] 	at scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
[error] 	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] 	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] 	at scala.reflect.internal.Trees$Block.transform(Trees.scala:556)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2591)
[error] 	at scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$2(Trees.scala:2621)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2621)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] 	at scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
[error] 	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] 	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] 	at scala.reflect.internal.Trees$Block.transform(Trees.scala:556)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.internal.Trees$DefDef.$anonfun$transform$5(Trees.scala:453)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] 	at scala.reflect.internal.Trees$DefDef.transform(Trees.scala:451)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] 	at scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
[error] 	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] 	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
[error] 	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
[error] 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
[error] 	at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:342)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
[error] 	at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:342)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:55)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
[error] 	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:90)
[error] 	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:183)
[error] 	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:32)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
[error] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:401)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1519)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1503)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1495)
[error] 	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1609)
[error] 	at xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
[error] 	at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
[error] 	at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:175)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:173)
[error] 	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error] 	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error] 	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:501)
[error] 	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error] 	at sbt.internal.inc.Incremental$.apply(Incremental.scala:167)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2357)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] 	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2310)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (Compile / compileIncremental) java.lang.AssertionError: assertion failed:
[error]   mkAttributedQualifier(example.PagedResponse[Response,PageIdentifier]{type Item = Item}, <none>) parents = List(example.PagedResponse[Response,PageIdentifier])
[error]      while compiling: /Users/user/workspace/playground/clone-error-test/src/main/scala/example/Hello.scala
[error]         during phase: patmat
[error]      library version: version 2.13.6
[error]     compiler version: version 2.13.6
[error]   reconstructed args: -bootclasspath /Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar -classpath /Users/user/workspace/playground/clone-error-test/target/scala-2.13/classes:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/akka/akka-stream_2.13/2.5.32/akka-stream_2.13-2.5.32.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/typelevel/cats-core_2.13/2.4.2/cats-core_2.13-2.4.2.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/akka/akka-actor_2.13/2.5.32/akka-actor_2.13-2.5.32.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/akka/akka-protobuf_2.13/2.5.32/akka-protobuf_2.13-2.5.32.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/ssl-config-core_2.13/0.3.8/ssl-config-core_2.13-0.3.8.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/typelevel/cats-kernel_2.13/2.4.2/cats-kernel_2.13-2.4.2.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/typelevel/simulacrum-scalafix-annotations_2.13/0.5.4/simulacrum-scalafix-annotations_2.13-0.5.4.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/com/typesafe/config/1.3.3/config-1.3.3.jar:/Users/user/.m2/repository/org/scala-lang/modules/scala-java8-compat_2.13/0.9.0/scala-java8-compat_2.13-0.9.0.jar:/Users/user/Library/Caches/Coursier/v1/https/artifactory.nike.com/artifactory/maven-virtual/org/scala-lang/modules/scala-parser-combinators_2.13/1.1.2/scala-parser-combinators_2.13-1.1.2.jar
[error]
[error]   last tree to typer: Ident(x)
[error]        tree position: line 25 of /Users/user/workspace/playground/clone-error-test/src/main/scala/example/Hello.scala
[error]             tree tpe: Boolean
[error]               symbol: value x
[error]    symbol definition: x: Boolean (a TermSymbol)
[error]       symbol package: <none>
[error]        symbol owners: value x
[error]            call site: method onPull in package example
[error]
[error] == Source file context for tree position ==
[error]
[error]     22   type Item
[error]     23   sealed trait NextPage
[error]     24   case class Next(page: PageIdentifier) extends NextPage
[error]     25   case class NoMorePages() extends NextPage
[error]     26
[error]     27   def nextPage(a: A): NextPage
[error]     28   def elements(a: A): List[Item]
```

## problem

This code compiled under numerous previous version of Scala, including Scala 2.13.5.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes https://github.com/scala/bug/issues/12467

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala [hunk 1]
```diff
@@ -429,7 +429,10 @@ trait MatchTreeMaking extends MatchCodeGen with Debugging {
                 || definedInStaticLocation(expectedTp)
                 || testedBinder.info <:< expectedTp
                 || prefixAligns) orig
-              else gen.mkAttributedQualifierIfPossible(expectedPrefix) match {
+              else (expectedPrefix match {
+                case RefinedType(parents, _) if !parents.exists(_.isStable) => None
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala]: can this (or an equivalent) test be part of `prefixAligns`?

```
                          pre.termSymbol match {
                            case NoSymbol => false
```

Comment (dwijnand) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala]: I don't think so because IIRC in the test case it's not the expected type's prefix, but the computed expectedPrefix which is a refined type.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala]: OK, thank you. Looking at it again, it seems the new test would nicely fit into `mkAttributedQualifierIfPossible`.

**Review by lrytz — APPROVED** [review]
