### PR TITLE
Position union preserves point of range [ci: last-only]

### LINKED ISSUE #12074: Bad symbol position if def is infix and rangepos is false
## reproduction steps

using Scala 2.13.3,

```scala
[warn] /Users/.../NumericRangeTest.scala:66:63: local val nr in method t11152_BigDecimalMakesProgress is never used
[warn]       val nr = (BigDecimal("-7", mc2) to BigDecimal("7", mc2) by BigDecimal("0.01", mc2))
[warn]                                                               ^
[warn] /Users/.../NumericRangeTest.scala:67:33: local val upscale in method t11152_BigDecimalMakesProgress is never used
[warn]       val upscale = -700 to 700 by 1
[warn]                                 ^
[warn] two warnings found
```

## problem

Normally it points to the unused identifier.

### PR DESCRIPTION
**Pull request by som-snytt**
`p | q` has `p.point` if `p.isRange`, otherwise `q.point` if `q.isRange`.

If neither is a range, union is a no-op.

Normalize that positions are ranges by default, by removing `-Yrangepos` from tests.

A follow-up could check whether `-Yrangepos:false` is testing offset positions, or if the test used to crash with ranges enabled.

Fixes scala/bug#12074

### CODE REVIEW

**Comment by som-snytt** [comment]
It looks like code anticipates encountering synthetic offset positions while rangepos is enabled, but not the other way around. I didn't investigate the origin of the range pos of the infix expr in parser, or whether the transition to enabling `-Yrangepos` always was shunted. The fix here is that for `p union q`, assume `p.point` even if it is "just" an offset position.

I don't know if this breaks other invariants of the position class hierarchy. The word "hierarchy" doesn't really do it justice.

**Comment by som-snytt** [comment]
Test failure revealed that previous PR to remove .flags neglected to update a test file; similar tests were correctly updated with `-Yrangepos`.

However, the test also shows expr `x + 1` now has non-rangepos-width of 3 instead of 1; maybe that is the todo branch?

**Comment by som-snytt** [comment]
Would be nice to have a test command to make sure I didn't forget to update a check file. `partest --check-check`

**Comment by som-snytt** [comment]
For `x + y`, `x.pos union y.pos` is offset `x.pos`, then `x.pos union +.rangepos` is range with `x.point`, then `+.rangepos union x.pos` is range with `+.point`. Not sure why or if the desired point comes out in the wash. Range calculations with `start` and `end` under `-Yrangepos:false` are misleading rather than degenerate. Just guessing that range for infix expr should union first one leg then the other with `+.rangepos`.

**Comment by som-snytt** [comment]
Hopefully unrelated failure at https://github.com/scala/scala/pull/9106#issuecomment-656863994

Edit: https://github.com/scala/scala/pull/9112

**Comment by lrytz** [comment]
(fyi)
```
!!    1 - run/position-val-def.scala                [output differs]
```

**Comment by som-snytt** [comment]
FYI, still haven't settled on best solution. `val x, y = 42` is rewritten, where the duplicate rhs for `x` has focused pos. The intention is to see the degenerate position and ignore it on union.

**Comment by som-snytt** [comment]
Non-trivial decision about how manage positions. There's another parsing ticket about losing pos in `{block expr}`. Maybe that will motivate further fixings.

**Comment by som-snytt** [comment]
Maybe revisit after https://github.com/scala/scala/pull/10740

**Comment by som-snytt** [comment]
@lrytz Not sure what the current story is for `-Yrangepos:false`. Does that mean never create ranges?

The example is that binop gets a range because `offset.withEnd(end)` produces a range. I tried changing `withEnd` to not promote to range, but that results in breakages.

For example, position of code actions in RefChecks. I think if `sym.pos.isRange`, it's correct to use it instead of computing a range. I'd prefer to be clear about whether I have a range. (I'd prefer `offset.toRange.withEnd(end)`.)

Probably mima will complain about whether `Range extends Offset`. And perhaps any changes to current behavior, with the possible exception of `union`, would be suspicious.

**Comment by som-snytt** [comment]
https://github.com/scala/bug/issues/6768
```
there should be a tested invariant that start <= point <= end.
```
TIL `test/files/positions`. Miles added the `ensureNonOverlapping` for var defs 15 years ago in October. That is what focuses the first tree since Jason's fix (not sure why yet).

**Comment by som-snytt** [comment]
Just realized that the annoying API for `updateAttachment` is flawed.

`updateAttachment(myobject)` does not infer `[myobject.type]` but `Any`. That will zap existing attachments.

From `Importers`, a niche I've never looked at:
```
importAttachments(their.attachments.all).foreach { my.updateAttachment(_) }
```
which could never work. I noticed because I copied the retronym test using `ToolBox`.

I wanted to test for `NamePos` attachment, which seemed to evaporate.

**Comment by lrytz** [comment]
> Not sure what the current story is for `-Yrangepos:false`

Probably we should rather remove that instead of fixing any bugs with it? We certainly still have imperfect range positions, but I'm not aware of any reason to ever disable them at this point. What do you think?

> That will zap existing attachments

Uh! Nice catch 🎣

**Comment by SethTisue** [comment]
> Probably we should rather remove that

I think I agree — we'd rather not have to wonder it's a factor in a bug report or a test failure, right?

**Comment by som-snytt** [comment]
It didn't occur to me that `-Y` has no guarantees, so that we can use ranges without compunction.

File: src/reflect/scala/reflect/internal/util/Position.scala [hunk 1]
```diff
@@ -133,19 +139,34 @@ private[util] trait InternalPositionImpl {
...
+  def focusStart: Position = if (isRange) asOffset(start) else this
+  def focus: Position      = if (isRange) asOffset(point) else this
+  def focusEnd: Position   = if (isRange) asOffset(end) else this
+
+  /** Convert an offset position to a degenerate range.
+   *
+   *  Note that withPoint does not promote to range, but withStart and withEnd may do so.
+   *  It would be more disciplined to require explicit promotion with toRange.
+   */
+  private[scala] def toRange: Position = if (isRange) this else copyRange()
```
Comment (som-snytt) [inline src/reflect/scala/reflect/internal/util/Position.scala]: it's internal API, so if this is desired, it need not be private

File: src/compiler/scala/tools/nsc/typechecker/RefChecks.scala [hunk 2]
```diff
@@ -1838,7 +1838,9 @@ abstract class RefChecks extends Transform {
         )
         if (!isOk) {
           val msg = s"side-effecting nullary methods are discouraged: suggest defining as `def ${sym.name.decode}()` instead"
-          val namePos = sym.pos.focus.withEnd(sym.pos.point + sym.decodedName.length)
+          val namePos =
+            if (sym.pos.isRange) sym.pos
+            else sym.pos.toRange.withEnd(sym.pos.point + sym.decodedName.length)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:1843]: `sym.pos` is the `tree.namePos`. What about names from duplicated trees in for comprehensions? Pos of dup tree is focused, but does it inherit `NamePos`? (Lint uses start to correlate those symbols.)

**Comment by som-snytt** [comment]
> I wanted to test for NamePos attachment, which seemed to evaporate.

I think you were mistaken there, bud. Probably something else was going on... (leaving this as a reminder to look again later).

**Comment by SethTisue** [comment]
do all the Soms eat lunch together?

**Comment by som-snytt** [comment]
How did you know I was hungry?

A watched PR never finishes CI. (A watched pot never boils.)

**Comment by lrytz** [comment]
> > I wanted to test for NamePos attachment, which seemed to evaporate.
> 
> I think you were mistaken there, bud. Probably something else was going on... (leaving this as a reminder to look again later).

Even so, the API seems dubious. Why do `updateAttachment` / `Attachments.update` take a `ClassTag`? They could use `attachment.getClass` instead, no?

```scala
scala> class C; val c = typeOf[C].typeSymbol; object o; object p; object q

scala> c.updateAttachment(p).updateAttachment(q).attachments.all
val res4: Set[Any] = Set(p$@2c974286, q$@3b5c054d)

scala> c.updateAttachment[Any](q).attachments.all
val res5: Set[Any] = Set(q$@3b5c054d)
```

Also, `remove` uses `Class.isInstance`, it could use `equals` instead. I don't think we need to support subclassing of attachments here.

**Review by lrytz — APPROVED** [review]
LGTM (for 2.13.17)

File: build.sbt [hunk 3]
```diff
@@ -196,7 +196,7 @@ lazy val commonSettings = instanceSettings ++ clearSourceAndResourceDirectories
   cleanFiles += (Compile / doc / target).value,
   run / fork := true,
   run / connectInput := true,
-  Compile / scalacOptions ++= Seq("-feature", "-Xlint",
+  Compile / scalacOptions ++= Seq("-feature", "-Xlint", "-opt:local",
```
Comment (lrytz) [inline build.sbt]: we need to be careful this doesn't accidentally disable inlining in release builds

```
➜ sandbox sc -O -opt:inline:'**' -O -Vinline:_ A.scala
> scala compile --server=false -S 2.13 -d . -release 8 -O -opt:inline:** -O -Vinline:_ A.scala
Inlining into A.g: inlined A.f (the callee is annotated `@inline`). Before: 7 ins, after: 15 ins.

➜ sandbox cfr-decompiler A.class

    public int g() {
        return 0;


➜ sandbox sc -O -opt:local -O -opt:inline:'**' -O -Vinline:_ A.scala
> scala compile --server=false -S 2.13 -d . -release 8 -O -opt:local -O -opt:inline:** -O -Vinline:_ A.scala

➜ sandbox cfr-decompiler A.class

    public int g() {
        return this.f();
```

**Review by lrytz — COMMENTED** [review]
lgtm otherwise

**Comment by som-snytt** [comment]
I dropped local `opt` for separate consideration.

There was a use case (having to do with looking at bytecode is easier with cleaner bytecode) but the exact motivation escapes me now.
