### PR TITLE
Warn implicit is wrapper of enclosing class [ci: last-only]

### LINKED ISSUE #12226: -Xlint:implicit-recursion doesn't notice implicit class conversion
## reproduction steps

using Scala? _Yes._

```scala
➜  ✗ scala -nobootcp -Xlint
Welcome to Scala 2.13.3 (OpenJDK 64-Bit Server VM, Java 11.0.7).
Type in expressions for evaluation. Or try :help.

scala> implicit class Elvis[A](alt: => A) { def ?:(a: A): A = if (a ne null) a else alt }
class Elvis

scala> (null: String) ?: "hi"
val res0: String = null

scala> implicit class Elvis[A](alt: => A) { def ?:(a: A): A = if (a ne null) a else alt } // print
implicit class Elvis[A](alt: => A) {
  def ?:(a: A): A = if (Elvis[A](a).ne(null))
    a
  else
    Elvis.this.alt
} // : <notype>
scala> implicit def f[A](a: A): AnyRef = if (a ne null) a else ???
                                                        ^
       error: the result type of an implicit conversion must be more specific than AnyRef
                                             ^
       warning: Implicit resolves to enclosing method f

scala> implicit def f[A](a: A): String = if (a ne null) a else "nope"
                                             ^
       warning: Implicit resolves to enclosing method f
```

## problem

The linter should notice the use of an enclosing implicit thing, as it does for an enclosing method.

Even better, don't go looking to add `ne` and other AnyRef members to my type. One could argue that it's just a form of boxing, but I don't argue that.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12226

Also take Lukas's idea of linting when a conversion adds a universal method.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/tasty/bridge/SymbolOps.scala [hunk 1]
```diff
@@ -74,7 +74,7 @@ trait SymbolOps { self: TastyUniverse =>
     def isTraitParamAccessor: Boolean = sym.owner.isTrait && repr.tflags.is(FieldAccessor|ParamSetter)
 
     def isParamGetter: Boolean =
-      sym.isMethod && sym.repr.tflags.is(FlagSets.ParamGetter)
+      sym.isMethod && /*sym.*/repr.tflags.is(FlagSets.ParamGetter)
```
Comment (SethTisue) [inline src/compiler/scala/tools/nsc/tasty/bridge/SymbolOps.scala]: intentional to leave this?

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/tasty/bridge/SymbolOps.scala]: `sym.repr` is "expressive" but wraps instead of just calling the method. I left it to show intent. The decorator can't be anyval. But if you think it looks like a mistake, I'll zap it.

File: src/compiler/scala/tools/nsc/typechecker/Implicits.scala [hunk 2]
```diff
@@ -135,15 +136,32 @@ trait Implicits extends splain.SplainData {
...
-        val s = if (rts.isAccessor) rts.accessed else if (rts.isModule) rts.moduleClass else rts
-        if (s != NoSymbol && context.owner.hasTransOwner(s))
-          context.warning(result.tree.pos, s"Implicit resolves to enclosing $rts", WarningCategory.WFlagSelfImplicit)
+        val s =
+          if (rts.isAccessor) rts.accessed
+          else if (rts.isModule) rts.moduleClass
+          else rts
+        val rtsIsImplicitWrapper = isView && rts.isMethod && rts.isSynthetic && rts.isImplicit
+        def isSelfEnrichment(encl: Symbol): Boolean =
+          tree.symbol.isParamAccessor && tree.symbol.owner == encl && !encl.isDerivedValueClass
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Implicits.scala:145]: `SelfEnrichment` is a pun for our times.

File: src/compiler/scala/tools/nsc/tasty/bridge/SymbolOps.scala (hunk 1 above)
Comment (SethTisue) [reply src/compiler/scala/tools/nsc/tasty/bridge/SymbolOps.scala]: that was one possible interpretation I considered, but I think on the balance it's more confusing than helpful. especially since there's a `sym.`-less `repr` just 3 lines above

File: src/compiler/scala/tools/nsc/typechecker/Implicits.scala (hunk 2 above)
Comment (SethTisue) [reply src/compiler/scala/tools/nsc/typechecker/Implicits.scala:145]: 😢

**Comment by som-snytt** [comment]
oh I don't need to push anything!

File: test/files/neg/t12226.check [hunk 3]
```diff
@@ -0,0 +1,15 @@
+t12226.scala:6: warning: Implicit resolves to enclosing class Elvis
+  implicit class Elvis[A](alt: => A) { def ?:(a: A): A = if (a ne null) a else alt } // warn
+                                                             ^
```
Comment (lrytz) [inline test/files/neg/t12226.check]: I think the message should tell more precisely what's going on, is that doable? I needed `-Vprint:typer`. Also for the other universal methods.

**Review by lrytz — COMMENTED** [review]
Impl looks good

File: test/files/neg/t12226.check (hunk 3 above)
Comment (som-snytt) [reply test/files/neg/t12226.check]: I'll add `try -Vprint to see what's going on`, ha. BTW in scala 2 it's not necessary to specify typer. I don't know if they'll accept the PR for dotty. I find it very convenient.

**Comment by som-snytt** [comment]
One wonders if that isn't a lot of work just for a warning, but when people lose hours for an issue that, as paulp used to say, `-Xlint` would have told you, then one wonders why dotty doesn't have better linting. And why do they hate `-Xlint`.

**Comment by lrytz** [comment]
Now that I think of it, `adaptToMember` to a member of `AnyRef` should always warn. Maybe even without `-Xlint`?

```scala
scala> implicit class Elvis[A](alt: => A) { def ?:(a: A): A = if (a.asInstanceOf[AnyRef] ne null) a else alt }
class Elvis

scala> def f[A](x: A) = if (x eq null) 0 else 1
def f[A](x: A): Int
```

**Comment by SethTisue** [comment]
Let's save this for 2.13.17, as 2.13.16 is now imminent and I'm growing very cautious.

**Comment by som-snytt** [comment]
No airplanes will fall out of the sky while we fiddle with this warning.

**Comment by som-snytt** [comment]
My previous comment needs to be amended.

**Comment by som-snytt** [comment]
`42.synchronized` was previously deemed suspicious; now, `42.wait` is also deemed dubious.

**Review by lrytz — APPROVED** [review]
Very nice, thank you!

I added a tiny change https://github.com/scala/scala/compare/f0cef92cb12821e3d648eb4f19da876269cee738..24c9a2dadcd601479314e6a8888bcc7cf1ba4056.
