### PR TITLE
Never emit abstract final inner class [ci: last-only]

### LINKED ISSUE #13110: ClassFormatError when extending Kotlin interface with interior enum class
Title is not 100% accurate, but I'm not sure exactly what is broken with the interface.

## Reproduction steps

The following class launches a ClassFormatError whenever loaded:

```scala
import org.intellij.markdown.parser.LookaheadText
import org.intellij.markdown.parser.constraints.MarkdownConstraints
import org.intellij.markdown.parser.markerblocks.MarkerBlock

object Main {
  def main(args: Array[String]): Unit = {
    println(new MyClass)
  }
}

class MyClass extends org.intellij.markdown.parser.markerblocks.MarkerBlock {
  override def acceptAction(closingAction: MarkerBlock.ClosingAction): Boolean = ???
  override def allowsSubBlocks(): Boolean = ???
  override def getBlockConstraints: MarkdownConstraints = ???
  override def getNextInterestingOffset(position: LookaheadText#Position): Int = ???
  override def isInterestingOffset(position: LookaheadText#Position): Boolean = ???
  override def processToken(position: LookaheadText#Position, markdownConstraints: MarkdownConstraints): MarkerBlock.ProcessingResult = ???
}
```

The class is https://github.com/JetBrains/markdown/blob/master/src/commonMain/kotlin/org/intellij/markdown/parser/markerblocks/MarkerBlock.kt, and the following build.sbt imports it:

```
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "2.13.16"
//ThisBuild / scalaVersion := "3.7.1"

lazy val root = (project in file("."))
  .settings(
    name := "untitled358",
    libraryDependencies ++= Seq(
      "org.jetbrains" % "markdown-jvm" % "0.7.3"
    )
  )
```

Here is this reproduction project as a zip: [InnerEnumBug.zip](https://github.com/user-attachments/files/21105943/InnerEnumBug.zip)

And the error:

```
Exception in thread "sbt-bg-threads-1" java.lang.ClassFormatError: Illegal class modifiers in class MyClass: 0x4419
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:103)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at Main$.main(Main.scala:8)
	at Main.main(Main.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at sbt.Run.invokeMain(Run.scala:135)
	at sbt.Run.execute$1(Run.scala:85)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:112)
	at sbt.Run$.executeSuccess(Run.scala:178)
	at sbt.Run.runWithLoader(Run.scala:112)
	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2091)
	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:2030)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:378)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Java can implement the interface fine, so it's some kind of interaction between Kotlin and Scala here. Best theory I have is that `acceptAction(action: ClosingAction): Boolean` breaks it somehow, because `ClosingAction` is a bit of a strange enum, with anonymous class values.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#13110

The commit just massages the flags for the `InnerClasses` attribute. It follows Dotty in dropping `final` and retaining `abstract`.

It might be nicer to notice the discrepancy earlier, ~but for this case it doesn't matter, perhaps~ so go ahead and reset `final` on a symbol that is understood to be abstract by `ClassfileParser`.

This Java test is not meaningful except as a regression test or to demonstrate Java behavior.

The local test:
```
//> using dep org.jetbrains:markdown-jvm:0.7.3
//> using scala 2.13.17-bin-SNAPSHOT

import org.intellij.markdown.parser.LookaheadText
import org.intellij.markdown.parser.constraints.MarkdownConstraints
import org.intellij.markdown.parser.markerblocks.MarkerBlock

object Main {
  def main(args: Array[String]): Unit = {
    println(new MyClass)
  }
}

class MyClass extends MarkerBlock {
  override def acceptAction(closingAction: MarkerBlock.ClosingAction): Boolean = ???
  override def allowsSubBlocks(): Boolean = ???
  override def getBlockConstraints: MarkdownConstraints = ???
  override def getNextInterestingOffset(position: LookaheadText#Position): Int = ???
  override def isInterestingOffset(position: LookaheadText#Position): Boolean = ???
  override def processToken(position: LookaheadText#Position, markdownConstraints: MarkdownConstraints): MarkerBlock.ProcessingResult = ???
}
```
I verified that the class flag fix works without the backstop for the attribute.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala [hunk 1]
```diff
@@ -675,19 +675,29 @@ abstract class BTypes {
...
-        )
-    })
+    def innerClassAttributeEntry: Either[NoClassBTypeInfo, Option[InnerClassEntry]] =
+      for (i <- info) yield
+        i.nestedInfo.force.map {
+          case NestedInfo(_, outerName, innerName, isStaticNestedClass, enteringTyperPrivate) =>
+            var flags = i.flags
+            if (enteringTyperPrivate)
+              flags = (flags & ~Opcodes.ACC_PUBLIC) | Opcodes.ACC_PRIVATE
+            // the static flag in the InnerClass table has a special meaning, see InnerClass comment
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala]:
```suggestion
            // the static flag in the InnerClass table has a special meaning, see ClassBType comment
```

File: src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala [hunk 2]
```diff
@@ -675,19 +675,29 @@ abstract class BTypes {
...
+            if (isStaticNestedClass)
+              flags |= Opcodes.ACC_STATIC
+            else
+              flags &= ~Opcodes.ACC_STATIC
+            if ((flags & Opcodes.ACC_ABSTRACT) != 0)
+              flags &= ~Opcodes.ACC_FINAL
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala:690]:
```suggestion
            // Kotlin interop (scala/bug#13110)
            if ((flags & Opcodes.ACC_ABSTRACT) != 0)
              flags &= ~Opcodes.ACC_FINAL
```

**Review by lrytz — COMMENTED** [review]
To summarize, the issue is that Kotlin generates an arguably wrong InnerClass entry for `MarkerBlock.ClosingAction`. The enum has an abstract method and the classfile is marked `abstract`, but the InnerClass entry gets flags `public final static enum`.

When compiling a Java class that references `MarkerBlock.ClosingAction`, javac copies the InnerClass entry as is, the Java class file also has an InnerClass entry with flags `public final static enum`.

In Scalac we reconstruct the flags for the InnerClass entry from the corresponding symbol flags.

The Symbol flags for `MarkerBlock.ClosingAction` are first set when reading the InnerClass entry (so we get `final`)

https://github.com/scala/scala/blob/7c0198adb7afba3d84869b71f445f39b880d03a8/src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala#L1051

and when completing the symbol (ClassfileLoader) the flags of the `MarkerBlock$ClosingAction` classfile (including `abstract`) are added

https://github.com/scala/scala/blob/7c0198adb7afba3d84869b71f445f39b880d03a8/src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala#L537

(note that `setFlags` does `|=`, not replace).

Should we fix the bad flags combination at that point instead?

File: src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala:685]: ha I said what comment, but wound up just reading all the comments.

**Comment by som-snytt** [comment]
IIRC my debug showed Scala 3 creates the symbol from package completion (which is why it's not final).

I can do a brief experiment with checking flags in classfile parser; but we don't see it yet as abstract; so maybe there is nothing to check without forcing types. Abstract means you have an abstract member.

**Comment by som-snytt** [comment]
I also verified that my change for enum flags did not cause the problem.
```
➜  snips scala-cli run --server=false -d /tmp t13110.scala
Downloading Scala 2.13.11 compiler
Exception in thread "main" java.lang.ClassFormatError: Illegal class modifiers in class MyClass: 0x4419
```
I think `javaClassfileFlags` is not used here; the incoming flags must just be from the type.

The earlier example of coping with unreliable `InnerClasses` is https://github.com/scala/scala/pull/2639/files also had to do with enums, so maybe enums are special in a way not yet understood (either because of how they are specified or not specified, or implemented).

**Comment by som-snytt** [comment]
Added comments, removed the stale joe darcy blog link (already done at scala3), rebased.

My pun is that if you search for that blog, you will find an analysis of Mr Darcy in Pride & Prejudice, which is fitting for an issue about "inner class" consciousness!

**Comment by lrytz** [comment]
> Abstract means you have an abstract member

Right, but we're reading a classfile and the `abstract` flag is there

```
➜ mkd javap -v org/intellij/markdown/parser/markerblocks/MarkerBlock\$ClosingAction.class

public abstract class org.intellij.markdown.parser.markerblocks.MarkerBlock$ClosingAction

...

InnerClasses:
  public static final #100= #2 of #99;    // ClosingAction=class org/intellij/markdown/parser/markerblocks/MarkerBlock$ClosingAction of class org/intellij/markdown/parser/markerblocks/MarkerBlock
```

As I tried to say above, the flags for the symbol are set in two stages. First the flags of the `InnerClass` entry are applied, then when completing the symbol through `ClassfileLoader`, the flags of the classfile are added.

```scala
➜ mkd scala repl -S 2.13 --dep org.jetbrains:markdown-jvm:0.7.3
Welcome to Scala 2.13.16 (OpenJDK 64-Bit Server VM, Java 21.0.1).

scala> :power

scala> val s = rootMirror.getClassIfDefined("org.intellij.markdown.parser.markerblocks.MarkerBlock.ClosingAction")

scala> s.debugFlagString
val res0: String = final sealed <java> <static> <enum>

scala> s.rawInfo.getClass
val res1: Class[_ <: $r.intp.global.Type] = class scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader

scala> s.info // force

scala> s.debugFlagString
val res3: String = final sealed abstract <java> <static> <enum>
```

Wouldn't it be cleaner to apply the workaround in the frontend?

I created a ticket, for the record: https://youtrack.jetbrains.com/issue/KT-79231

**Comment by som-snytt** [comment]
Thanks for your patience. I understood your explanation. Was this where I said I'll try it when I have a free afternoon, and that instead of free as in beer, we should say free as in time? I should put that on my FOSS t-shirt. Oh, let me know if there is urgency because of release schedule, maybe due to Scala 3.

I almost said something about the chestnut about accepting inputs generously and emitting outputs narrowly, and that this was just the latter; I decided against saying that for the reason you gave.

**Comment by lrytz** [comment]
No urgency, if there was I'd do it myself. And if you feel like handing something off, that's always fine too.

I just wasn't entirely sure if you disagree with addressing it in the frontend. So I won't merge this until we agree either way.

**Comment by som-snytt** [comment]
@lrytz ok thanks! I'll try it today. It's probably easy and not scary.

Famous last words; I need dotty to update check files on bootstrapped tests, on the subject of nothing is ever easy. (Edit: that was easy, just `blah-bootstrapped/testCompilation -update-checkfiles`.)

(I no longer stumble over `-update-checkfiles` vs `-update-check` because Scala 3 has to do everything different.)

Edit:

45220ce3b6b44503

I'm not sure how to read the ambiguity: either the scary things are easy and not hard, or easy things are scary but we should try not to be scared. I'm inclined to think it's reasonable to be scared of scary things. And that nothing is easy.

**Review by lrytz — APPROVED** [review]
https://de.wiktionary.org/wiki/doppelt_gen%C3%A4ht_h%C3%A4lt_besser
