### PR TITLE
Error trees conceal references

### LINKED ISSUE #11643: Spurious unused warnings on implicit not found
# Steps to reproduce

Have a build configured as follows:
```scala
scalaVersion := "2.12.8"
scalacOptions ++= List("-Xfatal-warnings", "-Ywarn-unused:params")
```

And a source file:
```scala
object Main {
  def foo(implicit i: Int): Int = i
  def bar(i: Int): Int = i + foo
}
```

# Expected behaviour
Compilation fails with:
```
[error] /path/src/main/scala/Test.scala:3:30: could not find implicit value for parameter i: Int
[error]   def bar(i: Int): Int = i + foo
[error]                              ^
[error] one error found
```
# Observed behaviour
Compilation fails with:
```
[error] /path/src/main/scala/Test.scala:3:30: could not find implicit value for parameter i: Int
[error]   def bar(i: Int): Int = i + foo
[error]                              ^
[error] /path/src/main/scala/Test.scala:3:11: parameter value i in method bar is never used
[error]   def bar(i: Int): Int = i + foo
[error]           ^
[error] two errors found
```

That second error seems spurious - `i` *is* used.

# Notes
This example is minimised, but I've seen up to 20 spurious errors for 1 missing implicit - not a showstopper, but it's certainly painful to sort through the noise to find the interesting error message.

### PR DESCRIPTION
**Pull request by som-snytt**
Instead of not descending into erroneous trees,
just don't register new symbols for diagnostics.

Fixes scala/bug#11643

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 1]
```diff
@@ -17,7 +17,7 @@ import scala.collection.mutable
 import scala.collection.mutable.ListBuffer
 import scala.util.control.Exception.ultimately
 import symtab.Flags._
-import PartialFunction.{condOpt => whenever}
+import PartialFunction.condOpt
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:20]: Seth complained about this at the time. Finally I made it right.

**Review by lrytz — APPROVED** [review]
