### PR TITLE
Respect `@uncheckedVariance` in higher-kinded types (fixing 2.13.2 regression)

### LINKED ISSUE #11968: 2.13.2: @uncheckedVariance is ignored in type member definitions
## reproduction steps

To reproduce execute:

```
git clone https://github.com/7mind/izumi.git
cd izumi
git checkout bug/no-unchecked-variance
sbt compile
```

## problem

Unchecked variance annotations are ignored and variance errors abort compilation:

```
[error] izumi/distage/distage-core-api/src/main/scala/izumi/distage/model/definition/DIResource.scala:776:12: contravariant type RR occurs in invariant position in type [-RR, +EE, +AA]F0[RR @scala.annotation.unchecked.uncheckedVariance,EE @scala.annotation.unchecked.uncheckedVariance,AA @scala.annotation.unchecked.uncheckedVariance] of type F
[error]       type F[-RR, +EE, +AA] = F0[RR @v, EE @v, AA @v]
[error]            ^
[error] izumi/distage/distage-core-api/src/main/scala/izumi/distage/model/definition/DIResource.scala:801:12: contravariant type RR occurs in invariant position in type [-RR, +EE, +AA]F0[RR @scala.annotation.unchecked.uncheckedVariance,EE @scala.annotation.unchecked.uncheckedVariance,AA @scala.annotation.unchecked.uncheckedVariance] @scala.annotation.unchecked.uncheckedVariance of type F
[error]       type F[-RR, +EE, +AA] = F0[RR @v, EE @v, AA @v] @v
[error]            ^
```

Minimized example (https://scastie.scala-lang.org/NupT3nqjS6qGhHIIAYaA3A):

```scala
import scala.annotation.unchecked.uncheckedVariance

trait T {
  type F[+_]
}
object T {
  implicit def fromUnchecked[F0[_]]: T { type F[+A] = F0[A @uncheckedVariance] } = new T {
    type F[+A] = F0[A @uncheckedVariance]
  }
}
```
```
covariant type A occurs in invariant position in type [+A]F0[A @scala.annotation.unchecked.uncheckedVariance] of type F
```

## expectation

Expected code to compile as in 2.13.1.

### PR DESCRIPTION
**Pull request by joroKr21**
A modification of `varianceInType` was necessary to propagate a
boolean flag that controls the behaviour wrt `@uncheckedVaraince`.

Fixes scala/bug#11968

### CODE REVIEW

File: src/reflect/scala/reflect/internal/Variances.scala [hunk 1]
```diff
@@ -300,17 +301,21 @@ trait Variances {
       case MethodType(params, restpe)                      => inSyms(params).flip  & inType(restpe)
       case PolyType(tparams, restpe)                       => inSyms(tparams).flip & inType(restpe)
       case ExistentialType(tparams, restpe)                => inSyms(tparams)      & inType(restpe)
-      case AnnotatedType(annots, tp)                       => inAnnots(annots)     & inType(tp)
+      case AnnotatedType(annots, tp) =>
+        if (considerUnchecked && annots.exists(_.matches(definitions.uncheckedVarianceClass))) Bivariant
+        else inAnnots(annots) & inType(tp)
```
Comment (dwijnand) [inline src/reflect/scala/reflect/internal/Variances.scala]: The vertically-aligned version!

```scala
      case AnnotatedType(annots, _) if unchecked(annots)   => Bivariant
      case AnnotatedType(annots, tp)                       => inAnnots(annots)     & inType(tp)
```

😄

**Review by dwijnand — COMMENTED** [review]
Seems good to me.  But probably good for someone else to give the nod.

File: src/reflect/scala/reflect/internal/Variances.scala (hunk 1 above)
Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Variances.scala]: We could make it happen 😄

**Review by lrytz — APPROVED** [review]
👍
