### PR TITLE
Improve inferred-`Any` lint (fixing false positives and false negatives)

### LINKED ISSUE #9211: Better tracking of inferred types and constraints for lint analysis
```scala
Welcome to Scala version 2.11.6-20150309-134842-c11032c6b1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_40).
Type in expressions to have them evaluated.
Type :help for more information.

scala> trait T[A] ; class C extends T[Any]
defined trait T
defined class C

scala> def f[A](t: T[A]) = ()
f: [A](t: T[A])Unit

scala> f(new C)
<console>:11: warning: a type was inferred to be `Any`; this may indicate a programming error.
              f(new C)
                ^
```

### LINKED ISSUE #12320: -Xlint:infer-any doesn't catch all scenarios where a type is inferred to be Any
## Reproduction steps

using Scala 2.13.3,

Run scala with `scala -Xlint:infer-any -Wconf:cat=lint-infer-any:error`
```scala
scala> Option.empty[Int].contains("") // this errors as expected
                         ^
       error: a type was inferred to be `Any`; this may indicate a programming error.

scala> Option.empty[Int].contains("") || false // this does not throw an error, even though a type was inferred to be `Any`
val res1: Boolean = false
```
or, to see type information:
This fails as expected:
```
scalac -Xlint:infer-any -Wconf:cat=lint-infer-any:error -Xprint:typer /dev/stdin <<<'object Main { Option.empty[Int].contains("") }'
```
This doesn't fail (even though it should, according to the typer output):
```
scalac -Xlint:infer-any -Wconf:cat=lint-infer-any:error -Xprint:typer /dev/stdin <<<'object Main { Option.empty[Int].contains("") || ??? }'
```

## Problem
Expectation: The linter reports all instances of `Any` being inferred when `-Xlint:infer-any` is enabled
Actual: The linter sometimes doesn't report instances of `Any` being inferred with `-Xlint:infer-any` enabled

### PR DESCRIPTION
**Pull request by som-snytt**
`-Xlint:infer-any`, which is part of the default `-Xlint` bundle, warns if an inferred type argument is a "top" type: `Any`, `AnyVal`, `AnyRef`, or `Object`.

The heuristic has been improved not to warn if a type parameter in the expression has an upper or lower bound that is a "top" type.

Typically, the warning is "silenced" by supplying an explicit type argument where needed, if the usage was intended.

It no longer considers whether the "expected type" is `Any`. Previously, just passing an expression to `println` would silence the warning.

Examples illustrating the errors to avoid:

```
scala> Option("hello, world").contains(42)
                              ^
       warning: a type was inferred to be `Any`; this may indicate a programming error.
val res0: Boolean = false

scala> List(42 -> 27).indexOf(42, 27) // indexOf is overloaded
                      ^
       warning: a type was inferred to be `Any`; this may indicate a programming error.
val res1: Int = -1

scala> List(42 -> 27).indexOf((42, 27)) // intended
val res2: Int = 0

scala> println(List(42 -> 27).indexOf(42, 27))
                              ^
       warning: a type was inferred to be `Any`; this may indicate a programming error.
-1
```
Supplying a type argument to an infix expression is irregular syntax in Scala 2, so it may be necessary to rewrite it:
```
scala> "hello, world" :: 42 :: Nil
                      ^
       warning: a type was inferred to be `Any`; this may indicate a programming error.
val res4: List[Any] = List(hello, world, 42)

scala> List[Any]("hello, world", 42)
val res5: List[Any] = List(hello, world, 42)

scala> { ::[Any]("hello, world", 42 :: Nil) }
val res6: scala.collection.immutable.::[Any] = List(hello, world, 42)
```

Fixes scala/bug#12320

Closes scala/bug#9211

### CODE REVIEW

**Comment by som-snytt** [comment]
It seems to me the lint is correct and the signature should include the bound:
```
def containsSlice[B >: A](that: Seq[B]): Boolean
```
Yesterday I experimented with trying to clear buffered warnings when retrying a result in typedApply, but I omitted that, since it seemed fragile given limitations of context reporting. But maybe the naive approach of always warning is worth any false positives. Probably I won't attempt anything nuanced and complicated here for limited bang/buck ratio. `-Wconf` to the rescue.

File: src/scalap/scala/tools/scalap/scalax/rules/scalasig/ScalaSig.scala [hunk 1]
```diff
@@ -170,7 +170,7 @@ object ScalaSigEntryParsers extends RulesWithState with MemoisableRules {
   val index = read(_.index)
   val key = read(_.entryType)
 
-  lazy val entry: EntryParser[Any] = symbol | typeEntry | literal | name | attributeInfo | annotInfo | children | get
+  lazy val entry: EntryParser[Any] = (symbol: EntryParser[Any]) | typeEntry | literal | name | attributeInfo | annotInfo | children | get
```
Comment (som-snytt) [inline src/scalap/scala/tools/scalap/scalax/rules/scalasig/ScalaSig.scala]: Intuitively, the outermost `Any` on LHS should suffice.

The parens are superfluous but clarifying.

File: src/library/scala/collection/Seq.scala [hunk 2]
```diff
@@ -514,7 +514,7 @@ trait SeqOps[+A, +CC[_], +C] extends Any
    *  @return  `true` if this $coll contains a slice with the same elements
    *           as `that`, otherwise `false`.
    */
-  def containsSlice[B](that: Seq[B]): Boolean = indexOfSlice(that) != -1
+  def containsSlice[B >: A](that: Seq[B]): Boolean = indexOfSlice(that) != -1
```
Comment (som-snytt) [inline src/library/scala/collection/Seq.scala]: Another containment problem per the ticket.

File: test/junit/scala/collection/MapTest.scala [hunk 3]
```diff
@@ -50,8 +50,8 @@ class MapTest {
     val m = (1 to 10).map(x => (x, x)).toMap
     val m1 = m ++: m
     assertEquals(m.toList.sorted, (m1: Map[Int, Int]).toList.sorted)
-    val s1 = List(1) ++: m
-    assertEquals(1 :: m.toList.sorted, (s1: Iterable[Any]).toList.sortBy({case (x: Int, _) => x; case x: Int => x}))
+    val s1: Iterable[Any] = List(1) ++: m
+    assertEquals(1 :: m.toList.sorted, s1.toList.sortBy { case (x: Int, _) => x ; case x: Int => x })
```
Comment (som-snytt) [inline test/junit/scala/collection/MapTest.scala]: Superfluous parens scalafix wasn't triggered?

File: test/junit/scala/collection/SetMapConsistencyTest.scala [hunk 4]
```diff
@@ -307,11 +307,11 @@ class SetMapConsistencyTest {
...
   // Actual tests
-  val smallKeys = Array(0, 1, 42, 9127)
-  val intKeys = smallKeys ++ Array(-1, Int.MaxValue, Int.MinValue, -129385)
-  val longKeys = intKeys.map(_.toLong) ++ Array(Long.MaxValue, Long.MinValue, 1397198789151L, -41402148014L)
+  val smallKeys  = Array(0, 1, 42, 9127)
+  val intKeys    = smallKeys ++ Array(-1, Int.MaxValue, Int.MinValue, -129385)
+  val longKeys   = intKeys.map(_.toLong) ++ Array(Long.MaxValue, Long.MinValue, 1397198789151L, -41402148014L)
   val stringKeys = intKeys.map(_.toString) ++ Array("", null)
-  val anyKeys = stringKeys.filter(_ != null) ++ Array(0L) ++ Array(true) ++ Array(math.Pi)
+  val anyKeys    = (stringKeys.filter(_ != null) ++ Array(0L): Array[Any]) ++ Array(true) ++ Array(math.Pi)
```
Comment (som-snytt) [inline test/junit/scala/collection/SetMapConsistencyTest.scala]: More clarifying but superfluous parens?

**Comment by lrytz** [comment]
Here's another example that this fixes:

```
scala> object t { def f(x: String) = 0; def f[T >: String](x: T) = 1 }
object t

scala> t.f(1)
         ^
       warning: a type was inferred to be `Any`; this may indicate a programming error.
error: No warnings can be incurred under -Werror.
```

I didn't manage to come up with a counter-example where the warning is issued in silent type checking but then the non-Any alternative is chosen, maybe someone else does?

File: src/compiler/scala/tools/nsc/typechecker/Infer.scala [hunk 5]
```diff
@@ -582,7 +582,7 @@ trait Infer extends Checkable {
         }
       }
       val targs = solvedTypes(tvars, tparams, varianceInTypes(formals), upper = false, lubDepth(formals) max lubDepth(argtpes))
-      if (settings.warnInferAny && context.reportErrors && !fn.isEmpty) {
+      if (settings.warnInferAny && !fn.isEmpty) {
```
Comment (dwijnand) [inline src/compiler/scala/tools/nsc/typechecker/Infer.scala]: > I see that it silences the warning because it may want to rejigger the enclosing application. Letting it ignore that the context is non-erroring shows the warning.

Given that `reportErrors` is `!(bufferErrors || reporter.isThrowing)` my first thought is should this stay at least `!reporter.isThrowing`.

But more broadly, is it safe to ignore buffering?  `TryTwice` uses `inSilentMode` up to twice, but `InferMethodAlternativeTwice` (which extends `TryTwice`) adds to that by uses `inSilentMode` within that silent mode for each alternative in the overloaded type, and does so up to twice.  So that's potentially a lot of times we're running `isApplicable` - don't we risk false negatives?

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Infer.scala]: Yes, it is risky. I briefly tried "clearWarnings" up the stack, but that looked brittle to me.

It needs better infrastructure to track and then warn, but that won't happen here.

If a good example of false example turns up, that would help determine if this is too risky. Also see if the only downside is more warning suppression.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Infer.scala]: My other thought was a warning is now issued that conceals a subsequent warning at the same pos.

**Comment by SethTisue** [comment]
(as Dale pointed out in conversation) this is a good candidate for https://github.com/scala/community-build/issues/1270 (which I set aside when it became no-longer-urgent on some other PR, but still intend to return to).

**Comment by som-snytt** [comment]
Moved the clean-up tweaks to a non-controversial PR.

It has to be wrong to lint code which isn't expected to compile.

A useful community build would indicate how bad the false positives are, or provide a helpful example. But it's better for 9 inferences of Any to go free than for one innocent LOC to be quarantined on false witness.

**Comment by som-snytt** [comment]
There are a few tickets for improvements: some missing warnings (may due to eta expansion), and not warning on `if/else`.

**Comment by som-snytt** [comment]
The current behavior change is the test for 9211, which currently warns (false positive).

Also adds a warning in t12441 (which was the silent warning change), where the pt is not relevant. (That would mean never warning for calls to println.)

This is a simplification and improvement, a clear win. Not sure why users are not yet profiting.

The warnings in test code demonstrate effectiveness. Non-test code was previously improved.

The code comment mentions the line in Map to avoid warning, but that is currently linted.

**Review by lrytz — APPROVED** [review]
LGTM. It's probably worth `release-notes`. Could you udpate the PR description?

**Comment by som-snytt** [comment]
PSA
```
scala> ::[Any]("hello, world", 42 :: Nil)
No such command '::[Any]("hello,'.  Type :help for help.

```
