### PR TITLE
CodePrinter prints backquoted names

### LINKED ISSUE #9250: reflection's CodePrinter outputs incorrect code
This is one is correct:

```scala
scala> println(showCode(q"""val ${TermName("someVal")}: String = "lala""""))
val someVal: String = "lala"
```

so is this one:

```scala
scala> println(showCode(q"""val ${TermName("some weird val")}: String = "lala""""))
val `some weird val`: String = "lala"
```

but not this one:

```scala
scala> println(showCode(q"""val ${TermName("some-val")}: String = "lala""""))
val some-val: String = "lala" //notice that some-val is not backticked, so it wont compile
```

I have to "encode.toTermName" it in order to get it right:

```scala
scala> println(showCode(q"""val ${TermName("some-val").encodedName.toTermName}: String = "lala""""))
val `some-val` : String = "lala"
```

### PR DESCRIPTION
**Pull request by chaitanyav**
```scala
scala> import scala.reflect.runtime.universe._
import scala.reflect.runtime.universe._

scala> print(showCode(q"""val ${TermName("some-val")} = 1"""))
val `some-val` = 1

scala> print(showCode(q"""val ${TermName("some$minusval")} = 1"""))
val `some-val` = 1

scala> print(showCode(q"""val ${TermName("foo-bar-goo")} = 1"""))
val `foo-bar-goo` = 1

scala> print(showCode(q"""val ${TermName("foo-bar goo")} = 1"""))
val `foo-bar goo` = 1

scala> print(showCode(q"""val ${TermName("some-val")}:String = "lala""""))
val `some-val`: String = "lala"

scala> print(showCode(q"""val ${TermName("some$minusval")}:String = "lala""""))
val `some-val` : String = "lala"
```
@SethTisue @VladimirNik @densh Please review.

Fixes scala/bug#9250

### CODE REVIEW

**Comment by som-snytt** [comment]
I updated the title to be direct and descriptive, and updated the comment with the "fixes" phrase. You'll want to update the commit text with an improved title, too. They used to have issue numbers in commit text but no longer. Also they used to at-notify reviewers but that is not necessary because of the "reviewers" widget in github on the right side.

File: src/reflect/scala/reflect/internal/Printers.scala [hunk 1]
```diff
@@ -562,7 +562,7 @@ trait Printers extends api.Printers { self: SymbolTable =>
 
       def addBackquotes(s: String) =
         if (decoded && (decName.exists(ch => brackets.contains(ch) || isWhitespace(ch) || isDot(ch)) ||
-          (name.isOperatorName && decName.exists(isOperatorPart) && decName.exists(isScalaLetter) && !decName.contains(bslash))))
+          (name.isOperatorName && decName.exists(isOperatorPart) && decName.exists(isScalaLetter) && !decName.contains(bslash)) || (decName.exists(isOperatorPart) && decName.exists(isScalaLetter) && !decName.contains(bslash))))
```
Comment (som-snytt) [inline src/reflect/scala/reflect/internal/Printers.scala]: It looks like you just duplicated the expression and dropped one condition, which is redundant.

Is the `isOperatorName` test too strict? Also I'm not sure why the issue says it's OK to supply an unencoded name.

Comment (chaitanyav) [reply src/reflect/scala/reflect/internal/Printers.scala]: `name.isOperatorName` is true if name contains operator names like `$plus`, `$times`, `$minus`  when decoded the operator name becomes a operator (e.g `$plus` becomes `+`). 
The condition `(name.isOperatorName && decName.exists(isOperatorPart) && decName.exists(isScalaLetter) && !decName.contains(bslash))` will only be true for names like `x$plusy`.

 If name is already decoded like `x-y` then this condition will fail and the generated code is not valid. To make it produce valid code (identifier according to https://www.scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html) I had to omit the name.isOperatorName.

```scala
scala> print(showCode(q"""val ${TermName("x$plusy")} = 1"""))
val `x+y` = 1
scala> print(showCode(q"""val ${TermName("x-y")} = 1"""))
val `x-y` = 1
```

I could have written
` ((name.isOperatorName || decName.exists(isOperatorPart)) && decName.exists(isScalaLetter) && !decName.contains(bslash))` instead of duplicating it which is better. Let me change it.

**Comment by chaitanyav** [comment]
@SethTisue the build has not started.

**Comment by SethTisue** [comment]
our Jenkins ran out of disk yesterday — should be fixed now — new build (just started) is https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/12646/

**Comment by chaitanyav** [comment]
thank you @SethTisue , it did not work. i think it tried to start the build at a non-existing commit.

**Review by dwijnand — APPROVED** [review]
Looks reasonable to me.  Thanks for the fix!

**Comment by chaitanyav** [comment]
@SethTisue @som-snytt @dwijnand @Irytz Thank you.
