### PR TITLE
Close long-standing soundness loophole involving overriding and bridge methods

### LINKED ISSUE #9912: Unsoundness involving generic type and same-named methods
The following code

```
class A {
  def compareTo(o: Any): Int = 0
}
class B extends A with Comparable[B] {
  def compareTo(b: B): Int = 0
}
object C {
  def main(args: Array[String]): Unit = {
    println(new B().compareTo(new Object()))
  }
}
```

compiles without warnings.  And it should be executed without any runtime error.  However, ClassCastException occurs when the code is executed.

This problem is also known as an already fixed bug of Java Generics:

http://www.concurrentaffair.org/2006/10/10/java-generics-unsound/

### PR DESCRIPTION
**Pull request by som-snytt**
An error with inheritance that previously resulted in a runtime exception is now correctly rejected.

Erasure already checks that if the bridge overrides a member, then the bridged method also overrides that member. The check was restricted to members cavorting with `AnyVal`; this commit includes bridge methods with an `Object`-typed parameter, since it is more possible to clash with a user-written member. (More correctly, bridge methods with parameters which are erased type parameters, where erasure is to an upper bound, which might be `Object`.)

Fixes scala/bug#9912

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/Erasure.scala [hunk 1]
```diff
@@ -495,11 +495,13 @@ abstract class Erasure extends InfoTransform
...
 
     /** Check that a bridge only overrides members that are also overridden by the original member.
-     *  This test is necessary only for members that have a value class in their type.
+     *  This test is necessary only* for members that have a value class in their type.
      *  Such members are special because their types after erasure and after post-erasure differ/.
      *  This means we generate them after erasure, but the post-erasure transform might introduce
      *  a name clash. The present method guards against these name clashes.
      *
+     *  *Note: Also check bridges with `Object`-typed params, as users might write that signature in a parent.
+     *
```
Comment (SethTisue) [inline src/compiler/scala/tools/nsc/transform/Erasure.scala:514]: Instead of using a footnote, I think it would be better to just revise the comment to reflect the current status.

**Review by SethTisue — CHANGES_REQUESTED** [review]

**Comment by SethTisue** [comment]
Community build results will improve our confidence this won't produce false positives.

File: src/compiler/scala/tools/nsc/transform/Erasure.scala [hunk 2]
```diff
@@ -582,17 +584,16 @@ abstract class Erasure extends InfoTransform
...
-
+      val shouldAdd = {
+        val sigContainsValueClass = member.tpe.exists(_.typeSymbol.isDerivedValueClass)
+        def bridgeMayClash = bridge.paramss.exists(_.exists(p => p.tpe =:= ObjectTpe || isTrivialTopType(p.tpe)))
+        def bridgeIsAOK = checkBridgeOverrides(member, other, bridge) match {
+          case Nil => true
+          case es if member.owner.isAnonymousClass => resolveAnonymousBridgeClash(member, bridge); true
+          case es => for ((pos, msg) <- es) reporter.error(pos, msg); false
+        }
+        if (sigContainsValueClass || bridgeMayClash) bridgeIsAOK else true
```
Comment (SethTisue) [inline src/compiler/scala/tools/nsc/transform/Erasure.scala]: perhaps a little clearer as:

```scala
!(sigContainsValueClass || bridgeMayClash) || bridgeIsAOK
```

or not, matter of taste I guess?

File: src/compiler/scala/tools/nsc/transform/Erasure.scala [hunk 3]
```diff
@@ -582,17 +584,16 @@ abstract class Erasure extends InfoTransform
...
-        ||  (checkBridgeOverrides(member, other, bridge) match {
-              case Nil => true
-              case es if member.owner.isAnonymousClass => resolveAnonymousBridgeClash(member, bridge); true
-              case es => for ((pos, msg) <- es) reporter.error(pos, msg); false
-            })
-      )
-
+      val shouldAdd = {
+        val sigContainsValueClass = member.tpe.exists(_.typeSymbol.isDerivedValueClass)
+        def bridgeMayClash = bridge.paramss.exists(_.exists(p => p.tpe =:= ObjectTpe || isTrivialTopType(p.tpe)))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/transform/Erasure.scala]: It seems `Object` is not sufficient?

```scala
➜ sandbox spr 10100
Welcome to Scala 2.13.9-20220730-031046-9de07a7 (OpenJDK 64-Bit Server VM, Java 17.0.1).
Type in expressions for evaluation. Or try :help.

scala> class A; class B extends A

scala> class C1 { def compareTo(a: A): Int = 0 }

scala> trait C2[T <: A]{ def compareTo(t: T): Int }

scala> class C3 extends C1 with C2[B] { def compareTo(b: B): Int = 1 }

scala> (new C3).compareTo(new A)
java.lang.ClassCastException: class A cannot be cast to class B (A and B are in unnamed module of loader scala.tools.nsc.interpreter.IMain$TranslatingClassLoader @76396509)
  at C3.compareTo(<console>:1)
  ... 32 elided
```

File: src/compiler/scala/tools/nsc/transform/Erasure.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/transform/Erasure.scala]: It took me two tries to get it right, so I decided not to be clever, but I am willing to upgrade.

File: src/compiler/scala/tools/nsc/transform/Erasure.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/transform/Erasure.scala:514]: Technically, a footnote would go in the page footer. I think they have `@implNote` or similar? in Java is it. I see a stray asterisk, a planetary punctuation.

File: src/compiler/scala/tools/nsc/transform/Erasure.scala (hunk 3 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/transform/Erasure.scala]: Now it looks at the params of `other` for a `f(t: T)`.

**Review by lrytz — APPROVED** [review]
Thank you @som-snytt, very nice fix!

**Comment by SethTisue** [comment]
No community build issues.
