### PR TITLE
Fix type inference involving wildcards

### LINKED ISSUE #11558: Java higher-order methods inconsistently require type annotations
This works:
```scala
scala> import java.util.stream.Stream
import java.util.stream.Stream

scala> Stream.of(1,2,3).map(_ + 1)
res20: java.util.stream.Stream[?0] = java.util.stream.ReferencePipeline$3@27014faf
```

But then, you'd think that this should work:

```scala
scala> Stream.of(1,2,3).map(_.toString)
                              ^
       error: type mismatch;
        found   : Int => String
        required: java.util.function.Function[_ >: Int, _]

```

It can be made to work only by including the map type param:
```scala
scala> Stream.of(1,2,3).map[String](_.toString)
res22: java.util.stream.Stream[String] = java.util.stream.ReferencePipeline$3@7e7daeac
```

This would hopefully work because it does actually work in java:

```java
Stream.of(1,2,3).map(i -> i.toString());
```

### PR DESCRIPTION
**Pull request by adriaanm**
Use == instead of =:= because we're looking for occurs, not equality.

When we were using =:= to detect occurrences of type params in bounds,
we'd accidentally unify too much (e.g. on wildcards / other type vars).

Discovered while looking into why this doesn't type check:
`java.util.stream.Stream.of(1,2,3).map(_.toString)`

I noticed that there was cross talk between the type params of java.util.Function during type inference.

This partially regressed in scala/scala#6492, but was actually wrong since the one with `*** empty log message ***`

Fix scala/bug#11558
Relates to scala/scala-dev#184

### CODE REVIEW

**Comment by retronym** [comment]
Confirming that the problematic example from scala/scala-dev#184 progresses here.

Before:

```
scala> "abc".chars.boxed.map(x => x.toString).collect(java.util.stream.Collectors.toList())
                               ^
       error: type mismatch;
        found   : Integer => String
        required: java.util.function.Function[_ >: Integer, _]
```

After:

```
scala> "abc".chars.boxed.map(x => x.toString).collect(java.util.stream.Collectors.toList())
res4: java.util.List[String] = [97, 98, 99]
```

**Comment by retronym** [comment]
Standalone test case that progresses:

```
trait F1[A, B] { def apply(a: A): B }; trait S[T] { def map[R](f: F1[_ >: T, _ <: R]): S[R] }; (f: S[Int]) => f.map(_.toString)
```

File: src/reflect/scala/reflect/internal/tpe/TypeConstraints.scala [hunk 1]
```diff
@@ -240,26 +241,20 @@ private[internal] trait TypeConstraints {
...
-            // Try to derive more constraints for `tvar` (and `tparam`) from its symmetric occurrences in the bounds of other tparams.
-            // `tparam` is the upper bound of `tvarOther`. Flip that, and add `tvarOther` as an lower bound for `tvar`.
-            // Use =:=, so that we equate eta-expanded type constructors (polytypes) and the equivalent no-arg typeref.
-            tvars.foreach { tvarOther =>
-              val tparamOther = tvarOther.origin.typeSymbol
-              if ((tparamOther ne tparam) && tparamOther.info.upperBound =:= tparamTycon)
-                tvar.addLoBound(tvarOther)
+          // Try to derive more constraints for `tvar` (and `tparam`) from its symmetric occurrences in the bounds of other tparams.
+          // `tparam` is the lower bound of `tvarOther`. Flip that, and add `tvarOther` as an upper bound for `tvar`.
+          // Use =:=, so that we equate eta-expanded type constructors (polytypes) and the equivalent no-arg typeref.
```
Comment (retronym) [inline src/reflect/scala/reflect/internal/tpe/TypeConstraints.scala]: Is this comment out of date? I don't see an `=:=` below anymore.

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/tpe/TypeConstraints.scala]: Yes, I’ll drop it

**Comment by retronym** [comment]
Pulling a few more threads in https://github.com/retronym/scala/tree/review/8129

**Comment by adriaanm** [comment]
@retronym I incorporated a few strands of your review branch. LGTY?

**Review by retronym — APPROVED** [review]

**Comment by SethTisue** [comment]
regression in overload resolution: https://github.com/scala/bug/issues/11755
