### PR TITLE
Remove redundant null check when matching value classes with extractor

### LINKED ISSUE #12405: Unnecessary allocation in name-based matching on value class
```scala
final class OptionVal[+A](val x: A) extends AnyVal {
  def isEmpty: Boolean =
    x == null
  def get: A =
    if (x == null) throw new NoSuchElementException("OptionVal.None.get")
    else x
}

object OptionVal {
  object Some {
    def apply[A](x: A): OptionVal[A] = new OptionVal(x)
    def unapply[A](x: OptionVal[A]): OptionVal[A] = x
  }
  def none[A]: OptionVal[A] = None.asInstanceOf[OptionVal[A]]
  val None = new OptionVal[Null](null)
}

class Test {
  def foo: OptionVal[String] = ???
  def bar = foo match {
    case OptionVal.Some(s) => s
    case _ => ""
  }
}
```

The 2.13 compiler emits a redunand `null` check on a freshly created `OptionVal` instance.

```
    public String bar() {
        String s;
        String string;
        String string2 = this.foo();
        String string3 = new OptionVal<String>(string2) != null && !OptionVal$.MODULE$.isEmpty$extension(string = OptionVal.Some$.MODULE$.unapply(string2)) ? (s = OptionVal$.MODULE$.get$extension(string)) : "";
        return string3;
    }
```

This was not the case in 2.12:
```
    public String bar() {
        String s;
        String string = this.foo();
        String string2 = OptionVal.Some$.MODULE$.unapply(string);
        String string3 = !OptionVal$.MODULE$.isEmpty$extension(string2) ? (s = OptionVal$.MODULE$.get$extension(string2)) : "";
        return string3;
    }
```

### PR DESCRIPTION
**Pull request by lrytz**
Follow-up for https://github.com/scala/scala/pull/6485

Fixes https://github.com/scala/bug/issues/12405

### CODE REVIEW

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala [hunk 1]
```diff
@@ -123,16 +123,9 @@ trait MatchTranslation {
...
-            // skip null test if it's implied
-            if (binderKnownNonNull) {
-              val unappBinder = typeTest.nextBinder
-              (typeTest :: treeMakers(unappBinder, pos), unappBinder)
-            } else {
-              val nonNullTest = NonNullTestTreeMaker(typeTest.nextBinder, paramType, pos)
-              val unappBinder = nonNullTest.nextBinder
-              (typeTest :: nonNullTest :: treeMakers(unappBinder, pos), unappBinder)
-            }
+            // binder is known non-null because the type test would not succeed on `null`
```
Comment (dwijnand) [inline src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala:126]: I'm not sure if this is really dead code...  Such as the outer pointer check.  Can we prove it's not?  Otherwise might be worth keeping, even with a follow-up TODO added.

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala [hunk 2]
```diff
@@ -214,11 +214,11 @@ trait MatchTreeMaking extends MatchCodeGen with Debugging {
       val nullCheck = REF(prevBinder) OBJ_NE NULL
       lazy val localSubstitution = Substitution(Nil, Nil)
 
-      def isExpectedPrimitiveType = isPrimitiveValueType(expectedTp)
+      def skipNullTest = isPrimitiveValueType(expectedTp) || expectedTp.typeSymbol.isDerivedValueClass
```
Comment (dwijnand) [inline src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala:217]: I'm not sure this is correct either. 😞

Using the example in scala/bug#12405 `new OptionVal<String>(string2) != null` is wrong, but it shouldn't go completely, it should be `string2 != null` as I see it.

(To be honest I don't quite understand why the `OptionVal.Some$.MODULE$.unapply` call is missing too - seems wrong to me...)

Comment (dwijnand) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala:217]: Found the unapply.  And understand now how the null check is redundant.

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala (hunk 1 above)
Comment (dwijnand) [reply src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala:126]: Turns out outer checks aren't "rendered" by the impliesBinderNonNull translation strategy.  Meaning this is indeed always true.

**Comment by viktorklang** [comment]
Nice work, @lrytz and @dwijnand!
