### PR TITLE
Bulk ops on TreeSet/TreeSet or TreeMap/TreeMap prefer keys from the left

### LINKED ISSUE #12042: RedBlackTree regressions need merge from 2.12.x for 2.13.3
Duplicate of #12039, to track it as a blocker of 2.13.3.

### PR DESCRIPTION
**Pull request by retronym**
The test suite that aimed to bring all of our sets and maps into
line did not exercise code paths optimized for:

   collection.$op(collectionOfSameType)

This commit updates the test to:

   - add test variants that generate operands of the same type as the
     input collection
   - add "preserves identity" tests for set intersection
   - fix the resulting failures by flipping the operands
     in `RedBlackTree.{union,intersection}`

I've also added concrete test cases to `Tree{Map,Set}Test` that
are easier to review and that also exercise builders.

Fixes scala/bug#12042

Backporting will remedy scala/bug#12039

### CODE REVIEW

**Comment by retronym** [comment]
Heads up @raboof. In https://github.com/akka/akka/pull/26043/files#diff-2223f4fc82176be1aa846ce301a60c80L212, you worked around this bug thinking it was an intended behaviour change in 2.13.x. I believe your workaround will still work when fix this bug, given that you're cross building against 2.12.11 which has the old, correct behaviour.

**Comment by raboof** [comment]
Thanks - I indeed thought it was an intended (or at least accepted) change (though I don't remember why...), sorry about not flagging it!

> I believe your workaround will still work when fix this bug

Agreed, and I don't think we use this anywhere performance-sensitive, so we'll probably leave it as is.

File: test/junit/scala/collection/SetMapRulesTest.scala [hunk 1]
```diff
@@ -154,6 +155,13 @@ class SetMapRulesTest {
     checkPreservesKeyIdentities(gen, "updated (equal value)")(_.updated(Value(1,2), Value(101,2)))
     checkPreservesKeyIdentities(gen, "+ (identical value)")(_.+((Value(1,2), Value(101,1))))
     checkPreservesKeyIdentities(gen, "+ (equal value)")(_.+((Value(1,2), Value(101,2))))
+
+    val values = Seq((Value(1,2), Value(101,2)))
+    val valuesSameCollection = gen().take(0).concat(values)
+    for (vs <- Seq(values, valuesSameCollection)) {
+      checkPreservesKeyIdentities(gen, "concat (identical key)")(_.concat(vs.asInstanceOf[IterableOnce[(Value, Value)]]))
```
Comment (lrytz) [inline test/junit/scala/collection/SetMapRulesTest.scala]: redundant cast?

**Review by lrytz — APPROVED** [review]
LGTM

**Review by lrytz — APPROVED** [review]

**Comment by ijuma** [comment]
It's a bit hard to understand the impact of this bug. Can someone clarify please? It will make it easier to check if applications are impacted.

**Comment by lrytz** [comment]
It's about questions like this: given two objects such that `(a == b) && (a ne b)`, which element does `(Set(a) + b)` store? This area of the collections library was under-specified before 2.13, and 2.12 collections are inconsistent. In 2.13 we consider such inconsistencies bugs.

I don't know if there's a "more official" place where that "spec" lives than this code comment: https://github.com/scala/scala/blob/db119f9be22674faf2cee3ced41050c07152a832/test/junit/scala/collection/SetMapRulesTest.scala#L24-L37

There should be a better place for it.

Does that clarify?

**Comment by ijuma** [comment]
Yes, thanks! So, this issue only matters if one cares about identity. If all one cares about is equality, there is no change in behavior?

**Comment by lrytz** [comment]
Yes, that's right.

**Comment by SethTisue** [comment]
followup PR: #9078
