### PR TITLE
Collect nowarn symbols instead of skipping them

### LINKED ISSUE #13095: false positive unused warning in for comprehensions
## Reproduction steps

Scala 2.13.15, 2.13.16 and `2.13.17-bin-ebdaf73`

build.sbt

```scala
Global / resolvers += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"

scalaVersion := "2.13.17-bin-ebdaf73"

scalacOptions += "-Wunused"
```

Main.scala

```scala
case class A(x: Int, y: Int)

object Main {
  for {
    a <- List.empty[A]
    A(x, y) = a
  } yield x + y
}
```

## Problem

```
[warn] false-positive-unused-warn/Main.scala:6:7: pattern var x in value $anonfun is never used
[warn]     A(x, y) = a
[warn]       ^
[warn] false-positive-unused-warn/Main.scala:6:10: pattern var y in value $anonfun is never used
[warn]     A(x, y) = a
[warn]          ^
[warn] two warnings found
```

`x` and `y` not unused.

### PR DESCRIPTION
**Pull request by som-snytt**
Associated patvars must be processed together: a patvar is unused if no associated symbol is used. Therefore a patvar can't be skipped if it is marked `@nowarn`. Instead, collect those symbols; then, a patvar is warnable if no associated symbol is marked nowarn.

Fixes scala/bug#13095

### CODE REVIEW

**Comment by som-snytt** [comment]
I didn't realize the failure is under "PR validation" and not (yet) "validate-main".

**Comment by som-snytt** [comment]
Just noticed that the nth unused warning is "unenthused".

**Comment by som-snytt** [comment]
Notice the shadowing!
```
      case n =>
        val leftSize = (size-1)/2
        val left = f(level+1, leftSize)
        val nn = xs.next()
        val right = f(level+1, size-1-leftSize)
        val (key, hash, value) = nn match {
          case nn: LLNode @uc => (nn.key, nn.hash, nn.value)
          case nn: RBNode @uc => (nn.key, nn.hash, nn.value)
        }
        val n = new RBNode(key, hash, value, red = false, left, right, null)
        if(left ne null) left.parent = n
        right.parent = n
        n
```
Considering these "casual" pattern variables, I wonder whether they are benign. This one is clearly pernicious!

**Comment by som-snytt** [comment]
I think it is time for `-Wunused:patvars` to join `-Xlint`. Today I couldn't understand why some warnings were enabled in the build: I'd forgot about `-Xlint`!

The only odd thing about patvars is that they are derived values.

But now I think that naming a value is as significant as naming a function parameter. It's a typo if it is not used in a computation.

**Comment by som-snytt** [comment]
github also recommends sjrd to review my PR on scala 2. sjrd is everywhere. Or possibly, github has identified sjrd as a nice guy willing to do code reviews.

**Comment by som-snytt** [comment]
The test failure was interesting because it showed that indiscriminate use of `NoWarnAttachment` to silence warnings in the old days is now wrong.

https://github.com/scala/scala/pull/6473

The two cases were: if a pattern var wound up in a refutability check, it would never warn; and binds for tupling would get an attachment to avoid warning, but that is no longer necessary since the position is transparent. (Only trees with opaque positions are considered for warning.)

Edit: the second case includes ordinary `for (_ <- g)`, and the bind has an opaque position. Therefore, keep the attachment for that case, and also filter out symbols with fresh names when warning.

File: src/library/scala/collection/Iterable.scala [hunk 1]
```diff
@@ -728,7 +728,7 @@ trait IterableOps[+A, +CC[_], +C] extends Any with IterableOnce[A] with Iterable
     */
   def concat[B >: A](suffix: IterableOnce[B]): CC[B] = iterableFactory.from(suffix match {
     case xs: Iterable[B] => new View.Concat(this, xs)
-    case xs => iterator ++ suffix.iterator
+    case _ => iterator ++ suffix.iterator
```
Comment (som-snytt) [inline src/library/scala/collection/Iterable.scala]: it is more clear to use the shadowing, aliasing name `suffix` on both lines.

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 2]
```diff
@@ -684,14 +705,19 @@ trait TypeDiagnostics extends splain.SplainDiagnostics {
       def varsWithoutSetters = defnTrees.iterator.map(_.symbol).filter(t => t.isVar && !isExisting(t.setter))
       varsWithoutSetters.filter(v => !isSuppressed(v) && !setVars(v) && !isUnusedTerm(v))
     }
-    def unusedParams = params.iterator.filter(isUnusedParam)
+    def unusedParams = params.iterator.filter(p => !ignore(p) && isUnusedParam(p))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala]: `!ignore(p)` is redundant?

File: test/files/pos/t13095.scala [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+case class A(x: Int, y: Int)
+
+object Main {
+  for {
+    a <- List.empty[A]
+    A(x, y) = a
+  } yield x + y
+
+  private val A(x, y) = A(42, 27)
```
Comment (lrytz) [inline test/files/pos/t13095.scala]:
```suggestion
  private val A(x, y) = A(42, 27) // nowarn because not patvars
```

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 4]
```diff
@@ -582,10 +582,12 @@ trait TypeDiagnostics extends splain.SplainDiagnostics {
               case bind @ Bind(`n`, _) => bind.updateAttachment(NoWarnAttachment)
               case _ =>
             }
+          def allow(n: Name): Unit = cases.foreach(k => allowVariableBindings(n, k.pat))
           def loop(selector: Tree): Unit =
             selector match {
-              case Ident(n) => cases.foreach(k => allowVariableBindings(n, k.pat))
+              case Ident(n) => allow(n)
               case Typed(expr, _) => loop(expr)
+              case Select(This(_), n) => allow(n)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:592]: Should it drill thru any selection, not just `this.x`?

File: test/files/neg/warn-unused-patvars.check [hunk 5]
```diff
@@ -1,5 +1,5 @@
-warn-unused-patvars.scala:11: warning: private val x in trait Boundings is never used
-  private val x = 42                      // warn, sanity check
+warn-unused-patvars.scala:10: warning: private val x in trait Boundings is never used
+  private val x = 42                      // warn, to ensure that warnings are enabled
```
Comment (lrytz) [inline test/files/neg/warn-unused-patvars.check:2]: 👍

**Review by lrytz — APPROVED** [review]
just some tiny remarks

File: test/files/pos/t13095.scala (hunk 3 above)
Comment (som-snytt) [reply test/files/pos/t13095.scala]: This is because they are the element names. Scala 3 has the same behavior in the port. In a case def, I say it's like importing the members. For the pat vardef, I'll say it's like exporting the members in Scala 3.

Comment (som-snytt) [reply test/files/pos/t13095.scala]: but I'll comment it.

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala (hunk 4 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:592]: The thinking here is that it's referred as a simple name, so the new name is shadowing.

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:724]: that was "better safe than sorry", but I'll take another look.

File: src/library/scala/Array.scala [hunk 6]
```diff
@@ -124,16 +124,16 @@ object Array {
     * @see `java.util.Arrays#copyOf`
     */
   def copyOf[A](original: Array[A], newLength: Int): Array[A] = ((original: @unchecked) match {
-    case x: Array[BoxedUnit]  => newUnitArray(newLength).asInstanceOf[Array[A]]
```
Comment (som-snytt) [inline src/library/scala/Array.scala:127]: unused, so naming it `original` invokes the shadowing rule. That is, the shadowing name does not introduce new information (except the narrower type). Then it's nicer to use the same name for all cases.

File: test/files/pos/t13095.scala (hunk 3 above)
Comment (lrytz) [reply test/files/pos/t13095.scala]:
```
➜ sandbox spr 11012 -Wunused
> scala repl -S 2.13.17-bin-f5e51db-SNAPSHOT -cp . --repository https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots -Wunused
Welcome to Scala 2.13.17-20250312-232340-f5e51db (OpenJDK 64-Bit Server VM, Java 21.0.1).
Type in expressions for evaluation. Or try :help.

scala> case class A(x: Int, y: Int)
class A

scala> class C { private val A(x, y) = A(42, 27) }
                               ^
       warning: private val x in class C is never used
                                  ^
       warning: private val y in class C is never used
class C
```

Comment (som-snytt) [reply test/files/pos/t13095.scala]: I'll check. I recall it reports as private val even if the option is patvars. It could say patvardef to confuse people.

Associated comment on dotty test
https://github.com/scala/scala3/blob/main/tests/warn/unused-privates.scala#L142

Comment (som-snytt) [reply test/files/pos/t13095.scala]: Edit: looks like I broke or unfixed it, or maybe just confused switching back from dotty... I'll align with current dotty, as my midnight comment seems correct: it's like the elements are imported or exported, from a lint perspective.

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala]: it was due to the check at L624 but was that an obsolete check at previous L592?

File: test/files/pos/t13095.scala (hunk 3 above)
Comment (som-snytt) [reply test/files/pos/t13095.scala]:
```
✗ scala-cli repl --server=false -S 3.7.0-RC1 -Wunused:all
Welcome to Scala 3.7.0-RC1 (23.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> case class C(c: Int, i: Int)
// defined case class C

scala> class D { private val C(x, y) = C(42, 27) }
2 warnings found
-- [E198] Unused Symbol Warning: -----------------------------------------------
1 |class D { private val C(x, y) = C(42, 27) }
  |                        ^
  |                        unused pattern variable
-- [E198] Unused Symbol Warning: -----------------------------------------------
1 |class D { private val C(x, y) = C(42, 27) }
  |                           ^
  |                           unused pattern variable
// defined class D

scala> class D { private val C(c, i) = C(42, 27) }
// defined class D
```

Comment (som-snytt) [reply test/files/pos/t13095.scala]: That was my confusion, but probably I intended it to work as stated. The "field" gets the `PatVarDefAttachment` but is not processed by the diagnostic (due to longstanding exclusion). Now it seems natural to throw both on the patvars pile. (The field has the original position.) It should just work?

I noticed the old tickets for crashes related to using positions: I wrote that error trees may result in missing pos, maybe for symbols such as getter/setters, where it was trying to "associate" or correlate and not warn twice. But same principle applies for patvars, which relies directly on positions of trees. When traversing, we can `getter.accessed` but we don't have its tree.

I just tried named constructor patterns in Scala 3, and that obviates the heuristics about canonical names, I believe. Or maybe you'd still want to not warn if all the elements are present and canonically named

Comment (som-snytt) [reply test/files/pos/t13095.scala]: Also see me reach the same conclusion on the previous ticket in January
https://github.com/scala/scala/pull/10980#discussion_r1915492229

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala]: L712

**Comment by som-snytt** [comment]
I'd been `partest --neg` all week but neglected to run it after adding "this is trivial".
```Scala
def unary_-()(implicit pos: Long) = this
```
Looks familiar
```
# starting 49 tests in presentation
................................X................
!!  1 - presentation/t12308                       [output differs]
% diff /home/runner/work/scala/scala/test/files/presentation/t12308.check /home/runner/work/scala/scala/test/files/presentation/t12308-presentation.log
@@ -46,5 +46,6 @@ askType at Foo.scala(4,37)
 [response] askTypeAt (4,37)
 1
 ================================================================================
+Problem(RangePosition(t12308/src/Foo.scala, 43, 43, 48),A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.,1,List())
 Problem(RangePosition(t12308/src/Foo.scala, 67, 67, 72),A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.,1,List())
 Problem(RangePosition(t12308/src/Foo.scala, 109, 109, 114),A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.,1,List())
```
My grandmother liked to joke, "The face looks familiar, but I can't remember my name."

**Comment by som-snytt** [comment]
Obviously, I consider myself very fortunate when Lukas has only tiny remarks, because that entails just two more weeks of work. A suggestion from him may incur a year of research.

I had the flags turned on in the build to test against this repo. I removed that clean-up commit and will submit it separately. (I may have broken something while editing.) (I did discover one actually unused class parameter, where the default was always used instead!) Not sure if I can turn them on here; it means local noise when building.

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 7]
```diff
@@ -528,41 +539,60 @@ trait TypeDiagnostics extends splain.SplainDiagnostics {
...
-                defnTrees += m
+                defnTrees += t
             case _ =>
-              defnTrees += m
+              defnTrees += t
           }
+        case Match(selector, cases) =>
+          // don't warn when a patvar redefines the selector ident: x match { case x: X => }
+          def allowVariableBindings(n: Name, pat: Tree): Unit =
+            pat.foreach {
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:583]: This allows an unused `n` to appear anywhere in the pattern, is that intended?

```scala
scala> def f(x: Any) = x match { case Some((List(_ :: x :: _), _)) => println() }
def f(x: Any): Unit

scala> def f(x: Any) = x match { case Some((List(_ :: y :: _), _)) => println() }
                                                      ^
       warning: pattern var y in method f is never used
def f(x: Any): Unit
```

**Review by lrytz — APPROVED** [review]
needs a rebase, lgtm!

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala (hunk 7 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:583]: It is conservative (tries not to annoy), to allow arbitrary extractors. `x match case FooBar(x)`. I guess a better example is `Some(x)`. It aligns with my new style of shadowing, `xs match case x :: xs`, where shadowing avoids having "two vars of the same type"; as opposed to `case x :: xs1` or `rest`.

I wish it didn't warn on
```
(i, j) match { case (i, j) => 42 }
```
on the same principle. Maybe I was too lazy to do tuples. Maybe I was waiting for named tuples.

**Comment by som-snytt** [comment]
Rebase was for Iterable code change abutting the scaladoc change for `$ccoll`.

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala (hunk 7 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:583]: > Maybe I was waiting for named tuples

🤫 https://github.com/scala/scala/compare/2.13.x...lrytz:scala:named-tuples?expand=1

File: test/files/neg/warn-unused-params.scala [hunk 8]
```diff
@@ -151,3 +151,9 @@ object END
 class Nested {
   @annotation.unused private def actuallyNotUsed(fresh: Int, stale: Int) = fresh
 }
+
+class Annie(value: String) extends annotation.StaticAnnotation // no warn for annotation
+
+class Selfie {
+  def f(i: Int, j: Int) = this // no warn this is trivial
```
Comment (som-snytt) [inline test/files/neg/warn-unused-params.scala:158]: I think this had a motivating example, but it looks wrong. `this` signals that the method is "merely" side-effecting, but why does that make it ok to ignore inputs? Maybe it means "this implementation does trivially nothing, but an override may attempt to do real work.

Comment (lrytz) [reply test/files/neg/warn-unused-params.scala:158]: > Maybe it means "this implementation does trivially nothing, but an override may attempt to do real work.

I agree. What's the goal of the unused param warning?
1. when a param is unused, maybe the user referenced some other symbol by mistake
2. when refactoring and a param becomes unused, maybe it can be removed

In both cases, a trivial body like `this` is unlikely to be an accident
