### PR TITLE
Map.from and Set.from are more sound [ci: last-only]

### LINKED ISSUE #10496: c.i.Map#toMap is unsound, warns against overriding with sound version
In retrospect, I should have checked `Map` when reporting #8346, which was the same problem but for `Set`.

```scala
Welcome to Scala 2.12.3 (OpenJDK 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.

scala> collection.immutable.TreeMap((1, 2)).toMap[Any, Any].get("hi")
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
  at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
  at scala.math.Ordering$Int$.compare(Ordering.scala:254)
  at scala.collection.immutable.RedBlackTree$.lookup(RedBlackTree.scala:40)
  at scala.collection.immutable.RedBlackTree$.get(RedBlackTree.scala:33)
  at scala.collection.immutable.TreeMap.get(TreeMap.scala:183)
  ... 39 elided
```

Deserves a fix similar to scala/scala#4703.

### LINKED ISSUE #12745: Map.from (and technically Set.from) are unsound
## Reproduction steps
I am 99% sure you know about it, but because `Set` makes an attempt to guard against it, and `Map` doesn't, I thought I'd mention it. I could not find any mention of it in the database though, and it's been a couple of days since I reported the last bug, so...

Scala version: 2.13.x, 3.x

```scala
	val iter :Iterable[(Any, String)] = List(1, 2, 3, 4, 5).map(i => i -> i.toString) to SortedMap.sortedMapFactory
	val set  :Map[Any, String] = Map.from(iter)
	set.contains("oops")
```

## Problem
Obvious:
```
Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
	at scala.math.Ordering$Int$.compare(Ordering.scala:376)
	at scala.collection.immutable.RedBlackTree$.lookup(RedBlackTree.scala:40)
	at scala.collection.immutable.RedBlackTree$.get(RedBlackTree.scala:33)
	at scala.collection.immutable.TreeMap.get(TreeMap.scala:128)
	at scala.collection.MapOps.contains(Map.scala:281)
	at scala.collection.MapOps.contains$(Map.scala:281)
	at scala.collection.AbstractMap.contains(Map.scala:405)
	at Playground$.delayedEndpoint$Playground$1(Playground.scala:16)
	at Playground$delayedInit$body.apply(Playground.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:42)
	at scala.Function0.apply$mcV$sp$(Function0.scala:42)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:98)
	at scala.App.$anonfun$main$1$adapted(App.scala:98)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at scala.App.main(App.scala:98)
	at scala.App.main$(App.scala:96)
	at Playground$.main(Playground.scala:13)
	at Playground.main(Playground.scala)
```

In `Set` you have:
```scala
  def from[E](it: collection.IterableOnce[E]): Set[E] =
    it match {
      // We want `SortedSet` (and subclasses, such as `BitSet`) to
      // rebuild themselves to avoid element type widening issues
      case _: SortedSet[E]         => (newBuilder[E] ++= it).result()
      case _ if it.knownSize == 0  => empty[E]
      case s: Set[E]               => s
      case _                       => (newBuilder[E] ++= it).result()
    }
```
But `Map` misses that:
```scala
  def from[K, V](it: collection.IterableOnce[(K, V)]): Map[K, V] =
    it match {
      case it: Iterable[_] if it.isEmpty => empty[K, V]
      case m: Map[K, V] => m
      case _ => (newBuilder[K, V] ++= it).result()
    }
```
Furthermore, even `Set` is unsound, because it guards itself only against implementations from the standard library; designing it as invariant and then treating it as covariant in the central method to the collection architecture seems a somewhat risky decision.
For example, I have (or rather, had, because it is not portable to Scala 3) a `NatSet` - naturally sorted `Set`. Thanks to a small trick, it is able to use the same API as `Set`, and I did not wish to make it a `SortedSet` because in the original use case I relied on the fact that ordering was natural (i.e., increasing). It will fail the same way `Map` does in the above example.

I am aware that performance is important, but the same effect can be achieved with positive filtering, rather than negative, i.e.
returning only `HashSet` and `HashMap` with widened types. Furthermore, it would be possible - though quite ugly - to wrap the argument to `from` in a proxy which catches `ClassCastException` and replaces the underlying set with a `HashSet`/`HashMap` if needed. Technically, `underlying` field doesn't even have to be `@volatile` (assuming all fields in all objects inside a `HashSet` are final in the byte code): we can leave that synchronization for after an exception is actually caught.

As a side note, warranting perhaps a separate bug report,
```scala
	val iter :Iterable[(Any, String)] = List(1, 2, 3, 4, 5).map(i => i -> i.toString) to SortedMap
```
(without an expclicit  call to `sortedMapFactory`) does not compile for me.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12745
Fixes scala/bug#10496

### CODE REVIEW

**Comment by SethTisue** [comment]
@scala/collections ...?

File: src/library/scala/collection/immutable/Map.scala [hunk 1]
```diff
@@ -206,11 +206,22 @@ object Map extends MapFactory[Map] {
...
-  def from[K, V](it: collection.IterableOnce[(K, V)]): Map[K, V] =
+  def from[K, V](it: IterableOnce[(K, V)]): Map[K, V] =
     it match {
       case it: Iterable[_] if it.isEmpty => empty[K, V]
-      case m: Map[K, V] => m
-      case _ => (newBuilder[K, V] ++= it).result()
+      // Since IterableOnce[(K, V)] launders the variance of K,
+      // identify only our implementations which can be soundly substituted.
+      // For example, the ordering used by sorted maps would fail on widened key type. (scala/bug#12745)
+      //case m: Map[K, V] => m
```
Comment (morgen-peschke) [inline src/library/scala/collection/immutable/Map.scala]: Is `//case m: Map[K, V] => m` an example or a missed deletion?

Comment (som-snytt) [reply src/library/scala/collection/immutable/Map.scala]: It was supposed to be documentary ("this doesn't work"). I will either make it look like a comment or delete it. Thanks.

I also meant to be more specific about what doesn't work for Set.

File: test/files/run/t12745.scala [hunk 2]
```diff
@@ -0,0 +1,35 @@
+
+// scalac: -Werror -Xlint
+import collection.immutable.{IntMap, SortedMap}
+
+import scala.tools.testkit.AssertUtil.assertFails
+
+object X {
+  //val iter: Iterable[(Any, String)] = List(1, 2, 3, 4, 5).map(i => i -> i.toString).to(SortedMap)
```
Comment (som-snytt) [inline test/files/run/t12745.scala]: This is the other question on the ticket, but I did not fill in the blanks.

**Comment by som-snytt** [comment]
Fixed/added comments, added test so there is a chance of detecting if the list of internal nested class names is wrong, and squashed.

File: src/library/scala/collection/immutable/Map.scala [hunk 3]
```diff
@@ -206,11 +206,23 @@ object Map extends MapFactory[Map] {
...
+      // For example, the ordering used by sorted maps would fail on widened key type. (scala/bug#12745)
+      // The following type test is not sufficient: case m: Map[K, V] => m
+      case m: HashMap[K, V]     => m
+      case m: ListMap[K, V]     => m
+      case m: Map1[K, V]        => m
+      case m: Map2[K, V]        => m
+      case m: Map3[K, V]        => m
+      case m: Map4[K, V]        => m
+      case m: WithDefault[K, V] => m
+      case m: SeqMap[K, V]      => m
```
Comment (lrytz) [inline src/library/scala/collection/immutable/Map.scala]: `WithDefault` and `SeqMap` could have external subclasses.

We could add `SeqMap1-4`, and also `VectorMap`?

**Review by lrytz — COMMENTED** [review]
LGTM otherwise!

**Comment by som-snytt** [comment]
As commented, `SortedMap.WithDefault` would be unsound, so just exclude `WithDefault` rather than cherry-pick.

Moved the `SeqMap`s into `SeqMap.from` where the tiny `SeqMap`s are accessible.

Improved the test so even I can read it.

File: src/library/scala/collection/immutable/Map.scala [hunk 4]
```diff
@@ -206,11 +206,22 @@ object Map extends MapFactory[Map] {
...
+      // identify only our implementations which can be soundly substituted.
+      // For example, the ordering used by sorted maps would fail on widened key type. (scala/bug#12745)
+      // The following type test is not sufficient: case m: Map[K, V] => m
+      case m: HashMap[K, V]    => m
+      case m: Map1[K, V]       => m
+      case m: Map2[K, V]       => m
+      case m: Map3[K, V]       => m
+      case m: Map4[K, V]       => m
+      //case m: WithDefault[K, V] => m    // cf SortedMap.WithDefault
+      case m: SeqMap[K, V]     => SeqMap.from(it)
```
Comment (sjrd) [inline src/library/scala/collection/immutable/Map.scala]: This is problematic for Scala.js. It will cause `SeqMap` to be reachable in basically all codebases, preventing it from being dead code eliminated.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: src/library/scala/collection/immutable/Map.scala (hunk 4 above)
Comment (som-snytt) [reply src/library/scala/collection/immutable/Map.scala]: Aha. I didn't like reaching into the subclass. That was really just for the private `SeqMap1` etc, which we can forego. Lukas made me do it! Do you mean the `SeqMap` companion, that is, I can type test for `VectorMap` here and that is OK?

Comment (sjrd) [reply src/library/scala/collection/immutable/Map.scala]: The type tests are fine. It's the instantiation via `SeqMap.from` that is problematic.

**Comment by SethTisue** [comment]
@som-snytt care to come back to this one in time for 2.13.12?

**Comment by som-snytt** [comment]
@SethTisue one more time. I think I pinged @sjrd with the ping icon, if he would be so kind as to review the unsquashed commit.

File: src/library/scala/collection/immutable/Set.scala [hunk 5]
```diff
@@ -94,14 +95,31 @@ object Set extends IterableFactory[Set] {
 
   def empty[A]: Set[A] = EmptySet.asInstanceOf[Set[A]]
 
+  // Miscellaneous inaccessible internal collections which can be returned directly in `from`.
+  // Fails silently but a unit test asserts that the classes were found.
+  @nowarn private val exclusions =
+    List(
+      "scala.collection.immutable.MapOps$ImmutableKeySet",
+      "scala.collection.immutable.HashMap$HashKeySet",
+    ).map(name => try Class.forName(name): AnyRef catch _ => null)
```
Comment (sjrd) [inline src/library/scala/collection/immutable/Set.scala]: Oh, I had not seen this before. `Class.forName` doesn't work on Scala.js (and probably not on Scala Native either). Is there any reason not to make those classes `private[immutable]` so that they would actually be accessible?

**Review by sjrd — CHANGES_REQUESTED** [review]

File: src/library/scala/collection/immutable/Map.scala (hunk 4 above)
Comment (sjrd) [reply src/library/scala/collection/immutable/Map.scala]: This is fine now, thanks :)

File: src/library/scala/collection/immutable/Set.scala (hunk 5 above)
Comment (som-snytt) [reply src/library/scala/collection/immutable/Set.scala]: I must have been reluctant to widen access. But as I'm in for a penny, I'll update it.

Comment (som-snytt) [reply src/library/scala/collection/immutable/Set.scala]: I removed the kludge, but I could not figure out how to express `instanceof` for the keyset of much-parameterized `MapOps`. That case was covered in a test: the test and the hypothetical LOC in `from` are commented out.

**Review by sjrd — APPROVED** [review]

**Comment by sjrd** [comment]
Thank you.

**Comment by som-snytt** [comment]
There was an additional test of the previous behavior in `SetTest`, besides `FactoriesTest`. I commented it out, adding comment text, and squashed with the penultimate commit that removed the kludgy exclusion.

File: src/library/scala/collection/immutable/Set.scala [hunk 6]
```diff
@@ -96,12 +96,21 @@ object Set extends IterableFactory[Set] {
...
+      // Since IterableOnce[E] launders the variance of E,
+      // identify only our implementations which can be soundly substituted.
+      // It's not sufficient to match `SortedSet[E]` to rebuild and `Set[E]` to retain.
+      case s: HashSet[E] => s
+      case s: ListSet[E] => s
+      case s: Set1[E]    => s
+      case s: Set2[E]    => s
+      case s: Set3[E]    => s
+      case s: Set4[E]    => s
+      //case s: MapOps[E @unchecked, _, _, _]#ImmutableKeySet => s
```
Comment (joroKr21) [inline src/library/scala/collection/immutable/Set.scala]: It's rocket science: https://github.com/scala/bug/issues/8039

But we can cheat because anyway it's eliminated by erasure. You can use:
```suggestion
      case s: MapOps[E, Any, Map, Map[E, Any]]#ImmutableKeySet @unchecked => s
```

Btw I found a crasher:
```scala
(MapOps[E, Any, Map, Map[E, Any]] @unchecked)#ImmutableKeySet
```

Comment (som-snytt) [reply src/library/scala/collection/immutable/Set.scala]: I will give you co-authored-by credit. I'm still trying to understand your earlier comment on a different PR.

I thought of the rocket science ticket, but I did not think of `Any`thing better.

Comment (joroKr21) [reply src/library/scala/collection/immutable/Set.scala]: This should fix the crash: https://github.com/scala/scala/pull/10498 🤞

**Comment by SethTisue** [comment]
@som-snytt seems ready for merge; you want to keep this sequence of commits...?

File: src/library/scala/collection/immutable/Set.scala (hunk 6 above)
Comment (som-snytt) [reply src/library/scala/collection/immutable/Set.scala]: I forgot to annotate the :rocket: scientist.

**Comment by som-snytt** [comment]
Appropriately squashed and rebased.

**Review by lrytz — APPROVED** [review]
Thank you, this is great!

**Comment by michelou** [comment]
@som-snytt @joroKr21 Great job !

**Comment by som-snytt** [comment]
also thanks @noresttherein for interesting tickets, without which there are no fixes.

I hope I spelled it right, even I parse it as `...darein`.
