### PR TITLE
RHS of var def is an expr

### LINKED ISSUE #11437: parser issue with `var` and `_`: default-value syntax and placeholder syntax collide
as reported at https://stackoverflow.com/questions/55182423/weird-behavior-of-anonymous-function-with-placeholder :

```
val adder: Int => Int = _ + 3 // Works fine
var adder: Int => Int = (_ + 3) // Works fine
var adder: Int => Int = _ + 3 // Error
```

The error is "error: ';' expected but identifier found.", pointing to the `+`.

@travisbrown writes on SO:

> The problem you're seeing seems to be that an underscore immediately following the = in a var definition is interpreted as this special default initial value, and the alternative use as a placeholder in a function is not considered. This behavior seems to me like it must be a bug

Dotty has the same issue.

### PR DESCRIPTION
**Pull request by som-snytt**
Previously too much was assumed from leading underscore.

Fixes scala/bug#11437

### CODE REVIEW

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala [hunk 1]
```diff
@@ -2658,24 +2658,23 @@ self =>
...
-            expr()
-          }
-        } else {
+        if (!tp.isEmpty && in.token != EQUALS) {
           newmods = newmods | Flags.DEFERRED
           EmptyTree
+        } else {
+          accept(EQUALS)
+          expr() match {
+            case x if !tp.isEmpty && newmods.isMutable && lhs.toList.forall(_.isInstanceOf[Ident]) && isWildcard(x) && placeholderParams.size == 1 =>
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/ast/parser/Parsers.scala]: The test that it is the only placeholder in play may be extraneous. Existing tests pass without it. Local vars can't exploit this syntax, so you don't see `_ + { var x = _ ; x = 42 ; x }`, for example; underscore doesn't escape braces anyway. If it were possible to see more than one placeholder, you'd want to strip only one placeholder and not reset `placeholderParams` to `Nil`.

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala [hunk 2]
```diff
@@ -2669,24 +2669,23 @@ self =>
...
-            expr()
-          }
-        } else {
+        if (!tp.isEmpty && in.token != EQUALS) {
           newmods = newmods | Flags.DEFERRED
           EmptyTree
+        } else {
+          accept(EQUALS)
+          expr() match {
+            case x if !tp.isEmpty && newmods.isMutable && lhs.toList.forall(_.isInstanceOf[Ident]) && isWildcard(x) =>
```
Comment (diesalbla) [inline src/compiler/scala/tools/nsc/ast/parser/Parsers.scala]:
```suggestion
            case x if !tp.isEmpty && newmods.isMutable && lhs.forall(_.isInstanceOf[Ident]) && isWildcard(x) =>
```
`lhs` already is a list.

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala [hunk 3]
```diff
@@ -2669,24 +2669,23 @@ self =>
...
-          } else {
-            expr()
-          }
-        } else {
+        if (!tp.isEmpty && in.token != EQUALS) {
           newmods = newmods | Flags.DEFERRED
           EmptyTree
+        } else {
+          accept(EQUALS)
+          expr() match {
```
Comment (diesalbla) [inline src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:2677]: Can I suggest the following: 
```Scala
val x = expr()
if ( !tp.isEmpty && newmods.isMutable && lhs.toList.forall(_.isInstanceOf[Ident]) && isWildcard(x) ) {
  /***/
} else x
```

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala [hunk 4]
```diff
@@ -2669,24 +2669,23 @@ self =>
...
-                syntaxError(tp.pos, "default initialization prohibited for literal-typed vars", skipIt = false)
-              case _ =>
-            }
-            newmods = newmods | Flags.DEFAULTINIT
-            EmptyTree
-          } else {
-            expr()
-          }
-        } else {
+        if (!tp.isEmpty && in.token != EQUALS) {
```
Comment (diesalbla) [inline src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:2672]: I don't think you need to alter the `if` condition or the order of the branches to fix the bug. I would suggest undoing this change, so as to clear out the essence of the bugfix, which is this line:
  
```Scala
               placeholderParams = placeholderParams.tail
```

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala (hunk 2 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/ast/parser/Parsers.scala]: Oh I didn't see your comment. I noticed the toList and didn't follow up. Not everything in the compiler API is a list or iterator; I suspect earlier code lacked forall et al. There ought to be -Xlint:monadic or somesuch to detect redundant calls.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/ast/parser/Parsers.scala]: I used "commit suggestion" for the first time...

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala (hunk 4 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:2672]: I found the logic easier to read this way.

That is, the special case is that if there's a type but no `=`, it's a declaration only. The inverted logic doesn't read well.

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala (hunk 3 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:2677]: This was also intended. I actually find match as "if-replacement" sometimes easier to read.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:2677]: Previously, I would
```
if (!p) default else { 
  some big logic
}
```
because it emphasizes the main part, but that style has lost its appeal because the conditional is pushed right.

But I don't like the dangling identity case here, either.

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala (hunk 4 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:2672]: I took your advice in forward-porting to doti; I also named the boolean conditions so the reader need not think about it.

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala [hunk 5]
```diff
@@ -2675,7 +2675,7 @@ self =>
         } else {
           accept(EQUALS)
           expr() match {
-            case x if !tp.isEmpty && newmods.isMutable && lhs.toList.forall(_.isInstanceOf[Ident]) && isWildcard(x) =>
+            case x if !tp.isEmpty && newmods.isMutable && lhs.forall(_.isInstanceOf[Ident]) && isWildcard(x) =>
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:2678]: I noticed this on the doti port, but hadn't noticed your fix-up back here. Thanks!
