### PR TITLE
fix scala/bug#12409: tasty - fix case class apply default params

### LINKED ISSUE #12409: default parameter values not recognised by tasty-reader
moved from https://github.com/lampepfl/dotty/issues/12704 by request of @bishabosha 

## Compiler version

3.0.0 and 2.13.6 in a multi project build

## Minimized code

```Scala
// in a scala 3 module
case class Scala3CaseClass(value: Int = 1)

// and in a scala 2 module which has -Ytasty-reader
  val importedCaseClass = Scala3CaseClass() // fails with "not enough arguments for method apply"
```

I have pushed a full example SBT project here: https://github.com/johnduffell/tasty-default-param-bug

## Output

```scala
[error] /Users/john_duffell/code/tasty-default-param-bug/scala2/src/main/scala/scala2/Main.scala:8:42: not enough arguments for method apply: (value: Int): scala3.Scala3CaseClass in object Scala3CaseClass
[error]   val importedCaseClass = Scala3CaseClass() // fails with "not enough arguments for method apply"

```

## Expectation
It should compile the same as the scala 2 version

## Workaround
Remove the default parameter, and add an explicit/overloaded apply method in a companion object.

## Other info
I have shared the problem on scala/scala gitter channel and another user has hit the same issue.  I couldn't find an existing report.  Let me know if you need more info.

### PR DESCRIPTION
**Pull request by bishabosha**
Here we special case insertion of default parameters for a synthetic `apply` method from scala 3, in this case, the constructor's default parameters should be used instead.

fixes scala/bug#12409

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala [hunk 1]
```diff
@@ -476,9 +476,20 @@ trait NamesDefaults { self: Analyzer =>
...
     val i = param.owner.paramss.flatten.indexWhere(p => p.name == param.name) + 1
     if (i > 0) {
-      val defGetterName = nme.defaultGetterName(param.owner.name, i)
-      if (param.owner.isConstructor) {
-        val mod = companionSymbolOf(param.owner.owner, context)
+      def isScala3SyntheticApply(meth: Symbol): Boolean = {
+        // According to rules in Scala 3, a synthetic method named `apply`
+        // should use `<init>` as the prefix of its default getters,
+        // i.e. reuse the constructor's default getters.
+        meth.isScala3Defined && meth.isSynthetic && meth.name == nme.apply
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala]: In addition to `meth.isSynthetic` you could add something like `meth.owner.isModule && companionSymbolOf(meth.owner).isCase`. But it's probably unlikely that there are other synthetic `apply` methods, so as you prefer.

Comment (bishabosha) [reply src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala]: I considered adding that, however the rule in Scala 3 is only a synthetic apply method - so perhaps a synthetic apply method forever more implies being in the companion object - I will add some more precision though

Comment (bishabosha) [reply src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala]: in Scala 3 this synthetic apply rule also works for the "universal apply methods" (which is backed up by a real `apply` method symbol) so it does not need to check for `case`

**Review by lrytz — APPROVED** [review]
