### PR TITLE
Fix false positive unused warning for private val used in annotation

### LINKED ISSUE #13130: New warning with 2.13.17: private val (...) is never used (false positive?)
## Reproduction steps

Scala version: 2.13.17

```scala
//> using scala 2.13.17
//> using dep io.swagger:swagger-annotations:1.6.16

import io.swagger.annotations._

class MyClass {
     // workaround:
     // @nowarn("cat=unused-privates")
     final private val xlsxMimeType = "mytype"

     @ApiOperation(value = "MyDesc", produces = xlsxMimeType)
     def getXlsxTemplate: Unit= ???
}
```

```bash 
scala-cli -Ywarn-unused:privates test.sc
Compiling project (Scala 2.13.17, JVM (21))
[warn] ./test.sc:7:24
[warn] private val xlsxMimeType in class MyClass is never used
[warn]      final private val xlsxMimeType = "mytype"
[warn]                        ^^^^^^^^^^^^
Compiled project (Scala 2.13.17, JVM (21))
```

## Problem

Variable is used so shouldn't be reported as unused.

Switching scala to previous version (2.13.16) gives no warning with same code : 
```bash
scala-cli -Ywarn-unused:privates test.sc
Compiling project (Scala 2.13.16, JVM (21))
Compiled project (Scala 2.13.16, JVM (21))
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#13130, a false positive unused warning for a `final private val` used as annotation argument.

Java or Constant annotations don't hold trees but wrappers of constant values for arguments to the annotation. For purposes of constant folding, there is no tree to receive an `OriginalTreeAttachment`, for tools to analyze.

`AnnotationInfo` has an original tree property to support reification, but that tree is the untyped named args.

This commit makes `LiteralAnnotArg` extend `Attachable` so that it can bear an "original" tree which is really the typed tree for the arg. The `unused` linter drills through the annot arg to its original, which allows it to resolve symbolic references to constant values.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala [hunk 1]
```diff
@@ -659,6 +671,7 @@ trait TypeDiagnostics extends splain.SplainDiagnostics {
             case b @ Bind(n, _) if n != nme.DEFAULT_CASE => addPatVar(b)
             case _ =>
           }
+        case NamedArg(_, rhs) => traverse(rhs)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:674]: This is not useful because rhs is untyped in annotation info original. Is it harmless?

**Review by lrytz — APPROVED** [review]
thank you!
