### PR TITLE
Make `Position.copyRange` public

### LINKED ISSUE #13083: Presentation compiler crash (bad position) on completing local import
Reproducer in https://github.com/scala/scala/compare/2.13.x...lrytz:scala:t13083?expand=1

```scala
object Autocompletewrapper {
  import java./*!*/
}
```

Reported by @kiendang at https://github.com/scala/scala/pull/10868#issuecomment-2613022940

### PR DESCRIPTION
**Pull request by lrytz**
Allow updating start and end at the same time, which prevents intermediate (potentially failing) validataion after changing only one value.

Fixes https://github.com/scala/bug/issues/13083

### CODE REVIEW

File: src/reflect/scala/reflect/internal/util/Position.scala [hunk 1]
```diff
@@ -133,14 +133,17 @@ private[util] trait InternalPositionImpl {
...
+  /* Copy a range position with a changed value. */
+  /* Note: the result is validated (start <= end), use `copyRange` to update both at the same time. */
   def withStart(start: Int): Position          = copyRange(start = start)
   def withPoint(point: Int): Position          = if (isRange) copyRange(point = point) else Position.offset(source, point)
   def withEnd(end: Int): Position              = copyRange(end = end)
   def withSource(source: SourceFile): Position = copyRange(source = source)
   def withShift(shift: Int): Position          = Position.range(source, start + shift, point + shift, end + shift)
 
+  def copyRange(start: Int = start, point: Int = point, end: Int = end, source: SourceFile = source) =
+    Position.range(source, start, point, end)
```
Comment (som-snytt) [inline src/reflect/scala/reflect/internal/util/Position.scala:145]: Starting with `source` would effectively encourage use of named args.

File: src/compiler/scala/tools/nsc/typechecker/ImportTracking.scala [hunk 2]
```diff
@@ -167,15 +167,15 @@ trait ImportTracking { self: Analyzer =>
...
                       emit(culled, delete(editPos))
                     }
                     else {
                       // info.tree.pos.end is one char after rbrace
                       val prev = selectors.lastIndexWhere(remaining.contains(_))
                       val comma = content.indexWhere(_ == ',', from = selectors(prev).namePos)
-                      val commaPos = infoPos.withStart(comma).withEnd(selectors(prev + 1).namePos)
-                      val editPos = infoPos.withStart(selector.namePos).withEnd(info.tree.pos.end - 1)
+                      val commaPos = infoPos.copyRange(start = comma, end = selectors(prev + 1).namePos)
+                      val editPos = infoPos.copyRange(start = selector.namePos, end = info.tree.pos.end - 1)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/ImportTracking.scala:178]: the port uses `Span` which felt heavyweight for some reason.

https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/transform/CheckUnused.scala#L701

but that API has trailing point: `def Span(start: Int, end: Int, point: Int): Span` with overloads

File: src/reflect/scala/reflect/internal/Trees.scala [hunk 3]
```diff
@@ -545,7 +545,7 @@ trait Trees extends api.Trees {
       if (start >= 0 && selectors.contains(sel)) {
         val hasRename = sel.rename != null && sel.renamePos >= 0 // !sel.isWildcard
         val end = if (hasRename) sel.renamePos + sel.rename.length else start + sel.name.length
-        pos0.withStart(start).withEnd(end) ^ start
+        pos0.copyRange(start, start, end)
```
Comment (som-snytt) [inline src/reflect/scala/reflect/internal/Trees.scala:548]: This would not benefit (much) from named args, but the alternative API would be a modest builder with a `result` that defers validation. Maybe another day.

**Review by som-snytt — APPROVED** [review]
Thanks I didn't see the comments on the old PR. (PR discussions should lock after merge IMHO.) You know positions are such a bane, and validation of point was another effort; dotty srcpos and span is a different bane. I like the idea of a builder, but that is only the difference between `copyRange` with named args and `withStart`. Another challenge is being aware of the point during coding or debug. Why isn't this a master's project. Edit: there is a dotty pr adding `span.pointMayBeIncorrect`, research is ongoing.

File: src/reflect/scala/reflect/internal/util/Position.scala (hunk 1 above)
Comment (lrytz) [reply src/reflect/scala/reflect/internal/util/Position.scala:145]: Right; I thought to allow positional args for the the common (?) case, but maybe it's better not to.

File: src/reflect/scala/reflect/internal/Trees.scala (hunk 3 above)
Comment (lrytz) [reply src/reflect/scala/reflect/internal/Trees.scala:548]: yeah.. but the API goes up to `reflect.api.Position`, so changing it is more painful.

File: src/reflect/scala/reflect/internal/util/Position.scala (hunk 1 above)
Comment (som-snytt) [reply src/reflect/scala/reflect/internal/util/Position.scala:145]: Although I love named args, I think this is fine, especially for a bug fix. I'd like a lint for APIs with multiple args of the same type. It's possible to use deprecatedName to discourage using a param name, but not conversely to require it.

**Comment by som-snytt** [comment]
@lrytz dotty uses this one weird trick!
```
  private def fromOffsets(start: Int, end: Int, pointDelta: Int) =
    //assert(start <= end || start == 1 && end == 0, s"$start..$end")
    new Span(
```

**Comment by lrytz** [comment]
image

Yeah. If a bad position leads to poor IDE / reporting experience it will eventually be reported and fixed. No need to blow up ASAP.
