### PR TITLE
More accurate outer checks in patterns

### LINKED ISSUE #11534: Spurious "cannot be checked at runtime" in latest 2.12.x (regression wrt. 2.12.8)
Trying to build the latest 0.6.x branch of Scala.js with the latest 2.12.x, I get a warning that I do not get with 2.12.8.

Repro:
```
$ git clone git@github.com:scala-js/scala-js.git
$ cd scala-js
$ git checkout fa02c74
$ sbt
> set resolvers in Global += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"
> ++2.12.9-bin-ae27fe9
> compiler/compile
[...]
[warn] compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:4421: The outer reference in this type test cannot be checked at run time.
[warn]         case JSUnaryOpMethodName(code) if argc == 0 =>
[warn]                                 ^
```
The line mentioned is here:
https://github.com/scala-js/scala-js/blob/fa02c745a64b869127b8cb68d594f5ca6c1b2d4e/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L4421

The warning was not reported by 2.12.8.

Note that the next case with `JSBinaryOpMethodName`, which is extremely similar, does not emit a warning.

A similar problem exists on our `master` branch (commit  https://github.com/scala-js/scala-js/commit/9f4f59b13051d9dfcc2fc34f6c37ecd9ac1ff69d), where this becomes an *error* because we have `-Xfatal-warnings`.

### PR DESCRIPTION
**Pull request by dwijnand**
Avoids eliding outer checks that matter (run/t11534b.scala) and
avoids emitting checks that don't (pos/t11534.scala) which avoids
compiler warnings when the tested class doesn't have an outer
field.

The latter stops the annoying unchecked warning that appeared since
a recent refactoring made TermName a final class.

Originally submitted to 2.12.x as #8261.

Fixes https://github.com/scala/bug/issues/11534

### CODE REVIEW

**Comment by SethTisue** [comment]
who do you have in mind as a reviewer?

**Comment by lrytz** [comment]
🙋‍♂️

**Comment by dwijnand** [comment]
No reviewer in mind, for a forward-port.

**Comment by SethTisue** [comment]
@lrytz this is the last open ticket or PR for 2.13.5, but it takes time to run the community build.
in the interest of not delaying the release past (hopefully) Tuesday, do you consider this basically safe for merge? if so, can we merge it, so we have a release candidate for the community build? then you could continue reviewing it, meanwhile, and see whether any followup PR (either pre-2.13.5 or post-2.13.5) is needed.

File: test/files/pos/t11534.scala [hunk 1]
```diff
@@ -0,0 +1,7 @@
+object Test1 {
+    val g: scala.tools.nsc.Global = ???
+    import g._
+    def test(sym: Symbol) = sym.name match {
+        case _: TermName  =>
```
Comment (lrytz) [inline test/files/pos/t11534.scala:6]: I get:

```
➜  sandbox git:(pr9504) qsc ../test/files/pos/t11534.scala
../test/files/pos/t11534.scala:5: warning: The outer reference in this type test cannot be checked at run time.
        case _: TermName  =>
              ^
1 warning
```

The test should have a `// scalac: -Werror`

**Comment by retronym** [comment]
I'm happy to leave this until post-2.13.5

**Comment by dwijnand** [comment]
Agreed, this doesn't look ready to me:

```
testedBinder.info <:< expectedTp: false
expectedTp: Test1.g.TermName
pre: Test1.g.type
testedBinder: value x1
testedBinder.info: sym.NameType
testedBinderClass: type NameType
testedBinderType: sym.NameType
testedBinderType.prefix: sym.type
testedPrefixIsExpectedTypePrefix: false
baseTypeFromFreshPrefix: <notype>
testedPrefixAndExpectedPrefixAreStaticallyIdentical: false
prefixAligns: false
```

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala [hunk 2]
```diff
@@ -383,20 +380,76 @@ trait MatchTreeMaking extends MatchCodeGen with Debugging {
...
+              //
+              // class P extends p1.B
+              // def test(b: p1.B) = b match { case _: p1.P }
+              // test(new p2.P)
+              def prefixAligns: Boolean = {
+                expectedTp match {
+                  case TypeRef(pre, _, _) if !pre.isStable => // e.g. _: Outer#Inner
+                    false
+                  case TypeRef(pre, sym, args) =>
+                    val testedBinderClass = testedBinder.info.upperBound.typeSymbol
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala:397]: This also works. Maybe slightly clearer than `.upperBound`.

```diff
diff --git a/src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala b/src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala
index c62510e5b2..894fcd834a 100644
--- a/src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala
+++ b/src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala
@@ -411,7 +411,7 @@ trait MatchTreeMaking extends MatchCodeGen with Debugging {
                   case TypeRef(pre, _, _) if !pre.isStable => // e.g. _: Outer#Inner
                     false
                   case TypeRef(pre, sym, args) =>
-                    val testedBinderClass = testedBinder.info.upperBound.typeSymbol
+                    val testedBinderClass = testedBinder.info.baseClasses.find(_.isClass).getOrElse(NoSymbol)
                     val testedBinderType = testedBinder.info.baseType(testedBinderClass)

                     val testedPrefixIsExpectedTypePrefix = pre =:= testedBinderType.prefix
```

**Review by lrytz — APPROVED** [review]
Tricky stuff...!

File: src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala [hunk 3]
```diff
@@ -361,20 +358,81 @@ trait MatchTreeMaking extends MatchCodeGen with Debugging {
...
+          // expectedTp               = p.P
+
+          expectedTp.dealias match {
+            case RefinedType(Nil, _) => orig
+            case rt@RefinedType(parent :: rest, scope) =>
+              // If the pattern type is refined type, emit outer tests for each component.
+              withOuterTest(withOuterTest(orig)(testedBinder, parent))(testedBinder, copyRefinedType(rt, rest, scope))
+            case expectedTp =>
+              val expectedClass = expectedTp.typeSymbol
+              assert(!expectedClass.isRefinementClass, orig)
```
Comment (dwijnand) [inline src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala:372]: This failed, and I think it's because it's failing on `xsbti.ScalaProvider with sbt.internal.inc.ScalaInstance.ScalaProvider2 @unchecked`.  See https://github.com/scala/community-build/pull/1400#issuecomment-824278131.  I'm going to try to fix this, but work-stealers welcome.
