### PR TITLE
Try any expression

### LINKED ISSUE #5887: Brace-less syntax for try/catch/finally gets confused by parentheses
The parser accepts expressions without braces after "try" but when an open paren occurs, it fails to parse it as part of the expressions and expects the whole expression to be enclosed in parens:

```scala
scala> try 1 + 1 finally ()
res0: Int = 2

scala> try (1) + 1 finally ()
<console>:1: error: ';' expected but identifier found.
       try (1) + 1 finally ()
               ^
```

### PR DESCRIPTION
**Pull request by som-snytt**
Previously, parsing `try` was special-cased for expressions
beginning with paren or brace. Perhaps that was to avoid odd
sights such as `try (1,2,3)` or `try { case _ => }`, but it
also broke `try { 1 } + 1 finally ()`.

This commit takes an arbitrary expression to `try`.

This is just the parser change for `try` from https://github.com/scala/scala/pull/4400

Fixes scala/bug#5887

### CODE REVIEW

**Comment by hrhino** [comment]
Try any patch twice.

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala [hunk 1]
```diff
@@ -1532,8 +1528,8 @@ self =>
               }
             }
           val finalizer = in.token match {
-            case FINALLY => in.nextToken(); expr()
-            case _ => EmptyTree
+            case FINALLY => in.nextToken() ; expr()
+            case _       => EmptyTree
```
Comment (hrhino) [inline src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:1532]: We don't need scalafmt, just somfmt.

File: test/files/neg/t5887.scala [hunk 2]
```diff
@@ -0,0 +1,11 @@
+
+trait TheOldCollegeTry {
+
+  // was: value isDefinedAt is not a member of Int
+  // now: required: PartialFunction[Throwable,?]
+  //def f = try ??? catch 22
```
Comment (hrhino) [inline test/files/neg/t5887.scala:6]: I think that's a good error message. Why not test it?

**Review by hrhino — APPROVED** [review]

File: test/files/neg/t5887.scala (hunk 2 above)
Comment (som-snytt) [reply test/files/neg/t5887.scala:6]: That will come back with the change to `catch`, which I'll attempt thricely.

File: src/compiler/scala/tools/nsc/ast/parser/Parsers.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:1532]: I'd changed it to if-else in the earlier patch, but now I always prefer match. This is how I typed it back in.

File: test/files/neg/t5887.scala (hunk 2 above)
Comment (som-snytt) [reply test/files/neg/t5887.scala:6]: Pardon, this is the third time, not so much charmed as cut off at the knees. The next try for catch will be a fourth.

**Comment by som-snytt** [comment]
@hrhino this is when I laughed again at your previous comment.
