### PR TITLE
Don't abort on glb/lub of TypeVar

### LINKED ISSUE #10514: trying to do lub/glb of typevar ?G[Foo[?F,?G,?A]]
```scala
type Id[X] = X
final case class Foo[F[_], G[_], A](value: F[(A, G[Foo[F, G, A]])])
val x = Foo(Some((1, Foo(Some((2, Foo[Option, Id, Int](None)))))))
```

Dies in 2.12.3 REPL with:
```scala
ReplGlobal.abort: trying to do lub/glb of typevar ?G[Foo[?F,?G,?A]]
error: 
  trying to do lub/glb of typevar ?G[Foo[?F,?G,?A]]
     while compiling: <pastie>
        during phase: globalPhase=typer, enteringPhase=namer
     library version: version 2.12.3
    compiler version: version 2.12.3
  reconstructed args: -feature -language:implicitConversions -language:higherKinds -language:existentials -Ypartial-unification -Ywarn-numeric-widen -unchecked -Xfuture -Yno-adapted-args -deprecation -Xplugin:/home/alex/.ivy2/cache/org.spire-math/kind-projector_2.12/jars/kind-projector_2.12-0.9.4.jar -classpath /home/alex/.ivy2/cache/org.typelevel/cats-core_2.12/jars/cats-core_2.12-1.0.0-MF.jar:/home/alex/.ivy2/cache/org.typelevel/cats-macros_2.12/jars/cats-macros_2.12-1.0.0-MF.jar:/home/alex/.ivy2/cache/org.typelevel/machinist_2.12/jars/machinist_2.12-0.6.1.jar:/home/alex/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.3.jar:/home/alex/.ivy2/cache/org.typelevel/cats-kernel_2.12/jars/cats-kernel_2.12-1.0.0-MF.jar:/home/alex/.ivy2/cache/eu.timepit/refined_2.12/jars/refined_2.12-0.8.2.jar:/home/alex/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.12.3.jar:/home/alex/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.6.jar:/home/alex/.ivy2/cache/org.typelevel/macro-compat_2.12/jars/macro-compat_2.12-1.1.1.jar:/home/alex/.ivy2/cache/com.chuusai/shapeless_2.12/bundles/shapeless_2.12-2.3.2.jar:/home/alex/.ivy2/cache/co.fs2/fs2-core_2.12/jars/fs2-core_2.12-0.9.7.jar:/home/alex/.ivy2/cache/co.fs2/fs2-io_2.12/jars/fs2-io_2.12-0.9.7.jar:/home/alex/.ivy2/cache/com.spinoco/fs2-http_2.12/jars/fs2-http_2.12-0.1.7.jar:/home/alex/.ivy2/cache/org.scodec/scodec-bits_2.12/bundles/scodec-bits_2.12-1.1.4.jar:/home/alex/.ivy2/cache/org.scodec/scodec-core_2.12/bundles/scodec-core_2.12-1.10.3.jar:/home/alex/.ivy2/cache/com.spinoco/protocol-http_2.12/jars/protocol-http_2.12-0.1.8.jar:/home/alex/.ivy2/cache/com.spinoco/protocol-common_2.12/jars/protocol-common_2.12-0.1.8.jar:/home/alex/.ivy2/cache/com.spinoco/protocol-websocket_2.12/jars/protocol-websocket_2.12-0.1.8.jar:/home/alex/.ivy2/cache/co.fs2/fs2-cats_2.12/jars/fs2-cats_2.12-0.4.0.jar:/home/alex/.ivy2/cache/org.typelevel/cats-effect_2.12/jars/cats-effect_2.12-0.4.jar:/home/alex/.ivy2/cache/io.circe/circe-core_2.12/jars/circe-core_2.12-0.8.0.jar:/home/alex/.ivy2/cache/io.circe/circe-numbers_2.12/jars/circe-numbers_2.12-0.8.0.jar:/home/alex/.ivy2/cache/io.circe/circe-generic_2.12/jars/circe-generic_2.12-0.8.0.jar:/home/alex/.ivy2/cache/io.circe/circe-parser_2.12/jars/circe-parser_2.12-0.8.0.jar:/home/alex/.ivy2/cache/io.circe/circe-jawn_2.12/jars/circe-jawn_2.12-0.8.0.jar:/home/alex/.ivy2/cache/org.spire-math/jawn-parser_2.12/jars/jawn-parser_2.12-0.10.4.jar:/home/alex/.m2/repository/com/alexknvl/pathy_2.12/0.2.1/pathy_2.12-0.2.1.jar:/home/alex/.m2/repository/com/alexknvl/leibniz_2.12/0.10.0/leibniz_2.12-0.10.0.jar:/home/alex/.ivy2/cache/org.tpolecat/atto-core_2.12/jars/atto-core_2.12-0.6.0.jar:/home/alex/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.12.3.jar:/home/alex/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.3.jar:/home/alex/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.6.jar:/home/alex/.ivy2/cache/jline/jline/jars/jline-2.14.4.jar -Ywarn-dead-code -bootclasspath /usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes:/home/alex/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.3.jar -Yrepl-sync

  last tree to typer: Ident(<argument>)
       tree position: line 13 of <pastie>
            tree tpe: Some[(Int, Foo[Option,Id,Int])]
              symbol: <none>
   symbol definition: <none> (a NoSymbol)
      symbol package: <none>
       symbol owners:
           call site: object $iw in package $line4

<Cannot read source file>
scala.reflect.internal.FatalError: 
  trying to do lub/glb of typevar ?G[Foo[?F,?G,?A]]
     while compiling: <pastie>
        during phase: globalPhase=typer, enteringPhase=namer
     library version: version 2.12.3
    compiler version: version 2.12.3
  reconstructed args: -feature -language:implicitConversions -language:higherKinds -language:existentials -Ypartial-unification -Ywarn-numeric-widen -unchecked -Xfuture -Yno-adapted-args -deprecation -Xplugin:/home/alex/.ivy2/cache/org.spire-math/kind-projector_2.12/jars/kind-projector_2.12-0.9.4.jar -classpath /home/alex/.ivy2/cache/org.typelevel/cats-core_2.12/jars/cats-core_2.12-1.0.0-MF.jar:/home/alex/.ivy2/cache/org.typelevel/cats-macros_2.12/jars/cats-macros_2.12-1.0.0-MF.jar:/home/alex/.ivy2/cache/org.typelevel/machinist_2.12/jars/machinist_2.12-0.6.1.jar:/home/alex/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.3.jar:/home/alex/.ivy2/cache/org.typelevel/cats-kernel_2.12/jars/cats-kernel_2.12-1.0.0-MF.jar:/home/alex/.ivy2/cache/eu.timepit/refined_2.12/jars/refined_2.12-0.8.2.jar:/home/alex/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.12.3.jar:/home/alex/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.6.jar:/home/alex/.ivy2/cache/org.typelevel/macro-compat_2.12/jars/macro-compat_2.12-1.1.1.jar:/home/alex/.ivy2/cache/com.chuusai/shapeless_2.12/bundles/shapeless_2.12-2.3.2.jar:/home/alex/.ivy2/cache/co.fs2/fs2-core_2.12/jars/fs2-core_2.12-0.9.7.jar:/home/alex/.ivy2/cache/co.fs2/fs2-io_2.12/jars/fs2-io_2.12-0.9.7.jar:/home/alex/.ivy2/cache/com.spinoco/fs2-http_2.12/jars/fs2-http_2.12-0.1.7.jar:/home/alex/.ivy2/cache/org.scodec/scodec-bits_2.12/bundles/scodec-bits_2.12-1.1.4.jar:/home/alex/.ivy2/cache/org.scodec/scodec-core_2.12/bundles/scodec-core_2.12-1.10.3.jar:/home/alex/.ivy2/cache/com.spinoco/protocol-http_2.12/jars/protocol-http_2.12-0.1.8.jar:/home/alex/.ivy2/cache/com.spinoco/protocol-common_2.12/jars/protocol-common_2.12-0.1.8.jar:/home/alex/.ivy2/cache/com.spinoco/protocol-websocket_2.12/jars/protocol-websocket_2.12-0.1.8.jar:/home/alex/.ivy2/cache/co.fs2/fs2-cats_2.12/jars/fs2-cats_2.12-0.4.0.jar:/home/alex/.ivy2/cache/org.typelevel/cats-effect_2.12/jars/cats-effect_2.12-0.4.jar:/home/alex/.ivy2/cache/io.circe/circe-core_2.12/jars/circe-core_2.12-0.8.0.jar:/home/alex/.ivy2/cache/io.circe/circe-numbers_2.12/jars/circe-numbers_2.12-0.8.0.jar:/home/alex/.ivy2/cache/io.circe/circe-generic_2.12/jars/circe-generic_2.12-0.8.0.jar:/home/alex/.ivy2/cache/io.circe/circe-parser_2.12/jars/circe-parser_2.12-0.8.0.jar:/home/alex/.ivy2/cache/io.circe/circe-jawn_2.12/jars/circe-jawn_2.12-0.8.0.jar:/home/alex/.ivy2/cache/org.spire-math/jawn-parser_2.12/jars/jawn-parser_2.12-0.10.4.jar:/home/alex/.m2/repository/com/alexknvl/pathy_2.12/0.2.1/pathy_2.12-0.2.1.jar:/home/alex/.m2/repository/com/alexknvl/leibniz_2.12/0.10.0/leibniz_2.12-0.10.0.jar:/home/alex/.ivy2/cache/org.tpolecat/atto-core_2.12/jars/atto-core_2.12-0.6.0.jar:/home/alex/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.12.3.jar:/home/alex/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.3.jar:/home/alex/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.6.jar:/home/alex/.ivy2/cache/jline/jline/jars/jline-2.14.4.jar -Ywarn-dead-code -bootclasspath /usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes:/home/alex/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.3.jar -Yrepl-sync

  last tree to typer: Ident(<argument>)
       tree position: line 13 of <pastie>
            tree tpe: Some[(Int, Foo[Option,Id,Int])]
              symbol: <none>
   symbol definition: <none> (a NoSymbol)
      symbol package: <none>
       symbol owners: 
           call site: object $iw in package $line4

<Cannot read source file>
	at scala.reflect.internal.Reporting.abort(Reporting.scala:61)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:57)
	at scala.tools.nsc.interpreter.IMain$$anon$1.scala$tools$nsc$interpreter$ReplGlobal$$super$abort(IMain.scala:240)
	at scala.tools.nsc.interpreter.ReplGlobal.abort(ReplGlobal.scala:23)
	at scala.tools.nsc.interpreter.ReplGlobal.abort$(ReplGlobal.scala:21)
	at scala.tools.nsc.interpreter.IMain$$anon$1.abort(IMain.scala:240)
	at scala.reflect.internal.Types.stripType$1(Types.scala:4500)
	at scala.reflect.internal.Types.$anonfun$stripExistentialsAndTypeVars$4(Types.scala:4503)
	at scala.reflect.internal.Types.stripExistentialsAndTypeVars(Types.scala:4503)
	at scala.reflect.internal.Types.stripExistentialsAndTypeVars$(Types.scala:4477)
	at scala.reflect.internal.SymbolTable.stripExistentialsAndTypeVars(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.GlbLubs.lub1$1(GlbLubs.scala:309)
	at scala.reflect.internal.tpe.GlbLubs.lub0$1(GlbLubs.scala:303)
	at scala.reflect.internal.tpe.GlbLubs.lub(GlbLubs.scala:400)
	at scala.reflect.internal.tpe.GlbLubs.lub$(GlbLubs.scala:281)
	at scala.reflect.internal.SymbolTable.lub(SymbolTable.scala:16)
	at scala.reflect.internal.Types.$anonfun$mergePrefixAndArgs$7(Types.scala:4560)
	at scala.reflect.internal.Types.mergePrefixAndArgs(Types.scala:4548)
	at scala.reflect.internal.Types.mergePrefixAndArgs$(Types.scala:4514)
	at scala.reflect.internal.SymbolTable.mergePrefixAndArgs(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.GlbLubs.loop$1(GlbLubs.scala:136)
	at scala.reflect.internal.tpe.GlbLubs.lubList(GlbLubs.scala:167)
	at scala.reflect.internal.tpe.GlbLubs.lubList$(GlbLubs.scala:99)
	at scala.reflect.internal.SymbolTable.lubList(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.GlbLubs.lub1$1(GlbLubs.scala:310)
	at scala.reflect.internal.tpe.GlbLubs.lub0$1(GlbLubs.scala:303)
	at scala.reflect.internal.tpe.GlbLubs.lub(GlbLubs.scala:400)
	at scala.reflect.internal.tpe.GlbLubs.lub$(GlbLubs.scala:281)
	at scala.reflect.internal.SymbolTable.lub(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeConstraints.solveOne$1(TypeConstraints.scala:249)
	at scala.reflect.internal.tpe.TypeConstraints.$anonfun$solve$9(TypeConstraints.scala:260)
	at scala.reflect.internal.tpe.TypeConstraints.solve(TypeConstraints.scala:260)
	at scala.reflect.internal.tpe.TypeConstraints.solve$(TypeConstraints.scala:192)
	at scala.reflect.internal.SymbolTable.solve(SymbolTable.scala:16)
	at scala.tools.nsc.typechecker.Infer.solvedTypes(Infer.scala:145)
	at scala.tools.nsc.typechecker.Infer.solvedTypes$(Infer.scala:137)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.solvedTypes(ReplGlobal.scala:26)
	at scala.tools.nsc.typechecker.Infer$Inferencer.methTypeArgs(Infer.scala:553)
	at scala.tools.nsc.typechecker.Infer$Inferencer.inferMethodInstance(Infer.scala:984)
	at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3640)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3645)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4718)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4746)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5536)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5553)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:660)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:628)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:496)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:947)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:975)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1032)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1418)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:81)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.inferImplicit(ReplGlobal.scala:26)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitView(Implicits.scala:43)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitView$(Implicits.scala:42)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.inferImplicitView(ReplGlobal.scala:26)
	at scala.tools.nsc.typechecker.Typers$Typer.inferView(Typers.scala:233)
	at scala.tools.nsc.typechecker.Typers$Typer.viewExists(Typers.scala:209)
	at scala.tools.nsc.typechecker.Typers$Typer$$anon$2.$anonfun$isCoercible$1(Typers.scala:124)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
	at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:56)
	at scala.tools.nsc.typechecker.Typers$Typer$$anon$2.isCoercible(Typers.scala:124)
	at scala.tools.nsc.typechecker.Infer$Inferencer.isCompatible(Infer.scala:308)
	at scala.tools.nsc.typechecker.Infer$Inferencer.$anonfun$methTypeArgs$3(Infer.scala:548)
	at scala.tools.nsc.typechecker.Infer$Inferencer.methTypeArgs(Infer.scala:542)
	at scala.tools.nsc.typechecker.Infer$Inferencer.inferMethodInstance(Infer.scala:984)
	at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3640)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3645)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4718)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4746)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5536)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5553)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5589)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5619)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5567)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3236)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:478)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3626)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$34(Typers.scala:3634)
	at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3634)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3645)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4718)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4746)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5536)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5553)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5589)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5619)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5567)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3236)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:478)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3626)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$34(Typers.scala:3634)
	at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3634)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3645)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4718)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4746)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5536)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5553)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5589)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5619)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5567)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3236)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:478)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3626)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$34(Typers.scala:3634)
	at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3634)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3645)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4718)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4746)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5536)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5553)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5589)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5619)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5567)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5661)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5749)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1068)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1617)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1786)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1751)
	at scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:904)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1948)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1946)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1941)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1531)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1679)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5195)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5589)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5619)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5567)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5650)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3220)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3220)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1983)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1854)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5503)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5552)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5589)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5619)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5567)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5650)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3220)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3220)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1983)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1854)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5503)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5552)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5589)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5619)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5567)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5650)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3220)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3220)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1983)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1854)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5503)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5552)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5589)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5619)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5567)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5650)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3220)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3220)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5202)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5505)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5552)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5589)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5619)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5567)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5646)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1431)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1416)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1412)
	at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:431)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:800)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:758)
	at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:947)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:942)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:589)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:561)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$pasteCommand$11(ILoop.scala:800)
	at scala.tools.nsc.interpreter.IMain.withLabel(IMain.scala:112)
	at scala.tools.nsc.interpreter.ILoop.interpretCode$1(ILoop.scala:800)
	at scala.tools.nsc.interpreter.ILoop.pasteCommand(ILoop.scala:806)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$standardCommands$9(ILoop.scala:190)
	at scala.tools.nsc.interpreter.LoopCommands$LineCmd.apply(LoopCommands.scala:144)
	at scala.tools.nsc.interpreter.LoopCommands.colonCommand(LoopCommands.scala:113)
	at scala.tools.nsc.interpreter.LoopCommands.colonCommand$(LoopCommands.scala:111)
	at scala.tools.nsc.interpreter.ILoop.colonCommand(ILoop.scala:44)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:736)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:456)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:477)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$1(ILoop.scala:1070)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:949)
	at scala.tools.nsc.InterpreterLoop.main(InterpreterLoop.scala:16)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:82)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:748)
```

Dies in 2.11.11 (on ScalaFiddle)
```
  trying to do lub/glb of typevar ?G[ScalaFiddle.Foo[?F,?G,?A]]
     while compiling: ScalaFiddle.scala
        during phase: typer
     library version: version 2.11.11
    compiler version: version 2.11.11
  reconstructed args: 
```

### PR DESCRIPTION
**Pull request by joroKr21**
Instead throw a `NoCommonType` exception and catch it when solving
type variables to avoid a compiler crash when type inference
cannot satisfy all constraints.

Fixes scala/bug#10514 by turning the crash into an error message.

scala/bug#10519 and scala/bug#5559 also produce error messages,
but are not fixed IMO, because it looks like they should compile.

### CODE REVIEW

**Review by adriaanm — DISMISSED** [review]

File: src/reflect/scala/reflect/internal/tpe/TypeConstraints.scala [hunk 1]
```diff
@@ -255,12 +255,16 @@ private[internal] trait TypeConstraints {
...
         tvar.constr.inst = NoType // necessary because hibounds/lobounds may contain tvar
 
-        val newInst =
+        val newInst = try {
           if (up || tvar.constr.hiBounds.exists(isSingleType)) { // If we have a singleton upper bound then we should use it.
             if (depth.isAnyDepth) glb(tvar.constr.hiBounds) else glb(tvar.constr.hiBounds, depth)
           } else {
             if (depth.isAnyDepth) lub(tvar.constr.loBounds) else lub(tvar.constr.loBounds, depth)
           }
+        } catch { case unsolvable: NoCommonType =>
```
Comment (adriaanm) [inline src/reflect/scala/reflect/internal/tpe/TypeConstraints.scala]: Hmm, I'm concerned about the performance impact. Can/should we handle this by returning an error result? /cc @retronym

**Review by adriaanm — COMMENTED** [review]
Let's check performance.

**Comment by adriaanm** [comment]
Clearly the abort is wrong, but how about just ignoring this case? I'd be more comfortable turning the abort into a debuglog. Let's not introduce exception handling here.

Btw, smaller test case:
```
class C[T](x: T)
class Foo[F[_], G[_]](value: F[C[G[Foo[F, G]]]])

class Test {
  type Id[A] = A
  new Foo(Some(new C(new Foo[Option, Id](None))))
}
```

**Comment by adriaanm** [comment]
I hope you won't mind if I push -f to your branch to implement my suggestion. (Original sha: 5326029)

**Comment by SethTisue** [comment]
thank you Georgi!

**Comment by joroKr21** [comment]
@adriaanm Thank you for amending my old PRs (or should I say sins). I haven't had much time lately. For some reason I thought that if we actually try to glb/lub of TypeVar the Universe would implode.

**Comment by adriaanm** [comment]
No worries, sorry for taking so long. It's intense stuff :-)

We actually still won't lub/glb the TypeVars -- they're now stripped by `stripExistentialsAndTypeVars` if there's no instance to replace them with.
