### PR TITLE
`Symbol#toString` is now `Symbol(foo)` instead of the deprecated single-quote form `'foo`

### LINKED ISSUE #11943: Symbol.toString uses deprecated syntax
## reproduction steps

```scala
scala> 'hi
       ^
       warning: symbol literal is deprecated; use Symbol("hi") instead
res0: Symbol = 'hi

scala> Symbol("hi")
res1: Symbol = 'hi
```

## problem

Input and output do not gibe.

## expectation

`Symbol.toString` should be consistent with recommended constructor expression.

### PR DESCRIPTION
**Pull request by changvvb**
Before:

```scala
scala 2.13.2> Symbol("foo")
val res0: Symbol = 'foo
```

After:

```scala
scala 2.13.3> Symbol("foo")
val res0: Symbol = Symbol(foo)
```

Fixes https://github.com/scala/bug/issues/11943

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]

**Comment by dwijnand** [comment]
Thanks!

File: test/junit/scala/lang/stringinterpol/StringContextTest.scala [hunk 1]
```diff
@@ -173,7 +173,7 @@ class StringContextTest {
       f"${s}%S"     -> "SCALA",
       f"${5}"       -> "5",
       f"${i}"       -> "42",
-      f"${'foo}"    -> "'foo",
+      f"${'foo}"    -> "Symbol(foo)",
```
Comment (som-snytt) [inline test/junit/scala/lang/stringinterpol/StringContextTest.scala:176]: Just to note that this will conflict with https://github.com/scala/scala/pull/8890/files#diff-bd815597e6f8f90ee8858d87776722ddR180 

I don't know if the merge is easier if you also amend the expression not to use symbol syntax?

**Review by som-snytt — CHANGES_REQUESTED** [review]
Thanks, definitely requires squashing.

File: test/junit/scala/lang/stringinterpol/StringContextTest.scala (hunk 1 above)
Comment (changvvb) [reply test/junit/scala/lang/stringinterpol/StringContextTest.scala:176]: It's better not to use symbol syntax, but it will still conflict with #8890 on the same line.

Comment (som-snytt) [reply test/junit/scala/lang/stringinterpol/StringContextTest.scala:176]: I guess you're right. No problem, though!

**Review by som-snytt — APPROVED** [review]

**Comment by SethTisue** [comment]
a few projects in the community build were (inappropriately) relying on the old behavior:

* https://github.com/pureconfig/pureconfig/pull/756
* https://github.com/scalatest/scalatest/pull/1808

**Comment by som-snytt** [comment]
Thanks, I was waiting for that shoe.

**Comment by som-snytt** [comment]
> a few projects in the community build were (inappropriately) relying on the old behavior:

Surprisingly, this change diverges from the spec, which the community were appropriately relying on. See 1.3.7! which is obsolete on a couple of points.
