### PR TITLE
Delay package object decls entering to the package object phase

### LINKED ISSUE #4695: package object misbehaves in the presence of classfiles
Multiple issues here.  (And that's before I get to the question of whether one's companion object can be a package object -- although I assume the answer is "no", I find nothing unambiguous in the spec.)

```
package foo

class Bar { }
package object Bar { }
```

1) Non-idempotence of source compilation
2) Classes not even on the classpath fail the compilation

```
// first time it compiles, second time it doesn't.
% scalac3 p.scala 
% scalac3 p.scala 
p.scala:1: error: package foo contains object and package with same name: Bar
one of them needs to be removed from classpath
package foo
        ^
one error found

// it will not compile as long as those classfiles are visible from the
// current directory, even though "." is explicitly unreferenced.
% scalac3 -d /tmp -cp /asldkfjlasdfj p.scala 
p.scala:1: error: package foo contains object and package with same name: Bar
one of them needs to be removed from classpath
package foo
        ^
one error found

// delete them, it compiles.
% rm -rf foo
% scalac3 -d /tmp -cp /asldkfjlasdfj p.scala 
%
```

Edit: Another, possibly more serious, related issue follows.  Example from mark harrah.
```
// demo/A.scala containing:
package demo
trait A

// demo/package.scala
package object demo extends demo.A

#!/usr/bin/env bash
#

rm -rf ./build
mkdir build
scalac -d build -cp build demo/A.scala demo/package.scala
rm -f build/demo/A.class
scalac -d build -cp build demo/A.scala demo/package.scala
```
It fails even when given all the source files it has just compiled:
```
error: error while loading demo, class file needed by package is missing.
reference type A of package demo refers to nonexisting symbol.
one error found
```

### LINKED ISSUE #12092: Unstable compiler output depending on order of package.scala and client code that uses type aliased defined therein
Here's a variant in userland, where the package object does not participate in root imports.

```scala
  @Test def testPackageObjectUserLand(): Unit = {
    def code = List[SourceFile](
      source("package.scala", "package userland; object `package` { type Throwy = java.lang.Throwable }"),
      source("th.scala", "package userland; class th[T <: Throwy](cause: T = null)")
    )
    test(code :: Nil, permuter = _.reverse :: Nil)
  }
```

When `th.scala` appears before `package.scala`, naming the `PackageDef` in `th.scala` with:

```scala
    def enterPackage(tree: PackageDef) {
      val sym = createPackageSymbol(tree.pos, tree.pid)
      tree.symbol = sym
      newNamer(context.make(tree, sym.moduleClass, sym.info.decls)) enterSyms tree.stats
    }
```

... forces the info of the the package class symbol, including entering the members of the `package.class`. Again, we end up with two symbols representing the same entity which results in a different (albeit semantically equivalent) pickle. I'm pretty sure there is also a correctness bug here in that references to members of `package.class` that no longer in `package.scala` might not result in "no such symbol" errors.

_Originally posted by @retronym in https://github.com/scala/bug/issues/12086#issuecomment-661459560_

### PR DESCRIPTION
**Pull request by dwijnand**
Existing code in the compiler avoids loading package.class when a source file contains a new definition for the package object. The source definition would be used instead in the `packageObjects` phase. 

This PR takes it a step further and defers forcing the info of _all_ package.class until the `packageObjects` phase. This avoids spurious `symbol not found` errors when in a particular incremental compilation scenarion, when: a) super-class of the package object (defined within the same package) is provided as a source file and B) the package object is _not_ supplied as a source file.

This change is intended to obviate the workaround in Zinc that supplies `package.scala` to the compiler more often than should be strictly necessary.

As a bonus, this addresses an issue with compiler determinism:

Fixes scala/bug#12092

Relates to #3389

Fixes scala/bug#5954 (properly this time, workaround removed and tests still pass)
Fixes scala/bug#4695

### CODE REVIEW

**Comment by retronym** [comment]
Another sketch, as discussed: https://github.com/scala/scala/pull/9664

File: src/compiler/scala/tools/nsc/Global.scala [hunk 1]
```diff
@@ -80,7 +80,15 @@ class Global(var currentSettings: Settings, reporter0: Reporter)
 
   import definitions.findNamedMember
   def findMemberFromRoot(fullName: Name): Symbol = rootMirror.findMemberFromRoot(fullName)
-
+  override def deferredOpenPackageModule(container: Symbol, dest: Symbol): Unit = {
+    // Some compiler runs (e.g. Toolbox and the PC) just initialise Global and then discard the Run
+    // such that the scala package object decls never get entered into the scala package
+    if ((curRun eq null) || !isGlobalInitialized || isPastPackageObjects) {
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/Global.scala]: I'm trying to pinpoint what breaks without the `isGlobalInitialized` condition. Ideally we can structure the initialization `Definitions` to work without the `package object scala`'s members being entered into the package.

Comment (retronym) [reply src/compiler/scala/tools/nsc/Global.scala]: I'm guessing this is to fix the `type Serializable not found` errors in `ClassPrintTest`, etc.

The root cause for the problem is the toolbox compiler has an ad-hoc usage of the compiler that doesnt just run through the phases, it just calls `Typer#typed` after doing a little setup work. We should override `deferredOpenPackageModule` in `ReflectGlobal` to be eager. 

This should be test driven by a test that checks that that involves user-defined package objects. Such a test should:

  - Compile a package object into a temp dir
  - Construct a classloader with temp dir and initialize a toolbox compiler with that classloader
  - Typecheck a snippet that references a member of the package object.

We should also add a similar test for runtime reflection
  - Compile a package object to a temp dir
  - Construct a runtime mirror based on that classloader: `val mirror = scala.reflect.runtime.universe.runtimeMirror(loader)`
  - Assert that we can reflect on a member of the package.

This code path will exercise `LazyPackageType`, which calls `openPackageModule` directly as things stand.

Comment (dwijnand) [reply src/compiler/scala/tools/nsc/Global.scala]: The tests that had failed with your initial patch and passed with my fixup were:

```
partest test/files/presentation/hyperlinks-macro test/files/presentation/t8934;
junit/Test/testOnly scala.lang.annotations.RunTest scala.lang.primitives.NaNTest scala.reflect.ClassOfTest scala.reflect.ClassTagTest scala.reflect.internal.QuasiTreesPrintTest;
scalacheck/Test/testOnly scala.reflect.quasiquotes.ErrorProps scala.reflect.quasiquotes.TypecheckedProps
```

So I wasn't seeing `ClassPrintTest` specifically, but yes, it was with the toolbox not running through to the package objects phase, meaning that those key modules weren't ever getting their decls copied over because a fresh run got a fresh "deferredOpen" buffer.  I wanted to find a way not to have to make things eager, because that would make it inconsistent when namer does and doesn't copy, but ended up going for that with `(curRun eq null) || !isGlobalInitialized`.  Btw, I took those as a single condition, copied from `isPast`.

File: test/files/run/package-object-toolbox.scala [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+    val toolbox = mirror.mkToolBox()
+    val result1 = toolbox.eval(toolbox.parse("pkg.foo"))
+    assertEquals(1, result1)
+
+    val obj  = toolbox.eval(toolbox.parse("pkg.`package`"))
+    val pkg  = mirror.staticPackage("pkg")
+    val sym  = pkg.info.decl(ru.TermName("foo")).asMethod
+    val meth = mirror.reflect(obj).reflectMethod(sym)
+    val res2 = meth.apply()
+    assertEquals(1, res2)
```
Comment (dwijnand) [inline test/files/run/package-object-toolbox.scala:29]: @retronym I tried this, but then _not_ overriding in ReflectGlobal doesn't fail the test, which isn't a good sign...

**Review by retronym — APPROVED** [review]

File: test/files/run/package-object-toolbox.scala (hunk 2 above)
Comment (retronym) [reply test/files/run/package-object-toolbox.scala:29]: I was worried about `Toolbox.typecheck` which has a fairly bespoke way of using the compiler. But adding that variation to this test works fine, with or without the override in `ReflectGlobal`. Without the override the condition `isPast(currentRun.namerPhase)` holds.

That comes done to:

```scala
          phase = run.typerPhase // need to set a phase to something <= typerPhase, otherwise implicits in typedSelect will be disabled
          globalPhase = run.typerPhase // amazing... looks like phase and globalPhase are different things, so we need to set them separately

```

There isn't an API in the toolbox (currently) that allows you to define a top-level package, everything gets wrapped in a synthetic package. So I don't think there is a way to trigger the original bug in toolbox anyway. The test here is good to make sure that package objects are working in toolbox in any case.

Should we remove the override given that it isn't strictly necessary? I guess so.

**Comment by som-snytt** [comment]
Possibly this broke `-Yimports:scala.util.chaining` where `chaining` is an object in a package object. Maybe there is API to force loading the package object, and maybe someone is awake on the other side of the earth to tell me what that is.
