### PR TITLE
Refrain from adding ctor to class from ct.sym

### LINKED ISSUE #12565: -release 8 causes java.time.Instant to have a fictitious constructor
## Reproduction steps

```
scalaVersion := "2.13.8"

scalacOptions ++= List("-release", "8")
```

```scala
Welcome to Scala 2.13.8 (OpenJDK 64-Bit Server VM, Java 11.0.14).
Type in expressions for evaluation. Or try :help.

scala> new java.time.Instant
java.lang.NoSuchMethodError: java.time.Instant: method 'void <init>()' not found
  ... 35 elided
```

## Problem

`java.time.Instant` doesn't have a default constructor but the compiler seems to think that it does.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12565

Tweak test for java annotation flag when parsing class file.

Previously, spurious constructors were added. Noticed when parsing `.sig` entry from `ct.sym`, which exposes only public API.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala [hunk 1]
```diff
@@ -549,7 +549,8 @@ abstract class ClassfileParser(reader: ReusableInstance[ReusableDataReader]) {
       val needsConstructor = (
            !sawPrivateConstructor
         && !(instanceScope containsName nme.CONSTRUCTOR)
-        && ((sflags & INTERFACE) == 0 || (sflags | JAVA_ANNOTATION) != 0)
+        && ((sflags & INTERFACE) == 0 || (sflags & JAVA_ANNOTATION) != 0)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala]: this certainly looks correct, so far every java interface had an `init` method.

```
scala> typeOf[Runnable].members
val res0: $r.intp.global.Scope =
Scope{
  def <init>(): Runnable;
```

It was added in https://github.com/scala/scala/pull/6869/files#diff-48440af466bc60ce77eb8afa75128abf7863f2bcba7a3153cf3adad0271df0b1

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala [hunk 2]
```diff
@@ -549,7 +549,8 @@ abstract class ClassfileParser(reader: ReusableInstance[ReusableDataReader]) {
...
+        && !file.name.endsWith(".sig")
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala]: When do we actually need to add the synthetic constructor, besides (apparently) Java annotations? Could we change the entire thing to `val needsConstructor = sflags & JAVA_ANNOTATION) != 0`?

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala]: Thanks, I was waiting for a smart person to explain it to me.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala]: My guess is: classfiles and sigfiles differ in that private members are omitted in the latter, so `sawPrivateConstructor` doesn't fire.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala]: I meant explain what the constructor construction was for. But I see now, yes, it's just for annotations which IIRC are automatically `new Thing`. I'll experiment with the simplication. And understand why the bad flag test did not matter. Or I guess it would just always supply the ctor.

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala (hunk 1 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala]: sorry I missed this comment. I'll read the linked PR.

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala [hunk 3]
```diff
@@ -548,8 +548,8 @@ abstract class ClassfileParser(reader: ReusableInstance[ReusableDataReader]) {
       0 until u2() foreach (_ => parseMethod())
       val needsConstructor = (
            !sawPrivateConstructor
-        && !(instanceScope containsName nme.CONSTRUCTOR)
-        && ((sflags & INTERFACE) == 0 || (sflags | JAVA_ANNOTATION) != 0)
+        && !instanceScope.containsName(nme.CONSTRUCTOR)
+        && ((sflags & (INTERFACE|JAVA_ANNOTATION)) == (INTERFACE|JAVA_ANNOTATION))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala:552]: `val needsConstructor = sflags & JAVA_ANNOTATION) != 0` and removing everything else (`sawPrivateConstructor` / `instanceScope`) doesn't work?

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala:552]: I was being conservative out of an abundance of fear.

**Review by dwijnand — APPROVED** [review]

File: src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala (hunk 3 above)
Comment (som-snytt) [reply src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala:552]: I have forgotten the correct answer here.

File: test/files/neg/t12565.scala [hunk 4]
```diff
@@ -0,0 +1,9 @@
+// scalac: -Werror --release 8
+// javaVersion: 9+
```
Comment (som-snytt) [inline test/files/neg/t12565.scala:2]: @lrytz on scala 3 I contributed `test: -jdk 9+` syntax. IIRC. Not sure if you renewed the patent application.
