### PR TITLE
Never inline varargs after named arg rewrite

### LINKED ISSUE #11964: Unused temporary for lonely vararg in named args rewrite
## reproduction steps

```scala
object t7 {
  def f(a: Int, b: String*) = "first"
}
object Test extends App {
  println(t7.f(1))
  println(t7.f(a = 19))
  println(t7.f(a = 28, b = "sl19"))
  println(t7.f(b = "sl19", a = 28))
}
```

## problem

```scala
$ scalac -Xlint unused-fresh.scala
unused-fresh.scala:8: warning: local val x$1 in value <local Test> is never used
  println(t7.f(b = "sl19", a = 28))
                   ^
one warning found
```
where
```
      scala.Predef.println({
        <artifact> val x$1: Seq = scala.collection.immutable.Seq.apply(scala.runtime.ScalaRunTime.wrapRefArray(Array[String]{"sl19"}.$asInstanceOf[Array[Object]]())).$asInstanceOf[Seq]();
        <artifact> val x$2: Int(28) = 28;
        t7.f(28, scala.runtime.ScalaRunTime.wrapRefArray(Array[String]{"sl19"}.$asInstanceOf[Array[Object]]()))
      });
```

## expectation

Less cruft.

### PR DESCRIPTION
**Pull request by som-snytt**
If a temp val has been created to hold varargs,
always use it. A single constant arg would induce
inlining and creation of a fresh varargs, ignoring
the unused temp val.

Fixes scala/bug#11964

### CODE REVIEW

**Review by retronym — APPROVED** [review]
Thanks for this!

**Comment by som-snytt** [comment]
The nice part is that I get to fix some tests, too.

**Comment by retronym** [comment]
Didn't see you comment until just now, I just pushed a fix.

**Comment by som-snytt** [comment]
I was making dinner, what did you do? Edit: I never know what retronym is up to, but I assume it's on 2.12.x.

**Comment by som-snytt** [comment]
I wrote `formals.nonEmpty` but I know you have an aversion for these wasteful enrichments.

Edit: TIL `lastOption`

Note that it's difficult to ascertain if this is a problem or a progression:
```
-names-defaults.scala:385: warning: local val x$112 in value <local Test> is never used
-  println(t3697.b(b = 1, a = 2, c = 3))
-                                    ^
```

File: src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala [hunk 1]
```diff
@@ -380,7 +378,12 @@ trait NamesDefaults { self: Analyzer =>
                   }
               })
               // cannot call blockTyper.typedBlock here, because the method expr might be partially applied only
-              val res = blockTyper.doTypedApply(tree, expr, refArgs, mode, pt)
+              val res =
+                blockTyper.doTypedApply(tree, expr, refArgs, mode, pt) match {
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala]: Another way to skin the cat would be to avoid const-folding the `refArg` for the by-name param. The `refArg` has type `Seq[String("sl19")] @scala.reflect.internal.annotations.uncheckedBounds`, which folds.

Changing the code to `f(b = "sl19": String, a = 28)` turns it into `Seq[String] @scala.reflect.internal.annotations.uncheckedBounds`, which doesn't fold.

https://github.com/scala/scala/compare/2.13.x...lrytz:pr9662-alt?expand=1

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala]: Thanks, that expresses retronym's workaround directly.

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala]: Speaking of by-name params, I realized that Scala 2 doesn't have by-name repeated params yet. I opened a ticket about that when I was learning me some scala.
