### PR TITLE
ArrayBuilder of Unit needs addAll forwarded

### LINKED ISSUE #13068: ArrayBuilder.ofUnit.addAll throws java.lang.UnsupportedOperationException
## Reproduction steps

```scala
val ab = new scala.collection.mutable.ArrayBuilder.ofUnit
val aou = Array[Unit]((), (), ())
ab.addAll(aou)
```
Please consider [this relevant Scastie](https://scastie.scala-lang.org/0wALRcgfQ7eSgVL96BwaxA)

## Problem
This should add three `Unit` values to the `ArrayBuilder`, but instead it throws `UnsupportedOperationException`.  

A straight forward fix involves overriding the `addAll` method in the `ofUnit` class so that it doesn't default to the one it inherits from the `ArrayBuilder[T]` abstract class:
```scala
def addAll(xs: Array[_ <: T]): this.type = doAddAll(xs, 0, xs.length)
```
The `doAddAll` method in `ArrayBuilder` accesses the `ofUnit.elems` method which, by design, always throws `UnsupportedOperationException` because the `ofUnit` builder never actually populates array data until the invocation of its `.result()` method.

[ArrayBuilder.scala#L497](https://github.com/scala/scala/blob/301d2db99fe72b96888a7eca1fc2a1f51ebabdc0/src/library/scala/collection/mutable/ArrayBuilder.scala#L497)

Please see [prior discussion on the Scala discord](https://discord.com/channels/632150470000902164/632150470000902166/1317015802679005265).

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#13068

Follow-up to previous changes for resizing.

One `addAll` used to forward to the other. That changed just to avoid redundant range checks.

### CODE REVIEW

**Comment by SethTisue** [comment]
@scala/collections

**Comment by som-snytt** [comment]
Added to current milestone not for pragmatic reasons, as the alternative method works, but just because.

Quick review: did you add a test for the other method?

Edit:
```
    // expect an exception when trying to grow larger than maximum size by addAll(array)
    assertThrows[Exception](ab.addAll(arr))
```
There was already a test that it throws...!

**Comment by He-Pin** [comment]
does I'm the problem live in 2.12.x too？

**Comment by som-snytt** [comment]
@He-Pin No, this is 2.13.x with new collections problems.

https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/mutable/ArrayBuilder.scala

**Comment by som-snytt** [comment]
I need the meme with the fellow with the nice beard:

I don't always throw exceptions, but when I do, I make it a `RuntimeException`.

**Comment by som-snytt** [comment]
I absolutely did run `library/mimaReportBinaryIssues` and it did not make a peep.

Therefore, the task as it currently exists is not useful to me locally. If there is some hoop to jump through, it is probably also not useful to me.

File: test/junit/scala/collection/mutable/ArrayBuilderTest.scala [hunk 1]
```diff
@@ -39,4 +39,11 @@ class ArrayBuilderTest {
     (1 to 100).foreach(_ => builder.addAll(Array.empty[String]))
     assertEquals(0, builder.knownSize)
   }
+
+  @Test def `t13068 addAll of array`: Unit = {
+    val ab: ArrayBuilder[Unit] = ArrayBuilder.make[Unit]
+    val arr = Array[Unit]((), (), (), (), (), (), (), (), (), (), (), ())
+    ab.addAll(arr)
+    assertEquals(arr.length, ab.result().length)
```
Comment (He-Pin) [inline test/junit/scala/collection/mutable/ArrayBuilderTest.scala:48]: Should we assert the elements  are all ()

Comment (som-snytt) [reply test/junit/scala/collection/mutable/ArrayBuilderTest.scala:48]: That sounds extreme, but  `result` doesn't use `Array.fill`. That is an "optimization", but also therefore a potential point of failure. This class "must" be rarely used, so arguably any optimization is not worth it. Look at the time suck due to "optimizing" the range checks. Probably the test should verify the `result`.

**Comment by som-snytt** [comment]
I restored the forwarding `addAll` for reasons of binary compat. A few int ops don't matter when you're copying arrays. Also, if you're computing arrays to fold into an array builder, you don't care about performance.

File: test/junit/scala/collection/mutable/ArrayBuilderTest.scala (hunk 1 above)
Comment (He-Pin) [reply test/junit/scala/collection/mutable/ArrayBuilderTest.scala:48]: Thanks for the input, but verify result seems  ✅️

Comment (som-snytt) [reply test/junit/scala/collection/mutable/ArrayBuilderTest.scala:48]: but then I would have to decide whether to nowarn
```
[warn] .../ArrayBuilderTest.scala:48:37: dubious usage of method == with unit value
[warn]     assertTrue(ab.result().forall(_ == ()))
[warn]                                     ^
```

File: src/library/scala/collection/mutable/ArrayBuilder.scala [hunk 2]
```diff
@@ -46,7 +46,7 @@ sealed abstract class ArrayBuilder[T]
   protected[this] def resize(size: Int): Unit
 
   /** Add all elements of an array. */
-  def addAll(xs: Array[_ <: T]): this.type = doAddAll(xs, 0, xs.length)
+  def addAll(xs: Array[_ <: T]): this.type = addAll(xs, 0, xs.length)
```
Comment (He-Pin) [inline src/library/scala/collection/mutable/ArrayBuilder.scala:49]: We can just forwarding when xs is not empty

Comment (som-snytt) [reply src/library/scala/collection/mutable/ArrayBuilder.scala:49]: That is a micro-optimization too far.

File: test/junit/scala/collection/mutable/ArrayBuilderTest.scala (hunk 1 above)
Comment (He-Pin) [reply test/junit/scala/collection/mutable/ArrayBuilderTest.scala:48]: > but then I would have to decide whether to nowarn
> ```
> [warn] .../ArrayBuilderTest.scala:48:37: dubious usage of method == with unit value
> [warn]     assertTrue(ab.result().forall(_ == ()))
> [warn]                                     ^
> ```

Maybe eq？

Comment (som-snytt) [reply test/junit/scala/collection/mutable/ArrayBuilderTest.scala:48]: oh good suggestion. I did add a commit earlier, but didn't push it yet, because I feel bad for Jenkins.

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by som-snytt** [comment]
It was green until I tempted fate with another Travis build:
```
No output has been received in the last 10m0s
```
which looks like "ten months".

**Comment by SethTisue** [comment]
I re-triggered Travis-CI

**Comment by SethTisue** [comment]
Thank you @som-snytt and @He-Pin !

**Comment by He-Pin** [comment]
I have a question, why it's travis-ci not a github action ?

**Comment by SethTisue** [comment]
@He-Pin Good question! It is indeed a bit absurd for us to have three different CI systems (GitHub Actions, Travis-CI, Jenkins).

It's mostly inertia. There is a bunch of long and confusing history at https://github.com/scala/scala-dev/issues/751

> We can't easily get rid of Travis-CI without redoing release publishing, which is complex and fragile

(Though yes, we could get rid of it for PR validation without redoing release publishing. That hasn't happened only because of inertia.)
