### PR TITLE
IterableOnce#copyToArray uses helper for count [ci: last-only]

### LINKED ISSUE #12948: Inconsistent `copyToArray` semantics between `IterableOnceOps` and `Vector` (and some other collections).
## Reproduction steps

Scala version:  2.13.12
I made another attempt to bring semantics of my collections exactly in line with the standard library and failed miserably.
I hinted at it  #12795, but it gets worse.
```scala
	println(Vector(1).copyToArray(new Array[Int](1), Int.MinValue, 1))
	println(List(1).copyToArray(new Array[Int](1), Int.MinValue, 1))
```

## Problem
```
0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -2147483648 out of bounds for length 20268
	at scala.runtime.ScalaRunTime$.array_update(ScalaRunTime.scala:75)
	at scala.collection.IterableOnceOps.copyToArray(IterableOnce.scala:926)
	at scala.collection.IterableOnceOps.copyToArray$(IterableOnce.scala:921)
	at scala.collection.AbstractIterable.copyToArray(Iterable.scala:933)
	at Playground$.delayedEndpoint$Playground$1(Playground.scala:20)
	at Playground$delayedInit$body.apply(Playground.scala:8)
```
Coincidentally,
```scala
	println(List(1).copyToArray(new Array[Int](1), -1, -1))
	println(List(1).copyToArray(new Array[Int](1), Int.MinValue, -1))
```
yields the same result:
```
0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -2147483648 out of bounds for length 1
	at scala.runtime.ScalaRunTime$.array_update(ScalaRunTime.scala:75)
	at scala.collection.IterableOnceOps.copyToArray(IterableOnce.scala:926)
	at scala.collection.IterableOnceOps.copyToArray$(IterableOnce.scala:921)
	at scala.collection.AbstractIterable.copyToArray(Iterable.scala:933)
	at Playground$.delayedEndpoint$Playground$1(Playground.scala:22)
	at Playground$delayedInit$body.apply(Playground.scala:8)
```

I know one probably has to be autistic to be bothered by it enough to fix it, given limited resources, but is there an official policy of what *should* happen in both of these scenarios that I can adopt?
``
`<soapbox>`These are exactly consequences of the philosophy of deriving API semantics from the simplest possible implementation, rather than the simplest possible specification, as defended in one of my past bugs`</soapbox>`.
I don't like that negative start index is accepted if the amount to copy is zero, but at least collections using `IterableOnce.elemsToCopyToArray` are somewhat consistent in it. I champion 'always reject negative index' cause in large part because it guards the rest of the code from an underflow.

### PR DESCRIPTION
**Pull request by som-snytt**
Don't throw (index out of bounds) when there is no runtime work (destination is zero length or count <= 0).

Audited implementations but did not boost the test coverage much.

Fixes scala/bug#12948

### CODE REVIEW

File: src/library/scala/collection/IterableOnce.scala [hunk 1]
```diff
@@ -1035,7 +1037,11 @@ trait IterableOnceOps[+A, +CC[_], +C] extends Any { this: IterableOnce[A] =>
   def copyToArray[B >: A](xs: Array[B], start: Int, len: Int): Int = {
```
Comment (He-Pin) [inline src/library/scala/collection/IterableOnce.scala]: Better update the scala doc for the new behavior.

Comment (som-snytt) [reply src/library/scala/collection/IterableOnce.scala]: I think we'll need a global documentation of out-of-bounds behaviors, as requested in the linked tickets.

This change satisfies the documented behavior, but we need a phrase like "all methods in this package throw on null input", as we read in Javadoc.

**Review by lrytz — APPROVED** [review]
Thank you!
