### PR TITLE
Plug many variance holes (in higher-kinded types, refined types and private inner classes)

### LINKED ISSUE #9725: Variance checking inconsistency when using type members in refinement types in argument position
```scala
trait Foo1[-X] { def bar[Y <: X](y: Y) = y } // typechecks

// A variant of Foo1 encoding the type parameter Y using a dependent method type.
// error: contravariant type X occurs in covariant position in type  <: X of type Y
trait Foo2[-X] { def bar(x: { type Y <: X })(y: x.Y) = y } 

trait Foo3[+X] { def bar[Y >: X](y: Y) = y } // typechecks

// A variant of Foo3 using a dependent method type.
// error: covariant type X occurs in contravariant position in type  >: X of type Y
trait Foo4[+X] { def bar(x: { type Y >: X })(y: x.Y) = y }
```

The errors appear even if we don't use dependent method types.
```scala
// error: covariant type X occurs in contravariant position in type  >: X of type Y
trait Foo9[+X] { def bar(x: { type Y >: X }): Any }
```

### LINKED ISSUE #9911: compiler crash in variance checks with erroneous use of someVal.super.someMethod
```scala
// This should say:
// Error: super may not be used on value source
class ScalacBug {

  class SomeClass {

    type U

    // Changing T or U stops the problem
    def getSomething[T]: U = ???
  }

  trait Base {

    // Changing this to a def like it should be stops the problem
    val source: SomeClass = ???
  }

  class Bug extends Base {

    override val source = {
      // Not calling the function stops the problem
      super.source.getSomething
      ???
    }
  }

}
```

### LINKED ISSUE #11789: Cannot widen a HKT parameter with covariant type parameters
Example:

```scala
case class Holder[F[+_, +_]](v: F[Int, Int]) {
  def asWiden[F2[+x, +y] >: F[x, y]]: F2[Int, Int] = v
}

object example extends App {
  println(Holder[Right](Right(5)).asWiden[Either])
}
```

Produces error:

```
Error:(4, 16) covariant type x occurs in contravariant position in type [+x, +y] >: F[x,y] of type F2
  def asWiden[F2[+x, +y] >: F[x, y]]: F2[Int, Int] = v
              ^
```

Expected it to succeed, as the expression does not appear unsound!
Writing it as `F2[+x, +y] >: F[_, _]` passes the variance checker, but the expression using the function fails to typecheck:

```scala
Error:(7, 99) type arguments [Either] do not conform to method asWiden's type parameter bounds [F2[+x, +y] >: Right[_, _]]
def res0 = Holder[Right](Right(5)).asWiden[Either]                                                              ^
```

Scala version 2.13.1

### PR DESCRIPTION
**Pull request by joroKr21**
Most examples are fixed in dotty.

The variance checks root in `RefChecks` for `TypeTree`s is modified
to check only the variance of `PolyType`s (this includes type lambdas).
Checking the definition of the `PolyType`s' owners is not correct,
because `relativeVariance` doesn't work for types in arbitrary position.

To check the variance of `PolyType`s we introduce a new type map:
`PolyTypeVarianceMap`. This is similar to the way variance is checked
for type lambdas in dotty, where type lambdas are encoded explicitly.

We also add explicit tracking for lower bounds of `PolyType`s.
For a type parameter of a `PolyType`, the variance should not be
flipped (or equivalently, flipped twice) in the lower bound.
This applies to both `ValidateVarianceMap` and `PolyTypeVarianceMap`.
It fixes variance bugs for types appering in the bounds of HKTs.

Finally, we don't skip local definitions entirely (this is unsound),
but instead cutoff `relativeVariance` at local boundaries.

Fixes scala/bug#11789, fixes scala/bug#9911, fixes scala/bug#9725

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/RefChecks.scala [hunk 1]
```diff
@@ -1774,13 +1774,9 @@ abstract class RefChecks extends Transform {
...
         }
         result1 match {
-          case ClassDef(_, _, _, _)
-             | TypeDef(_, _, _, _)
-             | ModuleDef(_, _, _) =>
+          case ClassDef(_, _, _, _) | TypeDef(_, _, _, _) | ModuleDef(_, _, _) =>
             if (result1.symbol.isLocalToBlock || result1.symbol.isTopLevel)
               varianceValidator.traverse(result1)
-          case tt @ TypeTree() if tt.original != null =>
-            varianceValidator.traverse(tt.original) // See scala/bug#7872
```
Comment (joroKr21) [inline src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:1781]: CC @Blaisorblade the wrong root for variance was here, but what I did in this PR is also wrong (having `varianceValidator` traverse bodies). But since refinements and "type lambdas" can hide anywhere I'm at a loss what to do.

File: test/files/neg/variance-holes.scala [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+  trait Refined1[+A] {
+    def foo: { type T >: A }
+  }
+
+  trait Refined2[+A] {
+    def foo(x: { type T <: A }): Unit
+  }
+
+  class RefinedLower[+A, x <: { type T >: A }]
+  private[this] class PrivateThis[+A](var x: A)
```
Comment (joroKr21) [inline test/files/neg/variance-holes.scala:21]: This compiles in dotty but is unsound: lampepfl/dotty#7567

File: test/files/neg/variance-holes.scala [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+
+  trait Refined1[+A] {
+    def foo: { type T >: A }
+  }
+
+  trait Refined2[+A] {
+    def foo(x: { type T <: A }): Unit
+  }
+
+  class RefinedLower[+A, x <: { type T >: A }]
```
Comment (joroKr21) [inline test/files/neg/variance-holes.scala:20]: This also compiles in dotty (should it though?)

**Comment by Blaisorblade** [comment]
Fwiw: Dotty does traverses bodies in PostTyper to find refinements and type lambdas (and guess RefChecks is a sensible phase for that). But those lambdas should not be checked for occurrences of class type params, only occurrences of their type params.

File: test/files/neg/variance-holes.scala (hunk 2 above)
Comment (Blaisorblade) [reply test/files/neg/variance-holes.scala:21]: Now fixed.

**Comment by joroKr21** [comment]
> Fwiw: Dotty does traverses bodies in PostTyper to find refinements and type lambdas (and guess RefChecks is a sensible phase for that). But those lambdas should not be checked for occurrences of class type params, only occurrences of their type params.

Cool, that's what I'm doing here as well. Now need to replicate the fix for `private[this]`.

**Comment by joroKr21** [comment]
@SethTisue may I kindly ask for a community build with this PR? :pray:

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2852/

**Comment by joroKr21** [comment]
Thank you, but unfortunately unlucky one :smile: 
`java.io.IOException: No space left on device`

**Comment by SethTisue** [comment]
gah. okay, I blew away a bunch of old builds. queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2854/

**Comment by joroKr21** [comment]
Apart from a stack overflow in `akka-stream` and an illegal cyclic error in `squants`, which are both known issues right now, couldn't find anything suspicious so I would say a successful build :tada:

**Comment by SethTisue** [comment]
@joroKr21 agree akka-stream and squants failures are known and unrelated.

but what about the monix failure? https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2855/artifact/logs/monix-build.log

**Comment by joroKr21** [comment]
Hmm, thanks, is that another build?

**Comment by SethTisue** [comment]
2854 had an airframe failure that looked possibly-intermittent to me, so I did one more run and indeed, that failure went away in 2855.

Offhand, I do not understand why monix compiled successfully in 2854 (though a test failed) but did not in 2855. Perhaps there were intervening commits on https://github.com/scala/community-build/tree/2.13.x . (The discrepancy probably isn't worth digging into? Not 100% sure.)

(As an aside: a fix for akka-stream was merged here in this repo recently, so a rebase of this PR would pick up that fix... except now Akka-stream is failing for a different reason, I'm looking into that separately.)

**Comment by joroKr21** [comment]
I pushed a commit to remove the check for escaping locals which was the cause of the Monix failure.

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2863/

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2868/

**Comment by SethTisue** [comment]
I canceled that run because I want to test #8586 first. assuming #8586 fixes akka-stream, then you could rebase this PR on top of it and we can try the run again.

**Comment by joroKr21** [comment]
Rebased

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2874/ (but, we already know that akka-stream isn't fixed yet, oh well)

File: src/reflect/scala/reflect/internal/Variances.scala [hunk 4]
```diff
@@ -85,12 +89,14 @@ trait Variances {
           else v
 
         @tailrec
-        def loop(sym: Symbol, v: Variance): Variance = (
-          if (sym == tvar.owner || v.isBivariant) v
+        def loop(sym: Symbol, v: Variance): Variance =
+          if (v.isBivariant) v
+          else if (sym == tvar.owner) if (lowerBoundStack.contains(sym)) v.flip else v
```
Comment (adriaanm) [inline src/reflect/scala/reflect/internal/Variances.scala]: Could the `if (lowerBoundStack.contains(sym)) v.flip` logic be moved into `nextVariance`/`shouldFlip`, and be handled before we get to this step of the recursion? We have a list of cases of when `shouldFlip` is true; would be great if you could add `lowerBoundStack.contains(sym.owner)` in there, if that makes sense.

In any case, please add some more comments around the usage of `lowerBoundStack`.

Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Variances.scala]: That was my attempt initially. But the recursion starts at `loop` and goes into `nextVariance` later (in the next branch). In some cases we don't even call `nextVariance` at all. Another option would be to merge `loop` and `nextVariance`.

Agree about the comments, I was thinking about adding more to the `validateDefinition` method.

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Variances.scala]: Ok, thanks for explaining. Would be good to also render those findings as comments, because it's likely someone else will have the same thought again at some point, if we already have evidence for N=2 :-)

Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Variances.scala]: @adriaanm I need a little help with something. I don't see `validateDefinition` being reentrant in any way (which confused me because the original version was saving and restoring the previous `base`).
Doesn't that mean we can replace the stack with a single variable?

Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Variances.scala]: Trying this now and also added documentation

**Comment by SethTisue** [comment]
@joroKr21 is this ready for review?

**Comment by joroKr21** [comment]
Yes it has been ready for a while, sorry if I didn't make it clear.

**Comment by dwijnand** [comment]
Looks like `test/files/neg/variance-holes.check` differences (only looked at the first commit results).

**Comment by joroKr21** [comment]
Uh, I rebased to resolve conflicts and updated the check. It worked locally. Could that be some difference between bootstrapped and non-bootstrapped compiler?

EDIT: That was another check file.

**Comment by SethTisue** [comment]
@adriaanm will you be doing the final review on this, or do we need to find another reviewer?

**Comment by adriaanm** [comment]
I won't have time to dig deeper than I already have. It all looked good on my initial pass. Glad to see the additional comments and cleanups since then! It would still be good to get another pair of 👀 on this IMO.

**Comment by SethTisue** [comment]
@lrytz you want to be the eyes, or assign someone?

**Comment by SethTisue** [comment]
@joroKr21 unless it gets left on the editing-room floor, there will be a brief shout-out in the next Scala Love episode to you and @milessabin for your bravery in tackling changes to Scala 2 type-checking

**Comment by SethTisue** [comment]
@joroKr21 I have the same question as I had on your other PR: whether this should get the "release-notes" label

**Comment by joroKr21** [comment]
Perhaps it's worth mentioning that together with #8651 there are a lot of bugs fixed in the variance check department for higher-kinded types, type aliases, type lambdas and type refinements.
And that this is another inch closer to Dotty (which obviously already fixed all the bugs here).

I'm not sure what's required for PR titles and descriptions.

**Review by lrytz — APPROVED** [review]
LGTM to the best of my knowledge

**Comment by lrytz** [comment]
Thank you, @joroKr21, for your continuous efforts!

**Comment by neko-kai** [comment]
@joroKr21 Wow, thank you! 👏
