### PR TITLE
SI-12290: support JDK15 text blocks in Java parser

### LINKED ISSUE #12290: scala.tools.nsc.javac.JavaParsers can't parse JDK15 Text Blocks (JEP 378)
This was originally reported as https://github.com/sbt/sbt/issues/6208 by @larousso  

## reproduction steps

```
$ java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```

### build.sbt

```scala
ThisBuild / scalaVersion     := "2.13.4"
ThisBuild / version          := "0.1.0-SNAPSHOT"

lazy val root = (project in file("."))
  .settings(
    name := "hello",
    // Compile / compileOrder := CompileOrder.JavaThenScala,
  )
```

### src/main/java/example/A.java

```java
package example;

class A {
  private String aText = """
    A text
    """;
}
```

## problem

```
sbt:hello> compile
[info] compiling 1 Scala source and 1 Java source to /private/tmp/hello/target/scala-2.13/classes ...
[error] /private/tmp/hello/src/main/java/example/A.java:4:29: unclosed string literal
[error]   private String aText = """
[error]                             ^
[error] /private/tmp/hello/src/main/java/example/A.java:6:8: unclosed string literal
[error]     """;
[error]        ^
[error] /private/tmp/hello/src/main/java/example/A.java:7:2: `;` expected but eof found.
[error] }
[error]  ^
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
```

## expectation

No errors.

## notes

https://openjdk.java.net/jeps/378

The workaround is to use `Compile / compileOrder := CompileOrder.JavaThenScala`.

See also:
- https://github.com/scala/bug/issues/11908
- https://github.com/scala/bug/issues/12159

### PR DESCRIPTION
**Pull request by harpocrates**
JDK15 introduced text blocks (JEP 378) for writing multiline strings.
This adds support for parsing these strings in the Java parser.

The logic for interpretting the literals is a little complicated, but
follows from the "3.10.6. Text Blocks" of the Java language specification.
The test cases include examples from there and from the JEP.

Fixes scala/bug#12290

### CODE REVIEW

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 1]
```diff
@@ -702,6 +716,108 @@ trait JavaScanners extends ast.parser.ScannersCommon {
...
+      if (in.ch != LF && in.ch != CR) {
+        syntaxError("illegal text block open delimiter sequence, missing line terminator")
+        return
+      }
+      in.next()
+
+      /* Do a lookahead scan over the full text block to:
+       *   - compute common white space prefix
+       *   - find the offset where the text block ends
+       */
```
Comment (harpocrates) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala:747]: I very much dislike needing to do two passes over the input (especially in a scanner), but the alternative is to buffer up and post-process lines. Finding the offset where the block ends is not essential, but it is definitely simplifies the second pass.

File: test/files/run/t12290/TextBlocks.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
+class TextBlocks {
```
Comment (harpocrates) [inline test/files/run/t12290/TextBlocks.java:2]: This code only compiles if the Java compiler is new enough to support text blocks. Is there some way to indicate that?

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 3]
```diff
@@ -702,6 +716,108 @@ trait JavaScanners extends ast.parser.ScannersCommon {
         in.next()
       }
 
+    /** read a triple-quote delimited text block, starting after the first three
+      * double quotes
+      */
+    private def getTextBlock(): Unit = {
+      // Open delimiter is followed by optional space, then a newline
+      while (isWhitespace(in.ch) && in.ch != CR && in.ch != LF && in.ch != SU) {
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: maybe avoid using `isWhitespace` since it's not really doing what we want here?

Acording to https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-3.10.6:

```suggestion
      while (in.ch = ' ' || in.ch == '\t' || in.ch == FF) {
```

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 4]
```diff
@@ -702,6 +716,108 @@ trait JavaScanners extends ast.parser.ScannersCommon {
...
+        in.next()
+      }
+      if (in.ch != LF && in.ch != CR) {
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: I think for `CR-LF`, both characters need to be consumed (also in the main loop below)

```
"""  \r\n
  foo\r\n
  bar"""
```
This block should have two lines.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 1 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala:747]: There's https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/lang/String.html#stripIndent() in newer JDKs, which suggests that javac handles the indentation in a post-processing step. I think that would be preferable also for us, not the most efficient solution, but I really don't think it matters for compiler performance.

File: test/files/run/t12290/TextBlocks.java (hunk 2 above)
Comment (lrytz) [reply test/files/run/t12290/TextBlocks.java:2]: Unfortunately we don't have anything set up to test on newer JDKs than 8.

You could do something like https://github.com/scala/scala/blob/2.13.x/test/files/run/t8852a.scala, I think that was added in a similar situation when we were still on JDK 6.

But we should have something better here, since this will also come when adding support for records or sealed classes.

**Review by lrytz — COMMENTED** [review]
Thank you and welcome! :)

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 1 above)
Comment (harpocrates) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala:747]: I'm not sure how we could use that. I think the Scala compiler is supposed to run in a host JVM that is 8+ even if it can target 8-16. Even then, code that depends on the host JVM version is usually hairy (since you have to detect the version and make sure it'll only ever be loaded on 16+).

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 4 above)
Comment (harpocrates) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: I was going to handle that, but then I noticed that it seems the Java char array reader already automatically turns `CR-LF` into `LF`:

https://github.com/scala/scala/blob/ccb7657760f72d8a48daf2efb1d3db0173425cf7/src/compiler/scala/tools/nsc/util/JavaCharArrayReader.scala#L46-L50

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 3 above)
Comment (harpocrates) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: It is shorter and simpler 👍. EDIT: nice catch - I see the `FF` I had initially missed. Thank you!

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 1 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala:747]: I was thinking we should re-implement it, sorry for being unclear.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 4 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: Ah, I wasn't aware 👍 Maybe leave in a comment about that.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 1 above)
Comment (harpocrates) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala:747]: OK, that makes sense now. I see that this is [what `javac` does](https://github.com/openjdk/jdk16/blob/37043b05576c8b81b43ac41a8f06de0d0bbb3f5b/src/jdk.compiler/share/classes/com/sun/tools/javac/parser/JavaTokenizer.java#L1059) - I guess that's the benefit of being able to move the compiler and runtime forward at the same time.

Is there a reason you prefer an approach that post-processes? I opted against that because the existing machinery for parsing character escapes would need to be refactored: we need to be aware of the character escapes while collecting the initial raw string, but we have to avoid interpreting them until after we've stripped whitespace. The current `getlitch` function does the parsing and interpreting all in one step (Java uses `translateEscapes`, but that's also only available JDK 14+).

Comment (lrytz) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala:747]: Let me take another look with the escaping issue in mind.

My main motivation splitting it up would be to keep the code in the Java scanner simpler.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 5]
```diff
@@ -702,6 +716,108 @@ trait JavaScanners extends ast.parser.ScannersCommon {
         in.next()
       }
 
+    /** read a triple-quote delimited text block, starting after the first three
+      * double quotes
+      */
+    private def getTextBlock(): Unit = {
+      // Open delimiter is followed by optional space, then a newline
+      while (in.ch = ' ' || in.ch == '\t' || in.ch == FF) {
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]:
```suggestion
      while (in.ch == ' ' || in.ch == '\t' || in.ch == FF) {
```

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 6]
```diff
@@ -702,6 +716,108 @@ trait JavaScanners extends ast.parser.ScannersCommon {
...
+            lineIsOnlyWhitespace = false
+          }
+        } else if (in.ch == CR || in.ch == LF) { // new line in the block
+          in.next()
+          if (!lineIsOnlyWhitespace) {
+            commonWhiteSpacePrefix = commonWhiteSpacePrefix min lineWhiteSpacePrefix
+          }
+          lineWhiteSpacePrefix = 0
+          lineIsOnlyWhitespace = true
+        } else if (lineIsOnlyWhitespace && isWhitespace(in.ch)) { // extend white space prefix
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: `isWhitespace` includes `CR`; i see `CR` is handled above, but it's still a bit confusing maybe?

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 7]
```diff
@@ -702,6 +716,108 @@ trait JavaScanners extends ast.parser.ScannersCommon {
...
+        }
+
+        var trailingWhitespaceLength = 0
+        while (in.ch != CR && in.ch != LF && in.cpos < blockEndOffset) {
+          if (isWhitespace(in.ch)) {
+            trailingWhitespaceLength += 1
+          } else {
+            trailingWhitespaceLength = 0
+          }
+          getlitch()
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: this method issues an error for invlid escapes. since this is the second time it's called, do we see the errors twice?

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 1 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala:747]: I took another look; we could change `getlitch` to have a boolean parameter to only check or also interpret escapes. The `getTextBlock` would then be quite simple, assuming we have `translateEscapes` and `stripIdent` - which is currently not the case though. Your implementation looks good, so I agree it's the better way for now.

**Comment by lrytz** [comment]
Oh another detail: `\s` is a valid escape sequence now in Java (not only for text blocks, also for strings and char literals). So it should be added to `getlitch`.
https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-3.10.7

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 7 above)
Comment (harpocrates) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: `syntaxError` is called twice, but the reporter itself must do some deduplication since I only see the error once. Is this still a concern (maybe for some reporter that isn't the default)?

**Comment by harpocrates** [comment]
> Oh another detail: \s is a valid escape sequence now in Java (not only for text blocks, also for strings and char literals).

I added support for `\s` and also for escaping newlines in text blocks (trailing `\`). All escape sequences should be covered now.

---

I've been force-pushing updates (since I read that Scala prefers to keep a clean commit log), but I can also just add commits if it is easier to review and squash them at the end.

**Comment by SethTisue** [comment]
> I've been force-pushing updates (since I read that Scala prefers to keep a clean commit log), but I can also just add commits if it is easier to review and squash them at the end.

Either way is fine. We do it either way depending on the nature of the PR and on individual preference, rather than trying to establish a firm policy.

If in doubt, I would say default to squashing at the end, especially on anything where the reviewing gets complicated or appears likely to get complicated.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 7 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: Right, the default shows at most one error at a position. But I think it would still be good to avoid it, non-default reporters do exist, in sbt for example.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 8]
```diff
@@ -702,6 +718,120 @@ trait JavaScanners extends ast.parser.ScannersCommon {
...
+      * double quotes
+      */
+    private def getTextBlock(): Unit = {
+      // Open delimiter is followed by optional space, then a newline
+      while (in.ch == ' ' || in.ch == '\t' || in.ch == FF) {
+        in.next()
+      }
+      if (in.ch != LF && in.ch != CR) { // CR-LF is already normalized into LF by `JavaCharArrayReader`
+        syntaxError("illegal text block open delimiter sequence, missing line terminator")
+        return
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala:740]: Instead of / before returning, maybe we try to advance reader to the end of the text block? Otherwise there are a lot of errors issued when continuing to parse.

Although javac is not any better :-) So I'm fine if you leave it.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 9]
```diff
@@ -665,7 +679,7 @@ trait JavaScanners extends ast.parser.ScannersCommon {
 
     /** read next character in character or string literal:
     */
-    protected def getlitch() =
+    protected def getlitch(skipErrors: Boolean = false) =
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: since we have the boolean param now, we could also skip the `putChar`, then nothing would get written to `cbuf` in the first pass

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 10]
```diff
@@ -702,6 +718,120 @@ trait JavaScanners extends ast.parser.ScannersCommon {
...
+        } else if (lineIsOnlyWhitespace &&
+                   (in.ch == ' ' || in.ch == '\t' || in.ch == FF)) { // extend white space prefix
+          in.next()
+          lineWhiteSpacePrefix += 1
+        } else {
+          lineIsOnlyWhitespace = false
+          getlitch(skipErrors = true)
+        }
+      }
+      setName() // clear the literal buffer
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: this is not ideal because `newTermName` adds the string to the name table even if it's never used in the end.

if we change the first pass to not add anything to `cbuf` we can just skip this (see my other comment).

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 11]
```diff
@@ -691,8 +705,10 @@ trait JavaScanners extends ast.parser.ScannersCommon {
             case '\"' => putChar('\"')
             case '\'' => putChar('\'')
             case '\\' => putChar('\\')
+            case 's'  => putChar(' ')  // specific to text blocks
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: `\s` is actually also allowed in string / char literals

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 12]
```diff
@@ -691,8 +705,10 @@ trait JavaScanners extends ast.parser.ScannersCommon {
...
+            case CR | LF =>            // specific to text blocks
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: Now it accepts

```
    System.out.println("hi\
lu");
```

so we should really only allow it in text blocks

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala [hunk 13]
```diff
@@ -702,6 +718,120 @@ trait JavaScanners extends ast.parser.ScannersCommon {
...
+          }
+        } else if (in.ch == CR || in.ch == LF) { // new line in the block
+          in.next()
+          if (!lineIsOnlyWhitespace) {
+            commonWhiteSpacePrefix = commonWhiteSpacePrefix min lineWhiteSpacePrefix
+          }
+          lineWhiteSpacePrefix = 0
+          lineIsOnlyWhitespace = true
+        } else if (lineIsOnlyWhitespace &&
+                   (in.ch == ' ' || in.ch == '\t' || in.ch == FF)) { // extend white space prefix
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: hmm, maybe here (and for trailing whitespace) a different definition of "white space" applies?

https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/lang/String.html#stripIndent()

refers to

https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/lang/Character.html#isWhitespace(int)

what do you think? at least that method exists on JDK 8, so it would be easy to change.

**Review by lrytz — COMMENTED** [review]
Gave it another pass... But we're close!

I'll talk to Seth next week about testing. It would be good if we could mark tests as Java N+ and have some CI job that runs those regularly.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 8 above)
Comment (harpocrates) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala:740]: Maybe just not returning would do the trick? I'll try this out after work.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 12 above)
Comment (harpocrates) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: I anticipated this, but I figured it maybe wasn't too important: the Java code is anyways not going to compile (similar to how `JavaParsers` will accept completely bogus method bodies that balance parens and braces). That said, it is easy to guard behind some `textBlock: Boolean` flag, so I'll do that.

File: src/compiler/scala/tools/nsc/javac/JavaScanners.scala (hunk 13 above)
Comment (harpocrates) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: Given that this appears to be what `javac` does, I guess we should too. I'm struggling to see how the implementation of `stripIndent` matches the spec's definition of whitespace https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-WhiteSpace.

Comment (lrytz) [reply src/compiler/scala/tools/nsc/javac/JavaScanners.scala]: If I understand the spec correctly, the spec's definition of `WhiteSpace` is only used for the whitespace following the initial `"""`. For the content of the text block (where leading and trailing whitespace is handled), the spec delegates to `String.stripIndent` and `String.translateEscapes`.

**Review by lrytz — COMMENTED** [review]
Looks good now!

We'll get back to you about the testing situation.

A few more tests could be added
  - mixed indentation with tabs and spaces (each count 1 character of indentation)
  - escaped new line `\`
  - `\uXXXX` escapes are handled before the text block (`\u0020` is leading whitespace, `\s` is not)
  - invalid text blocks
    - non-whitespace after initial `"""`
    - difference to scala, which just uses the last 3 `"` to close a multiline string `"""this is "fine""""`
  - maybe CRLF, FF, exoctic unicode whitespaces...

**Comment by harpocrates** [comment]
I've added some extra tests to cover the cases you mentioned. I imagine that depending on how testing plays out there may be some modification needed to indicate the tests only run on JDK 14+. I'll be looking out for those updates to testing.

Thanks for the patient reviews!

**Comment by SethTisue** [comment]
WIP PR adding JDK 16 to Travis-CI: #9579

**Comment by SethTisue** [comment]
#9579 has landed, but now this is waiting on https://github.com/scala/scala/pull/9587

**Comment by som-snytt** [comment]
I don't think lrytz wanted to wait.

**Review by lrytz — APPROVED** [review]
