### PR TITLE
Fix #12619: Tasty Reader: Add DEFAULTPARAM to default accessors.

### LINKED ISSUE #4700: js.native default arguments vs CrossVersion.for2_13Use3
I have an sbt project A on Scala 3 and another sbt project B at Scala 2 that depends on project A. Project B depends on scala-js-dom. Due to tricky situation with dependencies that A has and B has, B declares the dependency on scala-js-dom as `cross CrossVersion.for2_13Use3`.

I am facing issues with default arguments in this set-up. For example, I have this piece of code on the source code of B:

```scala
dom.document.addEventListener("load", myFunction)
```

this is the respective object code produced in fastOptJS:

```js
document.addEventListener("load", $m_sjs_js_Any$().fromFunction1__F1__sjs_js_Function1(myFunction), $uZ(document.addEventListener$default$3));
```

This code fails at runtime: `Uncaught org.scalajs.linker.runtime.UndefinedBehaviorError: java.lang.ClassCastException: undefined is not an instance of java.lang.Boolean`. `$uZ` is part of the stack trace. I did not inspect, but I assume that there is no value `document.addEventListener$default$3`, and therefore it is `undefined`.

Looking at the scala-js-dom code, we can see that the third parameter of that function is `useCapture: Boolean = js.native`.
https://github.com/scala-js/scala-js-dom/blob/3600c24f0612c940e59a5ff7371491e9eb0f9100/dom/src/main/scala/org/scalajs/dom/EventTarget.scala#L32-L33

I don't know how such arguments are designed to be compiled, but my intuition is that the object code should look like this instead:

```js
document.addEventListener("load", $m_sjs_js_Any$().fromFunction1__F1__sjs_js_Function1(myFunction));
```

### Versions

Plugins
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.10.1")
```

Project B
```
scalaVersion := "2.13.8"
scalacOptions += "-Ytasty-reader"
libraryDependencies += "org.scala-js" %%% "scalajs-dom" % "2.2.0" cross CrossVersion.for2_13Use3
```

### Reproduction

You can find a repository with the issue replicated here: https://github.com/gabriel-bezerra/scala-js-4700-reproduction/

The example of the produced file: https://github.com/gabriel-bezerra/scala-js-4700-reproduction/blob/5c0183a594b618a7767150bca937af3dd5452c40/scala-js-tutorial-fastopt.js#L855

### PR DESCRIPTION
**Pull request by sjrd**
In dotc, default accessors are identified by a semantic name. In scalac, they have the DEFAULTPARAM flag instead. We now add that flag to methods that have a default-param name.

I verified that this fixes https://github.com/scala-js/scala-js/issues/4700 as well.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/tasty/bridge/FlagOps.scala [hunk 1]
```diff
@@ -120,6 +120,7 @@ trait FlagOps { self: TastyUniverse =>
     if (!tflags) "EmptyTastyFlags"
     else {
       val sb = collection.mutable.ArrayBuffer.empty[String]
+      if (flags.is(HasDefault))  sb += "<defaultparam>"
```
Comment (bishabosha) [inline src/compiler/scala/tools/nsc/tasty/bridge/FlagOps.scala]: spurious change from when we attempted to treat `HasDefault` as one of `TastyOnlyFlags`
```suggestion
```

**Review by bishabosha — APPROVED** [review]
