### PR TITLE
Select symbol overload in tree unpickling

### LINKED ISSUE #13087: Compiler crash when using annotation defaults (nightlies only)
Regression due to (unreleased) https://github.com/scala/scala/pull/10976.

`ann.scala`:

```scala
class ann(key: Int = ann.f + 1) extends annotation.StaticAnnotation
object ann {
  def f = 1
  def f(x: Int) = 2
}
```

`T.scala`:

```scala
@ann() class T
```

Separate compilation of `T.scala` crashes the pickler

```
error: scala.reflect.internal.FatalError: bad type: (x: String): String <and> (x: Byte): Int <and> (x: Short): Int <and> (x: Char): Int <and> (x: Int): Int <and> (x: Long): Long <and> (x: Float): Float <and> (x: Double): Double(class scala.reflect.internal.Types$OverloadedType)
	at scala.tools.nsc.symtab.classfile.Pickler$Pickle.scala$tools$nsc$symtab$classfile$Pickler$Pickle$$putType(Pickler.scala:362)
	at scala.tools.nsc.symtab.classfile.Pickler$Pickle$putTreeTraverser$.put(Pickler.scala:377)
```

The default expression AST is pickled using the `@defaultArg` meta-annotation

`class ann(@defaultArg(ann.f + 1) key: Int = ann.f + 1) extends annotation.StaticAnnotation`

Pickling of ASTs doesn't include any information for overloading resolution. When unpickling the tree, the lookup for `ann.f` assigns an `OverloadedType` to the tree.

That unpickled tree is then inserted as default argument in `@ann(ann.f + 1)`. Pickling that annotation fails because the pickler doesn't expect overloaded types.

### PR DESCRIPTION
**Pull request by lrytz**
References to external symbols are pickled as owner + name, so overloads cannot be resolved. This only affects tree unpickling, i.e., only annotation arguments.

At some point in history, the unpickler was using
`Infer.inferMethodAlternative`, but not anymore since fff93cd049.

This commit performs overloading resolution based on the Select tree's type instead: when unpickling `t.f`, the `tpe` of the tree is unpickled. This type can be used to select the correct overload.

Fixes https://github.com/scala/bug/issues/13087

### CODE REVIEW

File: src/reflect/scala/reflect/internal/pickling/UnPickler.scala [hunk 1]
```diff
@@ -526,15 +526,6 @@ abstract class UnPickler {
       @inline def all[T](body: => T): List[T] = until(end, () => body)
       @inline def rep[T](body: => T): List[T] = times(readNat(), () => body)
 
-      // !!! What is this doing here?
-      def fixApply(tree: Apply, tpe: Type): Apply = {
-        val Apply(fun, args) = tree
-        if (fun.symbol.isOverloaded) {
-          fun setType fun.symbol.info
-          inferMethodAlternative(fun, args map (_.tpe), tpe)
```
Comment (lrytz) [inline src/reflect/scala/reflect/internal/pickling/UnPickler.scala:534]: This was actually making things worse. Tree types are pickled, so `fun.tpe` is a non-overloaded type before this code. `inferMethodAlternative` is a no-op.

So in unpickled ASTs, a Select of an overloaded method had an overloaded `selectTree.tpe`. Trying to re-pickle such a tree fails (https://github.com/scala/bug/issues/13087).

Removing this coulde would be enough to fix the bug, but I added the new `fixOverload` anyway.

**Comment by som-snytt** [comment]
The "balloon payment" commit is very frustrating when examining history. I think a different economic metaphor is needed, perhaps, "permanent lien".

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
("internal" because the regression never shipped)
