### PR TITLE
Correctly report unused variables introduced by patterns in value definitions in for comprehensions

### LINKED ISSUE #13070: No warning for unused patvars in for comprehension assignment
## Questions are not bug reports

I had a question...

## Reproduction steps

Scala version: 2.13.16

```scala
class C {
  def g = {
    val t = Option((27, 42))
    for {
      ns <- t
      (i, j) = ns
    } yield 42
  }
}
```

## Problem

Does not warn unused `i`, `j` under `-Wunused`.

It correctly does not warn for the unused "intermediates" during the tupling map, but should warn because they are not used after that.

The existing test only verifies that it does not yield a false positive under `-Wunused:-patvars` (turned off).

```
package <empty> {
  class C extends scala.AnyRef {
    def <init>(): C = {
      C.super.<init>();
      ()
    };
    def g: Option[Int] = {
      val t: Option[(Int, Int)] = scala.Option.apply[(Int, Int)](scala.Tuple2.apply[Int, Int](17, 42));
      t.map[((Int, Int), (Int, Int))](((ns: (Int, Int)) => {
  <synthetic> <artifact> private[this] val x$2: ((Int, Int), Int, Int) = (ns: (Int, Int) @unchecked) match {
    case (x$1 @ (_1: Int, _2: Int): (Int, Int)((i @ _), (j @ _))) => scala.Tuple3.apply[(Int, Int), Int, Int](x$1, i, j)
  };
  val x$1: (Int, Int) = x$2._1;
  val i: Int = x$2._2;
  val j: Int = x$2._3;
  scala.Tuple2.apply[(Int, Int), (Int, Int)](ns, x$1)
})).map[Int](((x$3: ((Int, Int), (Int, Int))) => (x$3: ((Int, Int), (Int, Int)) @unchecked) match {
        case (_1: (Int, Int), _2: (Int, Int)): ((Int, Int), (Int, Int))((ns @ _), (_1: Int, _2: Int): (Int, Int)((i @ _), (j @ _))) => 42
      }))
    }
  }
}
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes https://github.com/scala/bug/issues/13070

### CODE REVIEW

File: test/files/neg/t13070.scala [hunk 1]
```diff
@@ -0,0 +1,10 @@
+//> using options -Wunused:patvars -Werror
+class C {
+  def g = {
+    val t = Option((27, 42))
+    for {
+      ns <- t
+      (i, j) = ns
```
Comment (lrytz) [inline test/files/neg/t13070.scala]: let's add a variant to the test where i/j are used

Comment (som-snytt) [reply test/files/neg/t13070.scala]: from the other compiler, I've forgotten what the behavior is here. I seem to remember people complaining that they can't make just one mutable.
```
object `patvar is assignable`:
  var (i, j) = (42, 27) // no warn nonprivate
  j += 1
  println((i, j))

object `privy patvar is assignable`:
  private var (i, j) = (42, 27) // warn
  j += 1
  println((i, j))

object `local patvar is assignable`:
  def f() =
    var (i, j) = (42, 27) // warn
    j += 1
    println((i, j))

object `mutable patvar in for`:
  def f(xs: List[Int]) =
    for x <- xs; y = x + 1 if y > 10 yield
      var z :: Nil = y :: Nil: @unchecked // warn
      z + 10

class `unset var requires -Wunused`:
  private var i = 0 // no warn as we didn't ask for it
  def f = println(i)
```

Comment (som-snytt) [reply test/files/neg/t13070.scala]: I guess it doesn't warn for patvar def under patvars but under privates/locals. Even though they are patvars.

Hmm...

Comment (som-snytt) [reply test/files/neg/t13070.scala]: Maybe that was only because the patvar warning was unreliable, so for maximal utility it relied on the other flag.

This question suggests that the distinction is artificial.

**Review by lrytz — APPROVED** [review]
Thanks!

**Comment by He-Pin** [comment]
Thank you

**Comment by SethTisue** [comment]
@som-snytt is new PR title accurate?

**Comment by som-snytt** [comment]
@SethTisue thanks, this is the `x = y` in `for (y <- z; x = y)` which can be any pattern such as `Some(x) = y`.

I say "tupling" because that is the desugaring. Spec calls it "value definition"; Java called it "mid-stream assignment", which I use sometimes.
