### PR TITLE
[#11600] Vector.from(ArraySeq) copies elems rather than reusing unsafeArray

### LINKED ISSUE #11600: 2.13.0: ArrayStoreException in Vector.updated
This may be an instance of #7268 as it does not happen if the vector is not constructed via `Vector.apply`, but this particular manifestation is new in 2.13:
```scala
abstract class Base
class Derived1 extends Base
class Derived2 extends Base
val x = Vector(new Derived1)
x.updated(0, new Derived2) // exception in Vector.updateAt
```
If it matters, the JVM is openjdk 1.8.0_212

### PR DESCRIPTION
**Pull request by joshlemer**
Closes scala/bug#11600
Fixes scala/bug#11600

There were issues with reusing the ArraySeq unsafeArray which arose in
subsequent calls to Vector#updated which would then clone underlying
arrays, and insert into them the new updated element. However the
underlying array.clone() would return a new array with the same
componentType as the passed varargs, rather than an Array[AnyRef] which
is required in the general case.

### CODE REVIEW

File: src/library/scala/collection/immutable/Vector.scala [hunk 1]
```diff
@@ -30,11 +30,23 @@ object Vector extends StrictOptimizedSeqFactory[Vector] {
 
   def from[E](it: collection.IterableOnce[E]): Vector[E] =
     it match {
-      case as: ArraySeq[E] if as.length <= 32 && as.unsafeArray.isInstanceOf[Array[AnyRef]] =>
```
Comment (NthPortal) [inline src/library/scala/collection/immutable/Vector.scala:33]: we should be able to reuse the same array without copying if it's exactly `Array[AnyRef]]`

```scala
scala> new Array[String](0).getClass == classOf[Array[AnyRef]]
res2: Boolean = false

scala> new Array[AnyRef](0).getClass == classOf[Array[AnyRef]]
res3: Boolean = true
```

```scala
as.unsafeArray.getClass == classOf[Array[AnyRef]]
```

File: test/junit/scala/collection/immutable/VectorTest.scala [hunk 2]
```diff
@@ -219,4 +219,48 @@ class VectorTest {
       assertArrayEquals(s"<${v2.length}>.slice($j, $k)", v2.toArray.slice(j, k), v2.iterator.slice(j, k).toArray)
     }
   }
+
+  @Test
+  def i11600(): Unit = {
```
Comment (NthPortal) [inline test/junit/scala/collection/immutable/VectorTest.scala]: `t`?

File: src/library/scala/collection/immutable/Vector.scala (hunk 1 above)
Comment (joshlemer) [reply src/library/scala/collection/immutable/Vector.scala:33]: I thought about this, but thought this is a pretty niche scenario, who goes around calling `Vector.apply[AnyRef](...)`? An alternate approach would be to special case the underlying `display0.clone()` logic (which is hit by `updated`) to be `display0.copyToArray(new Array[AnyRef](32))`. This would allow us to keep reusing the unsafeArray. (and maybe even in the case of primitives?)

Comment (NthPortal) [reply src/library/scala/collection/immutable/Vector.scala:33]: anything that creates a vector from a generic context with varargs will be an `ArraySeq` wrapping an `Array[AnyRef]`

Comment (lrytz) [reply src/library/scala/collection/immutable/Vector.scala:33]: Ping @joshlemer, wdyt?

Comment (joshlemer) [reply src/library/scala/collection/immutable/Vector.scala:33]: @lrytz made a new draft PR https://github.com/scala/scala/pull/8276

**Comment by szeiger** [comment]
@joshlemer With the subtle Vector problems that led to the other remaining open Vector PR in mind, I think we should merge this one and leave the more ambitious version for 2.13.2 rather than rushing it now. WDYT?

File: src/library/scala/collection/immutable/Vector.scala [hunk 3]
```diff
@@ -45,17 +57,11 @@ object Vector extends StrictOptimizedSeqFactory[Vector] {
...
-          val display0 = new Array[AnyRef](knownSize)
-
-          var i = 0
-          val iterator = it.iterator
-          while (iterator.hasNext) {
-            display0(i) = iterator.next().asInstanceOf[AnyRef]
-            i += 1
-          }
+          val display0 = new Array[Any](knownSize)
+          it.iterator.copyToArray(display0)
```
Comment (szeiger) [inline src/library/scala/collection/immutable/Vector.scala:61]: why not `it.copyToArray` to benefit from fast array copying for array-based collections?

**Review by szeiger — APPROVED** [review]
Merging this now so we can get on with the 2.13.1 release. I see some room for optimization but we have #8276 for that and everything here looks safe.
