### PR TITLE
Don't warn about synthetic apply if user-added

### LINKED ISSUE #12883: Scala 2.13.12 fatal warning with -Xsource:3 and private constructor for case class
## Reproduction steps

Scala version: 2.13.12

```scala
scala> case class Data private (s: String)
                  ^
       error: constructor modifiers are assumed by synthetic `copy` method
       Scala 3 migration messages are errors under -Xsource:3. Use -Wconf / @nowarn to filter them or add -Xmigration to demote them to warnings.
       Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=scala3-migration, site=Data
```

## Problem

Same warning is for synthetic `apply` method. This cannot be fixed without redefining `copy` and `apply` explicitly and  doesn't help with any Scala 3 migration issue. In all cases I have to suppress it with `@nowarn`

### PR DESCRIPTION
**Pull request by som-snytt**
Improve message for clarity.

Fix bug where warning for `apply` is emitted too early, as the method may be "retracted" on completion if user-supplied.

Split from https://github.com/scala/scala/pull/10551

Fixes scala/bug#12883

### CODE REVIEW

**Comment by som-snytt** [comment]
@SethTisue "Also..."

```
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: fad1886f-28dc-4e89-a229-ce67037d7004
java.io.IOException: No space left on device
```

File: src/compiler/scala/tools/nsc/typechecker/Unapplies.scala [hunk 1]
```diff
@@ -156,10 +156,6 @@ trait Unapplies extends ast.TreeDSL {
     val mods =
       if (applyShouldInheritAccess(inheritedMods))
         (caseMods | (inheritedMods.flags & PRIVATE)).copy(privateWithin = inheritedMods.privateWithin)
-          .tap { mods =>
-            if (currentRun.isScala3 && mods != caseMods)
-              runReporting.warning(cdef.pos, "constructor modifiers are assumed by synthetic `apply` method", WarningCategory.Scala3Migration, cdef.symbol)
-          }
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Unapplies.scala:162]: so this code runs even if there is a user-defined companion `apply`? where do we check for that case?

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Unapplies.scala:162]: the retraction is in `applyUnapplyMethodCompleter`

**Comment by SethTisue** [comment]
Jenkins disk space issue is resolved.

**Comment by som-snytt** [comment]
🎃 (squash)

**Comment by som-snytt** [comment]
🦃 (rebased)

**Comment by lrytz** [comment]
The implementation looks good, thanks!

I'm still unsure about issuing a warning that cannot be addressed with a code change. `case class C private (val x: Int)` is fine code in Scala 3, we should not warn about it under `-Xsource:3`.

**Comment by som-snytt** [comment]
I will contribute distinguishing `-Xsource:3` (to warn but no behavior changes) and `-Xsource:3-X` (any version that compares > 3.0, to mean give me behavior change but then don't warn about it).

I see a commit, but I will have to organize a PR. It got mixed in with trying out `-Xsource:3` on stdlib.

https://github.com/som-snytt/scala/commit/df45ed0f37184cda47515021e36eb7f4d0e130cd

I think you can approve this as addressing the immediate issue, and I will follow up for the separate issue about nuanced `-Xsource:3`.

**Comment by lrytz** [comment]
Sounds good to me, thanks!
