### PR TITLE
Fix bug where `Vector#prependedAll` could leave the Vector in an illegal state

### LINKED ISSUE #12598: Vector.prependedAll returns Vector in illegal state
## Reproduction steps

Scala version: 2.13.3 to 2.13.8, latest [`7952071`](https://github.com/scala/scala/tree/7952071b88a85e2502e9ecd4e8bd57040d9448f5)

```scala
val v = Vector(1 to 10000: _*)
val (pre, suf) = v.splitAt(1) // split v ...
val v2 = pre ++: suf // ...and concat again
println(s"${v(1023)} becomes ${v2(1023)} 👀") // prints "1024 becomes 1025 👀"
v2(v2.length-1) // ArrayIndexOutOfBoundsException
```

## Problem

`v2.len12` is 1023, but should be 1024 (as `v2.prefix1.length + v2.prefix2.length * WIDTH = 32 + 31 * 32 = 1024`).
This is an illegal state and yields unexpected behavior as seen above.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12598

### CODE REVIEW

**Comment by ansvonwa** [comment]
Amended your PR, see https://github.com/som-snytt/scala/pull/10.

File: src/library/scala/collection/immutable/Vector.scala [hunk 1]
```diff
@@ -417,11 +417,11 @@ private final class Vector1[+A](_data1: Arr1) extends VectorImpl[A](_data1) {
...
-  override protected[this] def prependedAll0[B >: A](prefix: collection.IterableOnce[B], k: Int): Vector[B] = {
-    val data1b = prepend1IfSpace(prefix1, prefix)
-    if(data1b ne null) new Vector1(data1b)
-    else super.prependedAll0(prefix, k)
-  }
+  override protected[this] def prependedAll0[B >: A](prefix: collection.IterableOnce[B], k: Int): Vector[B] =
+    prepend1IfSpace(prefix1, prefix) match {
+      case null => super.prependedAll0(prefix, k)
+      case data1b => new Vector1(data1b)
+    }
```
Comment (NthPortal) [inline src/library/scala/collection/immutable/Vector.scala:424]: is there a reason to switch to pattern matching? for weird reasons that I'm sure someone other than me understands, it produces more bytecode.

<details>
<summary>REPL example:</summary>

```scala
scala> object Foo {
     |   private[this] def maybeAnyRef(): AnyRef =
     |     if (scala.util.Random.nextBoolean()) new AnyRef else null
     | 
     |   private[this] def identityHashCode(ref: AnyRef): String =
     |     s"${System.identityHashCode(ref)}"
     | 
     |   def bar(): String = {
     |     val ref = maybeAnyRef()
     |     if (ref == null) "null"
     |     else identityHashCode(ref)
     |   }
     | 
     |   def baz(): String =
     |     maybeAnyRef() match {
     |       case null => "null"
     |       case ref  => identityHashCode(ref)
     |     }
     | }
object Foo

scala> :javap -c -filter Foo
Compiled from "<console>"
public class Foo$ {
  public java.lang.String bar();
    Code:
       0: aload_0
       1: invokespecial #53                 // Method maybeAnyRef:()Ljava/lang/Object;
       4: astore_1
       5: aload_1
       6: ifnonnull     14
       9: ldc           #55                 // String null
      11: goto          19
      14: aload_0
      15: aload_1
      16: invokespecial #57                 // Method identityHashCode:(Ljava/lang/Object;)Ljava/lang/String;
      19: areturn

  public java.lang.String baz();
    Code:
       0: aload_0
       1: invokespecial #53                 // Method maybeAnyRef:()Ljava/lang/Object;
       4: astore_2
       5: aload_2
       6: ifnonnull     15
       9: ldc           #55                 // String null
      11: astore_1
      12: goto          27
      15: goto          18
      18: aload_0
      19: aload_2
      20: invokespecial #57                 // Method identityHashCode:(Ljava/lang/Object;)Ljava/lang/String;
      23: astore_1
      24: goto          27
      27: aload_1
      28: areturn

  public Foo$($iw);
    Code:
       0: aload_0
       1: invokespecial #27                 // Method java/lang/Object."<init>":()V
       4: return
}
```
</details>

Comment (ansvonwa) [reply src/library/scala/collection/immutable/Vector.scala:424]: The reason was that @som-snytt changed the structure in `Vector3.prependedAll0` (which I also think looks nicer). The same changes were needed for `Vector{4,5,6}.prependedAll0` and I thought it might be better if the methods don't look differently structured in `Vector{1,2}` although they do the same. See my [comment here](https://github.com/som-snytt/scala/pull/10#discussion_r889546229).

Imho, all those methods should use the same. Preferably pattern matching, but if the additional bytecode is a problem, I suppose that is the case in all classes, so they should all use the `if`.

I'd argue that suboptimal bytecode for idomatic code is a compiler-problem and maybe the generation should be improved?

---
Side note: In Dotty, the result is slightly better, but still worse than if-else.
```scala
  public java.lang.String bar();
    ... // as Scala-2

  public java.lang.String baz();
    Code:
       0: aload_0
       1: invokespecial #59                 // Method maybeAnyRef:()Ljava/lang/Object;
       4: astore_1
       5: aload_1
       6: ifnonnull     14
       9: ldc           #61                 // String null
      11: goto          24
      14: aload_1
      15: astore_2
      16: aload_0
      17: aload_2
      18: invokespecial #63                 // Method identityHashCode:(Ljava/lang/Object;)Ljava/lang/String;
      21: goto          24
      24: areturn
```
If you add return keywords in the match clauses, it's nearly the same bytecode as with if-else in Scala-2, but much worse in Dotty.
```scala
  def boo(): String =
    maybeAnyRef() match {
      case null => return "null"
      case ref  => return identityHashCode(ref)
    }
```
in Scala-2:
```scala
  public java.lang.String boo();
    Code:
       0: aload_0
       1: invokespecial #51                 // Method maybeAnyRef:()Ljava/lang/Object;
       4: astore_2
       5: aload_2
       6: ifnonnull     12
       9: ldc           #53                 // String null
      11: areturn
      12: goto          15
      15: aload_0
      16: aload_2
      17: invokespecial #55                 // Method identityHashCode:(Ljava/lang/Object;)Ljava/lang/String;
      20: areturn
```
But in Dotty:
```scala
  public java.lang.String boo();
    Code:
       0: aload_0
       1: invokespecial #59                 // Method maybeAnyRef:()Ljava/lang/Object;
       4: astore_1
       5: aload_1
       6: ifnonnull     15
       9: ldc           #61                 // String null
      11: areturn
      12: nop
      13: nop
      14: athrow
      15: aload_1
      16: astore_2
      17: aload_0
      18: aload_2
      19: invokespecial #63                 // Method identityHashCode:(Ljava/lang/Object;)Ljava/lang/String;
      22: areturn
      23: nop
      24: nop
      25: athrow
      26: athrow
      27: athrow
```

Comment (sjrd) [reply src/library/scala/collection/immutable/Vector.scala:424]: The bytecode generated for matches is dramatically improved in dotty's `main` branch (for 3.2.0), in scalac's `2.12.x` branch (for 2.12.16) and [soon in the `2.13.x` branch](https://github.com/scala/scala/pull/10039) (for 2.13.9). So if you want to compare generated bytecode, it's better to test with those changes included.

Comment (som-snytt) [reply src/library/scala/collection/immutable/Vector.scala:424]: Thanks sjrd! I was not aware. I can confirm that with scala 2, the match adds a local even under `-opt`, but with sjrd's branch the bytecode is identical (except that the null check is inverted). Without `-opt`, match incurs `astore 4`.

The other twist is that `data1b` as a pattern variable does not get an entry in local var table.

It seems dotty currently incurs `astore 4` just around the usage of `data1b` in `new Vector1(data1b)`; maybe for that reason, it shows up in the local var table. Otherwise it's as clean as sjrd scala 2.

Comment (som-snytt) [reply src/library/scala/collection/immutable/Vector.scala:424]: Also thanks NthPortal for taking a look. There may be another discussion to have about the idiom as style, that is, "abuse of match" to replace if/else. This is not as egregious as `case _ if b`; the other use case is to replace `isInstanceOf`/`asInstanceOf` pairs, which some people prefer (for reasons that escape me, unless it is for the same concern about "bloated code"). Briefly, I see that in this case, match avoids introducing a variable that is nullable. But really I just wanted to eliminate the enclosing braces.

Comment (som-snytt) [reply src/library/scala/collection/immutable/Vector.scala:424]: Note that if this were a terrible regression, care would be needed that Dotty didn't consume the lib change before its optimized backend caught up.

Comment (lrytz) [reply src/library/scala/collection/immutable/Vector.scala:424]: > The other twist is that `data1b` as a pattern variable does not get an entry in local var table.

I think that's https://github.com/scala/scala-dev/issues/811

**Review by lrytz — APPROVED** [review]
