### PR TITLE
[#11559] Fix HashMap.merged behaviour for case where left HashMap size=1

### LINKED ISSUE #11559: Poor behaviour in s.c.i.HashMap#merged (2.13.0)
If one of the maps in `s.c.i.HashMap#merged` (either `this` or `that`) has a single element, and the other has the key of that element, it will put the merged element into the other map without checking that the result of the merge function returns the same key; thus, if the merge function returns a different key, the resulting map will contain both its original mapping for the key in both maps and the mapping produced by the merge function.

For reference, I have copied the snippet covering the case where `this.size == 1`. You can see that `that.rootNode.updated(mergedK, ...) is called, but `k` is not removed if `k != mergedK`.

```scala
if (size == 1) {
  val payload@(k, v) = rootNode.getPayload(0)
  val originalHash = rootNode.getHash(0)
  val improved = improve(originalHash)

  if (that.rootNode.containsKey(k, originalHash, improved, 0)) {
    val thatPayload = that.rootNode.getTuple(k, originalHash, improved, 0)
    val (mergedK, mergedV) = mergef(payload, thatPayload)
    val mergedOriginalHash = mergedK.##
    val mergedImprovedHash = improve(mergedOriginalHash)
    new HashMap(that.rootNode.updated(mergedK, mergedV, mergedOriginalHash, mergedImprovedHash, 0, replaceValue = true))
  } else {
    new HashMap(that.rootNode.updated(k, v, originalHash, improved, 0, replaceValue = true))
  }
}
```

The result of the above snippet is the following behaviour:

```scala
scala> import scala.collection.immutable.HashMap
import scala.collection.immutable.HashMap

scala> HashMap("uh" -> "oh").merged(HashMap("uh" -> "oh"))((_, _) => "the other entry" -> "shouldn't be there")
res0: scala.collection.immutable.HashMap[String,String] = HashMap(the other entry -> shouldn't be there, uh -> oh)
```

It's possible that this behaviour is not a bug, given that the method is not spec-ed in any way and is free to do pretty much whatever it wants, but this behaviour seems at least undesirable and surprising.

### PR DESCRIPTION
**Pull request by joshlemer**
Fixes scala/bug#11559

### CODE REVIEW

File: src/library/scala/collection/immutable/HashMap.scala [hunk 1]
```diff
@@ -262,7 +262,7 @@ final class HashMap[K, +V] private[immutable] (private[immutable] val rootNode:
           val (mergedK, mergedV) = mergef(payload, thatPayload)
           val mergedOriginalHash = mergedK.##
           val mergedImprovedHash = improve(mergedOriginalHash)
-          new HashMap(that.rootNode.updated(mergedK, mergedV, mergedOriginalHash, mergedImprovedHash, 0, replaceValue = true))
+          new HashMap(that.rootNode.removed(thatPayload._1, originalHash, improved, 0).updated(mergedK, mergedV, mergedOriginalHash, mergedImprovedHash, 0, replaceValue = true))
```
Comment (NthPortal) [inline src/library/scala/collection/immutable/HashMap.scala:304]: does `removed` return `this` if neither `originalHash` nor `improved` match anything? if so, I think this is good. if not, I think it would be good to add a pre-check for that.

Comment (NthPortal) [reply src/library/scala/collection/immutable/HashMap.scala:304]: (I'm not in a position to check right now)

Comment (joshlemer) [reply src/library/scala/collection/immutable/HashMap.scala:304]: (yes it does turn `this` in that case)

File: test/junit/scala/collection/immutable/HashMapTest.scala [hunk 2]
```diff
@@ -135,4 +135,11 @@ class HashMapTest {
     assertEquals(hashMap.updatedWith(2)(noneAnytime), HashMap(1 -> "a"))
   }
 
+  @Test
+  def merged(): Unit = {
```
Comment (joshlemer) [inline test/junit/scala/collection/immutable/HashMapTest.scala]: should change the name fo the test to `t11559`

File: src/library/scala/collection/immutable/HashMap.scala (hunk 1 above)
Comment (diesalbla) [reply src/library/scala/collection/immutable/HashMap.scala:304]: For this specific case, could we add a test that checks for reference equality?

**Review by diesalbla — APPROVED** [review]
Perhaps adding a similar test to the 2.12 branch may be useful, as extra coverage _for free_.

**Review by lrytz — CHANGES_REQUESTED** [review]
@joshlemer I'm a bit late to the party...
  - Could you add a Scaladoc to the `merged` method, while you're at it?
  - Would it make sense increase test coverage by adding a scalacheck property (there's already `ImmutableChampHashMapProperties`)
  - And rename the test, as you suggested yourself

**Comment by NthPortal** [comment]
tangential, but it would be nice if all maps could be `merged`

**Comment by lrytz** [comment]
Yes, I was also wondering about the orphan `merged` method. Should we create a ticket to fix that in 2.14?

**Comment by joshlemer** [comment]
@lrytz Hey there, I hope to perform those change requests this weekend. There are actually already a few (4) property tests for HashMap#merged, but I guess they aren't that telling if this got through. I will have to think about if a better generator could improve them, or an other should be added, or what.

**Review by lrytz — APPROVED** [review]
Thank you!
